/** Actual source surface contacts for bounded neighbour exceptions. */
import{readFileSync,writeFileSync}from'node:fs';import{gunzipSync}from'node:zlib';import{nearest,levels}from'../assembly-support-review/triangles.mjs';import * as THREE from '../../../3d-viewer/vendor/three.module.js';import{prepareModelCatalogue,loadOfficialModel,disposeOfficialModel}from'../../../3d-viewer/city/official-model-assets.js';import{makeTerrainSampler}from'../../../3d-viewer/city/geo.js';
const read=p=>JSON.parse(readFileSync(p)),manifest=read('3d-viewer/city/data/manifest.json'),bundle=read('docs/astra-city/residual-support-review/terrain-bundle.json'),proposals=bundle.bundles.flatMap(b=>b.patches.map(p=>({row:p,data:read(p.path)}))),removed=new Set(proposals.flatMap(p=>p.row.replacesExistingManifestPatches||[])),terrain=read('3d-viewer/city/data/terrain.json');terrain.patches=manifest.terrainPatches.map(p=>read('3d-viewer/'+p.url));const old=makeTerrainSampler(terrain),after=makeTerrainSampler({...terrain,patches:[...manifest.terrainPatches.filter(p=>!removed.has(p.url)).map(p=>read('3d-viewer/'+p.url)),...proposals.map(p=>p.data)]}),buildings=new Map();for(const t of manifest.tiles)for(const b of read('3d-viewer/'+t.url).buildings)buildings.set(b.uid,b);
const sources=new Map();for(const row of read('docs/astra-city/residual-support-review/native-meshes.json').rows){const m=JSON.parse(gunzipSync(readFileSync(row.cache)));sources.set(row.uid,{...m,faces:[]});}
const lighting={night:{value:0},activity:{value:new THREE.Vector4(1,1,1,1)},retail:{value:1},elapsed:{value:0},shimmer:{value:0}};for(const path of manifest.officialModelCatalogues.map(u=>'3d-viewer/'+u))for(const e of prepareModelCatalogue(read(path),'http://review.local/'+path))if(e.uid==='landsd/324455:0'){const raw=readFileSync(path.slice(0,path.lastIndexOf('/')+1)+e.asset),m=await loadOfficialModel(e,buildings.get(e.uid),lighting,{fetcher:async()=>new Response(raw)});sources.set(e.uid,{...m.record.modelGeometry,faces:[]});disposeOfficialModel(m);}
for(const m of sources.values())for(let i=0;i<m.index.length;i+=3)m.faces.push(new THREE.Triangle(...[0,1,2].map(k=>new THREE.Vector3().fromArray(m.position,m.index[i+k]*3))));
const rows=[];for(const [uid,support]of [['landsd/179500:0','landsd/234162:0'],['landsd/272501:0','landsd/247062:0'],['landsd/251917:0','landsd/306084:0'],['landsd/251920:0','landsd/306084:0']]){const b=buildings.get(uid),points=b.rings.flatMap(r=>r.slice(1).flatMap((p,i)=>[p,[(p[0]+r[i][0])/2,(p[1]+r[i][1])/2]])),evidence=points.map(([x,z])=>({point:[x,b.base,z],nearestSupport:nearest(sources.get(support),new THREE.Vector3(x,b.base,z))}));rows.push({uid,support,samples:evidence.length,withinHalfMetre:evidence.filter(p=>p.nearestSupport<=.5).length,maxDistance:Math.max(...evidence.map(p=>p.nearestSupport)),evidence});}
const depot=sources.get('landsd/324455:0'),newBuried=[];let checked=0;for(let i=0;i<depot.faces.length;i++){const t=depot.faces[i],normal=t.getNormal(new THREE.Vector3());if(normal.y<=.25)continue;const points=[t.a,t.b,t.c,t.getMidpoint(new THREE.Vector3())],was=points.every(p=>p.y<old.height(p.x,p.z)-.5),now=points.every(p=>p.y<after.height(p.x,p.z)-.5);checked++;if(now&&!was)newBuried.push({triangle:i,area:t.getArea(),points:points.map(p=>({position:p.toArray(),beforeGround:old.height(p.x,p.z),afterGround:after.height(p.x,p.z)}))});}
const result={issue:'HKS-214',rows,depot:{uid:'landsd/324455:0',upwardTrianglesChecked:checked,newFullyBuriedUpwardTriangles:newBuried},policy:'Actual runtime source triangle distances and vertical terrain comparisons. Footprint envelope flags do not automatically imply missing native support.'};writeFileSync('docs/astra-city/residual-support-review/context-contacts.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,rows:rows.map(({evidence,...r})=>r)},null,2));
