/** Review-only native triangle cache, decoded through the real runtime loader. */
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import{gzipSync}from'node:zlib';import{createHash}from'node:crypto';import{resolve,dirname}from'node:path';
import * as THREE from '../../../3d-viewer/vendor/three.module.js';import{prepareModelCatalogue,loadOfficialModel,disposeOfficialModel}from'../../../3d-viewer/city/official-model-assets.js';
const read=p=>JSON.parse(readFileSync(p)),base='source-scripts/city/residual-support-review/',input=read(base+'input.json'),wanted=new Set(input.parts.map(p=>p.uid)),manifest=read('3d-viewer/city/data/manifest.json'),entries=new Map(),buildings=new Map(),out=[];
for(const path of ['source-scripts/city/landmark-preflight/snapshots/'+input.snapshotId+'/catalogue.json','source-scripts/city/residential-support-review/omitted-support/candidates/catalogue.json','source-scripts/city/residential-support-review/candidates/catalogue.json'])for(const e of prepareModelCatalogue(read(path),'http://review.local/catalogue.json'))if(wanted.has(e.uid))entries.set(e.uid,{e,path:resolve(dirname(path),path.includes('/snapshots/')?'assets':'',e.asset)});
for(const path of manifest.officialModelCatalogues.map(u=>'3d-viewer/'+u))for(const e of prepareModelCatalogue(read(path),'http://review.local/catalogue.json'))if(wanted.has(e.uid))entries.set(e.uid,{e,path:resolve(dirname(path),e.asset)});
for(const t of manifest.tiles)for(const b of read('3d-viewer/'+t.url).buildings)if(wanted.has(b.uid))buildings.set(b.uid,b);
const lighting={night:{value:0},activity:{value:new THREE.Vector4(1,1,1,1)},retail:{value:1},elapsed:{value:0},shimmer:{value:0}};mkdirSync(base+'mesh-cache',{recursive:true});
for(const uid of wanted){const{e,path}=entries.get(uid),raw=readFileSync(path),sha256=createHash('sha256').update(raw).digest('hex');if(sha256!==e.sha256)throw Error('Source changed '+uid);const loaded=await loadOfficialModel(e,buildings.get(uid),lighting,{fetcher:async()=>new Response(raw)}),g=loaded.record.modelGeometry,cache=base+'mesh-cache/'+uid.replace(/\W/g,'-')+'.json.gz';writeFileSync(cache,gzipSync(JSON.stringify({uid,sourcePath:path,sourceSHA256:sha256,position:Array.from(g.position),index:Array.from(g.index)})));out.push({uid,cache,sourcePath:path,sourceSHA256:sha256,cacheSHA256:createHash('sha256').update(readFileSync(cache)).digest('hex'),triangles:g.triangles});disposeOfficialModel(loaded);}
writeFileSync('docs/astra-city/residual-support-review/native-meshes.json',JSON.stringify({issue:'HKS-214',rows:out},null,2)+'\n');console.log(JSON.stringify({cached:out.length}));
