"""Approve the independently verified subset; keep source mismatch groups explicit."""
import json,pathlib,hashlib,shutil,copy
ROOT=pathlib.Path(__file__).resolve().parents[3];HERE=pathlib.Path(__file__).resolve().parent;DOC=ROOT/'docs/astra-city/residual-support-review';read=lambda p:json.loads(p.read_bytes());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();write=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n')
uids={'landsd/'+str(n)+':0'for n in [234162,265478,55976,55978,80800,101899,106992,225895,225917,179500]};cat=read(HERE/'candidates/catalogue.json');extra=read(HERE/'extras/catalogue.json');frames={r['uid']:(r,DOC/'framing')for r in read(DOC/'framing/report.json')['rows']};frames.update({r['uid']:(r,DOC/'extras-framing')for r in read(DOC/'extras-framing/report.json')['rows']});rows=[];approved=[];folder=HERE/'approved';folder.mkdir(exist_ok=True)
notes={'landsd/234162:0':'Island Resort native mall podium: curved perimeter, courtyard openings, stepped roof and connected tower bases inspected against native terrain.', 'landsd/265478:0':'Pacifica native mall: curved wings, open supported corners and rooftop plant inspected; exact native ground clears visible surfaces.', 'landsd/80800:0':'Wplace narrow native shaft and asymmetric rooftop service volume inspected between existing neighbours; camera-safe close view and isolated source confirm geometry.', 'landsd/179500:0':'Exact-CSUID lift/service shaft with recessed upper roof and stepped lower section, aligned with existing elevated walkways. Native rim clears native terrain by 0.023–0.037 m.'}
for m in cat['models']+extra['models']:
 if m['uid']not in uids:continue
 m=copy.deepcopy(m);u=m['uid'];fr,path=frames[u];assert fr['framingOutcome']=='source-part-inspectable' and all(v['final']['clear']for v in fr['views']);note=notes.get(u,'Island Resort tower shaft, recessed crown, service roof and lower native transition inspected in the complete assembly and isolated source view. Shared mall support is exact native geometry; source elevations unchanged.')
 m.update(identityReviewApproved=True,sourceIdentityReviewed=True,placementReviewed=True,publicationApproved=True,proposedIdentity=False,knownPlacementHold=None,reviewIssue='HKS-214',wholeLandmarkComplete=False,architectureReview=note)
 m.setdefault('supportDependencies',[]);src=(HERE/('extras'if u=='landsd/179500:0'else'candidates')/m['asset']);assert sha(src)==m['sha256'];shutil.copyfile(src,folder/m['asset']);approved.append(m);rows.append({'uid':u,'status':'approved-for-integration','modelSHA256':m['sha256'],'observation':note,'wholeLandmarkComplete':False,'images':[{'path':str((path/v['file']).relative_to(ROOT)),'sha256':v['sha256']}for v in fr['views']]})
assert {m['uid']for m in approved}==uids
for m in approved:
 for d in m['supportDependencies']:assert d['state']!='candidate'or d['uid']in uids
cat['models']=approved;cat['counts']['packedModels']=len(approved);write(folder/'catalogue.json',cat)
bundle=read(DOC/'terrain-bundle.json');patches=[p for b in bundle['bundles']for p in b['patches']if p['uids']==['landsd/234162:0']or p['uids']==['landsd/265478:0']];assert len(patches)==2
plan={'areas':[{'area':'Reviewed Island Resort, Pacifica and Wplace source components','catalogue':str((folder/'catalogue.json').relative_to(ROOT)),'destination':'city/data/official-models/residual-native-20260909/catalogue.json'}],'topLevelTerrainPatches':[{'source':p['path'],'sha256':p['sha256'],'destination':'city/data/terrain-residual-'+p['uids'][0].split('/')[1].replace(':','-')+'.json','resolution':1,'area':'Native LandsD terrain supporting '+p['uids'][0]}for p in patches]};write(HERE/'publication-plan.json',plan)
inputs=['source-scripts/city/residual-support-review/approved/catalogue.json','source-scripts/city/residual-support-review/publication-plan.json','docs/astra-city/residual-support-review/support-terrain.json','docs/astra-city/residual-support-review/neighbours.json','docs/astra-city/residual-support-review/framing/report.json','docs/astra-city/residual-support-review/extras-framing/report.json','docs/astra-city/residual-support-review/extras-audit.json','docs/astra-city/residual-support-review/extras-native.json']+[p['path']for p in patches]
result={'issue':'HKS-214','status':'approved-for-integration','published':False,'verticalScale':1,'approvedNewUids':sorted(uids),'rows':rows,'inputHashes':{p:sha(ROOT/p)for p in inputs},'heldGroups':[{'group':'LOHAS extension and 13 source components','reason':'Native272501 low ancillary block remains 1.867–1.871m above exact government terrain; missing source support or explicit estimated foundation decision required. Two unsurveyed canopy base estimates are prepared but excluded until this terrain group is accepted.'},{'group':'Festival306084','reason':'Native podium itself visible, but terrain exposes unsupported retained tower bases251917/251920; exact candidate podium contact3/584 and0/542. No publication.'},{'group':'Other residual parts','reason':'See decisions.json, support-terrain.json and native-audit(-adjacent).json for unresolved contacts, ground penetration or missing neighbouring assemblies.'}],'limits':['Approval concerns exact source components, not whole estates or regions.','Window treatment is illustrative, not surveyed facade material or floor count.','Neighbour checks sample footprint edges and interior centres; native model geometry checks and browser views complement those finite tests.','LOHAS preservation and estimated base proposals remain working candidates, absent from this publication plan.']};write(HERE/'approval.json',result);write(DOC/'approval.json',result);print(json.dumps({'approved':len(uids),'terrainPatches':len(patches),'plan':str((HERE/'publication-plan.json').relative_to(ROOT))}))
