"""Publishable Grand Promenade closure; source metadata migrations remain atomic."""
import json,pathlib,hashlib,copy,shutil,sys
ROOT=pathlib.Path(__file__).resolve().parents[3];HERE=pathlib.Path(__file__).resolve().parent;DEST=HERE/'grand';DOC=ROOT/'docs/astra-city/residual-support-review/grand';read=lambda p:json.loads(p.read_bytes());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();write=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n');sys.path.insert(0,str(ROOT/'source-scripts/city/shared-modelling'));import reservations
for path in ['/tmp/astra-grand-lease.json','/tmp/astra-grand-neighbours-lease.json']:
 lease=read(pathlib.Path(path));assert reservations.owns(lease);reservations.heartbeat(lease)
fr=read(DOC/'framing/report.json');nf=read(DOC/'neighbour-framing/report.json');assert len(fr['rows'])==6 and len(nf['rows'])==1
for report in [fr,nf]:
 assert not report['errors']
 for row in report['rows']:assert row['framingOutcome']=='source-part-inspectable'and not row['runtimeStats']['errors'] and not row['runtimeStats']['supportHolds']
for mode in ['canopies','canopies-isolated']:
 report=read(DOC/mode/'report.json');assert len(report['rows'])==2 and not report['errors']and all(r['clear']for r in report['rows'])
frames={r['uid']:(r,DOC/'framing')for r in fr['rows']};frames.update({r['uid']:(r,DOC/'neighbour-framing')for r in nf['rows']});support={r['uid']:r for r in read(DOC/'support-neighbour.json')['rows']};cat=read(DEST/'candidates/catalogue.json');old=read(DOC/'installed-context.json');batch=ROOT/'source-scripts/city/landmark-acquisition/batches/grand-promenade-neighbour-20260909';hq=read(batch/'candidates/catalogue.json')['models'][0];cat['models'].append(hq);new=[];rows=[];folder=DEST/'approved';folder.mkdir(exist_ok=True)
for m in cat['models']:
 u=m['uid'];frame,path=frames[u];r=support[u]['rimCounts'];assert r['samples']==r['terrainContact']+r['otherTriangleContact']and not r['noContact']and not r['belowTerrain'];note='Native Grand Promenade podium: open roof frame, internal courts, stepped decks and raised tower sockets inspected with all five native shafts.'if u=='landsd/229653:0'else 'Marine Police Headquarters exact native source: rounded seaward wing, sloped principal roof, terraces and rooftop service equipment inspected against the final coastal terrain. Native low-rim contact extends beyond the old simplified footprint.'if u=='landsd/83999:0'else 'Native Grand Promenade tower: articulated crown, upper setbacks and shaft inspected in complete context and isolated view, with exact native triangle contact to the shared podium.'
 rows.append({'uid':u,'status':'approved-metadata-only'if u in old else'approved-for-integration','sourceSHA256':m['sha256'],'rim':r,'observation':note,'images':[{'path':str((path/v['file']).relative_to(ROOT)),'sha256':v['sha256']}for v in frame['views']]})
 if u in old:continue
 m=copy.deepcopy(m);m.update(identityReviewApproved=True,sourceIdentityReviewed=True,placementReviewed=True,publicationApproved=True,proposedIdentity=False,knownPlacementHold=None,reviewIssue='HKS-214',wholeLandmarkComplete=False,architectureReview=note);m.setdefault('supportDependencies',[]);src=(batch/'candidates'if u=='landsd/83999:0'else DEST/'candidates')/m['asset'];assert sha(src)==m['sha256'];shutil.copyfile(src,folder/m['asset']);new.append(m)
cat['models']=new;cat['counts']['packedModels']=len(new);assert len(new)==4;write(folder/'catalogue.json',cat)
review=read(DEST/'dependency-replacements.json');review['contactReportSHA256']=sha(ROOT/review['contactReport']);review['requiresNewNativeUids']=[m['uid']for m in new]
for c in review['catalogues']:
 current=read(ROOT/c['source']);byuid={m['uid']:m for m in current['models']}
 for uid in c['models']:assert byuid[uid]==old[uid]['model'],'Existing tower changed during review'
 c['originalReviewCatalogueSHA256']=c['oldSHA256'];c['oldSHA256']=sha(ROOT/c['source'])
write(DEST/'dependency-replacements.json',review)
est=read(DEST/'estimated-bases.json');inputs=[DOC/'support-neighbour.json',DOC/'framing/report.json',DOC/'neighbour-framing/report.json',DOC/'neighbours.json',DOC/'canopies/report.json',DOC/'canopies-isolated/report.json',DEST/'dependency-replacements.json',DEST/'estimated-bases.json',folder/'catalogue.json',DEST/'terrain-patches/support-native-229653-0.json'];approval={'issue':'HKS-214','status':'approved-for-integration','published':False,'verticalScale':1,'approvedNewUids':[m['uid']for m in new],'approvedMetadataUids':list(old),'approvedEstimatedUids':[e['uid']for e in est['buildings']],'rows':rows,'inputHashes':{str(p.relative_to(ROOT)):sha(p)for p in inputs},'sourceStats':{'newHeadquartersSourceBytes':1473863,'headquartersPackedBytes':hq['bytes'],'lowRimSamples':sum(r['rim']['samples']for r in rows),'nativeGeometryChanged':False},'terrain':{'nativeCoveredGridNodes':78961,'totalGridNodes':78961,'boundarySamples':1124,'maximumBoundaryChangeMetres':4.285715133889312e-7,'affectedFootprints':53},'estimatedBases':est['buildings'],'neighbourResolution':'The simplistic83999 envelope warning is superseded by its actual exact-CSUID source model and inspected native foundation. Three low-rim native vertices are0.23–0.31m below local terrain; remaining model and coastal frontage visually inspected. No foundation or geometry invented.','limits':['Source components and supported assembly, not all surrounding neighbourhoods, are approved.','Window treatments and the two unsurveyed3m canopy forms remain illustrative.','Native Headquarters apex20.594m differs from old footprint top14.3m; detailed source roof/service geometry is preserved without scaling.','Initial staging omitted catalogue-count adjustment when replacing existing tower metadata; final browser evidence reran with full surrounding catalogue and zero runtime catalogue errors.']};write(DEST/'approval.json',approval);write(DOC/'approval.json',approval)
p=DEST/'terrain-patches/support-native-229653-0.json';plan={'areas':[{'area':'Grand Promenade native support assembly and adjacent Marine Police Headquarters','catalogue':str((folder/'catalogue.json').relative_to(ROOT)),'destination':'city/data/official-models/grand-native-20260909/catalogue.json','estimates':[str((DEST/'estimated-bases.json').relative_to(ROOT))]}],'topLevelTerrainPatches':[{'source':str(p.relative_to(ROOT)),'sha256':sha(p),'destination':'city/data/terrain-grand-native-20260909.json','resolution':1,'area':'Grand Promenade native government terrain'}],'dependencyReviews':[{'path':str((DEST/'dependency-replacements.json').relative_to(ROOT)),'sha256':sha(DEST/'dependency-replacements.json'),'visualApproval':{'path':str((DEST/'approval.json').relative_to(ROOT)),'sha256':sha(DEST/'approval.json')}}]};write(DEST/'publication-plan.json',plan);print(json.dumps({'models':4,'nativeMetadataMigrations':3,'estimatedBases':2,'lowRimSamples':approval['sourceStats']['lowRimSamples']}))
