"""Finish the smaller Capitol package with explicit estimated canopy reconciliation."""
import json,pathlib,hashlib,copy,shutil,sys
ROOT=pathlib.Path(__file__).resolve().parents[3];HERE=pathlib.Path(__file__).resolve().parent;DEST=HERE/'capitol';DOC=ROOT/'docs/astra-city/residual-support-review/capitol';read=lambda p:json.loads(p.read_bytes());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();write=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n');sys.path.insert(0,str(ROOT/'source-scripts/city/assembly-support-review'));import terrain_patches as t
cat=read(DEST/'catalogue.json');fr={r['uid']:r for r in read(DOC/'framing/report.json')['rows']};support={r['uid']:r for r in read(DOC/'support.json')['rows']};est=read(DEST/'estimated-bases.json');native=read(DOC/'context-contacts.json');assert not native['depot']['newFullyBuriedUpwardTriangles'];assert all(r['clear']for r in read(DOC/'canopies-isolated/report.json')['rows']);sampler=t.fine.DemSampler(read(DEST/'terrain.json'),rendered=True)
from shapely.geometry import Polygon
mf=read(ROOT/'3d-viewer/city/data/manifest.json');byuid={}
for tile in mf['tiles']:
 for b in read(ROOT/'3d-viewer'/tile['url'])['buildings']:
  if b['uid']in {e['uid']for e in est['buildings']}:byuid[b['uid']]=b
for e in est['buildings']:
 b=byuid[e['uid']];assert b['baseHeightHKPD']is None and b['topHeightHKPD']is None;actual=sampler.extrema(Polygon(b['rings'][0],b['rings'][1:]));assert actual==e['terrain'];assert e['base']==actual['min']and e['height']==b['height']==3
folder=DEST/'approved';folder.mkdir(exist_ok=True);rows=[]
for m in cat['models']:
 u=m['uid'];assert all(v['final']['clear']for v in fr[u]['views']);r=support[u]['rimCounts'];assert r['samples']==r['terrainContact']+r['otherTriangleContact']and not r['belowTerrain']and not r['noContact'];note='Native Capitol podium curved perimeter, stepped roof and tower sockets inspected with supported tower shafts.'if u=='landsd/262368:0'else 'Native narrow service/stair tower with staggered projections and roof recess inspected at unchanged source elevations.'if u=='landsd/111608:0'else 'Native Capitol tower shaft, service crown and exact native podium connection inspected in the complete and isolated assembly views.';m.update(identityReviewApproved=True,sourceIdentityReviewed=True,placementReviewed=True,publicationApproved=True,proposedIdentity=False,knownPlacementHold=None,reviewIssue='HKS-214',wholeLandmarkComplete=False,architectureReview=note);shutil.copyfile(DEST/m['asset'],folder/m['asset']);rows.append({'uid':u,'status':'approved-for-integration','sourceSHA256':m['sha256'],'observation':note,'rim':r,'images':[{'path':str((DOC/'framing'/v['file']).relative_to(ROOT)),'sha256':v['sha256']}for v in fr[u]['views']]})
write(folder/'catalogue.json',cat);patch=read(DEST/'terrain.json');old=patch['meta']['preservedTerrain'];plan={'areas':[{'area':'Capitol source assembly with bounded native terrain','catalogue':str((folder/'catalogue.json').relative_to(ROOT)),'destination':'city/data/official-models/capitol-native-20260909/catalogue.json','estimates':[str((DEST/'estimated-bases.json').relative_to(ROOT))]}],'topLevelTerrainPatches':[{'source':str((DEST/'terrain.json').relative_to(ROOT)),'sha256':sha(DEST/'terrain.json'),'destination':'city/data/terrain-capitol-native-20260909.json','resolution':1,'area':'Capitol native terrain retaining every Club Galaxy node','replaces':{'url':old['url'],'sha256':old['sha256']}}]};write(DEST/'publication-plan.json',plan)
inputs=['framing/report.json','support.json','neighbours.json','preservation.json','context-contacts.json','canopies/report.json','canopies-isolated/report.json'];evidence={str((DOC/f).relative_to(ROOT)):sha(DOC/f)for f in inputs}
for p in [DEST/'terrain.json',DEST/'estimated-bases.json',DEST/'approved/catalogue.json',DEST/'publication-plan.json']:evidence[str(p.relative_to(ROOT))]=sha(p)
result={'issue':'HKS-214','status':'approved-for-integration','published':False,'ledgerSnapshot':'f61930a5e4dfa572','approvedNewUids':[m['uid']for m in cat['models']],'approvedEstimatedUids':[e['uid']for e in est['buildings']],'verticalScale':1,'rows':rows,'inputHashes':evidence,'terrain':{'preservedOldNodes':29751,'boundarySamples':1404,'maximumBoundaryChangeMetres':4.285716492802294e-7,'affectedFootprints':43,'excludesUnresolvedAncillary':'landsd/272501:0'},'estimatedCanopyReview':{'status':'approved-explicit-estimates','bothHeightsRemain':3,'bothSurveyedBasesRemain':None,'bothSurveyedTopsRemain':None,'bases':[{'uid':e['uid'],'before':e['previousBase'],'after':e['base'],'terrain':e['terrain']}for e in est['buildings']],'normalScene':'109723 visible with grounded posts;311673 remains behind existing depot/podium, so no unoccluded full-scene claim.','isolatedRuntimeGeometry':'Both exact existing procedural canopy geometries inspected against final terrain; posts reach or enter terrain and roofs remain above it. Existing footbridge geometry retained.'},'limits':['Six source components are accepted, not the whole Capitol/LOHAS estate.','Other seven LOHAS candidates from the larger patch remain held for independent terrain work.','A basic depot envelope warning is superseded by9640 actual native upward triangles with zero newly buried surfaces.','Window pattern and unsurveyed canopies remain explicit illustrations/estimates.']};write(DEST/'approval.json',result);write(DOC/'approval.json',result);print(json.dumps({'approvedModels':6,'estimatedBases':2,'lowRimSamples':sum(r['rim']['samples']for r in rows)}))
