"""Package reviewed Convention Plaza native podium/tower, leaving hillside part separate."""
import pathlib,json,hashlib,shutil,sys
R=pathlib.Path(__file__).resolve().parents[3];H=pathlib.Path(__file__).resolve().parent/'foundation';D=R/'docs/astra-city/residual-support-review/foundation';read=lambda p:json.loads(p.read_bytes());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();write=lambda p,x:p.write_text(json.dumps(x,indent=2)+'\n');sys.path.insert(0,str(R/'source-scripts/city/shared-modelling'));import reservations
assert reservations.owns(read(pathlib.Path('/tmp/astra-residual-foundation-lease.json')))
ids={'landsd/255200:0','landsd/255386:0'};cat=read(H/'catalogue.json');cat['models']=[m for m in cat['models']if m['uid']in ids];cat['counts']['packedModels']=2;cat['area']='Convention Plaza native podium and Office Tower';cat['loadingPolicy']='Reviewed native source geometry at unchanged elevations; Office Tower requires native Dynasty Club podium.';dest=H/'approved';dest.mkdir(exist_ok=True)
frames={r['uid']:r for r in read(D/'framing/report.json')['rows']};surfaces={r['uid']:r for r in read(D/'current-terrain-surfaces.json')['rows']};support={r['uid']:r for r in read(R/'docs/astra-city/residual-support-review/support-terrain.json')['rows']};rows=[]
for m in cat['models']:
 assert sha(H/m['asset'])==m['sha256'];shutil.copyfile(H/m['asset'],dest/m['asset']);f=frames[m['uid']];s=surfaces[m['uid']];assert all(v['final']['clear']for v in f['views'])and not f['runtimeStats']['errors']and not any(h['uid']in ids for h in f['runtimeStats']['supportHolds']);assert not s['fullyBuriedUpwardTriangles']and not s['projectedRoofsBelowTerrain'];rows.append({'uid':m['uid'],'status':'approved-for-integration','sourceSHA256':m['sha256'],'observation':('Broad curved podium, stepped roof and service volumes remain visible. Native terrain also places79/486 lowest boundary samples below grade (up to3.374m); no complete upward native face or sampled roof is buried in either native terrain or current terrain. This is source-supported below-grade geometry, not a model offset.'if m['uid'].endswith('255200:0')else'Office shaft with recessed framed crown; all9 low-rim samples contact the native podium. Both normal and isolated views are clear.'),'currentTerrainSurfaceCheck':s,'runtimeSupportHolds':f['runtimeStats']['supportHolds'],'images':[{'path':str((D/'framing'/v['file']).relative_to(R)),'sha256':v['sha256']}for v in f['views']]})
write(dest/'catalogue.json',cat);approval={'issue':'HKS-214','status':'approved-for-integration','published':False,'ledgerSnapshot':'f61930a5e4dfa572','approvedNewUids':sorted(ids),'verticalScale':1,'rows':rows,'evidence':[{'path':str(p.relative_to(R)),'sha256':sha(p)}for p in [D/'framing/report.json',D/'native-terrain-evidence.json',D/'current-terrain-surfaces.json',R/'docs/astra-city/residual-support-review/support-terrain.json']],'limits':['Two source components, not all Convention Plaza or a completed region.','Window treatment is illustrative. Native source geometry and elevations are unchanged.','No terrain changes are required for these two; raw source230686 remains separate pending exact hillside terrain review.','Elevated wider podium view retains10 unrelated source groups as fallbacks because the existing memory/triangle budget is full; both reviewed components stay active without errors.','Parent must verify installed picking/collision/performance after integration.']};write(H/'approval.json',approval);write(H/'publication-plan.json',{'areas':[{'area':cat['area'],'catalogue':str((dest/'catalogue.json').relative_to(R)),'destination':'city/data/official-models/convention-native-20260909/catalogue.json'}]});write(D/'decisions.json',approval)
