"""Bounded source/native-terrain review of below-grade residual components; no geometry edits."""
import pathlib,json,sys,uuid,hashlib,shutil
ROOT=pathlib.Path(__file__).resolve().parents[3];HERE=pathlib.Path(__file__).resolve().parent;DEST=HERE/'foundation';DOC=ROOT/'docs/astra-city/residual-support-review/foundation';DEST.mkdir(exist_ok=True);DOC.mkdir(exist_ok=True);read=lambda p:json.loads(p.read_bytes());write=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n');sys.path.insert(0,str(ROOT/'source-scripts/city/shared-modelling'));import reservations
uids={'landsd/230686:0','landsd/255200:0','landsd/255386:0'};r=reservations.claim('residual-foundations-'+str(uuid.uuid4()),['building:'+u for u in uids],batch='HKS-214-native-foundation-review');assert r['ok'],r;pathlib.Path('/tmp/astra-residual-foundation-lease.json').write_text(json.dumps(r['reservation'],default=str));parts=[p for p in read(HERE/'input.json')['parts']if p['uid']in uids];sources={r['uid']:r for r in read(ROOT/'docs/astra-city/residual-support-review/native-meshes.json')['rows']};cat=read(HERE/'candidates/catalogue.json');cat['models']=[]
for p in parts:
 m=p['candidate'].copy();m['priority']='landmark';m['supportDependencies']=[{'uid':'landsd/255200:0','state':'candidate'}]if p['uid']=='landsd/255386:0'else[];src=pathlib.Path(sources[p['uid']]['sourcePath']);assert hashlib.sha256(src.read_bytes()).hexdigest()==m['sha256'];shutil.copyfile(src,DEST/m['asset']);cat['models'].append(m)
cat['counts']['packedModels']=3;write(DEST/'catalogue.json',cat);write(DEST/'selection.json',{'snapshot':'f61930a5e4dfa572','parts':[{'uid':p['uid'],'name':p['name'],'landmarks':p['landmarkIds']}for p in parts]});write(DOC/'terrain-bundle.json',{'bundles':[]});write(DEST/'uids.json',sorted(uids))
s=(HERE/'browser.mjs').read_text().replace('source-scripts/city/residual-support-review/visual-selection.json','source-scripts/city/residual-support-review/foundation/selection.json').replace("base='source-scripts/city/residual-support-review/candidates/'","base='source-scripts/city/residual-support-review/foundation/'").replace('docs/astra-city/residual-support-review/framing/','docs/astra-city/residual-support-review/foundation/framing/').replace('docs/astra-city/residual-support-review/terrain-bundle.json','docs/astra-city/residual-support-review/foundation/terrain-bundle.json');(HERE/'foundation-browser.generated.mjs').write_text(s)
native=[p for p in read(ROOT/'docs/astra-city/residual-support-review/native-audit.json')['rows']if p['uid']in uids and p['uid']!='landsd/230686:0'];native+=[p for p in read(ROOT/'docs/astra-city/residual-support-review/native-audit-adjacent.json')['rows']if p['uid']=='landsd/230686:0'];write(DOC/'native-terrain-evidence.json',{'rows':native,'policy':'Exact native model and native TIN inputs unchanged. This report provides source context, not automatic architectural acceptance.'});print(json.dumps({'models':3,'nativeRoofBelowTerrain':{p['uid']:p['nativeRoofBelowTerrainSamples']for p in native}}))
