"""Stage the omitted Grand Hall via established range fetcher, matcher and packer."""
import gzip,hashlib,importlib.util,json,pathlib,sys
HERE=pathlib.Path(__file__).resolve().parent;ROOT=HERE.parents[2];WORK=HERE/'existing-work-grandhall';OUT=HERE/'compact-grandhall'
def read(p):return json.loads(p.read_bytes())
def write(p,d):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
def module(n,p):
 s=importlib.util.spec_from_file_location(n,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
WORK.mkdir(parents=True,exist_ok=True);write(WORK/'index.json',read(HERE/'index.json'))
module('grandhall_fetch',HERE.parent/'mui-wo-models/fetch.py').fetch_tiles(WORK,['9-SE-21B'],['BUILDING/B085751299501063C0/','TERRAIN'])
sys.path.insert(0,str(ROOT/'docs/astra-city/mui-wo-buildings/review'));from prepare_model_sample import stage
folder=WORK/'sources/9-SE-21B';d=read(folder/'download.json');archive=folder/'9-SE-21B.zip';assert hashlib.sha256(archive.read_bytes()).hexdigest()==d['sha256'];sf=WORK/'staged/9-SE-21B';manifest=stage(archive,d,HERE/'official-selection.json.gz',sf);spec=next(m for m in manifest['models'] if m['id']=='B085751299501063C0');assert spec['officialBuildingCSUIDs']==['0857512995T20141029']
pack=module('grandhall_pack',HERE.parent/'central-completion/pack_models.py').pack;data,stats=pack(sf/spec['sourceEntry']);raw=gzip.compress(data,mtime=0);asset=OUT/'models/B085751299501063C0.glb.gz';asset.parent.mkdir(parents=True,exist_ok=True);asset.write_bytes(raw)
record={'uid':'landsd/238482:0','buildingCSUID':'0857512995T20141029','objectId':238482,'modelId':spec['id'],'sourceTile':manifest['tile'],'sourceTileRevision':manifest['tileRevision'],'worldBounds':spec['worldBounds'],'triangles':spec['triangles'],'recordedBaseHeight':448.4,'recordedTopHeight':478.8,'structureType':'Tower','label':'Grand Hall of Ten Thousand Buddhas','priority':'landmark','placementReviewed':False,'asset':str(asset.relative_to(OUT)),'encoding':'gzip','bytes':len(raw),'glbBytes':len(data),'decodedGeometryBytes':stats['decodedGeometryBytes'],'indexedVertices':stats['vertices'],'sha256':hashlib.sha256(raw).hexdigest()}
counts={'catalogueModels':1,'packedModels':1,'compressedBytes':len(raw),'packedTriangles':stats['triangles']};write(OUT/'catalogue.json',{'schemaVersion':1,'kind':'staged-official-model-catalogue','datasetId':'landsd_rcd_1742809441342_98380','area':'Grand Hall of Ten Thousand Buddhas','crs':'EPSG:2326','verticalDatum':'Hong Kong Principal Datum','rootTranslation':[-834500,0,816500],'counts':counts,'models':[record]});write(OUT/'catalogue-index.json',{'models':1,'catalogues':['catalogue.json']});write(OUT/'proofs.json',{'counts':counts,'models':[{'uid':record['uid'],'sourceManifest':str((sf/'manifest.json').relative_to(ROOT)),'sourceEntry':str((sf/spec['sourceEntry']).relative_to(ROOT)),'sourceHashes':spec['sourceHashes'],'officialMatches':spec['officialMatches'],'sourceArchiveSHA256':manifest['sourceArchiveSha256'],'nativeBaseTop':[spec['worldBounds'][0][1],spec['worldBounds'][1][1]],'reasonPreviouslyMissing':'Explicit landmark list omitted different building name; processing script followed the incomplete list.','placementReviewed':False}],'aiCalls':0});print(json.dumps({'counts':counts,'model':record,'matches':spec['officialMatches'],'transferredBytes':d['transferredBytes']},indent=2))
