"""Build the city's small inverse-projection grid; no runtime network/library.

EPSG:2326 Hong Kong 1980 Grid -> EPSG:4326 WGS 84, with the same local origin
as the terrain pipeline. Bilinear interpolation is validated against direct
PROJ transformations on cell interiors, bounds, and deterministic random points.
"""
import hashlib,json,math,pathlib,random
import pyproj
from pyproj import Transformer,Geod

ROOT=pathlib.Path(__file__).resolve().parents[2]
CITY=ROOT/'3d-viewer/city'
SPACING=5000

def main():
 terrain=json.loads((CITY/'data/terrain.json').read_text())
 g=terrain['meta']['georef'];origin=terrain['meta']['origin']
 x0=g['bE']-origin[0];x1=x0+(terrain['w']-1)*g['aE']
 z0=origin[1]-g['bN'];z1=z0-(terrain['h']-1)*g['aN']
 nx=math.ceil((x1-x0)/SPACING)+1;nz=math.ceil((z1-z0)/SPACING)+1
 dx=(x1-x0)/(nx-1);dz=(z1-z0)/(nz-1)
 transform=Transformer.from_crs('EPSG:2326','EPSG:4326',always_xy=True)
 geodesic=Geod(ellps='WGS84')
 def exact(x,z):
  lon,lat=transform.transform(x+origin[0],origin[1]-z)
  return [round(lat,12),round(lon,12)]
 nodes=[exact(x0+i*dx,z0+j*dz) for j in range(nz) for i in range(nx)]
 def interpolate(x,z):
  u=(x-x0)/dx;v=(z-z0)/dz;i=min(nx-2,max(0,math.floor(u)));j=min(nz-2,max(0,math.floor(v)));u-=i;v-=j
  a,b,c,d=nodes[j*nx+i],nodes[j*nx+i+1],nodes[(j+1)*nx+i],nodes[(j+1)*nx+i+1]
  return [a[k]*(1-u)*(1-v)+b[k]*u*(1-v)+c[k]*(1-u)*v+d[k]*u*v for k in [0,1]]
 points=[]
 for j in range(nz-1):
  for i in range(nx-1):
   for u in [0,.25,.5,.75,1]:
    for v in [0,.25,.5,.75,1]:points.append((x0+(i+u)*dx,z0+(j+v)*dz))
 rnd=random.Random(20260906)
 points += [(rnd.uniform(x0,x1),rnd.uniform(z0,z1)) for _ in range(20000)]
 errors=[]
 for x,z in points:
  a,b=exact(x,z),interpolate(x,z);errors.append(geodesic.inv(a[1],a[0],b[1],b[0])[2])
 maximum=max(errors)
 if maximum>.25:raise ValueError(f'Observer interpolation error {maximum:.6f} m exceeds 0.25 m')
 grid={'origin':origin,'bounds':[x0,z0,x1,z1],'width':nx,'height':nz,'step':[dx,dz],'nodes':nodes}
 text='// Generated by source-scripts/city/build_observer.py; see docs/astra-city/OBSERVER-PROJECTION.md.\n'
 text+='export const OBSERVER_GRID='+json.dumps(grid,separators=(',',':'))+';\n'
 (CITY/'observer-grid.js').write_text(text)
 reference=[(x0,z0),(x1,z0),(x0,z1),(x1,z1),(0,0),(x0,(z0+z1)/2),(x1,(z0+z1)/2),((x0+x1)/2,z0),((x0+x1)/2,z1)]
 rnd=random.Random(23264326)
 reference += [(round(rnd.uniform(x0,x1),3),round(rnd.uniform(z0,z1),3)) for _ in range(32)]
 samples=[{'x':x,'z':z,'lat':exact(x,z)[0],'lon':exact(x,z)[1]} for x,z in reference]
 (CITY/'tests/observer-reference.json').write_text(json.dumps(samples,indent=2)+'\n')
 metadata={'sourceCRS':'EPSG:2326','targetCRS':'EPSG:4326','axisInput':'easting,northing','worldCoordinates':'x=easting-834500; z=816500-northing','operation':transform.description,'operationReportedAccuracyMetres':transform.accuracy,'pyprojVersion':pyproj.__version__,'projVersion':pyproj.proj_version_str,'terrainGeoref':g,'origin':origin,'bounds':grid['bounds'],'gridShape':[nx,nz],'stepMetres':grid['step'],'validationPoints':len(points),'validationDescription':'5x5 points per grid cell including boundaries, plus 20000 uniform points with seed 20260906','maxInterpolationErrorMetres':maximum,'meanInterpolationErrorMetres':sum(errors)/len(errors),'runtimeBytes':len(text.encode()),'runtimeSha256':hashlib.sha256(text.encode()).hexdigest(),'limit':'Interpolation error is measured against PROJ, not independent survey accuracy. The CRS operation itself reports 1 metre accuracy.'}
 (ROOT/'docs/astra-city/observer-projection-verification.json').write_text(json.dumps(metadata,indent=2)+'\n')
 print(json.dumps(metadata,indent=2))

if __name__=='__main__':main()
