/** Audit actual native contacts before replacing an installed surveyed-support dependency. */
import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import * as THREE from '../../../3d-viewer/vendor/three.module.js';
import{prepareModelCatalogue,loadOfficialModel,disposeOfficialModel}from'../../../3d-viewer/city/official-model-assets.js';import{nearest}from'../assembly-support-review/triangles.mjs';
const root=new URL('../../../',import.meta.url),read=p=>JSON.parse(readFileSync(new URL(p,root))),sha=p=>createHash('sha256').update(readFileSync(new URL(p,root))).digest('hex'),manifest=read('3d-viewer/city/data/manifest.json'),assemblies=[{podium:'landsd/281182:0',towers:['landsd/59930:0','landsd/59982:0','landsd/59984:0']}],uids=new Set(assemblies.flatMap(a=>[a.podium,...a.towers])),entries=new Map(),records=new Map(),geometry=new Map(),catalogues=[];
for(const path of manifest.officialModelCatalogues.map(p=>'3d-viewer/'+p).concat(['source-scripts/city/residential-support-review/review-candidates/catalogue.json'])){
 const c=read(path),directory=path.slice(0,path.lastIndexOf('/')+1);for(const e of prepareModelCatalogue(c,'http://review.local/'+path))if(uids.has(e.uid)&&!entries.has(e.uid))entries.set(e.uid,{e,path,directory});if(c.models.some(m=>uids.has(m.uid)))catalogues.push({path,sha256:sha(path)});
}
for(const tile of manifest.tiles)for(const b of read('3d-viewer/'+tile.url).buildings)if(uids.has(b.uid))records.set(b.uid,b);
const lighting={night:{value:1},activity:{value:new THREE.Vector4(1,1,1,1)},retail:{value:1},elapsed:{value:0},shimmer:{value:0}};
for(const uid of uids){const{e,path,directory}=entries.get(uid),raw=readFileSync(new URL(directory+e.asset,root));if(createHash('sha256').update(raw).digest('hex')!==e.sha256)throw Error('Asset changed');const model=await loadOfficialModel(e,records.get(uid),lighting,{fetcher:async()=>new Response(raw)}),{position,index}=model.record.modelGeometry,faces=[],rim=new Map();for(let i=0;i<index.length;i+=3)faces.push(new THREE.Triangle(...[index[i],index[i+1],index[i+2]].map(j=>new THREE.Vector3().fromArray(position,j*3))));for(let i=0;i<position.length;i+=3)if(position[i+1]<=e.worldBounds[0][1]+.35){const v=[position[i],position[i+1],position[i+2]];rim.set(v.map(v=>v.toFixed(3)).join(','),v);}geometry.set(uid,{e,path,faces,rim:[...rim.values()]});disposeOfficialModel(model);}
const results=[];for(const assembly of assemblies){const podium=geometry.get(assembly.podium);for(const uid of assembly.towers){const g=geometry.get(uid),samples=g.rim.map(position=>({position,distance:nearest(podium,new THREE.Vector3(...position))}));results.push({uid,podiumUID:assembly.podium,modelSHA256:g.e.sha256,podiumSHA256:podium.e.sha256,catalogue:g.path,nativeBase:g.e.worldBounds[0][1],oldDependencies:g.e.supportDependencies||[],samples,contacts:samples.filter(s=>s.distance<=.5).length,total:samples.length,maxDistance:Math.max(...samples.map(s=>s.distance)),allNativeContacts:samples.length>=3&&samples.every(s=>s.distance<=.5)});}}
const report={issue:'HKS-214',published:false,verticalScale:1,method:'Existing runtime source decoder and exact nearest triangle distances for every unique vertex within0.35m of native minimumY; unchanged0.5m contact tolerance.',catalogues,manifestSHA256:sha('3d-viewer/city/data/manifest.json'),rows:results};writeFileSync(new URL('docs/astra-city/model-integration-20260909/hermitage-support.json',root),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(results.map(r=>({...r,samples:undefined})),null,2));
