"""DRAFT source-only completed P233218 capture freezer; no spatial identity or root credit."""
import argparse,importlib.util,json
from pathlib import Path
import numpy as np
from run import ROOT,HERE,read,save,digest,connect
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-beverly-podium233218-complete-current-ground-capture-v1-20261011';DOC=B/BATCH;LOCAL=HERE/'local'/BATCH;PRIOR=B/'government-xl-beverly-hill-k-j-original-podium233218-provenance-complete-contact-v2-20261011';UID='landsd/233218:0';SHA='5fd92d6e2e691795087421f5a528eb2d641cc82141f8960da319a4072281abef';STATE_UIDS=[UID,'landsd/255543:0','landsd/255939:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid',(STATE_UIDS,)).fetchall()
def main():
 parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--manifest-sha256',required=True);args=parser.parse_args();assert not(DOC/'result.json').exists();before=state();scope=read(DOC/'capture-scope.json');pre=read(DOC/'source-preflight.json');old=read(PRIOR/'diagnostic.json.gz');assert scope['currentManifest']==pre['currentManifest']==ref(ROOT/'3d-viewer/city/data/manifest.json')and scope['currentManifest']['sha256']==args.manifest_sha256;assert scope['startEndAllInputsVerified']and scope['allCurrentTerrainPatchesPreserved']and scope['terrainCandidates']==[]and not scope['wholeSourceIdentityAccepted'];assert scope['rawHistoricalIdentityReasons']==pre['rawHistoricalWholeSourceIdentityReasons']==old['rawHistoricalIdentityReasons'];assert pre['sourceUninstalled']
 s=read(DOC/'selection.json.gz')['rows'][0];assert s['uid']==UID and s['sourceSHA256']==SHA;p=ROOT/s['candidate']['path'];assert digest(p.read_bytes())==SHA;source=decode_original_world_triangles(p.read_bytes());assert source.shape==(4712,3,3)and digest(source.tobytes())==old['completeOriginalPodiumWorldSHA256']==pre['completeOriginalWorldSHA256'];body=old['completeOriginalPodiumNonzeroBodyCensus'];assert len(body['sharedEdgeConnectedComponents'])==14 and body['completeOriginalFaceIds']==list(range(4712))and body['completeWorldTrianglesSHA256']==digest(source.tobytes());assert sorted(f for c in body['sharedEdgeConnectedComponents']for f in c)==sorted(body['completeRenderableFaceIds'])
 rt=read(LOCAL/'runtime-geometry.json.gz');a=read(DOC/'actual-render-geometry.json.gz');assert len(rt['rows'])==len(a['rows'])==1;r=rt['rows'][0];attr=a['rows'][0];assert r['uid']==attr['uid']==UID and r['index']==attr['completeOriginalIndex']and r['position']==attr['completeLiteralWorldPosition'];g=np.asarray(r['drawnGroundGeometry'],float).reshape(-1,3,3);assert len(g)==scope['completeActualRelevantGroundFaces']and digest(g.tobytes())==scope['completeActualRelevantGroundSHA256']
 spec=importlib.util.spec_from_file_location('reviewed_P_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);paths=set();m.local_imports(Path(__file__),paths);m.local_imports(HERE/'beverly_podium233218_complete_current_ground_capture_v1_20261011.py',paths)
 for folder in [DOC,LOCAL]:
  for p in folder.rglob('*'):
   if p.is_file():
    paths.add(p)
    if p.name.endswith('.json')or p.name.endswith('.json.gz'):m.declared_refs(read(p),paths)
 paths.update([PRIOR/'diagnostic.json.gz',PRIOR/'result.json']+[HERE/n for n in ['beverly_podium233218_current_actual_render_attributes_v1_20261011.mjs','beverly_podium233218_capture_module_closures_v1_20261011.mjs','literal_production_module_dependency_closure_20261010.mjs','actual_float32_model_matrix_bounds_20261011.mjs']])
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');receipt=read(PRIOR/'result.json');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(receipt['jobId'],)).fetchone()==('complete',receipt)
 note='Full4712-facet unchanged original Beverly podium233218 and14genuine sourcebodies, alloriginal/literal/explicitleft/balanced attributes bound to complete relevant actualcurrentmakeTerrain Float32 ground. Source is uninstalled, recorded originalprovider P-CSUID/UID/parent and registryprovenance are verified, but whole spatialidentity remains false with four historicalreasons. All currentcatalogue/base/patch/form/source/module bytes fenced, emptyterraincandidates/allpatchespreserved. Capture supplies no grade/root/bridge/currentacceptance, protectedforeign/native discharge or whole-native reapproval. Complete original positive Pbody0→Kbody8(109)/Jbody8(137) contacts are separate source-only geometry;16Kdetails, remainingPbodyroles and entirecurrentfinite/identity/foundation/runtime/browser obligations persist.'
 save(DOC/'review.json',dict(uid=UID,uids=STATE_UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,wholeSourceIdentityAccepted=False,sourceUninstalled=True,gradeRootCredit=False,nativeReapproval=False,sourceGeometryChanges=0,terrainGeometryChanges=0,currentManifest=scope['currentManifest'],sourceSHA256=SHA,completeOriginalWorldSHA256=digest(source.tobytes()),completeOriginalFaces=4712,genuineOriginalBodies=14,exactBodyCensusAndContacts=ref(PRIOR/'diagnostic.json.gz'),exactPriorSourceReceipt=ref(PRIOR/'result.json'),completeActualCurrentGroundFaces=len(g),completeActualCurrentGroundSHA256=digest(g.tobytes()),rawHistoricalIdentityReasons=old['rawHistoricalIdentityReasons'],fullCurrentProtectiveFormInventory=pre['allCurrentRelevantForeignBasicNativeForms'],finding=note,evidenceRefs=[ref(p)for p in sorted(paths)]));(DOC/'REVIEW.md').write_text('# Beverly original podium actualcurrentground\n\n'+note+'\n');paths.update([DOC/'review.json',DOC/'REVIEW.md']);assert state()==before;save(DOC/'review-state-fence.json',dict(affectedUIDs=STATE_UIDS,before=before,after=state(),exactRowsUnchanged=True,modelReviewWrites=0));paths.add(DOC/'review-state-fence.json');result=m.F.freeze(BATCH,'uninstalled-original-podium233218-complete-actual-current-ground-source-only',sorted(paths),dict(uids=STATE_UIDS,sourceOnly=True,currentAcceptance=False,wholeSourceIdentityAccepted=False,sourceUninstalled=True,rawHistoricalIdentityReasons=old['rawHistoricalIdentityReasons'],completeActualCurrentGroundFaces=len(g),completeActualCurrentGroundSHA256=digest(g.tobytes()),gradeRootCredit=False,nativeReapproval=False,modelReviewWrites=0));assert state()==before;assert ref(ROOT/'3d-viewer/city/data/manifest.json')==scope['currentManifest'];print(json.dumps(dict(jobId=result['jobId'],reviewRowsUnchanged=True,currentAcceptance=False)))
if __name__=='__main__':main()
