"""Established source-only freezer for actual complete bounded primary-directory evidence."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-beverly-70279-primary-directory-absence-checkpoint-v1-20261011';DOC=B/BATCH;UIDS=['landsd/70279:0','landsd/233218:0','landsd/255543:0','landsd/255939:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid,snapshot_id',(UIDS,)).fetchall()
def main():
 before=state();d=read(DOC/'diagnostic.json.gz');assert d['sourceOnly']and not d['currentAcceptance']and not(DOC/'result.json').exists();s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);paths={DOC/'diagnostic.json.gz'};m.local_imports(HERE/'beverly_70279_primary_directory_absence_checkpoint_v1_20261011.py',paths);m.local_imports(Path(__file__),paths);m.declared_refs(d,paths);rows=d['allFourRelevantCachedPrimaryProviderDirectories'];note='All4 cached primary GLTF directory complete model-name sets equal corresponding native-stage sets;1430models total, no name-prefixB3716415011 and no omitted-processing model within this pinned four-sheet corpus. Native complete exactObject70279/CSUIDcandidate census also0. No remote/fresh/global absence or impossible recovery claimed. Revisit requires independently exact original70279/version/source identity (or separately source-authorized procedural foreign correction with full gates), and authoritative main3152facet Pbody0 extent reconciliation. Current1861/4712 Pburied facets/min−24.64m, raw16.63m/1.0736m² identity failures and34 actualP/BASIC70279 surface intersections remain. Terrain-only processing cannot resolve unchanged building intersections. Jinstalled original/terrain/review state preserved; K/P uninstalled. No modelling, tolerance waiver, acceptance, publication or review-state changes.'
 (DOC/'REVIEW.md').write_text('# Bounded primary original-source corpus result\n\n'+note+'\n');save(DOC/'review.json',dict(uids=UIDS,finding=note,sourceOnly=True,currentAcceptance=False,installationApproved=False,globalAbsenceClaimed=False,evidenceRefs=[ref(p)for p in sorted(paths)]));paths.update([DOC/'REVIEW.md',DOC/'review.json']);m.F.freeze(BATCH,'bounded-primary-directory-native-complete-name-set-comparison-no-original70279',sorted(paths),dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],reviewStateUnchanged=True)))
if __name__=='__main__':main()
