"""DRAFT established source-only freezer for fresh official index/directory evidence."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-beverly-70279-fresh-official-source-index-directory-search-v1-20261011';DOC=B/BATCH;METHOD=B/'government-xl-beverly-70279-fresh-official-source-search-method-v1-20261011/method.json';UIDS=['landsd/70279:0','landsd/233218:0','landsd/255543:0','landsd/255939:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid,snapshot_id',(UIDS,)).fetchall()
def main():
 before=state();d=read(DOC/'diagnostic.json.gz');assert d['sourceOnly']and not d['currentAcceptance']and not d['sourceGeometryAcquired']and not(DOC/'result.json').exists();s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);paths={p for p in DOC.rglob('*')if p.is_file()};paths.add(METHOD);m.local_imports(HERE/'beverly_70279_fresh_official_source_index_directory_search_v1_20261011.py',paths);m.local_imports(Path(__file__),paths);m.declared_refs(d,paths);stable=[f['attributes']for f in d['currentOutlineQueries'].get('exact-csuid',{}).get('features',[])if f['attributes'].get('BuildingCSUID')=='3716415011T20080220'];summary=dict(stableCSUIDCurrentlyReturned=bool(stable),freshStableCSUIDObjectIds=[a['OBJECTID']for a in stable],freshStableCSUIDRecordedElevationFields=[dict(base=a.get('BaseHeight'),top=a.get('TopHeight'))for a in stable],complete=d['completeBoundedFreshOfficialSearch'],boundedFreshDirectoryAbsence=d['boundedFreshDirectoryAbsence'],exactGeoRefCandidateDirectories=len(d['exactGeoRefSourceCandidates']),officialExactObjectCSUIDReturned=d['exactObjectAndCSUIDCurrentlyReturned'],errors=d['errors']);note='Fresh bounded official70279 source search: '+json.dumps(summary)+'. Cached1430absence remains historical and BUILDING-only, not an all-class archive absence. Fresh exactGeoRef matching covers all letter-prefixed model namespaces including infrastructure. StableCSUID2Dpresence is distinct from exact currentOBJECTID+CSUID equality; changed OBJECTID is not source disappearance, and null recorded BaseHeight/TopHeight gives no authoritative3D height. Fresh evidence only at exact recorded index revisions and archive ETags for two official families/four sheets/GLTF+FBX. ExactGeoRef member nominates potential source, not fullCSUID/source identity. An incomplete search proves no absence; complete negative proves only listed scope. No native model members acquired, nearby source substituted, terrain/building geometry altered, function/ownership/root/current approval or held state changed. ExistingPidentity/mainbodyextent/burial/34actual70279surfaceintersections andK16details remain; installedJ and separateK/Pheld ledger untouched.'
 (DOC/'REVIEW.md').write_text('# Beverly70279 fresh official source search\n\n'+note+'\n');save(DOC/'review.json',dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,finding=note,summary=summary,evidenceRefs=[ref(p)for p in sorted(paths)]));paths.update([DOC/'REVIEW.md',DOC/'review.json']);m.F.freeze(BATCH,'beverly-70279-fresh-official-source-index-directory-search-no-acceptance',sorted(paths),dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],reviewStateUnchanged=True)))
if __name__=='__main__':main()
