"""Complete12640-facet current finite strict clearance and all-wall actual grade interfaces.
Existing exact kernels; no whole-native reapproval or historical/global impossibility.
"""
from pathlib import Path
from fractions import Fraction as F
import numpy as np,json
from run import ROOT,HERE,read,save,digest
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from exact_original_face_conservative_clearance_v5_20261010 import verify as finite
from exact_original_triangle_pair_column_gap_20261010 import verify as column
from exact_original_upper_ground_interfaces_20261009 import exact_upper_ground_interfaces
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-beverly-hill-k-complete-current-carrier-strict-clearance-grade-exclusion-v1-20261011';DOC=B/BATCH;CAPTURE=B/'government-xl-beverly-elm-complete-current-support-ground-capture-v2-20261011';BFS=B/'government-xl-beverly-hill-k-current-carrier-four-stream-bounded-grade-route-diagnostic-v3-20261011';RUNTIME=HERE/'local'/CAPTURE.name/'runtime-geometry.json.gz';UID='landsd/255939:0'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not DOC.exists();assert read(CAPTURE/'result.json')['sourceOnly'];actor=next(r for r in read(CAPTURE/'review.json')['actors']if r['uid']==UID);selection=next(r for r in read(CAPTURE/'selection.json.gz')['rows']if r['uid']==UID);p=ROOT/selection['candidate']['path'];original=decode_original_world_triangles(p.read_bytes());rt=next(r for r in read(RUNTIME)['rows']if r['uid']==UID);ground=np.asarray(rt['drawnGroundGeometry'],float).reshape(-1,3,3);assert original.shape==(12640,3,3)and digest(original.tobytes())==actor['completeOriginalWorldSHA256']and digest(ground.tobytes())==actor['completeActualRelevantGroundSHA256']and len(ground)==4;a=next(r for r in read(CAPTURE/'actual-render-geometry.json.gz')['rows']if r['uid']==UID);index=np.asarray(a['completeOriginalIndex']).reshape(-1,3);streams={'original':original}
 for name,key in [('literal','completeLiteralWorldPosition'),('explicitLeftF32','completeExplicitLeftAssociatedFloat32WorldPosition'),('explicitBalancedF32','completeExplicitBalancedFloat32WorldPosition')]:streams[name]=np.asarray(a[key],float).reshape(-1,3)[index]
 old=read(BFS/'diagnostic.json.gz');assert old['completeFrozenCurrentGroundSHA256']==digest(ground.tobytes());proofs={};bindings={}
 for name,source in streams.items():
  h=digest(source.tobytes());bindings[name]=dict(completeWorldSHA256=h,completeFaces=len(source),proofTupleSHA256=h)
  if h in proofs:continue
  cached=old['allDistinctWholeSourceTupleRouteDiagnostics'].get(h);nodes={r['face']:r for r in cached['allExaminedFaceProofs']}if cached else {};rows=[];wallids=[];normal=np.cross(source[:,1]-source[:,0],source[:,2]-source[:,0]);wallids=list(map(int,np.flatnonzero((normal[:,1]==0)&np.any(normal!=0,axis=1))))
  for i,face in enumerate(source):
   if i in nodes:
    prior=nodes[i]['wholeFiniteProof'];pieces=nodes[i]['refinedFiniteColumnPieces'];lower=F(nodes[i]['exactLowerM']);assert prior['sourceFaceSHA256']==digest(face.tobytes());reuse=True
   else:
    prior=finite(face,ground);lower=F(prior['exactCertifiedLowerClearanceM']);pieces=[];reuse=False
    if prior['groundProjectionCovered']and lower<=0:
     pieces=[dict(originalGroundFace=j,proof=column(face,ground[j]))for j in prior['allProjectedBoundingCandidateOriginalGroundFacets']];gaps=[F(x['proof']['exactMinimumFiniteColumnGapM'])for x in pieces if x['proof']['exactClosedHorizontalProjectionsMeet']];assert gaps;lower=min(gaps)
   rows.append(dict(face=i,priorCompleteFiniteProof=prior,refinedCompleteFinitePairs=pieces,exactLowerM=str(lower),completeProjectionCovered=prior['groundProjectionCovered'],strictFiniteClearanceProved=bool(prior['groundProjectionCovered']and lower>0),reusedExactPriorFacetTupleAndWholeGround=bool(reuse)))
   if(i+1)%1000==0:print(json.dumps(dict(stream=name,completeFacets=i+1,of12640=True)),flush=True)
  wallinterfaces=exact_upper_ground_interfaces(source,wallids,ground);bottom=float(source[:,:,1].min());lowrim=np.flatnonzero(np.any(source[:,:,1]<=bottom+.35,axis=1));proofs[h]=dict(allWholeCarrierFacetProofs=rows,completeFacetsAccounted=len(rows),allStrictFiniteClearanceProved=all(r['strictFiniteClearanceProved']for r in rows),strictFailingSourceFacets=[r['face']for r in rows if not r['strictFiniteClearanceProved']],coverageFailingSourceFacets=[r['face']for r in rows if not r['completeProjectionCovered']],minimumCertifiedOrRefinedLowerM=str(min(F(r['exactLowerM'])for r in rows)),allExactVerticalNonzeroWallFacets=wallids,allExactPositiveUpperGroundWallInterfaces=wallinterfaces,allWholeSourceFacetsAtGlobalBottomPlusPoint35M=list(map(int,lowrim)),globalOriginalSourceBottomM=bottom,lowRimThresholdContextOnlyNoRootCredit=True,carrierActualCurrentGradeInterfacesExcluded=all(r['strictFiniteClearanceProved']for r in rows)and not wallinterfaces)
 pre=read(CAPTURE/'support-source-preflight.json');refs=[ref(x)for x in [Path(__file__),p,RUNTIME,CAPTURE/'result.json',CAPTURE/'review.json',CAPTURE/'actual-render-geometry.json.gz',CAPTURE/'support-source-preflight.json',BFS/'diagnostic.json.gz']]+[ref(HERE/(n+'.py'))for n in ['exact_packed_world_geometry_20261009','exact_original_face_conservative_clearance_v5_20261010','exact_original_triangle_pair_column_gap_20261010','exact_original_upper_ground_interfaces_20261009','exact_original_projection_coverage_v2_20261010','exact_original_shell_intersections_20261009','exact_original_component_contacts_20261009']]
 for r in refs:assert ref(ROOT/r['path'])==r
 save(DOC/'diagnostic.json.gz',dict(uids=[UID,'landsd/255543:0'],sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,noHistoricalFailureWaiver=True,currentManifest=pre['currentManifest'],completeActualCurrentGroundFacets=4,completeActualCurrentGroundSHA256=digest(ground.tobytes()),allFourStreamBindings=bindings,allDistinctWholeSourceFiniteAndWallProofs=proofs,exactByteIdenticalFullWorldTupleReuseOnly=True,wholeNativeReapproval=False,historical16OwnedDetailObligationsUnchanged=True,globalRecoveryImpossible=False,qualification='Complete current finite source/ground separation and every original nonzero vertical wall exact upper-envelope interface. If wholecarrier strictly positive, no genuine grade-interface route to cap2122 exists within this unchanged carrier/currentsurface; this is not a historical/global obstruction, whole-native reapproval or grounding credit. Seek actual independently evidenced lower original component/support/source or grade, preserving all originalgeometry and protected actors. Lowrim context and sampled metrics are not roots.',evidenceRefs=refs));print(json.dumps({h:dict(allStrict=x['allStrictFiniteClearanceProved'],minLower=x['minimumCertifiedOrRefinedLowerM'],walls=len(x['allExactVerticalNonzeroWallFacets']),positiveGradeInterfaces=len(x['allExactPositiveUpperGroundWallInterfaces']),gradeExcluded=x['carrierActualCurrentGradeInterfacesExcluded'],strictFailures=len(x['strictFailingSourceFacets']))for h,x in proofs.items()}),flush=True)
if __name__=='__main__':main()
