"""Established immutable source-only registry/attribution freezer; no review writes."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-beverly-podium233218-70279-original-registry-farpoint-attribution-v1-20261011';DOC=B/BATCH;PRODUCER=HERE/'beverly_podium233218_70279_original_registry_and_farpoint_attribution_v1_20261011.py';UIDS=['landsd/233218:0','landsd/255543:0','landsd/255939:0','landsd/70279:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid',(UIDS,)).fetchall()
def main():
 before=state();d=read(DOC/'diagnostic.json.gz');assert d['sourceOnly']and not d['currentAcceptance']and not(DOC/'result.json').exists();s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);paths={DOC/'diagnostic.json.gz'};m.local_imports(PRODUCER,paths);m.local_imports(Path(__file__),paths);m.declared_refs(d,paths)
 far=[dict(xz=p['xz'],distanceM=p['distanceM'],originalFaces=p['completeExactOriginalVertexIncidentFaces'],bodies=p['genuineOriginalBodies'])for p in d['farpointOriginalVertexAttributions']];note='Existing full-run exact name-prefix profiles='+str(len(d['allRunExactNamePrefixQueryResults']))+'; complete relevant four-sheet native registry versions='+str(len(d['completeFourSheetNativeRegistrySnapshots']))+'; independent exactObject70279/CSUID3716415011T20080220 candidates='+str(len(d['independentExactObjectAndCSUIDCandidateMatches']))+'. Bounded corpus only, not proof no original exists globally. Maximum16.634188m source excess: '+json.dumps(far)+'. All exact positive current foreign-intersection podium facets='+json.dumps(d['allExactCurrentForeignPositiveContactPodiumFaces'])+'. Functions remain unknown, no source trimming/ownership reassignment. Current wholeP burial1861/4712,min−24.63764m and all four extent/unrelated identity negatives stay unchanged. Terrain alone cannot resolve fixed actualP/BASIC70279 surface intersections; any independent original70279 replacement must satisfy complete ordinary source/identity/current/foundation/foreign/native gates before a candidate. No geometry, terrain, stage, live or review-state edits.'
 (DOC/'REVIEW.md').write_text('# Bounded original foreign-source availability and exact excess attribution\n\n'+note+'\n');save(DOC/'review.json',dict(uids=UIDS,finding=note,farpointAttribution=far,sourceOnly=True,currentAcceptance=False,installationApproved=False,boundedAbsenceNotGlobal=True,original70279Recovered=False,evidenceRefs=[ref(p)for p in sorted(paths)]));paths.update([DOC/'REVIEW.md',DOC/'review.json']);m.F.freeze(BATCH,'bounded-exact-original70279-registry-and-source-farpoint-attribution',sorted(paths),dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],reviewStateUnchanged=True)))
if __name__=='__main__':main()
