"""DRAFT immutable source-context supplement to existing K/P held snapshot; no review writes."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-beverly-k-p-fresh70279-held-revisit-context-v2-20261011';DOC=B/BATCH
FRESH=B/'government-xl-beverly-70279-fresh-official-source-index-directory-search-v1-20261011';HELD=B/'government-xl-beverly-k-p-separate-held-source-review-plan-v1-20261011'
PRIOR_SCOPE=B/'government-xl-beverly-elm-actual-original-tin-causal-additive-scope-v3-20261011/declared-scope.json'
SNAPSHOT='1ef9e76176f13d45';SOURCES={'landsd/233218:0':'5fd92d6e2e691795087421f5a528eb2d641cc82141f8960da319a4072281abef','landsd/255543:0':'a780f09a03f515f9baf33d7d0408f663fe82080d51c1b4290f02dd4121124667'};UIDS=list(SOURCES)+['landsd/255939:0','landsd/70279:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) OR snapshot_id=%s ORDER BY uid,snapshot_id',(UIDS,SNAPSHOT)).fetchall()
def main():
 assert not DOC.exists();before=state();own=[r[0]for r in before if r[0]['snapshot_id']==SNAPSHOT];assert {r['uid']:r['source_sha256']for r in own}==SOURCES and all(r['review_state']=='held'for r in own)
 receipts=[FRESH/'result.json',HELD/'result.json'];prior=read(PRIOR_SCOPE);assert prior['declaredReferencesClosed']and not prior['unboundExactReferenceVersions'];aliases={(x['originalPath'],x['sha256']):x['archive']for x in prior['historicalManifestAliases']};resolved=[]
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY')
  for p in receipts:
   r=read(p);assert not r['currentAcceptance'];assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(r['jobId'],)).fetchone()==('complete',r)
   for e in r['evidenceRefs']:
    if ref(ROOT/e['path'])!=e:
     archived=aliases[(e['path'],e['sha256'])];assert archived['sha256']==e['sha256']and ref(ROOT/archived['path'])==archived;resolved.append(dict(historicalRef=dict(originalPath=e['path'],historicalSHA256=e['sha256']),actualArchive=archived,qualification='Historical receipt binding only; no claim about current pointer bytes.'))
 d=read(FRESH/'diagnostic.json.gz');assert d['completeBoundedFreshOfficialSearch']and d['boundedFreshDirectoryAbsence']and not d['errors']and not d['exactGeoRefSourceCandidates']and d['sourceModelMemberRequests']==0 and not d['sourceGeometryAcquired'];a=[f['attributes']for f in d['currentOutlineQueries']['exact-csuid']['features']if f['attributes'].get('BuildingCSUID')=='3716415011T20080220'];assert len(a)==1;actor=a[0];assert actor['OBJECTID']==70234 and actor['Status']=='Active'and actor['BaseHeight']is None and actor['TopHeight']is None;assert not d['exactObjectAndCSUIDCurrentlyReturned']
 paths={PRIOR_SCOPE,*[ROOT/x['actualArchive']['path']for x in resolved]};paths.update(receipts+[FRESH/'diagnostic.json.gz',FRESH/'review.json',FRESH/'REVIEW.md',HELD/'held-source-decision.json',HELD/'held-ledger-neon.json',HELD/'source-review-inventory.json'])
 note=dict(heldSnapshotId=SNAPSHOT,heldUIDs=list(SOURCES),canonicalOriginalSourceSHA256=SOURCES,sourceOnly=True,currentAcceptance=False,installationApproved=False,newlyInstalled=0,modelReviewWrites=0,mainPointerWrites=0,installedJChanges=0,historicalHeldDecisionPreserved=True,historicalReceiptExactArchiveResolutions=resolved,priorExactAliasContract=ref(PRIOR_SCOPE),heldHumanStatus='held-unknown',inProcess=False,permanentRejection=False,stableForeignCSUID='3716415011T20080220',historicalForeignBASICObjectId=70279,freshOfficialObjectId=70234,freshOfficialBuildingId=actor['BuildingID'],freshOfficialGeoRef=actor['GeoRefNo'],freshOfficialStatus=actor['Status'],freshRecordedBaseHeight=None,freshRecordedTopHeight=None,exactOldObjectAndCSUIDReturned=False,stableCSUIDCurrentlyReturned=True,automaticBASICObjectRemapAuthorized=False,boundedFresh3DDirectoryAbsence=True,sourceModelMembersAcquired=0,
  revisitConditions=[
   'Recover independently versioned original government 3D geometry mapped to stable CSUID3716415011T20080220, accounting explicitly for current official OBJECTID70234 versus historical BASIC70279. Verify source revision, complete identity and provenance before testing all unchanged P/K/J/foreign source contacts; no automatic OID substitution. Fresh absence is only the 16 complete directories/two official families/four sheets/two formats at recorded revisions and ETags, not global or permanent unavailability.',
   'Resolve untouched original P233218 main-body extent identity: the 16.634188m far vertex belongs to 3152-facet connected body0, not an expendable detached detail. Obtain authoritative source/extent evidence or a separately reviewed source-authorized procedural correction; do not discard, shift, remodel or waive source obligations.',
   'Null recorded base/top in the active official 2D record supplies no authoritative 3D/source-grade elevations. Obtain versioned original 3D or authoritative recorded grade evidence separately; neither active identity nor archive absence authorizes invented heights.',
   'After identity and the 34 actual P-to-BASIC70279 noncoplanar positive surface intersections are resolved, require complete4712-face P original/literal/Float32 finite foundation and genuine source grade/support proofs, full K/J/P detail obligations, all current foreign/native/runtime protections and any separately reviewed affected terrain proof. Terrain-only changes cannot remove unchanged source-versus-BASIC surface intersections.'
  ],preservedBlockers=['Pcurrent1861ordinaryFiniteGroundFailures/min-24.6376392573m','PfourStreamWholeSourceIdentityFailures','PmainBodyFarExtent16.634188303863088m','P34actualForeign70279SurfaceIntersections','K16OriginalDetailBodiesUnresolved','ConditionalK/J/PcontactsAreNotGroundRoots'],qualification='This source-context supplement links fresh official source evidence to the existing separate held snapshot without overwriting historical decisions, events, source states, installed J or any main/current pointer. StableCSUID presence with OID renumbering is not disappearance and does not validate baseline geometry. The previous cached1430 BUILDING-only absence remains bounded historical evidence. No global impossibility, architectural function, ownership exemption, AI modelling or human approval requirement inferred.',evidenceRefs=[ref(p)for p in sorted(paths)])
 save(DOC/'held-revisit-context.json',note);save(DOC/'held-row-readback.json',dict(snapshotId=SNAPSHOT,rows=own,protectedUIDs=UIDS,protectedReviewRowsSHA256=digest(json.dumps(before,sort_keys=True,separators=(',',':')).encode()),sourceOnly=True,modelReviewWrites=0))
 (DOC/'REVIEW.md').write_text('# Beverly K/P held source revisit context\n\nThe stable foreign CSUID remains active under official object70234, whereas the saved BASIC actor is object70279. The fresh bounded16-directory search found no matching3D member; recorded base/top remain null. Neither finding resolves the34 original P-to-BASIC surface intersections or Pmainbody extent identity. K/P remain held in the existing separate snapshot.\n\nRevisit when independently versioned original foreign geometry and Pextent evidence allow full source/current identity, support, foreign and ground checks. No review row, main pointer, installed J or geometry is modified.\n');paths.update([DOC/'held-revisit-context.json',DOC/'held-row-readback.json',DOC/'REVIEW.md'])
 s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.local_imports(Path(__file__),paths);m.declared_refs(note,paths);m.F.freeze(BATCH,'beverly-k-p-fresh70279-held-revisit-context-no-model-review-writes',sorted(paths),dict(uids=list(SOURCES),heldSnapshotId=SNAPSHOT,sourceOnly=True,currentAcceptance=False,installationApproved=False,newlyInstalled=0,modelReviewWrites=0,mainPointerWrites=0,installedJChanges=0,qualification=note['qualification']));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],heldSnapshotId=SNAPSHOT,protectedReviewRowsUnchanged=True)))
if __name__=='__main__':main()
