"""Existing source-only freezer with exact declared inputs and unchanged review-state fence."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-beverly-podium233218-complete-current-finite-ground-diagnostic-v1-20261011';DOC=B/BATCH;PRODUCER=HERE/'beverly_podium233218_complete_current_finite_ground_diagnostic_v1_20261011.py';UIDS=['landsd/233218:0','landsd/255543:0','landsd/255939:0','landsd/70279:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid',(UIDS,)).fetchall()
def main():
 before=state();d=read(DOC/'diagnostic.json.gz');assert not(DOC/'result.json').exists()and d['sourceOnly']and not d['currentAcceptance']and not d['wholeSourceIdentityAccepted']and len(d['rawHistoricalIdentityReasons'])==4;s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);paths={DOC/'diagnostic.json.gz'};m.local_imports(PRODUCER,paths);m.local_imports(Path(__file__),paths);m.declared_refs(d,paths);proofs=list(d['allDistinctWholeSourceFiniteProofs'].values());assert all(x['completeFacetsAccounted']==4712 for x in proofs)
 summary=[dict(completeFacets=x['completeFacetsAccounted'],ordinaryFailures=len(x['ordinaryFailingSourceFaces']),coverageFailures=len(x['coverageFailingSourceFaces']),ordinaryFinite=x['allOrdinaryFiniteProved'],strictPositiveFinite=x['allStrictPositiveFiniteProved'],minimumLowerM=x['minimumCertifiedOrRefinedLowerM'])for x in proofs];note='All4712 original/literal/leftF32/balancedF32 facets accounted against18 complete actual current production terrain facets, with byte-identical whole tuple reuse only. Ordinary>=−1/2 and strict-positive exposure remain separate. Results: '+json.dumps(summary)+'. Four unchanged whole-source spatial identity failures, all14 source bodies, source-only109 K/137 J contact context, foreign70279 and all other native/foreign/grade/interface obligations remain unresolved. No grade root, whole-P approval, current acceptance, source/terrain edits or historical failure waiver.'
 (DOC/'REVIEW.md').write_text('# Podium whole-source finite-ground diagnostic\n\n'+note+'\n');save(DOC/'review.json',dict(uids=UIDS,finding=note,finiteSummaries=summary,sourceOnly=True,currentAcceptance=False,installationApproved=False,gradeRootCredit=False,wholeSourceIdentityAccepted=False,evidenceRefs=[ref(p)for p in sorted(paths)]));paths.update([DOC/'REVIEW.md',DOC/'review.json']);m.F.freeze(BATCH,'complete-original-podium-current-finite-ground-no-root-or-identity-credit',sorted(paths),dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],reviewStateUnchanged=True)))
if __name__=='__main__':main()
