"""DRAFT bounded original70279 registry audit and existing exact-source farpoint attribution.
No new terrain/geometry, whole-source identity waiver, source recovery guessing or model roles.
"""
from pathlib import Path
import json,numpy as np
from run import ROOT,HERE,read,save,digest,connect,NATIVE_RUN
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-beverly-podium233218-70279-original-registry-farpoint-attribution-v1-20261011';DOC=B/BATCH;LOCAL=HERE/'local'/BATCH;CAP=B/'government-xl-beverly-podium233218-complete-current-ground-capture-v1-20261011';ATTR=B/'government-xl-beverly-podium233218-foreign70279-identity-attribution-v1-20261011';PRIOR=B/'government-xl-beverly-hill-k-j-original-podium233218-provenance-complete-contact-v2-20261011';UID='landsd/70279:0';CSUID='3716415011T20080220';SHEETS=['11-SW-15A','11-SW-15B','11-SW-15C','11-SW-15D']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not DOC.exists()and not LOCAL.exists();refs=[ref(Path(__file__)),ref(HERE/'exact_packed_world_geometry_20261009.py')]
 for doc in [CAP,ATTR,PRIOR]:
  receipt=read(doc/'result.json')
  with connect()as c:
   c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(receipt['jobId'],)).fetchone()==('complete',receipt)
  refs.extend(ref(doc/n)for n in ['result.json','review.json','diagnostic.json.gz']if(doc/n).exists())
 pre=read(CAP/'source-preflight.json');foreign=next(r for r in pre['allCurrentRelevantForeignBasicNativeForms']if r['building']['uid']==UID);assert foreign['building']['objectId']==70279 and foreign['building']['buildingCSUID']==CSUID and not foreign['installedNative'];row=read(CAP/'selection.json.gz')['rows'][0];asset=ROOT/row['candidate']['path'];assert digest(asset.read_bytes())==row['sourceSHA256'];world=decode_original_world_triangles(asset.read_bytes());assert world.shape==(4712,3,3);census=read(PRIOR/'diagnostic.json.gz')['completeOriginalPodiumNonzeroBodyCensus'];assert digest(world.tobytes())==census['completeWorldTrianglesSHA256'];bodies=census['sharedEdgeConnectedComponents'];body_for={i:b for b,faces in enumerate(bodies)for i in faces};assert len(bodies)==14 and sorted(body_for)==list(range(4712));attribution=read(ATTR/'diagnostic.json.gz');farpoints=[]
 for key,p in attribution['allDistinctProofs'].items():
  for far in p['descriptiveMaximumExcessCoordinates']:
   xz=np.asarray(far['xz']);faces=np.flatnonzero(np.any(np.all(world[:,:,[0,2]]==xz,axis=2),axis=1)).tolist();assert faces,'Farthest projection coordinate is not an original vertex; cannot infer source facet';farpoints.append(dict(proofWorldSHA256=key,**far,completeExactOriginalVertexIncidentFaces=faces,genuineOriginalBodies=sorted({body_for[i]for i in faces}),completeOriginalIncidentFacetCoordinates=[dict(sourceFace=i,genuineOriginalBody=body_for[i],vertices=world[i].tolist())for i in faces]))
 contactfaces=sorted({c['sourceFaceA']for p in attribution['allDistinctProofs'].values()for c in p['allExactFiniteContacts']if c['dimension']>0});projectedfaces=sorted({r['originalFace']for p in attribution['allDistinctProofs'].values()for r in p['allNonzeroProjectedExcessFacetAttributions']if r['descriptiveForeignExcessAreaM2']>0});implicated=sorted({body_for[i]for i in contactfaces+projectedfaces}|{b for p in farpoints for b in p['genuineOriginalBodies']});bodycontext=[dict(body=b,completeOriginalFaces=bodies[b],completeOriginalFacetCount=len(bodies[b]),bounds=[world[bodies[b]].min((0,1)).tolist(),world[bodies[b]].max((0,1)).tolist()],visualOrStructuralFunctionUnknown=True,rootCredit=False)for b in implicated]
 prefix=[];profiles=[];snapshots=[];matches=[];namehits=[]
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');prefix=c.execute('SELECT DISTINCT cache_key,sheet,model_id FROM astra_modelling.native_model_sizes WHERE run_id=%s AND model_id LIKE %s',(NATIVE_RUN,'B'+CSUID[:10]+'%')).fetchall();profiles=c.execute('SELECT DISTINCT cache_key,sheet FROM astra_modelling.native_model_sizes WHERE run_id=%s AND sheet=ANY(%s)',(NATIVE_RUN,SHEETS)).fetchall()
  for key,sheet in sorted(profiles):
   sha,data=c.execute('SELECT r.result_sha,r.result FROM astra_modelling.native_stage_results r JOIN astra_modelling.native_stage_members m USING(cache_key) WHERE m.run_id=%s AND r.cache_key=%s',(NATIVE_RUN,key)).fetchone();path=LOCAL/'registry'/sheet/(digest(key.encode())+'.json.gz');save(path,dict(runId=NATIVE_RUN,cacheKey=key,sheet=sheet,resultSHA256=sha,exactNativeResult=data));snapshots.append(dict(cacheKey=key,sheet=sheet,resultSHA256=sha,completeRegistryModels=len(data['models']),snapshot=ref(path)))
   for model in data['models']:
    if model['modelId'][1:11]==CSUID[:10]:namehits.append(dict(cacheKey=key,sheet=sheet,resultSHA256=sha,model=model))
    if any(v.get('objectId')==70279 and v.get('buildingCSUID')==CSUID for v in model.get('matching',{}).get('officialCandidates',[])):matches.append(dict(cacheKey=key,sheet=sheet,resultSHA256=sha,model=model))
  for s in snapshots:
   assert c.execute('SELECT r.result_sha,r.result FROM astra_modelling.native_stage_results r JOIN astra_modelling.native_stage_members m USING(cache_key) WHERE m.run_id=%s AND r.cache_key=%s',(NATIVE_RUN,s['cacheKey'])).fetchone()==(s['resultSHA256'],read(ROOT/s['snapshot']['path'])['exactNativeResult'])
 refs.extend(ref(p)for p in [asset,CAP/'source-preflight.json',CAP/'selection.json.gz',ATTR/'diagnostic.json.gz',PRIOR/'diagnostic.json.gz']);refs.extend(s['snapshot']for s in snapshots)
 save(DOC/'diagnostic.json.gz',dict(uids=['landsd/233218:0',UID,'landsd/255543:0','landsd/255939:0'],sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,currentManifestHistoricalExact=pre['currentManifest'],actualCurrentForeignForm=foreign,existingNativeRun=NATIVE_RUN,allRunExactNamePrefixQueryResults=prefix,completeFourSheetNativeRegistrySnapshots=snapshots,exactNamePrefixModelsWithinFourSheets=namehits,independentExactObjectAndCSUIDCandidateMatches=matches,original70279Recovered=False,original70279AvailabilityUnresolved=(len(matches)!=1),boundedSearchNotGlobalProviderAbsenceProof=True,farpointOriginalVertexAttributions=farpoints,allExactCurrentForeignPositiveContactPodiumFaces=contactfaces,allDescriptive70279ProjectedExcessPodiumFaces=projectedfaces,completeImplicatedOriginalBodyContext=bodycontext,sourceExtentLimitM=10,sourceUnrelatedAreaLimitM2=1,noIdentityWaiver=True,terrainOnlyCannotRemoveUnchangedPToActualBasic70279SurfaceIntersections=True,qualification='Full exact candidate inventory limited to fixed NATIVE_RUN and four named relevant sheets; name-prefix query spans entire existing run. Missing matches do not prove unavailable original data outside that cache/provider corpus. No nearby model substituted. Exact farpoint vertex incidence identifies source facets/bodies, not visual/architectural function. All current burial/extent/foreign intersections remain; any future original70279 recovery must bind independent exact source identity and complete P/K/J/70279 source/current protections before a proposal.',evidenceRefs=refs))
 print(json.dumps(dict(nativePrefixProfiles=len(prefix),completeFourSheetRegistryVersions=len(snapshots),exactIndependentCandidates=len(matches),farpointBodies=sorted({b for p in farpoints for b in p['genuineOriginalBodies']}),positiveContactSourceFaces=contactfaces,currentAcceptance=False)))
if __name__=='__main__':main()
