"""Actual original BeverlyHill podium233218 provenance/fullbody/contact to K/J.
No current podium ground, source acceptance, root/bridge/native or installation credit.
"""
from pathlib import Path
import json
from collections import Counter
from run import ROOT,HERE,read,save,digest,connect,NATIVE_RUN
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from exact_original_shared_edge_component_census_v2_20261011 import census
from exact_original_finite_triangle_contacts_20261010 import exact_finite_contacts
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-beverly-hill-k-j-original-podium233218-provenance-complete-contact-v2-20261011';DOC=B/BATCH;CAPTURE=B/'government-xl-beverly-elm-complete-current-support-ground-capture-v2-20261011';SELECTION=B/'government-xl-seven-more-original-supports-current-inputs-20261007/check-selection.json.gz';IDENTITY=B/'xl-terrain-recovery-20261010-fresh-pair-identity-guard-checkpoints-v1/diagnostic.json.gz';RANK=B/'xl-terrain-recovery-20261010-next-current-native-cap-source-only-ranking-v1/diagnostic.json.gz';P='landsd/233218:0';SHA='5fd92d6e2e691795087421f5a528eb2d641cc82141f8960da319a4072281abef'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not DOC.exists();manifest=ROOT/'3d-viewer/city/data/manifest.json';start=ref(manifest);assert start['sha256']=='b61c0bc2d706793c7d436ef3334ccb41e93675d3d50c29818a2dca3b56f8830e';row=next(r for r in read(SELECTION)['rows']if r['uid']==P);sourcepath=ROOT/row['candidate']['path'];assert digest(sourcepath.read_bytes())==row['sourceSHA256']==SHA;entry=row['candidate']['entry'];assert entry['buildingCSUID']=='3722614969P20060312'and entry['modelId']=='B372261496902063C0'and entry['triangles']==4712 and row['native']['sheet']=='11-SW-15D';building=row['source']['building'];assert building['uid']==P and building['structureType']=='Podium'and building['parent']=='way/227077706'and building['base']==41.4 and building['topHeightHKPD']==75.9
 current=read(CAPTURE/'support-source-preflight.json');form=next(r['building']for r in current['fullCurrentRelevantForeignBasicAndNativeFormInventory']if r['building']['uid']==P);assert form==building;proof=next(r for r in read(IDENTITY)['rows']if r['uid']==P);assert proof['sourceSHA256']==SHA;assert proof['proof']['exactCurrentComponentRoute']['qualified']and proof['proof']['originalOwnership']['sourceGraphVerified'];assert not proof['proof']['passed'];assert set(proof['proof']['reasons'])==set(['fresh-current-spatial-bound:sourceExcessCoveredByUnrelatedFormsM2','fresh-current-spatial-bound:sourceExcessMaximumDistanceFromTargetM','full-source-maximum-extent','full-source-unrelated-overlap']);podium=decode_original_world_triangles(sourcepath.read_bytes());assert podium.shape==(4712,3,3)and digest(podium.tobytes())==proof['proof']['worldTrianglesSHA256'];parts=census(podium,list(range(len(podium))));byp={f:i for i,c in enumerate(parts['sharedEdgeConnectedComponents'])for f in c}
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');before=c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid',([P,'landsd/255543:0','landsd/255939:0'],)).fetchall();assert c.execute('SELECT r.result_sha FROM astra_modelling.native_stage_results r JOIN astra_modelling.native_stage_members m USING(cache_key) WHERE m.run_id=%s AND r.cache_key=%s',(NATIVE_RUN,row['native']['cacheKey'])).fetchone()==(row['native']['resultSha'],)
 refs=[ref(p)for p in [Path(__file__),manifest,sourcepath,SELECTION,IDENTITY,CAPTURE/'result.json',CAPTURE/'support-source-preflight.json',B/'government-xl-beverly-hill-k-j-original-podium233218-provenance-complete-contact-v1-20261011/result.json',B/'government-xl-beverly-hill-k-complete-current-carrier-strict-clearance-grade-exclusion-v1-20261011/result.json']];rank=next(r for r in read(RANK)['rows']if r['uid']=='landsd/255543:0');j=next(r for r in read(CAPTURE/'selection.json.gz')['rows']if r['uid']=='landsd/255939:0');rows=[]
 for uid,asset,sha in [('landsd/255543:0',ROOT/rank['cachedSource']['path'],rank['sourceSHA256']),('landsd/255939:0',ROOT/j['candidate']['path'],j['sourceSHA256'])]:
  assert digest(asset.read_bytes())==sha;tri=decode_original_world_triangles(asset.read_bytes());upperform=next(r['building']for r in current['fullCurrentRelevantForeignBasicAndNativeFormInventory']if r['building']['uid']==uid);assert upperform['parent']==building['parent']and upperform['structureType']=='Tower'and upperform['base']==building['topHeightHKPD'];censusupper=census(tri,list(range(len(tri))));byu={f:i for i,c in enumerate(censusupper['sharedEdgeConnectedComponents'])for f in c};contacts=exact_finite_contacts(podium,list(range(len(podium))),tri,list(range(len(tri))));positive=[r for r in contacts['contacts']if r['dimension']>0];pairs=Counter((byp[r['sourceFaceA']],byu[r['sourceFaceB']])for r in positive);rows.append(dict(uid=uid,sourceSHA256=sha,wholeOriginalFaces=len(tri),completeWorldSHA256=digest(tri.tobytes()),completeOriginalNonzeroBodyCensus=censusupper,completeOriginalPodiumToTowerFiniteContacts=contacts,positiveBodyPairs=[dict(podiumBody=a,upperBody=b,interfaces=n)for(a,b),n in sorted(pairs.items())],upperBodiesWithDirectPositivePodiumContact=sorted({b for(a,b)in pairs}),upperBodiesWithoutDirectPositivePodiumContact=sorted(set(byu.values())-{b for(a,b)in pairs}),rootOrStructuralAcceptance=False));refs.append(ref(asset));print(json.dumps(dict(uid=uid,faces=len(tri),bodies=len(censusupper['sharedEdgeConnectedComponents']),positiveInterfaces=len(positive),bodyPairs=rows[-1]['positiveBodyPairs'])),flush=True)
 refs.extend(ref(HERE/(n+'.py'))for n in ['exact_packed_world_geometry_20261009','exact_original_shared_edge_component_census_v2_20261011','test_exact_original_shared_edge_component_census_v2_20261011','exact_original_finite_triangle_contacts_20261010','exact_original_shell_intersections_20261009','exact_original_component_contacts_20261009']);refs.append(ref(RANK))
 for r in refs:assert ref(ROOT/r['path'])==r
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid',([P,'landsd/255543:0','landsd/255939:0'],)).fetchall()==before
 assert ref(manifest)==start;save(DOC/'diagnostic.json.gz',dict(uids=[P,'landsd/255543:0','landsd/255939:0'],sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,currentManifest=start,actualOriginalPodiumUID=P,sourceSHA256=SHA,providerModelId=entry['modelId'],providerCSUID=entry['buildingCSUID'],recordedBaseHKPD=41.4,recordedTopHKPD=75.9,sourceIdentityRoutingAndOwnershipEvidence=ref(IDENTITY),wholeSourceIdentityAccepted=False,rawHistoricalIdentityReasons=proof['proof']['reasons'],sameParent='way/227077706',wholeOriginalPodiumFaces=4712,completeOriginalPodiumWorldSHA256=digest(podium.tobytes()),completeOriginalPodiumNonzeroBodyCensus=parts,existingNativeRunResultSHA256=row['native']['resultSha'],nativeRun=NATIVE_RUN,exactRegistryProvenanceReadbackMatch=True,upperRows=rows,reviewRowsUnchanged=True,podiumCompleteCurrentGroundMissing=True,carrier255939StrictClearanceAndZeroGradeInterfacesPreserved=True,qualification='Recovered unchanged exact original4712facet government podium, exactUID/P-CSUID/provider/parent metadata and source graph ownership/fullcell projection evidence plus exact registry readback; whole-source spatial identity remains FALSE, allfour reasons preserved. Current frozen form equals source record. Metadata/recorded towerbase=podiumtop is a causal lead, not height/contact/root acceptance. Complete finite exact line/area contacts only; points receive no support credit. All original source-body/mount/foundation/foreign/native/fullactualPground/grade/current/runtime/browser obligations remain. No new source modelling, invented geometry, terrain proposal or reapproval.',evidenceRefs=refs))
if __name__=='__main__':main()
