"""Existing immutable source-only freezer; exact current actual mesh and unchanged review fence."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-beverly-podium233218-foreign70279-identity-attribution-v1-20261011';DOC=B/BATCH;CAP=B/'government-xl-beverly-podium233218-complete-current-ground-capture-v1-20261011';UIDS=['landsd/233218:0','landsd/255543:0','landsd/255939:0','landsd/70279:0'];METHOD=B/'government-xl-beverly-podium233218-foreign70279-identity-attribution-method-v1-20261011/README.md'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid',(UIDS,)).fetchall()
def main():
 before=state();d=read(DOC/'diagnostic.json.gz');assert not(DOC/'result.json').exists()and d['sourceOnly']and not d['currentAcceptance']and len(d['rawHistoricalIdentityReasons'])==4;s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);paths={DOC/'diagnostic.json.gz',METHOD};m.local_imports(HERE/'beverly_podium233218_foreign70279_identity_attribution_v1_20261011.py',paths);m.local_imports(Path(__file__),paths);m.declared_refs(d,paths);m.declared_refs(read(DOC/'complete-current-basic70279-geometry.json.gz'),paths);m.declared_refs(read(CAP/'review.json'),paths)
 summary=[]
 for h,x in d['allDistinctProofs'].items():
  c=x['rawCurrentFixedSpatialIdentityContext'];rows=x['allNonzeroProjectedExcessFacetAttributions'];summary.append(dict(worldSHA256=h,sourceExcessAreaM2=c['sourceExcessAreaM2'],sourceExcessMaximumDistanceFromTargetM=c['sourceExcessMaximumDistanceFromTargetM'],sourceExcessCoveredByUnrelatedFormsM2=c['sourceExcessCoveredByUnrelatedFormsM2'],allProjectedExcessBodies=sorted({r['genuineOriginalBody']for r in rows}),foreignExcessBodies=sorted({r['genuineOriginalBody']for r in rows if r['descriptiveForeignExcessAreaM2']>0}),farCoordinates=x['descriptiveMaximumExcessCoordinates'],allExactFiniteContacts=len(x['allExactFiniteContacts']),positiveContacts=x['positiveDimensionalContacts'],noncoplanarPositiveContacts=sum(c['dimension']>0 and not c['exactNonzeroPlanesCoplanar']for c in x['allExactFiniteContacts']),completeActualForeignFacets=x['completeActualForeignFaces']))
 note='Full4712source facets and allfour original/literal/left/balanced worlds vs112 actual production BASIC70279 facets; two distinct complete world tuples computed. '+json.dumps(summary)+'. Four fixed spatial identity failures retained, no source clipping/ownership intent/threshold waiver. All34 exact positive noncoplanar line contacts per tuple are raw surface intersections, no collision exemption or structural root. Actual BASIC estimated base/height is not authoritative original geometry; all other foreign/native obligations and genuine14sourcebody obligations remain unresolved.'
 (DOC/'REVIEW.md').write_text('# Podium spatial-identity and actual foreign intersection diagnostic\n\n'+note+'\n');save(DOC/'review.json',dict(uids=UIDS,finding=note,summaries=summary,sourceOnly=True,currentAcceptance=False,installationApproved=False,wholeSourceIdentityAccepted=False,architecturalIntentInferred=False,evidenceRefs=[ref(p)for p in sorted(paths)]));paths.update([DOC/'REVIEW.md',DOC/'review.json']);m.F.freeze(BATCH,'source-spatial-identity-and-actual-basic70279-finite-intersections-no-exemption',sorted(paths),dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],reviewStateUnchanged=True)))
if __name__=='__main__':main()
