"""Established source-only freezer; frozen source/identity fields are not acceptance."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-elm-tree-b-podium-frozen-source-identity-context-v1-20261011';DOC=B/BATCH;UIDS=['landsd/253874:0','landsd/258892:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid,snapshot_id',(UIDS,)).fetchall()
def main():
 before=state();d=read(DOC/'diagnostic.json.gz');assert d['sourceOnly']and not d['currentAcceptance']and not(DOC/'result.json').exists();s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);paths={DOC/'diagnostic.json.gz'};m.local_imports(HERE/'elm_tree_b_podium_frozen_source_identity_context_v1_20261011.py',paths);m.local_imports(Path(__file__),paths);m.declared_refs(d,paths);summary=[dict(uid=r['uid'],completeOriginalFaces=r['completeOriginalFaces'],fixedSpatialBoundsOnlyFailedFields=r['fixedSpatialBoundsOnlyFailedFields'],exactObjectAndCSUID=r['rawFixedSpatialIdentityContext']['exactObjectAndCSUID'],sourceExcessMaximumDistanceFromTargetM=r['rawFixedSpatialIdentityContext']['sourceExcessMaximumDistanceFromTargetM'],sourceExcessCoveredByUnrelatedFormsM2=r['rawFixedSpatialIdentityContext']['sourceExcessCoveredByUnrelatedFormsM2'])for r in d['rows']];note='Source-only immutable original TowerB12164 andP764 spatial context: '+json.dumps(summary)+'. Unchanged .95targetcoverage/10mextent/1m²unrelated-excess fields only. This is not full identity/current collision/root/foundation/foreign approval. Original99 linecontacts tobody269, all306tower bodies and Psinglebody; currentP223/764ordinaryfiniteburial,min−9.371756m and historical233656/253871 BASIC regressions remain. No current mutable capture, geometry/terrain edit, source role/architecture inference or acceptance.'
 (DOC/'REVIEW.md').write_text('# Elm Tree immutable source spatial context\n\n'+note+'\n');save(DOC/'review.json',dict(uids=UIDS,finding=note,summaries=summary,sourceOnly=True,currentAcceptance=False,installationApproved=False,wholeIdentityAccepted=False,evidenceRefs=[ref(p)for p in sorted(paths)]));paths.update([DOC/'REVIEW.md',DOC/'review.json']);m.F.freeze(BATCH,'elm-tree-frozen-original-source-fixed-spatial-identity-context-no-acceptance',sorted(paths),dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],reviewStateUnchanged=True)))
if __name__=='__main__':main()
