"""DRAFT established source-only freezer; no current/held/installed state changes."""
import importlib.util,json
from fractions import Fraction as F
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-elm-tree-b-podium-complete-original-authentic-tin-finite-v1-20261011';DOC=B/BATCH;UIDS=['landsd/253874:0','landsd/258892:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid,snapshot_id',(UIDS,)).fetchall()
def main():
 before=state();d=read(DOC/'diagnostic.json.gz');assert d['sourceOnly']and not d['currentAcceptance']and not d['terrainProposalCreated']and d['completeOriginalSourceFaces']==12928 and not(DOC/'result.json').exists();s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);paths={DOC/'diagnostic.json.gz'};m.local_imports(HERE/'elm_tree_b_podium_complete_original_authentic_tin_finite_v1_20261011.py',paths);m.local_imports(Path(__file__),paths);m.declared_refs(d,paths);summary=[dict(uid=r['uid'],completeOriginalFaces=r['completeOriginalFaces'],ordinaryFailingFaces=len(r['ordinaryFailingFaces']),coverageFailingFaces=len(r['coverageFailingFaces']),minimumCertifiedOrRefinedLowerM=r['minimumCertifiedOrRefinedLowerM'])for r in d['rows']];assert sum(r['completeOriginalFaces']for r in summary)==12928;note='Source-only whole unchanged Elm original B12164/P764 finite terrain diagnostic versus complete covering authentic11-SE-11C source facets: '+json.dumps(summary)+'. Existing>=−1/2 ordinary bounds distinct from strict-positive exposure, grade/root/body role. This is original-only: TowerB actual F32 is not captured or approved. No current drawn-ground, source datum shift, terrain proposal/seams, all306tower-body/path obligations, foreign/native protection or installation credit. Existing223actualcurrentPburial facets/min−9.371756m and historical233656/253871BASICregressions unchanged.'
 (DOC/'REVIEW.md').write_text('# Elm original authentic TIN finite diagnostic\n\n'+note+'\n');save(DOC/'review.json',dict(uids=UIDS,finding=note,summaries=summary,sourceOnly=True,currentAcceptance=False,installationApproved=False,gradeRootProved=False,terrainProposalCreated=False,evidenceRefs=[ref(p)for p in sorted(paths)]));paths.update([DOC/'REVIEW.md',DOC/'review.json']);m.F.freeze(BATCH,'elm-tree-full-original-authentic-tin-finite-diagnostic-no-current-acceptance',sorted(paths),dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],reviewStateUnchanged=True)))
if __name__=='__main__':main()
