"""DRAFT established source-only freezer; source incidence is not below-grade intent."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-elm-tree-podium-three-original-tin-negative-faces-causal-context-v1-20261011';DOC=B/BATCH;UIDS=['landsd/253874:0','landsd/258892:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid,snapshot_id',(UIDS,)).fetchall()
def main():
 before=state();d=read(DOC/'diagnostic.json.gz');assert d['sourceOnly']and not d['currentAcceptance']and d['wholeSingleGenuineBodyRetained']and not(DOC/'result.json').exists();s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);paths={DOC/'diagnostic.json.gz'};m.local_imports(HERE/'elm_tree_podium_three_original_tin_negative_faces_causal_context_v1_20261011.py',paths);m.local_imports(Path(__file__),paths);m.declared_refs(d,paths);summary=[dict(originalFace=r['originalSourceFace'],body=r['genuineBody'],minimumExactGapM=r['minimumExactGapM'],nonzeroVerticalFacet=r['nonzero3DVerticalFacet'],minimizingOriginalTINFacets=sorted({p['completeOriginalSheetFacet']for p in r['allExactMinimizingFinitePairs']}))for r in d['threeRawNegativeFacets']];assert [r['originalFace']for r in summary]==[102,103,104];note='Source-only causal attribution of three preserved original-TIN negative podiumfacets: '+json.dumps(summary)+'. All three belong to complete764-facet singlebody; full incident sourceface/corner coordinates and exact matching originalTIN facets bound. Source provider base/top metadata does not establish intentional below-grade function or a grade/root exemption. OriginalTIN alone fails wholepodium. All223actualcurrent negatives and233656/253871historical regressions unchanged. No source edits, changed terrain, current/F32 acceptance, body omission or native reapproval; meaningful recovery needs authoritative grade/source evidence or an explicitly evidenced altered-terrain method with complete 3D seam and all-current protectedactor proof.'
 (DOC/'REVIEW.md').write_text('# Elm original negative wall causal context\n\n'+note+'\n');save(DOC/'review.json',dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,finding=note,summaries=summary,evidenceRefs=[ref(p)for p in sorted(paths)]));paths.update([DOC/'REVIEW.md',DOC/'review.json']);m.F.freeze(BATCH,'elm-tree-three-original-tin-negative-wall-source-body-causal-context-no-acceptance',sorted(paths),dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],reviewStateUnchanged=True)))
if __name__=='__main__':main()
