"""DRAFT source-only completed whole original Stadium capture freezer; no spatial identity or root credit."""
import argparse,importlib.util,json
from pathlib import Path
import numpy as np
from run import ROOT,HERE,read,save,digest,connect
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-mongkok-stadium240332-complete-current-ground-capture-v1-20261011';DOC=B/BATCH;LOCAL=HERE/'local'/BATCH;PRIOR=B/'government-xl-mongkok-stadium-complete-original-far-extent-body-attribution-v1-20261011';UID='landsd/240332:0';SHA='896138f962db178400870c74c41d5eae3a2ba99e0c978fad49790956c0a50bdd';STATE_UIDS=[UID,'landsd/240527:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid,snapshot_id',(STATE_UIDS,)).fetchall()
def main():
 parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--manifest-sha256',required=True);args=parser.parse_args();assert not(DOC/'result.json').exists();before=state();scope=read(DOC/'capture-scope.json');pre=read(DOC/'source-preflight.json');old=read(PRIOR/'diagnostic.json.gz');assert scope['currentManifest']==pre['currentManifest']==ref(ROOT/'3d-viewer/city/data/manifest.json')and scope['currentManifest']['sha256']==args.manifest_sha256;assert scope['startEndAllInputsVerified']and scope['allCurrentTerrainPatchesPreserved']and scope['terrainCandidates']==[]and not scope['wholeSourceIdentityAccepted'];assert scope['rawHistoricalIdentityReasons']==pre['rawHistoricalWholeSourceIdentityReasons']==old['preservedIdentityReasons'];assert pre['sourceUninstalled']
 s=read(DOC/'selection.json.gz')['rows'][0];assert s['uid']==UID and s['sourceSHA256']==SHA;p=ROOT/s['candidate']['path'];assert digest(p.read_bytes())==SHA;source=decode_original_world_triangles(p.read_bytes());assert source.shape==(15456,3,3)and digest(source.tobytes())==old['completeOriginalWorldSHA256']==pre['completeOriginalWorldSHA256'];body=old['completeOriginalNonzeroBodyCensus'];assert len(body['sharedEdgeConnectedComponents'])==14 and body['completeOriginalFaceIds']==list(range(15456))and body['completeWorldTrianglesSHA256']==digest(source.tobytes());assert sorted(f for c in body['sharedEdgeConnectedComponents']for f in c)==sorted(body['completeRenderableFaceIds'])
 rt=read(LOCAL/'runtime-geometry.json.gz');a=read(DOC/'actual-render-geometry.json.gz');assert len(rt['rows'])==len(a['rows'])==1;r=rt['rows'][0];attr=a['rows'][0];assert r['uid']==attr['uid']==UID and r['index']==attr['completeOriginalIndex']and r['position']==attr['completeLiteralWorldPosition'];g=np.asarray(r['drawnGroundGeometry'],float).reshape(-1,3,3);assert len(g)==scope['completeActualRelevantGroundFaces']and digest(g.tobytes())==scope['completeActualRelevantGroundSHA256']
 spec=importlib.util.spec_from_file_location('reviewed_P_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);paths=set();m.local_imports(Path(__file__),paths);m.local_imports(HERE/'mongkok_stadium240332_complete_current_ground_capture_v1_20261011.py',paths)
 for folder in [DOC,LOCAL]:
  for p in folder.rglob('*'):
   if p.is_file():
    paths.add(p)
    if p.name.endswith('.json')or p.name.endswith('.json.gz'):m.declared_refs(read(p),paths)
 paths.update([PRIOR/'diagnostic.json.gz',PRIOR/'result.json']+[HERE/n for n in ['mongkok_stadium240332_current_actual_render_attributes_v1_20261011.mjs','mongkok_stadium240332_capture_module_closures_v1_20261011.mjs','literal_production_module_dependency_closure_20261010.mjs','actual_float32_model_matrix_bounds_20261011.mjs']])
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');receipt=read(PRIOR/'result.json');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(receipt['jobId'],)).fetchone()==('complete',receipt)
 note='Full15456 unchanged original Stadium/14 genuine bodies/15zeros, original/literal/explicit left/balanced actual attributes and complete relevant actualcurrentmakeTerrain Float32 ground. All source/form/catalogue/module/terrain inputs exact before/after fenced; no terrain proposal, replacement or geometry shift. Original historical source identity extent62/max12.871m/350.641m2outside persists unless a later separately reviewed narrowly typed62identity decision is implemented. Old native sparse70m terrain170below/658samples/min-2.024m remains explicitly historical/diagnostic only; source11/12/13 and every14body are not yet grounded. Protected installed240527 and foreign/native obligations unchanged; roof3 canopy architectural interpretation does not supply physical support/root/current approval. Capture current fields are diagnostic, zero acceptance/installation/grade/native-reapproval credit.'
 save(DOC/'review.json',dict(uid=UID,uids=STATE_UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,wholeSourceIdentityAccepted=False,sourceUninstalled=True,gradeRootCredit=False,nativeReapproval=False,sourceGeometryChanges=0,terrainGeometryChanges=0,currentManifest=scope['currentManifest'],sourceSHA256=SHA,completeOriginalWorldSHA256=digest(source.tobytes()),completeOriginalFaces=15456,genuineOriginalBodies=14,exactBodyCensusAndContacts=ref(PRIOR/'diagnostic.json.gz'),exactPriorSourceReceipt=ref(PRIOR/'result.json'),completeActualCurrentGroundFaces=len(g),completeActualCurrentGroundSHA256=digest(g.tobytes()),rawHistoricalIdentityReasons=old['preservedIdentityReasons'],rawHistoricalSparseTerrainCheck=scope['rawHistoricalSparseTerrainCheck'],sparseTerrainCheckNotCompleteOrFresh=True,fullCurrentProtectiveFormInventory=pre['allCurrentRelevantForeignBasicNativeForms'],finding=note,evidenceRefs=[ref(p)for p in sorted(paths)]));(DOC/'REVIEW.md').write_text('# Original Stadium actual current ground\n\n'+note+'\n');paths.update([DOC/'review.json',DOC/'REVIEW.md']);assert state()==before;save(DOC/'review-state-fence.json',dict(affectedUIDs=STATE_UIDS,before=before,after=state(),exactRowsUnchanged=True,modelReviewWrites=0));paths.add(DOC/'review-state-fence.json');result=m.F.freeze(BATCH,'uninstalled-original-stadium240332-complete-actual-current-ground-source-only',sorted(paths),dict(uids=STATE_UIDS,sourceOnly=True,currentAcceptance=False,wholeSourceIdentityAccepted=False,sourceUninstalled=True,rawHistoricalIdentityReasons=old['preservedIdentityReasons'],rawHistoricalSparseTerrainCheck=scope['rawHistoricalSparseTerrainCheck'],sparseTerrainCheckNotCompleteOrFresh=True,completeActualCurrentGroundFaces=len(g),completeActualCurrentGroundSHA256=digest(g.tobytes()),gradeRootCredit=False,nativeReapproval=False,modelReviewWrites=0));assert state()==before;assert ref(ROOT/'3d-viewer/city/data/manifest.json')==scope['currentManifest'];print(json.dumps(dict(jobId=result['jobId'],reviewRowsUnchanged=True,currentAcceptance=False)))
if __name__=='__main__':main()
