"""Established source-only freezer, full original Stadium/source TIN diagnostic."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-mongkok-stadium240332-complete-original-authentic-tin-finite-v1-20261011';DOC=B/BATCH;PRODUCER=HERE/'mongkok_stadium240332_complete_original_authentic_tin_finite_v1_20261011.py';UIDS=['landsd/240332:0','landsd/240527:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid,snapshot_id',(UIDS,)).fetchall()
def main():
 before=state();d=read(DOC/'diagnostic.json.gz');assert not(DOC/'result.json').exists()and d['sourceOnly']and not d['currentAcceptance']and not d['terrainProposalCreated']and not d['currentDrawnGround']and not d['foundationIntentInferred'];assert d['completeOriginalSourceFaces']==15456 and d['genuineOriginalBodies']==14 and len(d['zeroOriginalFaces'])==15 and len(d['allFaces'])==15456 and [r['sourceFace']for r in d['allFaces']]==list(range(15456));assert len(d['ordinaryFailingFacesByBody'])==14;s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);paths={DOC/'diagnostic.json.gz'};m.local_imports(PRODUCER,paths);m.local_imports(Path(__file__),paths);m.declared_refs(d,paths)
 summary=dict(completeOriginalSourceFaces=15456,completeRelevantOriginalTINFacets=d['completeRelevantOriginalTINFacets'],ordinaryFailures=len(d['ordinaryFailingFaces']),coverageFailures=len(d['coverageFailingFaces']),minimumCertifiedOrRefinedLowerM=d['minimumCertifiedOrRefinedLowerM'],strictPositiveNotCertifiedFaces=sum(not r['strictPositiveFiniteProved']for r in d['allFaces']))
 note='Complete unchanged15456 original Stadium source facets versus cached2026-08-27 original11NW14D TIN: '+json.dumps(summary)+'. Strict-positive not-certified counts retain conservative lower bounds and do not establish actual negative burial. Existing783 actualcurrent217ground ordinary failures/allfourstreams remain unchanged; cachedsourceTIN is not actual/current/proposed ground. No altered renderer mesh, foundation-intent inference, expected-foundation exposure, original/F32 root/cap/mount/body/identity acceptance, neighbour/native discharge or source height fitting. Genuine architecture and source-specific ground interfaces and exact protected-actor seam-compatible terrain proposal remain separate requirements.'
 (DOC/'REVIEW.md').write_text('# Original Stadium versus cached original government TIN\n\n'+note+'\n');save(DOC/'review.json',dict(uids=UIDS,finding=note,summary=summary,sourceOnly=True,currentAcceptance=False,installationApproved=False,foundationIntentInferred=False,gradeRootCredit=False,terrainProposalCreated=False,evidenceRefs=[ref(p)for p in sorted(paths)]));paths.update([DOC/'REVIEW.md',DOC/'review.json']);m.F.freeze(BATCH,'complete-original-tin-comparison-no-proposal-or-foundation-intent',sorted(paths),dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],reviewStateUnchanged=True)))
if __name__=='__main__':main()
