"""DRAFT unchanged whole original Stadium actual-current ground/fourstream capture.
Uninstalled source only; preserve full spatial identity failures and current terrain.
"""
import argparse,importlib.util,subprocess,json
from pathlib import Path
import numpy as np
from run import ROOT,HERE,read,save,digest
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-mongkok-stadium240332-complete-current-ground-capture-v1-20261011';DOC=B/BATCH;LOCAL=HERE/'local'/BATCH;UID='landsd/240332:0';SHA='896138f962db178400870c74c41d5eae3a2ba99e0c978fad49790956c0a50bdd';PRIOR=B/'government-xl-mongkok-stadium-complete-original-far-extent-body-attribution-v1-20261011';SELECTION=B/'government-xl-next-100-20261005/check-selection.json.gz'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def module(p):
 s=importlib.util.spec_from_file_location('reviewed_support_current_form_loader',p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--manifest-sha256');parser.add_argument('--preflight-only',action='store_true');args=parser.parse_args();row=next(r for r in read(SELECTION)['rows']if r['uid']==UID);asset=ROOT/row['candidate']['path'];assert digest(asset.read_bytes())==row['sourceSHA256']==SHA;tri=decode_original_world_triangles(asset.read_bytes());prior=read(PRIOR/'diagnostic.json.gz');assert tri.shape==(15456,3,3)and digest(tri.tobytes())==prior['completeOriginalWorldSHA256'];assert not prior['identityAccepted']and prior['preservedIdentityReasons']==['source-identity-fit'];raw_sparse=row['native']['model']['terrainCheck'];assert raw_sparse['method'].startswith('Deterministic source-order stratified sample') and raw_sparse['sampledVertices']==658 and raw_sparse['belowTerrainQuarterMetre']==170
 if args.preflight_only:print(json.dumps(dict(uid=UID,sourceSHA256=SHA,wholeFacets=15456,genuineBodies=14,mutableCurrentRead=False,executionApproved=False)));return
 assert args.manifest_sha256 and len(args.manifest_sha256)==64;assert not DOC.exists()and not LOCAL.exists();manifest=ROOT/'3d-viewer/city/data/manifest.json';start=ref(manifest);assert start['sha256']==args.manifest_sha256;current=read(manifest);pins={}
 def pin(p):h=digest(p.read_bytes());key=str(p.relative_to(ROOT));assert key not in pins or pins[key]==h;pins[key]=h
 catalogues=[ROOT/'3d-viewer'/url for url in current['officialModelCatalogues']];terrain=[ROOT/'3d-viewer'/r['url']for r in current['terrainPatches']]
 for p in [manifest,ROOT/'3d-viewer/city/data/terrain.json',Path(__file__),asset,SELECTION,PRIOR/'diagnostic.json.gz',PRIOR/'result.json',HERE/'mongkok_stadium240332_current_actual_render_attributes_v1_20261011.mjs',HERE/'mongkok_stadium240332_capture_module_closures_v1_20261011.mjs',HERE/'literal_production_module_dependency_closure_20261010.mjs',HERE/'actual_float32_model_matrix_bounds_20261011.mjs',HERE/'exact_packed_world_geometry_20261009.py',HERE/'xl-final-script-pass.py']+catalogues+terrain:pin(p)
 installed={}
 for cat in catalogues:
  for e in read(cat)['models']:assert e['uid']not in installed;installed[e['uid']]=e
 assert UID not in installed,'Previous uninstalled-source scope changed; separately reviewed capture needed';final=module(HERE/'xl-final-script-pass.py');lo,hi=tri.min((0,1)),tri.max((0,1));forms=final.load_forms([float(lo[0]-30),float(lo[2]-30),float(hi[0]+30),float(hi[2]+30)]);form,_,tile=next(r for r in forms if r[0]['uid']==UID);assert form==row['source']['building']and form['buildingCSUID']=='3583620831T20111031' and form==prior['historicalTargetForm']
 for f,_,t in forms:pin(ROOT/'3d-viewer'/t)
 entry=row['candidate']['entry'];assert entry['uid']==UID and entry['sha256']==SHA and entry['triangles']==15456;bounds=np.asarray(entry['worldBounds']);assert np.all(lo>=bounds[0]-1)and np.all(hi<=bounds[1]+1);dest=LOCAL/entry['asset'];dest.parent.mkdir(parents=True,exist_ok=True);dest.write_bytes(asset.read_bytes());row={**row,'candidate':dict(entry=entry,path=str(dest.relative_to(ROOT))),'source':dict(building=form,tile=tile,tileSHA256=ref(ROOT/'3d-viewer'/tile)['sha256'])}
 save(DOC/'selection.json.gz',dict(rows=[row],manifestSHA256=start['sha256']));save(DOC/'terrain-candidates.json',[]);save(LOCAL/'catalogue.json',dict(schemaVersion=1,kind='diagnostic-original-support-catalogue',crs='EPSG:2326',verticalDatum='Hong Kong Principal Datum',rootTranslation=[-834500,0,816500],models=[entry],counts=dict(packedModels=1)));save(LOCAL/'catalogue-index.json',dict(models=1,catalogues=['catalogue.json']));save(DOC/'source-preflight.json',dict(uid=UID,currentManifest=start,originalSource=ref(asset),priorCompleteBodyAndContactProof=ref(PRIOR/'diagnostic.json.gz'),priorSourceReceipt=ref(PRIOR/'result.json'),completeOriginalWorldSHA256=digest(tri.tobytes()),completeOriginalFacets=15456,genuineOriginalBodies=14,allCurrentCatalogueRefs=[ref(p)for p in catalogues],allCurrentTerrainRefs=[ref(p)for p in terrain],allCurrentRelevantForeignBasicNativeForms=[dict(building=f,tile=t,installedNative=f['uid']in installed)for f,_,t in forms],rawHistoricalWholeSourceIdentityReasons=prior['preservedIdentityReasons'],rawHistoricalSparseTerrainCheck=raw_sparse,sparseTerrainCheckNotCompleteOrFresh=True,wholeSourceIdentityAccepted=False,sourceUninstalled=True,noForeignRegressionDischarge=True,noWholeNativeReapproval=True,currentAcceptance=False))
 def fence():
  for p,h in pins.items():assert digest((ROOT/p).read_bytes())==h,p
 def call(args):fence();subprocess.run(args,cwd=ROOT,check=True);fence()
 rel=lambda p:str(p.relative_to(ROOT));call(['node',str(HERE/'mongkok_stadium240332_capture_module_closures_v1_20261011.mjs'),rel(DOC)+'/']);call(['node',str(HERE/'acceptance-metrics.mjs'),'--selection',rel(DOC/'selection.json.gz'),'--candidates',rel(LOCAL),'--terrain-candidates',rel(DOC/'terrain-candidates.json'),'--out',rel(DOC/'metrics.json'),'--geometry-out',rel(LOCAL/'runtime-geometry.json.gz')]);save(DOC/'literal-source-inputs.json.gz',dict(rows=[dict(uid=UID,path=row['candidate']['path'],entry=entry,building=form)],currentManifest=start,currentCatalogueRefs=[ref(p)for p in catalogues],evidenceRefs=[ref(DOC/'selection.json.gz'),ref(dest)]));call(['node',str(HERE/'mongkok_stadium240332_current_actual_render_attributes_v1_20261011.mjs'),rel(DOC/'literal-source-inputs.json.gz'),rel(DOC/'actual-render-geometry.json.gz')]);call(['node',str(HERE/'mongkok_stadium240332_capture_module_closures_v1_20261011.mjs'),rel(DOC)+'/','--verify'])
 runtime=read(LOCAL/'runtime-geometry.json.gz');actual=read(DOC/'actual-render-geometry.json.gz');assert len(runtime['rows'])==len(actual['rows'])==1;r=runtime['rows'][0];a=actual['rows'][0];assert r['uid']==a['uid']==UID and r['index']==a['completeOriginalIndex']and r['position']==a['completeLiteralWorldPosition'];ground=np.asarray(r['drawnGroundGeometry'],float).reshape(-1,3,3);assert len(ground)>0
 for name in ['completeLiteralWorldPosition','completeExplicitLeftAssociatedFloat32WorldPosition','completeExplicitBalancedFloat32WorldPosition']:
  points=np.asarray(a[name]).reshape(-1,3);assert np.all(points.min(0)>=bounds[0]-1)and np.all(points.max(0)<=bounds[1]+1),'Source outside complete actualground broadphase'
 for data in [runtime,actual,read(DOC/'metrics.json')]:
  for p,h in data.get('inputHashes',{}).items():assert digest((ROOT/p).read_bytes())==h
 fence();save(DOC/'capture-scope.json',dict(uid=UID,currentManifest=start,inputHashes=pins,startEndAllInputsVerified=True,completeActualRelevantGroundFaces=len(ground),completeActualRelevantGroundSHA256=digest(ground.tobytes()),actualGroundScope='Every complete productionmakeTerrain Float32 facet intersecting complete source bounds±1m; all literal/left/balanced positions contained. No proposed/authenticTIN override or clippedterrain.',allCurrentTerrainPatchesPreserved=True,terrainCandidates=[],wholeSourceIdentityAccepted=False,rawHistoricalIdentityReasons=prior['preservedIdentityReasons'],rawHistoricalSparseTerrainCheck=raw_sparse,sparseTerrainCheckNotCompleteOrFresh=True,currentAcceptance=False,installationApproved=False,gradeRootCredit=False,noForeignRegressionDischarge=True,nativeReapproval=False,sourceGeometryChanges=0,terrainGeometryChanges=0));print(json.dumps(dict(completeActualStadiumGroundFaces=len(ground),currentAcceptance=False)))
if __name__=='__main__':main()
