"""Established source-only freezer; exact original attribution, no foundation/role waiver."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-mongkok-stadium240332-buried-original-body-plane-attribution-v1-20261011';DOC=B/BATCH;PRODUCER=HERE/'mongkok_stadium240332_buried_original_body_plane_attribution_v1_20261011.py';UIDS=['landsd/240332:0','landsd/240527:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid,snapshot_id',(UIDS,)).fetchall()
def main():
 before=state();d=read(DOC/'diagnostic.json.gz');assert not(DOC/'result.json').exists()and d['sourceOnly']and not d['currentAcceptance']and not d['foundationIntentInferred']and not d['clearanceFailuresWaived'];assert d['completeOriginalFaces']==15456 and len(d['all15456OriginalLiteralPlaneProfiles'])==15456 and d['genuineOriginalBodies']==14 and len(d['zeroOriginalFaces'])==15;streams=d['allFourSavedFiniteFailureBodyAttributions'];assert len(streams)==4 and {r['stream']for r in streams}=={'original','literal','explicitLeftF32','explicitBalancedF32'} and all(len(r['completeBodyGroups'])==14 for r in streams);s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);paths={DOC/'diagnostic.json.gz'};m.local_imports(PRODUCER,paths);m.local_imports(Path(__file__),paths);m.declared_refs(d,paths)
 assert all(r['ordinaryFailures']==783 and {g['originalBody']:len(g['ordinaryFailingOriginalFaces'])for g in r['completeBodyGroups']if g['ordinaryFailingOriginalFaces']}=={0:743,11:20,13:20} and r['completeBodyGroups'][0]['originalLiteralPlaneCounts']=={'horizontal-up':34,'inclined-up':700,'inclined-down':8,'vertical':1}for r in streams)
 note='All15456 original literal planes/Y ranges assigned to14 genuine original bodies with15zero preserved; saved four-stream783 ordinary failures concentrate in body0(743),11(20),13(20), no finite rerun. Original body0 failing planes include34 horizontal-up,700 inclined-up,8 inclined-down,1vertical; detached11/13 failures are20inclined-up each. Literal normals/winding/plane tilts do not supply architectural function or foundations intent; original plane classes are not F32 normal reclassification. No whole-source finite waiver, terrain lowering/source shift, genuine grade root, cap/mount/body/current/identity acceptance. Actual current finite negatives, all source14body/foreign/native/runtime/extent obligations remain unchanged.'
 (DOC/'REVIEW.md').write_text('# Original Stadium buried-face attribution\n\n'+note+'\n');save(DOC/'review.json',dict(uids=UIDS,finding=note,sourceOnly=True,currentAcceptance=False,installationApproved=False,foundationIntentInferred=False,gradeRootCredit=False,evidenceRefs=[ref(p)for p in sorted(paths)]));paths.update([DOC/'REVIEW.md',DOC/'review.json']);m.F.freeze(BATCH,'original-plane-attribution-no-foundation-intent-or-finite-waiver',sorted(paths),dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],reviewStateUnchanged=True)))
if __name__=='__main__':main()
