"""DRAFT full unchanged original scene + explicit southwest detail; no source role/identity credit."""
from pathlib import Path
import json,numpy as np,matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.collections import PolyCollection
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
from run import ROOT,HERE,read,save,digest,connect
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
B=ROOT/'docs/astra-city/government-import';OLD=B/'government-xl-mongkok-stadium-complete-original-far-extent-body-attribution-v1-20261011';METHOD=B/'government-xl-mongkok-stadium-original-source-visual-primary-method-v2-20261011/METHOD.md';DOC=B/'government-xl-mongkok-stadium-complete-original-source-visual-context-v2-20261011'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not DOC.exists();d=read(OLD/'diagnostic.json.gz');r=read(OLD/'result.json')
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(r['jobId'],)).fetchone()==('complete',r)
 for e in r['evidenceRefs']:assert ref(ROOT/e['path'])==e
 asset=ROOT/d['source']['path'];assert ref(asset)==d['source'];tri=decode_original_world_triangles(asset.read_bytes());assert tri.shape==(15456,3,3)and digest(tri.astype('<f8').tobytes())==d['completeOriginalWorldSHA256'];census=d['completeOriginalNonzeroBodyCensus'];bodies=census['sharedEdgeConnectedComponents'];assert len(bodies)==14 and len(census['exactNonrenderingOriginalFaces'])==15;labels={f:k for k,fs in enumerate(bodies)for f in fs};far=[r['originalFace']for r in d['all62OriginalFarFaceAttributions']];assert len(far)==62 and all(labels[i]==0 for i in far);colormap=plt.get_cmap('tab20');colors=[colormap(labels.get(i,14))for i in range(len(tri))];ring=np.asarray(d['historicalTargetForm']['rings'][0],float);bounds=[tri.min((0,1)),tri.max((0,1))];DOC.mkdir();outputs=[]
 for cropped in [False,True]:
  fig,ax=plt.subplots(figsize=(9,8),dpi=200);ax.add_collection(PolyCollection(tri[:,:,[0,2]],facecolors=colors,edgecolors='none',alpha=.65));ax.add_collection(PolyCollection(tri[far][:,:,[0,2]],facecolors='red',edgecolors='red',linewidths=.25,alpha=.95));ax.plot(ring[:,0],ring[:,1],color='black',linewidth=1,label='Historical official target outline');ax.autoscale_view();ax.set_aspect('equal');ax.invert_yaxis();ax.set_xlabel('Original viewerX / East (m)');ax.set_ylabel('Original viewerZ (North decreasesZ)');ax.set_title('All15,456 original facets /14bodies; red=62far facets; no roles\n'+('Southwest detail: crop only'if cropped else'Complete plan bounds'));ax.annotate('N',xy=(.95,.95),xytext=(.95,.85),xycoords='axes fraction',ha='center',arrowprops=dict(arrowstyle='->'));ax.legend(loc='lower right')
  if cropped:ax.set_xlim(1287,1309);ax.set_ylim(-4299,-4320)
  filename='original-southwest-detail-plan.png'if cropped else'original-complete-plan.png';fig.tight_layout();fig.savefig(DOC/filename);plt.close(fig);outputs.append(dict(**ref(DOC/filename),width=1800,height=1600,all15456SourceFacetsSubmitted=True,detailCrop=cropped))
 for azimuth in [-60,120]:
  fig=plt.figure(figsize=(9,7),dpi=200);ax=fig.add_subplot(111,projection='3d');xyz=tri[:,:,[0,2,1]];ax.add_collection3d(Poly3DCollection(xyz,facecolors=colors,edgecolors='none',alpha=.8));ax.add_collection3d(Poly3DCollection(xyz[far],facecolors='red',edgecolors='red',linewidths=.2,alpha=1));lo,hi=bounds;ax.set_xlim(lo[0],hi[0]);ax.set_ylim(lo[2],hi[2]);ax.set_zlim(lo[1],hi[1]);ax.set_box_aspect([hi[0]-lo[0],hi[2]-lo[2],hi[1]-lo[1]]);ax.view_init(elev=26,azim=azimuth);ax.set_xlabel('OriginalX');ax.set_ylabel('OriginalZ');ax.set_zlabel('OriginalY / HKPD(m)');ax.set_title('Complete unchanged15,456face source context\nRed62far facets, body colors descriptive only');filename='original-complete-3d-'+str(azimuth)+'.png';fig.tight_layout();fig.savefig(DOC/filename);plt.close(fig);outputs.append(dict(**ref(DOC/filename),width=1800,height=1400,all15456SourceFacetsSubmitted=True,completeWholeSceneAxes=True,occlusionNotCertified=True))
 save(DOC/'context.json',dict(uid='landsd/240332:0',completeOriginalFaces=15456,genuineBodies=14,exactZeroFaces=15,allFarFaces=far,farFeatureDirection='southwest',orientationErratumForFrozenMethodV1=True,viewerEastingOffsetM=834500,viewerNorthingEquals816500MinusZ=True,source=d['source'],sourceWorldSHA256=d['completeOriginalWorldSHA256'],sourceOnly=True,currentAcceptance=False,identityAccepted=False,architectureRoleAccepted=False,geometryChanges=0,pixelWarp=False,sourceTextureChanges=False,outputs=outputs,qualification='Actual unchanged whole original source plan and full-scene3D submission plus explicitly cropped southwest detail. Diagnostic colors/overlays and geometric paths do not establish function/ownership/support/identity. Corrects earlier frozen method cardinal locator only; source numbers and provenance untouched. Every14body/15zero/62far-facet and full current/foreign/native/physical obligation remains.',evidenceRefs=[ref(p)for p in [Path(__file__),METHOD,OLD/'diagnostic.json.gz',OLD/'result.json',asset,HERE/'exact_packed_world_geometry_20261009.py']]));print(json.dumps(dict(outputs=len(outputs),allOriginalFaces=15456,farDirection='southwest',currentAcceptance=False)),flush=True)
if __name__=='__main__':main()
