import {loadOfficialModel,disposeOfficialModel} from '../../../3d-viewer/city/official-model-assets.js';
import * as THREE from '../../../3d-viewer/vendor/three.module.js';
/** Read-only full actual renderer attributes/matrices for unchanged complete original Mongkok Stadium landsd/240332:0. */
import {readFileSync,writeFileSync,existsSync} from 'node:fs';import {gunzipSync,gzipSync} from 'node:zlib';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {snapshotModuleClosure,verifyModuleClosure} from './literal_production_module_dependency_closure_20261010.mjs';
import {actualFloat32ModelMatrixPositions,positionBounds} from './actual_float32_model_matrix_bounds_20261011.mjs';
const root=new URL('../../../',import.meta.url),inputPath=process.argv[2],outputPath=process.argv[3],hashes={},sha=b=>createHash('sha256').update(b).digest('hex');
assert(inputPath?.startsWith('docs/astra-city/government-import/')&&outputPath?.startsWith('docs/astra-city/government-import/')&&!existsSync(new URL(outputPath,root)));
function bytes(path,expected){const u=new URL(path,root);assert(u.pathname.startsWith(root.pathname));const b=readFileSync(u);if(expected!==undefined)assert.equal(sha(b),expected);hashes[path]=sha(b);return b;}
const production=new URL('3d-viewer/city/official-model-assets.js',root),closure=snapshotModuleClosure(production,root);Object.assign(hashes,closure.inputHashes);
for(const p of ['source-scripts/city/government-import/mongkok_stadium240332_current_actual_render_attributes_v1_20261011.mjs','source-scripts/city/government-import/actual_float32_model_matrix_bounds_20261011.mjs','source-scripts/city/government-import/literal_production_module_dependency_closure_20261010.mjs'])bytes(p);
const input=JSON.parse(gunzipSync(bytes(inputPath)));assert.equal(input.rows.length,1);assert.deepEqual(input.rows.map(r=>r.uid),['landsd/240332:0']);const expected={'landsd/240332:0':['896138f962db178400870c74c41d5eae3a2ba99e0c978fad49790956c0a50bdd',15456]};
assert.equal(input.currentManifest.path,'3d-viewer/city/data/manifest.json');const manifest=JSON.parse(bytes(input.currentManifest.path,input.currentManifest.sha256));
assert.deepEqual(input.currentCatalogueRefs.map(r=>r.path),manifest.officialModelCatalogues.map(p=>'3d-viewer/'+p));for(const r of input.currentCatalogueRefs)bytes(r.path,r.sha256);
for(const r of input.evidenceRefs)bytes(r.path,r.sha256);

const lighting={night:{value:0},activity:{value:new THREE.Vector4()},retail:{value:0},elapsed:{value:0},shimmer:{value:0}},results=[];for(const r of input.rows){assert.equal(r.entry.uid,r.uid);assert.equal(r.entry.sha256,expected[r.uid][0]);assert.equal(r.entry.triangles,expected[r.uid][1]);
assert.equal(r.entry.buildingCSUID,r.building.buildingCSUID);const raw=bytes(r.path,r.entry.sha256);let model,result;
try{model=await loadOfficialModel({...r.entry,assetURL:'https://diagnostic.invalid/original.glb.gz'},r.building,lighting,{fetcher:async()=>new Response(raw)});model.group.updateMatrixWorld(true);const meshes=[],position=[],index=[],left=[],balanced=[];let offset=0;
 for(const mesh of model.meshes){const p=mesh.geometry.attributes.position,idx=mesh.geometry.index.array,m=mesh.matrixWorld.elements;const arithmetic=actualFloat32ModelMatrixPositions(p.array,m);meshes.push({completeOriginalVertexAttribute:Array.from(p.array),completeOriginalIndex:Array.from(idx),completeNormalAttribute:Array.from(mesh.geometry.attributes.normal.array),completeColorAttribute:Array.from(mesh.geometry.attributes.color.array),matrixWorldFloat64:Array.from(m),...arithmetic});const v=new THREE.Vector3();for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i).applyMatrix4(mesh.matrixWorld);position.push(...v.toArray());}for(const i of idx)index.push(i+offset);offset+=p.count;for(const v of arithmetic.leftAssociatedPerMultiplyAddFloat32WorldPosition)left.push(v);for(const v of arithmetic.balancedPerMultiplyAddFloat32WorldPosition)balanced.push(v);}
 assert.deepEqual(position,Array.from(model.record.modelGeometry.position));assert.deepEqual(index,Array.from(model.record.modelGeometry.index));assert.equal(index.length/3,expected[r.uid][1]);
 result={uid:r.uid,sourceSHA256:sha(raw),actualRenderMeshes:meshes,completeLiteralWorldPosition:position,completeOriginalIndex:index,completeExplicitLeftAssociatedFloat32WorldPosition:left,completeExplicitBalancedFloat32WorldPosition:balanced,completeLiteralWorldBounds:positionBounds(position),completeExplicitLeftAssociatedFloat32ModelMatrixWorldBounds:positionBounds(left),completeExplicitBalancedFloat32ModelMatrixWorldBounds:positionBounds(balanced),sourceGeometryChanges:0};
}finally{if(model)disposeOfficialModel(model);}results.push(result);}
assert(verifyModuleClosure(closure,root));for(const [p,h]of Object.entries(hashes))assert.equal(sha(readFileSync(new URL(p,root))),h);
writeFileSync(new URL(outputPath,root),gzipSync(JSON.stringify({rows:results,inputHashes:hashes,completeRecursiveProductionModuleClosure:closure,startEndAllInputsVerified:true,explicitArithmeticOnlyNotUniversalGPUCameraGuarantee:true,currentAcceptance:false,nativeReacceptance:false,sourceGeometryChanges:0})));console.log(JSON.stringify({completeOriginalFaces:15456,sourceGeometryChanges:0,currentAcceptance:false}));
