"""Existing source-only freezer with exact declared inputs and unchanged review-state fence."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-mongkok-stadium240332-complete-current-finite-ground-diagnostic-v1-20261011';DOC=B/BATCH;PRODUCER=HERE/'mongkok_stadium240332_complete_current_finite_ground_diagnostic_v1_20261011.py';UIDS=['landsd/240332:0','landsd/240527:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid,snapshot_id',(UIDS,)).fetchall()
def main():
 before=state();d=read(DOC/'diagnostic.json.gz');assert not(DOC/'result.json').exists()and d['sourceOnly']and not d['currentAcceptance']and not d['wholeSourceIdentityAccepted']and d['rawHistoricalIdentityReasons']==['source-identity-fit'] and d['captureReceiptStatusAndAllRefsVerified'] and d['currentManifestAndAllCaptureInputsFencedStartEnd'] and d['currentManifest']==ref(ROOT/'3d-viewer/city/data/manifest.json');s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);paths={DOC/'diagnostic.json.gz'};m.local_imports(PRODUCER,paths);m.local_imports(Path(__file__),paths);m.declared_refs(d,paths);proofs=list(d['allDistinctWholeSourceFiniteProofs'].values());assert all(x['completeFacetsAccounted']==15456 for x in proofs)
 bindings=d['allFourStreamBindings'];assert set(bindings)=={'original','literal','explicitLeftF32','explicitBalancedF32'} and len(bindings)==4;assert all(x['completeFaces']==15456 and x['proofTupleSHA256'] in d['allDistinctWholeSourceFiniteProofs'] for x in bindings.values())
 summary=[dict(completeFacets=x['completeFacetsAccounted'],ordinaryFailures=len(x['ordinaryFailingSourceFaces']),coverageFailures=len(x['coverageFailingSourceFaces']),ordinaryFinite=x['allOrdinaryFiniteProved'],strictPositiveFinite=x['allStrictPositiveFiniteProved'],minimumLowerM=x['minimumCertifiedOrRefinedLowerM'])for x in proofs];note='Every15456 original/literal/leftF32/balancedF32 source facet including15zero diagnosticfaces accounted against '+str(d['completeActualCurrentGroundFaces'])+' complete actual currentproduction terrain facets, byte-identical whole world tuple reuse only. Existing ordinary>=-1/2 and independently strict-positive exposure are separate. Results: '+json.dumps(summary)+'. Historical source62extent/350.641m2outside and all14 body/role/ground/foreign/native/runtime obligations remain independent. Body3 architectural canopy interpretation gives no physical support/root/current credit; source0-to1..10 proper surface contacts and disconnected11/12/13 remain separate. No grade root, source fit/elevation/terrain edit, whole-native/identity/current acceptance or historical waiver.'
 (DOC/'REVIEW.md').write_text('# Original Stadium whole-source finite-ground diagnostic\n\n'+note+'\n');save(DOC/'review.json',dict(uids=UIDS,finding=note,finiteSummaries=summary,sourceOnly=True,currentAcceptance=False,installationApproved=False,gradeRootCredit=False,wholeSourceIdentityAccepted=False,evidenceRefs=[ref(p)for p in sorted(paths)]));paths.update([DOC/'REVIEW.md',DOC/'review.json']);m.F.freeze(BATCH,'complete-original-stadium-current-finite-ground-no-root-or-identity-credit',sorted(paths),dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],reviewStateUnchanged=True)))
if __name__=='__main__':main()
