"""DRAFT all15456 unchanged original Stadium facets versus cached original11-NW-14D TIN.
Diagnostic only, not a terrain proposal or current/F32/support/identity acceptance.
"""
from pathlib import Path
from fractions import Fraction as F
import importlib.util,json,time,uuid,zipfile,zlib,numpy as np
from run import ROOT,HERE,read,save,digest,connect,reservations
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from exact_original_face_conservative_clearance_v5_20261010 import verify as finite
from exact_original_triangle_pair_column_gap_20261010 import verify as column
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-mongkok-stadium240332-complete-original-authentic-tin-finite-v1-20261011';DOC=B/BATCH;LOCAL=HERE/'local'/BATCH;OLD=B/'government-xl-mongkok-stadium-complete-original-far-extent-body-attribution-v1-20261011';CURRENT=B/'government-xl-mongkok-stadium240332-complete-current-finite-ground-diagnostic-v1-20261011';FOLDER=HERE/'local/government-xl-50-second-20260913/sheets/11-NW-14D';TERRAIN=FOLDER/'terrain/TERRAIN(TB)/T35250204000106E13/T35250204000106E13.gltf'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not DOC.exists();refs=[ref(Path(__file__)),ref(B/'government-xl-mongkok-stadium240332-complete-original-authentic-tin-method-v1-20261011/METHOD.md')]
 for folder in [OLD,CURRENT]:
  receipt=read(folder/'result.json')
  with connect()as c:
   c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(receipt['jobId'],)).fetchone()==('complete',receipt)
  for e in receipt['evidenceRefs']:assert ref(ROOT/e['path'])==e
  refs.extend(ref(folder/n)for n in ['result.json','diagnostic.json.gz'])
 o=read(OLD/'diagnostic.json.gz');current=read(CURRENT/'diagnostic.json.gz');asset=ROOT/o['source']['path'];assert ref(asset)==o['source'];world=decode_original_world_triangles(asset.read_bytes());assert world.shape==(15456,3,3)and digest(world.tobytes())==o['completeOriginalWorldSHA256'];assert current['allFourStreamBindings']['original']['completeWorldSHA256']==o['completeOriginalWorldSHA256'];refs.append(ref(asset));bodies=o['completeOriginalNonzeroBodyCensus']['sharedEdgeConnectedComponents'];labels={i:k for k,fs in enumerate(bodies)for i in fs};assert len(bodies)==14
 download=read(FOLDER/'original/download.json');directory=read(FOLDER/'directory/result.json');assert download['sheet']==directory['sheet']=='11-NW-14D'and download['sourceETag']==directory['etag']=='"371108f-6598a3054cfee"'and download['directorySHA256']==directory['directorySHA256']=='15448dc177cef3d0608a936a93c8e566ba9e2bed1511b129c3d6faad93a71cbb';assert download['revisionDate']=='2026-08-27T16:00:00+00:00'and directory['revision']==1787846400000
 archive=FOLDER/'original/11-NW-14D.zip';assert digest(archive.read_bytes())==download['sha256'];sourcefiles=[]
 with zipfile.ZipFile(archive)as z:
  for p in [TERRAIN,TERRAIN.with_suffix('.bin')]:
   name=str(p.relative_to(FOLDER/'terrain'));entry=next(r for r in download['entries']if r['name']==name);raw=p.read_bytes();assert len(raw)==entry['bytes']and digest(raw)==entry['sha256']and zlib.crc32(raw)==entry['sourceCRC32']and z.read(name)==raw;sourcefiles.append(ref(p));refs.append(ref(p))
 refs.extend(ref(p)for p in [FOLDER/'original/download.json',archive,FOLDER/'directory/result.json',FOLDER/'directory/zip-directory.bin']);assert digest((FOLDER/'directory/zip-directory.bin').read_bytes())==directory['directorySHA256']
 spec=importlib.util.spec_from_file_location('stadium_original_tin_decoder',HERE/'xl-second-pass.py');decoder=importlib.util.module_from_spec(spec);spec.loader.exec_module(decoder);decoder.LOCAL=LOCAL;whole=decoder.terrain_triangles(TERRAIN);assert whole.ndim==3 and whole.shape[1:]==(3,3)and len(whole)==109339 and np.isfinite(whole).all();lo=world.min((0,1));hi=world.max((0,1));keep=(whole[:,:,0].max(1)>=lo[0])&(whole[:,:,0].min(1)<=hi[0])&(whole[:,:,2].max(1)>=lo[2])&(whole[:,:,2].min(1)<=hi[2]);ground=whole[keep];assert len(ground)
 groundfile=LOCAL/'complete-original-tin-covering-whole-facets.json.gz';save(groundfile,dict(sourceSheet='11-NW-14D',sourceFiles=sourcefiles,sourceRevision=directory['revision'],sourceETag=directory['etag'],completeOriginalSheetFacets=len(whole),completeOriginalSheetSHA256=digest(whole.tobytes()),completeSelectedFacets=ground.tolist(),completeSelectedFacetIds=np.flatnonzero(keep).tolist(),completeSelectedFacetSHA256=digest(ground.tobytes()),sourceBounds=[lo.tolist(),hi.tolist()],selection='Every unmodified original whole facet whose closedXZ AABB meets complete source bounds; no clipping/slope filter/new height/terrain proposal. Cached original source revision, not fresh official availability or actual current ground.',currentDrawnGround=False));refs.append(ref(groundfile))
 for p in sorted((LOCAL/'terrain-repairs').rglob('*'))if(LOCAL/'terrain-repairs').exists()else []:
  if p.is_file():refs.append(ref(p))
 refs.extend(ref(HERE/(n+'.py'))for n in ['xl-second-pass','exact_packed_world_geometry_20261009','exact_original_face_conservative_clearance_v5_20261010','exact_original_projection_coverage_v2_20261010','exact_original_triangle_pair_column_gap_20261010']);claim=reservations.claim('stadium-original-tin-'+str(uuid.uuid4()),['immutable-source-proof:'+BATCH],batch=BATCH,ttl=3600);assert claim['ok'];lease=claim['reservation'];last=time.monotonic()
 try:
  binding=dict(producer=ref(Path(__file__)),source=ref(asset),completeWorldSHA256=digest(world.tobytes()),completeGroundSHA256=digest(ground.tobytes()),ground=ref(groundfile));checkpoint=LOCAL/'partial.json.gz';partial=read(checkpoint)if checkpoint.exists()else None;assert partial is None or partial['binding']==binding;faces=[]if partial is None else partial['allFaces'];assert [r['sourceFace']for r in faces]==list(range(len(faces)))
  for i in range(len(faces),len(world)):
   proof=finite(world[i],ground);lower=F(proof['exactCertifiedLowerClearanceM']);pieces=[]
   if proof['groundProjectionCovered']and lower< -F(1,2):
    pieces=[dict(originalGroundFace=j,proof=column(world[i],ground[j]))for j in proof['allProjectedBoundingCandidateOriginalGroundFacets']];gaps=[F(x['proof']['exactMinimumFiniteColumnGapM'])for x in pieces if x['proof']['exactClosedHorizontalProjectionsMeet']];assert gaps;lower=min(gaps)
   faces.append(dict(sourceFace=i,genuineOriginalBody=labels.get(i),completeFiniteProof=proof,allRefinedFiniteColumnPairs=pieces,exactLowerM=str(lower),ordinaryFiniteProved=bool(proof['groundProjectionCovered']and lower>=-F(1,2)),strictPositiveFiniteProved=bool(proof['groundProjectionCovered']and lower>0)))
   if time.monotonic()-last>=20:assert reservations.heartbeat(lease)['ok'];save(checkpoint,dict(binding=binding,allFaces=faces));print(json.dumps(dict(faces=len(faces),total=len(world))),flush=True);last=time.monotonic()
  save(checkpoint,dict(binding=binding,allFaces=faces,complete=True));assert reservations.heartbeat(lease)['ok'];assert all(ref(ROOT/r['path'])==r for r in refs);failed=[r['sourceFace']for r in faces if not r['ordinaryFiniteProved']];save(DOC/'diagnostic.json.gz',dict(uid='landsd/240332:0',source=ref(asset),completeOriginalWorldSHA256=digest(world.tobytes()),completeOriginalSourceFaces=15456,genuineOriginalBodies=14,zeroOriginalFaces=o['completeOriginalNonzeroBodyCensus']['exactNonrenderingOriginalFaces'],allFaces=faces,ordinaryFailingFaces=failed,coverageFailingFaces=[r['sourceFace']for r in faces if not r['completeFiniteProof']['groundProjectionCovered']],ordinaryFailingFacesByBody={k:[i for i in failed if labels.get(i)==k]for k in range(14)},minimumCertifiedOrRefinedLowerM=str(min(F(r['exactLowerM'])for r in faces)),completeRelevantOriginalTINFacets=len(ground),sourceOnly=True,currentAcceptance=False,installationApproved=False,terrainProposalCreated=False,geometryChanges=0,currentDrawnGround=False,originalOnlyNotFourStreamProof=True,ordinaryThresholdM='-1/2',strictPositiveSeparate=True,rawCurrent783FailuresPreserved=True,gradeRootProved=False,foreignNativeRegressionsDischarged=False,foundationIntentInferred=False,evidenceRefs=refs,qualification='Complete unchanged original15456 source faces versus exact cached original11-NW-14D TIN. Actual current217ground/783negativefaces remain independent and unchanged. This comparison cannot show foundations intentional, qualify genuine roots/caps/roles or authorize removal/lowering of any terrain. An authentic terrain recovery requires distinct exact bounded seam-compatible domain and complete current source/F32/foreign/native/installed240527 preservation. No candidate mesh or changed model height.'));print(json.dumps(dict(faces=len(faces),originalTINFaces=len(ground),ordinaryFailures=len(failed),currentAcceptance=False)),flush=True)
 finally:assert reservations.release(lease)['ok']
if __name__=='__main__':main()
