"""Nonaccepting complete Block6 role reconciliation over frozen current evidence."""
import importlib.util
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-parkview-block6-current-role-reconciliation-v1-20261011';DOC=B/BATCH
N=['fresh-current-physical-capture-v1','fresh-current-carrier-capture-v1','current-four-stream-source-proofs-v1','current-four-opening-guards-v3','fresh-current-bounded-route-binding-v1']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not DOC.exists();docs=[B/('government-xl-parkview-block6-'+n+'-20261011')for n in N];p,c,s,o,r=docs;raw=read(p/'current-raw-outcome.json');identity=read(p/'identity-proofs.json')['rows'][0];finite=read(s/'diagnostic.json.gz');opens=read(o/'diagnostic.json.gz');route=read(r/'diagnostic.json.gz');graph=read(B/'government-xl-parkview-block6-complete-original-support-paths-v1-20261011/diagnostic.json.gz');parts=graph['completeSourceEdgeBodyFaces'];struct=sorted(map(int,graph['completeConditionalParents']));visual=graph['unreachedBodies'];assert len(struct)==81 and visual==[78,79,80,83];sf=sorted(f for i in struct for f in parts[i]);vf=sorted(f for i in visual for f in parts[i]);assert len(sf)==10953 and len(vf)==88 and sorted(sf+vf)==list(range(11041));assert not set(sf)&set(vf)
 assert raw['identityPassed']and identity['passed']and read(p/'foundation.json')['rows'][0]['strictFoundationAccepted'];assert raw['reasons']==['ground-contact-unresolved','sampled-ground-gap-below-model-bottom'];assert all(not x['unprovedWholeFacetIDs']and x['all80ContactPathsRemainPositive']and x['all85OriginalBodiesRemainSingleNonzeroSharedEdgeBodies']for x in finite['rows']);assert opens['allFourStreamsPass'];assert len(route['rows'])==4 and all(x['exactCompleteTupleEqualToFrozenRouteAndCap']for x in route['rows']);neighbours=read(p/'neighbour-checks.json')['rows'];assert len(neighbours)==23 and not any(x['reasons']for x in neighbours);native=read(p/'native-neighbour-checks.json')['rows'];assert len(native)==5 and all(x['passed']for x in native)
 metric=read(p/'metrics.json')['rows'][0];validation=read(p/'validation.json');paths=[Path(__file__)];paths +=[d/'result.json'for d in docs];paths +=[p/'identity-proofs.json',p/'metrics.json',p/'validation.json',p/'foundation.json',p/'neighbour-checks.json',p/'native-neighbour-checks.json',p/'current-raw-outcome.json',s/'diagnostic.json.gz',o/'diagnostic.json.gz',r/'diagnostic.json.gz',HERE/'acceptance-metrics.mjs',HERE/'acceptance-policy.py'];historic=['government-xl-parkview-block6-complete-original-support-paths-v1-20261011','government-xl-parkview-block6-bounded-eligible-native-route-v2-20261011','government-xl-parkview-block6-bounded-original-clear-cap-probe-v1-20261011'];paths +=[B/n/'result.json'for n in historic]
 primary=B/historic[1];paths +=[primary/'original-roof-context.png',primary/'original-node-context.json']+[q for q in (primary/'primary').rglob('*')if q.is_file()]
 proposal=dict(uids=['landsd/255438:0','landsd/254491:0'],sourceSHA256=raw.get('sourceSHA256',finite['sourceSHA256']),currentManifest=raw['currentManifest'],proposedRoles=dict(positiveOriginalContactPathBodies=struct,positiveOriginalContactPathFaces=sf,lowerOpeningAssociatedVisualBodies=visual,lowerOpeningAssociatedVisualFaces=vf),completeFacePartition=True,allFourBoundStreamsProved=True,currentFiniteAndFoundationPassed=True,currentIdentityPassed=True,currentFullForeignFormScope=23,currentUnrelatedIntersectingForms=identity['freshCurrentIdentity']['unrelatedIntersectingForms'],currentForeignNeighbourFlags=0,retainedNativeBeforeAfterGuards=[dict(uid=x['uid'],passed=x['passed'],supportFraction=x['support']['supportFraction'],newlyWhollyBuried=x['terrain']['newlyWhollyBuried'])for x in native],numericRuntimeGuard=dict(checks=metric['checks'],lowRimChecks=metric['lowRimChecks'],samples='Every indexed-position vertex, every triangle centroid, plus low-rim edge interior samples spaced at most 1m in XZ; low rim means y <= catalogue bottom+0.35m.',height='Height on actual makeTerrain mesh facets clipped conservatively to candidate bounds+1m; makeTerrainSampler separately compared at each sampled point.',minSurfaceGap=metric['minSurfaceGap'],minLowGap=metric['minLowGap'],maxLowGap=metric['maxLowGap'],samplerDelta=metric['maxSamplerDelta'],wholeFacetProofSeparate=True),literalLoaderGuard=dict(loaderAccepted=validation['loaderAccepted'],checksPassed=validation['checksPassed'],exceptions=validation['exceptions'],concerns=validation['concerns']),qualifiedCarrierPath=route['qualifiedOriginalPath'],rawReasonsPreserved=raw['reasons'],proposedCausalRecovery='Replace only the direct-ground/root warning disposition with the bounded genuine carrier grade-wall/whole-exposed-edge/clear-cap positive contact path for the 81 original contact bodies; give four fully associated original roof opening bodies source visual roles only.',prohibitedCredits=['whole-native-body-ground-or-root-credit','point-only-bridge','partial-edge-mount','closed-solid-certification','architectural-function','camera-universal-F32-guarantee'],remaining=['independent-root-role-logic-review','role-aware-complete-staged-accepted-checkpoint','current-browser-runtime-and-all-publisher-guards','guarded-publisher-and-verified-receipt'],scriptFullAcceptancePassed=False,currentAcceptance=False,installationApproved=False,newlyInstalled=0,evidenceRefs=[ref(q)for q in paths])
 save(DOC/'review.json',proposal)
 (DOC/'REVIEW.md').write_text('''# Parkview Block6 current role reconciliation\n\nThe unchanged source has a complete, evidence-backed candidate recovery: 81 original positive-contact bodies (10,953 facets) connect to clear original carrier cap58400 through the bounded eligible grade-wall60333 path. Four separate original bodies78/79/80/83 (88 facets) qualify only as fully lower-opening-associated visual roof bodies. Every one of11,041 source facets passes the whole-facet current finite guard; all four original/literal/left/balanced streams are explicitly bound. This is a proposed role reconciliation, not current acceptance or installation.\n\nFresh exact identity and whole-cell coverage pass. The complete23-form current foreign scope has zero unrelated intersections and zero neighbour regression flags. All five retained native before/after guards pass with unchanged ground; their legacy negative clearance/buried counts remain, so this is not whole-carrier reacceptance. The literal production loader accepts1 model with1 check and0 exceptions. Both raw direct-ground warnings remain unchanged; a role-aware accepted-stage reconciliation is still required.\n\nThe numeric runtime guard samples every position vertex, every triangle centroid, and low-rim edge interiors spaced at most1m in XZ. Low-rim statistics use y<=catalogue bottom+0.35m. It compares actual makeTerrain mesh surface height against makeTerrainSampler, reporting34,149 samples/230 low-rim samples, minimum drawn gap2.926380695m, maximum low-rim gap13.857600775m, and zero sampler disagreement. This corrects the abbreviated 'samples model low vertices' sentence in the frozen fresh-physical review; the frozen receipts remain unchanged. Sampled metrics are not whole-surface proof: the separate exact finite receipt accounts for every original facet and complete actual ground.\n\nFresh carrier arrays and complete25,167-facet ground are bit identical to the frozen bounded route and paired440-cap-proof inputs in all four streams. Reuse binds the complete exact tuples; no repeated computations or tolerance changes. Facet54320 projection-gap failure and partly buried52248–52249 remain excluded. The old cap conservative lower bound remains inconclusive; only the exact finite paired refinement proves the cap.\n\nStandalone opening helperv3 independently rejects closed disconnected hitchhikers and degenerate hosts;11 tests pass. All four actual bodies retain their complete v2 band proofs verbatim. No exact-contact, structural root/bridge, closed solid, or equipment-function credit follows. Owner/contractor photos and the unchanged source roof PNG are context; precise architectural function remains unknown.\n\nRoot must review this role reconciliation and produce a complete staged accepted checkpoint, current browser/runtime and publisher closure, then guarded publication. No live asset, terrain, geometry, acceptance state, or held review was modified here.\n''')
 save(DOC/'evidence-scope.json',dict(closedEvidenceRefs=[ref(q)for q in paths],sourceOnly=True))
 z=importlib.util.spec_from_file_location('block6_roles_freezer',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(z);z.loader.exec_module(m);m.freeze(BATCH,'complete-current-source-role-reconciliation-v1',paths,dict(uids=proposal['uids'],sourceOnly=True,outcome='complete-source-role-recovery-proposed-awaiting-staged-acceptance',scriptFullAcceptancePassed=False,currentAcceptance=False,rawReasonsPreserved=raw['reasons'],proposedRoleCounts=dict(structuralBodies=81,structuralFaces=10953,visualBodies=4,visualFaces=88)))
if __name__=='__main__':main()
