"""Render unchanged provider source context only; no function/role/root inference."""
import numpy as np,json,gzip,struct,importlib.util
from pathlib import Path
from run import ROOT,HERE,read,save,digest
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-parkview-block17-original-roof-context-v2-20261011';D=B/BATCH;G=B/'government-xl-parkview-block17-complete-original-support-graph-v1-20261011';OPEN=B/'government-xl-parkview-block17-original-lower-opening-association-v3-20261011'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not D.exists();D.mkdir(parents=True)
 import matplotlib;matplotlib.use('Agg')
 import matplotlib.pyplot as plt
 from mpl_toolkits.mplot3d.art3d import Poly3DCollection
 r=read(G/'diagnostic.json.gz');p=ROOT/r['source']['path'];assert ref(p)==r['source'];raw=p.read_bytes();original=decode_original_world_triangles(raw);assert digest(original.tobytes())==r['completeOriginalWorldSHA256'];t=original[:,:,[0,2,1]];cs=r['completeSourceEdgeBodyFaces'];visible=np.flatnonzero(t[:,:,2].min(1)>=369);save(D/'visual-subset-scope.json',dict(completeOriginalWorldSHA256=digest(original.tobytes()),originalFaceIDs=list(map(int,visible)),renderOnlySelection='Unchanged original facets whose every vertex Y>=369m; original face geometry is not clipped or altered',notWholeSourceProof=True,sourceGeometryChanges=0));fig=plt.figure(figsize=(13,6),dpi=180)
 from matplotlib.collections import PolyCollection
 ax=fig.add_subplot(121);ax.add_collection(PolyCollection(t[visible,:,:2],facecolors='#cccccc',edgecolors='#555555',linewidths=.2,alpha=.55));ax.add_collection(PolyCollection(t[cs[62],:,:2],facecolors='red',edgecolors='black',linewidths=.5));v=t[cs[62]].mean((0,1));ax.annotate('body62',(v[0],v[1]),xytext=(v[0]+4,v[1]-2),arrowprops=dict(arrowstyle='->',color='red'),color='red');ax.set_xlim(3980,4013);ax.set_ylim(3254,3285);ax.set_aspect('equal');ax.set_xlabel('original world X');ax.set_ylabel('original world Z');ax.set_title('Original upper facets: every vertex Y >=369m')
 ax=fig.add_subplot(122,projection='3d');ax.add_collection3d(Poly3DCollection(t[visible],facecolors='#cccccc',edgecolors='#555555',linewidths=.2,alpha=.4));ax.add_collection3d(Poly3DCollection(t[cs[62]],facecolors='red',edgecolors='black',linewidths=.5));ax.text(v[0],v[1],v[2]+.5,'body62',color='red');ax.set_xlim(3980,4013);ax.set_ylim(3254,3285);ax.set_zlim(369,378);ax.set_box_aspect((33,31,9));ax.view_init(elev=30,azim=-60);ax.set_xlabel('original X');ax.set_ylabel('original Z');ax.set_zlabel('original Y');ax.set_title('Same original upper-facet subset; no role inferred')
 fig.tight_layout();fig.savefig(D/'original-roof-context.png');plt.close(fig)
 b=gzip.decompress(raw)if raw[:2]==b'\x1f\x8b'else raw;length,kind=struct.unpack_from('<II',b,12);gl=json.loads(b[20:20+length]);save(D/'original-node-context.json',dict(originalSourceSHA256=digest(raw),completeOriginalNodes=gl['nodes'],completeOriginalMeshes=[dict(name=m.get('name'),primitives=[dict(material=x.get('material'),attributes=x.get('attributes'),indices=x.get('indices'))for x in m['primitives']])for m in gl['meshes']],sourceOnly=True,roleApproval=False))
 refs=[ref(x)for x in [Path(__file__),p,G/'result.json',G/'diagnostic.json.gz',OPEN/'result.json',OPEN/'diagnostic.json.gz',HERE/'exact_packed_world_geometry_20261009.py']]
 save(D/'review.json',dict(uids=['landsd/256116:0'],sourceOnly=True,finding='Original provider geometry context, not a photograph or architectural intent. The ten-face body62 is highlighted in the explicitly recorded unchanged upper-facet visual subset (all vertex Y>=369m); the complete original source remains hash-bound. Exact source nodes/mesh attribute schemas retained. No function, solid, root/bridge, role approval or current acceptance inferred. Prior zero exact contact and two nonrendering original facets remain intact.',evidenceRefs=refs,currentAcceptance=False,installationApproved=False,newlyInstalled=0,sourceGeometryChanges=0,terrainChanges=0))
 spec=importlib.util.spec_from_file_location('block17_visual_freezer_v2',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');f=importlib.util.module_from_spec(spec);spec.loader.exec_module(f);f.freeze(BATCH,'original-source-roof-context-only-v2',[ROOT/x['path']for x in refs],dict(uids=['landsd/256116:0'],sourceOnly=True,currentAcceptance=False,scriptFullAcceptancePassed=False,currentHeldReasonsPreserved=True,nativeReacceptance=False,sourceGeometryChanges=0,terrainChanges=0,noArchitecturalFunctionClaim=True))
if __name__=='__main__':main()
