"""DRAFT standard source-only freezer for reviewed Science Museum directory lookup."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-science-museum-open-sided-fresh-official-allclass-directory-search-v1-20261011';DOC=B/BATCH;METHOD=B/'government-xl-science-museum-open-sided-fresh-official-allclass-source-search-method-v1-20261011/method.json';UIDS=['landsd/80343:0','landsd/83471:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid,snapshot_id',(UIDS,)).fetchall()
def main():
 before=state();d=read(DOC/'diagnostic.json.gz');assert d['sourceOnly']and not d['currentAcceptance']and d['sourceModelMemberRequests']==0 and not d['sourceGeometryAcquired']and not(DOC/'result.json').exists();assert d['preservedOriginalMuseumOverlapFaceCount']==63 and d['preservedRawForeignGuardOverlapM2']==1.855
 s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);paths={p for p in DOC.rglob('*')if p.is_file()};paths.add(METHOD);m.local_imports(HERE/'science_museum_open_sided_fresh_official_allclass_directory_search_v1_20261011.py',paths);m.local_imports(Path(__file__),paths);m.declared_refs(d,paths)
 summary=dict(stableCSUID='3631518015T20071227',stableCSUIDCurrentlyReturned=d['stableCSUIDCurrentlyReturned'],historicalBASICObjectId=d['historicalObjectId'],freshOfficialObjectId=d['freshStableCSUIDObjectId'],freshRecordedBaseHeight=d['freshRecordedBaseHeight'],freshRecordedTopHeight=d['freshRecordedTopHeight'],exactHistoricalObjectAndCSUIDReturned=d['exactObjectAndCSUIDCurrentlyReturned'],coveringSheetsByIndexFamily=d['coveringSheetsByIndexFamily'],expectedDirectoryCount=d['expectedDirectoryCount'],complete=d['completeBoundedFreshOfficialSearch'],boundedFreshDirectoryAbsence=d['boundedFreshDirectoryAbsence'],exactGeoRefCandidateDirectories=len(d['exactGeoRefSourceCandidates']),errors=d['errors'])
 note='Science Museum fresh source availability: '+json.dumps(summary)+'. ExactGeoRef matches only nominate source identifiers; they do not independently prove fullCSUID identity, uniqueness, placement or ownership. No model members acquired even for matches. Current official OBJECTID renumbering must remain distinct from historical BASIC IDs; null source height fields authorize no invented source elevations. Official index polygon search uses only genuine positive-area covering sheets with complete outline union coverage; projected sheet selection is not building/support proof. Complete negative supports absence only in the exact listed formats/families/revisions/ETags, never globally; any error prevents bounded absence. Existing63 Museum projected overlap sourcefaces and raw1.855m2 foreign guard remain, along with primary-plan registration and complete current source/body/ground/foreign/native/runtime gates. No source-body omission, new root/bridge, architecture function, ownership/placement exemption, terrain/geometry/review/pointer edits or installed credit.'
 (DOC/'REVIEW.md').write_text('# Science Museum source availability\n\n'+note+'\n');save(DOC/'review.json',dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,finding=note,summary=summary,evidenceRefs=[ref(p)for p in sorted(paths)]));paths.update([DOC/'REVIEW.md',DOC/'review.json']);m.F.freeze(BATCH,'science-museum-exact-csuid-allclass-covering-sheet-source-directories-no-acceptance',sorted(paths),dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,modelReviewWrites=0,pointerWrites=0,sourceModelMemberRequests=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],protectedReviewRowsUnchanged=True)))
if __name__=='__main__':main()
