"""DRAFT immutable source-specific held disposition; no review, ledger or pointer writes."""
from pathlib import Path
from fractions import Fraction
import importlib.util,json
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-science-museum-original-source-held-disposition-v1-20261011';DOC=B/BATCH;G=B/'government-xl-science-museum-original24-body-graph-bounded-grade-caps-v1-20261011';M=B/'government-xl-science-museum-original171-bounded-mount-grade-context-v1-20261011';C=B/'government-xl-science-museum-open-sided-original-gltf-identity-comparison-v3-20261011';UIDS=['landsd/80343:0','landsd/83471:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid,snapshot_id',(UIDS,)).fetchall()
def main():
 assert not DOC.exists();before=state();g=read(G/'diagnostic.json.gz');m=read(M/'diagnostic.json.gz');original=read(C/'diagnostic.json.gz')
 for folder in [G,M,C]:
  r=read(folder/'result.json')
  with connect()as c:
   c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(r['jobId'],)).fetchone()==('complete',r)
  for e in r['evidenceRefs']:assert ref(ROOT/e['path'])==e
 assert g['completeOriginalMuseumFaces']==11520 and g['completeOriginalMuseumNonzeroBodies']==24 and not g['qualifiedCapToBody0SurfaceInterfaceContexts'];facts=[]
 for body in [5,16]:
  r=next(x for x in g['completeTwoSourceBodyGradeCapRoutes']if x['originalMuseumBody']==body);nodes=[x for x in g['allExaminedWholeFacetProofs']if x['originalFace']in r['completeOriginalBodyFaces']];contacts=[x for x in g['allExactOriginalMuseumCrossBodyContacts']if set(x['originalNonzeroBodies'])=={0,body}];assert not contacts and not r['allStrictClearCapsReachedByWholeExposedEdges']and not any(x['strictClearUpwardCap']for x in nodes)
  if body==5:assert not r['allGenuineGradeFaces']and all(x['strictClear']for x in nodes)
  else:assert r['allGenuineGradeFaces']==[9798,9799,10076,10078]
  facts.append(dict(originalMuseumBody=body,wholeSourceFacetCount=len(nodes),strictClearFacets=sum(x['strictClear']for x in nodes),genuineGradeFaces=r['allGenuineGradeFaces'],upwardStrictCaps=0,finiteContactsWithBody0=0,minimumExactFiniteGapM=min((x['exactLowerM']for x in nodes),key=Fraction)))
 assert facts[0]['minimumExactFiniteGapM']=='217/1048576';assert len(m['all17InternalBothRelativeInteriorCrossingAttributions'])==17 and all(x['guardFailure']for r in m['completeOriginalBodyMountAndTopologyRows']for x in r['wholeMinimumOpeningAssociations']);assert m['body2DirectMuseumContactsPreserved']==46
 note='Source-held under completed bounded methods, not permanently rejected or proven corrupt. The unchanged original recovered171-face frontage actor is available with complete textures, but none of its five bodies passes the reviewed whole minimum-opening association. All11 proper body0/body1 crossings meet photographic frontage face69; six other internal crossings and53 Museum crossings remain open representation/joint obligations. Museum source bodies5/16 cannot carry contacted body0: neither has any exact finite contact with body0 or any qualifying original upward cap. Body5 is wholly strictly clear, including minimum +0.00020694732666015625m, so no genuine exact grade wall was found there. Body16 has exactly four genuine historical grade walls, but zero strict upward caps. No broader body0 support impossibility or current-ground conclusion follows.'
 revisit=['An independently evidenced genuine unchanged original Museum body0 grade/support path or a different complete original mount route, qualified by whole finite facets and whole exposed interfaces. Do not repeat failed bodies5/16 or whole minimum-opening methods with unchanged inputs.','A source-supported representation policy for every recovered original body and its photographic/open facade surfaces, retaining all exact crossing/topology/zero records; photo steel pixels cannot supply solid members or load support.','Complete current original/literal/left/balanced Float32 identity, actual ground, complete source/detail support, foreign/native preservation and runtime proofs. Original official footprint coverage90.75percent and historical63-face/1.855m2 foreign guard remain unresolved; no projection, pose, threshold or source exemption.']
 refs=[ref(p)for p in [Path(__file__),G/'diagnostic.json.gz',G/'result.json',M/'diagnostic.json.gz',M/'result.json',C/'diagnostic.json.gz',C/'result.json']];out=dict(uids=UIDS,decision='held-source-context',sourceOnly=True,sourceHeld=True,permanentRejection=False,sourceCorruptionProven=False,scopedMethodHoldOnly=True,currentAcceptance=False,installationApproved=False,newlyInstalled=0,modelReviewWrites=0,ledgerWrites=0,pointerWrites=0,geometryChanges=0,completeMuseumOriginalWorldSHA256=g['completeMuseumOriginalWorldSHA256'],completeRecoveredOriginalWorldSHA256=m['source171WorldSHA256'],historicalGroundSHA256=g['historicalCompleteGroundSHA256'],historicalOnly=True,exactBoundedRouteFacts=facts,completeGraphCensus=dict(possibleFacetPairs=g['completeCrossBodyFacetPairsConsidered'],exactAABBPairs=g['completeInclusiveUnpadded3DAABBPairsTested'],allFiniteContacts=len(g['allExactOriginalMuseumCrossBodyContacts'])),allFiveRecoveredBodyRolesRemainUnqualified=True,body2DirectMuseum46ContactsPreserved=True,allPriorNegativeEvidencePreserved=True,qualification=note,requiredChangedEvidence=revisit,evidenceRefs=refs);save(DOC/'diagnostic.json.gz',out)
 (DOC/'REVIEW.md').write_text('# Science Museum bounded source-held disposition\n\n'+note+'\n\nRequired changed evidence:\n\n'+'\n'.join('- '+x for x in revisit)+'\n');spec=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');f=importlib.util.module_from_spec(spec);spec.loader.exec_module(f);paths={p for p in DOC.rglob('*')if p.is_file()};f.local_imports(Path(__file__),paths);f.declared_refs(out,paths);f.F.freeze(BATCH,'science-museum-original-source-held-disposition-no-acceptance',sorted(paths),dict(uids=UIDS,sourceOnly=True,sourceHeld=True,currentAcceptance=False,installationApproved=False,governmentGeometryChanges=0,terrainGeometryChanges=0,modelReviewWrites=0,ledgerWrites=0,pointerWrites=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],sourceHeld=True,protectedReviewsUnchanged=True)),flush=True)
if __name__=='__main__':main()
