"""DRAFT reviewed source-only freezer: independently close acquisition, then comparison."""
import argparse,importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';A='government-xl-science-museum-open-sided-original-gltf-members-acquisition-v1-20261011';C='government-xl-science-museum-open-sided-original-gltf-identity-comparison-v1-20261011';F='government-xl-science-museum-open-sided-fresh-official-allclass-directory-search-v1-20261011';PLAN=B/'government-xl-science-museum-open-sided-original-source-acquisition-method-v1-20261011/plan.json';UIDS=['landsd/80343:0','landsd/83471:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute('SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s) ORDER BY uid,snapshot_id',(UIDS,)).fetchall()
def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('phase',choices=['acquisition','comparison']);phase=p.parse_args().phase;batch=A if phase=='acquisition'else C;doc=B/batch;before=state();assert not(doc/'result.json').exists();d=read(doc/('acquisition.json'if phase=='acquisition'else'diagnostic.json.gz'));assert d['sourceOnly']and not d['currentAcceptance']and not d['identityAccepted']and not d['conversionPerformed'];receipts=[B/F/'result.json']+([B/A/'result.json']if phase=='comparison'else[])
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY')
  for path in receipts:
   r=read(path);assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(r['jobId'],)).fetchone()==('complete',r)
 for e in d['evidenceRefs']:assert ref(ROOT/e['path'])==e
 if phase=='acquisition':assert d['sourceModelMemberRequests']==4 and len(d['completeOriginalMembers'])==4 and d['allOriginalTexturesPreserved'];summary=dict(modelId=d['modelId'],sourceFamily=d['sourceFamily'],revision=d['revision'],etag=d['etag'],sourceMembers=len(d['completeOriginalMembers']),allOriginalTexturesPreserved=True)
 else:summary=dict(modelId=d['originalModelId'],completeOriginalFaces=d['completeOriginalFaces'],completeOriginalPOSITIONVertices=d['completeOriginalPOSITIONVertices'],completeOriginalMuseumFaces=d['completeMuseumOriginalFaces'],projectionCentroidDistanceM=d['projectionCentroidDistanceM'],overlapOfSmallerFootprint=d['overlapOfSmallerFootprint'],exactPositiveOriginalMuseumSurfaceContacts=len(d['exactPositiveDimensionalOriginalMuseumSourceContacts']),pointOnlyContacts=len(d['pointOnlyOriginalMuseumContacts']),currentBASICContactReplayNotClaimed=True)
 note='Complete untouched individualised Science Museum open-sided source '+phase+': '+json.dumps(summary)+'. All original GLTF/bin/textures preserved, no source pose/Y fit, packing or conversion. Exact GeoRef/single member identity and descriptive footprint consistency are not fullCSUID/source placement acceptance; current object83412 remains distinct from historical BASIC83471. Null recorded heights supply no authored elevation. Original source contacts are surface context only, never full solid clearance, grade root, bridge or ownership exemption. Existing63 projected overlapfaces and rounded1.855m2 foreign guard, primary-plan registration and full current/F32/ground/foreign/native/runtime obligations remain. No model-review/native-registry/pointer/live/terrain/building geometry writes or installation credit.'
 spec=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);paths={p for p in doc.rglob('*')if p.is_file()};paths.update(receipts);paths.add(PLAN);producer=HERE/('science_museum_open_sided_original_gltf_members_acquisition_v1_20261011.py'if phase=='acquisition'else'science_museum_open_sided_original_gltf_identity_comparison_v1_20261011.py');m.local_imports(producer,paths);m.local_imports(Path(__file__),paths);m.declared_refs(d,paths)
 (doc/'REVIEW.md').write_text('# Science Museum original source '+phase+'\n\n'+note+'\n');save(doc/'review.json',dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,summary=summary,finding=note,evidenceRefs=[ref(p)for p in sorted(paths)]));paths.update([doc/'REVIEW.md',doc/'review.json']);m.F.freeze(batch,'science-museum-individualised-original-'+phase+'-no-acceptance',sorted(paths),dict(uids=UIDS,sourceOnly=True,currentAcceptance=False,installationApproved=False,governmentGeometryChanges=0,terrainGeometryChanges=0,modelReviewWrites=0,pointerWrites=0,qualification=note));assert state()==before;print(json.dumps(dict(jobId=read(doc/'result.json')['jobId'],phase=phase,protectedReviewsUnchanged=True)))
if __name__=='__main__':main()
