import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {gunzipSync} from 'node:zlib';import {appendFiniteOrdered,preflightCurrentActorCensus,preflightActualRenderMesh} from './current_geometry_capture_preflight_20261011.mjs';
const root=new URL('../../../',import.meta.url),read=p=>JSON.parse(gunzipSync(readFileSync(new URL(p,root)))),input=read('docs/astra-city/government-import/government-xl-lippo-tower-only-current-complete-inputs-v2-20261011/input.json.gz'),captured=read('docs/astra-city/government-import/government-xl-lippo-current-bound-six-roof-inputs-v4-20261011/actual-render-attribute-geometry.json.gz').rows.find(r=>r.uid==='landsd/239465:0').actualRenderMeshes[0],config={ownedUID:'landsd/239465:0',ownedFaces:3597,basicUID:'landsd/231645:0'};
function mesh(){const p=new Float32Array(captured.completeOriginalVertexAttribute),ix=new Uint32Array(captured.completeOriginalIndex),normal=new Float32Array(captured.completeNormalAttribute),color=new Float32Array(captured.completeColorAttribute),count=p.length/3;return {geometry:{attributes:{position:{array:p,itemSize:3,count},normal:{array:normal,itemSize:normal.length/count,count},color:{array:color,itemSize:color.length/count,count}},index:{array:ix}},matrixWorld:{elements:[...captured.matrixWorldFloat64]}};}
test('actual frozen current 21-form census has one native and retains basic podium',()=>assert.deepEqual(preflightCurrentActorCensus(input,config),{completeScopeForms:21,completeNativeActors:6637,capturedNearbyNativeActors:1}));
test('Polygon-as-native regression rejected',()=>{const x=structuredClone(input);x.completeCurrentForms.forEach(r=>r.existingNative=true);assert.throws(()=>preflightCurrentActorCensus(x,config));});
test('missing true current native flag rejected',()=>{const x=structuredClone(input);x.completeCurrentForms.find(r=>r.existingNative).existingNative=false;assert.throws(()=>preflightCurrentActorCensus(x,config));});
test('duplicate full native actor rejected',()=>{const x=structuredClone(input);x.completeCurrentNativeOriginalPOSITIONCensus.push(x.completeCurrentNativeOriginalPOSITIONCensus[0]);assert.throws(()=>preflightCurrentActorCensus(x,config));});
test('duplicate current form rejected',()=>{const x=structuredClone(input);x.completeCurrentForms.push(x.completeCurrentForms[0]);assert.throws(()=>preflightCurrentActorCensus(x,config));});
test('wrong source face count rejected',()=>{const x=structuredClone(input);x.rows[0].triangles--;assert.throws(()=>preflightCurrentActorCensus(x,config));});
test('unannounced terrain proposal rejected',()=>{const x=structuredClone(input);x.terrainProposal=[];assert.throws(()=>preflightCurrentActorCensus(x,config));});
test('actual frozen tower attribute/index/matrix schema passes',()=>assert(preflightActualRenderMesh(mesh()).completeIndexedFaces>0));
test('index beyond POSITION rejected',()=>{const x=mesh();x.geometry.index.array[0]=x.geometry.attributes.position.count;assert.throws(()=>preflightActualRenderMesh(x));});
test('nonfinite POSITION rejected',()=>{const x=mesh();x.geometry.attributes.position.array[0]=Infinity;assert.throws(()=>preflightActualRenderMesh(x));});
test('incomplete normal attribute rejected',()=>{const x=mesh();x.geometry.attributes.normal.count--;assert.throws(()=>preflightActualRenderMesh(x));});
test('nonaffine actual matrix rejected',()=>{const x=mesh();x.matrixWorld.elements[3]=1;assert.throws(()=>preflightActualRenderMesh(x));});
test('large native-sized arrays preserve all values and order without variadic argument limit',()=>{const source=Float32Array.from({length:200000},(_,i)=>Math.fround(i/7));const out=appendFiniteOrdered([],source);assert.deepEqual(new Float32Array(out),source);});
test('append forbids nonfinite arithmetic values',()=>assert.throws(()=>appendFiniteOrdered([],[0,NaN])));
test('append forbids boolean coercion',()=>assert.throws(()=>appendFiniteOrdered([],[false])));
