import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {gunzipSync} from 'node:zlib';
import {verifyDrawnBasicCarrier} from './lippo_current_basic_drawn_carrier_witness_v1_20261011.mjs';
const root=new URL('../../../',import.meta.url),g=JSON.parse(gunzipSync(readFileSync(new URL('docs/astra-city/government-import/government-xl-lippo-tower-only-current-complete-inputs-v4-20261011/complete-current-geometry.json.gz',root)))),p=g.completeCurrentBasicGeometry.find(r=>r.uid==='landsd/231645:0'),triangles=[];
for(let k=0;k<p.index.length;k+=3){const t=[];for(let j=0;j<3;j++)for(let d=0;d<3;d++)t.push(p.position[p.index[k+j]*3+d]);triangles.push(t);}
const expected={uid:p.uid,csuid:p.currentForm.buildingCSUID,completeTriangles:triangles};
const state={uid:p.uid,csuid:expected.csuid,completeDrawnTriangles:triangles,loaded:true,tileWanted:true,supportAvailable:true,tileGroupVisible:true,detailedActive:false,hidden:false,suppressed:false,nativeCatalogueEntry:false,bakedModelGeometry:false,meshMatrices:[p.identityModelMatrix]};
test('actual full284-face current BASIC fixture is source-preserving witness',()=>assert.equal(verifyDrawnBasicCarrier(expected,state).completeDrawnFaces,284));
test('triangle draw order differs but full oriented multiset unchanged',()=>{const s=structuredClone(state);s.completeDrawnTriangles.reverse();assert(verifyDrawnBasicCarrier(expected,s));});
for(const field of ['loaded','tileWanted','supportAvailable','tileGroupVisible'])test(field+' unavailable rejects',()=>{const s=structuredClone(state);s[field]=false;assert.throws(()=>verifyDrawnBasicCarrier(expected,s));});
for(const field of ['detailedActive','hidden','suppressed','nativeCatalogueEntry','bakedModelGeometry'])test(field+' cannot substitute for BASIC',()=>{const s=structuredClone(state);s[field]=true;assert.throws(()=>verifyDrawnBasicCarrier(expected,s));});
for(const [name,mutate]of [['wrong-csuid',s=>s.csuid='wrong'],['missing-face',s=>s.completeDrawnTriangles.pop()],['duplicate-face',s=>s.completeDrawnTriangles[0]=s.completeDrawnTriangles[1]],['changed-vertex',s=>s.completeDrawnTriangles[0][0]+=1],['reversed-orientation',s=>{const a=s.completeDrawnTriangles[0];s.completeDrawnTriangles[0]=a.slice(3,6).concat(a.slice(0,3),a.slice(6));}],['nonidentity-matrix',s=>s.meshMatrices[0][12]=1],['nonfinite-vertex',s=>s.completeDrawnTriangles[0][0]=NaN]])test(name+' rejects',()=>{const s=structuredClone(state);mutate(s);assert.throws(()=>verifyDrawnBasicCarrier(expected,s));});
