"""Publish the verified unchanged 1881 Heritage government podium."""
import importlib.util,json,subprocess,sys,uuid
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent));spec=importlib.util.spec_from_file_location('second',Path(__file__).with_name('xl-second-pass.py'));s=importlib.util.module_from_spec(spec);spec.loader.exec_module(s)
ROOT,HERE=s.ROOT,s.HERE;read,save,h,rel=s.read,s.save,s.h,s.rel
UID='landsd/264745:0';SUPPORT='landsd/208117:0';BATCH='government-xl-1881-20260914';CHECK=s.DOC/'third-pass/1881-heritage';LOCAL=s.LOCAL/'1881-install';STAGE=HERE/'accepted'/BATCH;DOC=s.DOC/'third-pass/1881-install'
sys.path.insert(0,str(HERE.parent/'model-review-ledger'));import ledger
spec=importlib.util.spec_from_file_location('direct',HERE/'integrate.py');direct=importlib.util.module_from_spec(spec);spec.loader.exec_module(direct)
def call(args):subprocess.run(args,cwd=ROOT,check=True)
def start():
 assert read(CHECK/'result.json')['passed'];resources=read(s.LOCAL/'third-pass-1881-heritage/reservation.json')['resources'];claim=s.reservations.claim('codex-xl-1881-import-'+str(uuid.uuid4()),resources,batch=BATCH);assert claim['ok'];save(LOCAL/'reservation.json',json.loads(json.dumps(claim['reservation'],default=str)));call([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(LOCAL/'reservation.json'),'--',sys.executable,__file__,'owned'])
def owned():
 receipt=LOCAL/'reservation.json';assert s.reservations.owns(read(receipt));result=read(CHECK/'result.json');assert result['passed'] and not result['reasons'] and result['aiCalls']==result['modelGeometryChanges']==0;support=read(CHECK/'source-support.json');assert support['resolved']==[SUPPORT] and support['rows'][0]['passed'] and support['aiCalls']==0;catalogue=read(STAGE/'catalogue.json');assert [m['uid'] for m in catalogue['models']]==[UID];model=catalogue['models'][0];assert h(STAGE/model['asset'])==model['sha256'];metrics=read(CHECK/'metrics.json');metric=metrics['rows'][0];assert metric['sourcePreserved'] and not metric['missingTerrain'];validation=read(CHECK/'validation.json');assert validation['loaderAccepted']==validation['checksPassed']==1 and validation['exceptions']==0 and not validation['results'][0]['concerns'];direct.browser_verified(CHECK/'staged-browser.json',{UID})
 decision={'policy':result['policy'],'uid':UID,'retainedSupportUid':SUPPORT,'sourceSHA256':model['sha256'],'catalogueSHA256':h(STAGE/'catalogue.json'),'planSHA256':h(STAGE/'plan.json'),'resultSHA256':h(CHECK/'result.json'),'sourceSupportSHA256':h(CHECK/'source-support.json'),'metricsSHA256':h(CHECK/'metrics.json'),'validationSHA256':h(CHECK/'validation.json'),'stagedBrowserSHA256':h(CHECK/'staged-browser.json'),'aiCallsThisImport':0,'geometryChanges':0};save(DOC/'decision.json',decision)
 pointer_path=ROOT/'docs/astra-city/model-integration-20260909/current-source-review.json';pointer=read(pointer_path);inventory=read(ROOT/pointer['inventory']);parts={p['uid']:p for p in inventory['parts']};previous=parts.get(UID,{});parts[UID]={'uid':UID,'name':model['label'],'landmarkIds':previous.get('landmarkIds',[]),'objectId':model['objectId'],'csuid':model['buildingCSUID'],'candidate':{'sha256':model['sha256']},'sourceProgress':'prepared-for-review','classification':'script-verified-original-government-supported-podium','knownHold':False};ordered=sorted(parts.values(),key=lambda row:row['uid']);snapshot=s.digest(s.jobs.encode([ordered,decision]).encode())[:16];inventory_path=pointer_path.parent/f'source-review-inventory-{snapshot}.json';save(inventory_path,{**inventory,'snapshotId':snapshot,'derivedFrom':pointer['snapshotId'],'parts':ordered});ledger.seed(inventory_path,inherit=pointer['snapshotId']);commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip();effort={'method':'scripted','ai_model':None,'reasoning_effort':'not-applicable','issue':'HKS-203','run_id':snapshot,'output_ref':rel(DOC/'decision.json')};observation='Exact unchanged 1881 Heritage government podium. Its separate basic tower remains visible and has complete source-roof support with a 4.7 cm overlap. Source integrity, foundation, runtime budget, staged/live browser, picking, collision and fallback/retry checks passed. No AI modelling, review or model geometry edits.';ledger.record_many(snapshot,receipt,[(UID,'approved-for-integration',DOC/'decision.json',observation,commit)],effort=effort,request_id=BATCH+'-approved-'+snapshot)
 publish=[sys.executable,str(HERE.parent/'model-integration-20260909/publish.py'),rel(STAGE/'plan.json'),'--receipt',str(receipt),'--phase',BATCH];call(publish);manifest=ROOT/'3d-viewer/city/data/manifest.json';before=manifest.read_bytes();(LOCAL/'manifest-before.json').write_bytes(before);call(publish+['--apply'])
 try:call(['node',str(HERE/'resolution-browser.mjs'),'live',rel(STAGE/'browser-config.json')]);direct.browser_verified(CHECK/'live-browser.json',{UID})
 except BaseException:manifest.write_bytes(before);raise
 acceptance={**decision,'snapshot':snapshot,'liveBrowserSHA256':h(CHECK/'live-browser.json'),'manifestSHA256':h(manifest)};save(DOC/'installed-acceptance.json',acceptance);ledger.record_many(snapshot,receipt,[(UID,'installed-verified',DOC/'installed-acceptance.json',observation,commit)],effort=effort,request_id=BATCH+'-installed-'+snapshot);assert read(pointer_path)==pointer;save(pointer_path,{**pointer,'snapshotId':snapshot,'inventory':rel(inventory_path),'previousSnapshots':[*pointer.get('previousSnapshots',[]),pointer['snapshotId']]});call([sys.executable,str(HERE.parent/'building-progress/export.py'),'--refresh']);call(['node',str(ROOT/'3d-viewer/scripts/build_progress.mjs')]);save(DOC/'summary.json',{'installedUids':[UID],'retainedSupportUid':SUPPORT,'snapshot':snapshot,'aiCalls':0,'geometryChanges':0,'progress':read(ROOT/'3d-viewer/city/data/building-progress.json')});print(json.dumps({'installed':UID,'retainedSupportUid':SUPPORT,'snapshot':snapshot,'aiCalls':0}))
if __name__=='__main__':owned() if len(sys.argv)>1 else start()
