"""Publish the verified Greenery Garden and Block C government assembly."""
import importlib.util,json,shutil,subprocess,sys,uuid
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent));spec=importlib.util.spec_from_file_location('second',Path(__file__).with_name('xl-second-pass.py'));s=importlib.util.module_from_spec(spec);spec.loader.exec_module(s)
ROOT,HERE=s.ROOT,s.HERE;read,save,h,rel=s.read,s.save,s.h,s.rel
BATCH='government-xl-greenery-garden-20260914';CHECK=s.DOC/'third-pass/greenery-garden';LOCAL=s.LOCAL/'third-pass-greenery-install';STAGE=HERE/'accepted'/BATCH;DOC=s.DOC/'third-pass/greenery-garden-install';SUPPORT='landsd/233384:0';TOWER='landsd/264029:0';UIDS=[SUPPORT,TOWER]
sys.path.insert(0,str(HERE.parent/'model-review-ledger'));import ledger
spec=importlib.util.spec_from_file_location('direct',HERE/'integrate.py');direct=importlib.util.module_from_spec(spec);spec.loader.exec_module(direct)
def call(args):subprocess.run(args,cwd=ROOT,check=True)
def start():
 result=read(CHECK/'assembly-result.json');assert result['passed'] and result['uids']==UIDS and not result['reasons'];resources=read(s.LOCAL/'third-pass-greenery-assembly/reservation.json')['resources'];claim=s.reservations.claim('codex-xl-greenery-import-'+str(uuid.uuid4()),resources,batch=BATCH);assert claim['ok'];save(LOCAL/'reservation.json',json.loads(json.dumps(claim['reservation'],default=str)));call([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(LOCAL/'reservation.json'),'--',sys.executable,__file__,'owned'])
def owned():
 receipt=LOCAL/'reservation.json';assert s.reservations.owns(read(receipt));result=read(CHECK/'assembly-result.json');assert result['passed'] and result['uids']==UIDS and not result['reasons'] and result['aiCalls']==result['modelGeometryChanges']==0;catalogue=read(STAGE/'catalogue.json');assert [m['uid'] for m in catalogue['models']]==UIDS and all(h(STAGE/m['asset'])==m['sha256'] for m in catalogue['models']);tower=next(m for m in catalogue['models'] if m['uid']==TOWER);assert tower['supportDependencies']==[{'uid':SUPPORT,'state':'candidate','csuid':next(m['buildingCSUID'] for m in catalogue['models'] if m['uid']==SUPPORT),'sha256':next(m['sha256'] for m in catalogue['models'] if m['uid']==SUPPORT)}];contact=read(CHECK/'support-contact.json');assert contact['row']['passed'] and contact['row']['within05']==contact['row']['rimSamples'];foundation=read(CHECK/'support-native-foundation.json');assert foundation['passed'] and foundation['fullyBuriedTriangles']==0;budget=read(CHECK/'assembly-budget.json');assert budget['measured']['mobilePassed'];metrics=read(CHECK/'assembly-metrics.json');assert {r['uid'] for r in metrics['rows']}==set(UIDS) and all(r['sourcePreserved'] and not r['missingTerrain'] for r in metrics['rows']);validation=read(CHECK/'assembly-validation.json');assert validation['loaderAccepted']==validation['checksPassed']==2 and validation['exceptions']==0;terrain=read(CHECK/'terrain-candidates.json')[0];assert h(ROOT/terrain['path'])==terrain['sha256'];neighbours=read(s.DOC/'third-pass/terrain-greenery-garden/neighbour-checks.json');assert not neighbours['patches'][0]['blockedBy'];direct.browser_verified(CHECK/'staged-browser.json',{TOWER})
 decision={'policy':result['policy'],'uids':UIDS,'sourceSHA256s':{m['uid']:m['sha256'] for m in catalogue['models']},'catalogueSHA256':h(STAGE/'catalogue.json'),'planSHA256':h(STAGE/'plan.json'),'resultSHA256':h(CHECK/'assembly-result.json'),'supportContactSHA256':h(CHECK/'support-contact.json'),'supportFoundationSHA256':h(CHECK/'support-native-foundation.json'),'terrainSHA256':terrain['sha256'],'validationSHA256':h(CHECK/'assembly-validation.json'),'stagedBrowserSHA256':h(CHECK/'staged-browser.json'),'aiCallsThisImport':0,'geometryChanges':0};save(DOC/'decision.json',decision)
 pointer_path=ROOT/'docs/astra-city/model-integration-20260909/current-source-review.json';pointer=read(pointer_path);inventory=read(ROOT/pointer['inventory']);parts={p['uid']:p for p in inventory['parts']}
 for model in catalogue['models']:
  previous=parts.get(model['uid'],{});parts[model['uid']]={'uid':model['uid'],'name':model['label'],'landmarkIds':previous.get('landmarkIds',[]),'objectId':model['objectId'],'csuid':model['buildingCSUID'],'candidate':{'sha256':model['sha256']},'sourceProgress':'prepared-for-review','classification':'script-verified-original-government-greenery-assembly','knownHold':False}
 ordered=sorted(parts.values(),key=lambda row:row['uid']);snapshot=s.digest(s.jobs.encode([ordered,decision]).encode())[:16];inventory_path=pointer_path.parent/f'source-review-inventory-{snapshot}.json';save(inventory_path,{**inventory,'snapshotId':snapshot,'derivedFrom':pointer['snapshotId'],'parts':ordered});ledger.seed(inventory_path,inherit=pointer['snapshotId']);commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip();effort={'method':'scripted','ai_model':None,'reasoning_effort':'not-applicable','issue':'HKS-203','run_id':snapshot,'output_ref':rel(DOC/'decision.json')};observation='Exact unchanged Greenery Garden and Block C government assembly passed same-sheet identity and foundation checks, exact mesh contact, native terrain, neighbour, mobile budget, staged/live browser, picking, collision and fallback/retry gates. No AI modelling, review, simplification or model geometry edits.';ledger.record_many(snapshot,receipt,[(uid,'approved-for-integration',DOC/'decision.json',observation,commit) for uid in UIDS],effort=effort,request_id=BATCH+'-approved-'+snapshot)
 publish=[sys.executable,str(HERE.parent/'model-integration-20260909/publish.py'),rel(STAGE/'plan.json'),'--receipt',str(receipt),'--phase',BATCH];call(publish);manifest=ROOT/'3d-viewer/city/data/manifest.json';before=manifest.read_bytes();(LOCAL/'manifest-before.json').write_bytes(before);call(publish+['--apply'])
 try:call(['node',str(HERE/'resolution-browser.mjs'),'live',rel(STAGE/'browser-config.json')]);direct.browser_verified(CHECK/'live-browser.json',{TOWER})
 except BaseException:
  manifest.write_bytes(before);shutil.rmtree(ROOT/'3d-viewer/city/data/official-models'/BATCH,ignore_errors=True);shutil.rmtree(ROOT/'docs/astra-city/model-integration-20260909'/BATCH,ignore_errors=True);(ROOT/'3d-viewer/city/data/government-native-264029-0.json').unlink(missing_ok=True);raise
 acceptance={**decision,'snapshot':snapshot,'liveBrowserSHA256':h(CHECK/'live-browser.json'),'manifestSHA256':h(manifest)};save(DOC/'installed-acceptance.json',acceptance);ledger.record_many(snapshot,receipt,[(uid,'installed-verified',DOC/'installed-acceptance.json',observation,commit) for uid in UIDS],effort=effort,request_id=BATCH+'-installed-'+snapshot);assert read(pointer_path)==pointer;save(pointer_path,{**pointer,'snapshotId':snapshot,'inventory':rel(inventory_path),'previousSnapshots':[*pointer.get('previousSnapshots',[]),pointer['snapshotId']]});call([sys.executable,str(HERE.parent/'building-progress/export.py'),'--refresh']);call(['node',str(ROOT/'3d-viewer/scripts/build_progress.mjs')]);save(DOC/'summary.json',{'installedUids':UIDS,'snapshot':snapshot,'aiCalls':0,'modelGeometryChanges':0,'progress':read(ROOT/'3d-viewer/city/data/building-progress.json')});print(json.dumps({'installed':UIDS,'snapshot':snapshot,'aiCalls':0}),flush=True)
if __name__=='__main__':owned() if len(sys.argv)>1 else start()
