"""Independent current HK80 basemap features at every far original low wall face."""
import math,sys,json,gzip,importlib.util,mapbox_vector_tile
from shapely.geometry import shape,mapping
from shapely.ops import transform
from run import ROOT,HERE,read,save,digest
sys.path.insert(0,str(HERE.parent/'landsd-territory'));from source import request
BATCH='government-xl-two-harbourfront-primary-owner-20261009';DOC=ROOT/'docs/astra-city/government-import'/BATCH;BASE='https://mapapi.geodata.gov.hk/gs/api/v1.0.0/vt/basemap/HK80'
def fetch(path,url,parameters=None,json_expected=False):
 assert not path.exists();raw,receipt=request(url,parameters,json_expected=False);path.parent.mkdir(parents=True,exist_ok=True);decoded=gzip.decompress(raw) if raw.startswith(b'\x1f\x8b') else raw;original=path.with_name(path.name+'.provider-original.gz') if raw!=decoded else path;original.write_bytes(raw);path.write_bytes(decoded if json_expected else raw);receipt['originalPath']=str(original.relative_to(ROOT));receipt['decodedSHA256']=digest(decoded);receipt['decodedBytes']=len(decoded);receipt['gzipDetected']=raw!=decoded;save(path.with_name(path.name+'.request.json'),receipt);return json.loads(decoded) if json_expected else raw
meta=fetch(DOC/'basemap-service.json',BASE,{'f':'pjson'},True);style=fetch(DOC/'basemap-style.json',BASE+'/resources/styles/root.json',None,True);info=meta['tileInfo'];assert info['spatialReference'].get('latestWkid',info['spatialReference']['wkid'])==2326
packet=read(ROOT/'docs/astra-city/government-import/xl-terrain-recovery-20261009-118230-original-components/far-original-source-faces.json');verts=[v for f in packet['faces'] for v in f['originalVertices']];xs=[v[0] for v in verts];zs=[v[2] for v in verts];bbox=[min(xs)-5,min(zs)-5,max(xs)+5,max(zs)+5];level=15;lod=next(l for l in info['lods'] if l['level']==level);width=lod['resolution']*info['cols'];ox=info['origin']['x'];oy=info['origin']['y'];emin,emax=bbox[0]+834500,bbox[2]+834500;nmin,nmax=816500-bbox[3],816500-bbox[1];tiles={(x,y) for x in range(math.floor((emin-ox)/width),math.floor((emax-ox)/width)+1) for y in range(math.floor((oy-nmax)/width),math.floor((oy-nmin)/width)+1)};rows=[]
for x,y in sorted(tiles):
 raw=fetch(DOC/f'vector-tiles/{level}-{x}-{y}.pbf',f'{BASE}/tile/{level}/{y}/{x}.pbf');decoded=mapbox_vector_tile.decode(gzip.decompress(raw) if raw.startswith(b'\x1f\x8b') else raw,default_options={'y_coord_down':True});save(DOC/f'vector-tiles/{level}-{x}-{y}-layers.json',{k:{'extent':v['extent'],'features':len(v['features'])} for k,v in decoded.items()})
 for name,layer in decoded.items():
  extent=layer['extent']
  for f in layer['features']:
   geom=transform(lambda xx,yy,zz=None:(ox+x*width+xx/extent*width-834500,816500-(oy-y*width-yy/extent*width)),shape(f['geometry']))
   if geom.intersects(shape({'type':'Polygon','coordinates':[[[bbox[0],bbox[1]],[bbox[2],bbox[1]],[bbox[2],bbox[3]],[bbox[0],bbox[3]],[bbox[0],bbox[1]]]]})):rows.append({'tile':[level,x,y],'layer':name,'id':f.get('id'),'properties':f.get('properties'),'geometry':mapping(geom),'quantizationStepM':width/extent})
selected=[l for l in style['layers'] if any(s in str(l.get('source-layer','')) for s in ['BuiltStructure','Carto','Topog'])];save(DOC/'current-original-feature-style-contract.json',{'layers':selected,'tileInfo':info,'qualification':'Exact unedited HK80 cartographic symbols and geometry; object function still needs measured source/feature correspondence.'});save(DOC/'decoded-original-local-feature-geometries.json.gz',{'rows':rows,'tileCount':len(tiles),'worldOrigin':[834500,816500],'sourcePacket':str((ROOT/'docs/astra-city/government-import/xl-terrain-recovery-20261009-118230-original-components/far-original-source-faces.json').relative_to(ROOT)),'sourcePacketSHA256':digest((ROOT/'docs/astra-city/government-import/xl-terrain-recovery-20261009-118230-original-components/far-original-source-faces.json').read_bytes()),'bbox':bbox,'sourceUntouched':True});print(json.dumps({'tiles':len(tiles),'features':len(rows),'properties':[(r['layer'],r['properties']) for r in rows],'styles':[(l['id'],l.get('filter')) for l in selected]}),flush=True)
