"""Persist exact-source primary-provider research and actionable identity dispositions.
No review/source/geometry mutation or installation approval; receipts stay immutable.
"""
import json,uuid,collections
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect,reservations,jobs,Jsonb,dict_row
BATCH='government-xl-identity-search-20261009';DOC=ROOT/'docs/astra-city/government-import'/BATCH;LOCAL=HERE/'local'/BATCH
SCOPE=ROOT/'docs/astra-city/government-import/government-xl-current-320-blocker-families-20261009/dispositions.json.gz'
def ref(p):return {'path':str(p.relative_to(ROOT)),'sha256':digest(p.read_bytes())}
def main():
 assert not (DOC/'result.json').exists(),'Immutable fresh checkpoint only'
 scope=read(SCOPE);live=read(DOC/'live-georef-research.json.gz');assert len(live['rows'])==190
 proofs={r['uid']:r for r in read(DOC/'current-positive-proof-bindings.json.gz')['rows']};metrics={r['uid']:r for r in read(DOC/'live-outline-metrics.json.gz')['rows']};packages={r['modelId']:r for r in read(DOC/'current-package-research.json.gz')['rows']};contexts={r['modelId']:r for r in read(DOC/'unmapped-context.json.gz')['rows']};old={r['sourceKey']:r for r in scope['rows']};rows=[]
 for r in live['rows']:
  p=proofs.get(r['uid']);source=old[r['sourceKey']];attrs=next((c['attributes'] for c in r['officialCandidates'] if c['sourceCurrentExactCSUIDMatches']),{})
  if p:state='identity-resolved-physical-held';action='Continue exact-source physical support/terrain/runtime investigation; suppress historical raw identity failures only in current human status, preserve receipts.';cause='previous-full-identity-passed-exact-current-forms'
  elif r['uid'] is None:state='provider-source-gis-lineage-unresolved';cause='current-source-exists-but-exact-current-gis-route-absent';action='Retrieve provider B1000 CSUID reassignment/merge/split history for old GeoRef and candidate current identifiers; current GLTF/FBX names are not ownership proof. Retain current basic; no source-version obsolete conclusion from absence.'
  elif r['state']=='no-exact-type-official-feature':state='provider-source-classification-mismatch';cause='model-id-subtype-disagrees-with-current-provider-block-type';action='Reconcile exact provider modelId subtype with current GIS Tower/Podium/open-sided classification using source contract/corrected provider revision. Retain current model; no corrupt/permanent rejection.'
  else:
   state='complete-original-component-coverage-unresolved';action='Establish complete source component ownership from official/owner site plans or provider component metadata; then rerun full-original coverage, extent, unrelated overlap and complete physical/runtime acceptance. No geometry suppression or threshold waiver.'
   reasons=r['reasons'];cause=next((tag for tag in ['runtime-original-footprint-fit','full-source-extent-exceeds-10m','source-overlaps-unrelated-current-forms','target-footprint-coverage-below-0.95','current-original-target-whole-georef-cell','source-identity-fit'] if any(tag in x for x in reasons)),'exact-source-identity-or-component-coverage-investigation')
  item={k:r[k] for k in ('uid','sourceKey','sourceSHA256','modelId','geoRefNo','expectedType')};item.update(name=attrs.get('BuildingNameEN') or r['name'],humanStatus='held for AI processing',identityState=state,currentReason=cause,nextStep=action,historicalReasons=source['reasons'],previousDispositionJobId=source['jobId'],officialLookupState=r['state'],officialCandidates=r['officialCandidates'],primaryURLs=['https://portal.csdi.gov.hk/csdi-webpage/metadata/landsd_rcd_1637211194312_35158/html','https://www.hkmapmeta.gov.hk/mcs/home/web/data/lands/b1000.faq.html','https://static.csdi.gov.hk/csdi-webpage/download/common/5fae157cd31d217e580ea22cd65cc3e12f4bd55a26bf26339693b2865204ae1e'],identityAccepted=False,installationApproved=False,installed=False,inProcess=False,permanentRejection=False,retainCurrentModel=True,revisitLater=True,aiGeometryModelling=False,modelGeometryChanges=0)
  if p:item.update(previousPositiveIdentity=p,identityPreviouslyPassed=True,humanStatus='held for compute processing')
  if r['uid'] in metrics:item['freshOfficialOutlineFullOriginalMeasures']=metrics[r['uid']]
  if r['modelId'] in packages:item.update(currentPackageResearch=packages[r['modelId']],nearbyGISContext=contexts[r['modelId']],exactCurrentGISLineageEstablished=False)
  rows.append(item)
 counts=dict(collections.Counter(r['identityState'] for r in rows));reasons=dict(collections.Counter(r['currentReason'] for r in rows));assert counts=={'identity-resolved-physical-held':5,'complete-original-component-coverage-unresolved':179,'provider-source-classification-mismatch':2,'provider-source-gis-lineage-unresolved':4}
 save(DOC/'actionable-dispositions.json.gz',{'rows':rows,'counts':counts,'reasonCounts':reasons,'historicalIdentityFamily':190,'currentUnresolvedIdentity':185,'newlyInstalled':0,'publication':False})
 save(DOC/'primary-source-research.json',{'sources':[{'url':'https://www.hkmapmeta.gov.hk/mcs/home/web/data/lands/b1000.faq.html','finding':'GeoRef decimals truncated, creating 1m cell; historical reassignment/merge/split operations and previous O_BLDG_CSUID exist in documented B1000 data contract. Public outline response lacks those lineage fields.'},{'url':'https://www.landsd.gov.hk/en/survey-mapping/mapping/3d-mapping.html','finding':'Individualised, non-textured and tile-based maps are distinct. Current 4sheet public index exposes glTF, FBX and MAX; no 3DS URL in returned current index.'},{'url':'https://www.hkia.net/en/awards-gallery/2/hkia-awards/detail/255','finding':'Mariners Club site has redevelopment to50storeyKimpton. This provides current site chronology only; originalB3601717386 mesh is not proved tobe formerclub because oldmeshbounds extend outside currentKimpton footprint.'},{'url':'https://www.hkexnews.hk/listedco/listconews/sehk/2024/1007/2024100700635.pdf','finding':'SHKP describes office/retail WestKowloonTerminus project. Current20260615ONEIGC/PingAnTower GIS IDs near oldpodium are useful lineage leads; no exactoldsourceownership established.'},{'url':'https://www.peninsula.com/en/-/media/news-room/about-us/story_bureau_phk_fact_sheet_gold_08flr_20190923.pdf','finding':'Sixstorey1928original plus30storey1994tower explains multi-part site context but does not override Podium02 vs Tower GIS conflict.'},{'url':'https://www.lcsd.gov.hk/dept/annualrpt/2007-08/eng/ls/content03.htm','finding':'TaiPoWaterfrontPark32mlookout identifies a plausible complexmesh investigation; this is site context, not whole component ownership approval.'}], 'qualification':'New authoritative context searches supplement cohort-level provider queries; proximity, site redevelopment dates, names and source member availability do not prove mesh ownership or obsolescence.'})
 paths=[Path(__file__),SCOPE,*sorted(DOC.glob('*.json')), *sorted(DOC.glob('*.json.gz')),*sorted(HERE.glob('xl-identity-search-20261009-*.py')),*sorted((LOCAL/'fresh-directories').glob('*/result.json')),*sorted((LOCAL/'fresh-directories').glob('*/transfer.json')),*sorted((LOCAL/'fresh-directories').glob('*/zip-directory.bin')),*sorted((LOCAL/'fbx-directories').glob('*/result.json')),*sorted((LOCAL/'fbx-directories').glob('*/transfer.json')),*sorted((LOCAL/'fbx-directories').glob('*/zip-directory.bin'))]
 refs=[ref(p) for p in sorted(set(paths))];refs += [r['proofRef'] for r in proofs.values()]
 claim=reservations.claim('xl-identity-search-checkpoint-'+str(uuid.uuid4()),['source-context:'+BATCH],batch=BATCH,ttl=1800);assert claim['ok'],claim;lease=claim['reservation']
 try:
  stage='primary-provider-current-source-identity-research-v1';payload={'evidenceRefs':refs,'sourceKeys':[r['sourceKey'] for r in rows],'sourceScope':190};jid=jobs.enqueue(BATCH,stage,payload);job=jobs.claim(BATCH,lease['owner'],[stage],lease_seconds=1800);assert job and job['id']==jid
  result={**payload,'jobId':jid,'batch':BATCH,'stage':stage,'rows':rows,'counts':counts,'reasonCounts':reasons,'inputManifestSHA256':scope['manifestSHA256'],'completionManifestSHA256':digest((ROOT/'3d-viewer/city/data/manifest.json').read_bytes()),'currentUnresolvedIdentity':185,'priorFullIdentityPassesVerified':5,'freshProviderGeoRefLookups':190,'freshCurrentPackageDirectories':8,'changedProviderOutlineDiagnostics':20,'newPositiveCandidates':0,'newlyInstalled':0,'publication':False,'modelGeometryChanges':0,'scriptExternalAICalls':0,'aiGeometryModelling':False,'qualification':'Exact current-source research checkpoint. Five complete positive identity receipts match current forms and are verified in Neon; historical failures stay immutable. 179 full component ownership/coverage investigations,2provider-source subtype conflicts and4exactGISlineage investigations remain. Fresh20outline measurements produce0newpositives. FourcurrentGLTFdirectories preserveoriginalmembers and currentFBXdirectories containsameIDs; no unsupportedobsolescence/corrupt/permanentrejection/installationcredit.'}
  with connect() as c:
   c.row_factory=dict_row;c.execute('SELECT pg_advisory_xact_lock(%s)',(reservations.LOCK_ID,));assert reservations._current(c,lease)
   for item in refs:assert ref(ROOT/item['path'])==item
   for p in proofs.values():assert c.execute('SELECT status FROM astra_modelling.jobs WHERE id=%s',(p['parentJobId'],)).fetchone()['status']=='complete'
   assert c.execute("UPDATE astra_modelling.jobs SET status='complete',result=%s,owner=NULL,token=NULL,lease_until=NULL,updated_at=clock_timestamp() WHERE id=%s AND owner=%s AND token=%s AND status='running' AND lease_until>clock_timestamp()",(Jsonb(result),jid,job['owner'],job['token'])).rowcount==1
  with connect() as c:
   c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(jid,)).fetchone()==('complete',result)
  save(DOC/'result.json',result);save(DOC/'neon-sync.json',{'jobId':jid,'resultVerified':True});print(json.dumps({'jobId':jid,'counts':counts,'reasonCounts':reasons,'neonVerified':True}),flush=True)
 finally:assert reservations.release(lease)['ok']
if __name__=='__main__':main()
