"""Fence the read-only 190-source diagnostic ranking; no queue or acceptance."""
import importlib.util,json,csv,collections
from pathlib import Path
from run import ROOT,HERE,read,digest
BASE=ROOT/'docs/astra-city/government-import';BATCH='government-xl-identity-primary-spatial-ranking-20261009';DOC=BASE/BATCH
def main():
 data=read(DOC/'ranking.json.gz');rows=data['rows'];assert len(rows)==190
 for p,h in data['inputHashes'].items():assert digest((ROOT/p).read_bytes())==h
 with (DOC/'ranking.csv').open('w',newline='') as f:
  writer=csv.writer(f);writer.writerow(['rank','uid','name','exact_source_key','source_sha256','state','primary_coverage','extent_m','foreign_excess_m2','foreign_actor_count','foreign_uids','explicit_op_ids','whole_source_cell','whole_primary_cell','acceptance_approved'])
  for r in rows:
   m=r.get('measures',{});writer.writerow([r['diagnosticRank'],r['uid'],r['name'],r['sourceKey'],r['sourceSHA256'],r['measurementState'],m.get('targetCoverage'),m.get('maximumSourceExtentM'),m.get('unrelatedExcessOverlapM2'),m.get('unrelatedActorCount'),';'.join(b['uid'] for b in r.get('foreignActors',[])),';'.join(str(i) for i in r['officialStructureIds']),m.get('sourceWholeCell'),m.get('primaryWholeCell'),False])
 summary={'states':dict(collections.Counter(r['measurementState'] for r in rows)),'numericPositives':sum(r['ordinaryNumericBoundsPass'] is True for r in rows),'singleActorCoverageExtentCandidates':[r['uid'] for r in rows if r.get('measures',{}).get('targetCoverage',0)>=.95 and r['measures']['maximumSourceExtentM']<=10 and r['measures']['unrelatedActorCount']==1]}
 (DOC/'README.md').write_text('# Fixed 190-source identity cohort: complete-original spatial research ranking\n\nAgent: xl_identity_search. Diagnostic ranking only; no queues, acceptance, model-state updates, geometry edits or installations.\n\n183 sources have complete original-face/vertex measurements against their uniquely mapped captured primary polygons and all current local actors; six lack a unique exact primary candidate and Central Pier8 lacks its referenced local asset. Captured primary records are not asserted to be a new provider revision. Every source hash/world stream and current tile/catalogue input is pinned; original bytes and poses remain unchanged.\n\nZero sources clear all ordinary95%coverage/10mextent/1m²unrelated-overlap bounds unchanged. This does not mean they are impossible or corrupt: it identifies exact remaining evidence needs. Whole-cell, source-root/native lineage, complete physical/support/foreign/runtime/browser checks remain separate.\n\n`ranking.csv` and `ranking.json.gz` preserve every exact source version. Sorting prioritizes coverage and extent that already meet ordinary bounds, then smaller foreign excess/fewer actors. Single-actor typed-podium cases offer a more direct ownership investigation than multi-actor slivers. Strong leads: Yoho Town Block8 /146396 (only podium231756,8.877m²), Tuen Mun Hospital Special Block/191896 (only podium280350,11.626m²), Tung Sing House/53800 (only Lei Tung commercial podium126434,20.584m²). Explicit occupation-structure IDs are descriptive; no same-name/parent or OP-group exemption is granted.\n\nThe first diagnostic completed all measurements but failed to sort a null UID. The final runner corrects that null key, preserves complete unsorted measurements before sorting, and caches exact current polygons. Its cached form membership was independently compared to the existing uncached full loader on the first three source bounds. Unmapped sources remain unresolved and receive no skip/acceptance credit.\n\nThe fenced Neon `result.json` records this research, with zero installations. No external AI model calls or AI geometry modelling occur in the runner.\n')
 spec=importlib.util.spec_from_file_location('identity_rank_freeze',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
 paths=[ROOT/p for p in data['inputHashes']]+[Path(__file__),HERE/'xl-identity-primary-spatial-ranking-20261009.py',HERE/'xl-second-pass.py',HERE/'xl-final-script-pass.py',HERE/'government_georef_cell_identity.py']
 result=m.freeze(BATCH,'fixed190-original-primary-spatial-research-ranking-v1',paths,{'uids':sorted(r['uid'] for r in rows if r['uid']),'sourceKeys':[r['sourceKey'] for r in rows],'fixedCohortSources':190,'measurementSummary':summary,'identityAccepted':False,'physicalAccepted':False,'queueCreated':False,'sourceReviewSuggestedByRankingOnly':True,'manifestSHA256':data['manifestSHA256'],'requiresHumanDecision':False,'requiresAIModelGeometry':False,'nextStep':'Investigate exact single-actor/source-role ownership from original components and independent primary evidence; advance only through all ordinary identity and complete physical/runtime/browser gates. Missing/unmapped sources retain explicit evidence needs; no permanent rejection.'})
 print(json.dumps({'jobId':result['jobId'],'summary':summary}),flush=True)
if __name__=='__main__':main()
