"""Bound actual lower authored floor roles; higher original fixtures get no floor credit."""
import json,numpy as np,shapely,importlib.util
from pathlib import Path
from run import ROOT,HERE,read,save,digest
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from source_closed_components import components
from lei_tung_named_original_lower_platform_identity_20261010 import polygon,provider_polygon
BASE=ROOT/'docs/astra-city/government-import';BATCH='government-xl-man-hei-authored-lower-floor-role-diagnostic-20261010';DOC=BASE/BATCH
UPPER=BASE/'government-xl-man-fuk-nine-current-identity-75694-0-20261010';PLATFORM=BASE/'government-xl-man-fuk-complete-retained-original-physical-v5-20261010';PRIMARY=BASE/'government-xl-man-hei-man-fuk-primary-platform-context-20261010';PRIOR=BASE/'government-xl-man-hei-mandatory-original-platform-spatial-diagnostic-v2-20261010'
def main():
 assert not DOC.exists();rs=[read(d/'selection.json.gz')['rows'][0] for d in [UPPER,PLATFORM]];tri=[];files=[Path(__file__),UPPER/'selection.json.gz',PLATFORM/'selection.json.gz',PRIMARY/'exact-current-primary.json',PRIMARY/'exact-current-primary.request.json',PRIMARY/'ha-man-hei-block-h.pdf',PRIOR/'result.json',PRIOR/'diagnostic.json.gz',HERE/'source_closed_components.py',HERE/'exact_packed_world_geometry_20261009.py']
 for r in rs:
  p=ROOT/r['candidate']['path'];raw=p.read_bytes();assert digest(raw)==r['sourceSHA256'];tri.append(decode_original_world_triangles(raw));files.append(p)
 a,b=tri;norm=np.cross(b[:,1]-b[:,0],b[:,2]-b[:,0]);form=rs[1]['source']['building'];low,high=form['baseHeightHKPD'],form['topHeightHKPD'];ids=[i for i in range(len(b)) if norm[i,1]>0 and low<b[i,:,1].min()<=b[i,:,1].max()<=high];assert ids;parts=components(b)['components'];owners={f:pi for pi,p in enumerate(parts) for f in p['faceIndices']};own=shapely.union_all(shapely.polygons(a[:,:,[0,2]]));floor=shapely.union_all(shapely.polygons(b[ids][:,:,[0,2]]));providers={p['attributes']['BuildingCSUID']:p for p in read(PRIMARY/'exact-current-primary.json')['features']};out=[];credited=set()
 for label,target in [('current',polygon(rs[0]['source']['building']['rings'])),('primary',provider_polygon(providers[rs[0]['source']['building']['buildingCSUID']]))]:
  missing=target.difference(own);sup=[i for i in ids if shapely.Polygon(b[i][:,[0,2]]).intersection(missing).area>0];credited.update(sup);remaining=missing.difference(floor);out.append({'representation':label,'rawStandaloneTargetCoverage':own.intersection(target).area/target.area,'ownTowerPlusBoundedAuthoredLowerFloorsTargetCoverage':own.union(floor).intersection(target).area/target.area,'rawStandaloneMissingUpperAreaM2':missing.area,'genuineRemainingMissingRegionLowerFloorGapM2':remaining.area,'genuineRemainingGapGeoJSON':json.loads(shapely.to_geojson(remaining)),'originalSupplyingLowerFloorFaces':sup,'originalSupplyingLowerFloorComponents':sorted({owners[i] for i in sup})})
 prior=read(PRIOR/'diagnostic.json.gz');highfaces=[f for f in prior['allOriginalSupplyingUpwardFaces'] if f['sourceFace'] not in ids];result={'uids':[r['uid'] for r in rs],'sourceSHA256s':{r['uid']:r['sourceSHA256'] for r in rs},'completeOriginalWorldSHA256s':{r['uid']:digest(w.tobytes()) for r,w in zip(rs,tri)},'primaryLowerPlatformSpan':[low,high],'primaryTowerBase':rs[0]['source']['building']['baseHeightHKPD'],'rawAllSupplyingUpwardFloorSpanRetained':prior['supplyingUpwardFloorYSpan'],'higherOriginalFixtureFacesNotGivenLowerFloorCredit':highfaces,'completeAuthoredUpwardFloorsWithinPrimaryLowerSpan':ids,'creditedLowerFloorOriginalFacets':[{'face':i,'component':owners[i],'triangle':b[i].tolist()} for i in sorted(credited)],'currentAndProviderUpperTargetChecks':out,'geometryChanged':False,'physicalOrSupportCredit':False,'identityAccepted':False,'qualification':'Only original upward lower-floor facets strictly inside primary32.2..43.4span are proposed geometric lower-platform roles. Original higher fixtures/all10661faces remain present and physically independent. Genuine partial gaps remain; numerical area/coverage is ordinary unchanged95% spatial diagnosis only, not exactcompletefloor or property/engineering proof.'};save(DOC/'diagnostic.json.gz',result);spec=importlib.util.spec_from_file_location('floor_role_fence',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);m.freeze(BATCH,'actual-authored-man-hei-lower-platform-height-role-diagnostic-v1',files,{'uids':result['uids'],'identityAccepted':False,'physicalOrSupportCredit':False,'currentAndProviderUpperTargetChecks':out,'originalHigherFixturesNotCreditedAsLowerFloor':len(highfaces),'sourceGeometryChanges':0});print({'checks':out,'highFacesNotCredited':len(highfaces)},flush=True)
if __name__=='__main__':main()
