"""Complete original paired spatial diagnosis; genuine partial-floor gap retained."""
import importlib.util,json,numpy as np,shapely
from pathlib import Path
from fractions import Fraction
from run import ROOT,HERE,read,save,digest
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from lei_tung_named_original_lower_platform_identity_20261010 import polygon,provider_polygon
BASE=ROOT/'docs/astra-city/government-import';BATCH='government-xl-man-hei-mandatory-original-platform-spatial-diagnostic-20261010';DOC=BASE/BATCH
UPPER=BASE/'government-xl-man-fuk-nine-current-identity-75694-0-20261010';PLATFORM=BASE/'government-xl-man-fuk-complete-retained-original-physical-v5-20261010';PRIMARY=BASE/'government-xl-man-hei-man-fuk-primary-platform-context-20261010';MISSING=BASE/'government-xl-man-hei-original-platform-missing-floor-diagnostic-20261010';CONTACT=BASE/'government-xl-man-fuk-nine-original-platform-interfaces-20261010'
def main():
 assert not DOC.exists();rows=[read(d/'selection.json.gz')['rows'][0] for d in [UPPER,PLATFORM]];world=[];files=[Path(__file__),UPPER/'selection.json.gz',UPPER/'identity.json',PLATFORM/'selection.json.gz',PRIMARY/'diagnostic.json',PRIMARY/'exact-current-primary.json',MISSING/'result.json',MISSING/'diagnostic.json.gz',CONTACT/'result.json',CONTACT/'diagnostic.json.gz',HERE/'lei_tung_named_original_lower_platform_identity_20261010.py',HERE/'exact_packed_world_geometry_20261009.py']
 for r,count in zip(rows,[2286,10661]):
  p=ROOT/r['candidate']['path'];raw=p.read_bytes();assert digest(raw)==r['sourceSHA256'];a=decode_original_world_triangles(raw);assert a.shape==(count,3,3);world.append(a);files.append(p)
 own=shapely.union_all(shapely.polygons(world[0][:,:,[0,2]]));pair=np.concatenate(world);projection=shapely.union_all(shapely.polygons(pair[:,:,[0,2]]));providers=read(PRIMARY/'exact-current-primary.json')['features'];primary={r['attributes']['BuildingCSUID']:r for r in providers};forms=[r['source']['building'] for r in rows];metrics=[]
 for label,target,platform in [('current',polygon(forms[0]['rings']),polygon(forms[1]['rings'])),('primary',provider_polygon(primary[forms[0]['buildingCSUID']]),provider_polygon(primary[forms[1]['buildingCSUID']]))]:
  union=target.union(platform);metrics.append({'representation':label,'rawStandaloneTargetCoverage':own.intersection(target).area/target.area,'mandatoryTwoOriginalUpperTargetCoverage':projection.intersection(target).area/target.area,'mandatoryTwoOriginalCompletePairedTargetCoverage':projection.intersection(union).area/union.area,'rawStandaloneMissingUpperAreaM2':target.difference(own).area,'genuineRemainingUpperTargetNotInWholeOriginalPairM2':target.difference(projection).area,'maximumWholePairSourceExtentFromCompletePairedTargetM':float(shapely.distance(shapely.points(pair[:,:,[0,2]].reshape(-1,2)),union).max()),'rawCurrentUpperTargetOutsidePlatformM2':target.difference(platform).area})
 missing=read(MISSING/'diagnostic.json.gz');assert missing['allLiteralMissingRegionFacetsCovered'] is False;uncovered=Fraction(0);failed=[]
 for ri,r in enumerate(missing['completeMissingRegionDispositions']):
  for fi,f in enumerate(r['allFiniteFacets']):
   q=f['completeOriginalUpwardFloorCoverage']
   if not q['exactProjectionCovered']:
    assert 'exactUncoveredAreaM2' in q;uncovered+=Fraction(q['exactUncoveredAreaM2']);failed.append({'regionIndex':ri,'facetIndex':fi,'completeVerbatimFiniteFailure':f})
 contact=next(r for r in read(CONTACT/'diagnostic.json.gz')['rows'] if r['uid']==rows[0]['uid']);assert contact['sourceSHA256']==rows[0]['sourceSHA256'];supplier=missing['allOriginalSupplyingUpwardFaces'];result={'uids':[r['uid'] for r in rows],'sourceSHA256s':{r['uid']:r['sourceSHA256'] for r in rows},'completeOriginalWorldSHA256s':{r['uid']:digest(w.tobytes()) for r,w in zip(rows,world)},'completeOriginalFaceCounts':[2286,10661],'strictWholePairSpatialMetrics':metrics,'rawAllMissingUpperRegionsFloorCoverageAccepted':False,'genuineRemainingMissingFloorAreaExactFraction':str(uncovered),'genuineRemainingMissingFloorAreaM2':float(uncovered),'completeFailedMissingRegionFiniteWitnessesRetained':failed,'allOriginalSupplyingUpwardFaces':supplier,'supplyingFloorOriginalComponents':sorted({f['originalComponent'] for f in supplier}),'supplyingUpwardFloorYSpan':[min(np.asarray(f['completeLiteralOriginalTriangle'])[:,1].min() for f in supplier),max(np.asarray(f['completeLiteralOriginalTriangle'])[:,1].max() for f in supplier)],'completePositiveDimensionalPairContactsVerbatim':contact,'providerPlatformTopAndTowerBase':[forms[1]['topHeightHKPD'],forms[0]['baseHeightHKPD']],'identityAccepted':False,'fullAcceptance':False,'physicalAccepted':False,'sourceGeometryChanges':0,'qualification':'Read-only prospective mandatory-two-source named platform role. Raw94.807% standalone footprint and genuine missingfloor witnesses retained. Paired95%/10m ordinary spatial thresholds alone do not prove assembly ownership or support. Specifically named HA BlockHplan and actual original component/contact/height role require independent review; no LeiTung complete-floor claim, same-estate grouping, actor exemption or standalone import.'};save(DOC/'diagnostic.json.gz',result)
 spec=importlib.util.spec_from_file_location('freeze_man_hei_pair',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);m.freeze(BATCH,'mandatory-original-man-hei-platform-spatial-diagnostic-v1',files,{'uids':[r['uid'] for r in rows],'identityAccepted':False,'fullAcceptance':False,'sourceGeometryChanges':0,'genuineMissingFloorAreaM2':float(uncovered),'strictWholePairSpatialMetrics':metrics});print({'metrics':metrics,'positiveContacts':contact['positiveDimensionalContacts'],'supplierParts':result['supplyingFloorOriginalComponents'],'genuineMissingFloorAreaM2':float(uncovered)},flush=True)
if __name__=='__main__':main()
