"""Fence complete fourteen-original identity/support and inspected source captures."""
import importlib.util
from pathlib import Path
from run import ROOT,HERE,read
def module(name,file):
 s=importlib.util.spec_from_file_location(name,HERE/file);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 freezer=module('miami_fourteen_fence','xl-popcorn-source-investigations-checkpoints-20261009.py');base=ROOT/'docs/astra-city/government-import';d=base/'government-xl-miami-fourteen-original-current-diagnostic-20261009';identity=read(d/'complete-fourteen-current-identity.json.gz');support=read(d/'all-fourteen-original-ground-podium-contact.json.gz');selection=read(d/'selection.json.gz');assert identity['sourceIdentityAccepted'];positive=[];pending=[]
 for r in support['rows']:
  passing=[p['uid'] for p in r['independentPodiumInterfaces'] if p['interface']['passed']]
  item={'uid':r['uid'],'sourceSHA256':r['sourceSHA256'],'groundInterfacePassed':r['originalGroundInterface']['passed'],'passingOriginalPodiumInterfaces':passing,'rawGroundFailures':r['wholeGroundContact']['failed'],'rawIndependentPodiumInterfaces':r['independentPodiumInterfaces']};(positive if r['originalGroundInterface']['passed'] or passing else pending).append(item)
 refs=[Path(__file__),HERE/'xl-miami-fourteen-original-current-diagnostic-20261009.py',HERE/'xl-miami-fourteen-original-contact-20261009.mjs',HERE/'miami_original_yaw_root_20261009.py',base/'government-xl-miami-five-upper-original-acquisition-20261009/result.json',base/'government-xl-miami-intersecting-upper-source-discovery-20261009/result.json',ROOT/'3d-viewer/city/data/manifest.json']+[ROOT/r['candidate']['path'] for r in selection['rows']];refs.extend(ROOT/'3d-viewer'/p for p in identity['currentTargetTileSHA256s'])
 freezer.freeze(d.name,'complete-fourteen-current-original-identity-and-independent-support-v1',refs,{'uids':[r['uid'] for r in identity['rows']],'originalSources':14,'originalTriangles':50456,'sourceIdentityAccepted':True,'coverage':identity['coverage'],'maximumExtentM':identity['maximumExtentM'],'foreignExcessM2':identity['foreignExcessM2'],'positiveOriginalInterfaceSources':[r['uid'] for r in positive],'pendingOriginalInterfaceSources':[r['uid'] for r in pending],'requiresMoreComputeOrSourceEvidence':True,'requiresAIModelGeometry':False,'requiresHumanDecision':False,'physicalAccepted':False,'remainingReason':'eight-complete-source-support-roles-and-full-current-neighbour-acceptance-pending','nextStep':'Current full14independent source identity passes, but original terrain/support interfaces are diagnostics. Carry six direct interface positives and every remaining original component through current drawn terrain, complete foundation, all neighbours/runtime and staged/live guarded acceptance; no arbitrary component omission or ownership merger.'})
 c=base/'government-xl-miami-elevated-original-source-capture-20261009';report=read(c/'views/render.json');assert len(report['views'])==4 and not report['errors'];refs=[Path(__file__),HERE/'render-miami-original-source-evidence-20261009.mjs',c/'capture-inputs.json',base/'government-xl-miami-elevated-original-contact-graph-20261009/result.json']+[ROOT/p for p in report['inputHashes']];freezer.freeze(c.name,'four-complete-original-miami-podium-tower-captures-v1',refs,{'uids':[v['uid'] for v in report['views']],'wholeOriginalSourceCaptures':4,'allExportedImagesInspected':True,'accurateOriginalUIDLabels':True,'allOriginalFailedSampleMarkersRetained':True,'requiresMoreComputeOrSourceEvidence':True,'requiresAIModelGeometry':False,'requiresHumanDecision':False,'identityAccepted':False,'physicalAccepted':False,'remainingReason':'complete-original-elevated-envelope-and-support-roles-unresolved','nextStep':'The complete source plots show authentic tower/podium contacts and separate rooftop objects. Use precise original-face/edge roles and independently supported anchors; whole low-rim failures remain, and the render alone is not support or installation acceptance.'})
if __name__=='__main__':main()
