"""Current complete fourteen-original identities and support inputs; no publication."""
import sys,json,importlib.util,numpy as np,shapely
from run import ROOT,HERE,read,save,digest
from original_source_ownership import graph_reasons,document
from miami_original_yaw_root_20261009 import verify_original_root
from government_georef_cell_identity import geographic_cell
from georef_projection_coverage import whole_cell_coverage
sys.path.insert(0,str(HERE.parent/'landsd-territory'))
from source import BASE,request
BATCH='government-xl-miami-fourteen-original-current-diagnostic-20261009';DOC=ROOT/'docs/astra-city/government-import'/BATCH
def main():
 assert not (DOC/'result.json').exists(),'Completed checkpoint immutable'
 nine=read(DOC.parent/'government-xl-miami-nine-independent-original-diagnostic-20261009/selection.json.gz')['rows'];upper=read(DOC.parent/'government-xl-miami-five-upper-original-acquisition-20261009/five-exact-upper-original-selection.json.gz')['rows'];selected=nine+upper;wanted={r['uid'] for r in selected};assert len(wanted)==14
 oldinputs=read(DOC.parent/'government-xl-miami-nine-original-contact-20261009/all-original-source-contact-inputs.json.gz');manifest=ROOT/'3d-viewer/city/data/manifest.json';forms=[];current={};tiles={}
 for tile in read(manifest)['tiles']:
  path=ROOT/'3d-viewer'/tile['url'];buildings=read(path)['buildings'];forms+=buildings
  for b in buildings:
   if b['uid'] in wanted:assert b['uid'] not in current;current[b['uid']]=b;tiles[tile['url']]=digest(path.read_bytes())
 assert set(current)==wanted;csuids=sorted(b['buildingCSUID'] for b in current.values());params={'f':'json','where':'BuildingCSUID IN('+','.join("'"+x+"'" for x in csuids)+')','outFields':'*','returnGeometry':'true','resultRecordCount':'1000'};raw,rec=request(BASE+'/0/query',params);DOC.mkdir(parents=True,exist_ok=True);(DOC/'fresh-fourteen-provider.json').write_bytes(raw);save(DOC/'fresh-fourteen-provider.request.json',rec);provider=json.loads(raw);assert not provider.get('error') and not provider.get('exceededTransferLimit') and len(provider['features'])==14
 spec=importlib.util.spec_from_file_location('miami_fourteen_decode',HERE/'xl-second-pass.py');decoder=importlib.util.module_from_spec(spec);spec.loader.exec_module(decoder);decoder.LOCAL=HERE/'local'/BATCH;geometry=[];identities=[];alltri=[];paths=[]
 for row in selected:
  uid=row['uid'];b=current[uid];assert b==row['source']['building'];assert digest((ROOT/'3d-viewer'/row['source']['tile']).read_bytes())==row['source']['tileSHA256'];source=(ROOT/row['candidate']['path']).read_bytes();assert digest(source)==row['sourceSHA256']==row['native']['model']['asset']['sha256'];dest=decoder.LOCAL/'assets'/(row['sourceSHA256']+'.glb.gz');dest.parent.mkdir(parents=True,exist_ok=True);dest.write_bytes(source);row['triangles']=row['native']['model']['triangles'];t=decoder.glb_triangles(row);root=verify_original_root(source,row,t);reasons=list(root['remainingReasons']);fresh=[f for f in provider['features'] if f['attributes']['BuildingCSUID']==b['buildingCSUID']];assert len(fresh)==1;attrs=fresh[0]['attributes'];assert str(attrs['GeoRefNo'])==row['modelId'][1:11] and attrs['Status']=='Active' and attrs['BuildingBlockType']==b['structureType'];cell=geographic_cell(row['modelId'],b['buildingCSUID'],b['structureType']);p=shapely.union_all(shapely.polygons(t[:,:,[0,2]]));cp=whole_cell_coverage(t,cell,p);fp=shapely.symmetric_difference_all([shapely.Polygon([(x-834500,816500-y) for x,y in ring]) for ring in fresh[0]['geometry']['rings']]);target=shapely.Polygon(b['rings'][0],b['rings'][1:]);
  if not (cp['coversWholeCell'] and fp.covers(cell) and target.covers(cell)):reasons.append('whole-original-current-provider-georef-cell')
  g={'uid':uid,'sourceSHA256':row['sourceSHA256'],'position':t.flatten().tolist(),'index':list(range(len(t)*3)),'triangles':len(t),'worldTriangleSHA256':digest(t.astype('<f8').tobytes()),'worldBounds':[t.min(axis=(0,1)).tolist(),t.max(axis=(0,1)).tolist()]};geometry.append(g);alltri.append(t);identities.append({'uid':uid,'modelId':row['modelId'],'sourceSHA256':row['sourceSHA256'],'completeSourceRoot':root,'wholeCell':cp,'currentProviderObjectId':attrs['OBJECTID'],'viewerObjectId':b['objectId'],'currentOriginalFaceCount':len(t),'reasons':reasons,'identityAccepted':not reasons});paths.append(ROOT/row['candidate']['path']);print({'uid':uid,'faces':len(t),'sourceBoundsY':g['worldBounds'][0][1:2]+g['worldBounds'][1][1:2],'rootCellReasons':reasons},flush=True)
 t=np.concatenate(alltri);projection=shapely.union_all(shapely.polygons(t[:,:,[0,2]]));target=shapely.union_all([shapely.Polygon(b['rings'][0],b['rings'][1:]) for b in current.values()]);extra=projection.difference(target);foreign=[b for b in forms if b['uid'] not in wanted and shapely.Polygon(b['rings'][0],b['rings'][1:]).intersects(projection.envelope)];foreignshape=shapely.union_all([shapely.Polygon(b['rings'][0],b['rings'][1:]) for b in foreign]);coverage=projection.intersection(target).area/target.area;extent=float(shapely.distance(shapely.points(t[:,:,[0,2]].reshape(-1,2)),target).max());foreignarea=extra.intersection(foreignshape).area
 save(DOC/'complete-fourteen-current-identity.json.gz',{'rows':identities,'coverage':coverage,'maximumExtentM':extent,'foreignExcessM2':foreignarea,'allOtherCurrentFormsRetained':foreign,'currentTargetTileSHA256s':tiles,'currentManifestSHA256':digest(manifest.read_bytes()),'sourceIdentityAccepted':all(not r['reasons'] for r in identities) and coverage>=.95 and extent<=10 and foreignarea<=1,'physicalAccepted':False,'installationApproved':False,'geometryChanges':0})
 save(DOC/'complete-fourteen-original-contact-inputs.json.gz',{'rows':geometry,'terrain':oldinputs['terrain'],'terrainProvenance':oldinputs['terrainProvenance'],'sourceGeometryChanges':0,'terrainGeometryChanges':0,'installationApproved':False});save(DOC/'selection.json.gz',{'rows':selected,'manifestSHA256':digest(manifest.read_bytes())});print({'sources':len(selected),'faces':len(t),'coverage':coverage,'maximumExtentM':extent,'foreignExcessM2':foreignarea},flush=True)
if __name__=='__main__':main()
