"""Fresh complete Man Fuk primary/original/current inputs, identity-only."""
import importlib.util,gzip,json,shutil
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
from tung_sing_current_bound_identity_20261010 import stream_pin
from man_fuk_named_original_envelope_identity_v3_20261010 import UID,RELATED,SOURCE_SHA,RELATED_SHA
BATCH='government-xl-man-fuk-current-bound-envelope-inputs-20261010';DOC=ROOT/'docs/astra-city/government-import'/BATCH
RAW=DOC.parent/'government-xl-man-fuk-current-complete-identity-diagnostic-v1-20261010';OLD=DOC.parent/'government-xl-man-fuk-man-oi-primary-relations-20261010';SELECT=DOC.parent/'government-xl-man-fuk-man-oi-original-recovery-20261010/selection.json.gz'
def native_rows(c):return [{'sourceKey':k+'/'+m['modelId'],'model':m,'sheet':s,'resultSHA256':h} for k,m,s,h in c.execute("SELECT r.cache_key,m,i.sheet,r.result_sha FROM astra_modelling.native_stage_results r JOIN astra_modelling.native_stage_inputs i USING(cache_key),LATERAL jsonb_array_elements(r.result->'models')m WHERE m->>'modelId' IN ('B364461960802063C0','B364721945401063C0') ORDER BY m->>'modelId'").fetchall()]
def module(name,file):
 s=importlib.util.spec_from_file_location(name,HERE/file);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 assert not DOC.exists();rawreceipt=read(RAW/'result.json');manifest=ROOT/'3d-viewer/city/data/manifest.json';msha=digest(manifest.read_bytes());assert msha==rawreceipt['manifestSHA256'];
 for r in rawreceipt['evidenceRefs']:assert digest((ROOT/r['path']).read_bytes())==r['sha256']
 with connect() as c:
  c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(rawreceipt['jobId'],)).fetchone()==('complete',rawreceipt);native=native_rows(c)
 assert len(native)==2;selection=read(RAW/'selection.json.gz');context=read(RAW/'context.json.gz');forms=read(RAW/'complete-current-forms.json.gz')['rows'];source=read(SELECT);paths={r['uid']:ROOT/r['candidate']['path'] for r in source['rows']};assert digest(paths[UID].read_bytes())==SOURCE_SHA and digest(paths[RELATED].read_bytes())==RELATED_SHA
 DOC.mkdir(parents=True);query=module('man_fuk_primary_query','xl-aqua-marine-fresh-overhead-source-context-v3-20261010.py');query.DOC=DOC;where="BuildingCSUID IN ('3644619608P20050726','3647219454T20050430')";primary=query.query(0,where,'exact-current-primary',True);relations=query.query(1002,where,'exact-current-structure-relations');assert not relations
 for name,src in [('ha-estate-layout.pdf',OLD/'ha-chun-man-estate-url-probe.pdf'),('ha-man-oi-block-k.pdf',OLD/'ha-man-oi-block-k.pdf'),('ha-man-fuk-block-a.pdf',DOC.parent/'government-xl-man-fuk-complete-foreign-context-20261010/official-man-fuk-block-a-floor-plan.pdf')]:shutil.copyfile(src,DOC/name)
 contact=read(DOC.parent/'government-xl-man-fuk-man-oi-complete-original-contacts-20261010/diagnostic.json.gz')
 evidence={'rows':native,'primaryRecords':primary,'exactRelations':relations,'exactStructures':[],'primaryPlanSHA256':digest((DOC/'ha-estate-layout.pdf').read_bytes()),'primaryFloorPlanSHA256':digest((DOC/'ha-man-oi-block-k.pdf').read_bytes()),'primaryBlockAPlanSHA256':digest((DOC/'ha-man-fuk-block-a.pdf').read_bytes()),'completeOverlapFaceIds':contact['all23ForeignOverlapOriginalFaceIds'],'primaryNamedRelationship':{'platformName':'MAN FUK HOUSE (BLK A)','namedBlock':'A','adjacentStructure':'Man Oi House / Block K','relationship':'adjacent connected source envelopes','legalOwnershipClaim':False,'surveyPrecisionClaim':False,'supportClaim':False}}
 save(DOC/'original-source-lookup.json.gz',evidence);save(DOC/'selection.json.gz',selection);save(DOC/'context.json.gz',context);save(DOC/'current-inputs.json.gz',{'manifestSHA256':msha,'forms':forms,'tileHashes':context['rows'][0]['neighbourTileHashes'],'relatedOriginalPath':str(paths[RELATED].relative_to(ROOT))});save(DOC/'complete-original-stream-pins.json.gz',{'own':stream_pin(paths[UID].read_bytes(),'B364461960802063C0',10661),'related':stream_pin(paths[RELATED].read_bytes(),'B364721945401063C0',2160)})
 assert digest(manifest.read_bytes())==msha
 (DOC/'README.md').write_text('Fresh exact original source/current/primary binding for one named Man Fuk podium and independently named Man Oi Tower. All10661+2160 original faces and93+4parts retained. All23 excess faces belong the complete mainbody or the source-owned108faceplate with134exactpositive internal interfaces; mainbody has12exactoriginal ManOi interfaces. Three official HA plans corroborate independently named BlocksA/K; no commonOP/legal ownership, surveyed heights, structural/ground or actor/terrain/collision exemptions. Raw full-cell and physical/browser gates remain independent.\n')
 refs=[Path(__file__),manifest,SELECT,*paths.values(),HERE/'man_fuk_named_original_envelope_identity_v3_20261010.py',HERE/'test_man_fuk_named_original_envelope_identity_v3_20261010.py',HERE/'tung_sing_current_bound_identity_20261010.py',HERE/'xl-aqua-marine-fresh-overhead-source-context-v3-20261010.py']+[p for p in RAW.rglob('*') if p.is_file()]+[p for p in OLD.rglob('*') if p.is_file()]+[DOC.parent/'government-xl-man-fuk-complete-foreign-context-20261010/official-plan-request.json']+[ROOT/'3d-viewer'/url for url in context['rows'][0]['neighbourTileHashes']]
 module('man_fuk_capture_fence','xl-popcorn-source-investigations-checkpoints-20261009.py').freeze(BATCH,'complete-current-primary-original-source-envelope-inputs-v1',refs,{'uids':[UID,RELATED],'identityAccepted':False,'physicalAccepted':False,'sourceIdentityReviewUsedAI':True,'manifestSHA256':msha,'remainingReason':'reviewed-source-envelope-current-adapter-replay-and-independent-physical-checks'})
if __name__=='__main__':main()
