"""Current five original ground/interface-qualified originals, preserve all unselected current actors."""
import json,numpy as np,shapely
from run import ROOT,HERE,read,save,digest
from original_source_ownership import document,graph_reasons
from government_georef_cell_identity import geographic_cell
from miami_original_yaw_root_20261009 import verify_original_root
BATCH='government-xl-miami-five-grounded-originals-20261009';DOC=ROOT/'docs/astra-city/government-import'/BATCH
assert not (DOC/'result.json').exists(),'Completed checkpoint immutable'
sel=read(ROOT/'docs/astra-city/government-import/government-xl-miami-nine-independent-original-diagnostic-20261009/selection.json.gz');inp=read(ROOT/'docs/astra-city/government-import/government-xl-miami-nine-original-contact-20261009/all-original-source-contact-inputs.json.gz');contacts=read(ROOT/'docs/astra-city/government-import/government-xl-miami-nine-original-contact-20261009/all-nine-original-ground-podium-contact.json.gz');uids={r['uid'] for r in contacts['rows'] if r['originalGroundInterface']['passed']};assert uids=={'landsd/232089:0','landsd/202994:0','landsd/203433:0','landsd/231147:0','landsd/259038:0'};rows=[r for r in sel['rows'] if r['uid'] in uids];tri=[];owned=[]
for r in rows:
 original=(ROOT/r['candidate']['path']).read_bytes();assert digest(original)==r['sourceSHA256'];g=next(g for g in inp['rows'] if g['uid']==r['uid']);t=np.array(g['position']).reshape(-1,3,3);assert digest(t.astype('<f8').tobytes())==g['worldTriangleSHA256'];graph=verify_original_root(original,r,t);assert graph['passed'],graph;tri.append(t);b=r['source']['building'];cell=geographic_cell(r['modelId'],b['buildingCSUID'],b['structureType']);p=shapely.union_all(shapely.polygons(t[:,:,[0,2]]));target=shapely.Polygon(b['rings'][0],b['rings'][1:]);owned.append({'uid':r['uid'],'sourceSHA256':r['sourceSHA256'],'originalRoot':r['modelId'],'completeOriginalSceneGraphPass':True,'originalRootProof':graph,'originalTriangles':len(t),'allOriginalNodes':document(original)['nodes'],'allOriginalMeshesCount':len(document(original)['meshes']),'sourceAndCurrentWholeCellPass':bool(p.covers(cell) and target.covers(cell))})
t=np.concatenate(tri);p=shapely.union_all(shapely.polygons(t[:,:,[0,2]]));target=shapely.union_all([shapely.Polygon(r['source']['building']['rings'][0],r['source']['building']['rings'][1:]) for r in rows]);excess=p.difference(target);allforms=[];mh=digest((ROOT/'3d-viewer/city/data/manifest.json').read_bytes())
for tile in read(ROOT/'3d-viewer/city/data/manifest.json')['tiles']:
 for b in read(ROOT/'3d-viewer'/tile['url'])['buildings']:
  if b['uid'] not in uids and shapely.Polygon(b['rings'][0],b['rings'][1:]).intersects(p.envelope):allforms.append({'building':b,'tile':tile['url'],'tileSHA256':digest((ROOT/'3d-viewer'/tile['url']).read_bytes())})
other=shapely.union_all([shapely.Polygon(r['building']['rings'][0],r['building']['rings'][1:]) for r in allforms]);out={'uids':sorted(uids),'allOriginalFaces':len(t),'coverage':p.intersection(target).area/target.area,'maximumExtentM':float(shapely.distance(shapely.points(t[:,:,[0,2]].reshape(-1,2)),target).max()),'unrelatedExcessOverlapM2':excess.intersection(other).area,'completeOriginalOwnership':owned,'otherPositiveExcessOverlaps':[{'uid':r['building']['uid'],'areaM2':excess.intersection(shapely.Polygon(r['building']['rings'][0],r['building']['rings'][1:])).area} for r in allforms if excess.intersection(shapely.Polygon(r['building']['rings'][0],r['building']['rings'][1:])).area>0],'currentManifestSHA256':mh,'allOtherCurrentFormsRetained':allforms,'groundOrOrdinaryWallTINContactForEverySourcePassed':True,'identityAccepted':False,'physicalAccepted':False,'installationApproved':False,'geometryChanges':0,'qualification':'Four originals share explicit OPpodium/towerrelationships; distinctneighbour remains separatelyowned. No removal of remaining five originals/currentactors. Full subset spatial/ownership diagnostic only; raw remaining gates retained.'};save(DOC/'five-grounded-complete-original-current-proof.json.gz',out);save(DOC/'selection.json.gz',{'rows':rows,'manifestSHA256':mh,'groundContactPrior':str((ROOT/'docs/astra-city/government-import/government-xl-miami-nine-original-contact-20261009/all-nine-original-ground-podium-contact.json.gz').relative_to(ROOT))});print({k:v for k,v in out.items() if k not in ['allOtherCurrentFormsRetained','completeOriginalOwnership','otherPositiveExcessOverlaps']},flush=True)
