"""Freeze changed Miami complete-source/foreign-interface evidence in searchable Neon."""
import importlib.util
from run import ROOT,HERE,read
s=importlib.util.spec_from_file_location('miami_freeze',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
base=ROOT/'docs/astra-city/government-import'
def local(batch):return [p for p in (HERE/'local'/batch).rglob('*') if p.is_file()]
pair='government-xl-miami-op-complete-pair-20261009';family='government-xl-miami-op-complete-family-20261009';foreign='government-xl-miami-foreign-original-interface-20261009'
common=[HERE/'xl-miami-family-evidence-checkpoints-20261009.py',HERE/'xl-second-pass.py',HERE/'xl-next-support-recovery-20261005.py',HERE/'government_georef_cell_identity.py']
pairrunners=[HERE/('xl-miami-op-'+n+'-20261009.py') for n in ['complete-pair','pair-missing-roles','pair-upper-form-research']]
m.freeze(pair,'original-op-family-missing-component-identity-investigation-v1',common+pairrunners+local(pair),{'uids':['landsd/232089:0','landsd/259038:0'],'identityAccepted':False,'scriptFullAcceptancePassed':False,'rawPairMetrics':read(base/pair/'complete-original-pair-current-measures.json'),'changedEvidence':'Six distinct tower originals explicitly share NT73/91/NT166/91 podium permits and explain most missing projection area.','remainingReason':'complete-source-family-requires-independent-foreign-interface-resolution','nextStep':'Use eight untouched sources; do not substitute absent courtyards or edit originals.'})
uids=read(base/family/'complete-original-pair-current-measures.json')['uids']
m.freeze(family,'complete-eight-original-op-family-current-coverage-v1',common+pairrunners+[HERE/('xl-miami-'+n+'-20261009.py') for n in ['op-complete-family','family-foreign-face-cause','family-current-provider']]+local(family)+[base/pair/'result.json']+[p for p in (base/foreign).rglob('*') if p.is_file()],{'uids':uids,'identityAccepted':False,'scriptFullAcceptancePassed':False,'rawCompleteFamilyMetrics':read(base/family/'complete-original-pair-current-measures.json'),'allEightWholeCellsPassed':True,'remainingReason':'distinct-current-neighbour-podium-8.0472m2-excess-overlap','changedEvidence':'Eight untouched originals cover99.8661%; exact17ClubIIborderfaces accountfor remainingforeignoverlap. Freshprovider revision doesnot removeit.','nextStep':'Independently validate original distinct podium and exact source-authored external interface; preserve every current form and raw threshold.'})
m.freeze(foreign,'independent-distinct-original-neighbour-interface-v1',common+[HERE/'xl-miami-family-foreign-original-interface-20261009.py',HERE/'exact_original_component_contacts_20261009.py',HERE/'exact_original_shell_intersections_20261009.py',base/family/'result.json']+local(foreign),{'uids':['landsd/259038:0','landsd/231147:0'],'identityAccepted':False,'scriptFullAcceptancePassed':False,'currentHeldReason':'independent-source-external-interface-contract-and-full-physical-checks-required','exactInterface':read(base/foreign/'exact-original-distinct-interface.json.gz'),'nextStep':'Validate distinct original neighbour independently; source-backed actual geometry is useful evidence, no suppression or permit grouping.'})
