"""Replay retained terrain after correcting only its stale numerical gap record."""
import importlib.util,json,subprocess,sys,uuid,copy,traceback
from pathlib import Path
import numpy as np
from shapely.geometry import Polygon
from run import ROOT,HERE,read,save,digest,reservations
from publication_lock import locked_publication
from miami_independent_original_collection_20261009 import verify_files,UIDS,POLICY
BATCH='government-xl-miami-five-retained-measurement-physical-20261009';DOC=ROOT/'docs/astra-city/government-import'/BATCH;LOCAL=HERE/'local'/BATCH
PREVIOUS=ROOT/'docs/astra-city/government-import/government-xl-miami-five-disjoint-parent-physical-20261009';OLD=HERE/'local'/PREVIOUS.name
def module(name,file):
 s=importlib.util.spec_from_file_location(name,HERE/file);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def call(args):
 subprocess.run(args,cwd=ROOT,check=True);assert reservations.owns(read(LOCAL/'reservation.json'))
def owned():
 selected=read(OLD/'frozen-inputs/check-selection.json.gz');contexts=read(OLD/'frozen-inputs/context.json.gz');manifest=ROOT/'3d-viewer/city/data/manifest.json';assert digest(manifest.read_bytes())==selected['manifestSHA256'];assert reservations.owns(read(LOCAL/'reservation.json'));identities=[]
 for r in selected['rows']:
  context=next(c for c in contexts['rows'] if c['uid']==r['uid']);proof=verify_files(r,context,LOCAL/'identity');assert proof['passed'];identities.append(proof);source=(ROOT/r['candidate']['path']).read_bytes();assert digest(source)==r['sourceSHA256'];path=LOCAL/'assets'/(r['sourceSHA256']+'.glb.gz');path.parent.mkdir(exist_ok=True);path.write_bytes(source)
 save(DOC/'fresh-owned-identity.json',{'rows':identities});save(DOC/'selection.json.gz',{**selected,'batch':BATCH});save(LOCAL/'catalogue.json',{**read(OLD/'catalogue.json'),'area':BATCH});save(LOCAL/'catalogue-index.json',read(OLD/'catalogue-index.json'));save(LOCAL/'source-forms.json',read(OLD/'source-forms.json'))
 patches=module('miami_gap_exact_projection','native_patch_resolution.py');second=module('miami_gap_validator','xl-second-pass.py');final=module('miami_gap_full_foundation','xl-final-script-pass.py');parent=read(ROOT/'3d-viewer/city/data/terrain.json');oldpath=OLD/'government-native-232089-0.json';patch=read(oldpath);mesh=copy.deepcopy(patch['nativeMesh']);g=patch['meta']['georef'];bounds=[g['bE']-834500,816500-g['bN'],g['bE']-834500+(patch['w']-1)*g['aE'],816500-g['bN']-(patch['h']-1)*g['aN']];old=copy.deepcopy(mesh['source']['numericalCoverageGap']);gap=float(patches.projected_context(patch,bounds)[2].area);assert gap<=old['maximumAreaM2'] and old['maximumFraction']==.001;patch['nativeMesh']['source']['numericalCoverageGap']['measuredAreaM2']=gap;assert patch['nativeMesh']['position']==mesh['position'] and patch['nativeMesh']['index']==mesh['index'];path=LOCAL/oldpath.name;save(path,patch)
 source_files=patch['meta']['source']['nativeSources'];files=[f for s in source_files for f in s['sourceFiles']];assert all(digest((ROOT/f['path']).read_bytes())==f['sha256'] for f in files)
 if patches.projected_context(patch,bounds)[3]>1e-8:patches.approve_original_overlap(patch,path,DOC/'native-overlap.json',files);patches.finalize_overlap_evidence(patch,DOC/'native-overlap.json')
 second.resolution.validate_patch(patch,parent);save(path,patch);assert patch['nativeMesh']['position']==mesh['position'] and patch['nativeMesh']['index']==mesh['index'];save(DOC/'stale-gap-record-resolution.json',{'previousSource':str(oldpath.relative_to(ROOT)),'previousSHA256':digest(oldpath.read_bytes()),'oldApproval':old,'currentFloat32GapM2':gap,'maximumAreaM2Unchanged':old['maximumAreaM2'],'maximumFractionUnchanged':.001,'positionsAndIndicesExactlyUnchanged':True,'allExistingTerrainGatesRetained':True,'sourceGeometryChanges':0,'publication':False})
 row={'path':str(path.relative_to(ROOT)),'sha256':digest(path.read_bytes()),'uids':sorted(UIDS),'bounds':bounds,'triangles':len(patch['nativeMesh']['index'])//3};save(DOC/'terrain-candidates.json',[row]);inputs=read(PREVIOUS/'selection.json.gz') if (PREVIOUS/'selection.json.gz').exists() else selected;scope=final.load_forms(bounds);live={m['uid'] for u in read(manifest)['officialModelCatalogues'] for m in read(ROOT/'3d-viewer'/u)['models']};save(DOC/'neighbour-inputs.json.gz',{'rows':[{'building':b,'patchIndexes':[0],'existingNative':b['uid'] in live or bool(b.get('modelGeometry'))} for b,_,_ in scope],'candidateIds':sorted(UIDS),'patches':[row],'inputHashes':{str((ROOT/'3d-viewer'/url).relative_to(ROOT)):digest((ROOT/'3d-viewer'/url).read_bytes()) for _,_,url in scope}})
 for script,args in [('acceptance-metrics.mjs',['--selection',str((DOC/'selection.json.gz').relative_to(ROOT)),'--candidates',str(LOCAL.relative_to(ROOT)),'--terrain-candidates',str((DOC/'terrain-candidates.json').relative_to(ROOT)),'--out',str((DOC/'metrics.json').relative_to(ROOT)),'--geometry-out',str((LOCAL/'runtime-geometry.json.gz').relative_to(ROOT))]),('../building-batch/validate_candidates.mjs',['--candidates',str(LOCAL.relative_to(ROOT)),'--source-forms',str((LOCAL/'source-forms.json').relative_to(ROOT)),'--terrain-candidates',str((DOC/'terrain-candidates.json').relative_to(ROOT)),'--out',str((DOC/'validation.json').relative_to(ROOT))]),('check-neighbours.mjs',[str(DOC.relative_to(ROOT))+'/']),('check-native-neighbours.mjs',[str(DOC.relative_to(ROOT))+'/'])]:call(['node',str(HERE/script),*args])
 runtime=read(LOCAL/'runtime-geometry.json.gz')['rows'];foundations=[]
 for r in selected['rows']:
  geom=next(g for g in runtime if g['uid']==r['uid']);t=np.asarray(geom['position']).reshape(-1,3)[np.asarray(geom['index']).reshape(-1,3)];terrain=np.asarray(geom['drawnGroundGeometry']).reshape(-1,3,3);b=r['source']['building'];f=final.foundation_context(t,terrain,Polygon(b['rings'][0],b['rings'][1:]));foundations.append({'uid':r['uid'],'sourceSHA256':r['sourceSHA256'],'foundation':f,'strictFoundationAccepted':f['completeTerrainTriangles']==f['triangles'] and not f['fullyBuriedUpwardTriangles'] and f['fullyBuriedAreaFraction']==0})
 save(DOC/'foundation.json',{'rows':foundations,'sourceGeometryChanges':0});metrics=read(DOC/'metrics.json');policy=module('miami_gap_existing_policy','acceptance-policy.py');validation=read(DOC/'validation.json');reasons=[];decisions=[]
 from terrain_diagnostic_resolution import resolve_global_bottom_warning
 for r in selected['rows']:
  uid=r['uid'];m=next(x for x in metrics['rows'] if x['uid']==uid);f=next(x for x in foundations if x['uid']==uid);p=next(x for x in identities if x['uid']==uid);raw=policy.reasons({'state':'runtime-validated-awaiting-acceptance','sourceSHA256':r['sourceSHA256'],'identityProof':p['proof']},m,metrics['profiles']['mobile']);resolution=resolve_global_bottom_warning(next(v for v in validation['results'] if v['uid']==uid),m,f);reasons.extend(uid+':'+x for x in raw+resolution['remaining']);decisions.append({'uid':uid,'rawReasons':raw,'diagnosticResolution':resolution});
  if not f['strictFoundationAccepted']:reasons.append(uid+':whole-source-foundation')
 if validation['checksPassed']!=5 or validation['loaderAccepted']!=5 or validation['exceptions']:reasons.append('runtime-validation')
 native=read(DOC/'native-neighbour-checks.json');resolved=set(native['resolved']);reasons.extend('native-neighbour-regression:'+u for u in set(native['blocked'])-resolved);reasons.extend('terrain-regresses-neighbour:'+r['uid'] for r in read(DOC/'neighbour-checks.json')['rows'] if r['reasons'] and r['uid'] not in resolved);save(DOC/'physical-decisions.json',{'rows':decisions})
 freezer=module('miami_gap_fence','xl-popcorn-source-investigations-checkpoints-20261009.py');refs=[Path(__file__),PREVIOUS/'result.json',OLD/'frozen-inputs/check-selection.json.gz',OLD/'frozen-inputs/context.json.gz',oldpath,path,HERE/'miami_independent_original_collection_20261009.py'];refs.extend(ROOT/p for p in read(DOC/'native-neighbour-checks.json')['inputHashes']);freezer.freeze(BATCH,'five-original-eight-disjoint-parent-fresh-complete-physical-v3',[*refs],{'uids':sorted(UIDS),'identityAccepted':True,'scriptFullAcceptancePassed':not reasons,'reasons':sorted(set(reasons)),'positionsAndIndicesExactlyUnchangedFromRetainedTrial':True,'remainingReason':'staged-and-live-browser-guarded-publication' if not reasons else 'complete-current-neighbour-support-recovery','nextStep':'Source geometry and raw neighbour failures remain; complete current basic-source interfaces or upper original support before publication. No staging credit from partial passes.'})
def main():
 if '--owned' in sys.argv:
  with locked_publication(ROOT):return owned()
 assert not (DOC/'result.json').exists(),'Completed stage immutable';selection=read(OLD/'frozen-inputs/check-selection.json.gz');oldpatch=read(OLD/'government-native-232089-0.json');g=oldpatch['meta']['georef'];bounds=[g['bE']-834500,816500-g['bN'],g['bE']-834500+(oldpatch['w']-1)*g['aE'],816500-g['bN']-(oldpatch['h']-1)*g['aN']];final=module('miami_gap_claim_scope','xl-final-script-pass.py');scope={b['uid'] for b,_,_ in final.load_forms(bounds)};claim=reservations.claim('miami-gap-continuation-'+str(uuid.uuid4()),['building:'+u for u in sorted(scope|UIDS)]+['terrain-patch:'+u for u in sorted(UIDS)]+['terrain-surface:city/data/terrain.json'],batch=BATCH,ttl=3600);assert claim['ok'],claim;save(LOCAL/'reservation.json',json.loads(json.dumps(claim['reservation'],default=str)));subprocess.run([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(LOCAL/'reservation.json'),'--ttl','3600','--',sys.executable,__file__,'--owned'],cwd=ROOT,check=True)
if __name__=='__main__':main()
