"""Fresh complete named overhead identity replay; no physical/install credit."""
import importlib.util
from pathlib import Path
from run import ROOT,HERE,read,save,digest
from man_fuk_current_bound_envelope_identity_v3_20261010 import verify_files,DOC as INPUT,INSTALLED
BATCH='government-xl-man-fuk-current-bound-envelope-promotion-v3-20261010';DOC=ROOT/'docs/astra-city/government-import'/BATCH;LOCAL=HERE/'local'/BATCH
assert not (DOC/'result.json').exists();row=read(INPUT/'selection.json.gz')['rows'][0];context=read(INPUT/'context.json.gz')['rows'][0];(LOCAL/'assets').mkdir(parents=True,exist_ok=True);raw=(ROOT/row['candidate']['path']).read_bytes();assert digest(raw)==row['sourceSHA256'];(LOCAL/'assets'/(row['sourceSHA256']+'.glb.gz')).write_bytes(raw);proof=verify_files(row,context,LOCAL);assert proof['passed'],proof['reasons'];save(DOC/'identity.json',proof)
(DOC/'README.md').write_text('Man Fuk complete original source-envelope identity passed the current manifest/provider/native/root/BIN/fullcell replay. All10661faces/93parts remain; all23 named excess faces belong complete mainbody or attached108faceplate. Complete ManOi2160face source and its unique actual installed catalogue bytes are pinned; allother actors remain foreign. Raw identity reasons retained, no OP/legal/support/collision/terrain/physical/install exemption.24 bound adapter and29 named actual-source mutation tests pass. Independent current original mesh/ground/foundation/neighbour/runtime/browser gates still required.\n')
s=importlib.util.spec_from_file_location('man_fuk_promote_freezer',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
paths=[Path(__file__),HERE/'man_fuk_current_bound_envelope_identity_v3_20261010.py',HERE/'test_man_fuk_current_bound_envelope_identity_v3_20261010.py',HERE/'test_man_fuk_named_original_envelope_identity_v3_20261010.py']+[p for p in INPUT.rglob('*') if p.is_file()]+[p for p in INSTALLED.rglob('*') if p.is_file()]+[HERE/'man_fuk_named_original_envelope_identity_v3_20261010.py']
receipt=m.freeze(BATCH,'complete-current-named-original-envelope-identity-v2',paths,{'uids':[row['uid']],'uid':row['uid'],'sourceSHA256':row['sourceSHA256'],'identityAccepted':True,'scriptFullAcceptancePassed':False,'physicalAccepted':False,'newlyInstalled':0,'sourceIdentityReviewUsedAI':True,'manifestSHA256':read(INPUT/'current-inputs.json.gz')['manifestSHA256'],'nextStep':'Complete independent source terrain/support/current foreign/runtime/browser acceptance; rebind current after any map publication.'});print(receipt['jobId'],flush=True)
