"""Freeze complete No1 Garden/Hollywood current/source/provider identity inputs."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect,NATIVE_RUN
from tung_sing_current_bound_identity_20261010 import stream_pin
from no1_garden_original_overhead_roof_edge_identity_20261010 import UID,FOREIGN,SOURCE_SHA,FOREIGN_SHA
BATCH='government-xl-no1-garden-current-bound-roof-edge-inputs-v2-20261010';DOC=ROOT/'docs/astra-city/government-import'/BATCH
RAW=DOC.parent/'government-xl-no1-garden-current-original-identity-diagnostic-20261010'
OTHER=DOC.parent/'government-xl-source-neighbour-recovery-leads-20261010/selection.json.gz'
def native_rows(c):return [{'sourceKey':k+'/'+m['modelId'],'model':m,'sheet':s,'resultSHA256':h} for k,m,s,h in c.execute("SELECT r.cache_key,m,i.sheet,r.result_sha FROM astra_modelling.native_stage_results r JOIN astra_modelling.native_stage_inputs i USING(cache_key),LATERAL jsonb_array_elements(r.result->'models')m WHERE m->>'modelId' IN ('B339611526102063C0','B339531529702063C0') ORDER BY m->>'modelId'").fetchall()]
def main():
 assert not DOC.exists();selection=read(RAW/'selection.json.gz');row=selection['rows'][0];context=read(RAW/'context.json.gz')['rows'][0];forms=read(RAW/'complete-current-forms.json.gz')['rows'];manifest=ROOT/'3d-viewer/city/data/manifest.json';assert digest(manifest.read_bytes())==selection['manifestSHA256'];foreign=next(r for r in read(OTHER)['rows'] if r['uid']==FOREIGN);paths={UID:ROOT/row['candidate']['path'],FOREIGN:ROOT/foreign['candidate']['path']};assert digest(paths[UID].read_bytes())==SOURCE_SHA and digest(paths[FOREIGN].read_bytes())==FOREIGN_SHA
 with connect() as c:
  c.execute('SET TRANSACTION READ ONLY');native=native_rows(c);assert len(native)==2
  for r in native:
   key=r['sourceKey'].rsplit('/',1)[0];assert c.execute('SELECT r.result_sha FROM astra_modelling.native_stage_results r JOIN astra_modelling.native_stage_members m USING(cache_key) WHERE m.run_id=%s AND r.cache_key=%s',(NATIVE_RUN,key)).fetchone()==(r['resultSHA256'],)
 DOC.mkdir(parents=True);s=importlib.util.spec_from_file_location('garden_exact_current_primary_query',HERE/'xl-aqua-marine-fresh-overhead-source-context-v3-20261010.py');q=importlib.util.module_from_spec(s);s.loader.exec_module(q);q.DOC=DOC;primary=q.query(0,"BuildingCSUID IN ('3396115261P20060312','3395315297P20060312')",'exact-current-primary',True);assert len(primary)==2
 save(DOC/'source-lookup.json.gz',{'rows':native,'originalPaths':{u:str(p.relative_to(ROOT)) for u,p in paths.items()}});save(DOC/'complete-original-stream-pins.json.gz',{'own':stream_pin(paths[UID].read_bytes(),'B339611526102063C0',821),'foreign':stream_pin(paths[FOREIGN].read_bytes(),'B339531529702063C0',546)});save(DOC/'current-inputs.json.gz',{'manifestSHA256':selection['manifestSHA256'],'forms':forms,'tileHashes':context['neighbourTileHashes']});save(DOC/'selection.json.gz',selection);save(DOC/'context.json.gz',{'rows':[context]})
 (DOC/'README.md').write_text('Complete821-face three-part original No1 Garden and546-face two-part original Hollywood Heights remain unchanged. Only exact upward horizontal roof-edge faces642–644 at133.2569885HKPD project over the distinct original body (complete maximum129.72899HKPD). Whole779-face own main body is not claimed overhead. Current all-form/tile/manifest, exact native versions/run memberships, source scene/root/BIN/attribute streams, unique current primary stable identifiers and raw full-cell failures are bound. Separate OP H39/83/H229/77 retained as evidence; no common ownership, physical support, collision, terrain or model-removal exemption. Kernel tests21PASS; current replay/full physical and publication remain independent.\n')
 inputs=[Path(__file__),manifest,OTHER,*paths.values(),HERE/'no1_garden_original_overhead_roof_edge_identity_20261010.py',HERE/'test_no1_garden_original_overhead_roof_edge_identity_20261010.py',HERE/'tung_sing_current_bound_identity_20261010.py',HERE/'xl-aqua-marine-fresh-overhead-source-context-v3-20261010.py']+[p for p in RAW.rglob('*') if p.is_file()]+[ROOT/'3d-viewer'/u for u in context['neighbourTileHashes']]
 for name in ['government-xl-garden-original-identity-role-leads-20261010','government-xl-garden-exact-structure-permits-20261010','government-xl-garden-current-primary-identity-context-20261010']:
  inputs.extend(p for p in (DOC.parent/name).rglob('*') if p.is_file())
 assert digest(manifest.read_bytes())==selection['manifestSHA256'];s=importlib.util.spec_from_file_location('garden_roof_edge_fence',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);r=m.freeze(BATCH,'complete-no1-garden-roof-edge-current-provider-original-inputs-v1',inputs,{'uids':[UID,FOREIGN],'identityAccepted':False,'physicalAccepted':False,'scriptFullAcceptancePassed':False,'completeOriginalFaces':[821,546],'completeProjectedOverlapFaces':3,'remainingReason':'reviewed-named-kernel-current-replay-then-independent-fullphysical'});print({'jobId':r['jobId']},flush=True)
if __name__=='__main__':main()
