"""Fresh complete original No1 Garden roof-edge identity replay, no physical credit."""
import importlib.util,uuid
from pathlib import Path
from run import ROOT,HERE,read,save,digest,reservations
from no1_garden_current_bound_roof_edge_identity_v4_20261010 import verify_files,DOC as INPUT
BATCH='government-xl-no1-garden-current-bound-roof-edge-promotion-v3-20261010';DOC=ROOT/'docs/astra-city/government-import'/BATCH;LOCAL=HERE/'local'/BATCH

def main():
 assert not DOC.exists();claim=reservations.claim('no1-garden-complete-identity-'+str(uuid.uuid4()),['building:landsd/304714:0','building:landsd/213929:0'],batch=BATCH,ttl=3600);assert claim['ok'],claim
 try:
  row=read(INPUT/'selection.json.gz')['rows'][0];context=read(INPUT/'context.json.gz')['rows'][0];(LOCAL/'assets').mkdir(parents=True,exist_ok=True);raw=(ROOT/row['candidate']['path']).read_bytes();assert digest(raw)==row['sourceSHA256'];(LOCAL/'assets'/(row['sourceSHA256']+'.glb.gz')).write_bytes(raw);proof=verify_files(row,context,LOCAL);save(DOC/'identity.json',proof);assert proof['passed'],proof['reasons'];assert reservations.owns(claim['reservation']);assert digest((ROOT/'3d-viewer/city/data/manifest.json').read_bytes())==read(INPUT/'current-inputs.json.gz')['manifestSHA256']
  (DOC/'README.md').write_text('Fresh complete original821-face No1 Garden identity passed exact current/provider/native/root/stream/full-cell replay. Only three literal upward horizontal roof-edge faces642–644 lie above the distinct complete546-face original/current/primary Hollywood Heights body. Whole779-face own mainbody is not claimed overhead. Both separate OP structures, all raw projected overlap and every independent current foreign collision/terrain/support/runtime gate retained.52 actual kernel+adapter+spatial tests pass. Exactly two unique current native original versions/source keys required; ambiguous or duplicate versions reject. The archival first input captured attributes without geometry and correctly failed its adapter test; separately frozen full-polygon v2 input fixes that request. No physical or installation credit; source geometry changes zero.\n')
  s=importlib.util.spec_from_file_location('no1_garden_roof_edge_promotion_freeze',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);paths=[Path(__file__),HERE/'no1_garden_current_bound_roof_edge_identity_v4_20261010.py',HERE/'test_no1_garden_current_bound_roof_edge_identity_v4_20261010.py',HERE/'test_no1_garden_roof_edge_spatial_guards_20261010.py',HERE/'no1_garden_original_overhead_roof_edge_identity_20261010.py',HERE/'test_no1_garden_original_overhead_roof_edge_identity_20261010.py']+[p for p in INPUT.rglob('*') if p.is_file()]+[p for p in LOCAL.rglob('*') if p.is_file()]
  r=m.freeze(BATCH,'complete-current-source-authored-roof-edge-identity-v1',paths,{'uids':[row['uid']],'sourceSHA256':row['sourceSHA256'],'identityAccepted':True,'scriptFullAcceptancePassed':False,'physicalAccepted':False,'newlyInstalled':0,'manifestSHA256':read(INPUT/'current-inputs.json.gz')['manifestSHA256'],'nextStep':'Complete independent original terrain/whole foundations/component support/actual current foreign/native/runtime/browser gates; source foreign is not imported.'});print(r['jobId'],flush=True)
 finally:assert reservations.release(claim['reservation'])['ok']
if __name__=='__main__':main()
