"""New authoritative current glTF archive/member capture for the two stable source identities."""
import json,sys,importlib.util,uuid,zipfile
from run import ROOT,HERE,read,save,digest,connect,reservations
sys.path.insert(0,str(HERE.parent/'landsd-territory'));from source import request
BATCH='government-xl-popcorn-current-gltf-source-lineage-20261009';DOC=ROOT/'docs/astra-city/government-import'/BATCH;LOCAL=HERE/'local'/BATCH;PAIR=ROOT/'docs/astra-city/government-import/government-xl-popcorn-complete-original-current-pair-20261009'
def main():
 assert not DOC.exists();selection=read(PAIR/'selection.json.gz');rows=selection['rows'];claim=reservations.claim('popcorn-current-lineage-'+str(uuid.uuid4()),['building:'+r['uid'] for r in rows]+['native-model:'+r['native']['cacheKey']+'/'+r['modelId'] for r in rows],batch=BATCH,ttl=1800);assert claim['ok'],claim;lease=claim['reservation']
 try:
  spec=importlib.util.spec_from_file_location('popcorn_current_original','xl-next-support-recovery-20261005.py' if False else HERE/'xl-next-support-recovery-20261005.py');helper=importlib.util.module_from_spec(spec);spec.loader.exec_module(helper);sheets=sorted({r['native']['sheet'] for r in rows});params={'f':'json','where':'SHEETNO IN ('+','.join("'"+s+"'" for s in sheets)+')','outFields':'*','returnGeometry':'false','resultRecordCount':'1000'};raw,receipt=request('https://portal.csdi.gov.hk/server/rest/services/common/landsd_rcd_1742809441342_98380/FeatureServer/0/query',params);index=json.loads(raw);assert len(index['features'])==len(sheets);DOC.mkdir(parents=True);(DOC/'current-package-index.json').write_bytes(raw);save(DOC/'current-package-index.request.json',receipt);out=[]
  for f in index['features']:
   a=f['attributes'];sheet=a['SHEETNO'];folder=LOCAL/'sheets'/sheet;directory,scan=helper.scan(a,folder/'directory');want=[r for r in rows if r['native']['sheet']==sheet];directory['models']=[m for m in directory['models'] if m['modelId'] in {r['modelId'] for r in want}];assert len(directory['models'])==len(want);download=helper.acquire(directory,folder/'directory/zip-directory.bin',folder/'original');packed=folder/'packed';packed.mkdir(exist_ok=True)
   with zipfile.ZipFile(folder/'original'/(sheet+'.zip')) as archive:
    for r in want:
     info=archive.getinfo(r['native']['model']['sourceEntry']);converted=helper._convert_one(archive,info,folder/'decoded',packed,{}, {'modelId':r['modelId']});original=(packed/converted['asset']['asset']).read_bytes();canonical=helper.canonical_bytes(original,r['sourceSHA256']);assert digest(canonical)==r['sourceSHA256'];dest=LOCAL/'assets'/(r['sourceSHA256']+'.glb.gz');dest.parent.mkdir(parents=True,exist_ok=True);dest.write_bytes(canonical);out.append({'uid':r['uid'],'modelId':r['modelId'],'exactCurrentStableCSUID':r['source']['building']['buildingCSUID'],'freshCurrentNativeSourceSHA256':digest(canonical),'freshUncanonicalizedPackedSHA256':digest(original),'expectedFrozenNativeSHA256':r['sourceSHA256'],'providerCurrentRevisionDate':a['REVISIONDATE'],'currentArchiveURL':a['Format_glTF'],'currentETag':directory['etag'],'currentDirectorySHA256':directory['directorySHA256'],'originalGLTFMember':{'name':info.filename,'crc32':info.CRC,'decodedBytes':info.file_size,'memberSHA256':digest(archive.read(info.filename))},'currentSourceHashUnchanged':True,'assetPath':str(dest.relative_to(ROOT)),'modelGeometryChanges':0})
  save(DOC/'fresh-current-source-asset-lineage.json',{'rows':out,'qualifier':'Fresh current official archive index/directory/ETag/member bytes, canonical native-byte hash exactly unchanged. Volatile provider OBJECTID changes are explicitly recorded separately; no viewer metadata edits or physical acceptance inherited.','geometryChanges':0,'installationApproved':False});print([{k:r[k] for k in ['uid','modelId','freshCurrentNativeSourceSHA256','currentSourceHashUnchanged']} for r in out],flush=True)
 finally:assert reservations.release(lease)['ok']
if __name__=='__main__':main()
