"""Strict unchanged two-original collection metrics, no exclusions or courtyard credit."""
import importlib.util,numpy as np,shapely
from shapely.geometry import Polygon,mapping
from run import ROOT,HERE,read,save,digest
from government_georef_cell_identity import geographic_cell
DOC=ROOT/'docs/astra-city/government-import/government-xl-popcorn-station-collection-20261009';OPEN=ROOT/'docs/astra-city/government-import/government-xl-source-authored-openings-20261009';SURFACE=ROOT/'docs/astra-city/government-import/government-xl-spatial-surface-roles-20261009';r=read(OPEN/'295538-0/opening-diagnostics.json.gz');target=shapely.union_all([Polygon(b['rings'][0],b['rings'][1:]) for b in r['groupForms']]);proofs=[];projections=[];triangles=[];cells=[]
for batch,mid,uid in [('government-xl-source-authored-openings-20261009',r['modelId'],r['uid']),('government-xl-popcorn-station-collection-20261009','B448271874701063C0','landsd/295539:0')]:
 base=HERE/'local'/batch/'raw-fbx'/mid;info=read(base/'inspection.json');tri=np.load(base/'full-world-triangles.npz')['triangles'];assert digest(tri.astype('<f8').tobytes())==info['worldTrianglesSHA256'];v=np.stack([tri[:,:,0]-834500,tri[:,:,2],816500-tri[:,:,1]],axis=2);p=shapely.union_all(shapely.polygons(v[:,:,[0,2]]));projections.append(p);triangles.append(v);proofs.append(info);b=next(b for b in r['groupForms'] if b['uid']==uid);cell=geographic_cell(mid,b['buildingCSUID'],b['structureType']);cells.append({'uid':uid,'modelId':mid,'wholeCellInsideOriginalProjection':bool(p.covers(cell)),'wholeCellInsideExactTarget':bool(Polygon(b['rings'][0],b['rings'][1:]).covers(cell)),'geometry':mapping(cell)})
s=importlib.util.spec_from_file_location('popcorn_collection_forms',HERE/'xl-final-script-pass.py');final=importlib.util.module_from_spec(s);s.loader.exec_module(final)
proj=shapely.union_all(projections);missing=target.difference(proj);excess=proj.difference(target);x0,z0,x1,z1=proj.bounds;context=final.load_forms([x0-2,z0-2,x1+2,z1+2]);group={b['uid'] for b in r['groupForms']};others=[p for b,p,_ in context if b['uid'] not in group];overlap=excess.intersection(shapely.union_all(others));polys=[p for p in ([proj] if proj.geom_type=='Polygon' else proj.geoms) if p.geom_type=='Polygon'];points=np.concatenate([np.asarray(p.exterior.coords) for p in polys]);extent=float(shapely.distance(shapely.points(points),target).max());coverage=float(target.intersection(proj).area/target.area);metrics={'targetCoverage':coverage,'maximumExtentM':extent,'unrelatedExcessOverlapM2':float(overlap.area)};strict=coverage>=.95 and extent<=10 and overlap.area<=1 and all(c['wholeCellInsideOriginalProjection'] and c['wholeCellInsideExactTarget'] for c in cells)
result={'uid':r['uid'],'name':r['name'],'groupForms':r['groupForms'],'sourceProofs':proofs,'originalCells':cells,'rawStrictSingleSourceCoverage':r['rawTargetCoverage'],'completeCollectionMeasures':metrics,'targetAreaM2':float(target.area),'remainingMissingAreaM2':float(missing.area),'sourceOriginalTriangleCount':sum(map(len,triangles)),'fullOriginalWorldTrianglesSHA256':digest(np.concatenate(triangles).astype('<f8').tobytes()),'strictSpatialDiagnosticPass':bool(strict),'identityAccepted':False,'installationApproved':False,'geometryChanges':0,'qualification':'Both exact full original FBX geometries under authored metre/HKPD poses. Full existing grouped forms and all neighbours remain; no source/GIS edits, excluded openings, suppressed components, fitted placement or threshold waiver. Spatial diagnostic is not full physical/runtime acceptance.'};save(DOC/'complete-original-popcorn-station-measures.json.gz',result);save(DOC/'exact-collection-difference.geojson',{'type':'FeatureCollection','features':[{'type':'Feature','properties':{'role':role},'geometry':mapping(g)} for role,g in [('complete-original-collection',proj),('unchanged-full-target',target),('remaining-missing',missing),('source-excess',excess),('unrelated-overlap',overlap)]]});print({k:result[k] for k in ['completeCollectionMeasures','remainingMissingAreaM2','sourceOriginalTriangleCount','strictSpatialDiagnosticPass','originalCells']},flush=True)
