"""Bounded fresh FBX/MAX source directory research for one exact ancillary structure."""
import sys,json,struct,importlib.util,concurrent.futures
from pathlib import Path
from run import ROOT,HERE,read,save,digest
sys.path.insert(0,str(HERE.parent/'landsd-territory'));from source import request
sys.path.insert(0,str(HERE.parent/'citywide-source'));from discover import ac
BATCH='government-xl-science-canopy-fresh-other-format-directories-20261009';DOC=ROOT/'docs/astra-city/government-import'/BATCH;LOCAL=HERE/'local'/BATCH
SHEETS=['11-NW-25A','11-NW-25B','11-NW-25C','11-NW-25D'];URL='https://portal.csdi.gov.hk/server/rest/services/common/landsd_rcd_1742809441342_98380/FeatureServer/0/query'
def main():
 assert not DOC.exists();DOC.mkdir(parents=True);params={'f':'json','where':'SHEETNO IN('+','.join("'"+s+"'" for s in SHEETS)+')','outFields':'*','returnGeometry':'false','resultRecordCount':'1000'};raw,receipt=request(URL,params);index=json.loads(raw);assert not index.get('error') and not index.get('exceededTransferLimit') and len(index['features'])==4 and {f['attributes']['SHEETNO'] for f in index['features']}==set(SHEETS);(DOC/'fresh-official-package-index.json').write_bytes(raw);save(DOC/'fresh-official-package-index.request.json',receipt)
 tasks=[(f['attributes'],fmt) for f in index['features'] for fmt in ['FBX','MAX']]
 def work(task):
  a,fmt=task;sheet=a['SHEETNO'];folder=LOCAL/(sheet+'-'+fmt);folder.mkdir(parents=True);net=ac.Network(folder/'directory-transfer.json',cap=2_000_000);url=a['Format_'+fmt];_,headers=net.get(url,0,method='HEAD');etag=headers['ETag'];size=int(headers['Content-Length']);tail,h=net.get(url,65536,'-65536',etag);end=tail.rfind(b'PK\x05\x06');assert end>=0;fields=struct.unpack('<4s4H2LH',tail[end:end+22]);offset=fields[6];start=int(h['Content-Range'].split()[1].split('-')[0]);assert int(h['Content-Range'].split('/')[-1])==size
  if offset<start:prefix,_=net.get(url,start-offset,f'{offset}-{start-1}',etag);directory=prefix+tail
  else:directory=tail[offset-start:]
  infos,check=ac.parse_directory(directory);(folder/'zip-directory.bin').write_bytes(directory);matches=[{'name':e.filename,'crc32':e.CRC,'headerOffset':e.header_offset,'compressedBytes':e.compress_size,'decodedBytes':e.file_size} for e in infos if '3631518015' in e.filename];building_models=sorted({e.filename.split('/')[1] for e in infos if e.filename.startswith('BUILDING/') and len(e.filename.split('/'))>2});r={'sheet':sheet,'format':fmt,'sourceURL':url,'etag':etag,'archiveBytes':size,'revision':a['REVISIONDATE'],'completeEntries':len(infos),'buildingModels':len(building_models),'completeBuildingModelIdentifiers':building_models,'matches':matches,'checkedAt':ac.now(),'receivedDirectoryBytes':net.data['receivedBytes'],**check};save(folder/'directory.json',r);print(json.dumps({k:r[k] for k in ['sheet','format','buildingModels','matches','receivedDirectoryBytes']}),flush=True);return r
 with concurrent.futures.ThreadPoolExecutor(max_workers=2) as pool:rows=list(pool.map(work,tasks))
 save(DOC/'exact-canopy-other-format-source-search.json',{'uid':'landsd/83471:0','csuid':'3631518015T20071227','rows':rows,'qualification':'Fresh complete ETag-bound original FBX0/MAX0 directory byte searches on four exact/adjacent25quadrants. No payload conversion, source corruption or territory-wide absence claim. Each format/revision is independent.'})
 paths=[Path(__file__),HERE.parent/'landmark-acquisition/acquire.py',HERE.parent/'landsd-territory/source.py',DOC.parent/'government-xl-science-museum-open-structure-primary-20261009/result.json',DOC.parent/'government-xl-science-open-structure-fresh-directory-20261009/result.json'];paths +=[p for p in LOCAL.rglob('*') if p.is_file()]
 spec=importlib.util.spec_from_file_location('science_other_formats_fence',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');f=importlib.util.module_from_spec(spec);spec.loader.exec_module(f);f.freeze(BATCH,'fresh-complete-exact-canopy-FBX-MAX-source-directory-search-v1',paths,{'uids':['landsd/80343:0','landsd/83471:0'],'freshSourceDirectories':len(rows),'exactCanopyMemberMatches':sum(len(r['matches']) for r in rows),'buildingIdentifierEntriesAcrossFormats':sum(r['buildingModels'] for r in rows),'receivedDirectoryBytes':sum(r['receivedDirectoryBytes'] for r in rows),'territoryAbsenceEstablished':False,'sourceCorruptionEstablished':False,'identityAccepted':False,'scriptFullAcceptancePassed':False,'nextStep':'Acquire independently pinned original exact ancillary member only if found; otherwise retain recorded source-version ground incompatibility and move to another actionable identity route.'})
if __name__=='__main__':main()
