"""Complete untouched museum/current open-sided canopy interfaces, no identity waiver."""
import numpy as np
from run import ROOT,HERE,read,save,digest
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from exact_original_component_contacts_20261009 import exact_component_contacts
DOC=ROOT/'docs/astra-city/government-import/government-xl-science-open-sided-current-interface-20261009'
def main():
 assert not (DOC/'result.json').exists();inp=DOC/'complete-current-open-sided-canopy.json.gz';x=read(inp)
 for p,h in x['inputHashes'].items():assert digest((ROOT/p).read_bytes())==h,p
 path=DOC.parent/'xl-terrain-recovery-20261009-80343-current-inputs/check-selection.json.gz';row=read(path)['rows'][0];raw=(ROOT/row['candidate']['path']).read_bytes();assert digest(raw)==row['sourceSHA256'];t=decode_original_world_triangles(raw);assert len(t)==row['triangles']==11520;b=x['currentRendererBody'];body=np.asarray(b['position'],float).reshape(-1,3)[np.asarray(b['index']).reshape(-1,3)];packet=read(DOC.parent/'xl-terrain-recovery-20261009-science-open-structure-context/diagnostic.json.gz');assert max(float(np.abs(t[f['face']]-np.asarray(f['vertices'])).max()) for f in packet['sourceFaces'])<1e-12
 def ids(v):return np.flatnonzero(np.any(np.cross(v[:,1]-v[:,0],v[:,2]-v[:,0])!=0,axis=1)).tolist()
 result=exact_component_contacts(t,ids(t),body,ids(body),first_only=False);save(DOC/'complete-original-current-canopy-contacts.json.gz',{'uid':row['uid'],'sourceSHA256':row['sourceSHA256'],'wholeOriginalFaces':len(t),'worldTrianglesSHA256':digest(t.astype('<f8').tobytes()),'currentCanopyUID':x['uid'],'wholeCurrentCanopyFaces':len(body),'exactContact':result,'countsByDimension':{str(d):sum(c['dimension']==d for c in result['contacts']) for d in range(3)},'originalZeroAreaFacesRetained':[i for i in range(len(t)) if i not in set(ids(t))],'currentZeroAreaFacesRetained':[i for i in range(len(body)) if i not in set(ids(body))],'estimatedCanopyVerticalShapeHasNoPrimaryPrecision':True,'sourceGeometryChanges':0,'currentActorChanges':0,'identityAccepted':False,'physicalAccepted':False,'inputHashes':{**x['inputHashes'],str(inp.relative_to(ROOT)):digest(inp.read_bytes()),str(path.relative_to(ROOT)):digest(path.read_bytes()),row['candidate']['path']:digest(raw)},'qualification':'Complete original/current surface query with all original positive-area faces and explicit retained zero-area accounting. Current roof/posts are unchanged illustrative geometry; true related ownership and all full physical/runtime gates remain independent. Raw 1.855m² source/foreign projected excess is not waived.'});print({'originalFaces':len(t),'currentFaces':len(body),'countsByDimension':{str(d):sum(c['dimension']==d for c in result['contacts']) for d in range(3)}})
if __name__=='__main__':main()
