"""Stage Greenery Garden and its exact Block C government support as one assembly."""
import gzip,importlib.util,json,shutil,struct,subprocess,sys,uuid
from pathlib import Path
import numpy as np
from shapely.geometry import MultiPoint,Polygon
sys.path.insert(0,str(Path(__file__).resolve().parent));spec=importlib.util.spec_from_file_location('second',Path(__file__).with_name('xl-second-pass.py'));s=importlib.util.module_from_spec(spec);spec.loader.exec_module(s)
ROOT,HERE=s.ROOT,s.HERE;read,save,h,rel=s.read,s.save,s.h,s.rel
BATCH='government-xl-greenery-garden-20260914';DOC=s.DOC/'third-pass/greenery-garden';LOCAL=s.LOCAL/'third-pass-greenery-assembly';STAGE=HERE/'accepted'/BATCH;TOWER='landsd/264029:0';SUPPORT='landsd/233384:0';UIDS=[SUPPORT,TOWER]
def call(args,allowed=(0,)):
 result=subprocess.run(args,cwd=ROOT);assert result.returncode in allowed,(args,result.returncode)
def rows():
 frozen=read(s.DOC/'runtime-selection.json.gz');tower=next(r for r in frozen['rows'] if r['uid']==TOWER);recovered=read(s.LOCAL/'third-pass-greenery-support/support-runtime.json.gz');assert recovered['aiCalls']==recovered['modelGeometryChanges']==0;return frozen,[recovered['rows'][0],tower]
def start():
 frozen,items=rows();manifest_sha=h(ROOT/'3d-viewer/city/data/manifest.json');save(DOC/'assembly-selection.json.gz',{**frozen,'manifestSHA256':manifest_sha,'rows':items});claim=s.reservations.claim('codex-xl-greenery-'+str(uuid.uuid4()),['building:'+uid for uid in UIDS],batch=BATCH);assert claim['ok'];save(LOCAL/'reservation.json',json.loads(json.dumps(claim['reservation'],default=str)));call([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(LOCAL/'reservation.json'),'--',sys.executable,__file__,'owned'])
def budget(entries):
 result={'count':len(entries),'geometryBytes':0,'residentBytes':0,'triangles':0};limits={'count':24,'geometryBytes':48*1024*1024,'residentBytes':128*1024*1024,'triangles':450000}
 for e in entries:
  collision=e['indexedVertices']*24+e['triangles']*(12+48+64);result['geometryBytes']+=e['decodedGeometryBytes'];result['residentBytes']+=e['decodedGeometryBytes']*2+collision+65536;result['triangles']+=e['triangles']
 result['mobilePassed']=all(result[k]<=limits[k] for k in limits);return result,limits
def support_foundation(row):
 spec=importlib.util.spec_from_file_location('final_pass',HERE/'xl-final-script-pass.py');final_pass=importlib.util.module_from_spec(spec);spec.loader.exec_module(final_pass);raw=gzip.decompress(Path(row['candidate']['path']).read_bytes());size,kind=struct.unpack_from('<II',raw,12);assert kind==0x4e4f534a;data=json.loads(raw[20:20+size]);at=20+size;n,binary_kind=struct.unpack_from('<II',raw,at);assert binary_kind==0x004e4942 and at+8+n==len(raw);unpacked=LOCAL/'support-unpacked';unpacked.mkdir(parents=True,exist_ok=True);(unpacked/'buffer.bin').write_bytes(raw[at+8:]);data['buffers'][0]['uri']='buffer.bin';save(unpacked/'model.gltf',data);triangles=s.context.triangles(unpacked/'model.gltf');source=next(x for x in read(s.DOC/'recovery.json')['sheets'] if x['sheet']=='11-SW-11B');terrain=np.concatenate([s.terrain_triangles(ROOT/path) for path in source['terrainPaths']]);form=row['source']['building'];result=final_pass.foundation_context(triangles,terrain,Polygon(form['rings'][0],form['rings'][1:]));result.update(passed=result['completeTerrainTriangles']==result['triangles'] and result['fullyBuriedTriangles']==result['fullyBuriedUpwardTriangles']==0,sourceSHA256=row['candidate']['entry']['sha256'],sourceTerrainHashes={path:h(ROOT/path) for path in source['terrainPaths']},policy='Every unchanged Block C source face and centre checked against exact terrain from the same pinned government sheet; full coverage and zero fully buried faces are required.',aiCalls=0,modelGeometryChanges=0);return result
def owned():
 assert s.reservations.owns(read(LOCAL/'reservation.json'));selection=read(DOC/'assembly-selection.json.gz');assert h(ROOT/'3d-viewer/city/data/manifest.json')==selection['manifestSHA256'];by_uid={r['uid']:r for r in selection['rows']};assert set(by_uid)==set(UIDS);final=next(r for r in read(s.DOC/'final-script-pass/results.json.gz')['rows'] if r['uid']==TOWER);assert final['scriptedWorkComplete'] and final['identityScriptAccepted'] and final['foundationScriptAccepted'] and final['runtime']['mobileBudgetPassed'] and final['runtime']['sourcePreserved'] and not final['runtime']['missingTerrain'] and final['aiCalls']==final['modelGeometryChanges']==0
 support=by_uid[SUPPORT]['candidate']['entry'];form=by_uid[SUPPORT]['source']['building'];support_identity={'exactObjectId':support['objectId']==form['objectId'],'exactBuildingCSUID':support['buildingCSUID']==form['buildingCSUID'],'modelIdEmbedsCSUID':support['modelId'][1:11]==support['buildingCSUID'][:10],'overlapOfSmallerFootprint':support['overlapOfSmallerFootprint'],'centroidDistanceMetres':support['footprintCentroidDistanceMetres']};support_identity['passed']=all(support_identity[k] for k in ('exactObjectId','exactBuildingCSUID','modelIdEmbedsCSUID')) and support_identity['overlapOfSmallerFootprint']>=.95 and support_identity['centroidDistanceMetres']<=2;assert support_identity['passed'];save(DOC/'assembly-identity.json',{'towerFrozenIdentity':final['identity'],'towerIdentityScriptAccepted':True,'support':support_identity,'samePinnedSheet':True,'sourceSheet':'11-SW-11B','aiCalls':0,'modelGeometryChanges':0})
 call(['node',str(HERE/'xl-greenery-support-contact.mjs')]);raw=read(DOC/'support-contact-raw.json')['row'];target=Polygon(by_uid[TOWER]['source']['building']['rings'][0],by_uid[TOWER]['source']['building']['rings'][1:]);contact=MultiPoint([(x,z) for x,y,z in raw.pop('contactPositions')]).convex_hull;coverage=contact.intersection(target).area/target.area;contact_proof={**raw,'contactProjectionAreaM2':contact.area,'contactHullTargetCoverage':coverage,'contactHullBounds':list(contact.bounds),'passed':raw['rimSamples']>=50 and raw['within05']==raw['rimSamples'] and raw['maximumDistance']<=.5 and coverage>=.8};assert contact_proof['passed'];save(DOC/'support-contact.json',{'row':contact_proof,'policy':'Every unique tower low-rim vertex must lie within 0.5m of the exact Block C government mesh, with at least 50 rim vertices and a projected contact hull covering at least 80% of the tower footprint.','aiCalls':0,'modelGeometryChanges':0})
 foundation=support_foundation(by_uid[SUPPORT]);assert foundation['passed'];save(DOC/'support-native-foundation.json',foundation)
 terrain_doc=s.DOC/'third-pass/terrain-greenery-garden';terrain_result=read(terrain_doc/'result.json');assert terrain_result['reasons']==['ground-contact-unresolved','sampled-ground-gap-below-model-bottom'];neighbours=read(terrain_doc/'neighbour-checks.json');assert not neighbours['patches'][0]['blockedBy'];patch_entry=terrain_result['patch'];source_patch=ROOT/patch_entry['path'];assert h(source_patch)==patch_entry['sha256'];patch=read(source_patch);assert set(patch['meta']['targetUids'])==set(UIDS);stage_patch=STAGE/source_patch.name;stage_patch.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(source_patch,stage_patch);staged_patch={'path':rel(stage_patch),'sha256':h(stage_patch),'uids':UIDS,'bounds':patch_entry['bounds'],'triangles':patch_entry['triangles']};terrain_publication={'source':rel(stage_patch),'sha256':h(stage_patch),'destination':'city/data/'+stage_patch.name,'resolution':patch['cell'],'area':'Greenery Garden exact native terrain'};save(DOC/'terrain-candidates.json',[staged_patch])
 entries=[];source_forms=[];source_map={}
 for uid in UIDS:
  row=by_uid[uid];entry=dict(row['candidate']['entry']);entry.update(priority='landmark' if uid==TOWER else 'detail',placementReviewed=True,sourceIdentityReviewed=True,identityReviewApproved=True,placementReview='Exact unchanged government source matched by object ID and Building CSUID in pinned sheet 11-SW-11B. Greenery Garden and Block C form a support-first assembly with exact mesh-contact and same-sheet terrain proofs; no model geometry edits and no AI modelling or review.')
  if uid==TOWER:entry['supportDependencies']=[{'uid':SUPPORT,'state':'candidate','csuid':support['buildingCSUID'],'sha256':support['sha256']}]
  asset=STAGE/entry['asset'];asset.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(row['candidate']['path'],asset);assert h(asset)==entry['sha256'];entries.append(entry);source_map[uid]=row['source'];f=dict(row['source']['building']);f['tile']=Path(row['source']['tile']).stem;source_forms.append(f)
 group,limits=budget(entries);assert group['mobilePassed'];save(DOC/'assembly-budget.json',{'measured':group,'mobileLimits':limits,'aiCalls':0});catalogue=read(HERE/'accepted/government-xxl-20260911/catalogue.json');catalogue.update(area='Greenery Garden and Block C original government assembly',counts={'packedModels':2},models=entries);save(STAGE/'catalogue.json',catalogue);save(STAGE/'catalogue-index.json',{'models':2,'catalogues':['catalogue.json']});save(STAGE/'source-forms.json',source_forms);save(LOCAL/'source-forms.json',source_map)
 call(['node',str(HERE/'acceptance-metrics.mjs'),'--selection',rel(DOC/'assembly-selection.json.gz'),'--candidates',rel(STAGE),'--terrain-candidates',rel(DOC/'terrain-candidates.json'),'--out',rel(DOC/'assembly-metrics.json')]);call(['node',str(HERE.parent/'building-batch/validate_candidates.mjs'),'--candidates',rel(STAGE),'--source-forms',rel(LOCAL/'source-forms.json'),'--terrain-candidates',rel(DOC/'terrain-candidates.json'),'--out',rel(DOC/'assembly-validation.json')],allowed=(0,1));metrics=read(DOC/'assembly-metrics.json');validation=read(DOC/'assembly-validation.json');reasons=[]
 for metric in metrics['rows']:
  if metric.get('error') or not metric.get('sourcePreserved') or metric.get('missingTerrain') or metric.get('maxSamplerDelta',0)>.004:reasons.append(metric['uid']+':source-integrity-or-terrain')
  if metric.get('budget') and any(metric['budget'][k]>metrics['profiles']['mobile'][k] for k in ('triangles','geometryBytes','residentBytes')):reasons.append(metric['uid']+':mobile-runtime-budget')
 allowed={TOWER:{'sampled-ground-gap-below-model-bottom','sampled-terrain-above-model-bottom'},SUPPORT:{'sampled-terrain-above-model-bottom'}}
 for result in validation['results']:
  if result['outcome']=='validation-exception':reasons.append(result['uid']+':runtime-validation-exception')
  reasons.extend(result['uid']+':'+c for c in result.get('concerns',[]) if c not in allowed[result['uid']])
 decision={'uids':UIDS,'policy':'original-government-greenery-support-assembly-v1','passed':not reasons,'reasons':sorted(set(reasons)),'patch':staged_patch,'groupBudget':group,'identitySHA256':h(DOC/'assembly-identity.json'),'supportContactSHA256':h(DOC/'support-contact.json'),'supportFoundationSHA256':h(DOC/'support-native-foundation.json'),'sourceRecoverySHA256':h(DOC/'support-source-recovery.json'),'neighbourChecksSHA256':h(terrain_doc/'neighbour-checks.json'),'aiCalls':0,'modelGeometryChanges':0,'publication':False};save(DOC/'assembly-result.json',decision)
 if decision['passed']:
  destination='city/data/official-models/'+BATCH+'/catalogue.json';save(STAGE/'plan.json',{'areas':[{'area':catalogue['area'],'catalogue':rel(STAGE/'catalogue.json'),'destination':destination}],'topLevelTerrainPatches':[terrain_publication]});save(STAGE/'browser-config.json',{'stage':rel(STAGE)+'/','doc':rel(DOC)+'/','catalogueURL':destination,'terrain':[terrain_publication],'fitBox':True,'browserUids':[TOWER],'failureTestUids':[TOWER]})
 print(json.dumps(decision))
if __name__=='__main__':owned() if len(sys.argv)>1 else start()
