"""Stage unchanged 1881 Heritage source after proving its retained tower support."""
import importlib.util,json,shutil,subprocess,sys,uuid
from pathlib import Path
import numpy as np
import shapely
from shapely.geometry import Polygon
sys.path.insert(0,str(Path(__file__).resolve().parent));spec=importlib.util.spec_from_file_location('second',Path(__file__).with_name('xl-second-pass.py'));s=importlib.util.module_from_spec(spec);spec.loader.exec_module(s)
ROOT,HERE=s.ROOT,s.HERE;read,save,h,rel=s.read,s.save,s.h,s.rel
UID='landsd/264745:0';SUPPORT='landsd/208117:0';BATCH='government-xl-1881-20260914';DOC=s.DOC/'third-pass/1881-heritage';LOCAL=s.LOCAL/'third-pass-1881-heritage';STAGE=HERE/'accepted'/BATCH
def call(args,allowed=(0,)):
 result=subprocess.run(args,cwd=ROOT);assert result.returncode in allowed,(args,result.returncode)
def support_proof(source,building):
 triangles=s.glb_triangles(source);polygons=shapely.polygons(triangles[:,:,[0,2]]);valid=shapely.area(polygons)>1e-10;triangles=triangles[valid];polygons=polygons[valid];tree=shapely.STRtree(polygons);projection=shapely.union_all(polygons)
 footprint=Polygon(building['rings'][0],building['rings'][1:]);ring=np.asarray(building['rings'][0]);lo,hi=ring.min(0),ring.max(0);step=max(2,float(np.sqrt((hi[0]-lo[0])*(hi[1]-lo[1])/2500)))
 points=np.array([[x,z] for x in np.arange(lo[0]+step/2,hi[0],step) for z in np.arange(lo[1]+step/2,hi[1],step) if footprint.covers(shapely.Point(x,z))]);base=building['base']+building.get('minimum',0);heights=np.full(len(points),-np.inf)
 pi,ti=tree.query(shapely.points(points),predicate='covered_by');abc=triangles[ti];ab=abc[:,1,[0,2]]-abc[:,0,[0,2]];ac=abc[:,2,[0,2]]-abc[:,0,[0,2]];ap=points[pi]-abc[:,0,[0,2]];det=ab[:,0]*ac[:,1]-ab[:,1]*ac[:,0];u=(ap[:,0]*ac[:,1]-ap[:,1]*ac[:,0])/det;v=(ab[:,0]*ap[:,1]-ab[:,1]*ap[:,0])/det;ys=abc[:,0,1]+u*(abc[:,1,1]-abc[:,0,1])+v*(abc[:,2,1]-abc[:,0,1]);ok=ys<=base+.1;np.maximum.at(heights,pi[ok],ys[ok]);covered=np.isfinite(heights);gaps=base-heights
 coverage=footprint.intersection(projection).area/footprint.area;passed=coverage>=.9999 and len(points)>0 and covered.sum()/len(points)>=.9 and np.abs(gaps[covered]).max()<=.1
 return {'uid':building['uid'],'supportUid':UID,'footprintCoverage':coverage,'interiorSamples':len(points),'covered':int(covered.sum()),'coveredFraction':float(covered.mean()),'gapRangeM':[float(gaps[covered].min()),float(gaps[covered].max())] if covered.any() else None,'passed':bool(passed)}
def start():
 resources=['building:'+UID,'building:'+SUPPORT];claim=s.reservations.claim('codex-xl-1881-stage-'+str(uuid.uuid4()),resources,batch=BATCH);assert claim['ok'];save(LOCAL/'reservation.json',json.loads(json.dumps(claim['reservation'],default=str)));runtime=next(r for r in read(s.DOC/'runtime-selection.json.gz')['rows'] if r['uid']==UID);save(DOC/'selection.json.gz',{'manifestSHA256':h(ROOT/'3d-viewer/city/data/manifest.json'),'rows':[runtime]});call([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(LOCAL/'reservation.json'),'--',sys.executable,__file__,'owned'])
def owned():
 assert s.reservations.owns(read(LOCAL/'reservation.json'));selection=read(DOC/'selection.json.gz');assert h(ROOT/'3d-viewer/city/data/manifest.json')==selection['manifestSHA256'];runtime=selection['rows'][0];final=next(r for r in read(s.DOC/'final-script-pass/results.json.gz')['rows'] if r['uid']==UID);source=next(r for r in read(s.DOC/'selection.json.gz')['rows'] if r['uid']==UID)
 identity,foundation,run=final['identity'],final['foundation'],final['runtime'];assert final['publicationCandidate'] and final['scriptedWorkComplete'] and final['aiCalls']==final['modelGeometryChanges']==0;assert identity['exactObjectAndCSUID'] and identity['targetCoveredBySourceProjection']>.99 and identity['sourceExcessFraction']<.09 and identity['unrelatedIntersectingForms']==0;assert foundation['fullyBuriedTriangles']==0 and foundation['minimumGapM']>-.5;assert run['sourcePreserved'] and run['mobileBudgetPassed'] and not run['missingTerrain'] and run['minimumCurrentViewerSurfaceGapM']>-.5 and run['maximumCurrentViewerLowRimGapM']<1
 manifest=read(ROOT/'3d-viewer/city/data/manifest.json');support=next(b for tile in manifest['tiles'] for b in read(ROOT/'3d-viewer'/tile['url'])['buildings'] if b['uid']==SUPPORT);proof=support_proof(source,support);assert proof['passed'];save(DOC/'source-support.json',{'rows':[proof],'resolved':[SUPPORT],'sourceSHA256':source['sourceSHA256'],'policy':'Highest unchanged government source surface at or below >=90% of <=2m interior samples, >=99.99% footprint coverage, and <=0.1m support gap at every covered sample.','aiCalls':0})
 entry=dict(runtime['candidate']['entry']);entry.update(priority='detail',placementReviewed=True,sourceIdentityReviewed=True,identityReviewApproved=True,placementReview='Exact unchanged government 1881 Heritage podium matched by object ID and Building CSUID. The retained tower remains visible and is supported across its complete footprint with a 4.7 cm roof overlap. Current terrain, foundation and runtime checks pass. No AI modelling or geometry edits.');asset=STAGE/entry['asset'];asset.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(runtime['candidate']['path'],asset);assert h(asset)==entry['sha256'];catalogue=read(HERE/'accepted/government-xxl-20260911/catalogue.json');catalogue.update(area='1881 Heritage original government model',counts={'packedModels':1},models=[entry]);save(STAGE/'catalogue.json',catalogue);save(STAGE/'catalogue-index.json',{'models':1,'catalogues':['catalogue.json']});form=dict(runtime['source']['building']);form['tile']=Path(runtime['source']['tile']).stem;save(STAGE/'source-forms.json',[form]);save(DOC/'terrain-candidates.json',[]);save(LOCAL/'source-forms.json',{UID:runtime['source']})
 call(['node',str(HERE/'acceptance-metrics.mjs'),'--selection',rel(DOC/'selection.json.gz'),'--candidates',rel(STAGE),'--terrain-candidates',rel(DOC/'terrain-candidates.json'),'--out',rel(DOC/'metrics.json')]);call(['node',str(HERE.parent/'building-batch/validate_candidates.mjs'),'--candidates',rel(STAGE),'--source-forms',rel(LOCAL/'source-forms.json'),'--out',rel(DOC/'validation.json')],allowed=(0,1));metrics=read(DOC/'metrics.json');metric=metrics['rows'][0];validation=read(DOC/'validation.json');reasons=[]
 if metric.get('error') or not metric.get('sourcePreserved') or metric.get('missingTerrain') or metric.get('maxSamplerDelta',0)>.004:reasons.append('source-integrity-or-terrain')
 if metric.get('minSurfaceGap',0)<-.5 or metric.get('minLowGap',0)<-.5 or metric.get('maxLowGap',0)>1:reasons.append('ground-contact')
 if metric.get('budget') and any(metric['budget'][k]>metrics['profiles']['mobile'][k] for k in ('triangles','geometryBytes','residentBytes')):reasons.append('mobile-runtime-budget')
 for result in validation['results']:
  if result['outcome']=='validation-exception':reasons.append('runtime-validation-exception')
  reasons.extend(result.get('concerns',[]))
 decision={'uid':UID,'policy':'original-government-1881-supported-podium-v1','passed':not reasons,'reasons':sorted(set(reasons)),'retainedSupportUid':SUPPORT,'sourceSupportSHA256':h(DOC/'source-support.json'),'aiCalls':0,'modelGeometryChanges':0,'publication':False};save(DOC/'result.json',decision)
 if decision['passed']:
  destination='city/data/official-models/'+BATCH+'/catalogue.json';save(STAGE/'plan.json',{'areas':[{'area':catalogue['area'],'catalogue':rel(STAGE/'catalogue.json'),'destination':destination}]});save(STAGE/'browser-config.json',{'stage':rel(STAGE)+'/','doc':rel(DOC)+'/','catalogueURL':destination,'terrain':[],'fitBox':True,'browserUids':[UID],'failureTestUids':[UID],'retainedBuildingUids':[SUPPORT]})
 print(json.dumps(decision))
if __name__=='__main__':owned() if len(sys.argv)>1 else start()
