"""Publish three verified unchanged XL towers with retained basic podium supports."""
import importlib.util,json,shutil,subprocess,sys,uuid
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent));spec=importlib.util.spec_from_file_location('second',Path(__file__).with_name('xl-second-pass.py'));s=importlib.util.module_from_spec(spec);spec.loader.exec_module(s)
ROOT,HERE=s.ROOT,s.HERE;read,save,h,rel=s.read,s.save,s.h,s.rel
BATCH='government-xl-supported-towers-20260914';CHECK=s.DOC/'third-pass/supported-towers';LOCAL=s.LOCAL/'supported-towers-install';STAGE=HERE/'accepted'/BATCH;DOC=s.DOC/'third-pass/supported-towers-install';UIDS=['landsd/274763:0','landsd/162512:0','landsd/219311:0']
sys.path.insert(0,str(HERE.parent/'model-review-ledger'));import ledger
spec=importlib.util.spec_from_file_location('direct',HERE/'integrate.py');direct=importlib.util.module_from_spec(spec);spec.loader.exec_module(direct)
def call(args):subprocess.run(args,cwd=ROOT,check=True)
def start():
 assert read(CHECK/'result.json')['passed'];resources=read(s.LOCAL/'third-pass-supported-towers/reservation.json')['resources'];claim=s.reservations.claim('codex-xl-supported-towers-import-'+str(uuid.uuid4()),resources,batch=BATCH);assert claim['ok'];save(LOCAL/'reservation.json',json.loads(json.dumps(claim['reservation'],default=str)));call([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(LOCAL/'reservation.json'),'--',sys.executable,__file__,'owned'])
def owned():
 receipt=LOCAL/'reservation.json';assert s.reservations.owns(read(receipt));result=read(CHECK/'result.json');assert result['passed'] and result['uids']==UIDS and not result['reasons'] and result['aiCalls']==result['modelGeometryChanges']==0;support=read(CHECK/'support-proof.json');assert {r['uid'] for r in support['rows']}==set(UIDS) and all(r['passed'] for r in support['rows']) and support['aiCalls']==support['geometryChanges']==0;catalogue=read(STAGE/'catalogue.json');assert [m['uid'] for m in catalogue['models']]==UIDS;assert all(h(STAGE/m['asset'])==m['sha256'] for m in catalogue['models']);metrics=read(CHECK/'metrics.json');assert {r['uid'] for r in metrics['rows']}==set(UIDS) and all(r['sourcePreserved'] and not r['missingTerrain'] for r in metrics['rows']);validation=read(CHECK/'validation.json');assert validation['loaderAccepted']==validation['checksPassed']==len(UIDS) and validation['exceptions']==0;direct.browser_verified(CHECK/'staged-browser.json',set(UIDS))
 decision={'policy':result['policy'],'uids':UIDS,'sourceSHA256s':{m['uid']:m['sha256'] for m in catalogue['models']},'catalogueSHA256':h(STAGE/'catalogue.json'),'planSHA256':h(STAGE/'plan.json'),'resultSHA256':h(CHECK/'result.json'),'supportProofSHA256':h(CHECK/'support-proof.json'),'metricsSHA256':h(CHECK/'metrics.json'),'validationSHA256':h(CHECK/'validation.json'),'stagedBrowserSHA256':h(CHECK/'staged-browser.json'),'aiCallsThisImport':0,'geometryChanges':0};save(DOC/'decision.json',decision)
 pointer_path=ROOT/'docs/astra-city/model-integration-20260909/current-source-review.json';pointer=read(pointer_path);inventory=read(ROOT/pointer['inventory']);parts={p['uid']:p for p in inventory['parts']};models={m['uid']:m for m in catalogue['models']}
 for uid in UIDS:
  model=models[uid];previous=parts.get(uid,{});parts[uid]={'uid':uid,'name':model['label'],'landmarkIds':previous.get('landmarkIds',[]),'objectId':model['objectId'],'csuid':model['buildingCSUID'],'candidate':{'sha256':model['sha256']},'sourceProgress':'prepared-for-review','classification':'script-verified-original-government-supported-tower','knownHold':False}
 ordered=sorted(parts.values(),key=lambda row:row['uid']);snapshot=s.digest(s.jobs.encode([ordered,decision]).encode())[:16];inventory_path=pointer_path.parent/f'source-review-inventory-{snapshot}.json';save(inventory_path,{**inventory,'snapshotId':snapshot,'derivedFrom':pointer['snapshotId'],'parts':ordered});ledger.seed(inventory_path,inherit=pointer['snapshotId']);commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip();effort={'method':'scripted','ai_model':None,'reasoning_effort':'not-applicable','issue':'HKS-203','run_id':snapshot,'output_ref':rel(DOC/'decision.json')};observations={r['uid']:f"Exact unchanged government tower with retained basic podium {r['supportUid']}. The podium covers the source low rim and remains visible. Source integrity, foundation, runtime budget, staged/live browser, picking, collision and fallback/retry checks passed. No AI modelling, review or model geometry edits." for r in support['rows']};ledger.record_many(snapshot,receipt,[(uid,'approved-for-integration',DOC/'decision.json',observations[uid],commit) for uid in UIDS],effort=effort,request_id=BATCH+'-approved-'+snapshot)
 publish=[sys.executable,str(HERE.parent/'model-integration-20260909/publish.py'),rel(STAGE/'plan.json'),'--receipt',str(receipt),'--phase',BATCH];call(publish);manifest=ROOT/'3d-viewer/city/data/manifest.json';before=manifest.read_bytes();(LOCAL/'manifest-before.json').write_bytes(before);call(publish+['--apply'])
 try:call(['node',str(HERE/'resolution-browser.mjs'),'live',rel(STAGE/'browser-config.json')]);direct.browser_verified(CHECK/'live-browser.json',set(UIDS))
 except BaseException:
  manifest.write_bytes(before);shutil.rmtree(ROOT/'3d-viewer/city/data/official-models'/BATCH,ignore_errors=True);shutil.rmtree(ROOT/'docs/astra-city/model-integration-20260909'/BATCH,ignore_errors=True);raise
 acceptance={**decision,'snapshot':snapshot,'liveBrowserSHA256':h(CHECK/'live-browser.json'),'manifestSHA256':h(manifest)};save(DOC/'installed-acceptance.json',acceptance);ledger.record_many(snapshot,receipt,[(uid,'installed-verified',DOC/'installed-acceptance.json',observations[uid],commit) for uid in UIDS],effort=effort,request_id=BATCH+'-installed-'+snapshot);assert read(pointer_path)==pointer;save(pointer_path,{**pointer,'snapshotId':snapshot,'inventory':rel(inventory_path),'previousSnapshots':[*pointer.get('previousSnapshots',[]),pointer['snapshotId']]});call([sys.executable,str(HERE.parent/'building-progress/export.py'),'--refresh']);call(['node',str(ROOT/'3d-viewer/scripts/build_progress.mjs')]);save(DOC/'summary.json',{'installedUids':UIDS,'supports':{r['uid']:r['supportUid'] for r in support['rows']},'snapshot':snapshot,'aiCalls':0,'geometryChanges':0,'progress':read(ROOT/'3d-viewer/city/data/building-progress.json')});print(json.dumps({'installed':UIDS,'snapshot':snapshot,'aiCalls':0}))
if __name__=='__main__':owned() if len(sys.argv)>1 else start()
