"""Typed unchanged Block17 current roles; nonpublishing complete pinned recheck."""
import importlib.util,json,collections
from pathlib import Path
from fractions import Fraction as F
import numpy as np
from run import ROOT,HERE,read,save,digest,connect
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from exact_original_shared_edge_component_census_v2_20261011 import census
from exact_original_finite_triangle_contacts_20261010 import finite_intersection_points,exact_finite_contacts
from exact_original_shell_intersections_20261009 import rational_face
from exact_original_component_contacts_20261009 import contact_measure
from complete_original_lower_opening_mounts_v3_20261011 import verify as opening_verify,binding
B=ROOT/'docs/astra-city/government-import';BATCH='xl-terrain-recovery-20261011-parkview-block17-current-role-v1';DOC=B/BATCH
UID='landsd/256116:0';NATIVE='landsd/254491:0';SOURCE='d53efca53ef9693232a9ae6ffbf1f3a4596028ad444ed539d96fe1afb407cfb5';CURRENT='ba6399c629e6c8876125a339cc80e0a03974080449cf156438c9fe6c346901f3';RETAINED=['landsd/254491:0','landsd/255439:0','landsd/255647:0','landsd/256112:0','landsd/256114:0','landsd/255438:0']
P=B/'government-xl-parkview-block17-fresh-current-physical-capture-v1-20261011';C=B/'government-xl-parkview-block17-fresh-current-carrier-capture-v1-20261011';FINITE=B/'government-xl-parkview-block17-current-four-stream-source-proofs-v1-20261011';REBIND=B/'government-xl-parkview-block17-fresh-current-bounded-route-binding-v1-20261011';GRAPH=B/'government-xl-parkview-block17-complete-original-support-graph-v1-20261011';OPEN=B/'government-xl-parkview-block17-original-lower-opening-association-v3-20261011';ROUTE=B/'government-xl-parkview-block17-bounded-eligible-native-route-v1-20261011';CAP=B/'government-xl-parkview-next-three-original-cap-contacts-v1-20261011';STRICTCAP=B/'government-xl-parkview-next-three-exact-cap-refinement-v1-20261011'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def normal(v):return json.loads(json.dumps(v))
def module(name,p):
 s=importlib.util.spec_from_file_location(name,p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def fenced(doc,verify_current=False):
 receipt=read(doc/'result.json')
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(receipt['jobId'],)).fetchone()==('complete',receipt)
 if verify_current:
  for r in receipt['evidenceRefs']:assert ref(ROOT/r['path'])==r
 return receipt
def capture(doc):
 row=read(doc/'selection.json.gz')['rows'][0];asset=ROOT/row['candidate']['path'];assert digest(asset.read_bytes())==row['sourceSHA256']==row['candidate']['entry']['sha256'];a=read(doc/'actual-render-geometry.json.gz');assert a['startEndAllInputsVerified']and a['completeRecursiveProductionModuleClosure'];a=a['row'];assert a['uid']==row['uid']and a['sourceSHA256']==row['sourceSHA256'];rt=read(HERE/'local'/doc.name/'runtime-geometry.json.gz')['rows'][0];assert rt['uid']==row['uid']and rt['index']==a['completeOriginalIndex'];assert np.array_equal(np.asarray(rt['position']),np.asarray(a['completeLiteralWorldPosition']));idx=np.asarray(a['completeOriginalIndex']).reshape(-1,3);worlds=[decode_original_world_triangles(asset.read_bytes())]+[np.asarray(a[k]).reshape(-1,3)[idx]for k in ['completeLiteralWorldPosition','completeExplicitLeftAssociatedFloat32WorldPosition','completeExplicitBalancedFloat32WorldPosition']];ground=np.asarray(rt['drawnGroundGeometry'],float).reshape(-1,3,3);return row,a,worlds,ground

def recheck():
 manifest=ROOT/'3d-viewer/city/data/manifest.json';start=ref(manifest);assert start['sha256']==CURRENT;current=read(manifest);refs=[ref(Path(__file__)),start]
 for d in [P,C,FINITE,REBIND]:
  receipt=fenced(d,True);refs.append(ref(d/'result.json'));refs.extend(receipt['evidenceRefs'])
 for d in [GRAPH,OPEN,ROUTE,CAP,STRICTCAP]:fenced(d);refs.append(ref(d/'result.json'))
 row,a,worlds,ground=capture(P);cr,ca,natives,nground=capture(C);assert row['uid']==UID and cr['uid']==NATIVE and row['sourceSHA256']==SOURCE;assert ground.shape==(195,3,3)and nground.shape==(25167,3,3);assert all(w.shape==(15614,3,3)and np.isfinite(w).all()for w in worlds);assert all(w.shape==(63133,3,3)and np.isfinite(w).all()for w in natives)
 g=read(GRAPH/'diagnostic.json.gz');parts=g['completeSourceEdgeBodyFaces'];parents={int(k):v for k,v in g['completeConditionalParents'].items()};visual=g['unreachedBodies'];assert len(parts)==93 and len(parents)==92 and visual==[62]and g['completeOriginalDegenerateFaces']==[24,25]and parents[0]is None;hostfaces=sorted(f for i in parents for f in parts[i]);assert len(hostfaces)==15602;assert sorted(f for fs in parts for f in fs)==[f for f in range(15614)if f not in [24,25]];assert not set(visual)&set(parents)
 finite=read(FINITE/'diagnostic.json.gz');rb=read(REBIND/'diagnostic.json.gz');route=read(ROUTE/'diagnostic.json.gz');capdoc=read(CAP/'diagnostic.json.gz');cap=next(x for x in capdoc['rows']if x['uid']==UID);strict=next(x for x in read(STRICTCAP/'diagnostic.json.gz')['rows']if x['uid']==UID);capproof=strict['priorProof'];assert cap['nativeOriginalCapFace']==strict['cap']==54418 and strict['wholeFiniteCapStrictClear']and strict['existingStrictCapProofReused'];assert F(capproof['exactCertifiedLowerClearanceM'])>0 and capproof['groundProjectionCovered'];assert capproof['sourceFaceSHA256']==digest(natives[0][54418].tobytes());assert route['boundedOriginalPathProved']and route['qualifiedGenuineGradeFace']==51646;path=route['qualifiedOriginalPathToStrictCap'];assert path==[51646,49682,54417,54418];assert 54320 not in path and [52248,52249]not in [path[i:i+2]for i in range(len(path)-1)]
 assert digest(nground.tobytes())==route['completePinnedGroundSHA256']==capdoc['completeFrozenGroundSHA256']==capproof['completeCurrentGroundSHA256'];grade=next(p for p in route['allExaminedFaceProofs']if p['face']==51646);assert grade['eligible']and grade['genuineGrade']and grade['exactPositiveUpperGroundInterfaces']and F(grade['completeGradeVertexExposure']['exactExposureLowerBoundM'])>0
 for f in path[1:-1]:
  p=next(p for p in route['allExaminedFaceProofs']if p['face']==f);assert p['eligible']and p['strictClear']and F(p['exactLowerM'])>0
 for f,h in zip(path,path[1:]):
  p=next(p for p in route['allExaminedWholeSharedEdgeProofs']if set(p['faces'])=={f,h});assert p['eligible']and p['completeGroundSHA256']==digest(nground.tobytes());q=p['originalSubsetProof'];assert q['strictlyExposedWholePositiveInterface']and q['closedWholeSegmentProjectionCovered']and F(q['exactMinimumGapM'])>0
 modes=['providerOriginal','actualLiteral','explicitLeftAssociatedF32ModelMatrix','explicitBalancedF32ModelMatrix'];roles=[]
 for mode,t,nt in zip(modes,worlds,natives):
  th=digest(t.tobytes());nh=digest(nt.tobytes());assert th==cap['completeOriginalWorldSHA256']and nh==route['completeOriginalNativeWorldSHA256'];fr=next(p for p in finite['rows']if p['mode']==mode);rbr=next(p for p in rb['rows']if p['mode']==mode);assert fr['completeWorldSHA256']==rbr['completeOwnedWorldSHA256']==th and rbr['completeCarrierWorldSHA256']==nh;assert fr['completeGroundSHA256']==digest(ground.tobytes());assert not fr['unprovedWholeFacetIDs']and len(fr['all15614WholeFacetFiniteProofs'])==15614
  for i,p in enumerate(fr['all15614WholeFacetFiniteProofs']):
   q=p['proof'];assert p['sourceFace']==i and q['sourceFaceSHA256']==digest(t[i].tobytes())and q['completeCurrentGroundSHA256']==digest(ground.tobytes())and q['groundProjectionCovered']and q['existingOrdinaryClearanceBoundProved']and F(q['exactCertifiedLowerClearanceM'])>=F(-1,2)
  completecensus=census(t,list(range(15614)));assert completecensus['exactNonrenderingOriginalFaces']==[24,25]and normal(completecensus['sharedEdgeConnectedComponents'])==parts
  same=next((p for p in roles if p['completeOwnedWorldSHA256']==th and p['completeNativeWorldSHA256']==nh),None)
  if same:roles.append({**same,'mode':mode,'identicalCompleteSourceAndNativeAndGroundProofsReusedFrom':same['mode']});continue
  bodies=[]
  for i,fs in enumerate(parts):
   proof=census(t,fs);assert len(proof['sharedEdgeConnectedComponents'])==1 and not proof['exactNonrenderingOriginalFaces'];assert normal(proof)==next(p['proof']for p in fr['complete93OriginalBodyEdgeCensuses']if p['originalBody']==i);bodies.append(dict(originalBody=i,proof=proof))
  contacts=[];adj={i:set()for i in parents}
  for witness in fr['original92BodyPositiveContactPaths']:
   f,h=witness['originalFaces'];x,y=witness['bodies'];assert x in parents and y in parents;assert f in parts[x]and h in parts[y]or f in parts[y]and h in parts[x];points=finite_intersection_points(rational_face(t[f]),rational_face(t[h]));measure=contact_measure(points);assert measure['dimension']>0 and normal(measure)=={k:witness[k]for k in measure};adj[x].add(y);adj[y].add(x);contacts.append(witness)
  assert len(contacts)==91;proved={0:None};todo=collections.deque([0])
  while todo:
   i=todo.popleft()
   for j in sorted(adj[i]):
    if j not in proved:proved[j]=i;todo.append(j)
  assert set(proved)==set(parents)
  completecap=exact_finite_contacts(nt,[54418],t,list(range(15614)));assert normal(completecap)==cap['completeOwnedToOneOriginalCapContacts']and completecap['allPairsExamined']and not completecap['sourceFacesOmitted'];capcontacts=completecap['contacts'];positive=[p for p in capcontacts if p['dimension']>0];assert len(positive)==6 and cap['directlyContactingOwnedNonzeroEdgeBodies']==[0]
  for w in positive:
   f,h=w['sourceFaceA'],w['sourceFaceB'];assert f==54418 and h in parts[0];m=contact_measure(finite_intersection_points(rational_face(nt[f]),rational_face(t[h])));assert m['dimension']>0 and m['exactPoints']==w['exactPoints']
  openings=[]
  for i in visual:
   proof=normal(opening_verify(t,parts[i],hostfaces,expected_binding=binding(t,parts[i],hostfaces)));saved=next(p['proof']for p in fr['completeOneOpeningProof']if p['originalBody']==i);assert proof==saved and proof['completeLowerOpeningAssociated']and not proof['structuralRootCredit']and not proof['structuralBridgeCredit']and not proof['closedSolidCertified'];openings.append(dict(originalBody=i,proof=proof))
  roles.append(dict(mode=mode,completeOwnedWorldSHA256=th,completeNativeWorldSHA256=nh,completeOwnedCurrentGroundSHA256=digest(ground.tobytes()),completeCarrierCurrentGroundSHA256=digest(nground.tobytes()),completeOriginal93BodyEdgeCensuses=bodies,completeStructuralOwnedParents=proved,all91PositiveOriginalContactWitnesses=contacts,all6PositiveOriginalCapContacts=positive,completeOwnedToOneCapContactsIncludingUncreditedPoints=completecap,qualifiedNativeFacePath=path,allOtherNativeFacesUncredited=True,visualOnlyOriginalRoofBodies=openings,complete15614FacePartitionAccounted=True,originalZeroAreaFacetsPreserved=[24,25],originalZeroAreaFacetCoordinates=t[[24,25]].tolist(),zeroAreaRootBridgeBandCredit=False,all15614OrdinaryFinitePredicateVerified=True,minimumConservativeWholeOwnedBoundM=str(min(F(p['proof']['exactCertifiedLowerClearanceM'])for p in fr['all15614WholeFacetFiniteProofs'])),wholeOwnedStrictPositiveClearanceClaimed=False))
 identity=read(P/'identity-proofs.json')['rows'][0];assert identity['passed']and identity['worldTrianglesSHA256']==digest(worlds[0].tobytes());assert identity['proof']['exactObjectId']and identity['proof']['exactBuildingCSUID']and identity['proof']['uniqueViewerMatch']and identity['exactWholeCellCoverage']['covered'];assert identity['freshCurrentIdentity']['unrelatedIntersectingForms']==0;assert read(P/'source-preflight.json')['completeCurrentForeignFormScope']==23;neighbourinputs=read(P/'neighbour-inputs.json.gz');neighbours=read(P/'neighbour-checks.json');assert len(neighbourinputs['rows'])==len(neighbours['rows'])==23 and not any(p['reasons']for p in neighbours['rows']);assert read(P/'terrain-candidates.json')==neighbourinputs['patches']==[]
 foundation=read(P/'foundation.json')['rows'][0];assert foundation['strictFoundationAccepted']and foundation['foundation']['triangles']==foundation['foundation']['completeTerrainTriangles']==15614 and not foundation['foundation']['fullyBuriedUpwardTriangles']and not foundation['foundation']['fullyBuriedTriangles']and foundation['foundation']['fullyBuriedAreaFraction']==0
 nativechecks=read(P/'native-neighbour-checks.json');assert set(nativechecks['blocked'])==set(nativechecks['resolved'])==set(RETAINED)and len(nativechecks['rows'])==6;assert all(p['passed']and p['terrain']['newlyWhollyBuried']==p['terrain']['newlyUpwardWhollyBuried']==0 for p in nativechecks['rows'])
 metric=read(P/'metrics.json')['rows'][0];assert metric['uid']==UID and metric['sourcePreserved']and metric['sourceSHA256']==SOURCE and metric['maxSamplerDelta']<=.004 and not metric['missingTerrain']and metric['missingDrawnTerrain']['count']==metric['samplerDisagreement']['count']==0;validation=read(P/'validation.json');assert all(type(validation[k])is int for k in ['models','loaderAccepted','checksPassed','exceptions']);assert validation['models']==validation['loaderAccepted']==validation['checksPassed']==1 and validation['exceptions']==0 and len(validation['results'])==1 and validation['results'][0]['uid']==UID and validation['results'][0]['triangles']==15614 and validation['results'][0]['outcome']=='runtime-accepted-placement-unreviewed'
 raw=read(P/'current-raw-outcome.json');assert raw['reasons']==['ground-contact-unresolved','sampled-ground-gap-below-model-bottom'];policy=module('block17_current_role_policy',HERE/'acceptance-policy.py');found=policy.reasons(dict(state='runtime-validated-awaiting-acceptance',sourceSHA256=SOURCE,identityProof=identity['proof']),metric,read(P/'metrics.json')['profiles']['mobile']);assert found==['ground-contact-unresolved'];assert read(P/'diagnostic-resolutions.json')['rows'][0]['remaining']==['sampled-ground-gap-below-model-bottom']
 entries={};catrefs=[];retainedassets={}
 for url in current['officialModelCatalogues']:
  cp=ROOT/'3d-viewer'/url;catrefs.append(ref(cp))
  for e in read(cp)['models']:
   assert e['uid']not in entries;entries[e['uid']]=e
   if e['uid']in RETAINED:
    asset=cp.parent/e['asset'];assert digest(asset.read_bytes())==e['sha256'];retainedassets[e['uid']]=ref(asset)
 assert UID not in entries and set(retainedassets)==set(RETAINED);nativeentry=entries[NATIVE];assert nativeentry['sha256']==cr['sourceSHA256'];refs+=catrefs+list(retainedassets.values());nativeentries={u:entries[u]for u in RETAINED};positions=[np.asarray(a[k],float).reshape(-1,3)for k in ['completeLiteralWorldPosition','completeExplicitLeftAssociatedFloat32WorldPosition','completeExplicitBalancedFloat32WorldPosition']];protected=[[float(min(p[:,i].min()for p in positions))for i in range(3)],[float(max(p[:,i].max()for p in positions))for i in range(3)]]
 refs=list({(r['path'],r['sha256']):r for r in refs}.values())
 for r in refs:assert ref(ROOT/r['path'])==r
 assert ref(manifest)==start
 return dict(uids=[UID],currentManifest=start,sourceSHA256=SOURCE,completeOriginalFaces=15614,completeOriginalComponents=93,completeOriginalNonzeroFacets=15612,completeOriginalZeroAreaFacets=[24,25],zeroAreaSourceFacetsRetainedWithoutRootBridgeBandCredit=True,completeCurrentNeighbourForms=23,independentlySupportedStructuralOwnedComponents=92,visualOnlyOwnedComponents=visual,roles=roles,currentOwnedIdentities=[identity],completeCurrentInstalledNativeEntriesPreserved=nativeentries,completeCurrentInstalledNativeAssetRefsPreserved=retainedassets,completeOwnedWholePOSITIONLiteralExplicitF32ProtectedBounds=dict(union=protected),mandatoryInstalledNativeSupport=dict(uid=NATIVE,sourceSHA256=nativeentry['sha256'],installedVerified=False,currentNativeAvailabilityVerified=True,wholeNativeReaccepted=False,qualifiedNativeFacePath=path),rawReasonsPreserved=raw['reasons'],historicalHeldReasonsPreserved=read(P/'source-preflight.json')['historicalHeldReasonsPreserved'],historicalNeighbour256120FailureWaived=False,currentNoTerrainChangeForeignScopeIsDistinct=True,narrowlyReconciledReasons=dict(groundContact='92 genuine original contact bodies reach independently qualified current native grade-wall/whole-exposed-edge/strict-clear-cap through positive-dimensional original contacts; body62 complete original lower opening associates visually only, two original zero-area facets remain uncredited',sampledGroundGap='direct terrain gap is preserved; complete original grounded source contact path supplies the candidate support route'),sourceVisualRoleLimits='body62 complete original lower-opening association and original source roof context only; no equipment function, solid, root or bridge',wholeOwnedClearancePredicate='existing ordinary >=-0.5m, not strict-positive',currentTypedPhysicalAccepted=True,scriptChecksPassed=True,reasons=[],terrainProposal=[],terrainProposalGeometryChanged=False,nativeReacceptance=False,namedRoofUnitRootOrBridgeCredit=False,publication=False,newlyInstalled=0,installationApproved=False,aiGeometryModelling=False,scriptExternalAICalls=0,explicitArithmeticNotUniversalGPUCameraGuarantee=True,stagedBrowserAndPublisherMandatory=True,evidenceRefs=refs)
def main():
 assert not DOC.exists();role=recheck();save(DOC/'typed-role.json.gz',role);save(DOC/'REVIEW.json',dict(currentTypedPhysicalAccepted=True,nonpublishing=True,rawReasonsPreserved=role['rawReasonsPreserved'],stagedBrowserAndPublisherMandatory=True));paths=[ROOT/p['path']for p in role['evidenceRefs']]+[DOC/'typed-role.json.gz',DOC/'REVIEW.json',HERE/'complete_original_lower_opening_mounts_v3_20261011.py',HERE/'test_complete_original_lower_opening_mounts_v3_20261011.py'];f=module('block17_typed_role_freezer',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');f.freeze(BATCH,'complete-current-typed-original-source-role-v1',paths,dict(uids=role['uids'],currentTypedPhysicalAccepted=True,scriptChecksPassed=True,reasons=[],rawReasonsPreserved=role['rawReasonsPreserved'],currentAcceptance=False,scriptFullAcceptancePassed=False,stagedBrowserAndPublisherMandatory=True))
if __name__=='__main__':main()
