"""Pin actual untouched source/provider and six visual roles; no installation."""
import importlib.util,json,uuid
from pathlib import Path
import numpy as np
from run import ROOT,HERE,read,save,digest,connect,reservations
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from xl_source_stream_binding_20261009 import source_stream_binding
from glorious_peak_original_mounted_detail_roles_v2_20261010 import verify,SOURCES,SPECS,canonical
BASE=ROOT/'docs/astra-city/government-import';PHYSICAL=BASE/'government-xl-terrain-recovery-glorious-peak-original-pair-current-physical-v2-20261010';SUPPORT=BASE/'xl-terrain-recovery-20261010-glorious-peak-wall-grade-source-v1';MOUNTS=BASE/'xl-terrain-recovery-20261010-glorious-peak-finite-original-mounts-v1';BATCH='xl-terrain-recovery-20261010-glorious-peak-provider-mounted-roles-v1';DOC=BASE/BATCH
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not DOC.exists();rows=read(PHYSICAL/'selection.json.gz')['rows'];assert {r['uid']:r['sourceSHA256'] for r in rows}==SOURCES
 for d in [PHYSICAL,SUPPORT,MOUNTS]:
  r=read(d/'result.json')
  with connect() as c:c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(r['jobId'],)).fetchone()==('complete',r)
 geometry=read(HERE/'local'/PHYSICAL.name/'runtime-geometry.json.gz');streams={};assets=[];pieces=[];worlds=[];grounds=[];contexts=[];ctxpaths=[]
 for r,g in zip(rows,geometry['rows']):
  assert r['uid']==g['uid'];p=ROOT/r['candidate']['path'];raw=p.read_bytes();assert digest(raw)==SOURCES[r['uid']];assets.append(p);streams[r['uid']]=source_stream_binding(raw);tri=decode_original_world_triangles(raw);world=np.asarray(g['position']).reshape(-1,3)[np.asarray(g['index']).reshape(-1,3)];assert tri.shape==world.shape and np.max(np.abs(tri-world))<=1e-9;pieces.append(tri);worlds.append(world);grounds.append(np.asarray(g['drawnGroundGeometry']).reshape(-1,9));uid=r['uid'].split('/')[1].split(':')[0];cp=BASE/f'xl-terrain-recovery-20261010-glorious-peak-{uid}-complete-context-v1'/'diagnostic.json.gz';ctxpaths.append(cp);d=read(cp);assert d['sourceSHA256']==r['sourceSHA256'] and len(d['faces'])==len(tri);offset=len(contexts);contexts.extend({**c,'sourceFace':offset+i} for i,c in enumerate(d['faces']))
 tri=np.concatenate(pieces);world=np.concatenate(worlds);ground=np.unique(np.concatenate(grounds),axis=0).reshape(-1,3,3);graph=read(SUPPORT/'diagnostic.json.gz');assert digest(tri.tobytes())==graph['binding']['completeOriginalWorldTrianglesSHA256'];assert sorted(graph['unresolvedOriginalComponents'])==list(SPECS)
 role=dict(contract='glorious-peak-six-complete-original-visual-details-v1',sources=SOURCES,providerRootAndStreams=streams,providerRootAndStreamsSHA256=canonical(streams),completeOriginalWorldTrianglesSHA256=digest(tri.tobytes()),completeIndexedOriginalGraph=ref(SUPPORT/'diagnostic.json.gz'),allNamedOriginalVisualComponents=[dict(component=k,actorUID=graph['components'][k]['actorUID'],allOriginalFaces=v['faces'],alreadyRootedHostComponent=v['host'],role=v['role'],completeOriginalVerticesSHA256=digest(tri[v['faces']].tobytes())) for k,v in SPECS.items()],qualification='Actual complete original source/provider pin. Every mount is recomputed across full finite original edge using existing contact band; no root, support bridge, closed solid, cap or installation credit.')
 oldmanifest=read(PHYSICAL/'selection.json.gz')['manifestSHA256'];foreign=dict(frozenPhysicalForeignInput=ref(PHYSICAL/'neighbour-inputs.json.gz'),frozenNativePhysical=ref(PHYSICAL/'native-neighbour-checks.json'),freshCurrentAcceptance=False)
 binding=dict(completeOriginalWorldTrianglesSHA256=digest(tri.tobytes()),completeActualRenderedWorldSHA256=digest(world.tobytes()),completeCurrentDrawnGroundSHA256=digest(ground.tobytes()),completeContinuousContextsSHA256=canonical(contexts),completeRootedOriginalGraphSHA256=canonical(graph),frozenProviderRoleSHA256=canonical(role),actualProviderRootAndStreamsSHA256=canonical(streams),completeCurrentPhysicalSHA256=digest((PHYSICAL/'result.json').read_bytes()),completeCurrentForeignScopeSHA256=canonical(foreign),currentManifestSHA256=oldmanifest)
 claim=reservations.claim('glorious-provider-mounted-'+str(uuid.uuid4()),['immutable-source-proof:'+BATCH],batch=BATCH,ttl=3600);assert claim['ok'];lease=claim['reservation']
 try:
  typed=verify(tri,contexts,graph,ground,world,expected_role=role,expected_binding=binding,current_binding=binding);save(DOC/'expected-role.json',role);save(DOC/'original-source-provenance.json',dict(sources=SOURCES,providerRootAndStreams=streams,originalSourceRootsAndAllIndexedStreamsUnchanged=True,sourceEvidenceInterpretationUsedAI=True,aiGeometryModelling=False));save(DOC/'typed-source-only-visual-roles.json.gz',typed)
  refs=[ref(q) for q in [Path(__file__),PHYSICAL/'result.json',SUPPORT/'result.json',SUPPORT/'diagnostic.json.gz',MOUNTS/'result.json',MOUNTS/'diagnostic.json.gz',HERE/'local'/PHYSICAL.name/'runtime-geometry.json.gz',HERE/'glorious_peak_original_mounted_detail_roles_v2_20261010.py',HERE/'test_glorious_peak_original_mounted_detail_roles_v3_20261010.py',HERE/'exact_original_segment_surface_contact_band_20261009.py',HERE/'exact_original_face_conservative_clearance_v4_20261010.py',HERE/'exact_original_closed_projection_intersection_20261010.py',HERE/'exact_shell_context_accelerated_20261009.py',HERE/'xl_source_stream_binding_20261009.py',*ctxpaths,*assets]]
  spec=importlib.util.spec_from_file_location('glorious_provider_freeze',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);m.freeze(BATCH,'source-bound-six-original-mounted-visual-detail-roles-v1',[ROOT/r['path'] for r in refs],dict(uids=list(SOURCES),completeOriginalFaces=len(tri),completeOriginalComponents=len(graph['components']),allSourceComponentsAccounted=typed['allComponentsAccounted'],structuralOriginalComponents=len(graph['resolvedOriginalComponents']),visualOriginalComponents=list(SPECS),sourceGeometryChanges=0,visualStructuralBridgeCredit=False,visualGroundRootCredit=False,currentAcceptancePassed=False,installationApproved=False,qualification='Only frozen source-bound visual roles/whole-facet clearance pass. Fresh complete current identity/foreign/ordinary/runtime/staged/live proof remains mandatory before installation.'));print(json.dumps(dict(allSourceComponentsAccounted=True,currentAcceptancePassed=False,sourceGeometryChanges=0)),flush=True)
 finally:assert reservations.release(lease)['ok']
if __name__=='__main__':main()
