"""Declare current source/rebind closure; root verifies all numerical bindings."""
from pathlib import Path
from run import ROOT,HERE,read,save,digest
BASE=ROOT/'docs/astra-city/government-import';DOC=BASE/'xl-terrain-recovery-20261010-park-hkdi-current-source-scope-v1'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not DOC.exists();paths=set();leaves=set();aliases=[];pointers=[]
 for name in ['xl-terrain-recovery-20261010-park-haven-source-scope-declaration-v3','xl-terrain-recovery-20261010-hkdi-block-b-source-scope-declaration-v3']:
  old=read(BASE/name/'declared-scope.json');paths.update(old['closedPaths']);aliases.extend(old['historicalManifestAliases']);leaves.update(old['metadataLeafPaths']);pointers.extend(old.get('metadataLeafJsonPointers',[]));paths.add(str((BASE/name/'declared-scope.json').relative_to(ROOT)))
 names=['xl-terrain-recovery-20261010-current-original-literal-actor-bounds-proof-v3','xl-terrain-recovery-20261010-complete-current-native-position-inventory-v1','xl-terrain-recovery-20261010-complete-current-native-position-inventory-v2','xl-terrain-recovery-20261010-park-haven-post-atomic-disjoint-rebind-v2','xl-terrain-recovery-20261010-park-haven-post-atomic-disjoint-rebind-v3','xl-terrain-recovery-20261010-hkdi-block-b-post-atomic-disjoint-rebind-v1','xl-terrain-recovery-20261010-hkdi-block-b-post-atomic-disjoint-rebind-v2','xl-terrain-recovery-20261010-hkdi-block-b-post-atomic-disjoint-rebind-v3','government-xl-terrain-recovery-park-haven-post-atomic-complete-current-role-v2-20261010','government-xl-terrain-recovery-hkdi-block-b-post-atomic-complete-current-role-v2-20261010','government-xl-terrain-recovery-park-haven-final-native-validation-v2-20261010']
 for name in names:
  folder=BASE/name;assert folder.is_dir();paths.update(str(p.relative_to(ROOT))for p in folder.rglob('*')if p.is_file())
 scripts=['xl-terrain-recovery-20261010-current-original-literal-actor-bounds-readonly-v3.mjs','xl-terrain-recovery-20261010-current-original-literal-actor-bounds-proof-checkpoint-v3.py','literal_production_module_dependency_closure_20261010.mjs','test_literal_production_module_dependency_closure_20261010.mjs','original_literal_complete_actor_bounds_20261010.mjs','test_original_literal_complete_actor_bounds_20261010.mjs','exact_packed_world_bounds_v2_20261010.py','test_exact_packed_world_bounds_v2_20261010.py','exact_packed_world_bounds_v3_20261010.py','test_exact_packed_world_bounds_v3_20261010.py','xl-terrain-recovery-20261010-complete-current-native-position-inventory-v1.py','xl-terrain-recovery-20261010-complete-current-native-position-inventory-v2.py','xl-terrain-recovery-20261010-coupled-disjoint-current-rebind-v6.py','xl-terrain-recovery-20261010-coupled-disjoint-current-rebind-v7.py','xl-terrain-recovery-20261010-coupled-disjoint-current-rebind-v8.py','xl-terrain-recovery-20261010-park-haven-post-atomic-disjoint-rebind-v2.py','original_literal_rebound_role_accounting_20261010.py','test_original_literal_rebound_role_accounting_20261010.py','complete_disjoint_source_role_replay_v2_20261010.py','xl-terrain-recovery-20261010-park-haven-post-atomic-complete-current-role-v2.py','xl-terrain-recovery-20261010-hkdi-block-b-post-atomic-complete-current-role-v2.py','xl-terrain-recovery-20261010-park-haven-final-native-validation-v2.py']
 paths.update(str((HERE/f).relative_to(ROOT))for f in scripts);paths.add(str(Path(__file__).relative_to(ROOT)))
 manifest=ROOT/'3d-viewer/city/data/manifest.json';raw=manifest.read_bytes();assert digest(raw)=='afe71ffa851d82ab2d1350834b5a6cd1484f28e481bd6bf866ca7a6f73e05d0b';DOC.mkdir();archive=DOC/'historical-current-manifest.json';archive.write_bytes(raw);paths.add(str(archive.relative_to(ROOT)));leaves.add(str(archive.relative_to(ROOT)));aliases.append(dict(originalPath='3d-viewer/city/data/manifest.json',sha256=digest(raw),archive=ref(archive)))
 current=read(manifest);leaves.update('3d-viewer/'+url for url in current['officialModelCatalogues']);leaves.update('3d-viewer/'+p['url']for p in current['terrainPatches'])
 for name in ['xl-terrain-recovery-20261010-park-haven-post-atomic-disjoint-rebind-v3','xl-terrain-recovery-20261010-hkdi-block-b-post-atomic-disjoint-rebind-v3']:
  p=BASE/name/'historical-manifest.json';aliases.append(dict(originalPath='3d-viewer/city/data/manifest.json',sha256=ref(p)['sha256'],archive=ref(p)));leaves.add(str(p.relative_to(ROOT)))
 unique={(a['originalPath'],a['sha256'],a['archive']['path']):a for a in aliases};save(DOC/'declared-scope.json',dict(closedPaths=sorted(paths),closedExplicitPaths=sorted(paths),presentFileBindings=[ref(ROOT/p)for p in sorted(paths)],historicalManifestAliases=list(unique.values()),metadataLeafPaths=sorted(leaves),metadataLeafJsonPointers=pointers,sourceGeometryChanges=0,newMetadataPointerContract=False,fullNumericalSourceClosureRequired=True,stageAndLiveExcluded=True,qualification='Both current roles preserve fenced complete original/literal numerical physical roles and all raw failures. Full regional disjoint proofs include every original POSITION including unused, current literal and castF32 whole bounds for owned/retained/changed actors. Global6631native assets independently source-decoded with separate face bounds and all hierarchy transforms. Existing reviewed global catalogue/terrain metadata leaves inherited; no ownedsource/ground/kernel/currentrole/positioninventory numerical leaf added. Root unchanged verifier must close every exact numerical binding before publication.'))
 print(dict(paths=len(paths),currentManifestSHA256=digest(raw)),flush=True)
if __name__=='__main__':main()
