"""Close unchanged Man Oi numeric source proof with typed archival pointers."""
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
from original_complete_role_routing_metadata_scope_20261010 import role_boundaries,verify_role_boundaries
BASE=ROOT/'docs/astra-city/government-import';OUT=BASE/'xl-terrain-recovery-20261010-man-oi-current-source-closed-scope-v1'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not OUT.exists();dirs=[BASE/n for n in ['xl-terrain-recovery-20261010-man-oi-current-complete-support-v1','xl-terrain-recovery-20261010-man-oi-current-complete-support-v2','xl-terrain-recovery-20261010-man-oi-plain-stage-config-v1','government-xl-man-oi-complete-original-physical-20261010','government-xl-man-oi-complete-original-physical-v2-20261010','government-xl-man-oi-current-original-preflight-20261010','government-xl-man-oi-current-original-preflight-v2-20261010']]
 paths={str(p.relative_to(ROOT)) for d in dirs for p in d.rglob('*') if p.is_file()};assert all(d.exists() for d in dirs)
 for n in ['xl-terrain-recovery-20261010-man-oi-current-complete-support-v1.py','xl-terrain-recovery-20261010-man-oi-current-complete-support-v2.py','xl-terrain-recovery-20261010-man-oi-plain-stage-config-v1.py','original_complete_role_routing_metadata_scope_20261010.py','test_original_complete_role_routing_metadata_scope_20261010.py','original_disjoint_routing_metadata_scope_20261010.py','test_original_disjoint_routing_metadata_scope_20261010.py']:paths.add(str((HERE/n).relative_to(ROOT)))
 paths.add(str(Path(__file__).relative_to(ROOT)));aliases=[];pointers=[];leaf=set(read(BASE/'xl-terrain-recovery-20261010-green18-stage-live-closure-v3/closed-scope.json')['metadataLeafPaths'])
 for version in [1,2]:
  d=BASE/f'xl-terrain-recovery-20261010-man-oi-current-complete-support-v{version}';receipt=read(d/'result.json');role_path=d/'typed-role.json.gz';role=read(role_path)
  with connect() as c:c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(receipt['jobId'],)).fetchone()==('complete',receipt)
  wanted=role['manifestSHA256'];possibles=[ROOT/'3d-viewer/city/data/manifest.json',BASE/'xl-terrain-recovery-20261010-green18-current-source-closed-scope-v1/acceptance-manifest.json',HERE/'local/government-xl-man-oi-plain-installed-v1-20261010/manifest-before-installation.json'];raw=next(p.read_bytes() for p in possibles if p.is_file() and digest(p.read_bytes())==wanted);archive=OUT/f'acceptance-manifest-v{version}.json';archive.parent.mkdir(parents=True,exist_ok=True);archive.write_bytes(raw);paths.add(str(archive.relative_to(ROOT)));alias=dict(originalPath='3d-viewer/city/data/manifest.json',sha256=wanted,archive=ref(archive));aliases.append(alias);manifest=read(archive);manifest_ref=dict(path=alias['originalPath'],sha256=wanted)
  candidate_ref=next(r for r in role['evidenceRefs'] if r['path'].endswith('/terrain-candidates.json'));candidate_path=ROOT/candidate_ref['path'];assert ref(candidate_path)==candidate_ref;candidate=read(candidate_path);kwargs=dict(candidate_ref=candidate_ref,manifest_ref=manifest_ref,expected_uids=['landsd/75697:0']);declared=role_boundaries(role,manifest,candidate,**kwargs);verify_role_boundaries(role,manifest,candidate,declared,**kwargs)
  pointers.extend(dict(path=str(role_path.relative_to(ROOT)),documentSHA256=digest(role_path.read_bytes()),boundary=row) for row in declared)
  leaf.add(str(archive.relative_to(ROOT)));leaf.update('3d-viewer/'+u for u in manifest['officialModelCatalogues']);leaf.update('3d-viewer/'+p['url'] for p in manifest['terrainPatches'])
 final=read(dirs[1]/'result.json');save(OUT/'closed-scope.json',dict(closedPaths=sorted(paths),closedExplicitPaths=sorted(paths),presentFileBindings=[ref(ROOT/p) for p in sorted(paths)],historicalManifestAliases=aliases,metadataLeafPaths=sorted(leaf),metadataLeafJsonPointers=pointers,currentRoleNeon=final['jobId'],sourceGeometryChanges=0,installationApproved=False,stageAndLiveExcluded=True,qualification='Complete unchanged2160-source-face/4component/13currentactor numeric proof and source identity/provider/terrain/runtime dependencies remain fully recursive. Only typed archived original manifest entry/source acquisition provenance has canonical per-document pointers; actual disjoint current routing assets, whole measured bounds and own native TIN/source/ground are still mandatory. Stage/live installation evidence closes separately.'))
 print(dict(paths=len(paths),metadataPointers=len(pointers),currentRoleNeon=final['jobId']),flush=True)
if __name__=='__main__':main()
