"""Full certified original/runtime facets, exposed crossing-wall paths, no installation credit."""
import importlib.util,json,numpy as np
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from original_bound_facet_wall_context_v2_20261010 import contexts,canonical
from original_strict_clear_cap_wall_paths_20261009 import verify as paths
BASE=ROOT/'docs/astra-city/government-import';BATCH='government-xl-tung-sing-three-original-current-certified-wall-paths-v1-20261010';DOC=BASE/BATCH;PHYSICAL=BASE/'government-xl-tung-sing-three-original-literal-parent-physical-v2-20261010';FINITE=BASE/'government-xl-tung-sing-three-original-complete-paired-finite-clearance-v1-20261010';GRAPH=BASE/'government-xl-tung-sing-three-original-current-root-graph-v3-20261010';RUNTIME=HERE/'local'/PHYSICAL.name/'runtime-geometry.json.gz'
def main():
 assert not DOC.exists();manifest=ROOT/'3d-viewer/city/data/manifest.json';selection=read(PHYSICAL/'selection.json.gz');assert digest(manifest.read_bytes())==selection['manifestSHA256'];finite=read(FINITE/'diagnostic.json.gz');graph=read(GRAPH/'diagnostic.json.gz');runtime={r['uid']:r for r in read(RUNTIME)['rows']};refs=[Path(__file__),manifest,PHYSICAL/'result.json',PHYSICAL/'selection.json.gz',RUNTIME,FINITE/'result.json',FINITE/'diagnostic.json.gz',GRAPH/'diagnostic.json.gz',HERE/'original_bound_facet_wall_context_v2_20261010.py',HERE/'original_bound_facet_wall_context_20261010.py',HERE/'original_strict_clear_cap_wall_paths_20261009.py'];out=[]
 for folder in [PHYSICAL,FINITE]:
  receipt=read(folder/'result.json')
  with connect() as c:c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(receipt['jobId'],)).fetchone()==('complete',receipt)
  for ref in receipt['evidenceRefs']:assert digest((ROOT/ref['path']).read_bytes())==ref['sha256']
 for row in selection['rows']:
  uid=row['uid'];asset=ROOT/row['candidate']['path'];raw=asset.read_bytes();assert digest(raw)==row['sourceSHA256'];tri=decode_original_world_triangles(raw);r=runtime[uid];world=np.asarray(r['position']).reshape(-1,3)[np.asarray(r['index']).reshape(-1,3)];ground=np.asarray(r['drawnGroundGeometry']).reshape(-1,3,3);f=next(v for v in finite['rows'] if v['uid']==uid);assert digest(tri.tobytes())==f['completeOriginalWorldSHA256'] and digest(world.tobytes())==f['completeActualRenderedWorldSHA256'] and digest(ground.tobytes())==f['completeGroundSHA256'];actor=next(a for a in graph['completeOriginalActors'] if a['uid']==uid);off=actor['globalFaceRange'][0];source_contacts=[ [i-off for i in c['globalOriginalFaces']] for c in graph['contactWitnesses'] if all(off<=i<off+len(tri) for i in c['globalOriginalFaces'])];rows=[]
  for mode,a in [('completeOriginal',tri),('actualRendered',world)]:
   prepared=[]
   for c in f['allFaces']:
    prepared.append({'sourceFace':c['sourceFace'],'priorCoarseBoundProofVerbatim':{'sourceFace':c['sourceFace'],'completeOriginal':c['priorCoarseBoundProofVerbatim'][mode]},'pairedExactOriginalFiniteBound':c['pairedExactOriginalFiniteBound' if mode=='completeOriginal' else 'pairedExactActualRenderedFiniteBound'],'completeOriginalBoundProved':c['completeOriginalBoundProved' if mode=='completeOriginal' else 'completeActualRenderedBoundProved']})
   cb={'completeOriginalWorldTrianglesSHA256':digest(a.tobytes()),'completeDrawnGroundSHA256':digest(ground.tobytes()),'completeFiniteFacetProofRowsSHA256':canonical(prepared)};ctx=contexts(a,ground,prepared,expected_binding=cb,current_binding=cb);binding={'completeOriginalWorldTrianglesSHA256':digest(a.tobytes()),'completeCurrentFacetContextsSHA256':canonical(ctx),'exactOriginalContactListSHA256':canonical(source_contacts)}
   try:proof=paths(a,ctx,source_contacts,expected_binding=binding,current_binding=binding);error=None
   except AssertionError as e:proof=None;error=str(e)
   rows.append({'representation':mode,'completeCertifiedLowerBoundContexts':ctx,'binding':binding,'completeSourceContactPairs':source_contacts,'strictClearCapWallPaths':proof,'exactPathGuardFailure':error,'allFacetsRemainAccounted':len(ctx)==len(a),'sourceGeometryChanges':0,'physicalAccepted':False})
   print({'uid':uid,'representation':mode,'ordinaryClearFacets':sum(c['minimum']['minimumGapM']>=-.5 for c in ctx),'wallPathPassed':proof and proof['allAffectedHavePaths'],'exposureFailures':proof and proof['rawExposureFailures'],'guard':error},flush=True)
  refs.append(asset);out.append({'uid':uid,'sourceSHA256':row['sourceSHA256'],'completeOriginalFaces':len(tri),'sourceAndLiteralActualProofs':rows})
 save(DOC/'diagnostic.json.gz',{'rows':out,'manifestSHA256':selection['manifestSHA256'],'sourceGeometryChanges':0,'physicalAccepted':False,'installationApproved':False,'qualification':'Every source and literal runtime facet retains exact finite coverage/minimum lower bound. Each affected steep wall must independently expose a real highest vertex and reach a strictly clear authored upward cap through exact source edges/finite contacts. All foreign/body/interface/numeric/runtime/browser checks remain separate.'});assert digest(manifest.read_bytes())==selection['manifestSHA256'];s=importlib.util.spec_from_file_location('wallpath_fence',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.freeze(BATCH,'complete-current-source-rendered-certified-facet-wall-paths-v1',refs,{'uids':[r['uid'] for r in out],'completeOriginalFaces':12751,'sourceGeometryChanges':0,'physicalAccepted':False,'installationApproved':False,'nextStep':'Full current foreign scope plus independently typed original exterior wall and rim/whole numeric/runtime composition.'})
if __name__=='__main__':main()
