"""Render complete untouched original details in their authored local host context."""
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import numpy as np,importlib.util
from pathlib import Path
from run import ROOT,HERE,read,save,digest
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
BATCH='xl-terrain-recovery-20261010-festival-pair-original-four-detail-groups-visual-v1';BASE=ROOT/'docs/astra-city/government-import';DOC=BASE/BATCH
GRAPH=BASE/'xl-terrain-recovery-20261010-festival-complete-original-pair-support-v1';PHYS=BASE/'government-xl-festival-two-originals-full-physical-20261007';DIST=BASE/'xl-terrain-recovery-20261010-festival-pair-original-all-finite-mount-boundaries-v1'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not DOC.exists();g=read(GRAPH/'diagnostic.json.gz');selected=read(PHYS/'selection.json.gz')['rows'];assets=[ROOT/r['candidate']['path'] for r in selected];assert all(digest(p.read_bytes())==r['sourceSHA256'] for p,r in zip(assets,selected));tri=np.concatenate([decode_original_world_triangles(p.read_bytes()) for p in assets]);assert digest(tri.tobytes())==g['binding']['completeOriginalWorldTrianglesSHA256'];roots=g['resolvedOriginalComponents'];rootids=np.array(sorted(i for k in roots for i in g['components'][k]['globalOriginalFaces']));fig=plt.figure(figsize=(18,14.4),dpi=100);rows=[]
 for n,ks in enumerate([[92,*range(201,220)],[176,177,178,179,180,276],[122,*range(130,143)],[258,259,263]]):
  ks=[k for k in ks if k not in roots];k=ks[0];faces=[i for j in ks for i in g['components'][j]['globalOriginalFaces']];piece=tri[faces];lo=piece.min(axis=(0,1));hi=piece.max(axis=(0,1));center=(lo+hi)/2;extent=max(hi-lo)*.8+.3;hosts=rootids[np.all(tri[rootids].max(axis=1)>=lo-1,axis=1)&np.all(tri[rootids].min(axis=1)<=hi+1,axis=1)];ax=fig.add_subplot(2,2,n+1,projection='3d');swap=lambda x:x[:,:,[0,2,1]];ax.add_collection3d(Poly3DCollection(swap(tri[hosts]-center),facecolor='#c4cfdb',edgecolor='#68788a',alpha=.45,linewidth=.3));ax.add_collection3d(Poly3DCollection(swap(piece-center),facecolor='#e76f38',edgecolor='#1a1c20',alpha=1,linewidth=1));ax.set_xlim(-extent,extent);ax.set_ylim(-extent,extent);ax.set_zlim(-extent,extent);ax.set_box_aspect((1,1,1));ax.view_init(elev=20,azim=130);ax.set_xlabel('local X (m)');ax.set_ylabel('local Z (m)');ax.set_zlabel('HKPD offset (m)');ax.set_title(f'Original components {ks}: {len(faces)} faces\nOrange detail; grey independently rooted source');rows.append(dict(components=ks,completeOriginalFaces=faces,vertices=piece.tolist(),normals=np.cross(piece[:,1]-piece[:,0],piece[:,2]-piece[:,0]).tolist(),completeDisplayedRootedSourceFaces=hosts.tolist(),worldCenter=center.tolist()))
 DOC.mkdir(parents=True);fig.tight_layout();image=DOC/'original-upper-detail-groups-1800x1440.png';fig.savefig(image,dpi=100);plt.close(fig);refs=[ref(p) for p in [Path(__file__),*assets,GRAPH/'diagnostic.json.gz',GRAPH/'result.json',DIST/'diagnostic.json.gz',DIST/'result.json',image,HERE/'exact_packed_world_geometry_20261009.py']];save(DOC/'diagnostic.json.gz',dict(uids=['landsd/91827:0','landsd/104302:0'],rows=rows,image=ref(image),pixelDimensions=[1800,1440],sourceGeometryChanges=0,visualInterpretationNotAcceptance=True,evidenceRefs=refs));spec=importlib.util.spec_from_file_location('freeze',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);m.freeze(BATCH,'complete-original-upper-four-groups-rendered-context-v1',[ROOT/r['path'] for r in refs],dict(uids=['landsd/91827:0','landsd/104302:0'],sourceOnlyVisualContext=True,sourceGeometryChanges=0,visualRoleAccepted=False))
if __name__=='__main__':main()
