"""Freeze closed exact source-role diagnostics and honest terrain budget failures."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,digest
BATCH='government-xl-tung-sing-closed-source-support-and-budget-20261010';DOC=ROOT/'docs/astra-city/government-import'/BATCH
NAMES=['government-xl-lei-tung-current-full-cell-preflight-v2-20261010','government-xl-tung-sing-original-pair-source-tin-context-20261010','government-xl-tung-sing-original-pair-exact-source-terrain-20261010','government-xl-tung-sing-original-pair-source-anchor-paths-20261010','government-xl-tung-sing-two-detached-original-context-20261010','government-xl-tung-sing-two-original-continuous-counterparts-20261010','government-xl-tung-sing-two-original-roof-contact-20261010','government-xl-tung-sing-two-original-boundary-host-context-20261010','government-xl-tung-sing-two-original-physical-inputs-20261010','government-xl-tung-sing-two-complete-original-physical-20261010','government-xl-tung-sing-two-retained-original-physical-v2-20261010','government-xl-tung-sing-retained-original-terrain-census-20261010']
FILES=['xl-lei-tung-current-full-cell-preflight-20261010.py','xl-lei-tung-current-full-cell-preflight-v2-20261010.py','xl-tung-sing-original-pair-source-tin-context-20261010.py','xl-tung-sing-original-pair-exact-terrain-coverage-20261010.py','xl-tung-sing-original-pair-source-ground-interfaces-20261010.mjs','xl-tung-sing-original-pair-source-anchor-paths-20261010.py','xl-tung-sing-two-detached-original-context-20261010.py','xl-tung-sing-two-original-continuous-counterparts-20261010.py','xl-tung-sing-two-original-roof-contact-20261010.py','xl-tung-sing-two-original-roof-contact-20261010.mjs','xl-tung-sing-two-original-boundary-host-context-20261010.py','tung_sing_two_original_collection_identity_20261010.py','xl-tung-sing-two-original-contact-resolution-20261010.py','xl-tung-sing-two-physical-inputs-20261010.py','xl-tung-sing-two-complete-original-physical-20261010.py','xl-tung-sing-two-retained-original-physical-v2-20261010.py','xl-tung-sing-retained-original-terrain-census-20261010.py']
def main():
 assert not DOC.exists();DOC.mkdir(parents=True)
 (DOC/'README.md').write_text('''# Tung Sing / Lei Tung closed source support and terrain budget diagnostics

Both unchanged originals retain all 11,877 faces and 368 source components. The original source TIN covers all24 initially flagged finite facets exactly (Fraction union; no buffer or tolerance). It has zero upward burial violations. The exact positive-dimensional component graph reaches366/368 components from two strict original-ground anchors; this is a source-only diagnostic, not current support approval.

The two unresolved8-face Tung Sing façade components343/344 have no exact surface contacts. All eight open boundaries of each component continuously lie within1cm of actual original mainbody witness surfaces; every finite edge is subdivided and bounded using1-Lipschitz continuity. Corners alone are not proof: full-facet conservative witness bounds are0.568/0.577m, and ordinary source-roof low-rim checks fail. These facts support only a separately reviewable original architectural envelope interpretation. No snapping, fabricated contacts or load-bearing/roof-mount claim.

The first full physical attempt explicitly required retaining existing native163705 terrain. The retained second attempt passed both current identities/native memberships but failed the100,000-facet runtime budget before remaining checks; Neon e0b7d0121d467d6f6fe3c03e789b4e262bb4c4bd0f5ec967e4093327cd93deb2 preserves the failure. Read-only census finds111,616 original facets and zero exact duplicates across the expanded whole retained patch. A new nested candidate, outside this immutable scope, preserves the existing parent and limits work to actual new model regions. No budget increase or installation credit.

Raw legacy/roof/coverage/retained/budget failures are kept. These completed diagnostics predate hospital publication; manifest versions are historical and cannot be reused as current acceptance. No source building mesh/elevation edits, AI geometry modelling, live terrain changes or permanent rejection.
''')
 paths=[Path(__file__)]+[HERE/f for f in FILES];scopes=[str(DOC.relative_to(ROOT))]+['docs/astra-city/government-import/'+n for n in NAMES]+['source-scripts/city/government-import/'+f for f in FILES]+[str(Path(__file__).relative_to(ROOT))]
 for name in NAMES:
  folder=DOC.parent/name;assert folder.exists();paths.extend(q for q in folder.rglob('*') if q.is_file())
 for name in ['government-xl-tung-sing-two-complete-original-physical-20261010','government-xl-tung-sing-two-retained-original-physical-v2-20261010']:
  paths.extend(q for q in (HERE/'local'/name/'frozen-inputs').rglob('*') if q.is_file());scopes.append('source-scripts/city/government-import/local/'+name+'/frozen-inputs')
 s=importlib.util.spec_from_file_location('tung_sing_closed_freezer',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.freeze(BATCH,'closed-original-component-and-terrain-budget-diagnostics-v1',paths,{'uids':['landsd/53800:0','landsd/126434:0'],'identityAccepted':False,'physicalAccepted':False,'completeOriginalFaces':11877,'completeOriginalComponents':368,'sourceOnlyPositivePathComponents':366,'unresolvedSourceOriginalComponents':[343,344],'exactInitialTerrainCoverageResolved':24,'previousTerrainRuntimeBudgetFailurePreserved':True,'terrainRuntimeBudgetRaised':False,'remainingReason':'distinct-fresh-nested-physical-and-source-envelope-role-checks-running'})
 Path('/tmp/xl-identity-tung-sing-closed-source-support-and-budget-scope-20261010.json').write_text(json.dumps(scopes,indent=2)+'\n')
if __name__=='__main__':main()
