"""Exact finite coverage refinement of historical raw current-candidate flags."""
from pathlib import Path
import numpy as np,json
from run import ROOT,HERE,read,save,digest
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from exact_original_slab_projection_coverage_20261010 import slab_coverage
BATCH='government-xl-tung-sing-three-original-captured-exact-coverage-20261010';DOC=ROOT/'docs/astra-city/government-import'/BATCH;PHYSICAL=DOC.parent/'government-xl-tung-sing-three-original-literal-parent-physical-20261010';CONTEXT=DOC.parent/'government-xl-tung-sing-three-original-complete-current-face-context-20261010/diagnostic.json.gz';RUNTIME=HERE/'local'/PHYSICAL.name/'runtime-geometry.json.gz'
def main():
 assert not DOC.exists();s=read(PHYSICAL/'selection.json.gz');prior=read(CONTEXT);assert prior['manifestSHA256']==s['manifestSHA256'];runtime={r['uid']:r for r in read(RUNTIME)['rows']};out=[];refs=[Path(__file__),CONTEXT,PHYSICAL/'result.json',PHYSICAL/'selection.json.gz',RUNTIME,HERE/'exact_original_slab_projection_coverage_20261010.py',HERE/'exact_original_projection_coverage_20261009.py']
 for r in s['rows']:
  raw=(ROOT/r['candidate']['path']).read_bytes();assert digest(raw)==r['sourceSHA256'];a=decode_original_world_triangles(raw);g=runtime[r['uid']];ground=np.asarray(g['drawnGroundGeometry']).reshape(-1,3,3);world=np.asarray(g['position']).reshape(-1,3)[np.asarray(g['index']).reshape(-1,3)];old=next(v for v in prior['rows'] if v['uid']==r['uid']);assert old['completeOriginalWorldSHA256']==digest(a.astype('<f8').tobytes()) and old['completeActualGroundSHA256']==digest(ground.astype('<f8').tobytes());rows=[]
  for i in old['summary']['uncoveredSourceFaces']:
   first=slab_coverage(a[i],ground);second=slab_coverage(world[i],ground);rows.append({'sourceFace':i,'rawOriginalContextVerbatim':old['allOriginalFaceContexts'][i],'completeOriginalExactFiniteCoverage':first,'completeActualRenderedExactFiniteCoverage':second,'originalExactCoverageAccepted':first['exactProjectionCovered'],'actualRenderedExactCoverageAccepted':second['exactProjectionCovered']});print({'uid':r['uid'],'sourceFace':i,'original':first['exactProjectionCovered'],'rendered':second['exactProjectionCovered']},flush=True)
  out.append({'uid':r['uid'],'sourceSHA256':r['sourceSHA256'],'completeOriginalWorldSHA256':old['completeOriginalWorldSHA256'],'completeActualRenderedWorldSHA256':digest(world.astype('<f8').tobytes()),'completeActualGroundSHA256':old['completeActualGroundSHA256'],'allRawUncoveredFacesRefined':rows,'unresolvedOriginalSourceFaces':[v['sourceFace'] for v in rows if not v['originalExactCoverageAccepted']],'unresolvedActualRenderedFaces':[v['sourceFace'] for v in rows if not v['actualRenderedExactCoverageAccepted']]});refs.append(ROOT/r['candidate']['path'])
 save(DOC/'diagnostic.json.gz',{'rows':out,'capturedManifestSHA256':s['manifestSHA256'],'freshCurrentLiveBindingAccepted':False,'inputHashes':{str(p.relative_to(ROOT)):digest(p.read_bytes()) for p in refs},'sourceGeometryChanges':0,'physicalAccepted':False,'installationApproved':False,'qualification':'Exact Fraction complete finite original and actual-rendered facet/edge coverage only, immutable422e candidate math. Every raw coverage failure retained. Genuine point/line/interior gaps remain failures; no tolerance/buffer, geometry edits or fresh-current credit.'});print(json.dumps([{'uid':r['uid'],'unresolvedOriginal':r['unresolvedOriginalSourceFaces'],'unresolvedRendered':r['unresolvedActualRenderedFaces']} for r in out]),flush=True)
if __name__=='__main__':main()
