"""Diagnostic only: every original finite face versus actual candidate terrain."""
from pathlib import Path
import numpy as np,shapely,json
from run import ROOT,HERE,read,save,digest
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from original_face_ground_crossing_v2_20261009 import face_ground_context
from original_degenerate_ground_context_20261009 import degenerate_ground_context
BATCH='government-xl-tung-sing-three-original-complete-current-face-context-20261010';DOC=ROOT/'docs/astra-city/government-import'/BATCH;PHYSICAL=DOC.parent/'government-xl-tung-sing-three-original-literal-parent-physical-20261010';RUNTIME=HERE/'local'/PHYSICAL.name/'runtime-geometry.json.gz'
def main():
 assert not DOC.exists();s=read(PHYSICAL/'selection.json.gz');assert s['manifestSHA256']==digest((ROOT/'3d-viewer/city/data/manifest.json').read_bytes());runtime={r['uid']:r for r in read(RUNTIME)['rows']};out=[];refs=[Path(__file__),PHYSICAL/'result.json',PHYSICAL/'selection.json.gz',RUNTIME,HERE/'original_face_ground_crossing_v2_20261009.py',HERE/'original_degenerate_ground_context_20261009.py',ROOT/'3d-viewer/city/data/manifest.json']
 for r in s['rows']:
  uid=r['uid'];raw=(ROOT/r['candidate']['path']).read_bytes();assert digest(raw)==r['sourceSHA256'];a=decode_original_world_triangles(raw);g=runtime[uid];assert g['sourceSHA256']==r['sourceSHA256'];world=np.asarray(g['position']).reshape(-1,3)[np.asarray(g['index']).reshape(-1,3)];assert world.shape==a.shape;ground=np.asarray(g['drawnGroundGeometry']).reshape(-1,3,3);allpolys=shapely.polygons(ground[:,:,[0,2]]);valid=shapely.area(allpolys)>0;surfaces,polys=ground[valid],allpolys[valid];tree=shapely.STRtree(polys);n=np.cross(a[:,1]-a[:,0],a[:,2]-a[:,0]);length=np.linalg.norm(n,axis=1);ratio=np.divide(n[:,1],length,out=np.zeros(len(a)),where=length>0);contexts=[]
  for i,face in enumerate(a):
   c=face_ground_context(face,surfaces,polys,tree) if length[i]>0 else degenerate_ground_context(face,surfaces,polys,tree);contexts.append({'sourceFace':i,'normalYRatio':float(ratio[i]),'completeOriginal':c})
   if i%500==0:save(DOC/'progress.json',{'uid':uid,'facesChecked':i,'completeActorOriginalFaces':len(a)});print({'uid':uid,'facesChecked':i,'completeActorOriginalFaces':len(a)},flush=True)
  missing=[i for i,c in enumerate(contexts) if not c['completeOriginal']['groundProjectionCovered']];affected=[i for i,c in enumerate(contexts) if c['completeOriginal']['minimum'] and c['completeOriginal']['minimum']['minimumGapM']<-.5];up=[i for i in affected if ratio[i]>.25];summary={'uid':uid,'sourceFaces':len(a),'actualDrawnGroundFacets':len(ground),'nonHeightOnlyFacetsRetainedAndSeparatelyUncertified':list(map(int,np.flatnonzero(~valid))),'uncoveredSourceFaces':missing,'affectedOriginalFaces':affected,'affectedUpwardOriginalFaces':up,'affectedNonwallOriginalFaces':[i for i in affected if abs(ratio[i])>.25],'rawRemainingPhysicalReasonsPreserved':True};out.append({'uid':uid,'sourceSHA256':r['sourceSHA256'],'completeOriginalWorldSHA256':digest(a.astype('<f8').tobytes()),'completeActualRenderedWorldSHA256':digest(world.astype('<f8').tobytes()),'maximumObservedDecodedActualWorldDifferenceM':float(np.max(np.abs(world-a))),'renderedParityAccepted':False,'completeActualGroundSHA256':digest(ground.astype('<f8').tobytes()),'allOriginalFaceContexts':contexts,'summary':summary});refs.append(ROOT/r['candidate']['path']);save(DOC/'progress-summary.json',summary)
 save(DOC/'diagnostic.json.gz',{'rows':out,'manifestSHA256':s['manifestSHA256'],'inputHashes':{str(p.relative_to(ROOT)):digest(p.read_bytes()) for p in refs},'sourceGeometryChanges':0,'physicalAccepted':False,'qualification':'Complete every original finite source face causal census against its actual candidate drawn ground height facets. Original/rendered hashes and observed differences recorded without parity acceptance. Every collapsed ground facet remains retained in runtime and requires separate finite proof. All raw wall/gap/role/foreign/foundation/runtime failures preserved.'});print(json.dumps([r['summary'] for r in out]),flush=True)
if __name__=='__main__':main()
