"""Actual full provider source pin and bounded AI sign-role interpretation."""
import importlib.util
from pathlib import Path
from run import ROOT,HERE,read,save,digest
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from xl_source_stream_binding_20261009 import source_stream_binding
from festival_original_mounted_sign_roles_20261010 import SOURCE,WORLD,FACES
BATCH='xl-terrain-recovery-20261010-festival-original-three-provider-sign-role-v1';BASE=ROOT/'docs/astra-city/government-import';DOC=BASE/BATCH
GRAPH=BASE/'xl-terrain-recovery-20261010-festival-podium-independent-original-support-v1';PHYS=BASE/'government-xl-festival-two-originals-full-physical-20261007';VISUAL=BASE/'xl-terrain-recovery-20261010-festival-original-three-detail-visual-v1';DIST=BASE/'xl-terrain-recovery-20261010-festival-original-three-finite-mount-boundaries-v1'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not DOC.exists();g=read(GRAPH/'diagnostic.json.gz');r=next(r for r in read(PHYS/'selection.json.gz')['rows'] if r['uid']=='landsd/91827:0');asset=ROOT/r['candidate']['path'];raw=asset.read_bytes();assert digest(raw)==r['sourceSHA256']==SOURCE;tri=decode_original_world_triangles(raw);assert len(tri)==18484 and digest(tri.tobytes())==WORLD;stream=source_stream_binding(raw);assert g['actors'][0]['sourceSHA256']==SOURCE and g['actors'][0]['originalStreamBindingSHA256']==digest(__import__('json').dumps(stream,sort_keys=True,separators=(',',':')).encode());assert read(DIST/'diagnostic.json.gz')['sourceOnlyPassedComponents']==[46,53,58]
 for k,ids in FACES.items():assert g['components'][k]['globalOriginalFaces']==ids
 role=dict(contract='festival-walk-original-I-L-dash-facade-sign-role-v1',sourceSHA256=SOURCE,completeOriginalWorldSHA256=WORLD,completeOriginalActor=g['actors'][0],completeOriginalProviderRootAndStreams=stream,allSignComponents=[46,53,58],completeOriginalSignFaces=FACES,interpretation='The complete original components form I, L and dash glyphs alongside the other source-authored Festival Walk facade lettering. Their entire original directed back openings lie within the existing finite .1 m band of independently rooted original facade faces. Visual detail role only; no structural, ground, bridge, collision or terrain exemption.',sourceRoleReviewUsedAI=True,geometryModelledWithAI=False,sourceGeometryChanges=0,upperActorOtherDetailsAccepted=False,fullCurrentAcceptance=False,installationApproved=False);save(DOC/'provider-role.json.gz',role);refs=[ref(p) for p in [Path(__file__),asset,GRAPH/'diagnostic.json.gz',GRAPH/'result.json',PHYS/'selection.json.gz',VISUAL/'diagnostic.json.gz',VISUAL/'original-three-details-1800x720.png',VISUAL/'result.json',DIST/'diagnostic.json.gz',DIST/'result.json',HERE/'festival_original_mounted_sign_roles_20261010.py',HERE/'xl_source_stream_binding_20261009.py',HERE/'exact_packed_world_geometry_20261009.py']];save(DOC/'source-role-binding.json',dict(uids=['landsd/91827:0'],actualSource=ref(asset),providerRole=ref(DOC/'provider-role.json.gz'),evidenceRefs=refs));spec=importlib.util.spec_from_file_location('f',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);m.freeze(BATCH,'actual-provider-three-original-facade-sign-glyph-visual-role-v1',[ROOT/r['path'] for r in refs],dict(uids=['landsd/91827:0'],boundedSourceRoleAIInterpretation=True,visualOnlySignComponents=[46,53,58],structuralRootCredit=False,upperActorOtherDetailsAccepted=False,fullCurrentAcceptance=False))
if __name__=='__main__':main()
