"""Complete source counterpart witnesses for two original rooftop parts; no edits."""
import importlib.util,numpy as np,shapely
from run import ROOT,HERE,read,save,digest
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from source_closed_components import components
import matplotlib;matplotlib.use('Agg')
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
DOC=ROOT/'docs/astra-city/government-import/government-xl-tung-sing-two-detached-original-context-20261010'
GRAPH=DOC.parent/'government-xl-tung-sing-original-pair-source-anchor-paths-20261010/diagnostic.json.gz'
INPUT=DOC.parent/'government-xl-tung-sing-lei-tung-original-source-relationship-20261010'
def main():
 assert not DOC.exists();row=read(INPUT/'selection.json.gz')['rows'][0];source=ROOT/row['candidate']['path'];tri=decode_original_world_triangles(source.read_bytes());graph=read(GRAPH);parts=components(tri)['components'];missing=[p for i,p in enumerate(parts) if i in graph['componentsWithoutPositiveOriginalGroundPath']];assert len(missing)==2;excluded=[f for p in missing for f in p['faceIndices']];attached=np.setdiff1d(np.arange(len(tri)),excluded);main=parts[1]['faceIndices'];s=importlib.util.spec_from_file_location('tung_sing_nearest_original',HERE/'xl-popcorn-original-panel-distance-20261009.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);rows=[]
 for part in missing:
  ids=part['faceIndices'];face=tri[ids];vertices=np.unique(face.reshape(-1,3),axis=0);witness=[]
  for point in vertices:
   ds,ws=m.closest(point,tri[attached]);j=int(np.argmin(ds));md,mw=m.closest(point,tri[main]);k=int(np.argmin(md));witness.append({'originalVertex':point.tolist(),'attachedOriginalSourceFace':int(attached[j]),'nearestAttachedOriginalPoint':ws[j].tolist(),'attachedOriginalDistanceM':float(ds[j]),'mainbodyOriginalFace':int(main[k]),'nearestOriginalMainbodyPoint':mw[k].tolist(),'originalMainbodyDistanceM':float(md[k])})
  n=np.cross(face[:,1]-face[:,0],face[:,2]-face[:,0]);length=np.linalg.norm(n,axis=1);ratios=np.divide(n[:,1],length,out=np.zeros(len(face)),where=length>0);projection=shapely.union_all(shapely.polygons(face[:,:,[0,2]]));mp=shapely.union_all(shapely.polygons(tri[main][:,:,[0,2]]));rows.append({'component':next(i for i,p in enumerate(parts) if p==part),'allOriginalFaces':ids,'allOriginalFaceVertices':face.tolist(),'completeOriginalTopology':part,'normalYRatios':ratios.tolist(),'wholePartProjectionInsideMainbody':mp.covers(projection),'partProjectionOutsideMainbodyAreaM2':projection.difference(mp).area,'wholeOriginalVertexWitnesses':witness,'maximumVertexToAttachedOriginalM':max(q['attachedOriginalDistanceM'] for q in witness),'maximumVertexToMainbodyM':max(q['originalMainbodyDistanceM'] for q in witness)})
  lo,hi=face.min(axis=(0,1)),face.max(axis=(0,1));near=[i for i,t in enumerate(tri) if np.all(t.max(axis=0)>=lo-1)&np.all(t.min(axis=0)<=hi+1)];fig=plt.figure(figsize=(12,9));ax=fig.add_subplot(111,projection='3d');ax.add_collection3d(Poly3DCollection(tri[near][:,:,[0,2,1]],facecolors='#bbb',edgecolors='#555',linewidths=.2,alpha=.25));ax.add_collection3d(Poly3DCollection(face[:,:,[0,2,1]],facecolors='#e76f51',edgecolors='#c00',linewidths=.5,alpha=.7));ax.set_xlim(lo[0]-.7,hi[0]+.7);ax.set_ylim(lo[2]-.7,hi[2]+.7);ax.set_zlim(lo[1]-.7,hi[1]+.7);ax.view_init(25,-55);ax.set_title('Complete untouched Tung Sing original rooftop component '+str(rows[-1]['component']));fig.tight_layout();file=DOC/('original-component-'+str(rows[-1]['component'])+'-2400x1800.png');file.parent.mkdir(parents=True,exist_ok=True);fig.savefig(file,dpi=200);plt.close(fig)
 save(DOC/'diagnostic.json.gz',{'uid':row['uid'],'sourceSHA256':row['sourceSHA256'],'wholeSourceWorldSHA256':digest(tri.astype('<f8').tobytes()),'rows':rows,'inputHashes':{str(source.relative_to(ROOT)):digest(source.read_bytes()),str(GRAPH.relative_to(ROOT)):digest(GRAPH.read_bytes())},'sourceGeometryChanges':0,'physicalAccepted':False,'exactNoContactFailurePreserved':True,'qualification':'Complete original eight-face rooftop parts and all nearest original surfaces diagnosed. Projection containment/vertex distances alone supply no continuous surface relation, source function or load-bearing support credit. Every source part retained; no geometry edits.'});print([{k:r[k] for k in ['component','allOriginalFaces','normalYRatios','wholePartProjectionInsideMainbody','partProjectionOutsideMainbodyAreaM2','maximumVertexToAttachedOriginalM','maximumVertexToMainbodyM']} for r in rows],flush=True)
if __name__=='__main__':main()
