"""Authoritative exact three-original source family context, no acceptance waiver."""
from pathlib import Path
import importlib.util,json
from run import ROOT,HERE,read,save,digest
DOC=ROOT/'docs/astra-city/government-import/government-xl-tung-sing-three-original-primary-family-20261010'
def main():
 assert not DOC.exists();manifest=ROOT/'3d-viewer/city/data/manifest.json';pin=digest(manifest.read_bytes());paths=[DOC.parent/'government-xl-tung-sing-interior-current-identity-inputs-v2-20261010/selection.json.gz',DOC.parent/'government-xl-tung-sing-commercial-current-identity-diagnostic-20261010/selection.json.gz'];rows=read(paths[0])['rows']+read(paths[1])['rows'];assert len(rows)==3;ids=[r['source']['building']['buildingCSUID'] for r in rows];where='BuildingCSUID IN ('+','.join("'"+v+"'" for v in ids)+')';s=importlib.util.spec_from_file_location('tung_three_primary_query',HERE/'xl-aqua-marine-fresh-overhead-source-context-v3-20261010.py');q=importlib.util.module_from_spec(s);s.loader.exec_module(q);DOC.mkdir(parents=True);q.DOC=DOC;primary=q.query(0,where,'exact-current-primary',True);relations=q.query(1002,where,'exact-current-relations');structureids=sorted({r['attributes']['BuildingStructureID'] for r in relations});structures=q.query(1003,'BuildingStructureID IN ('+','.join(map(str,structureids))+')','exact-current-structures') if structureids else [];reverse=q.query(1002,'BuildingStructureID IN ('+','.join(map(str,structureids))+')','exact-all-related-buildings') if structureids else []
 assert len(primary)==3 and digest(manifest.read_bytes())==pin
 save(DOC/'primary-family-context.json.gz',{'manifestSHA256':pin,'originalRows':rows,'exactPrimaryFeatures':primary,'exactStructureRelations':relations,'exactStructures':structures,'allRelatedBuildingRelations':reverse,'inputHashes':{str(p.relative_to(ROOT)):digest(p.read_bytes()) for p in paths+[Path(__file__)]},'rawCommercialStandaloneTargetCoverage':.94791057849,'identityAccepted':False,'physicalAccepted':False,'qualification':'Exact authoritative unique source identifier/component/structure/permit context. Compound projection alone does not waive individual95% or grant ownership, support, actor suppression, terrain or collision credit.'});print(json.dumps({'structures':structures,'relations':relations,'reverse':reverse}),flush=True)
if __name__=='__main__':main()
