"""Independent strict literal-rendered P0/T361 full-rim checks; no arithmetic parity credit."""
import subprocess,json,numpy as np
from pathlib import Path
from run import ROOT,HERE,read,save,digest
BATCH='government-xl-tung-sing-three-original-literal-rendered-footings-20261010';DOC=ROOT/'docs/astra-city/government-import'/BATCH
PHYS=DOC.parent/'government-xl-tung-sing-three-original-literal-parent-physical-v2-20261010';RUNTIME=HERE/'local'/PHYS.name/'runtime-geometry.json.gz'
def main():
 assert not DOC.exists();manifest=ROOT/'3d-viewer/city/data/manifest.json';selection=read(PHYS/'selection.json.gz');assert digest(manifest.read_bytes())==selection['manifestSHA256'];runtime=read(RUNTIME);out=[];deps=[Path(__file__),RUNTIME,manifest,PHYS/'selection.json.gz',HERE/'xl-tung-sing-three-original-footing-readonly-replay-20261010.mjs',HERE/'support-interface.mjs']
 for folder,uid,part in [('government-xl-tung-sing-three-original-current-anchor-v2-20261010','landsd/126434:0',0),('government-xl-tung-sing-three-original-current-tower-footing-v2-20261010','landsd/53800:0',361)]:
  source=DOC.parent/folder/'complete-current-original-platform-anchor-input.json.gz';inp=read(source);r=next(x for x in runtime['rows'] if x['uid']==uid);assert r['sourceSHA256']==inp['sourceSHA256'];world=np.asarray(r['position']).reshape(-1,3)[np.asarray(r['index']).reshape(-1,3)];ground=np.asarray(r['drawnGroundGeometry']).reshape(-1,3,3);assert np.array_equal(ground,np.asarray(inp['terrain']['position']).reshape(-1,3,3));ids=inp['part']['originalFaceIds'];actual=world[ids];assert inp['part']['component']==part;inp['representation']='complete-literal-actual-rendered';inp['completeLiteralRenderedWorldSHA256']=digest(world.tobytes());inp['part']['position']=actual.reshape(-1).tolist();inp['part']['bottomHKPD']=float(actual[:,:,1].min());inp['inputHashes']={str(p.relative_to(ROOT)):digest(p.read_bytes()) for p in [source,*deps]};path=DOC/(uid.replace('/','-').replace(':','-')+'-input.json.gz');save(path,inp);res=json.loads(subprocess.check_output(['node',str(HERE/'xl-tung-sing-three-original-footing-readonly-replay-20261010.mjs'),str(path)],cwd=ROOT,text=True));print(uid,res,flush=True);assert res.get('passed') is True,res;out.append({'uid':uid,'component':part,'completeLiteralRenderedWorldSHA256':digest(world.tobytes()),'completeCurrentDrawnGroundSHA256':digest(ground.tobytes()),'inputPath':str(path.relative_to(ROOT)),'inputSHA256':digest(path.read_bytes()),'strictLiteralRenderedCurrentGroundAnchor':True,'result':res});deps.extend([source,path])
 assert digest(manifest.read_bytes())==selection['manifestSHA256'];save(DOC/'diagnostic.json.gz',{'manifestSHA256':selection['manifestSHA256'],'rows':out,'strictLiteralRenderedCurrentGroundAnchors':True,'buildingGeometryChanges':0,'arithmeticParityCredit':False,'physicalAccepted':False});print({'strictLiteralRenderedCurrentGroundAnchors':True},flush=True)
if __name__=='__main__':main()
