"""Bind Green18's fully verified current source-specific acceptance to plain stage."""
from pathlib import Path
from run import ROOT,HERE,read,save,digest
BASE=ROOT/'docs/astra-city/government-import';DOC=BASE/'xl-terrain-recovery-20261010-green18-plain-stage-config-v1';ROLE=BASE/'xl-terrain-recovery-20261010-green18-current-complete-support-v2';PHYSICAL=BASE/'government-xl-terrain-recovery-green18-original-terrain-current-v1-20261010'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not DOC.exists();typed=read(ROLE/'typed-role.json.gz');assert typed['independentPhysicalChecksPassed'] and not typed['unresolvedIndependentPhysicalReasons'];assert typed['manifestSHA256']==digest((ROOT/'3d-viewer/city/data/manifest.json').read_bytes())
 cfg=dict(schema='plain-single-source-original-stage-v1',batch='government-xl-terrain-recovery-green18-plain-typed-stage-v1-20261010',sources={'landsd/6462:0':'d2d2c62ed2d29ffbf7ec4060c108f1c53eb784558120cb153a5d9482d60d493f'},completeOriginalFaces=11088,completeOriginalComponents=903,plainNewTerrain=True,retainedNativeUIDs=[],supportDependencies=[],physicalReceipt=ref(PHYSICAL/'result.json'),currentRoleReceipt=ref(ROLE/'result.json'),currentTypedRole=ref(ROLE/'typed-role.json.gz'),currentRoleRunner=ref(HERE/'xl-terrain-recovery-20261010-green18-current-complete-support-v2.py'),plainStageRunner=ref(HERE/'xl-terrain-recovery-20261010-plain-single-source-stage-v1.py'),plainLiveRunner=ref(HERE/'xl-terrain-recovery-20261010-plain-single-source-live-v1.py'),area='Green18 complete unchanged government original',captureDirection=[-.65,.75,-.5],placementReview='Complete unchanged original government Green18: all903 original components are rooted through five independently verified ordinary ground interfaces and1367 exact positive-dimensional authored contacts. All11088 original and actual rendered faces independently satisfy the existing whole-facet -.5m limit; both complete source support and current foundation/identity/four ordinary forms/all native whole bounds/sampler/runtime gates pass. The historical global-bottom contact failure remains recorded and is resolved only by the complete original assembly proof. Original compressed source, POSITION/NORMAL/COLOR/root/elevation and frozen source-authentic terrain proposal are unchanged; no visual roots/bridges, no omitted faces/actors and zero AI geometry modelling.',producer=ref(Path(__file__)))
 save(DOC/'config.json',cfg);print(str((DOC/'config.json').relative_to(ROOT)))
if __name__=='__main__':main()
