"""Stage two untouched Park Haven originals; root owns later atomic publication."""
import argparse,importlib.util,json,os,shutil,subprocess,sys,uuid
from pathlib import Path
from run import ROOT,HERE,read,save,digest,reservations,connect
from dependency_preflight import from_catalogues
UIDS={'landsd/246467:0','landsd/320705:0'}
PHYSICAL=ROOT/'docs/astra-city/government-import/government-xl-terrain-recovery-park-haven-overlapping-native-parent-original-pair-current-physical-v4-20261010'
ROLE=ROOT/'docs/astra-city/government-import/government-xl-terrain-recovery-park-haven-post-atomic-complete-current-role-v2-20261010'
BATCH='government-xl-terrain-recovery-park-haven-two-typed-stage-v5-20261010';DOC=ROOT/'docs/astra-city/government-import'/BATCH;STAGE=HERE/'accepted'/BATCH;LEASE=HERE/'local'/BATCH/'install-reservation.json'
def ref(p):return dict(path=str(Path(p).relative_to(ROOT)),sha256=digest(Path(p).read_bytes()))
def module(name,path):
 spec=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);return m
def recheck(local):
 auditdoc=ROOT/'docs/astra-city/government-import/government-xl-terrain-recovery-park-haven-final-native-validation-v2-20261010';auditreceipt=read(auditdoc/'result.json')
 with connect() as c:c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(auditreceipt['jobId'],)).fetchone()==('complete',auditreceipt)
 for r in auditreceipt['evidenceRefs']:assert ref(ROOT/r['path'])==r
 audited=module('park_frozen_native_publication_validation',HERE/'xl-terrain-recovery-20261010-park-haven-final-native-validation-v2.py').recheck();assert audited==read(auditdoc/'diagnostic.json') and audited['validationPassed'] is True
 receipt=read(ROLE/'result.json');assert read(ROLE/'neon-sync.json')==dict(jobId=receipt['jobId'],resultVerified=True)
 with connect() as c:c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(receipt['jobId'],)).fetchone()==('complete',receipt)
 for r in receipt['evidenceRefs']:assert ref(ROOT/r['path'])==r
 m=module('park_haven_complete_current_original_roles',HERE/'xl-terrain-recovery-20261010-park-haven-post-atomic-complete-current-role-v2.py');role=json.loads(json.dumps(m.recheck()));assert role==read(ROLE/'typed-role.json.gz') and role['currentTypedPhysicalAccepted'] and not role['reasons'] and role['completeStrictStructuralGraph']['supportInterfaceAccepted'];assert role['completeOriginalFaces']==11173 and role['completeOriginalComponents']==554 and role['completeCurrentNeighbourForms']==24 and role['allCurrentRetainedNativeChecksPassed'] is True
 rows=read(PHYSICAL/'selection.json.gz')['rows'];assert {r['uid'] for r in rows}==UIDS
 return rows,role['completeCurrentSourceIdentities'],role
PLACEMENT='Two unchanged original Park Haven sources,636-face podium and10537-face tower. All11173 original and literal facets meet existing strict finite clearance; all554 original components independently ground rooted through genuine podium root and738 exact original positive contacts, no visual or wall credit. All24 currentforms and full296-face existing native lowpodium pass. Explicit terrain-only proposal preserves actual current parent planes under complete native closed projection with measured overlap; no disjoint claim. Original source geometry, roots and attributes unchanged; all old failures retained.'

def owned():
 def owns():assert reservations.owns(read(LEASE))
 def call(cmd):subprocess.run(cmd,cwd=ROOT,check=True,env={**os.environ,'CHROME_PATH':'/opt/google/chrome/chrome'});owns()
 owns();rows,identities,role=recheck(HERE/'local'/BATCH/'identity-recheck');save(DOC/'identity-publication-recheck.json',identities);save(DOC/'typed-role-publication-recheck.json.gz',role);podium=next(r for r in rows if r['uid']=='landsd/246467:0');dependency=dict(uid=podium['uid'],csuid=podium['source']['building']['buildingCSUID'],sha256=podium['sourceSHA256'],state='candidate');entries=[]
 for row in rows:
  e=dict(row['candidate']['entry']);assert not e.get('suppressesBuildingUids') and not e.get('footprintScope') and not e.get('supportDependencies');e.update(priority='landmark',proceduralWindows=False,sourceIdentityReviewed=True,sourceIdentityReviewUsedAI=True,identityReviewApproved=True,placementReviewed=True,publicationApproved=True,supportDependencies=[] if row['uid']==podium['uid'] else [dependency],placementReview=PLACEMENT);asset=STAGE/e['asset'];asset.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(ROOT/row['candidate']['path'],asset);assert ref(asset)['sha256']==e['sha256'];entries.append(e)
 entries.sort(key=lambda e:e['uid']!=podium['uid']);catalogue=read(HERE/'local'/PHYSICAL.name/'catalogue.json');catalogue.update(models=entries,counts={'packedModels':2},area='Park Haven complete unchanged original podium and upper body');save(STAGE/'catalogue.json',catalogue);save(STAGE/'catalogue-index.json',dict(models=2,catalogues=['catalogue.json']));forms=read(PHYSICAL/'neighbour-inputs.json.gz')['rows'];sourceforms=[r['building'] for r in forms if r['building']['uid'] in UIDS];assert {r['uid'] for r in sourceforms}==UIDS;save(STAGE/'source-forms.json',sourceforms)
 candidates=read(PHYSICAL/'terrain-candidates.json');assert len(candidates)==1;c=candidates[0];assert set(c['uids'])==UIDS and c.get('replaces') and not c.get('replacesMany') and ref(ROOT/c['path'])['sha256']==c['sha256'];patch=STAGE/Path(c['path']).name;shutil.copyfile(ROOT/c['path'],patch);p=read(patch);parent=read(ROOT/'3d-viewer'/c['replaces']['url']);assert p.get('nativeMesh') and parent.get('nativeMesh') and p['meta']['targetUids']==['landsd/246270:0','landsd/246467:0','landsd/320705:0'] and parent['meta']['targetUids']==['landsd/246270:0']
 for k in ['w','h','cell','coarseCells','vegetation']:assert p.get(k)==parent.get(k)
 assert p['meta']['georef']==parent['meta']['georef'] and p['meta']['source']==parent['meta']['source']
 terrain=dict(source=ref(patch)['path'],sha256=ref(patch)['sha256'],destination='city/data/terrain-government-xl-park-haven-original-pair-installed-v1-20261010.json',resolution=p['cell'],area=catalogue['area']+' nested indexed government terrain and explicit dyadic foreign-parent preservation')
 NATIVE=PHYSICAL;native=read(NATIVE/'native-neighbour-checks.json');retained=['landsd/246270:0'];replacement=dict(c['replaces']);assert replacement['retainedUids']==retained and len(native['rows'])==1 and native['rows'][0]['passed'] and role['completeCurrentRetainedNativeChecks']==native
 assert replacement['url'] in {r['url'] for r in read(ROOT/'3d-viewer/city/data/manifest.json')['terrainPatches']}
 review=dict(status='approved-for-integration',supersededURL=replacement['url'],supersededSHA256=replacement['sha256'],replacementSHA256=terrain['sha256'],sourceGeometryChanged=False,terrainProposalChanged=True,aiCalls=0,modelGeometryChanges=0,retainedUids=retained,replacementTargetUids=sorted(p['meta']['targetUids']),fullMeshCheck=ref(NATIVE/'native-neighbour-checks.json'),completeOriginalNativeProjection=ref(PHYSICAL/'complete-original-native-projection-government-native-246270-0.json'),explicitMeasuredOwnedNativeOverlap=True,disjointClaim=False,completeOriginalNativeAndOwnedSourceFoundationsPassed=True)
 save(DOC/'native-replacement-review.json',review);terrain.update(replaces=replacement,nativeReview=ref(DOC/'native-replacement-review.json'))
 destination='city/data/official-models/'+BATCH+'/catalogue.json';save(STAGE/'plan.json',dict(areas=[dict(area=catalogue['area'],catalogue=ref(STAGE/'catalogue.json')['path'],destination=destination)],topLevelTerrainPatches=[terrain]));deps=from_catalogues(ROOT/'3d-viewer/city/data/manifest.json',[STAGE/'catalogue.json']);assert not any(r['blockers'] for r in deps['rows']);save(DOC/'dependencies.json',deps)
 assembly=[[min(e['worldBounds'][0][i] for e in entries) for i in range(3)],[max(e['worldBounds'][1][i] for e in entries) for i in range(3)]];config=dict(captureDirectionByModel={u:[.6,.9,.6] for u in UIDS},stage=str(STAGE.relative_to(ROOT))+'/',doc=str(DOC.relative_to(ROOT))+'/',catalogueURL=destination,terrain=[terrain],fitBox=True,captureBoundsByModel={e['uid']:e['worldBounds'] for e in entries},captureBoundsByViewport={'1280':{e['uid']:assembly for e in entries}},browserUids=sorted(UIDS),failureTestUids=sorted(UIDS),nativeSupportUidsByModel={'landsd/246467:0':retained,'landsd/320705:0':retained+['landsd/246467:0']});save(STAGE/'browser-config.json',config)
 evidence=[ref(q) for q in [HERE/'xl-terrain-recovery-20261010-park-haven-final-native-validation-v2.py',ROOT/'docs/astra-city/government-import/government-xl-terrain-recovery-park-haven-final-native-validation-v2-20261010/result.json',ROOT/'docs/astra-city/government-import/government-xl-terrain-recovery-park-haven-final-native-validation-v2-20261010/diagnostic.json',Path(__file__),PHYSICAL/'result.json',ROLE/'result.json',ROLE/'typed-role.json.gz',DOC/'identity-publication-recheck.json',DOC/'typed-role-publication-recheck.json.gz',DOC/'dependencies.json',DOC/'native-replacement-review.json',NATIVE/'result.json',NATIVE/'retained-native-proof.json',NATIVE/'native-neighbour-checks.json',STAGE/'catalogue.json',STAGE/'plan.json',STAGE/'browser-config.json',HERE/'xl-terrain-recovery-20261010-park-haven-post-atomic-complete-current-role-v2.py',HERE/'xl-terrain-recovery-20261010-multi-native-solid-browser-v5.mjs']];decision=dict(batch=BATCH,uids=sorted(UIDS),sourceSHA256s={r['uid']:r['sourceSHA256'] for r in rows},manifestSHA256=role['currentManifest']['sha256'],checksPassed=True,publication=False,newlyInstalled=0,modelGeometryChanges=0,terrainProposalGeometryChanged=True,scriptExternalAICalls=0,sourceEvidenceInterpretationUsedAI=True,aiGeometryModelling=False,evidenceRefs=evidence);save(DOC/'stage.json',decision)
 call([sys.executable,str(HERE.parent/'model-integration-20260909/publish.py'),ref(STAGE/'plan.json')['path'],'--receipt',str(LEASE),'--phase',BATCH]);call(['node',str(HERE/'xl-terrain-recovery-20261010-multi-native-solid-browser-v5.mjs'),'staged',ref(STAGE/'browser-config.json')['path']]);report=module('park_haven_browser_validator',HERE/'integrate.py').browser_verified(DOC/'staged-browser.json',UIDS);assert len(report['retainedNativeOwnViews'])==4*len(retained) and {v['uid'] for v in report['retainedNativeOwnViews']}==set(retained)
 for view in report['views']:
  if 'time' in view:
   expected=set(config['nativeSupportUidsByModel'][view['uid']]);assert set(view['nativeSupports'])==expected;assert all(v['active'] and v['visible'] for v in view['nativeSupports'].values() if v.get('wanted') or v.get('declaredCandidateSupport'));assert all(view['nativeSupports'][u].get('declaredCandidateSupport') for u in expected&UIDS)
 for r in evidence:assert ref(ROOT/r['path'])==r
 recheck(HERE/'local'/BATCH/'identity-recheck-final');decision.update(stagedBrowser=ref(DOC/'staged-browser.json'),passed=True,failures=[],livePublicationRequired=True);save(DOC/'acceptance.json',decision);print(json.dumps(dict(stagedBrowserPassed=True,uids=sorted(UIDS),publication=False,newlyInstalled=0)),flush=True)
def main():
 p=argparse.ArgumentParser();p.add_argument('--owned',action='store_true');a=p.parse_args()
 if a.owned:
  from publication_lock import locked_publication
  with locked_publication(ROOT):owned()
  return
 assert not DOC.exists() and not STAGE.exists();forms=read(PHYSICAL/'neighbour-inputs.json.gz')['rows'];retained=['landsd/246270:0'];resources={(('building:' if r['building']['uid'].startswith('landsd/') else 'source-form:')+r['building']['uid']) for r in forms}|{'building:'+u for u in retained}|{'terrain-patch:'+u for u in UIDS}|{'terrain-surface:'+read(PHYSICAL/'terrain-candidates.json')[0]['replaces']['url']};claim=reservations.claim('codex-park-haven-two-stage-'+str(uuid.uuid4()),sorted(resources),batch=BATCH,ttl=3600);assert claim['ok'],claim;save(LEASE,json.loads(json.dumps(claim['reservation'],default=str)));subprocess.run([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(LEASE),'--ttl','3600','--',sys.executable,__file__,'--owned'],cwd=ROOT,check=True)
if __name__=='__main__':main()
