"""Bind Mei Yat's fully verified current source-specific acceptance to plain stage."""
from pathlib import Path
from run import ROOT,HERE,read,save,digest
BASE=ROOT/'docs/astra-city/government-import';DOC=BASE/'xl-terrain-recovery-20261010-mei-yat-plain-stage-config-v2';ROLE=BASE/'xl-terrain-recovery-20261010-mei-yat-current-complete-visual-support-v1';PHYSICAL=BASE/'government-xl-terrain-recovery-mei-yat-original-terrain-current-v4-20261010'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not DOC.exists();typed=read(ROLE/'typed-role.json.gz');assert typed['independentPhysicalChecksPassed'] and not typed['unresolvedIndependentPhysicalReasons'];assert typed['manifestSHA256']==digest((ROOT/'3d-viewer/city/data/manifest.json').read_bytes())
 cfg=dict(schema='plain-single-source-original-stage-v1',batch='government-xl-terrain-recovery-mei-yat-plain-typed-stage-v2-20261010',sources={'landsd/183776:0':'ca03730a32beed8bd41aea1ef631517746bf20861dc83000364b39040abfcb82'},completeOriginalFaces=10209,completeOriginalComponents=878,plainNewTerrain=True,retainedNativeUIDs=[],supportDependencies=[],physicalReceipt=ref(PHYSICAL/'result.json'),currentRoleReceipt=ref(ROLE/'result.json'),currentTypedRole=ref(ROLE/'typed-role.json.gz'),currentRoleRunner=ref(HERE/'xl-terrain-recovery-20261010-mei-yat-current-complete-visual-support-v1.py'),plainStageRunner=ref(HERE/'xl-terrain-recovery-20261010-plain-single-source-stage-v1.py'),plainLiveRunner=ref(HERE/'xl-terrain-recovery-20261010-plain-single-source-live-v1.py'),area='Mei Yat complete unchanged government original',captureDirection=[.3,.9,1],placementReview='Complete unchanged original government Mei Yat: all 878 original parts are explicitly accounted. 757 independently rooted structural components retain the genuine ground root and 1380 exact positive-dimensional original contacts. The remaining 121 original authored facade panels, open-ended ledges and corner trim are separately bound nonstructural visual details mounted to already rooted original hosts within the unchanged finite 0.1m band, with zero root or bridge credit. All 10209 original and literal rendered facets independently satisfy the existing whole-facet -0.5m limit. Full current identity, all 19 foreign forms, complete native bounds, strict whole foundation, sampler and runtime checks pass. Raw 121 structural no-contact diagnostics, open boundaries and triple incidences remain recorded. Original compressed source, all provider attributes/root/elevation and the frozen source-authentic 413-face terrain proposal are unchanged; no omitted faces or actors and zero AI geometry modelling.',producer=ref(Path(__file__)))
 save(DOC/'config.json',cfg);print(str((DOC/'config.json').relative_to(ROOT)))
if __name__=='__main__':main()
