"""Stage three untouched Tung Sing/Lei Tung originals; root owns later atomic publication."""
import argparse,importlib.util,json,os,shutil,subprocess,sys,uuid
from pathlib import Path
from run import ROOT,HERE,read,save,digest,reservations,connect
from dependency_preflight import from_catalogues
UIDS={'landsd/53800:0','landsd/126434:0','landsd/254604:0'};PODIUM='landsd/126434:0';RETAINED={'landsd/12851:0','landsd/12852:0','landsd/12854:0','landsd/163705:0'}
PHYSICAL=ROOT/'docs/astra-city/government-import/government-xl-tung-sing-three-original-literal-parent-physical-v2-20261010'
ROLE=ROOT/'docs/astra-city/government-import/government-xl-tung-sing-three-original-current-complete-typed-role-v5-20261010'
BATCH='government-xl-tung-sing-three-original-complete-typed-stage-v1-20261010';DOC=ROOT/'docs/astra-city/government-import'/BATCH;STAGE=HERE/'accepted'/BATCH;LEASE=HERE/'local'/BATCH/'install-reservation.json'
def ref(p):return dict(path=str(Path(p).relative_to(ROOT)),sha256=digest(Path(p).read_bytes()))
def module(name,path):
 spec=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);return m
def recheck(local):
 receipt=read(ROLE/'result.json');assert read(ROLE/'neon-sync.json')==dict(jobId=receipt['jobId'],resultVerified=True)
 with connect() as c:c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(receipt['jobId'],)).fetchone()==('complete',receipt)
 for r in receipt['evidenceRefs']:assert ref(ROOT/r['path'])==r
 m=module('tung_complete_current_original_roles',HERE/'xl-tung-sing-three-original-current-complete-typed-role-v5-20261010.py');role=json.loads(json.dumps(m.recheck()));assert role==read(ROLE/'typed-role.json.gz') and role['currentTypedPhysicalAccepted'] and not role['reasons'] and role['allComponentsAccounted'];assert role['completeOriginalFaces']==12751 and role['completeOriginalComponents']==387 and role['completeCurrentNeighbourForms']==40
 rows=read(PHYSICAL/'selection.json.gz')['rows'];assert {r['uid'] for r in rows}==UIDS
 return rows,role['completeCurrentSourceIdentities'],role
PLACEMENT='Complete unchanged original Tung Sing tower, Lei Tung government podium and commercial platform. All12751 provider/root-decoded and literal-rendered faces have complete exact finite current ground coverage. Thirty-seven steep walls have strictly exposed original vertices and exact original clear-cap paths, with every current foreign basic, all current native bounds, and both other proposed originals independently checked for wall collisions. Strict original and independently literal-rendered P0/T361 footings ground385 ordinary components through unchanged original positive-dimensional interfaces; two complete authored single-opening sleeves have exact finite visual mounting edges within the existing .1m band and supply no structural/root credit. Mandatory source-bound tower/podium and lower/upper platform identities preserve standalone failed coverage and all raw failures. All40 current forms, four retained native actors, foundations, runtime picking/collision/sampler gates pass. The explicitly changed92211-facet terrain proposal includes exact parent consolidation, authenticated original terrain, separately qualified transition/residual and14 literal whole-source-disjoint parent facets. Government building bytes, all attributes/root/pose/elevations remain unchanged; zero AI geometry modelling.'
def owned():
 def owns():assert reservations.owns(read(LEASE))
 def call(cmd):subprocess.run(cmd,cwd=ROOT,check=True,env={**os.environ,'CHROME_PATH':'/opt/google/chrome/chrome'});owns()
 owns();rows,identities,role=recheck(HERE/'local'/BATCH/'identity-recheck');save(DOC/'identity-publication-recheck.json',identities);save(DOC/'typed-role-publication-recheck.json.gz',role);podium=next(r for r in rows if r['uid']==PODIUM);dependency=dict(uid=podium['uid'],csuid=podium['source']['building']['buildingCSUID'],sha256=podium['sourceSHA256'],state='candidate');entries=[]
 for row in rows:
  e=dict(row['candidate']['entry']);assert not e.get('suppressesBuildingUids') and not e.get('footprintScope') and not e.get('supportDependencies');e.update(priority='landmark',proceduralWindows=False,sourceIdentityReviewed=True,sourceIdentityReviewUsedAI=True,identityReviewApproved=True,placementReviewed=True,publicationApproved=True,supportDependencies=[] if row['uid']==podium['uid'] else [dependency],placementReview=PLACEMENT);asset=STAGE/e['asset'];asset.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(ROOT/row['candidate']['path'],asset);assert ref(asset)['sha256']==e['sha256'];entries.append(e)
 entries.sort(key=lambda e:e['uid']!=podium['uid']);catalogue=read(HERE/'local'/PHYSICAL.name/'catalogue.json');catalogue.update(models=entries,counts={'packedModels':3},area='Tung Sing and Lei Tung complete original three-model assembly');save(STAGE/'catalogue.json',catalogue);save(STAGE/'catalogue-index.json',dict(models=3,catalogues=['catalogue.json']));forms=read(PHYSICAL/'neighbour-inputs.json.gz')['rows'];sourceforms=[r['building'] for r in forms if r['building']['uid'] in UIDS];assert {r['uid'] for r in sourceforms}==UIDS;save(STAGE/'source-forms.json',sourceforms)
 candidates=read(PHYSICAL/'terrain-candidates.json');assert len(candidates)==1;c=candidates[0];assert set(c['uids'])==UIDS and c.get('replaces') and not c.get('replacesMany') and ref(ROOT/c['path'])['sha256']==c['sha256'];patch=STAGE/Path(c['path']).name;shutil.copyfile(ROOT/c['path'],patch);p=read(patch);assert p.get('nativeMesh') and not p.get('patches') and len(p['nativeMesh']['index'])//3==92211;assert p['meta']['parentTerrain']=='city/data/terrain.json' and p['meta']['parentSha256']==ref(ROOT/'3d-viewer/city/data/terrain.json')['sha256'];terrain=dict(source=ref(patch)['path'],sha256=ref(patch)['sha256'],destination='city/data/'+patch.name,resolution=p['cell'],area=catalogue['area']+' complete authentic finite native TIN restoration')
 replacement=c['replaces'];assert replacement['url']=='city/data/government-native-163705-0.json' and ref(ROOT/'3d-viewer'/replacement['url'])['sha256']==replacement['sha256'];assert replacement['url'] in {r['url'] for r in read(ROOT/'3d-viewer/city/data/manifest.json')['terrainPatches']};assert set(replacement['retainedUids'])==RETAINED and RETAINED|UIDS<=set(p['meta']['targetUids'])
 review=dict(status='approved-for-integration',supersededURL=replacement['url'],supersededSHA256=replacement['sha256'],replacementSHA256=terrain['sha256'],sourceGeometryChanged=False,terrainProposalGeometryChanged=True,aiCalls=0,modelGeometryChanges=0,retainedUids=replacement['retainedUids'],replacementTargetUids=p['meta']['targetUids'],fullMeshCheck=ref(PHYSICAL/'native-neighbour-checks.json'));save(DOC/'native-replacement-review.json',review);terrain.update(replaces=replacement,nativeReview=ref(DOC/'native-replacement-review.json'))
 destination='city/data/official-models/'+BATCH+'/catalogue.json';save(STAGE/'plan.json',dict(areas=[dict(area=catalogue['area'],catalogue=ref(STAGE/'catalogue.json')['path'],destination=destination)],topLevelTerrainPatches=[terrain]));deps=from_catalogues(ROOT/'3d-viewer/city/data/manifest.json',[STAGE/'catalogue.json']);assert not any(r['blockers'] for r in deps['rows']);save(DOC/'dependencies.json',deps)
 assembly=[[min(e['worldBounds'][0][i] for e in entries) for i in range(3)],[max(e['worldBounds'][1][i] for e in entries) for i in range(3)]];config=dict(captureDirectionByModel={u:[-.65,.75,-.5] for u in UIDS},stage=str(STAGE.relative_to(ROOT))+'/',doc=str(DOC.relative_to(ROOT))+'/',catalogueURL=destination,terrain=[terrain],fitBox=True,captureBoundsByModel={e['uid']:e['worldBounds'] for e in entries},captureBoundsByViewport={'1280':{e['uid']:assembly for e in entries}},browserUids=sorted(UIDS),failureTestUids=sorted(UIDS),nativeSupportUidsByModel={u:sorted(RETAINED)+([] if u==PODIUM else [PODIUM]) for u in UIDS});save(STAGE/'browser-config.json',config)
 evidence=[ref(q) for q in [Path(__file__),PHYSICAL/'result.json',ROLE/'result.json',ROLE/'typed-role.json.gz',DOC/'identity-publication-recheck.json',DOC/'typed-role-publication-recheck.json.gz',DOC/'dependencies.json',DOC/'native-replacement-review.json',STAGE/'catalogue.json',STAGE/'plan.json',STAGE/'browser-config.json',HERE/'xl-tung-sing-three-original-current-complete-typed-role-v5-20261010.py',HERE/'xl-terrain-recovery-20261010-multi-native-solid-browser-v5.mjs']];decision=dict(batch=BATCH,uids=sorted(UIDS),sourceSHA256s={r['uid']:r['sourceSHA256'] for r in rows},manifestSHA256=role['currentManifest']['sha256'],checksPassed=True,publication=False,newlyInstalled=0,modelGeometryChanges=0,terrainProposalGeometryChanged=True,scriptExternalAICalls=0,sourceEvidenceInterpretationUsedAI=True,aiGeometryModelling=False,evidenceRefs=evidence);save(DOC/'stage.json',decision)
 call([sys.executable,str(HERE.parent/'model-integration-20260909/publish.py'),ref(STAGE/'plan.json')['path'],'--receipt',str(LEASE),'--phase',BATCH]);call(['node',str(HERE/'xl-terrain-recovery-20261010-multi-native-solid-browser-v5.mjs'),'staged',ref(STAGE/'browser-config.json')['path']]);report=module('festival_browser_validator',HERE/'integrate.py').browser_verified(DOC/'staged-browser.json',UIDS);expected={(u,w,t) for u in RETAINED for w in [1280,390] for t in ['15:00','22:00']};assert {(v['uid'],v['width'],v['time']) for v in report['retainedNativeOwnViews']}==expected and all(v['active'] and v['visible'] and v['fullyFramed'] for v in report['retainedNativeOwnViews'])
 for view in report['views']:
  if 'time' in view:
   expected=set(config['nativeSupportUidsByModel'][view['uid']]);assert set(view['nativeSupports'])==expected;assert all(view['nativeSupports'][u]['active'] and view['nativeSupports'][u]['visible'] and view['nativeSupports'][u].get('declaredCandidateSupport') for u in ([] if view['uid']==PODIUM else [PODIUM]));assert all(not v['wanted'] or (v['active'] and v['visible']) for u,v in view['nativeSupports'].items() if u in RETAINED)
 for r in evidence:assert ref(ROOT/r['path'])==r
 recheck(HERE/'local'/BATCH/'identity-recheck-final');decision.update(stagedBrowser=ref(DOC/'staged-browser.json'),passed=True,failures=[],livePublicationRequired=True);save(DOC/'acceptance.json',decision);print(json.dumps(dict(stagedBrowserPassed=True,uids=sorted(UIDS),publication=False,newlyInstalled=0)),flush=True)
def main():
 p=argparse.ArgumentParser();p.add_argument('--owned',action='store_true');a=p.parse_args()
 if a.owned:
  from publication_lock import locked_publication
  with locked_publication(ROOT):owned()
  return
 assert not DOC.exists() and not STAGE.exists();forms=read(PHYSICAL/'neighbour-inputs.json.gz')['rows'];resources={(('building:' if r['building']['uid'].startswith('landsd/') else 'foreign-form:')+r['building']['uid']) for r in forms}|{'terrain-patch:'+u for u in UIDS}|{'terrain-surface:city/data/government-native-163705-0.json'};claim=reservations.claim('codex-tung-three-stage-'+str(uuid.uuid4()),sorted(resources),batch=BATCH,ttl=3600);assert claim['ok'];save(LEASE,json.loads(json.dumps(claim['reservation'],default=str)));subprocess.run([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(LEASE),'--',sys.executable,__file__,'--owned'],cwd=ROOT,check=True)
if __name__=='__main__':main()
