"""Candidate single-native surface: literal outside parent and source-bound interior."""
import importlib.util,copy,numpy as np
from run import ROOT,HERE,read,save,digest
from native_parent_child_flat_composition_20261010 import faces,bounds
from actual_native_parent_transition_v2_20261010 import transition,nondegenerate,rational
from exact_runtime_coplanar_consolidation_20261010 import consolidate
BATCH='government-xl-tung-sing-actual-parent-interior-composition-v2-20261010';DOC=ROOT/'docs/astra-city/government-import'/BATCH
PARENT=ROOT/'3d-viewer/city/data/government-native-163705-0.json'
CHILD=HERE/'local/government-xl-tung-sing-two-nested-original-physical-v3-20261010/government-native-53800-0.json'
SOURCE=DOC.parent/'government-xl-tung-sing-original-pair-source-tin-context-20261010/complete-original-source-tin.json.gz'
def module(name,file):
 s=importlib.util.spec_from_file_location(name,HERE/file);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def main():
 assert not DOC.exists();parent=read(PARENT);old_child=read(CHILD);bb=bounds(old_child);original=faces(parent);lo,hi=original[:,:,[0,2]].min(1),original[:,:,[0,2]].max(1);normal=np.cross(original[:,1]-original[:,0],original[:,2]-original[:,0]);nonzero=np.asarray([nondegenerate([rational(p) for p in t]) for t in original],dtype=bool);inside=(lo[:,0]>=bb[0])&(hi[:,0]<=bb[2])&(lo[:,1]>=bb[1])&(hi[:,1]<=bb[3])&nonzero;kept_ids=np.flatnonzero(~inside);retained,proof=consolidate(original[kept_ids]);proof['originalParentFaceIds']=kept_ids.tolist();save(DOC/'outside-exact-surface-certificates.json.gz',proof);print({'outsideOriginal':len(kept_ids),'outsideConsolidated':len(retained),'removedWhollyInteriorFaces':int(inside.sum())},flush=True)
 tin=read(SOURCE)
 for p,h in tin['sourceFileHashes'].items():assert digest((ROOT/p).read_bytes())==h,p
 second=module('tung_actual_parent_original_tin_decode','xl-second-pass.py');source=np.concatenate([second.terrain_triangles(ROOT/p) for p in tin['sourceFileHashes'] if p.endswith('.gltf')]);source=source[(source[:,:,0].max(1)>=bb[0])&(source[:,:,0].min(1)<=bb[2])&(source[:,:,2].max(1)>=bb[1])&(source[:,:,2].min(1)<=bb[3])];resolve=module('tung_actual_parent_grid_metadata','resolve-pass.py');sampler=resolve.terrain.fine.DemSampler(parent,rendered=True);child,childproof=transition(source,parent,bb,sampler);save(DOC/'complete-original-transition-dispositions.json.gz',childproof);combined=np.concatenate([retained,child]);out=copy.deepcopy(parent);out['id']='government-native-53800-0';out['meta']['targetUids']=sorted(set(parent['meta']['targetUids'])|{'landsd/53800:0','landsd/126434:0'});out['nativeMesh']={'position':combined.reshape(-1).tolist(),'index':list(range(len(combined)*3)),'source':{'verticalDatum':'HKPD','verticalScale':1,'policy':'Candidate exact consolidated literal outside original parent plus actual-native-parent-bounded source terrain child; complete independent seam/support/current-actor/runtime acceptance pending.'}};save(DOC/'candidate-single-native-original-surface.json',out)
 save(DOC/'diagnostic.json.gz',{'originalParentFacets':len(original),'removedWhollyInteriorOriginalFaceIds':np.flatnonzero(inside).tolist(),'retainedLiteralOriginalFaceIds':kept_ids.tolist(),'retainedExactlyEquivalentFacets':len(retained),'actualParentTransitionChildFacets':len(child),'combinedFacets':len(combined),'withinUnchanged100kBudget':len(combined)<=100000,'allOriginalOutsideFiniteSurfacesRetainedExactly':True,'allOriginalOutsideVerticalAndDegenerateFacetsRetained':True,'everyRemovedParentFacetEntirelyInsideChildRectangle':True,'childBounds':bb,'inputHashes':{str(p.relative_to(ROOT)):digest(p.read_bytes()) for p in [PARENT,CHILD,SOURCE,__import__('pathlib').Path(__file__)]}|tin['sourceFileHashes'],'candidateRuntimeTriangleSHA256':digest(combined.astype('<f8').tobytes()),'currentManifestSHA256':digest((ROOT/'3d-viewer/city/data/manifest.json').read_bytes()),'physicalAccepted':False,'qualification':'Terrain candidate only. Parent outside/boundary-spanning facets remain literal or exact finite-surface-equivalent; only complete interior parent facets removed. All seams, current original actor/foundation/foreign collision, finite coverage, runtime100k budget and guarded publisher/browser gates remain independent. No government building bytes or poses changed.'});print({'childFacets':len(child),'combinedFacets':len(combined),'budgetPass':len(combined)<=100000},flush=True)
if __name__=='__main__':main()
