"""Close original Ching Hin current numeric proof with exact archival bindings."""
import json,subprocess
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
from original_exact_replacement_routing_metadata_scope_20261010 import boundaries,verify_boundaries
BASE=ROOT/'docs/astra-city/government-import';BATCH='xl-terrain-recovery-20261010-ching-hin-source-closed-scope-v1';OUT=BASE/BATCH
PHYS=BASE/'government-xl-terrain-recovery-ching-hin-original-terrain-current-v3-20261010'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not OUT.exists();role=BASE/'xl-terrain-recovery-20261010-ching-hin-current-complete-role-v2';receipt=read(role/'result.json');typed=read(role/'typed-role.json.gz');assert typed['independentPhysicalChecksPassed']
 with connect() as c:c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(receipt['jobId'],)).fetchone()==('complete',receipt)
 dirs=[BASE/n for n in ['government-xl-terrain-recovery-ching-hin-original-terrain-current-v3-20261010','xl-terrain-recovery-20261010-ching-hin-exact-parent-boundary-proposal-v2','xl-terrain-recovery-20261010-ching-hin-complete-original-support-v1','xl-terrain-recovery-20261010-ching-hin-complete-finite-clearance-v1','xl-terrain-recovery-20261010-ching-hin-complete-paired-finite-clearance-v1','xl-terrain-recovery-20261010-ching-hin-finite-wall-grade-context-v1','xl-terrain-recovery-20261010-ching-hin-provider-wall-role-v1','xl-terrain-recovery-20261010-ching-hin-current-complete-role-v2']]
 paths={str(p.relative_to(ROOT)) for d in dirs for p in d.rglob('*') if p.is_file()};assert all(d.exists() for d in dirs)
 names=['xl-terrain-recovery-20261010-ching-hin-current-original-terrain-physical-v1.py','xl-terrain-recovery-20261010-ching-hin-current-original-terrain-physical-v2.py','xl-terrain-recovery-20261010-ching-hin-current-original-terrain-physical-v3.py','xl-terrain-recovery-20261010-ching-hin-exact-parent-boundary-proposal-v1.py','xl-terrain-recovery-20261010-ching-hin-exact-parent-boundary-proposal-v2.py','xl-terrain-recovery-20261010-ching-hin-current-complete-role-v1.py','xl-terrain-recovery-20261010-ching-hin-current-complete-role-v2.py','xl-terrain-recovery-20261010-ching-hin-provider-wall-role-v1.py','xl-terrain-recovery-20261010-ching-hin-finite-wall-grade-context-v1.py','test_ching_hin_complete_current_role_actual_20261010.py','original_unchanged_adjacent_terrain_boundary_20261010.py','test_original_unchanged_adjacent_terrain_boundary_20261010.py','test_original_unchanged_adjacent_terrain_boundary_actual_20261010.py','original_bound_facet_wall_context_20261010.py','test_original_bound_facet_wall_context_20261010.py','original_exact_replacement_routing_metadata_scope_20261010.py','test_original_exact_replacement_routing_metadata_scope_actual_20261010.py'];paths.update(str((HERE/n).relative_to(ROOT)) for n in names);paths.add(str(Path(__file__).relative_to(ROOT)))
 aliases=list(read(BASE/'xl-terrain-recovery-20261010-man-oi-stage-live-closure-v1/closed-scope.json')['historicalManifestAliases']);leaf=set(read(BASE/'xl-terrain-recovery-20261010-man-oi-stage-live-closure-v1/closed-scope.json')['metadataLeafPaths'])
 current=ROOT/'3d-viewer/city/data/manifest.json';raw=current.read_bytes();assert digest(raw)==typed['currentManifest']['sha256'];archive=OUT/'acceptance-manifest.json';archive.parent.mkdir(parents=True,exist_ok=True);archive.write_bytes(raw);paths.add(str(archive.relative_to(ROOT)));aliases.append(dict(originalPath='3d-viewer/city/data/manifest.json',sha256=digest(raw),archive=ref(archive)));leaf.add(str(archive.relative_to(ROOT)))
 manifest=read(archive);preflight=read(PHYS/'current-source-terrain-preflight.json');candidate_ref=ref(PHYS/'terrain-candidates.json');seam_ref=ref(PHYS/'exact-unchanged-adjacent-terrain-seams.json');c=read(ROOT/candidate_ref['path']);seams=read(ROOT/seam_ref['path']);kwargs=dict(candidate_ref=candidate_ref,seam_ref=seam_ref,manifest_ref=typed['currentManifest'],actual_assets={r['entry']['url']:dict(ref=r['asset'],data=read(ROOT/r['asset']['path'])) for r in preflight['completeCurrentTerrainRouting']},proposal=read(ROOT/c[0]['path']))
 for v in kwargs['actual_assets'].values():assert ref(ROOT/v['ref']['path'])==v['ref']
 pointers=boundaries(preflight,manifest,c,seams,**kwargs);verify_boundaries(preflight,manifest,c,seams,pointers,**kwargs);pointer_rows=[dict(path=str((PHYS/'current-source-terrain-preflight.json').relative_to(ROOT)),documentSHA256=ref(PHYS/'current-source-terrain-preflight.json')['sha256'],boundary=p) for p in pointers]
 leaf.update('3d-viewer/'+u for u in manifest['officialModelCatalogues']);leaf.update('3d-viewer/'+e['url'] for e in manifest['terrainPatches'])
 # The current routing assets remain exact-byte inputs and full mesh/bounds
 # proofs. Their unrelated embedded historic acquisition caches are archival.
 save(OUT/'closed-scope.json',dict(closedPaths=sorted(paths),closedExplicitPaths=sorted(paths),presentFileBindings=[ref(ROOT/p) for p in sorted(paths)],historicalManifestAliases=aliases,metadataLeafPaths=sorted(leaf),metadataLeafJsonPointers=pointer_rows,currentRoleNeon=receipt['jobId'],sourceGeometryChanges=0,terrainProposalChanged=True,terrainBoundaryValuesRestoredFromExactCurrentParent=True,stageAndLiveExcluded=True,qualification='Complete16555original/rendered faces,963parts962contacts,61exact grade interfaces, all25forms/five native originals, provider/identity/current ground/foundation/runtime remain fully bound. Current routing JSON assets are bytebound and their complete geometry/bounds/seam replayed; only their unrelated historical acquisition caches and authoritative manifest source metadata are archival. Original source/TIN/candidate/ground numeric dependencies remain recursive. Prior terrain seam differences preserved; candidate parent-boundary packed values changed explicitly, interior/index bytes did not. No installed credit.'))
 print(dict(paths=len(paths),pointers=len(pointer_rows),roleNeon=receipt['jobId']),flush=True)
if __name__=='__main__':main()
