"""Current full-source graph replay and literal original/runtime mounted visual roles.

No structural bridge/root or physical acceptance is granted by visual mounts.
"""
import importlib.util,json,numpy as np
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from xl_source_stream_binding_20261009 import source_stream_binding
from original_multi_actor_support_graph_20261009 import verify as verify_graph
from tung_sing_original_single_end_visual_sleeves_v2_20261010 import verify_current_visual_roles
BASE=ROOT/'docs/astra-city/government-import';BATCH='government-xl-tung-sing-three-original-current-rendered-visual-roles-v3-20261010';DOC=BASE/BATCH;PHYSICAL=BASE/'government-xl-tung-sing-three-original-literal-parent-physical-v2-20261010';GRAPH=BASE/'government-xl-tung-sing-three-original-current-root-graph-v3-20261010';RUNTIME=HERE/'local'/PHYSICAL.name/'runtime-geometry.json.gz'
def canonical(v):return digest(json.dumps(v,sort_keys=True,separators=(',',':'),allow_nan=False).encode())
def main():
 assert not DOC.exists();selection=read(PHYSICAL/'selection.json.gz');manifest=ROOT/'3d-viewer/city/data/manifest.json';assert digest(manifest.read_bytes())==selection['manifestSHA256'];receipt=read(PHYSICAL/'result.json')
 with connect() as c:
  c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(receipt['jobId'],)).fetchone()==('complete',receipt)
 for ref in receipt['evidenceRefs']:assert digest((ROOT/ref['path']).read_bytes())==ref['sha256']
 captured=read(GRAPH/'diagnostic.json.gz');assert captured['manifestSHA256']==selection['manifestSHA256'] and captured['freshCurrentLiveBindingAccepted']
 for path,pinned in captured['inputHashes'].items():assert digest((ROOT/path).read_bytes())==pinned,path
 rows={r['uid']:r for r in selection['rows']};worlds={};streams={};assets=[]
 for actor in captured['completeOriginalActors']:
  r=rows[actor['uid']];asset=ROOT/r['candidate']['path'];raw=asset.read_bytes();assert digest(raw)==r['sourceSHA256']==actor['sourceSHA256'];worlds[r['uid']]=decode_original_world_triangles(raw);streams[r['uid']]=source_stream_binding(raw);assets.append(asset);assert digest(worlds[r['uid']].tobytes())==actor['originalWorldTrianglesSHA256'] and canonical(streams[r['uid']])==actor['originalStreamBindingSHA256']
 alltri=np.concatenate([worlds[a['uid']] for a in captured['completeOriginalActors']]);graph=verify_graph(alltri,captured['completeOriginalActors'],captured['completeOriginalComponents'],captured['currentOriginalGroundInterfaces'],captured['contactWitnesses'],expected_binding=captured['binding'],current_binding=captured['binding']);assert canonical(graph)==canonical(captured['completeCurrentOriginalGraph'])
 uid='landsd/53800:0';runtime=next(r for r in read(RUNTIME)['rows'] if r['uid']==uid);world=np.asarray(runtime['position']).reshape(-1,3)[np.asarray(runtime['index']).reshape(-1,3)];ground=np.asarray(runtime['drawnGroundGeometry']).reshape(-1,3,3)
 binding={'currentManifestSHA256':selection['manifestSHA256'],'completeCurrentPhysicalSHA256':digest((PHYSICAL/'result.json').read_bytes()),'completeCurrentForeignActorScopeSHA256':digest((PHYSICAL/'neighbour-inputs.json.gz').read_bytes()),'completeProviderRootAndStreamsSHA256':canonical(streams[uid]),'completeOriginalWorldSHA256':digest(worlds[uid].tobytes()),'completeActualRenderedWorldSHA256':digest(world.tobytes()),'completeActualDrawnGroundSHA256':digest(ground.tobytes()),'completeCurrentRootedGraphSHA256':canonical(graph)}
 roles=verify_current_visual_roles(worlds[uid],world,ground,graph,streams[uid],expected_binding=binding,current_binding=binding);assert roles['typedOriginalVisualRoleAccepted'];save(DOC/'diagnostic.json.gz',{'manifestSHA256':selection['manifestSHA256'],'binding':binding,'completeReplayedCurrentOriginalGraph':graph,'completeLiteralCurrentVisualRoles':roles,'completeOriginalFaces':12751,'completeOriginalParts':387,'ordinarySourceParts':385,'nonstructuralVisualSourceParts':[343,344],'rawGraphFailureRetained':graph['reasons'],'sourceGeometryChanges':0,'physicalAccepted':False,'installationApproved':False})
 (DOC/'README.md').write_text('Complete three untouched originals retain12751 faces/387 components. Current graph replays every positive finite source contact and independently checked fullrim platform0/tower361 footings.385 parts have actual current ground paths;343/344 stay raw graph failures and get no root/bridge credit. Each is a complete8-face horizontal sleeve with a complete4-edge authored mounting opening within unchanged0.1m exact finite host band. Complete source root/attributes/hierarchy and literal actual-rendered world streams are independently fixed; old exact-equality failure retained, no coordinate tolerance supplies credit. All16 original and literal rendered facets and both rendered mounting loops are independently checked. Source geometry changes zero. This is visual role evidence only; complete ordinary wall/foreign/clearance/foundation/runtime/browser gates remain independent.\n')
 refs=[Path(__file__),manifest,RUNTIME,PHYSICAL/'result.json',PHYSICAL/'selection.json.gz',PHYSICAL/'neighbour-inputs.json.gz',GRAPH/'diagnostic.json.gz',HERE/'tung_sing_original_single_end_visual_sleeves_v2_20261010.py',HERE/'test_tung_sing_original_single_end_visual_sleeves_v2_20261010.py',HERE/'tung_sing_original_single_end_visual_sleeves_20261010.py',HERE/'test_tung_sing_original_single_end_visual_sleeves_20261010.py',HERE/'exact_original_edge_finite_facade_distance_band_v2_20261010.py',HERE/'exact_original_face_conservative_clearance_v4_20261010.py',HERE/'original_multi_actor_support_graph_20261009.py',HERE/'xl_source_stream_binding_20261009.py',HERE/'exact_packed_world_geometry_20261009.py',*assets]+[ROOT/path for path in captured['inputHashes']]
 assert digest(manifest.read_bytes())==selection['manifestSHA256'];s=importlib.util.spec_from_file_location('visual_role_fence',HERE/'xl-popcorn-source-investigations-checkpoints-20261009.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.freeze(BATCH,'complete-current-literal-source-rendered-single-mounted-visual-roles-v2',refs,{'uids':sorted(rows),'typedOriginalVisualRoleAccepted':True,'completeOriginalFaces':12751,'completeOriginalComponents':387,'sourceOrdinaryGroundPathParts':385,'visualOnlyParts':[343,344],'structuralVisualRootOrBridgeCredit':False,'sourceGeometryChanges':0,'physicalAccepted':False,'installationApproved':False});print({'visualRolesAccepted':True,'ordinaryRootedParts':385,'sourceVisualParts':2,'physicalAccepted':False},flush=True)
if __name__=='__main__':main()
