"""Stage two untouched Caine Road originals; root owns later atomic publication."""
import argparse,importlib.util,json,os,shutil,subprocess,sys,uuid
from pathlib import Path
from run import ROOT,HERE,read,save,digest,reservations,connect
from dependency_preflight import from_catalogues
UIDS={'landsd/101781:0','landsd/268032:0'}
PHYSICAL=ROOT/'docs/astra-city/government-import/government-xl-terrain-recovery-unnamed-268032-nested-original-pair-current-physical-v5-20261010'
ROLE=ROOT/'docs/astra-city/government-import/government-xl-terrain-recovery-caine-road-current-complete-visual-role-v2-20261010'
BATCH='government-xl-terrain-recovery-caine-road-two-typed-stage-v2-20261010';DOC=ROOT/'docs/astra-city/government-import'/BATCH;STAGE=HERE/'accepted'/BATCH;LEASE=HERE/'local'/BATCH/'install-reservation.json'
def ref(p):return dict(path=str(Path(p).relative_to(ROOT)),sha256=digest(Path(p).read_bytes()))
def module(name,path):
 spec=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);return m
def recheck(local):
 receipt=read(ROLE/'result.json');assert read(ROLE/'neon-sync.json')==dict(jobId=receipt['jobId'],resultVerified=True)
 with connect() as c:c.execute('SET TRANSACTION READ ONLY');assert c.execute('SELECT status,result FROM astra_modelling.jobs WHERE id=%s',(receipt['jobId'],)).fetchone()==('complete',receipt)
 for r in receipt['evidenceRefs']:assert ref(ROOT/r['path'])==r
 m=module('caine_road_complete_current_original_roles',HERE/'xl-terrain-recovery-20261010-caine-road-current-complete-visual-role-v2.py');role=json.loads(json.dumps(m.recheck()));assert role==read(ROLE/'typed-role.json.gz') and role['currentTypedPhysicalAccepted'] and not role['reasons'] and role['allComponentsAccounted'];assert role['completeOriginalFaces']==10947 and role['completeOriginalComponents']==204 and role['completeCurrentNeighbourForms']==18 and role['allCurrentRetainedNativeChecksPassed'] is True
 rows=read(PHYSICAL/'selection.json.gz')['rows'];assert {r['uid'] for r in rows}==UIDS
 return rows,role['completeCurrentSourceIdentities'],role
PLACEMENT='Two untouched government Caine Road originals: podium101781 and upper building268032. All10947 original and literal facets have independently proved strict finite clearance; all204 original components are accounted,202 structural components independently rooted through genuine podium roots and293 exact original contacts. Two precisely pinned source-authored cantilever/slanted visual details have complete back/end mounting within existing .1m finite host band and provide no structural root or bridge. All18 current forms and all10 retained native originals pass independent before/after whole-source checks. The explicit terrain-only proposal restores literal current parent surface beneath two dyadically covered disjoint foreign footprints; all nine original parent children and grid remain unchanged. Original geometry/root/elevation/streams and all raw failures remain preserved; zero AI geometry.'

def owned():
 def owns():assert reservations.owns(read(LEASE))
 def call(cmd):subprocess.run(cmd,cwd=ROOT,check=True,env={**os.environ,'CHROME_PATH':'/opt/google/chrome/chrome'});owns()
 owns();rows,identities,role=recheck(HERE/'local'/BATCH/'identity-recheck');save(DOC/'identity-publication-recheck.json',identities);save(DOC/'typed-role-publication-recheck.json.gz',role);podium=next(r for r in rows if r['uid']=='landsd/101781:0');dependency=dict(uid=podium['uid'],csuid=podium['source']['building']['buildingCSUID'],sha256=podium['sourceSHA256'],state='candidate');entries=[]
 for row in rows:
  e=dict(row['candidate']['entry']);assert not e.get('suppressesBuildingUids') and not e.get('footprintScope') and not e.get('supportDependencies');e.update(priority='landmark',proceduralWindows=False,sourceIdentityReviewed=True,sourceIdentityReviewUsedAI=True,identityReviewApproved=True,placementReviewed=True,publicationApproved=True,supportDependencies=[] if row['uid']==podium['uid'] else [dependency],placementReview=PLACEMENT);asset=STAGE/e['asset'];asset.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(ROOT/row['candidate']['path'],asset);assert ref(asset)['sha256']==e['sha256'];entries.append(e)
 entries.sort(key=lambda e:e['uid']!=podium['uid']);catalogue=read(HERE/'local'/PHYSICAL.name/'catalogue.json');catalogue.update(models=entries,counts={'packedModels':2},area='Caine Road complete unchanged original podium and upper body');save(STAGE/'catalogue.json',catalogue);save(STAGE/'catalogue-index.json',dict(models=2,catalogues=['catalogue.json']));forms=read(PHYSICAL/'neighbour-inputs.json.gz')['rows'];sourceforms=[r['building'] for r in forms if r['building']['uid'] in UIDS];assert {r['uid'] for r in sourceforms}==UIDS;save(STAGE/'source-forms.json',sourceforms)
 candidates=read(PHYSICAL/'terrain-candidates.json');assert len(candidates)==1;c=candidates[0];assert set(c['uids'])==UIDS and c.get('replaces') and not c.get('replacesMany') and ref(ROOT/c['path'])['sha256']==c['sha256'];patch=STAGE/Path(c['path']).name;shutil.copyfile(ROOT/c['path'],patch);p=read(patch);parent=read(ROOT/'3d-viewer'/c['replaces']['url']);assert not p.get('nativeMesh') and len(p['patches'])==10 and len(parent['patches'])==9 and p['patches'][-1]['meta']['targetUids']==['landsd/101781:0','landsd/268032:0']
 for old,new in zip(parent['patches'],p['patches'][:9]):
  for k in ['elev','renderedElev']:assert old.get(k)==new.get(k)
  for k in ['position','index']:assert old.get('nativeMesh',{}).get(k)==new.get('nativeMesh',{}).get(k)
 for k in ['w','h','cell','coarseCells','elev','renderedElev','vegetation','hydro']:assert p.get(k)==parent.get(k)
 assert p['meta']['georef']==parent['meta']['georef']
 terrain=dict(source=ref(patch)['path'],sha256=ref(patch)['sha256'],destination='city/data/terrain-government-xl-caine-road-original-pair-installed-v2-20261010.json',resolution=p['cell'],area=catalogue['area']+' nested indexed government terrain and explicit dyadic foreign-parent preservation')
 NATIVE=ROOT/'docs/astra-city/government-import/xl-terrain-recovery-20261010-caine-road-complete-retained-native-v1';native=read(NATIVE/'native-neighbour-checks.json');retained=read(NATIVE/'retained-scope.json')['retainedNativeUids'];replacement=dict(c['replaces']);replacement['retainedUids']=sorted({u for child in parent['patches'] for u in child['meta']['targetUids']});assert set(replacement['retainedUids'])==set(retained) and len(retained)==10 and all(r['passed'] for r in native['rows']) and role['completeCurrentRetainedNativeScope']==read(NATIVE/'retained-scope.json')
 assert replacement['url'] in {r['url'] for r in read(ROOT/'3d-viewer/city/data/manifest.json')['terrainPatches']}
 review=dict(status='approved-for-integration',supersededURL=replacement['url'],supersededSHA256=replacement['sha256'],replacementSHA256=terrain['sha256'],sourceGeometryChanged=False,terrainProposalChanged=True,aiCalls=0,modelGeometryChanges=0,retainedUids=replacement['retainedUids'],replacementTargetUids=sorted({u for child in p['patches'] for u in child['meta']['targetUids']}),fullMeshCheck=ref(NATIVE/'native-neighbour-checks.json'),allCurrentRetainedNativeScope=ref(NATIVE/'retained-scope.json'),allNineOriginalChildGeometryExactlyPreserved=True,currentGridExactlyPreserved=True,completeForeignDyadicParentPreservation=ref(PHYSICAL/'complete-disjoint-foreign-parent-preservation.json'))
 save(DOC/'native-replacement-review.json',review);terrain.update(replaces=replacement,nativeReview=ref(DOC/'native-replacement-review.json'))
 destination='city/data/official-models/'+BATCH+'/catalogue.json';save(STAGE/'plan.json',dict(areas=[dict(area=catalogue['area'],catalogue=ref(STAGE/'catalogue.json')['path'],destination=destination)],topLevelTerrainPatches=[terrain]));deps=from_catalogues(ROOT/'3d-viewer/city/data/manifest.json',[STAGE/'catalogue.json']);assert not any(r['blockers'] for r in deps['rows']);save(DOC/'dependencies.json',deps)
 assembly=[[min(e['worldBounds'][0][i] for e in entries) for i in range(3)],[max(e['worldBounds'][1][i] for e in entries) for i in range(3)]];config=dict(captureDirectionByModel={u:[-.65,.75,-.5] for u in UIDS},stage=str(STAGE.relative_to(ROOT))+'/',doc=str(DOC.relative_to(ROOT))+'/',catalogueURL=destination,terrain=[terrain],fitBox=True,captureBoundsByModel={e['uid']:e['worldBounds'] for e in entries},captureBoundsByViewport={'1280':{e['uid']:assembly for e in entries}},browserUids=sorted(UIDS),failureTestUids=sorted(UIDS),nativeSupportUidsByModel={'landsd/101781:0':retained,'landsd/268032:0':retained+['landsd/101781:0']});save(STAGE/'browser-config.json',config)
 evidence=[ref(q) for q in [Path(__file__),PHYSICAL/'result.json',ROLE/'result.json',ROLE/'typed-role.json.gz',DOC/'identity-publication-recheck.json',DOC/'typed-role-publication-recheck.json.gz',DOC/'dependencies.json',DOC/'native-replacement-review.json',NATIVE/'result.json',NATIVE/'retained-scope.json',NATIVE/'native-neighbour-checks.json',STAGE/'catalogue.json',STAGE/'plan.json',STAGE/'browser-config.json',HERE/'xl-terrain-recovery-20261010-caine-road-current-complete-visual-role-v2.py',HERE/'xl-terrain-recovery-20261010-multi-native-solid-browser-v5.mjs']];decision=dict(batch=BATCH,uids=sorted(UIDS),sourceSHA256s={r['uid']:r['sourceSHA256'] for r in rows},manifestSHA256=role['currentManifest']['sha256'],checksPassed=True,publication=False,newlyInstalled=0,modelGeometryChanges=0,terrainProposalGeometryChanged=True,scriptExternalAICalls=0,sourceEvidenceInterpretationUsedAI=True,aiGeometryModelling=False,evidenceRefs=evidence);save(DOC/'stage.json',decision)
 call([sys.executable,str(HERE.parent/'model-integration-20260909/publish.py'),ref(STAGE/'plan.json')['path'],'--receipt',str(LEASE),'--phase',BATCH]);call(['node',str(HERE/'xl-terrain-recovery-20261010-multi-native-solid-browser-v5.mjs'),'staged',ref(STAGE/'browser-config.json')['path']]);report=module('caine_road_browser_validator',HERE/'integrate.py').browser_verified(DOC/'staged-browser.json',UIDS);assert len(report['retainedNativeOwnViews'])==4*len(retained) and {v['uid'] for v in report['retainedNativeOwnViews']}==set(retained)
 for view in report['views']:
  if 'time' in view:
   expected=set(config['nativeSupportUidsByModel'][view['uid']]);assert set(view['nativeSupports'])==expected;assert all(v['active'] and v['visible'] for v in view['nativeSupports'].values() if v.get('wanted') or v.get('declaredCandidateSupport'));assert all(view['nativeSupports'][u].get('declaredCandidateSupport') for u in expected&UIDS)
 for r in evidence:assert ref(ROOT/r['path'])==r
 recheck(HERE/'local'/BATCH/'identity-recheck-final');decision.update(stagedBrowser=ref(DOC/'staged-browser.json'),passed=True,failures=[],livePublicationRequired=True);save(DOC/'acceptance.json',decision);print(json.dumps(dict(stagedBrowserPassed=True,uids=sorted(UIDS),publication=False,newlyInstalled=0)),flush=True)
def main():
 p=argparse.ArgumentParser();p.add_argument('--owned',action='store_true');a=p.parse_args()
 if a.owned:
  from publication_lock import locked_publication
  with locked_publication(ROOT):owned()
  return
 assert not DOC.exists() and not STAGE.exists();forms=read(PHYSICAL/'neighbour-inputs.json.gz')['rows'];retained=read(ROOT/'docs/astra-city/government-import/xl-terrain-recovery-20261010-caine-road-complete-retained-native-v1/retained-scope.json')['retainedNativeUids'];resources={(('building:' if r['building']['uid'].startswith('landsd/') else 'source-form:')+r['building']['uid']) for r in forms}|{'building:'+u for u in retained}|{'terrain-patch:'+u for u in UIDS}|{'terrain-surface:'+read(PHYSICAL/'terrain-candidates.json')[0]['replaces']['url']};claim=reservations.claim('codex-caine-road-two-stage-'+str(uuid.uuid4()),sorted(resources),batch=BATCH,ttl=3600);assert claim['ok'],claim;save(LEASE,json.loads(json.dumps(claim['reservation'],default=str)));subprocess.run([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(LEASE),'--ttl','3600','--',sys.executable,__file__,'--owned'],cwd=ROOT,check=True)
if __name__=='__main__':main()
