"""All7731 untouched podium faces vs complete actual drawn ground/foreign scope."""
import importlib.util,json
import numpy as np,shapely
from run import ROOT,HERE,read,save,digest
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from original_face_ground_crossing_v2_20261009 import face_ground_context
from original_degenerate_ground_context_20261009 import degenerate_ground_context
from source_closed_components import components
from yoho_eight_related_original_podium_identity_20261009 import UID,RELATED,PODIUM_SHA,ring_poly
from yoho_eight_current_bound_identity_20261009 import DOC as INPUT,verify_receipt,checked_provider
BATCH='government-xl-yoho-original-podium-current-ground-20261010';DOC=ROOT/'docs/astra-city/government-import'/BATCH
CURRENT=DOC.parent/'government-xl-yoho-eight-actual-current-podium-support-20261009'
def main():
 assert not DOC.exists();verify_receipt(read(INPUT/'result.json'));x=read(CURRENT/'complete-current-rendered-podium-inputs.json.gz')
 for p,h in x['inputHashes'].items():assert digest((ROOT/p).read_bytes())==h,p
 source=ROOT/read(INPUT/'current-inputs.json.gz')['podiumOriginalPath'];raw=source.read_bytes();assert digest(raw)==PODIUM_SHA;t=decode_original_world_triangles(raw)
 ground=np.asarray(x['drawnGroundGeometry']['position'],float).reshape(-1,3)[np.asarray(x['drawnGroundGeometry']['index']).reshape(-1,3)];assert digest(ground.astype('<f8').tobytes())==x['drawnGroundGeometry']['worldTriangleSHA256']
 n=np.cross(t[:,1]-t[:,0],t[:,2]-t[:,0]);length=np.linalg.norm(n,axis=1);ratios=np.divide(n[:,1],length,out=np.zeros(len(t)),where=length>0);polys=shapely.polygons(ground[:,:,[0,2]]);keep=shapely.area(polys)>1e-10;ground,polys=ground[keep],polys[keep];tree=shapely.STRtree(polys);contexts=[]
 for i,face in enumerate(t):
  c=face_ground_context(face,ground,polys,tree) if length[i]>0 else degenerate_ground_context(face,ground,polys,tree);contexts.append(dict(c,sourceFace=i,normalYRatio=float(ratios[i]) if length[i]>0 else None))
  if i%500==0:save(DOC/'progress.json',{'facesChecked':i,'completeOriginalFaces':len(t),'geometryChanges':0});print({'facesChecked':i,'completeOriginalFaces':len(t)},flush=True)
 parts=components(t)['components'];save(DOC/'complete-original-podium-footing-inputs.json.gz',{'terrain':{'position':ground.reshape(-1).tolist(),'index':list(range(len(ground)*3)),'worldTriangleSHA256':digest(ground.astype('<f8').tobytes())},'rows':[{'uid':RELATED,'sourceSHA256':PODIUM_SHA,'worldTriangleSHA256':digest(t.astype('<f8').tobytes()),'wholeOriginalFaces':len(t),'parts':[{'component':i,'originalFaceIds':p['faceIndices'],'position':t[p['faceIndices']].reshape(-1).tolist(),'index':list(range(p['triangles']*3)),'bottomHKPD':float(t[p['faceIndices'],:,1].min()),'worldBounds':[t[p['faceIndices']].min(axis=(0,1)).tolist(),t[p['faceIndices']].max(axis=(0,1)).tolist()]} for i,p in enumerate(parts)]}]})
 s=importlib.util.spec_from_file_location('yoho_original_pair_current_foreign',HERE/'xl-final-script-pass.py');final=importlib.util.module_from_spec(s);s.loader.exec_module(final);tower=x['rows'][0];a=np.asarray(tower['position'],float).reshape(-1,3)[np.asarray(tower['index']).reshape(-1,3)];alltri=np.concatenate([a,t]);lo,hi=alltri.min(axis=(0,1)),alltri.max(axis=(0,1));forms=final.load_forms([lo[0]-2,lo[2]-2,hi[0]+2,hi[2]+2]);foreign=shapely.union_all([ring_poly(b['rings']) for b,_,_ in forms if b['uid'] not in [UID,RELATED]]);primary=checked_provider('exact-current-primary');projection=shapely.union_all(shapely.polygons(alltri[:,:,[0,2]]));pair_spatial=[]
 for basis,targets in [('current',shapely.union_all([ring_poly(b['rings']) for b,_,_ in forms if b['uid'] in [UID,RELATED]])),('primary',shapely.union_all([ring_poly(f['geometry']['rings'],primary=True) for f in primary]))]:
  pair_spatial.append({'basis':basis,'completePairTargetCoverage':projection.intersection(targets).area/targets.area,'completePairMaximumExtentM':float(shapely.distance(shapely.points(alltri[:,:,[0,2]].reshape(-1,2)),targets).max()),'completePairForeignExcessM2':projection.difference(targets).intersection(foreign).area,'completePodiumTargetCoverage':shapely.union_all(shapely.polygons(t[:,:,[0,2]])).intersection(ring_poly(next(b['rings'] for b,_,_ in forms if b['uid']==RELATED)) if basis=='current' else ring_poly(next(f['geometry']['rings'] for f in primary if f['attributes']['BuildingCSUID']=='2187833636P20050609'),primary=True)).area/(ring_poly(next(b['rings'] for b,_,_ in forms if b['uid']==RELATED)) if basis=='current' else ring_poly(next(f['geometry']['rings'] for f in primary if f['attributes']['BuildingCSUID']=='2187833636P20050609'),primary=True)).area})
 affected=[i for i,c in enumerate(contexts) if c['minimum'] and c['minimum']['minimumGapM']<-.5];upward=[i for i,c in enumerate(contexts) if ratios[i]>.25 and c['minimum']];summary={'uid':RELATED,'completeOriginalFaces':len(t),'completeOriginalComponents':len(parts),'completeCurrentGroundFaces':len(ground),'uncoveredOriginalFaces':sum(not c['groundProjectionCovered'] for c in contexts),'affectedFaces':len(affected),'affectedUpwardFaces':len(set(affected)&set(upward)),'upwardContinuousMinimumGapM':min(contexts[i]['minimum']['minimumGapM'] for i in upward),'sourcePairSpatial':pair_spatial,'physicalAccepted':False,'sourceGeometryChanges':0,'currentActorChanges':0};save(DOC/'diagnostic.json.gz',{'summary':summary,'completeFaceContexts':contexts,'completeComponents':parts,'allCurrentForms':[b for b,_,_ in forms],'inputHashes':{**x['inputHashes'],str(source.relative_to(ROOT)):digest(raw),str((CURRENT/'complete-current-rendered-podium-inputs.json.gz').relative_to(ROOT)):digest((CURRENT/'complete-current-rendered-podium-inputs.json.gz').read_bytes()),**{'3d-viewer/'+u:digest((ROOT/'3d-viewer'/u).read_bytes()) for _,_,u in forms}},'qualification':'Every unchanged original podium surface measured continuously against complete current drawn ground. Complete pair own/current primary footprint and every other current actor retained; no grouping/exemption or support/physical credit. Original mainbody42interfaces and143 detached parts remain independent.'});save(DOC/'summary.json',summary);print(json.dumps(summary),flush=True)
if __name__=='__main__':main()
