"""Immutable fixed295 historical sources: exact body census, no acceptance."""
import json
from pathlib import Path
from run import ROOT,HERE,read,save,digest
from exact_packed_world_geometry_20261009 import decode_original_world_triangles
from exact_original_shared_edge_component_census_v2_20261011 import census
B=ROOT/'docs/astra-city/government-import';DOC=B/'government-xl-fixed295-simple-source-support-nomination-census-v1-20261011';INVENTORY=B/'government-xl-parkview-block17-unchanged-installed-v1-20261011/full-xl-current-count.json';RANK=B/'xl-terrain-recovery-20261010-complete-component-route-candidate-rank-v1/ranking.json';DISP=B/'government-xl-current-320-blocker-families-20261009/dispositions.json.gz'
UIDS=['landsd/338946:0','landsd/144536:0','landsd/79099:0','landsd/253874:0','landsd/198440:0','landsd/117814:0']
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def main():
 assert not DOC.exists();inv=read(INVENTORY);assert inv['counts']==dict(installedVerified=226,remaining=295,total=521);held={r['uid']:r for r in inv['rows']if not r['installedVerified']};rank=read(RANK);disp={r['uid']:r for r in read(DISP)['rows']};refs=[ref(p)for p in [Path(__file__),INVENTORY,RANK,DISP,HERE/'exact_packed_world_geometry_20261009.py',HERE/'exact_original_shared_edge_component_census_v2_20261011.py',HERE/'test_exact_original_shared_edge_component_census_v2_20261011.py']];rows=[]
 for uid in UIDS:
  r=next(r for r in rank['rows']if r['uid']==uid);assert uid in held and held[uid]['indexedSourceSHA256']==r['sourceSHA256']==disp[uid]['sourceSHA256']and not r['historicalOtherReasons'];sel=next(ROOT/e['path']for e in r['evidenceRefs']if e['path'].endswith('/selection.json.gz'));selection=read(sel);s=next(s for s in selection['rows']if s['uid']==uid);asset=ROOT/s['candidate']['path'];assert digest(asset.read_bytes())==r['sourceSHA256'];tri=decode_original_world_triangles(asset.read_bytes());assert len(tri)==r['triangles'];c=census(tri,list(range(len(tri))));sizes=sorted([len(x)for x in c['sharedEdgeConnectedComponents']],reverse=True);refs.extend([ref(sel),ref(asset)]+[e for e in r['evidenceRefs']]);rows.append(dict(uid=uid,name=r['label'],sourceSHA256=r['sourceSHA256'],nativeProviderModel=s['native']['model'],originalBuildingRecord=s['source']['building'],sourceAsset=ref(asset),wholeOriginalFaces=len(tri),completeExactOriginalBodyCensus=c,genuineBodies=len(sizes),largestGenuineBodyFaces=sizes[0],otherGenuineBodyFaces=sum(sizes[1:]),largestBodyShare=sizes[0]/len(tri),historicalOnlyOrdinaryReasons=disp[uid]['reasons'],historicalSampledMinimumRimGapM=r['sampledMinimumRimGapM'],historicalIdentityRecord='cached named form/provider association; no identity blocker in disposition',historicalStrictFoundationPass=r['historicalStrictFoundationPass'],requiresActualOriginalSupport=True,currentAcceptance=False))
 for r in refs:assert ref(ROOT/r['path'])==r
 save(DOC/'diagnostic.json.gz',dict(sourceOnly=True,currentAcceptance=False,installationApproved=False,solverInvoked=False,meshCreated=False,immutableFixedInventory=ref(INVENTORY),historicalFixedManifestSHA256=inv['manifestSHA256'],notFreshCurrentCapture=True,completeBoundedSixSourceInventories=True,rows=rows,evidenceRefs=refs,qualification='Fixed post17 remaining295 membership/sourceSHA plus six complete unchanged source shared-edge body inventories. Historical ordinary-only warnings/sampled clearance/strict foundation and named association are nomination hints,not current acceptance/undisputed entire-source identity or structural support. Bodies are not solids,roots or mounting; partialedge contacts/open visual obligations still need exact finite proof. No mutable currentcapture, native source rejection waiver, scene/source changes or install credit.'))
 print(json.dumps([dict(uid=r['uid'],name=r['name'],faces=r['wholeOriginalFaces'],bodies=r['genuineBodies'],largestBodyFaces=r['largestGenuineBodyFaces'],otherFaces=r['otherGenuineBodyFaces'])for r in rows]),flush=True)
if __name__=='__main__':main()
