"""Two source-only nominations; cached membership and full body obligations, no acceptance."""
import importlib.util,json
from pathlib import Path
from run import ROOT,HERE,read,save,digest,connect
B=ROOT/'docs/astra-city/government-import';BATCH='government-xl-fixed295-simple-source-support-nomination-census-v1-20261011';DOC=B/BATCH
RANK=B/'xl-terrain-recovery-20261010-next-current-native-cap-source-only-ranking-v1/diagnostic.json.gz'
INV=B/'government-xl-parkview-block17-unchanged-installed-v1-20261011/full-xl-current-count.json'
GRAPH=B/'xl-terrain-recovery-20261009-255543-historical-ordinary-support-v1/diagnostic.json.gz'
ELM=B/'government-xl-elm-tree-podium-physical-20261007'
def ref(p):return dict(path=str(p.relative_to(ROOT)),sha256=digest(p.read_bytes()))
def state():
 with connect()as c:
  c.execute('SET TRANSACTION READ ONLY');return c.execute("SELECT row_to_json(t) FROM astra_modelling.model_reviews t WHERE uid=ANY(%s)",(['landsd/255543:0','landsd/253874:0','landsd/258892:0'],)).fetchall()
def main():
 assert not(DOC/'result.json').exists();before=state();inv=read(INV);assert inv['counts']==dict(installedVerified=226,remaining=295,total=521);held={r['uid']:r for r in inv['rows']if not r['installedVerified']}
 row=next(r for r in read(RANK)['rows']if r['uid']=='landsd/255543:0');assert held[row['uid']]['indexedSourceSHA256']==row['sourceSHA256'];contacts=row['exactOriginalNativeCapContacts'];assert len(contacts)==1 and contacts[0]['ownedOriginalFace']==104 and contacts[0]['nativeOriginalUpwardCapFace']==2122
 graph=read(GRAPH);assert graph['completeOriginalComponentCount']==231 and graph['completeOriginalFaces']==10130
 census=read(DOC/'diagnostic.json.gz');tower=next(r for r in census['rows']if r['uid']=='landsd/253874:0');assert tower['genuineBodies']==306
 podium=next(r for r in read(ELM/'selection.json.gz')['rows']if r['uid']=='landsd/258892:0');assert podium['triangles']==764 and podium['sourceSHA256']=='8a4ff3f17f25fbf7f974e38955e83b4ff078665e477b42b7b53a8c800aed9c6b'
 er=read(ELM/'result.json');assert not er['scriptChecksPassed'];assert 'terrain-intersects-source-over-0.5m'in er['reasons']
 nominations=[dict(priority=1,uid=row['uid'],name=row['name'],sourceSHA256=row['sourceSHA256'],wholeSourceFaces=10130,genuineBodies=231,actualOriginalSupportUID='landsd/255939:0',supportSHA256=row['completeCandidateNativeInventory'][0]['sourceSHA256'],supportFaces=12640,positiveContact=contacts[0],nextScript='Decode complete unchanged carrier255939; source-only genuine shared-edge body census, finite exposed grade-wall and whole exposed edge search to cap2122; bind ownedface104 to exact original body and reuse closed original graph only after complete tuple equality. Independently resolve16 remaining original detail bodies using existing point-details inventory and exact mounting/visual source evidence. A qualified carrier route is missing; do not count historical215 ordinary conditional paths as grounded.',limits=['not a simple single-body source','positive104-to-2122 interface is not qualified carrier ground route','all16 unresolved details stay open','full current finite source/identity/foreign/native/runtime/browser mandatory after stable current window','no whole-native reapproval or terrain changes']),dict(priority=2,uid=tower['uid'],name=tower['name'],sourceSHA256=tower['sourceSHA256'],wholeSourceFaces=tower['wholeOriginalFaces'],genuineBodies=306,actualOriginalSupportUID=podium['uid'],supportSHA256=podium['sourceSHA256'],supportFaces=764,providerModelId=podium['modelId'],providerCSUID=podium['candidate']['entry']['buildingCSUID'],supportIdentityBasis='Exact cached provider Georef/hull match, same original Block B parent way/956201912; original podium role recorded by LandsD. This is a search lead, not a finite contact proof.',positiveContact=None,nextScript='Use full cached12164-face original tower and764-face original podium; exact finite positive-dimensional contact broadphase+census first, retaining all306 tower body obligations. Only if contact exists, bound complete original podium grade-to-qualified clear cap support; retain prior podium burial and neighbour233656/253871 regressions. Do not reuse generated native-terrain candidate JSON as original source.',limits=['secondary exploratory nomination; no exact tower-podium interface established here','podium itself has historical burial/foreign regressions','764 original podium source facets, not generated terrain candidate face counts','full unchanged source and finite/current gates remain mandatory'])]
 paths=set([Path(__file__),HERE/'xl_fixed295_simple_source_support_nomination_census_v1_20261011.py',INV,RANK,GRAPH,ELM/'selection.json.gz',ELM/'result.json',ROOT/podium['candidate']['path'],DOC/'diagnostic.json.gz'])
 s=importlib.util.spec_from_file_location('reviewed_source_freezer',HERE/'parkview_block17_freeze_current_source_evidence_20261011.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
 m.local_imports(Path(__file__),paths);m.local_imports(HERE/'xl_fixed295_simple_source_support_nomination_census_v1_20261011.py',paths);m.declared_refs(census,paths);m.declared_refs(row,paths)
 payload=dict(sourceOnly=True,currentAcceptance=False,installationApproved=False,sourceGeometryChanges=0,terrainGeometryChanges=0,newlyInstalled=0,freshCurrentCapture=False,fixedInventory=ref(INV),historicalFixedCounts=inv['counts'],nominations=nominations,sixSourceFilter='Six complete cached source censuses found225–1380 genuine bodies; none is asserted to be a simple support case. Large source face counts or ordinary-only historical warnings are not evidence of support.',scope='Two distinct original support paths nominated from exact cached data. Primary255543 has actual positive contact; secondary253874/258892 has source identity only and must first establish contact. No source/model review approval or historical negative waiver.',evidenceRefs=[ref(p)for p in sorted(paths)])
 save(DOC/'nominations.json',payload);(DOC/'README.md').write_text('# Fixed295 source-only support leads\n\nPriority1: Beverly Hill Block K landsd/255543:0 has exact original face104 contact to unchanged carrier landsd/255939:0 cap2122. Qualification of that cap through a genuine original grade route is missing;16 original detail obligations remain. Complete231-body cached graph may be reused only on full tuple equality.\n\nPriority2: Elm Tree Towers Block B landsd/253874:0 has a distinct original764-face podium landsd/258892:0, exact provider/source identity and same recorded Block B parent. Full finite contact remains unproved; historical podium burial and foreign regressions remain blockers. Begin with full original contact inventory, before any carrier-route claim.\n\nThe six-source body census rejects a simple-source assumption:225–1380 genuine bodies. These are nominations, not acceptance. Fixed post17 inventory226/295 is historical pinned evidence, not a fresh current count. No mutable current capture, altered source/terrain, publication or native reapproval.\n')
 paths.update([DOC/'nominations.json',DOC/'README.md']);m.F.freeze(BATCH,'two-distinct-original-support-route-nominations-and-six-source-complete-body-filter',sorted(paths),dict(uids=['landsd/255543:0','landsd/253874:0'],sourceOnly=True,currentAcceptance=False,installationApproved=False,newlyInstalled=0,nominations=nominations,negativeSimpleSourceFilterPreserved=True,noMutableCapture=True))
 assert state()==before;print(json.dumps(dict(jobId=read(DOC/'result.json')['jobId'],nominatedUIDs=[r['uid']for r in nominations],paths=len(paths),reviewStateUnchanged=True)))
if __name__=='__main__':main()
