"""Publish a script-verified unchanged government source containing mapped subforms."""
import importlib.util,json,subprocess,sys,uuid
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent));spec=importlib.util.spec_from_file_location('second',Path(__file__).with_name('xxl-second-pass.py'));s=importlib.util.module_from_spec(spec);spec.loader.exec_module(s)
ROOT,HERE=s.ROOT,s.HERE;read,save,h,rel=s.read,s.save,s.h,s.rel
CONFIG={'fortune':{'uid':'landsd/240841:0','policy':'original-government-contained-fortune-assembly-v1'},'maritime':{'uid':'landsd/228574:0','policy':'original-government-contained-maritime-assembly-v1'},'pao':{'uid':'landsd/305793:0','policy':'original-government-contained-pao-assembly-v1'},'mtr-mongkok':{'uid':'landsd/266918:0','policy':'original-government-mtr-mongkok-below-grade-v1'}}
sys.path.insert(0,str(HERE.parent/'model-review-ledger'));import ledger
spec=importlib.util.spec_from_file_location('direct',HERE/'integrate.py');direct=importlib.util.module_from_spec(spec);spec.loader.exec_module(direct)
def call(args):subprocess.run(args,cwd=ROOT,check=True)
def paths(key):return s.DOC/'fourth-pass'/key,s.LOCAL/(key+'-install'),HERE/'accepted'/('government-xxl-'+key+'-20260913')
def start(key):
 uid=CONFIG[key]['uid'];doc,local,stage=paths(key);batch='government-xxl-'+key+'-20260913';claim=s.reservations.claim('codex-'+key+'-import-'+str(uuid.uuid4()),['building:'+uid],batch=batch);assert claim['ok'];save(local/'import-reservation.json',json.loads(json.dumps(claim['reservation'],default=str)));call([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(local/'import-reservation.json'),'--',sys.executable,__file__,key,'owned'])
def owned(key):
 cfg=CONFIG[key];uid=cfg['uid'];doc,local,stage=paths(key);batch='government-xxl-'+key+'-20260913';receipt=local/'import-reservation.json';assert s.reservations.owns(read(receipt));catalogue=read(stage/'catalogue.json');assert [m['uid'] for m in catalogue['models']]==[uid];model=catalogue['models'][0];assert h(stage/model['asset'])==model['sha256'];suppressions=model['suppressesBuildingUids'];suppression=read(doc/'suppression-map.json');assert suppressions==suppression['suppressedUids'] and 0<len(suppressions)<=64;direct.browser_verified(doc/'staged-browser.json',{uid});validation=read(doc/'validation.json');assert validation['loaderAccepted']==validation['checksPassed']==1 and validation['exceptions']==0;metrics=read(doc/'metrics.json');metric=metrics['rows'][0];assert metric['sourcePreserved'] and not metric['missingTerrain'] and metric['budget']['residentBytes']<=metrics['profiles']['mobile']['residentBytes'];result=read(doc/'result.json');assert result['passed'] and result['policy']==cfg['policy'] and result['aiCalls']==result['modelGeometryChanges']==0 and result['suppressionCount']==len(suppressions)
 decision={'policy':cfg['policy'],'uid':uid,'sourceSHA256':model['sha256'],'catalogueSHA256':h(stage/'catalogue.json'),'planSHA256':h(stage/'plan.json'),'resultSHA256':h(doc/'result.json'),'suppressionMapSHA256':h(doc/'suppression-map.json'),'metricsSHA256':h(doc/'metrics.json'),'validationSHA256':h(doc/'validation.json'),'stagedBrowserSHA256':h(doc/'staged-browser.json'),'aiCallsThisImport':0,'geometryChanges':0};save(doc/'decision.json',decision);pointer_path=ROOT/'docs/astra-city/model-integration-20260909/current-source-review.json';pointer=read(pointer_path);inventory=read(ROOT/pointer['inventory']);parts={p['uid']:p for p in inventory['parts']};previous=parts.get(uid,{});parts[uid]={'uid':uid,'name':model['label'],'landmarkIds':previous.get('landmarkIds',[]),'objectId':model['objectId'],'csuid':model['buildingCSUID'],'candidate':{'sha256':model['sha256']},'sourceProgress':'prepared-for-review','classification':'script-verified-original-government-contained-complex','knownHold':False};ordered=sorted(parts.values(),key=lambda r:r['uid']);snapshot=s.digest(s.jobs.encode([ordered,decision]).encode())[:16];inventory_path=pointer_path.parent/f'source-review-inventory-{snapshot}.json';save(inventory_path,{**inventory,'snapshotId':snapshot,'derivedFrom':pointer['snapshotId'],'parts':ordered});ledger.seed(inventory_path,inherit=pointer['snapshotId']);commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip();effort={'method':'scripted','ai_model':None,'reasoning_effort':'not-applicable','issue':'HKS-203','run_id':snapshot,'output_ref':rel(doc/'decision.json')};observation=f'Exact unchanged government complex matched by object ID and Building CSUID. {len(suppressions)} basic source forms covered by at least 95% are reversibly suppressed. Bounded foundation, source, mobile budget, staged/live browser, picking, collision and fallback/retry checks pass. No AI modelling, review or model geometry edits.';ledger.record_many(snapshot,receipt,[(uid,'approved-for-integration',doc/'decision.json',observation,commit)],effort=effort,request_id=batch+'-approved-'+snapshot)
 publish=[sys.executable,str(HERE.parent/'model-integration-20260909/publish.py'),rel(stage/'plan.json'),'--receipt',str(receipt),'--phase',batch];call(publish);manifest=ROOT/'3d-viewer/city/data/manifest.json';before=manifest.read_bytes();(local/'manifest-before.json').write_bytes(before);call(publish+['--apply'])
 try:call(['node',str(HERE/'resolution-browser.mjs'),'live',rel(stage/'browser-config.json')]);direct.browser_verified(doc/'live-browser.json',{uid})
 except BaseException:manifest.write_bytes(before);raise
 acceptance={**decision,'snapshot':snapshot,'liveBrowserSHA256':h(doc/'live-browser.json'),'manifestSHA256':h(manifest)};save(doc/'installed-acceptance.json',acceptance);ledger.record_many(snapshot,receipt,[(uid,'installed-verified',doc/'installed-acceptance.json',observation,commit)],effort=effort,request_id=batch+'-installed-'+snapshot);assert read(pointer_path)==pointer;save(pointer_path,{**pointer,'snapshotId':snapshot,'inventory':rel(inventory_path),'previousSnapshots':[*pointer.get('previousSnapshots',[]),pointer['snapshotId']]});call([sys.executable,str(HERE.parent/'building-progress/export.py'),'--refresh']);call(['node',str(ROOT/'3d-viewer/scripts/build_progress.mjs')]);save(doc/'summary.json',{'installedUids':[uid],'suppressedBasicForms':len(suppressions),'snapshot':snapshot,'aiCalls':0,'geometryChanges':0,'progress':read(ROOT/'3d-viewer/city/data/building-progress.json')});print(json.dumps({'installed':uid,'suppressedBasicForms':len(suppressions),'snapshot':snapshot,'aiCalls':0}),flush=True)
if __name__=='__main__':
 key=sys.argv[1];assert key in CONFIG;owned(key) if len(sys.argv)>2 else start(key)
