"""Stage unchanged Harrow school government pair after explicit assembly checks; never AI."""
import importlib.util,json,shutil,subprocess,sys,uuid
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent));spec=importlib.util.spec_from_file_location('second',Path(__file__).with_name('xxl-second-pass.py'));s=importlib.util.module_from_spec(spec);spec.loader.exec_module(s)
ROOT,HERE=s.ROOT,s.HERE;DOC=s.DOC/'fourth-pass/harrow';LOCAL=s.LOCAL/'fourth-pass-harrow';STAGE=HERE/'accepted/government-xxl-harrow-20260913';UID='landsd/85040:0';SUPPORT='landsd/193532:0';BATCH='government-xxl-harrow-20260913';read,save,h,rel=s.read,s.save,s.h,s.rel

def call(args,allowed=(0,)):
 result=subprocess.run(args,cwd=ROOT);assert result.returncode in allowed,(args,result.returncode)
def primary():
 original=next(r for r in read(s.BASE/'selection.json.gz')['rows'] if r['sourceSHA256']=='7e6e8c41c654cd73fa35ffda88a23cd4474d47bb771e93281d8ba03caf02dbcf');second=next(r for r in read(s.DOC/'selection.json.gz')['rows'] if r['modelId']==original['modelId']);match=next(c for c in second['diagnosticSourceCandidates'] if c['building']['uid']==UID);form=match['building'];model=original['native']['model'];official=model.get('candidate') or model['matching']['officialCandidates'][0];entry={**model['asset'],**{k:official[k] for k in ('objectId','buildingCSUID','overlapOfSmallerFootprint','footprintCentroidDistanceMetres')},'uid':UID,'modelId':original['modelId'],'label':form['name'],'recordedBaseHeight':form['baseHeightHKPD'],'recordedTopHeight':form['topHeightHKPD'],'worldBounds':model['worldBounds'],'triangles':original['triangles'],'placementReviewed':False,'priority':'unreviewed','publicationApproved':False,'rootTranslation':[-834500,0,816500],'sourceTile':original['native']['sheet']};return {'uid':UID,'source':{'building':form,'tile':match['tile'],'tileSHA256':match['tileSHA256']},'candidate':{'path':str(s.LOCAL/'assets'/(entry['sha256']+'.glb.gz')),'entry':entry},'native':original['native']}
def start():
 rows=[primary(),read(LOCAL/'support-runtime.json')];assert [r['uid'] for r in rows]==[UID,SUPPORT];claim=s.reservations.claim('codex-harrow-'+str(uuid.uuid4()),['building:'+UID,'building:'+SUPPORT],batch=BATCH);assert claim['ok'];save(LOCAL/'reservation.json',json.loads(json.dumps(claim['reservation'],default=str)));save(DOC/'selection.json.gz',{**read(s.DOC/'runtime-selection.json.gz'),'manifestSHA256':h(ROOT/'3d-viewer/city/data/manifest.json'),'rows':rows});save(LOCAL/'source-forms.json',{r['uid']:r['source'] for r in rows});call([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(LOCAL/'reservation.json'),'--',sys.executable,__file__,'owned'])
def owned():
 assert s.reservations.owns(read(LOCAL/'reservation.json'));selection=read(DOC/'selection.json.gz');assert h(ROOT/'3d-viewer/city/data/manifest.json')==selection['manifestSHA256'];rows=selection['rows'];proof=next(r for r in read(s.DOC/'final-script-pass/results.json.gz')['rows'] if r['uid']==UID);identity,foundation=proof['identity'],proof['foundation'];assert proof['scriptedWorkComplete'] and identity['exactObjectAndCSUID'] and identity['targetCoveredBySourceProjection']>.999 and identity['sourceExcessFraction']<.31 and identity['sourceExcessMaximumDistanceFromTargetM']<12.7 and identity['unrelatedIntersectingForms']==1;other=next(f for f in identity['intersectingForms'] if f['uid']==SUPPORT);recovery=read(DOC/'support-source-recovery.json');assert other['fractionOfForm']>.067 and recovery['overlapOfSmallerFootprint']>.97 and recovery['centroidDistanceMetres']<13.4
 assert foundation['completeTerrainTriangles']==foundation['triangles'] and foundation['fullyBuriedTriangles']==1321 and foundation['fullyBuriedAreaM2']<286 and foundation['fullyBuriedAreaFraction']<.0044 and foundation['fullyBuriedUpwardAreaM2']<171 and foundation['minimumGapM']>-4.5
 entries=[];forms=[]
 for row in rows:
  entry=dict(row['candidate']['entry']);entry.update(priority='landmark',placementReviewed=True,sourceIdentityReviewed=True,identityReviewApproved=True,placementReview='Exact unchanged Harrow school government component matched by object ID and Building CSUID. The two-source assembly, bounded below-grade components and runtime checks are scripted; no AI or geometry edits.');entries.append(entry);asset=STAGE/entry['asset'];asset.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(row['candidate']['path'],asset);assert h(asset)==entry['sha256'];form=dict(row['source']['building']);form['tile']=Path(row['source']['tile']).stem;forms.append(form)
 cat=read(HERE/'accepted/government-xxl-20260911/catalogue.json');cat.update(area='Harrow International School original government assembly',counts={'packedModels':2},models=entries);save(STAGE/'catalogue.json',cat);save(STAGE/'catalogue-index.json',{'models':2,'catalogues':['catalogue.json']});save(STAGE/'source-forms.json',forms);save(DOC/'terrain-candidates.json',[])
 call(['node',str(HERE/'acceptance-metrics.mjs'),'--selection',rel(DOC/'selection.json.gz'),'--candidates',rel(STAGE),'--terrain-candidates',rel(DOC/'terrain-candidates.json'),'--out',rel(DOC/'metrics.json')]);call(['node',str(HERE.parent/'building-batch/validate_candidates.mjs'),'--candidates',rel(STAGE),'--source-forms',rel(LOCAL/'source-forms.json'),'--out',rel(DOC/'validation.json')],allowed=(0,1));metrics=read(DOC/'metrics.json');validation=read(DOC/'validation.json');reasons=[]
 for metric in metrics['rows']:
  if metric.get('error') or not metric.get('sourcePreserved') or metric.get('missingTerrain') or metric.get('maxSamplerDelta',0)>.004:reasons.append('source-integrity-or-terrain')
  if metric.get('budget') and any(metric['budget'][k]>metrics['profiles']['mobile'][k] for k in ('triangles','geometryBytes','residentBytes')):reasons.append('mobile-runtime-budget')
 allowed={'sampled-ground-gap-below-model-bottom','sampled-terrain-above-model-bottom'}
 for result in validation['results']:
  if result['outcome']=='validation-exception':reasons.append('runtime-validation-exception')
  reasons.extend(c for c in result.get('concerns',[]) if c not in allowed)
 decision={'uids':[UID,SUPPORT],'policy':'original-government-harrow-assembly-v1','passed':not reasons,'reasons':sorted(set(reasons)),'supportRecoverySHA256':h(DOC/'support-source-recovery.json'),'aiCalls':0,'modelGeometryChanges':0,'publication':False};save(DOC/'result.json',decision)
 if decision['passed']:
  destination='city/data/official-models/government-xxl-harrow-20260913/catalogue.json';save(STAGE/'plan.json',{'areas':[{'area':cat['area'],'catalogue':rel(STAGE/'catalogue.json'),'destination':destination}]});save(STAGE/'browser-config.json',{'stage':rel(STAGE)+'/','doc':rel(DOC)+'/','catalogueURL':destination,'terrain':[],'fitBox':True,'browserUids':[UID,SUPPORT],'failureTestUids':[UID]})
 print(json.dumps(decision))
if __name__=='__main__':owned() if len(sys.argv)>1 else start()
