"""Stage unchanged MTR Mong Kok East source with proven intentional below-grade structure; never AI."""
import importlib.util,json,shutil,subprocess,sys,uuid
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent));spec=importlib.util.spec_from_file_location('second',Path(__file__).with_name('xxl-second-pass.py'));s=importlib.util.module_from_spec(spec);spec.loader.exec_module(s)
ROOT,HERE=s.ROOT,s.HERE;DOC=s.DOC/'fourth-pass/mtr-mongkok';LOCAL=s.LOCAL/'fourth-pass-mtr-mongkok';STAGE=HERE/'accepted/government-xxl-mtr-mongkok-20260913';UID='landsd/266918:0';MID='B358222042102063C0';BATCH='government-xxl-mtr-mongkok-20260913';read,save,h,rel=s.read,s.save,s.h,s.rel
def call(args,allowed=(0,)):r=subprocess.run(args,cwd=ROOT);assert r.returncode in allowed,(args,r.returncode)
def source_row():
 proof=next(r for r in read(s.DOC/'final-script-pass/results.json.gz')['rows'] if r['uid']==UID);original=next(r for r in read(s.BASE/'selection.json.gz')['rows'] if r['modelId']==MID);second=next(r for r in read(s.DOC/'selection.json.gz')['rows'] if r['modelId']==MID);match=next(c for c in second['diagnosticSourceCandidates'] if c['building']['uid']==UID);form=match['building'];model=original['native']['model'];official=model['matching']['officialCandidates'][0];entry={**model['asset'],**{k:official[k] for k in ('objectId','buildingCSUID','overlapOfSmallerFootprint','footprintCentroidDistanceMetres')},'uid':UID,'modelId':MID,'label':form['name'],'recordedBaseHeight':form['baseHeightHKPD'],'recordedTopHeight':form['topHeightHKPD'],'worldBounds':model['worldBounds'],'triangles':proof['foundation']['triangles'],'placementReviewed':False,'priority':'unreviewed','publicationApproved':False,'rootTranslation':[-834500,0,816500],'sourceTile':original['native']['sheet']};return {'uid':UID,'source':{'building':form,'tile':match['tile'],'tileSHA256':match['tileSHA256']},'candidate':{'path':str(s.LOCAL/'assets'/(entry['sha256']+'.glb.gz')),'entry':entry},'native':original['native']}
def start():
 row=source_row();claim=s.reservations.claim('codex-mtr-mongkok-'+str(uuid.uuid4()),['building:'+UID],batch=BATCH);assert claim['ok'];save(LOCAL/'reservation.json',json.loads(json.dumps(claim['reservation'],default=str)));save(DOC/'selection.json.gz',{**read(s.DOC/'runtime-selection.json.gz'),'manifestSHA256':h(ROOT/'3d-viewer/city/data/manifest.json'),'rows':[row]});save(LOCAL/'source-forms.json',{UID:row['source']});call([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(LOCAL/'reservation.json'),'--',sys.executable,__file__,'owned'])
def owned():
 assert s.reservations.owns(read(LOCAL/'reservation.json'));selection=read(DOC/'selection.json.gz');assert h(ROOT/'3d-viewer/city/data/manifest.json')==selection['manifestSHA256'];row=selection['rows'][0];proof=next(r for r in read(s.DOC/'final-script-pass/results.json.gz')['rows'] if r['uid']==UID);identity,foundation=proof['identity'],proof['foundation'];same=read(DOC/'same-archive-below-grade.json');terrain=read(DOC/'terrain-result.json');assert identity['exactObjectAndCSUID'] and identity['targetCoveredBySourceProjection']>.969 and identity['sourceExcessFraction']<.043 and identity['sourceExcessMaximumDistanceFromTargetM']<18.9;assert foundation['fullyBuriedTriangles']==133 and foundation['fullyBuriedAreaFraction']<.049 and foundation['minimumGapM']>-24.8;assert same['fullyBelowSameArchiveTerrainTriangles']>120 and same['fullyBelowSameArchiveTerrainAreaM2']>1800 and same['minimumSameArchiveGapM']<-8 and same['aiCalls']==same['modelGeometryChanges']==0;assert len(terrain['blockedBy'])==9 and terrain['aiCalls']==terrain['modelGeometryChanges']==0
 suppressions=sorted(f['uid'] for f in identity['intersectingForms'] if f['uid']!=UID and f.get('fractionOfForm',0)>=.95);assert suppressions and len(suppressions)<=64;entry=dict(row['candidate']['entry']);entry.update(priority='landmark',placementReviewed=True,sourceIdentityReviewed=True,identityReviewApproved=True,suppressesBuildingUids=suppressions,placementReview='Exact unchanged MTR Mong Kok East government complex matched by object ID and Building CSUID. Same-archive terrain proves coherent intentional below-grade station structure. A bounded terrain patch is withheld because nine detailed neighbours require regional reconciliation. Covered basic forms are reversibly suppressed; no AI or geometry edits.');asset=STAGE/entry['asset'];asset.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(row['candidate']['path'],asset);assert h(asset)==entry['sha256'];form=dict(row['source']['building']);form['tile']=Path(row['source']['tile']).stem
 cat=read(HERE/'accepted/government-xxl-20260911/catalogue.json');cat.update(area='MTR Mong Kok East original government complex',counts={'packedModels':1},models=[entry]);save(STAGE/'catalogue.json',cat);save(STAGE/'catalogue-index.json',{'models':1,'catalogues':['catalogue.json']});save(STAGE/'source-forms.json',[form]);save(DOC/'staged-terrain-candidates.json',[]);save(DOC/'suppression-map.json',{'uid':UID,'minimumCoveredFraction':.95,'suppressedUids':suppressions,'count':len(suppressions),'source':'final-script-pass intersecting forms','aiCalls':0})
 call(['node',str(HERE/'acceptance-metrics.mjs'),'--selection',rel(DOC/'selection.json.gz'),'--candidates',rel(STAGE),'--terrain-candidates',rel(DOC/'staged-terrain-candidates.json'),'--out',rel(DOC/'metrics.json')]);call(['node',str(HERE.parent/'building-batch/validate_candidates.mjs'),'--candidates',rel(STAGE),'--source-forms',rel(LOCAL/'source-forms.json'),'--out',rel(DOC/'validation.json')],allowed=(0,1));metrics=read(DOC/'metrics.json');validation=read(DOC/'validation.json');metric=metrics['rows'][0];reasons=[]
 if metric.get('error') or not metric.get('sourcePreserved') or metric.get('missingTerrain') or metric.get('maxSamplerDelta',0)>.004:reasons.append('source-integrity-or-terrain')
 if metric.get('budget') and any(metric['budget'][k]>metrics['profiles']['mobile'][k] for k in ('triangles','geometryBytes','residentBytes')):reasons.append('mobile-runtime-budget')
 allowed={'sampled-ground-gap-below-model-bottom','sampled-terrain-above-model-bottom'}
 for result in validation['results']:
  if result['outcome']=='validation-exception':reasons.append('runtime-validation-exception')
  reasons.extend(c for c in result.get('concerns',[]) if c not in allowed)
 decision={'uid':UID,'policy':'original-government-mtr-mongkok-below-grade-v1','passed':not reasons,'reasons':sorted(set(reasons)),'suppressionCount':len(suppressions),'sameArchiveBelowGradeSHA256':h(DOC/'same-archive-below-grade.json'),'withheldTerrainPatchSHA256':terrain['patch']['sha256'],'terrainPatchBlockedBy':terrain['blockedBy'],'aiCalls':0,'modelGeometryChanges':0,'publication':False};save(DOC/'result.json',decision)
 if decision['passed']:
  destination='city/data/official-models/government-xxl-mtr-mongkok-20260913/catalogue.json';save(STAGE/'plan.json',{'areas':[{'area':cat['area'],'catalogue':rel(STAGE/'catalogue.json'),'destination':destination}]});save(STAGE/'browser-config.json',{'stage':rel(STAGE)+'/','doc':rel(DOC)+'/','catalogueURL':destination,'terrain':[],'fitBox':True,'browserUids':[UID],'failureTestUids':[UID]})
 print(json.dumps(decision))
if __name__=='__main__':owned() if len(sys.argv)>1 else start()
