"""Build and verify MTR Mong Kok East against its same-archive government terrain; no AI."""
import importlib.util,json,sys
from pathlib import Path
import numpy as np,shapely
from shapely.geometry import box,Polygon
sys.path.insert(0,str(Path(__file__).resolve().parent));spec=importlib.util.spec_from_file_location('second',Path(__file__).with_name('xxl-second-pass.py'));s=importlib.util.module_from_spec(spec);spec.loader.exec_module(s)
ROOT,HERE=s.ROOT,s.HERE;DOC=s.DOC/'fourth-pass/mtr-mongkok';LOCAL=s.LOCAL/'fourth-pass-mtr-mongkok';UID='landsd/266918:0';SHEET='11-NW-14D';read,save,h,rel=s.read,s.save,s.h,s.rel
def main():
 original=next(r for r in read(s.BASE/'selection.json.gz')['rows'] if r['modelId']=='B358222042102063C0');recovery=read(s.LOCAL/'sheets'/SHEET/'recovery.json');proof=recovery['source'];terrain_paths=[s.LOCAL/'sheets'/SHEET/'terrain'/e['name'] for e in proof['entries'] if e['name'].startswith('TERRAIN') and e['name'].endswith('.gltf')];assert terrain_paths
 parent=read(ROOT/'3d-viewer/city/data/terrain.json');world=original['native']['model']['worldBounds'];cells=s.resolution.rectangle_for(world,parent);bounds=s.resolution.extent(cells,parent);manifest=read(ROOT/'3d-viewer/city/data/manifest.json');assert not any(s.resolution.terrain.overlap(cells,read(ROOT/'3d-viewer'/p['url'])['coarseCells']) for p in manifest['terrainPatches'])
 fragments=[]
 for path in terrain_paths:
  triangles=s.context.triangles(path);near=triangles[(triangles[:,:,0].max(1)>=bounds[0])&(triangles[:,:,0].min(1)<=bounds[2])&(triangles[:,:,2].max(1)>=bounds[1])&(triangles[:,:,2].min(1)<=bounds[3])];fragments.append(near)
 native=np.concatenate(fragments);polygons=shapely.polygons(native[:,:,[0,2]]);valid=shapely.area(polygons)>1e-10;native=native[valid];polygons=polygons[valid];tree=shapely.STRtree(polygons);model=s.glb_triangles(original);centres=model.mean(1)[:,[0,2]];source_at_model=s.context.shared.samples(centres,native,tree);covered=np.isfinite(source_at_model);tops=model[:,:,1].max(1);buried=covered&(tops<source_at_model-.5);areas=np.linalg.norm(np.cross(model[:,1]-model[:,0],model[:,2]-model[:,0]),axis=1)/2
 source_check={'modelTriangles':len(model),'terrainCoveredTriangles':int(covered.sum()),'fullyBelowSameArchiveTerrainTriangles':int(buried.sum()),'fullyBelowSameArchiveTerrainAreaM2':float(areas[buried].sum()),'fullyBelowSameArchiveTerrainAreaFraction':float(areas[buried].sum()/areas.sum()),'minimumSameArchiveGapM':float(np.min(tops[covered]-source_at_model[covered])),'sameArchiveTerrainSHA256':[{'path':rel(p),'sha256':h(p)} for p in terrain_paths],'sourceDirectorySHA256':proof['directorySHA256'],'interpretation':'Below-grade source surfaces persist against terrain shipped in the same government archive; retained as intentional station/complex structure, not viewer-terrain placement error.','aiCalls':0,'modelGeometryChanges':0};print(json.dumps(source_check));assert source_check['terrainCoveredTriangles']>.84*len(model) and source_check['fullyBelowSameArchiveTerrainTriangles']>120 and source_check['fullyBelowSameArchiveTerrainAreaM2']>1800 and source_check['minimumSameArchiveGapM']<-8;save(DOC/'same-archive-below-grade.json',source_check)
 step=5;w=round((bounds[2]-bounds[0])/step)+1;hh=round((bounds[3]-bounds[1])/step)+1;grid=np.array([[bounds[0]+c*step,bounds[1]+r*step] for r in range(hh) for c in range(w)]);source_heights=s.context.shared.samples(grid,native,tree);rendered=s.resolution.terrain.fine.DemSampler(parent,rendered=True);parent_heights=np.array([rendered.ground(x,z) for x,z in grid]);lo,hi=world;core=[lo[0]-1,lo[2]-1,hi[0]+1,hi[2]+1];alphas=[];heights=[]
 for (x,z),source_height,parent_height in zip(grid,source_heights,parent_heights):
  alpha=max(0,min(1,min(x-core[0],core[2]-x,z-core[1],core[3]-z)/10)) if np.isfinite(source_height) else 0;alphas.append(alpha);heights.append(float(source_height*alpha+parent_height*(1-alpha)) if alpha else float(parent_height))
 pg=parent['meta']['georef'];cell=pg['aE'];vegetation=[]
 for x,z in grid:
  col=min(parent['w']-1,max(0,round((x+834500-pg['bE'])/cell)));row=min(parent['h']-1,max(0,round((z-816500+pg['bN'])/cell)));vegetation.append(parent['vegetation'][row*parent['w']+col])
 positions=np.column_stack([grid[:,0],np.asarray(heights),grid[:,1]]);index=[]
 for r in range(hh-1):
  for c in range(w-1):q=r*w+c;index.extend([q,q+1,q+w,q+1,q+w+1,q+w])
 source={'provider':'Lands Department/HKSAR','crs':'EPSG:2326','verticalDatum':'HKPD','nativeSource':{'sheet':SHEET,'revision':proof['revisionDate'],'sourceETag':proof['sourceETag'],'directorySHA256':proof['directorySHA256'],'files':source_check['sameArchiveTerrainSHA256']},'policy':'Deterministic five-metre samples of the same-archive government TIN in the model core with a ten-metre parent-terrain boundary blend. Source building geometry and elevations remain unchanged.','sourceSampledGridPoints':int(np.isfinite(source_heights).sum()),'maximumSourceWeight':float(max(alphas))}
 patch={'id':'government-native-266918-0','w':w,'h':hh,'cell':step,'elev':heights,'renderedElev':heights,'vegetation':vegetation,'coarseCells':cells,'meta':{'georef':{'aE':step,'aN':-step,'bE':bounds[0]+834500,'bN':816500-bounds[1],'W':w,'H':hh},'parentTerrain':'city/data/terrain.json','parentSha256':h(ROOT/'3d-viewer/city/data/terrain.json'),'targetUids':[UID],'source':source},'nativeMesh':{'position':positions.reshape(-1).tolist(),'index':index,'source':{'verticalDatum':'HKPD','verticalScale':1,'policy':'Five-metre deterministic same-archive TIN samples with exact parent boundary joins; no AI or building geometry changes.'}}};s.resolution.validate_patch(patch,parent);assert len(index)//3<30000;path=DOC/('withheld-'+patch['id']+'.json');save(path,patch);entry={'path':rel(path),'sha256':h(path),'uids':[UID],'bounds':bounds,'triangles':len(index)//3};save(DOC/'terrain-candidates.json',[entry])
 region=box(*bounds);live={m['uid'] for url in manifest['officialModelCatalogues'] for m in read(ROOT/'3d-viewer'/url)['models']};neighbours=[];hashes={}
 for tile in manifest['tiles']:
  path2=ROOT/'3d-viewer'/tile['url'];raw=path2.read_bytes();touched=False
  for building in json.loads(raw)['buildings']:
   if Polygon(building['rings'][0],building['rings'][1:]).intersects(region):neighbours.append({'building':building,'patchIndexes':[0],'existingNative':building['uid'] in live or bool(building.get('modelGeometry'))});touched=True
  if touched:hashes[rel(path2)]=s.digest(raw)
 save(DOC/'neighbour-inputs.json.gz',{'rows':neighbours,'inputHashes':hashes,'candidateIds':[UID],'patches':[entry]});s.call(['node',str(HERE/'check-neighbours.mjs'),rel(DOC)+'/']);report=read(DOC/'neighbour-checks.json');result={'uid':UID,'cells':cells,'bounds':bounds,'patch':entry,'neighbours':len(neighbours),'blockedBy':report['patches'][0]['blockedBy'],'sameArchiveCheckSHA256':h(DOC/'same-archive-below-grade.json'),'aiCalls':0,'modelGeometryChanges':0,'publication':False};save(DOC/'terrain-result.json',result);print(json.dumps(result))
if __name__=='__main__':main()
