"""Publish the exact Elements government assembly after deterministic acceptance."""
import importlib.util,json,subprocess,sys,uuid
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent));spec=importlib.util.spec_from_file_location('second',Path(__file__).with_name('xxl-second-pass.py'));s=importlib.util.module_from_spec(spec);spec.loader.exec_module(s)
ROOT,HERE=s.ROOT,s.HERE;DOC=s.DOC/'elements';LOCAL=s.LOCAL/'elements-install';STAGE=HERE/'accepted/government-xxl-elements-assembly-20260912';UID='landsd/273061:0';HARBOURSIDE='landsd/204153:0';BATCH='government-xxl-elements-assembly-20260912';read,save,h,rel=s.read,s.save,s.h,s.rel
sys.path.insert(0,str(HERE.parent/'model-review-ledger'));import ledger

def call(args):subprocess.run(args,cwd=ROOT,check=True)
def browser(name,uids):
 r=read(DOC/name);assert r.get('passed') and not r['errors'] and r['aiCalls']==0 and not r['architectureReview'];expected={(u,w,t) for u in uids for w in (1280,390) for t in ('15:00','22:00')};assert {(v['uid'],v['width'],v['time']) for v in r['views'] if 'time' in v}==expected;assert {v['uid'] for v in r['views'] if v.get('fallbackRetained')}=={UID}
 for v in r['views']:
  if 'time' in v:assert v['fullyFramed'] and v['active'] and v['visible'] and v['pick']==v['uid'] and v['collision']==v['uid'] and not v['overflow'] and abs(v['ground']-v['groundSampler'])<=.004
 return r
def start():
 cat=read(STAGE/'catalogue.json');ids={e['uid'] for e in cat['models']};assert len(ids)==38 and UID in ids and HARBOURSIDE not in ids;claim=s.reservations.claim('codex-elements-import-'+str(uuid.uuid4()),['building:'+u for u in ids|{HARBOURSIDE}],batch=BATCH);assert claim['ok'];save(LOCAL/'reservation.json',json.loads(json.dumps(claim['reservation'],default=str)));call([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(LOCAL/'reservation.json'),'--',sys.executable,__file__,'owned'])
def owned():
 receipt=LOCAL/'reservation.json';assert s.reservations.owns(read(receipt));cat=read(STAGE/'catalogue.json');ids={e['uid'] for e in cat['models']};assert len(ids)==len(cat['models'])==38
 for e in cat['models']:assert h(STAGE/e['asset'])==e['sha256'] and e['placementReviewed'] and e['sourceIdentityReviewed'] and e['identityReviewApproved']
 sampled={UID,'landsd/203724:0','landsd/203728:0','landsd/201351:0'};browser('staged-browser.json',sampled);result=read(DOC/'assembly-result.json');assert result['passed'] and result['policy']=='original-government-elements-assembly-v1' and result['newModels']==38 and not result['reasons'] and not result['unresolvedNeighbours'] and result['blockedNeighbours']==[HARBOURSIDE] and result['aiCalls']==result['modelGeometryChanges']==0
 validation=read(DOC/'assembly-validation.json');assert validation['loaderAccepted']==validation['checksPassed']==38 and validation['exceptions']==0
 metrics=read(DOC/'assembly-metrics.json');assert len(metrics['rows'])==38 and metrics['aiCalls']==metrics['geometryChanges']==0 and all(not r.get('error') and r.get('sourcePreserved') and not r.get('missingTerrain') for r in metrics['rows'])
 dep=read(HERE.parent/'identity-four-native/dependency-replacements.json');assert dep['changes'][0]['uid']==HARBOURSIDE and h(ROOT/dep['catalogues'][0]['source'])==dep['catalogues'][0]['oldSHA256'];assert h(HERE.parent/'identity-four-native/harbourside-migrated-catalogue.json')==dep['catalogues'][0].get('newSHA256',h(HERE.parent/'identity-four-native/harbourside-migrated-catalogue.json'))
 decision={'policy':result['policy'],'primaryUid':UID,'newModelCount':38,'existingDependencyMigration':HARBOURSIDE,'sourceModels':[{'uid':e['uid'],'sha256':e['sha256']} for e in cat['models']],'catalogueSHA256':h(STAGE/'catalogue.json'),'planSHA256':h(STAGE/'plan.json'),'resultSHA256':h(DOC/'assembly-result.json'),'metricsSHA256':h(DOC/'assembly-metrics.json'),'validationSHA256':h(DOC/'assembly-validation.json'),'neighbourChecksSHA256':h(DOC/'assembly-neighbour-checks.json'),'supportRecoverySHA256':h(DOC/'support-source-recovery.json'),'dependencyReviewSHA256':h(HERE.parent/'identity-four-native/dependency-replacements.json'),'stagedBrowserSHA256':h(DOC/'staged-browser.json'),'aiCallsThisImport':0,'geometryChanges':0};save(DOC/'decision.json',decision)
 pointer_path=ROOT/'docs/astra-city/model-integration-20260909/current-source-review.json';pointer=read(pointer_path);inventory=read(ROOT/pointer['inventory']);parts={p['uid']:p for p in inventory['parts']};forms={b['uid']:b for b in read(STAGE/'source-forms.json')}
 for e in cat['models']:
  old=parts.get(e['uid'],{});parts[e['uid']]={'uid':e['uid'],'name':e['label'],'landmarkIds':old.get('landmarkIds',[]),'objectId':e['objectId'],'csuid':e['buildingCSUID'],'candidate':{'sha256':e['sha256']},'sourceProgress':'prepared-for-review','classification':'script-verified-original-government-assembly','knownHold':False};assert forms[e['uid']]['objectId']==e['objectId']
 ordered=sorted(parts.values(),key=lambda x:x['uid']);snapshot=s.digest(s.jobs.encode([ordered,decision]).encode())[:16];inv=pointer_path.parent/f'source-review-inventory-{snapshot}.json';save(inv,{**inventory,'snapshotId':snapshot,'derivedFrom':pointer['snapshotId'],'parts':ordered});ledger.seed(inv,inherit=pointer['snapshotId']);commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip();effort={'method':'scripted','ai_model':None,'reasoning_effort':'not-applicable','issue':'HKS-203','run_id':snapshot,'output_ref':rel(DOC/'decision.json')};observation='Exact unchanged government Elements estate assembly with 38 new source models, one existing Harbourside dependency migration and restored approved native terrain passed source, neighbour, staged/live runtime, picking, collision, terrain-ray and fallback/retry checks. No AI modelling or geometry edits.'
 ledger.record_many(snapshot,receipt,[(u,'approved-for-integration',DOC/'decision.json',observation,commit) for u in sorted(ids)],effort=effort,request_id=BATCH+'-approved-'+snapshot);pub=[sys.executable,str(HERE.parent/'model-integration-20260909/publish.py'),rel(STAGE/'plan.json'),'--receipt',str(receipt),'--phase',BATCH];call(pub);manifest=ROOT/'3d-viewer/city/data/manifest.json';before=manifest.read_bytes();(LOCAL/'manifest-before.json').write_bytes(before);call(pub+['--apply'])
 try:call(['node',str(HERE/'resolution-browser.mjs'),'live',rel(STAGE/'browser-config.json')]);browser('live-browser.json',sampled)
 except BaseException:manifest.write_bytes(before);raise
 acceptance={**decision,'snapshot':snapshot,'liveBrowserSHA256':h(DOC/'live-browser.json'),'manifestSHA256':h(manifest)};save(DOC/'installed-acceptance.json',acceptance);ledger.record_many(snapshot,receipt,[(u,'installed-verified',DOC/'installed-acceptance.json',observation,commit) for u in sorted(ids)],effort=effort,request_id=BATCH+'-installed-'+snapshot);assert read(pointer_path)==pointer;save(pointer_path,{**pointer,'snapshotId':snapshot,'inventory':rel(inv),'previousSnapshots':[*pointer.get('previousSnapshots',[]),pointer['snapshotId']]});call([sys.executable,str(HERE.parent/'building-progress/export.py'),'--refresh']);call(['node',str(ROOT/'3d-viewer/scripts/build_progress.mjs')]);save(DOC/'summary.json',{'installedUids':sorted(ids),'existingDependencyMigration':HARBOURSIDE,'snapshot':snapshot,'aiCalls':0,'geometryChanges':0,'progress':read(ROOT/'3d-viewer/city/data/building-progress.json')});print(json.dumps({'installed':len(ids),'dependencyMigration':HARBOURSIDE,'snapshot':snapshot,'aiCalls':0}),flush=True)
if __name__=='__main__':owned() if len(sys.argv)>1 else start()
