"""Publish the exact Harrow government assembly after deterministic acceptance."""
import importlib.util,json,subprocess,sys,uuid
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent))
spec=importlib.util.spec_from_file_location('second',Path(__file__).with_name('xxl-second-pass.py'));s=importlib.util.module_from_spec(spec);spec.loader.exec_module(s)
ROOT,HERE=s.ROOT,s.HERE;DOC=s.DOC/'fourth-pass/harrow';LOCAL=s.LOCAL/'harrow-install';STAGE=HERE/'accepted/government-xxl-harrow-20260913';UID='landsd/85040:0';SUPPORT='landsd/193532:0';UIDS={UID,SUPPORT};BATCH='government-xxl-harrow-20260913';read,save,h,rel=s.read,s.save,s.h,s.rel
sys.path.insert(0,str(HERE.parent/'model-review-ledger'));import ledger
spec=importlib.util.spec_from_file_location('direct',HERE/'integrate.py');direct=importlib.util.module_from_spec(spec);spec.loader.exec_module(direct)
def call(args):subprocess.run(args,cwd=ROOT,check=True)
def browser_verified(path):
 report=read(path);assert report.get('passed') and not report['errors'];expected={(uid,width,time) for uid in UIDS for width in (1280,390) for time in ('15:00','22:00')};actual={(v['uid'],v['width'],v['time']) for v in report['views'] if 'time' in v};assert actual==expected;assert {v['uid'] for v in report['views'] if v.get('fallbackRetained')}=={UID}
 for v in report['views']:
  if 'time' in v:assert v['active'] and v['visible'] and v['pick']==v['uid'] and v['collision']==v['uid'] and not v['overflow']
 return report
def start():
 claim=s.reservations.claim('codex-harrow-import-'+str(uuid.uuid4()),['building:'+uid for uid in sorted(UIDS)],batch=BATCH);assert claim['ok'];save(LOCAL/'import-reservation.json',json.loads(json.dumps(claim['reservation'],default=str)));call([sys.executable,str(HERE.parent/'shared-modelling/reservations.py'),'run','--lease-file',str(LOCAL/'import-reservation.json'),'--',sys.executable,__file__,'owned'])
def owned():
 receipt=LOCAL/'import-reservation.json';assert s.reservations.owns(read(receipt));catalogue=read(STAGE/'catalogue.json');models={m['uid']:m for m in catalogue['models']};assert set(models)==UIDS and len(models)==2
 for model in models.values():assert h(STAGE/model['asset'])==model['sha256'] and model['placementReviewed'] and model['sourceIdentityReviewed'] and model['identityReviewApproved']
 browser_verified(DOC/'staged-browser.json');validation=read(DOC/'validation.json');assert validation['loaderAccepted']==validation['checksPassed']==2 and validation['exceptions']==0;assert validation['concerns']=={'sampled-terrain-above-model-bottom':2}
 metrics=read(DOC/'metrics.json');assert len(metrics['rows'])==2 and all(row['sourcePreserved'] and not row['missingTerrain'] and row['budget']['residentBytes']<=metrics['profiles']['mobile']['residentBytes'] for row in metrics['rows'])
 result=read(DOC/'result.json');assert result['passed'] and result['policy']=='original-government-harrow-assembly-v1' and set(result['uids'])==UIDS and not result['reasons'] and result['aiCalls']==result['modelGeometryChanges']==0
 decision={'policy':result['policy'],'primaryUid':UID,'modelCount':2,'sourceModels':[{'uid':uid,'sha256':models[uid]['sha256']} for uid in sorted(UIDS)],'catalogueSHA256':h(STAGE/'catalogue.json'),'planSHA256':h(STAGE/'plan.json'),'resultSHA256':h(DOC/'result.json'),'metricsSHA256':h(DOC/'metrics.json'),'validationSHA256':h(DOC/'validation.json'),'supportRecoverySHA256':h(DOC/'support-source-recovery.json'),'stagedBrowserSHA256':h(DOC/'staged-browser.json'),'aiCallsThisImport':0,'geometryChanges':0};save(DOC/'decision.json',decision)
 pointer_path=ROOT/'docs/astra-city/model-integration-20260909/current-source-review.json';pointer=read(pointer_path);inventory=read(ROOT/pointer['inventory']);parts={p['uid']:p for p in inventory['parts']}
 for uid,model in models.items():
  previous=parts.get(uid,{});parts[uid]={'uid':uid,'name':model['label'],'landmarkIds':previous.get('landmarkIds',[]),'objectId':model['objectId'],'csuid':model['buildingCSUID'],'candidate':{'sha256':model['sha256']},'sourceProgress':'prepared-for-review','classification':'script-verified-original-government-assembly','knownHold':False}
 ordered=sorted(parts.values(),key=lambda row:row['uid']);snapshot=s.digest(s.jobs.encode([ordered,decision]).encode())[:16];inventory_path=pointer_path.parent/f'source-review-inventory-{snapshot}.json';save(inventory_path,{**inventory,'snapshotId':snapshot,'derivedFrom':pointer['snapshotId'],'parts':ordered});ledger.seed(inventory_path,inherit=pointer['snapshotId'])
 commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip();effort={'method':'scripted','ai_model':None,'reasoning_effort':'not-applicable','issue':'HKS-203','run_id':snapshot,'output_ref':rel(DOC/'decision.json')};observation='Exact unchanged Harrow government tower and podium matched by object ID and Building CSUID. Deterministic source, bounded foundation, mobile budget, staged/live browser, picking, collision and fallback/retry checks pass. No AI modelling, review or model geometry edits.';ledger.record_many(snapshot,receipt,[(uid,'approved-for-integration',DOC/'decision.json',observation,commit) for uid in sorted(UIDS)],effort=effort,request_id=BATCH+'-approved-'+snapshot)
 publish=[sys.executable,str(HERE.parent/'model-integration-20260909/publish.py'),rel(STAGE/'plan.json'),'--receipt',str(receipt),'--phase',BATCH];call(publish);manifest=ROOT/'3d-viewer/city/data/manifest.json';before=manifest.read_bytes();(LOCAL/'manifest-before.json').write_bytes(before);call(publish+['--apply'])
 try:call(['node',str(HERE/'resolution-browser.mjs'),'live',rel(STAGE/'browser-config.json')]);browser_verified(DOC/'live-browser.json')
 except BaseException:manifest.write_bytes(before);raise
 acceptance={**decision,'snapshot':snapshot,'liveBrowserSHA256':h(DOC/'live-browser.json'),'manifestSHA256':h(manifest)};save(DOC/'installed-acceptance.json',acceptance);ledger.record_many(snapshot,receipt,[(uid,'installed-verified',DOC/'installed-acceptance.json',observation,commit) for uid in sorted(UIDS)],effort=effort,request_id=BATCH+'-installed-'+snapshot);assert read(pointer_path)==pointer;save(pointer_path,{**pointer,'snapshotId':snapshot,'inventory':rel(inventory_path),'previousSnapshots':[*pointer.get('previousSnapshots',[]),pointer['snapshotId']]});call([sys.executable,str(HERE.parent/'building-progress/export.py'),'--refresh']);call(['node',str(ROOT/'3d-viewer/scripts/build_progress.mjs')]);save(DOC/'summary.json',{'installedUids':sorted(UIDS),'primaryUid':UID,'supportingModels':1,'snapshot':snapshot,'aiCalls':0,'geometryChanges':0,'progress':read(ROOT/'3d-viewer/city/data/building-progress.json')});print(json.dumps({'installed':2,'primary':UID,'snapshot':snapshot,'aiCalls':0}),flush=True)
if __name__=='__main__':owned() if len(sys.argv)>1 else start()
