import {REGIONAL_PLACES} from './regional-places.js';
// Generated by source-scripts/city/build_places.py. Coordinates are approximate public-place camera positions.
export const REGIONS={"island":{"title":"Hong Kong Island","zh":"香港島"},"kowloon":{"title":"Kowloon","zh":"九龍"},"ntwest":{"title":"New Territories West","zh":"新界西","short":"NT West"},"nteast":{"title":"New Territories East","zh":"新界東","short":"NT East"},"ntnorth":{"title":"Northern New Territories","zh":"新界北","short":"NT North"},"lantau":{"title":"Lantau","zh":"大嶼山"},"islands":{"title":"Outlying islands","zh":"離島","short":"Islands"}};
const BASE_PLACES={
  "central": {
    "region": "island",
    "title": "Central",
    "zh": "中環",
    "target": [
      0,
      110,
      420
    ],
    "spawn": [
      0,
      575
    ],
    "offset": [
      1900,
      1560,
      -2050
    ],
    "description": "Where the mountains meet the metropolis.",
    "lat": 22.283602,
    "lon": 114.159719
  },
  "wanchai": {
    "region": "island",
    "title": "Wan Chai",
    "zh": "灣仔",
    "target": [
      1390,
      90,
      680
    ],
    "spawn": [
      1390,
      920
    ],
    "offset": [
      1500,
      1150,
      -1500
    ],
    "description": "A thousand stories between the streets.",
    "lat": 22.281255,
    "lon": 114.173206
  },
  "northpoint": {
    "region": "island",
    "title": "North Point",
    "zh": "北角",
    "target": [
      4151,
      80,
      -399
    ],
    "spawn": [
      4151,
      -399
    ],
    "offset": [
      1500,
      1250,
      -1600
    ],
    "description": "Follow the shoreline further east.",
    "lat": 22.290997,
    "lon": 114.199999
  },
  "chaiwan": {
    "region": "island",
    "title": "Chai Wan",
    "zh": "柴灣",
    "target": [
      8068,
      80,
      2479
    ],
    "spawn": [
      8068,
      2479
    ],
    "offset": [
      1500,
      1250,
      -1600
    ],
    "description": "A city tucked beneath the eastern hills.",
    "lat": 22.264997,
    "lon": 114.237998
  },
  "aberdeen": {
    "region": "island",
    "title": "Aberdeen",
    "zh": "香港仔",
    "target": [
      -487,
      80,
      4252
    ],
    "spawn": [
      -486.1,
      4268.2
    ],
    "offset": [
      1400,
      1150,
      1500
    ],
    "description": "The other harbour, beyond the ridge.",
    "arrivalSource": "https://www.openstreetmap.org/way/1307678037",
    "lat": 22.248996,
    "lon": 114.154998
  },
  "stanley": {
    "region": "island",
    "title": "Stanley",
    "zh": "赤柱",
    "target": [
      5390,
      80,
      7684
    ],
    "spawn": [
      5393.8,
      7655.0
    ],
    "offset": [
      1000,
      900,
      1200
    ],
    "description": "Village streets beside the southern sea.",
    "arrivalSource": "https://www.openstreetmap.org/way/96822889",
    "lat": 22.218,
    "lon": 114.212004
  },
  "kowloon": {
    "region": "kowloon",
    "title": "Kowloon waterfront",
    "zh": "尖沙咀",
    "target": [
      750,
      90,
      -1020
    ],
    "spawn": [
      998,
      -853
    ],
    "offset": [
      -1600,
      1300,
      2000
    ],
    "description": "Across the water, another world awaits.",
    "lat": 22.296607,
    "lon": 114.166995
  },
  "mongkok": {
    "region": "kowloon",
    "title": "Mong Kok",
    "zh": "旺角",
    "target": [
      957,
      80,
      -3511
    ],
    "spawn": [
      937.0,
      -3511.8
    ],
    "offset": [
      1700,
      1550,
      1650
    ],
    "description": "Street upon street, story upon story.",
    "lat": 22.319102,
    "lon": 114.169003,
    "arrivalSource": "https://www.openstreetmap.org/way/970658225",
    "terrainY": 5.146
  },
  "shamshuipo": {
    "region": "kowloon",
    "title": "Sham Shui Po",
    "zh": "深水埗",
    "target": [
      236,
      80,
      -4718
    ],
    "spawn": [
      244.0,
      -4727.6
    ],
    "offset": [
      1500,
      1350,
      1800
    ],
    "description": "Old neighbourhoods and everyday discoveries.",
    "arrivalSource": "https://www.openstreetmap.org/way/1303898515",
    "lat": 22.330001,
    "lon": 114.162004
  },
  "kowloonbay": {
    "region": "kowloon",
    "title": "Kowloon Bay",
    "zh": "九龍灣",
    "target": [
      4975,
      80,
      -3943
    ],
    "spawn": [
      4990.4,
      -3944.4
    ],
    "offset": [
      -1600,
      1400,
      1800
    ],
    "description": "Industrial roots, a changing waterfront.",
    "arrivalSource": "https://www.openstreetmap.org/way/1220677250",
    "lat": 22.323,
    "lon": 114.208002
  },
  "lantau": {
    "region": "lantau",
    "title": "Tung Chung",
    "zh": "東涌",
    "description": "A new town at the foot of Lantau’s mountains.",
    "offset": [
      1700,
      1300,
      -1800
    ],
    "target": [
      -22510.8,
      70,
      -218.0
    ],
    "spawn": [
      -22500.5,
      -198.9
    ],
    "lat": 22.289193,
    "lon": 113.941276,
    "source": "https://www.openstreetmap.org/way/45725781"
  },
  "discoverybay": {
    "region": "lantau",
    "title": "Discovery Bay",
    "zh": "愉景灣",
    "target": [
      -14706,
      80,
      -1183
    ],
    "spawn": [
      -14683.6,
      -1056.0
    ],
    "offset": [
      1400,
      1100,
      -1300
    ],
    "description": "A hillside neighbourhood opening onto the water.",
    "arrivalSource": "https://www.openstreetmap.org/way/386427029",
    "lat": 22.298,
    "lon": 114.017003
  },
  "muiwo": {
    "region": "lantau",
    "title": "Mui Wo",
    "zh": "梅窩",
    "description": "Silvermine Bay, villages and a slower pace.",
    "offset": [
      1000,
      900,
      1100
    ],
    "target": [
      -16540.4,
      40,
      2297.2
    ],
    "spawn": [
      -16551.2,
      2282.0
    ],
    "lat": 22.266553,
    "lon": 113.999241,
    "source": "https://www.openstreetmap.org/way/552532081"
  },
  "taio": {
    "region": "lantau",
    "title": "Tai O",
    "zh": "大澳",
    "description": "A fishing village between mountains and tidal creeks.",
    "offset": [
      -950,
      850,
      900
    ],
    "target": [
      -30337.9,
      30,
      3638.8
    ],
    "spawn": [
      -30308.9,
      3655.8
    ],
    "lat": 22.254237,
    "lon": 113.865401,
    "source": "https://www.openstreetmap.org/way/680293250"
  },
  "lantaupeaks": {
    "region": "lantau",
    "title": "Lantau mountains",
    "zh": "大嶼山山巒",
    "target": [
      -22440,
      300,
      2273
    ],
    "spawn": [
      -22440,
      2273
    ],
    "offset": [
      7400,
      5700,
      7200
    ],
    "description": "The high country between the settlements.",
    "lat": 22.266699,
    "lon": 113.942001
  },
  "kowlooncity": {
    "region": "kowloon",
    "title": "Kowloon City",
    "zh": "九龍城",
    "description": "Kowloon Walled City Park, beside the former Yamen building.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      3166.7,
      80,
      -4967.3
    ],
    "spawn": [
      3169.3,
      -4957.9
    ],
    "lat": 22.332253,
    "lon": 114.190452,
    "source": "https://www.openstreetmap.org/relation/18506822",
    "arrivalSource": "https://www.openstreetmap.org/way/1348776549",
    "terrainY": 13.491
  },
  "wongtaisin": {
    "region": "kowloon",
    "title": "Wong Tai Sin",
    "zh": "黃大仙",
    "description": "Temple gardens and the neighbourhood beneath Lion Rock.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      3455.2,
      80,
      -5563.7
    ],
    "spawn": [
      3455.4,
      -5563.4
    ],
    "lat": 22.337638,
    "lon": 114.193252,
    "source": "https://www.openstreetmap.org/way/263310067"
  },
  "tsuenwan": {
    "region": "ntwest",
    "title": "Tsuen Wan",
    "zh": "荃灣",
    "description": "A waterfront park beside the western new town.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      -4803.6,
      80,
      -8828.9
    ],
    "spawn": [
      -4803.3,
      -8840.1
    ],
    "lat": 22.367113,
    "lon": 114.113069,
    "source": "https://www.openstreetmap.org/way/359379157"
  },
  "tsingyi": {
    "region": "ntwest",
    "title": "Tsing Yi",
    "zh": "青衣",
    "description": "Parks and housing between the island’s hills and harbour.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      -5599.3,
      70,
      -7603.4
    ],
    "spawn": [
      -5596.8,
      -7604.8
    ],
    "lat": 22.356043,
    "lon": 114.105349,
    "source": "https://www.openstreetmap.org/way/205770060"
  },
  "tuenmun": {
    "region": "ntwest",
    "title": "Tuen Mun",
    "zh": "屯門",
    "description": "The town park and river between western hills.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      -19168.5,
      70,
      -11529.9
    ],
    "spawn": [
      -19162.7,
      -11524.2
    ],
    "lat": 22.391389,
    "lon": 113.973561,
    "source": "https://www.openstreetmap.org/way/55444337"
  },
  "yuenlong": {
    "region": "ntwest",
    "title": "Yuen Long",
    "zh": "元朗",
    "description": "A town surrounded by villages and the northern plain.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      -14497.2,
      70,
      -17110.2
    ],
    "spawn": [
      -14499.2,
      -17112.7
    ],
    "lat": 22.441833,
    "lon": 114.018867,
    "source": "https://www.openstreetmap.org/way/157811032"
  },
  "tinshuiwai": {
    "region": "ntwest",
    "title": "Tin Shui Wai",
    "zh": "天水圍",
    "description": "Residential towers around a connected network of parks.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      -16204.8,
      65,
      -18722.4
    ],
    "spawn": [
      -16207.1,
      -18719.6
    ],
    "lat": 22.456375,
    "lon": 114.00226,
    "source": "https://www.openstreetmap.org/way/25637587"
  },
  "shatin": {
    "region": "nteast",
    "title": "Sha Tin",
    "zh": "沙田",
    "description": "Follow the Shing Mun River through the new town.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      3049.3,
      80,
      -10189.7
    ],
    "spawn": [
      3045.6,
      -10192.9
    ],
    "lat": 22.379414,
    "lon": 114.189316,
    "source": "https://www.openstreetmap.org/way/32559006"
  },
  "maonshan": {
    "region": "nteast",
    "title": "Ma On Shan",
    "zh": "馬鞍山",
    "description": "The waterfront below the saddle-shaped mountain.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      7297.5,
      65,
      -15384.1
    ],
    "spawn": [
      7295.1,
      -15405.8
    ],
    "lat": 22.426313,
    "lon": 114.230584,
    "source": "https://www.openstreetmap.org/way/150664686"
  },
  "taipo": {
    "region": "nteast",
    "title": "Tai Po",
    "zh": "大埔",
    "description": "Waterfront gardens opening onto Tolo Harbour.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      2328.5,
      60,
      -18190.4
    ],
    "spawn": [
      2314.0,
      -18284.5
    ],
    "lat": 22.451665,
    "lon": 114.18232,
    "source": "https://www.openstreetmap.org/way/111577520"
  },
  "taimeituk": {
    "region": "nteast",
    "title": "Tai Mei Tuk",
    "zh": "大美督",
    "description": "Village lanes, a reservoir and the hills of Pat Sin Leng.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      7607.3,
      45,
      -20039.3
    ],
    "spawn": [
      7664.1,
      -20070.4
    ],
    "lat": 22.468351,
    "lon": 114.233611,
    "source": "https://www.openstreetmap.org/relation/11598542"
  },
  "saikung": {
    "region": "nteast",
    "title": "Sai Kung",
    "zh": "西貢",
    "description": "The harbour town at the gateway to the eastern countryside.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      11826.3,
      50,
      -10534.5
    ],
    "spawn": [
      11826.9,
      -10534.0
    ],
    "lat": 22.382499,
    "lon": 114.274544,
    "source": "https://www.openstreetmap.org/way/266586309"
  },
  "tseungkwano": {
    "region": "nteast",
    "title": "Tseung Kwan O",
    "zh": "將軍澳",
    "description": "Promenades and new neighbourhoods around Junk Bay.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      10456.2,
      65,
      -1637.5
    ],
    "spawn": [
      10453.4,
      -1641.6
    ],
    "lat": 22.302161,
    "lon": 114.261191,
    "source": "https://www.openstreetmap.org/way/311764682"
  },
  "sheungshui": {
    "region": "ntnorth",
    "title": "Sheung Shui",
    "zh": "上水",
    "description": "Town streets around North District Town Hall.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      -3184.9,
      65,
      -23701.2
    ],
    "spawn": [
      -3199.3,
      -23686.9
    ],
    "lat": 22.501422,
    "lon": 114.128739,
    "source": "https://www.openstreetmap.org/way/255289130"
  },
  "fanling": {
    "region": "ntnorth",
    "title": "Fanling",
    "zh": "粉嶺",
    "description": "Station-side streets linking the northern new towns.",
    "offset": [
      1500,
      1250,
      -1600
    ],
    "target": [
      -1975.7,
      65,
      -22584.9
    ],
    "spawn": [
      -1970.3,
      -22592.3
    ],
    "lat": 22.491345,
    "lon": 114.140493,
    "source": "https://www.openstreetmap.org/way/354970547"
  },
  "cheungchau": {
    "region": "islands",
    "title": "Cheung Chau",
    "zh": "長洲",
    "description": "A compact harbour town with a pedestrian waterfront.",
    "offset": [
      -900,
      750,
      1000
    ],
    "target": [
      -13547.3,
      40,
      8719.6
    ],
    "spawn": [
      -13507.6,
      8715.5
    ],
    "lat": 22.208584,
    "lon": 114.028342,
    "source": "https://www.openstreetmap.org/way/182368836"
  },
  "pengchau": {
    "region": "islands",
    "title": "Peng Chau",
    "zh": "坪洲",
    "description": "Ferry-side lanes and a small island’s working waterfront.",
    "offset": [
      -900,
      750,
      1000
    ],
    "target": [
      -12635.3,
      35,
      305.2
    ],
    "spawn": [
      -12664.7,
      208.9
    ],
    "lat": 22.284579,
    "lon": 114.037111,
    "source": "https://www.openstreetmap.org/way/174414610"
  },
  "lamma": {
    "region": "islands",
    "title": "Yung Shue Wan",
    "zh": "榕樹灣",
    "description": "Lamma’s village waterfront and paths into the hills.",
    "offset": [
      -900,
      750,
      1000
    ],
    "target": [
      -5011.7,
      40,
      6701.3
    ],
    "spawn": [
      -5017.9,
      6679.2
    ],
    "lat": 22.226865,
    "lon": 114.111114,
    "source": "https://www.openstreetmap.org/way/763007436",
    "arrivalSource": "https://www.openstreetmap.org/way/530132789",
    "terrainY": 10.974
  },
  "sokkwuwan": {
    "region": "islands",
    "title": "Sok Kwu Wan",
    "zh": "索罟灣",
    "description": "A sheltered bay on the eastern side of Lamma.",
    "offset": [
      -900,
      750,
      1000
    ],
    "target": [
      -2890.9,
      35,
      9033.4
    ],
    "spawn": [
      -2888.1,
      9026.4
    ],
    "lat": 22.205812,
    "lon": 114.131692,
    "source": "https://www.openstreetmap.org/way/763007432"
  },
  "tapmun": {
    "region": "islands",
    "title": "Tap Mun",
    "zh": "塔門",
    "description": "Village lanes and grassy slopes beside the eastern sea.",
    "offset": [
      -900,
      750,
      1000
    ],
    "target": [
      20862.5,
      55.8,
      -20440.6
    ],
    "spawn": [
      20864.3,
      -20432.3
    ],
    "lat": 22.471879,
    "lon": 114.362407,
    "source": "https://www.openstreetmap.org/way/1472167849"
  },
  "tungpingchau": {
    "region": "islands",
    "title": "Tung Ping Chau",
    "zh": "東平洲",
    "description": "A remote northeastern island on the edge of the terrain map.",
    "offset": [
      -900,
      750,
      950
    ],
    "target": [
      28165.6,
      30,
      -28550.9
    ],
    "spawn": [
      28099.3,
      -28495.2
    ],
    "lat": 22.54502,
    "lon": 114.433503,
    "source": "https://www.openstreetmap.org/way/1255462870"
  },
  "potoi": {
    "region": "islands",
    "title": "Po Toi",
    "zh": "蒲台",
    "description": "Southern island paths above rocky bays.",
    "offset": [
      -900,
      750,
      1000
    ],
    "target": [
      10046.1,
      107.1,
      13573.8
    ],
    "spawn": [
      10046.1,
      13573.8
    ],
    "lat": 22.164795,
    "lon": 114.257133,
    "source": "https://www.openstreetmap.org/way/155551381"
  },
  "puio": {
    "region": "lantau",
    "title": "Pui O",
    "zh": "貝澳",
    "description": "Village lanes between the wetlands, beach and Lantau’s southern hills.",
    "offset": [
      1100,
      900,
      1200
    ],
    "target": [
      -18798.4,
      45,
      5085.0
    ],
    "spawn": [
      -18839.7,
      5018.7
    ],
    "lat": 22.241353,
    "lon": 113.977369,
    "source": "https://www.openstreetmap.org/way/1422842689"
  },
  "cheungsha": {
    "region": "lantau",
    "title": "Cheung Sha",
    "zh": "長沙",
    "description": "Hillside villages above the long southern beaches.",
    "offset": [
      1100,
      900,
      1200
    ],
    "target": [
      -20563.0,
      54.8,
      5729.1
    ],
    "spawn": [
      -20689.9,
      5707.2
    ],
    "lat": 22.235514,
    "lon": 113.96026,
    "source": "https://www.openstreetmap.org/way/1347945823"
  },
  "tongfuk": {
    "region": "lantau",
    "title": "Tong Fuk",
    "zh": "塘福",
    "description": "Village streets opening towards the south coast.",
    "offset": [
      1100,
      900,
      1200
    ],
    "target": [
      -23380.6,
      45,
      6543.4
    ],
    "spawn": [
      -23362.1,
      6572.6
    ],
    "lat": 22.228122,
    "lon": 113.932941,
    "source": "https://www.openstreetmap.org/way/700447115"
  },
  "shuihau": {
    "region": "lantau",
    "title": "Shui Hau",
    "zh": "水口",
    "description": "A village beside broad tidal flats and the western hills.",
    "offset": [
      1100,
      900,
      1200
    ],
    "target": [
      -25160.9,
      48.3,
      7224.5
    ],
    "spawn": [
      -25161.0,
      7231.8
    ],
    "lat": 22.221944,
    "lon": 113.915685,
    "source": "https://www.openstreetmap.org/way/700272388"
  },
  "ngongping": {
    "region": "lantau",
    "title": "Ngong Ping",
    "zh": "昂坪",
    "description": "The high plateau around Po Lin Monastery and the Big Buddha.",
    "offset": [
      1100,
      900,
      1200
    ],
    "target": [
      -26122.9,
      473.8,
      3617.6
    ],
    "spawn": [
      -26111.4,
      3621.4
    ],
    "lat": 22.254501,
    "lon": 113.906291,
    "source": "https://www.openstreetmap.org/way/700634975"
  },
  "tungchungvalley": {
    "region": "lantau",
    "title": "Tung Chung valley",
    "zh": "東涌谷",
    "description": "The old fort and villages at the entrance to Tung Chung valley.",
    "offset": [
      1100,
      900,
      1200
    ],
    "target": [
      -23055.1,
      55,
      999.3
    ],
    "spawn": [
      -23064.8,
      1003.8
    ],
    "lat": 22.278192,
    "lon": 113.936014,
    "source": "https://www.openstreetmap.org/way/543838006"
  }
};
export const PLACES={...BASE_PLACES,...REGIONAL_PLACES};
export function closestPlace(x,z){return Object.entries(PLACES).filter(([id])=>id!=='lantaupeaks').sort((a,b)=>Math.hypot(a[1].target[0]-x,a[1].target[2]-z)-Math.hypot(b[1].target[0]-x,b[1].target[2]-z))[0][0];}
