// Generated by source-scripts/city/build_regional.py. Source-based browsing positions, not surveyed locations.
export const REGIONAL_PLACES={
  "tungchungpublicpier": {
    "region": "lantau",
    "title": "Tung Chung public pier",
    "zh": "東涌公眾碼頭",
    "sectionId": "10.1",
    "description": "A checked waterfront approach beside the mapped public pier.",
    "source": "https://www.openstreetmap.org/way/98082723",
    "lat": 22.286237,
    "lon": 113.934293,
    "target": [
      -23231.0,
      35,
      108.2
    ],
    "spawn": [
      -23191.2,
      112.0
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/549536113"
  },
  "pakmong": {
    "region": "lantau",
    "title": "Pak Mong village",
    "zh": "白芒村",
    "sectionId": "10.2",
    "description": "Public village paths on the northern Lantau coast.",
    "source": "https://www.openstreetmap.org/way/700985402",
    "lat": 22.29566,
    "lon": 113.971911,
    "target": [
      -19352.9,
      46.9,
      -929.5
    ],
    "spawn": [
      -19401.4,
      -907.4
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/199999616"
  },
  "airportterminal": {
    "region": "lantau",
    "title": "Airport Terminal 1",
    "zh": "機場一號客運大樓",
    "sectionId": "10.3",
    "description": "The terminal complex and mapped airport aprons; walking starts outside the building where a checked public approach exists.",
    "source": "https://www.openstreetmap.org/way/772085062",
    "lat": 22.314584,
    "lon": 113.931937,
    "target": [
      -23468.7,
      38.0,
      -3031.2
    ],
    "spawn": [
      -23272.2,
      -3358.0
    ],
    "offset": [
      2200,
      1700,
      -2400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1374665971"
  },
  "asiaworldexpo": {
    "region": "lantau",
    "title": "AsiaWorld-Expo",
    "zh": "亞洲國際博覽館",
    "sectionId": "10.4",
    "description": "Airport-city approaches beside the exhibition complex.",
    "source": "https://www.openstreetmap.org/way/23398992",
    "lat": 22.321339,
    "lon": 113.943278,
    "target": [
      -22299.0,
      37.0,
      -3777.3
    ],
    "spawn": [
      -22216.4,
      -3698.8
    ],
    "offset": [
      1900,
      1450,
      -1800
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1322032939"
  },
  "nimshuewan": {
    "region": "lantau",
    "title": "Nim Shue Wan",
    "zh": "稔樹灣",
    "sectionId": "10.5",
    "description": "Village paths near the mapped Tin Hau Temple and Discovery Bay's southern shore.",
    "source": "https://www.openstreetmap.org/way/243848749",
    "lat": 22.291076,
    "lon": 114.018857,
    "target": [
      -14515.7,
      45.1,
      -416.1
    ],
    "spawn": [
      -14519.0,
      -412.1
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/275227013"
  },
  "silverminebaybeach": {
    "region": "lantau",
    "title": "Silvermine Bay beach",
    "zh": "銀礦灣泳灘",
    "sectionId": "10.6",
    "description": "The mapped beach and promenade on the northern side of Mui Wo's bay.",
    "source": "https://www.openstreetmap.org/way/42391122",
    "lat": 22.269707,
    "lon": 113.999005,
    "target": [
      -16564.3,
      35,
      1947.9
    ],
    "spawn": [
      -16593.1,
      1933.3
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/204797330"
  },
  "chimawanpier": {
    "region": "lantau",
    "title": "Chi Ma Wan pier",
    "zh": "芝麻灣碼頭",
    "sectionId": "10.7",
    "description": "A peninsula-side public path near the mapped ferry landing.",
    "source": "https://www.openstreetmap.org/way/101704925",
    "lat": 22.239572,
    "lon": 113.999967,
    "target": [
      -16469.0,
      35,
      5285.0
    ],
    "spawn": [
      -16483.5,
      5592.1
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/893934215"
  },
  "puiobeach": {
    "region": "lantau",
    "title": "Pui O beach",
    "zh": "貝澳泳灘",
    "sectionId": "10.7",
    "description": "The mapped beach beside Pui O's village and wetland edge.",
    "source": "https://www.openstreetmap.org/way/35900298",
    "lat": 22.239231,
    "lon": 113.977325,
    "target": [
      -18803.2,
      35,
      5319.9
    ],
    "spawn": [
      -18777.1,
      5271.6
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/107501760"
  },
  "lowercheungshabeach": {
    "region": "lantau",
    "title": "Lower Cheung Sha beach",
    "zh": "下長沙泳灘",
    "sectionId": "10.8",
    "description": "A public approach to the long mapped southern beach.",
    "source": "https://www.openstreetmap.org/way/102774743",
    "lat": 22.233911,
    "lon": 113.955343,
    "target": [
      -21070.2,
      35,
      5905.9
    ],
    "spawn": [
      -21046.3,
      5854.1
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/197995504"
  },
  "uppercheungshabeach": {
    "region": "lantau",
    "title": "Upper Cheung Sha beach",
    "zh": "上長沙泳灘",
    "sectionId": "10.8",
    "description": "The western continuation of Cheung Sha's beach landscape.",
    "source": "https://www.openstreetmap.org/way/102774742",
    "lat": 22.232483,
    "lon": 113.94652,
    "target": [
      -21980.0,
      35,
      6062.6
    ],
    "spawn": [
      -21732.4,
      5804.2
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/692542483"
  },
  "tongfukbeach": {
    "region": "lantau",
    "title": "Tong Fuk beach",
    "zh": "塘福泳灘",
    "sectionId": "10.8",
    "description": "The mapped beach below Tong Fuk village.",
    "source": "https://www.openstreetmap.org/way/108069823",
    "lat": 22.228134,
    "lon": 113.935449,
    "target": [
      -23122.1,
      35,
      6542.4
    ],
    "spawn": [
      -23111.0,
      6485.9
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/448892366"
  },
  "shekpik": {
    "region": "lantau",
    "title": "Shek Pik reservoir approach",
    "zh": "石壁水塘入口",
    "sectionId": "10.9",
    "description": "Public paths beside the reservoir's southern approach; the terrain and dam remain the existing model.",
    "source": "https://www.openstreetmap.org/way/307414722",
    "lat": 22.228061,
    "lon": 113.891069,
    "target": [
      -27697.6,
      103.3,
      6542.6
    ],
    "spawn": [
      -27693.8,
      6550.5
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1332586339"
  },
  "fanlau": {
    "region": "lantau",
    "title": "Fan Lau village",
    "zh": "分流村",
    "sectionId": "10.9",
    "description": "A remote village path at the southwestern end of Lantau.",
    "source": "https://www.openstreetmap.org/way/700697669",
    "lat": 22.20299,
    "lon": 113.849697,
    "target": [
      -31968.9,
      41.8,
      9310.2
    ],
    "spawn": [
      -31968.5,
      9305.5
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/239150213"
  },
  "taiopromenade": {
    "region": "lantau",
    "title": "Tai O promenade",
    "zh": "大澳海濱長廊",
    "sectionId": "10.10",
    "description": "A checked shore approach near the mapped promenade landing. The source notes imagery distortion, so the footprint needs local review.",
    "source": "https://www.openstreetmap.org/way/115584709",
    "lat": 22.252478,
    "lon": 113.860967,
    "target": [
      -30795.4,
      35,
      3832.6
    ],
    "spawn": [
      -30796.6,
      3830.3
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1187601818"
  },
  "shalowan": {
    "region": "lantau",
    "title": "Sha Lo Wan",
    "zh": "沙螺灣",
    "sectionId": "10.10",
    "description": "Northwestern village paths near the mapped public pier.",
    "source": "https://www.openstreetmap.org/way/101715581",
    "lat": 22.293509,
    "lon": 113.90406,
    "target": [
      -26345.2,
      35,
      -702.3
    ],
    "spawn": [
      -26338.2,
      -662.9
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1187601798"
  },
  "polinforecourt": {
    "region": "lantau",
    "title": "Po Lin Monastery approach",
    "zh": "寶蓮禪寺入口",
    "sectionId": "10.11",
    "description": "The high-plateau paths and mapped pedestrian spaces around Po Lin Monastery.",
    "source": "https://www.openstreetmap.org/way/486775883",
    "lat": 22.254814,
    "lon": 113.907932,
    "target": [
      -25953.8,
      474.6,
      3583.3
    ],
    "spawn": [
      -25952.3,
      3626.1
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1232576232"
  },
  "pengchaupublicpier": {
    "region": "islands",
    "title": "Peng Chau public pier",
    "zh": "坪洲公眾碼頭",
    "sectionId": "10.12",
    "description": "A checked inland approach to the mapped public landing and village waterfront.",
    "source": "https://www.openstreetmap.org/way/246580863",
    "lat": 22.284246,
    "lon": 114.037933,
    "target": [
      -12550.6,
      35,
      342.2
    ],
    "spawn": [
      -12501.4,
      310.2
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1324438780"
  },
  "heilingchauaerial": {
    "region": "islands",
    "title": "Hei Ling Chau aerial view",
    "zh": "喜靈洲空中景觀",
    "sectionId": "10.12",
    "description": "Aerial view of the island. This detail pass does not provide a public walking arrival.",
    "source": "https://www.openstreetmap.org/relation/12923646",
    "lat": 22.251973,
    "lon": 114.03898,
    "target": [
      -12446.0,
      146.0,
      3916.0
    ],
    "spawn": [
      -12446.0,
      3916.0
    ],
    "offset": [
      1400,
      1000,
      -1500
    ],
    "aerialOnly": true
  },
  "cheungchautungwan": {
    "region": "islands",
    "title": "Cheung Chau Tung Wan",
    "zh": "長洲東灣",
    "sectionId": "10.13",
    "description": "The mapped eastern beach, with a checked approach through village paths.",
    "source": "https://www.openstreetmap.org/way/44717226",
    "lat": 22.210795,
    "lon": 114.030057,
    "target": [
      -13370.2,
      35,
      8474.9
    ],
    "spawn": [
      -13401.1,
      8512.9
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/364730759"
  },
  "cheungchaupublicpier": {
    "region": "islands",
    "title": "Cheung Chau public pier",
    "zh": "長洲公眾碼頭",
    "sectionId": "10.13",
    "description": "The harbour's mapped public landing and pedestrian waterfront.",
    "source": "https://www.openstreetmap.org/way/436984437",
    "lat": 22.207991,
    "lon": 114.028462,
    "target": [
      -13535.0,
      35,
      8785.3
    ],
    "spawn": [
      -13535.0,
      8785.3
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/532296387"
  },
  "hungshingyeh": {
    "region": "islands",
    "title": "Hung Shing Yeh beach",
    "zh": "洪聖爺灣泳灘",
    "sectionId": "10.14",
    "description": "A mapped beach along northern Lamma's coastal walking paths.",
    "source": "https://www.openstreetmap.org/way/52298447",
    "lat": 22.218801,
    "lon": 114.119589,
    "target": [
      -4138.3,
      35,
      7594.6
    ],
    "spawn": [
      -4120.0,
      7570.2
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1375817262"
  },
  "lososhing": {
    "region": "islands",
    "title": "Lo So Shing beach",
    "zh": "蘆鬚城泳灘",
    "sectionId": "10.15",
    "description": "A mapped southern Lamma beach reached from retained public paths.",
    "source": "https://www.openstreetmap.org/way/26519927",
    "lat": 22.204454,
    "lon": 114.12256,
    "target": [
      -3832.5,
      35.5,
      9183.4
    ],
    "spawn": [
      -3802.0,
      9167.0
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/26519924"
  },
  "sokkwuwanpublicpier": {
    "region": "islands",
    "title": "Sok Kwu Wan public pier",
    "zh": "索罟灣公眾碼頭",
    "sectionId": "10.15",
    "description": "A checked shore approach near the mapped village landing.",
    "source": "https://www.openstreetmap.org/way/109740650",
    "lat": 22.205639,
    "lon": 114.130939,
    "target": [
      -2968.5,
      35,
      9052.5
    ],
    "spawn": [
      -2963.8,
      9054.1
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/378602249"
  },
  "potoipublicpier": {
    "region": "islands",
    "title": "Po Toi public pier",
    "zh": "蒲台公眾碼頭",
    "sectionId": "10.16",
    "description": "A checked island path near the mapped public landing.",
    "source": "https://www.openstreetmap.org/way/449056701",
    "lat": 22.165041,
    "lon": 114.253113,
    "target": [
      9631.4,
      35,
      13546.8
    ],
    "spawn": [
      9629.4,
      13533.4
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/143741972"
  },
  "sokoislandsaerial": {
    "region": "islands",
    "title": "Soko Islands aerial view",
    "zh": "索罟群島空中景觀",
    "sectionId": "10.16",
    "description": "Aerial view over Tai A Chau and the Soko island group; no checked public walking arrival is supplied.",
    "source": "https://www.openstreetmap.org/relation/14384590",
    "lat": 22.162686,
    "lon": 113.908397,
    "target": [
      -25923.9,
      75.1,
      13785.1
    ],
    "spawn": [
      -25923.9,
      13785.1
    ],
    "offset": [
      1600,
      1200,
      -1700
    ],
    "aerialOnly": true
  },
  "sunnybay": {
    "region": "lantau",
    "title": "Sunny Bay station approach",
    "zh": "欣澳站入口",
    "sectionId": "11.6",
    "description": "A checked public approach to Sunny Bay and the northeastern coast.",
    "source": "https://www.openstreetmap.org/way/334664293",
    "lat": 22.331826,
    "lon": 114.028606,
    "target": [
      -13506.7,
      37.0,
      -4927.5
    ],
    "spawn": [
      -13512.8,
      -4932.7
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1372806502"
  },
  "yamolukkeng": {
    "region": "lantau",
    "title": "Yam O and Luk Keng pier",
    "zh": "陰澳鹿頸碼頭",
    "sectionId": "11.6",
    "description": "Mapped coastal paths near the old village landing.",
    "source": "https://www.openstreetmap.org/way/101695604",
    "lat": 22.331896,
    "lon": 114.024266,
    "target": [
      -13953.8,
      35,
      -4935.7
    ],
    "spawn": [
      -13971.0,
      -4948.9
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/312366056"
  },
  "inspirationlake": {
    "region": "lantau",
    "title": "Inspiration Lake",
    "zh": "迪欣湖",
    "sectionId": "11.7",
    "description": "Mapped public recreation paths near Penny's Bay.",
    "source": "https://www.openstreetmap.org/way/31858217",
    "lat": 22.322533,
    "lon": 114.037604,
    "target": [
      -12580.6,
      37.5,
      -3897.5
    ],
    "spawn": [
      -12570.9,
      -4020.6
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/100781816"
  },
  "disneylandresortpier": {
    "region": "lantau",
    "title": "Disneyland Resort pier",
    "zh": "迪士尼碼頭",
    "sectionId": "11.7",
    "description": "The mapped waterfront landing and nearby promenade; this visit point is outside the theme-park attractions.",
    "source": "https://www.openstreetmap.org/way/101695603",
    "lat": 22.306791,
    "lon": 114.04575,
    "target": [
      -11742.9,
      35,
      -2153.6
    ],
    "spawn": [
      -11752.2,
      -2180.4
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/642352498"
  },
  "tapmunpier": {
    "region": "islands",
    "title": "Tap Mun public pier",
    "zh": "塔門碼頭",
    "sectionId": "14.8",
    "description": "A checked village path near the mapped public landing on Grass Island.",
    "source": "https://www.openstreetmap.org/way/134396010",
    "lat": 22.470318,
    "lon": 114.358688,
    "target": [
      20480.0,
      35,
      -20267.3
    ],
    "spawn": [
      20494.0,
      -20260.2
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/386427049"
  },
  "tungpingchaupier": {
    "region": "islands",
    "title": "Tung Ping Chau pier approach",
    "zh": "東平洲碼頭入口",
    "sectionId": "14.8",
    "description": "A checked inland path near the northeastern island's mapped public pier.",
    "source": "https://www.openstreetmap.org/way/102306135",
    "lat": 22.544796,
    "lon": 114.433218,
    "target": [
      28136.4,
      35,
      -28526.1
    ],
    "spawn": [
      28105.6,
      -28500.5
    ],
    "offset": [
      1150,
      950,
      1250
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/386427053"
  },
  "section-01-1": {
    "region": "island",
    "title": "Statue Square",
    "zh": "皇后像廣場",
    "sectionId": "01.1",
    "description": "Central's civic square and the adjoining banking streets.",
    "source": "https://www.openstreetmap.org/relation/6970394",
    "lat": 22.281342,
    "lon": 114.1599493,
    "target": [
      23.8,
      50.2,
      670.2
    ],
    "spawn": [
      24.8,
      666.9
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/746368315"
  },
  "section-01-2": {
    "region": "island",
    "title": "Tamar & Central waterfront",
    "zh": "添馬與中環海濱",
    "sectionId": "01.2",
    "description": "Harbourfront paths between Admiralty, Tamar and the Central piers.",
    "source": "https://www.openstreetmap.org/way/138602057",
    "lat": 22.2811466,
    "lon": 114.1655944,
    "target": [
      605.5,
      51.0,
      691.9
    ],
    "spawn": [
      652.6,
      631.9
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/142227306"
  },
  "section-01-3": {
    "region": "island",
    "title": "SoHo & Shelley Street",
    "zh": "蘇豪與些利街",
    "sectionId": "01.3",
    "description": "The stepped street grid around the Mid-Levels escalator corridor.",
    "source": "https://www.openstreetmap.org/way/817778707",
    "lat": 22.2815409,
    "lon": 114.1528602,
    "target": [
      -706.8,
      95.5,
      648.1
    ],
    "spawn": [
      -706.8,
      648.1
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/817778707"
  },
  "section-01-4": {
    "region": "island",
    "title": "Sheung Wan & Hollywood Road",
    "zh": "上環與荷李活道",
    "sectionId": "01.4",
    "description": "Older streets, small parks and the Tai Ping Shan neighbourhood.",
    "source": "https://www.openstreetmap.org/way/148228845",
    "lat": 22.2860782,
    "lon": 114.1476834,
    "target": [
      -1240.2,
      57.4,
      145.6
    ],
    "spawn": [
      -1238.2,
      142.2
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1112227929"
  },
  "section-01-5": {
    "region": "island",
    "title": "Sai Ying Pun",
    "zh": "西營盤",
    "sectionId": "01.5",
    "description": "Hillside blocks around King George V Memorial Park.",
    "source": "https://www.openstreetmap.org/way/26201750",
    "lat": 22.2855876,
    "lon": 114.1443568,
    "target": [
      -1583.1,
      84.8,
      199.9
    ],
    "spawn": [
      -1583.3,
      209.8
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/583518391"
  },
  "section-01-6": {
    "region": "island",
    "title": "Kennedy Town waterfront",
    "zh": "堅尼地城海濱",
    "sectionId": "01.6",
    "description": "Belcher Bay's promenade and the western end of the island city.",
    "source": "https://www.openstreetmap.org/way/761609177",
    "lat": 22.2852361,
    "lon": 114.1291784,
    "target": [
      -3147.3,
      50.1,
      238.4
    ],
    "spawn": [
      -3156.6,
      228.4
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/875004399"
  },
  "section-01-7": {
    "region": "island",
    "title": "Lugard Road & the Peak",
    "zh": "盧吉道與山頂",
    "sectionId": "01.7",
    "description": "A mapped pedestrian route above Central's hillside neighbourhoods.",
    "source": "https://www.openstreetmap.org/way/300497950",
    "lat": 22.2742429,
    "lon": 114.1490003,
    "target": [
      -1104.8,
      453.4,
      1456.2
    ],
    "spawn": [
      -1104.8,
      1456.2
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/300497950"
  },
  "section-02-1": {
    "region": "island",
    "title": "Wan Chai old town",
    "zh": "灣仔舊城",
    "sectionId": "02.1",
    "description": "Queen's Road East streets and the public paths beside Wan Chai Park.",
    "source": "https://www.openstreetmap.org/way/184798477",
    "lat": 22.2755583,
    "lon": 114.1760664,
    "target": [
      1684.7,
      61.8,
      1310.8
    ],
    "spawn": [
      1684.3,
      1307.1
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/563642425"
  },
  "section-02-2": {
    "region": "island",
    "title": "Golden Bauhinia waterfront",
    "zh": "金紫荊海濱",
    "sectionId": "02.2",
    "description": "The exhibition-centre waterfront and Golden Bauhinia Square.",
    "source": "https://www.openstreetmap.org/way/998741825",
    "lat": 22.2842311,
    "lon": 114.1737936,
    "target": [
      1450.5,
      50.4,
      350.4
    ],
    "spawn": [
      1459.9,
      347.9
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1012390588"
  },
  "section-02-3": {
    "region": "island",
    "title": "Causeway Bay streets",
    "zh": "銅鑼灣街道",
    "sectionId": "02.3",
    "description": "Pak Sha Road and the shopping streets behind the tram corridor.",
    "source": "https://www.openstreetmap.org/way/26469055",
    "lat": 22.2790426,
    "lon": 114.1840514,
    "target": [
      2507.7,
      52.7,
      924.9
    ],
    "spawn": [
      2507.7,
      924.9
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/26469055"
  },
  "section-02-4": {
    "region": "island",
    "title": "Victoria Park & Tin Hau",
    "zh": "維多利亞公園與天后",
    "sectionId": "02.4",
    "description": "The park's courts and paths between Causeway Bay and Tin Hau.",
    "source": "https://www.openstreetmap.org/way/4182605",
    "lat": 22.2825337,
    "lon": 114.1887333,
    "target": [
      2990.1,
      50.9,
      538.3
    ],
    "spawn": [
      3005.0,
      527.2
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/28103872"
  },
  "section-02-5": {
    "region": "island",
    "title": "Happy Valley",
    "zh": "跑馬地",
    "sectionId": "02.5",
    "description": "Wong Nai Chung Road beside the racecourse and hillside residential streets.",
    "source": "https://www.openstreetmap.org/way/1056788258",
    "lat": 22.2734481,
    "lon": 114.1837442,
    "target": [
      2476.0,
      56.6,
      1544.5
    ],
    "spawn": [
      2481.2,
      1542.1
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1056788256"
  },
  "section-03-1": {
    "region": "island",
    "title": "North Point waterfront",
    "zh": "北角海濱",
    "sectionId": "03.1",
    "description": "The North Point promenade and adjoining older residential blocks.",
    "source": "https://www.openstreetmap.org/way/715705487",
    "lat": 22.2933253,
    "lon": 114.2005733,
    "target": [
      4210.1,
      53.0,
      -656.8
    ],
    "spawn": [
      4208.6,
      -664.0
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/457938520"
  },
  "section-03-2": {
    "region": "island",
    "title": "Quarry Bay & Taikoo Place",
    "zh": "鰂魚涌與太古坊",
    "sectionId": "03.2",
    "description": "Quarryside and the public street network around Taikoo Place.",
    "source": "https://www.openstreetmap.org/way/1187351984",
    "lat": 22.2889099,
    "lon": 114.2127217,
    "target": [
      5462.1,
      50.4,
      -168.1
    ],
    "spawn": [
      5449.9,
      -236.0
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1223141054"
  },
  "section-03-3": {
    "region": "island",
    "title": "Sai Wan Ho waterfront",
    "zh": "西灣河海濱",
    "sectionId": "03.3",
    "description": "Harbour Park and the waterfront beside Taikoo Shing and Lei King Wan.",
    "source": "https://www.openstreetmap.org/way/451087473",
    "lat": 22.2870867,
    "lon": 114.2233151,
    "target": [
      6553.9,
      48.0,
      33.5
    ],
    "spawn": [
      6546.2,
      41.4
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1243115495"
  },
  "section-03-4": {
    "region": "island",
    "title": "Shau Kei Wan & Aldrich Bay",
    "zh": "筲箕灣與愛秩序灣",
    "sectionId": "03.4",
    "description": "Aldrich Bay Park and the older streets around Shau Kei Wan.",
    "source": "https://www.openstreetmap.org/way/86463847",
    "lat": 22.2826498,
    "lon": 114.2245351,
    "target": [
      6679.7,
      50.2,
      524.7
    ],
    "spawn": [
      6683.3,
      528.4
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/111104347"
  },
  "section-03-5": {
    "region": "island",
    "title": "Chai Wan neighbourhoods",
    "zh": "柴灣社區",
    "sectionId": "03.5",
    "description": "Wan Tsui's park paths and the surrounding eastern-island estates.",
    "source": "https://www.openstreetmap.org/way/916926428",
    "lat": 22.261071,
    "lon": 114.2393758,
    "target": [
      8210.2,
      103.8,
      2913.7
    ],
    "spawn": [
      8207.6,
      2918.3
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/406191503"
  },
  "section-03-6": {
    "region": "island",
    "title": "Siu Sai Wan promenade",
    "zh": "小西灣海濱",
    "sectionId": "03.6",
    "description": "The eastern waterfront below Cape Collinson's hills.",
    "source": "https://www.openstreetmap.org/way/961605650",
    "lat": 22.2662547,
    "lon": 114.2512576,
    "target": [
      9434.6,
      51.6,
      2339.1
    ],
    "spawn": [
      9460.9,
      2312.6
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/904134718"
  },
  "section-04-1": {
    "region": "island",
    "title": "Cyberport & Pok Fu Lam",
    "zh": "數碼港與薄扶林",
    "sectionId": "04.1",
    "description": "Waterfront park paths below the Pok Fu Lam hillside.",
    "source": "https://www.openstreetmap.org/way/231602706",
    "lat": 22.2575196,
    "lon": 114.1310053,
    "target": [
      -2959.9,
      50.2,
      3307.6
    ],
    "spawn": [
      -2956.5,
      3304.4
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/107387161"
  },
  "section-04-2": {
    "region": "island",
    "title": "Aberdeen waterfront",
    "zh": "香港仔海濱",
    "sectionId": "04.2",
    "description": "The promenade facing Aberdeen Harbour and its working waterfront.",
    "source": "https://www.openstreetmap.org/way/51801673",
    "lat": 22.2471777,
    "lon": 114.1547209,
    "target": [
      -515.6,
      52.9,
      4453.3
    ],
    "spawn": [
      -510.3,
      4437.7
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1197441878"
  },
  "section-04-3": {
    "region": "island",
    "title": "Ap Lei Chau",
    "zh": "鴨脷洲",
    "sectionId": "04.3",
    "description": "Public waterfront paths beside the old town on Ap Lei Chau.",
    "source": "https://www.openstreetmap.org/way/40959234",
    "lat": 22.2450162,
    "lon": 114.1578552,
    "target": [
      -192.6,
      51.9,
      4692.7
    ],
    "spawn": [
      -211.2,
      4655.3
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/514558506"
  },
  "section-04-4": {
    "region": "island",
    "title": "Deep Water Bay",
    "zh": "深水灣",
    "sectionId": "04.4",
    "description": "The beach and promenade on the coast east of Wong Chuk Hang.",
    "source": "https://www.openstreetmap.org/way/123991947",
    "lat": 22.2446558,
    "lon": 114.1872827,
    "target": [
      2840.9,
      47.6,
      4732.7
    ],
    "spawn": [
      2846.9,
      4719.3
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/879073524"
  },
  "section-04-5": {
    "region": "island",
    "title": "Repulse Bay",
    "zh": "淺水灣",
    "sectionId": "04.5",
    "description": "The beach frontage between the hillside neighbourhoods and the bay.",
    "source": "https://www.openstreetmap.org/way/155997180",
    "lat": 22.2366473,
    "lon": 114.196267,
    "target": [
      3767.2,
      48.8,
      5619.4
    ],
    "spawn": [
      3805.7,
      5569.7
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1436394186"
  },
  "section-04-6": {
    "region": "island",
    "title": "Stanley waterfront",
    "zh": "赤柱海濱",
    "sectionId": "04.6",
    "description": "The village promenade and market streets beside Stanley Bay.",
    "source": "https://www.openstreetmap.org/way/576655993",
    "lat": 22.2178845,
    "lon": 114.2119752,
    "target": [
      5387.0,
      48.4,
      7696.8
    ],
    "spawn": [
      5398.2,
      7658.5
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/96822889"
  },
  "section-04-7": {
    "region": "island",
    "title": "Tai Tam reservoir paths",
    "zh": "大潭水塘步道",
    "sectionId": "04.7",
    "description": "A mapped family-walk route among the Tai Tam reservoir hills.",
    "source": "https://www.openstreetmap.org/way/52557562",
    "lat": 22.2562425,
    "lon": 114.2034547,
    "target": [
      4507.8,
      326.1,
      3449.5
    ],
    "spawn": [
      4507.8,
      3449.5
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/52557562"
  },
  "section-04-8": {
    "region": "island",
    "title": "Shek O village & beach",
    "zh": "石澳村與泳灘",
    "sectionId": "04.8",
    "description": "The beach frontage and village paths below the Dragon's Back hills.",
    "source": "https://www.openstreetmap.org/way/97700177",
    "lat": 22.2286924,
    "lon": 114.2508891,
    "target": [
      9398.6,
      49.6,
      6498.6
    ],
    "spawn": [
      9375.2,
      6472.9
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/879094149"
  },
  "section-05-1": {
    "region": "kowloon",
    "title": "Tsim Sha Tsui ferry waterfront",
    "zh": "尖沙咀碼頭海濱",
    "sectionId": "05.1",
    "description": "A mapped public-path arrival by the ferry and cultural-centre waterfront.",
    "source": "https://www.openstreetmap.org/way/699026408",
    "lat": 22.2935615,
    "lon": 114.1693934,
    "target": [
      997.1,
      49.7,
      -682.8
    ],
    "spawn": [
      995.5,
      -687.5
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/699026408"
  },
  "section-05-2": {
    "region": "kowloon",
    "title": "Tsim Sha Tsui East",
    "zh": "尖沙咀東部",
    "sectionId": "05.2",
    "description": "The eastern promenade and streets towards the Hung Hom Bay edge.",
    "source": "https://www.openstreetmap.org/way/33613654",
    "lat": 22.296403,
    "lon": 114.1758335,
    "target": [
      1660.7,
      51.6,
      -997.4
    ],
    "spawn": [
      1628.8,
      -1002.8
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/557643422"
  },
  "section-05-3": {
    "region": "kowloon",
    "title": "Jordan & King's Park",
    "zh": "佐敦與京士柏",
    "sectionId": "05.3",
    "description": "Public recreation grounds above Jordan and Yau Ma Tei.",
    "source": "https://www.openstreetmap.org/way/446811355",
    "lat": 22.3105096,
    "lon": 114.1736487,
    "target": [
      1435.6,
      76.4,
      -2559.5
    ],
    "spawn": [
      1436.9,
      -2556.3
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1494935071"
  },
  "section-05-4": {
    "region": "kowloon",
    "title": "Mong Kok & Prince Edward",
    "zh": "旺角與太子",
    "sectionId": "05.4",
    "description": "The civic triangle beside the market streets and older urban blocks.",
    "source": "https://www.openstreetmap.org/way/665731930",
    "lat": 22.3228296,
    "lon": 114.1683803,
    "target": [
      892.9,
      51.1,
      -3923.8
    ],
    "spawn": [
      889.0,
      -3916.1
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1166307757"
  },
  "section-05-5": {
    "region": "kowloon",
    "title": "Tai Kok Tsui & Olympic",
    "zh": "大角咀與奧運",
    "sectionId": "05.5",
    "description": "The western residential waterfront and Olympian City promenade.",
    "source": "https://www.openstreetmap.org/way/672609038",
    "lat": 22.3207402,
    "lon": 114.1573465,
    "target": [
      -243.9,
      52.9,
      -3692.5
    ],
    "spawn": [
      -244.0,
      -3692.5
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1271398827"
  },
  "section-05-6": {
    "region": "kowloon",
    "title": "West Kowloon Art Park",
    "zh": "西九文化區藝術公園",
    "sectionId": "05.6",
    "description": "The cultural district's waterfront park and nearby museum precinct.",
    "source": "https://www.openstreetmap.org/way/567801791",
    "lat": 22.3013425,
    "lon": 114.1545541,
    "target": [
      -531.9,
      49.0,
      -1544.6
    ],
    "spawn": [
      -511.8,
      -1529.7
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1175604286"
  },
  "section-06-1": {
    "region": "kowloon",
    "title": "Sham Shui Po",
    "zh": "深水埗",
    "sectionId": "06.1",
    "description": "Older street blocks and public paths around Sham Shui Po Park.",
    "source": "https://www.openstreetmap.org/way/151705893",
    "lat": 22.3308059,
    "lon": 114.1561086,
    "target": [
      -371.3,
      50.1,
      -4807.2
    ],
    "spawn": [
      -372.3,
      -4807.2
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1141884101"
  },
  "section-06-2": {
    "region": "kowloon",
    "title": "Shek Kip Mei",
    "zh": "石硤尾",
    "sectionId": "06.2",
    "description": "The central playground and streets through the early housing estates.",
    "source": "https://www.openstreetmap.org/way/122356139",
    "lat": 22.3331815,
    "lon": 114.1690017,
    "target": [
      957.0,
      70.2,
      -5070.1
    ],
    "spawn": [
      956.8,
      -5077.4
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/595809128"
  },
  "section-06-3": {
    "region": "kowloon",
    "title": "Cheung Sha Wan",
    "zh": "長沙灣",
    "sectionId": "06.3",
    "description": "Public recreation space beside the industrial and residential street grid.",
    "source": "https://www.openstreetmap.org/way/151705833",
    "lat": 22.3349522,
    "lon": 114.1553687,
    "target": [
      -447.5,
      51.0,
      -5266.3
    ],
    "spawn": [
      -456.8,
      -5291.1
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1053172490"
  },
  "section-06-4": {
    "region": "kowloon",
    "title": "Lai Chi Kok & Mei Foo",
    "zh": "荔枝角與美孚",
    "sectionId": "06.4",
    "description": "The paths and sports spaces of Lai Chi Kok Park.",
    "source": "https://www.openstreetmap.org/way/25609090",
    "lat": 22.3357264,
    "lon": 114.1381796,
    "target": [
      -2218.2,
      54.9,
      -5352.4
    ],
    "spawn": [
      -2218.5,
      -5342.1
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/820229333"
  },
  "section-06-5": {
    "region": "kowloon",
    "title": "Nam Cheong & western waterfront",
    "zh": "南昌與西部海濱",
    "sectionId": "06.5",
    "description": "The park and public routes towards the western Kowloon waterfront.",
    "source": "https://www.openstreetmap.org/relation/20318610",
    "lat": 22.323866,
    "lon": 114.1573497,
    "target": [
      -243.5,
      53.3,
      -4038.7
    ],
    "spawn": [
      -241.5,
      -4033.5
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/862577031"
  },
  "section-06-6": {
    "region": "kowloon",
    "title": "Beacon Hill foothills",
    "zh": "筆架山山麓",
    "sectionId": "06.6",
    "description": "A public garden approach below the northern Sham Shui Po hills; upper trails remain a later review.",
    "source": "https://www.openstreetmap.org/way/185090462",
    "lat": 22.3412313,
    "lon": 114.1645805,
    "target": [
      501.6,
      133.3,
      -5961.5
    ],
    "spawn": [
      503.9,
      -5959.5
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1014973982"
  },
  "section-07-1": {
    "region": "kowloon",
    "title": "Hung Hom & Whampoa",
    "zh": "紅磡與黃埔",
    "sectionId": "07.1",
    "description": "Urban-park paths beside Hung Hom's waterfront residential blocks.",
    "source": "https://www.openstreetmap.org/way/1207904366",
    "lat": 22.3017324,
    "lon": 114.1901884,
    "target": [
      3139.9,
      49.9,
      -1587.6
    ],
    "spawn": [
      3137.5,
      -1586.5
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/494447358"
  },
  "section-07-2": {
    "region": "kowloon",
    "title": "To Kwa Wan & Cattle Depot",
    "zh": "土瓜灣與牛棚",
    "sectionId": "07.2",
    "description": "The art park and older industrial streets of To Kwa Wan.",
    "source": "https://www.openstreetmap.org/way/684780794",
    "lat": 22.3203832,
    "lon": 114.1912754,
    "target": [
      3251.7,
      51.7,
      -3652.9
    ],
    "spawn": [
      3247.4,
      -3644.4
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/837855781"
  },
  "section-07-3": {
    "region": "kowloon",
    "title": "Kowloon Walled City Park",
    "zh": "九龍寨城公園",
    "sectionId": "07.3",
    "description": "The historic park and the surrounding Kowloon City street grid.",
    "source": "https://www.openstreetmap.org/relation/1650915",
    "lat": 22.332135,
    "lon": 114.1902796,
    "target": [
      3149.0,
      59.4,
      -4954.3
    ],
    "spawn": [
      3144.8,
      -4953.5
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1348695118"
  },
  "section-07-4": {
    "region": "kowloon",
    "title": "Kai Tak Sports Park approach",
    "zh": "啟德體育園外圍",
    "sectionId": "07.4",
    "description": "Shing Kai Road's public garden and the approach to the sports precinct.",
    "source": "https://www.openstreetmap.org/way/1191574324",
    "lat": 22.3218882,
    "lon": 114.1950873,
    "target": [
      3644.4,
      50.9,
      -3819.6
    ],
    "spawn": [
      3639.6,
      -3816.8
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1252050786"
  },
  "section-07-5": {
    "region": "kowloon",
    "title": "Kai Tak runway waterfront",
    "zh": "啟德跑道海濱",
    "sectionId": "07.5",
    "description": "The mapped promenade along the former runway towards the cruise-terminal waterfront.",
    "source": "https://www.openstreetmap.org/relation/18504352",
    "lat": 22.313497,
    "lon": 114.2064953,
    "target": [
      4820.0,
      49.8,
      -2890.6
    ],
    "spawn": [
      4817.7,
      -2892.9
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1251138428"
  },
  "section-07-6": {
    "region": "kowloon",
    "title": "Ho Man Tin",
    "zh": "何文田",
    "sectionId": "07.6",
    "description": "Public park paths among the Ho Man Tin hillside neighbourhoods.",
    "source": "https://www.openstreetmap.org/way/197739476",
    "lat": 22.3119234,
    "lon": 114.1808318,
    "target": [
      2175.8,
      104.6,
      -2716.1
    ],
    "spawn": [
      2154.5,
      -2684.9
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1493613558"
  },
  "section-08-1": {
    "region": "kowloon",
    "title": "Wong Tai Sin precinct",
    "zh": "黃大仙一帶",
    "sectionId": "08.1",
    "description": "Public garden space south of the temple and Chuk Yuen neighbourhood.",
    "source": "https://www.openstreetmap.org/way/263310067",
    "lat": 22.337638,
    "lon": 114.1932522,
    "target": [
      3455.2,
      55.1,
      -5563.7
    ],
    "spawn": [
      3455.4,
      -5563.4
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/263310497"
  },
  "section-08-2": {
    "region": "kowloon",
    "title": "Lok Fu & Wang Tau Hom",
    "zh": "樂富與橫頭磡",
    "sectionId": "08.2",
    "description": "Lok Fu Recreation Ground and the surrounding residential streets.",
    "source": "https://www.openstreetmap.org/way/184291966",
    "lat": 22.336705,
    "lon": 114.1884337,
    "target": [
      2958.8,
      71.0,
      -5460.3
    ],
    "spawn": [
      2932.4,
      -5449.0
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/240397655"
  },
  "section-08-3": {
    "region": "kowloon",
    "title": "Diamond Hill & Nan Lian",
    "zh": "鑽石山與南蓮園池",
    "sectionId": "08.3",
    "description": "The garden precinct beside Chi Lin Nunnery and Diamond Hill.",
    "source": "https://www.openstreetmap.org/way/86041251",
    "lat": 22.3392489,
    "lon": 114.2045573,
    "target": [
      4619.8,
      62.5,
      -5742.2
    ],
    "spawn": [
      4625.2,
      -5746.6
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/109743746"
  },
  "section-08-4": {
    "region": "kowloon",
    "title": "San Po Kong & Choi Hung",
    "zh": "新蒲崗與彩虹",
    "sectionId": "08.4",
    "description": "Choi Hung Road's playground and the surrounding older urban blocks.",
    "source": "https://www.openstreetmap.org/way/158182424",
    "lat": 22.3379339,
    "lon": 114.1968931,
    "target": [
      3830.2,
      52.4,
      -5596.5
    ],
    "spawn": [
      3833.3,
      -5586.1
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/714446571"
  },
  "section-08-5": {
    "region": "kowloon",
    "title": "Tsz Wan Shan",
    "zh": "慈雲山",
    "sectionId": "08.5",
    "description": "Estate playgrounds and public paths below the northern hills.",
    "source": "https://www.openstreetmap.org/way/108037381",
    "lat": 22.3494733,
    "lon": 114.2009198,
    "target": [
      4244.9,
      147.7,
      -6874.4
    ],
    "spawn": [
      4268.2,
      -6865.9
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/612925857"
  },
  "section-08-6": {
    "region": "kowloon",
    "title": "Lion Rock foothills",
    "zh": "獅子山山麓",
    "sectionId": "08.6",
    "description": "The country-park approach above Wong Tai Sin's residential districts.",
    "source": "https://www.openstreetmap.org/way/224751148",
    "lat": 22.3454196,
    "lon": 114.183053,
    "target": [
      2404.5,
      158.0,
      -6425.3
    ],
    "spawn": [
      2369.5,
      -6455.7
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/339911115"
  },
  "section-09-1": {
    "region": "kowloon",
    "title": "Kowloon Bay",
    "zh": "九龍灣",
    "sectionId": "09.1",
    "description": "Public paths beside the Zero Carbon Building and former industrial blocks.",
    "source": "https://www.openstreetmap.org/way/126469800",
    "lat": 22.3209536,
    "lon": 114.2083654,
    "target": [
      5012.5,
      52.0,
      -3716.4
    ],
    "spawn": [
      5015.8,
      -3731.3
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1044412478"
  },
  "section-09-2": {
    "region": "kowloon",
    "title": "Ngau Tau Kok",
    "zh": "牛頭角",
    "sectionId": "09.2",
    "description": "Ngau Tau Kok Park and the surrounding residential street network.",
    "source": "https://www.openstreetmap.org/way/367542053",
    "lat": 22.3226745,
    "lon": 114.2151961,
    "target": [
      5716.2,
      51.7,
      -3907.1
    ],
    "spawn": [
      5732.1,
      -3912.3
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1036829302"
  },
  "section-09-3": {
    "region": "kowloon",
    "title": "Kwun Tong waterfront",
    "zh": "觀塘海濱",
    "sectionId": "09.3",
    "description": "Promenade paths along the former industrial waterfront.",
    "source": "https://www.openstreetmap.org/way/205719186",
    "lat": 22.3121656,
    "lon": 114.2170774,
    "target": [
      5910.3,
      52.2,
      -2743.4
    ],
    "spawn": [
      5925.6,
      -2734.8
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1046149718"
  },
  "section-09-4": {
    "region": "kowloon",
    "title": "Sau Mau Ping",
    "zh": "秀茂坪",
    "sectionId": "09.4",
    "description": "Memorial-park paths between Sau Mau Ping's hillside estates.",
    "source": "https://www.openstreetmap.org/way/457650488",
    "lat": 22.317999,
    "lon": 114.2289372,
    "target": [
      7132.1,
      71.8,
      -3389.8
    ],
    "spawn": [
      7134.8,
      -3394.0
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/313796062"
  },
  "section-09-5": {
    "region": "kowloon",
    "title": "Lam Tin",
    "zh": "藍田",
    "sectionId": "09.5",
    "description": "Lam Tin Park and the residential slopes towards Yau Tong.",
    "source": "https://www.openstreetmap.org/way/58475071",
    "lat": 22.3108123,
    "lon": 114.2404861,
    "target": [
      8322.3,
      204.5,
      -2594.4
    ],
    "spawn": [
      8322.7,
      -2596.8
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/914289201"
  },
  "section-09-6": {
    "region": "kowloon",
    "title": "Cha Kwo Ling old village",
    "zh": "茶果嶺舊村",
    "sectionId": "09.6",
    "description": "The mapped village lane beside the eastern harbour shore.",
    "source": "https://www.openstreetmap.org/way/111855476",
    "lat": 22.3015922,
    "lon": 114.2280556,
    "target": [
      7041.8,
      50.9,
      -1572.9
    ],
    "spawn": [
      7041.8,
      -1572.9
    ],
    "offset": [
      1050,
      900,
      -1300
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/111855476"
  },
  "nt-tsuen-wan-park": {
    "region": "ntwest",
    "title": "Tsuen Wan waterfront park",
    "zh": "荃灣海濱公園",
    "sectionId": "11.1",
    "description": "Explore the park paths between Tsuen Wan West and the Rambler Channel.",
    "source": "https://www.openstreetmap.org/way/755626377",
    "lat": 22.3661009,
    "lon": 114.1118955,
    "target": [
      -4924.5,
      80,
      -8716.9
    ],
    "spawn": [
      -4924.5,
      -8716.9
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/755626377"
  },
  "nt-tsuen-king": {
    "region": "ntwest",
    "title": "Tsuen King Circuit",
    "zh": "荃景圍",
    "sectionId": "11.2",
    "description": "A hillside estate and sports-centre approach above Tsuen Wan.",
    "source": "https://www.openstreetmap.org/way/96197169",
    "lat": 22.3774054,
    "lon": 114.1114513,
    "target": [
      -4969.7,
      80,
      -9968.7
    ],
    "spawn": [
      -4956.6,
      -9980.1
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1205704231"
  },
  "nt-sham-tseng": {
    "region": "ntwest",
    "title": "Sham Tseng village and coast",
    "zh": "深井村與海岸",
    "sectionId": "11.3",
    "description": "Visit the village playground and browse the coastal towers below Tai Lam.",
    "source": "https://www.openstreetmap.org/way/334676185",
    "lat": 22.3677849,
    "lon": 114.0584066,
    "target": [
      -10433.5,
      80,
      -8906.7
    ],
    "spawn": [
      -10421.6,
      -8914.0
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/334676192"
  },
  "nt-tai-mo-shan-visitor": {
    "region": "ntwest",
    "title": "Tai Mo Shan visitor centre",
    "zh": "大帽山遊客中心",
    "sectionId": "11.4",
    "description": "Begin exploring the mountain slopes around the country-park visitor centre.",
    "source": "https://www.openstreetmap.org/way/300687210",
    "lat": 22.4058923,
    "lon": 114.1065803,
    "target": [
      -5469.9,
      546.8,
      -13123.4
    ],
    "spawn": [
      -5482.3,
      -13116.4
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1016993753"
  },
  "nt-ma-wan-park": {
    "region": "ntwest",
    "title": "Ma Wan park and bridge views",
    "zh": "馬灣公園與大橋景觀",
    "sectionId": "11.5",
    "description": "Explore Ma Wan's park setting beside the Tsing Ma and Kap Shui Mun crossings.",
    "source": "https://www.openstreetmap.org/way/69717322",
    "lat": 22.3488913,
    "lon": 114.0584064,
    "target": [
      -10435.1,
      80,
      -6814.5
    ],
    "spawn": [
      -10450.6,
      -6789.4
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/351090911"
  },
  "nt-central-kwai-chung": {
    "region": "ntwest",
    "title": "Central Kwai Chung Park",
    "zh": "中葵涌公園",
    "sectionId": "12.1",
    "description": "An open park arrival amongst Kwai Chung's residential and industrial neighbourhoods.",
    "source": "https://www.openstreetmap.org/way/199756565",
    "lat": 22.3560374,
    "lon": 114.1327816,
    "target": [
      -2773.7,
      106.9,
      -7601.7
    ],
    "spawn": [
      -2762.1,
      -7589.1
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/755122692"
  },
  "nt-lai-king-hill": {
    "region": "ntwest",
    "title": "Lai King hillside",
    "zh": "荔景山",
    "sectionId": "12.2",
    "description": "Browse the hillside estates and public playground above the container-port corridor.",
    "source": "https://www.openstreetmap.org/way/199625316",
    "lat": 22.3459503,
    "lon": 114.1276735,
    "target": [
      -3300.2,
      95.2,
      -6484.9
    ],
    "spawn": [
      -3300.2,
      -6491.5
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/754858052"
  },
  "nt-kwai-tsing-port": {
    "region": "ntwest",
    "title": "Kwai Tsing container terminals",
    "zh": "葵青貨櫃碼頭",
    "sectionId": "12.3",
    "description": "An aerial overview of the mapped cargo waterfront and terminal yards. Aerial overview only; operational container terminals are not public walking destinations.",
    "source": "https://www.openstreetmap.org/relation/10507292",
    "lat": 22.3368713,
    "lon": 114.1212099,
    "target": [
      -3966.4,
      80,
      -5479.7
    ],
    "spawn": [
      -3966.4,
      -5479.7
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": true
  },
  "nt-tsing-yi-promenade": {
    "region": "ntwest",
    "title": "Tsing Yi promenade",
    "zh": "青衣海濱長廊",
    "sectionId": "12.4",
    "description": "Explore Tsing Yi's eastern waterfront, with the town and Maritime Square nearby.",
    "source": "https://www.openstreetmap.org/way/135158476",
    "lat": 22.3631297,
    "lon": 114.1054072,
    "target": [
      -5592.9,
      80,
      -8388.1
    ],
    "spawn": [
      -5637.5,
      -8353.6
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1332801724"
  },
  "nt-tsing-yi-southwest": {
    "region": "ntwest",
    "title": "Tsing Yi southwest",
    "zh": "青衣西南",
    "sectionId": "12.5",
    "description": "A public leisure-centre approach overlooking the southern island's industrial landscape.",
    "source": "https://www.openstreetmap.org/way/487423997",
    "lat": 22.3514704,
    "lon": 114.1020959,
    "target": [
      -5934.6,
      85.5,
      -7097.2
    ],
    "spawn": [
      -5906.7,
      -7073.3
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/685084541"
  },
  "nt-lantau-link-view": {
    "region": "ntwest",
    "title": "Lantau Link viewing platform",
    "zh": "青嶼幹線觀景台",
    "sectionId": "12.6",
    "description": "Look across the Tsing Ma Bridge from the mapped public viewing-platform approach.",
    "source": "https://www.openstreetmap.org/way/158307216",
    "lat": 22.3583638,
    "lon": 114.0809896,
    "target": [
      -8108.2,
      104.7,
      -7861.8
    ],
    "spawn": [
      -8107.3,
      -7866.5
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/903452946"
  },
  "nt-tai-wai-che-kung": {
    "region": "nteast",
    "title": "Tai Wai and Che Kung corridor",
    "zh": "大圍車公廟走廊",
    "sectionId": "13.1",
    "description": "Start by Che Kung Miu Road Playground to explore Tai Wai and the river corridor.",
    "source": "https://www.openstreetmap.org/way/138461154",
    "lat": 22.3690477,
    "lon": 114.1764673,
    "target": [
      1726.1,
      80,
      -9041.7
    ],
    "spawn": [
      1735.9,
      -9042.6
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/261065286"
  },
  "nt-sha-tin-park": {
    "region": "nteast",
    "title": "Sha Tin Park and river",
    "zh": "沙田公園與城門河",
    "sectionId": "13.2",
    "description": "Explore the town-centre park and Shing Mun River banks.",
    "source": "https://www.openstreetmap.org/way/32559006",
    "lat": 22.3796412,
    "lon": 114.1897618,
    "target": [
      3095.2,
      80,
      -10214.9
    ],
    "spawn": [
      3093.9,
      -10213.4
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/258923617"
  },
  "nt-fo-tan-racecourse": {
    "region": "nteast",
    "title": "Fo Tan and racecourse park",
    "zh": "火炭與馬場公園",
    "sectionId": "13.3",
    "description": "Browse Fo Tan, the racecourse and Penfold Park from their mapped setting.",
    "source": "https://www.openstreetmap.org/way/163970357",
    "lat": 22.3994995,
    "lon": 114.2067412,
    "target": [
      4843.4,
      80,
      -12414.1
    ],
    "spawn": [
      4844.1,
      -12413.7
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/179092824"
  },
  "nt-shek-mun-riverside": {
    "region": "nteast",
    "title": "Shek Mun riverside",
    "zh": "石門河畔",
    "sectionId": "13.4",
    "description": "An arrival by the riverside gardens near Shek Mun and City One.",
    "source": "https://www.openstreetmap.org/way/722719221",
    "lat": 22.3852841,
    "lon": 114.2092244,
    "target": [
      5099.4,
      80,
      -10840.0
    ],
    "spawn": [
      5099.8,
      -10841.1
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/808469954"
  },
  "nt-wu-kai-sha-village": {
    "region": "nteast",
    "title": "Wu Kai Sha village lanes",
    "zh": "烏溪沙村巷",
    "sectionId": "13.5",
    "description": "Explore the village lanes and the coast at the northern end of Ma On Shan.",
    "source": "https://www.openstreetmap.org/way/377259846",
    "lat": 22.4279824,
    "lon": 114.2388175,
    "target": [
      8145.0,
      80,
      -15569.2
    ],
    "spawn": [
      8141.4,
      -15565.8
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/377259846"
  },
  "nt-ma-liu-shui-pier": {
    "region": "nteast",
    "title": "Ma Liu Shui ferry approach",
    "zh": "馬料水渡輪碼頭入口",
    "sectionId": "13.6",
    "description": "Explore the shore near the ferry pier and Chinese University hills.",
    "source": "https://www.openstreetmap.org/way/709245126",
    "lat": 22.4171821,
    "lon": 114.2144134,
    "target": [
      5632.9,
      80,
      -14372.4
    ],
    "spawn": [
      5618.7,
      -14377.2
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/386427048"
  },
  "nt-shing-mun-lead-mine": {
    "region": "nteast",
    "title": "Lead Mine Pass trail connection",
    "zh": "鉛礦坳山徑接點",
    "sectionId": "13.7",
    "description": "Browse the wooded trail connection above Sha Tin and Shing Mun.",
    "source": "https://www.openstreetmap.org/way/271203780",
    "lat": 22.3971148,
    "lon": 114.1513982,
    "target": [
      -855.3,
      252.5,
      -12150.0
    ],
    "spawn": [
      -857.7,
      -12152.6
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/94329305"
  },
  "nt-tai-po-market-garden": {
    "region": "nteast",
    "title": "Tai Po Market garden",
    "zh": "大埔墟休憩花園",
    "sectionId": "14.1",
    "description": "Begin amongst the streets and public garden around Tai Po Market.",
    "source": "https://www.openstreetmap.org/way/189410346",
    "lat": 22.4486095,
    "lon": 114.1653067,
    "target": [
      577.3,
      80,
      -17852.1
    ],
    "spawn": [
      577.1,
      -17852.1
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/605895922"
  },
  "nt-tai-po-waterfront": {
    "region": "nteast",
    "title": "Tai Po Waterfront Park",
    "zh": "大埔海濱公園",
    "sectionId": "14.2",
    "description": "Explore the waterfront park between the new town and Tolo Harbour.",
    "source": "https://www.openstreetmap.org/way/111577520",
    "lat": 22.4520862,
    "lon": 114.1899972,
    "target": [
      3118.7,
      80,
      -18237.1
    ],
    "spawn": [
      3136.9,
      -18233.2
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/611146815"
  },
  "nt-science-park-waterfront": {
    "region": "nteast",
    "title": "Science Park and Pak Shek Kok",
    "zh": "科學園與白石角",
    "sectionId": "14.3",
    "description": "Browse the Science Park campus and public waterfront setting at Pak Shek Kok.",
    "source": "https://www.openstreetmap.org/relation/12638453",
    "lat": 22.4263193,
    "lon": 114.2111942,
    "target": [
      5301.2,
      80,
      -15384.1
    ],
    "spawn": [
      5297.0,
      -15378.3
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/709071770"
  },
  "nt-lam-tsuen-square": {
    "region": "nteast",
    "title": "Lam Tsuen Wishing Square",
    "zh": "林村許願廣場",
    "sectionId": "14.4",
    "description": "Explore the village square and the rural Lam Tsuen valley.",
    "source": "https://www.openstreetmap.org/way/147224415",
    "lat": 22.4566561,
    "lon": 114.1426276,
    "target": [
      -1757.0,
      85.1,
      -18743.5
    ],
    "spawn": [
      -1745.9,
      -18709.3
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/766680983"
  },
  "nt-tai-mei-tuk-trail": {
    "region": "nteast",
    "title": "Tai Mei Tuk family walk",
    "zh": "大美督家樂徑",
    "sectionId": "14.5",
    "description": "A coastal trail arrival beside Plover Cove Reservoir and Tai Mei Tuk.",
    "source": "https://www.openstreetmap.org/way/308478793",
    "lat": 22.4689208,
    "lon": 114.2341224,
    "target": [
      7659.9,
      80,
      -20102.4
    ],
    "spawn": [
      7659.9,
      -20102.4
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/308478793"
  },
  "nt-ma-shi-chau-trail": {
    "region": "nteast",
    "title": "Ma Shi Chau nature trail",
    "zh": "馬屎洲自然教育徑",
    "sectionId": "14.6",
    "description": "Explore the island's mapped nature trail and the eastern Tolo Harbour shore.",
    "source": "https://www.openstreetmap.org/way/134846907",
    "lat": 22.4508021,
    "lon": 114.2292463,
    "target": [
      7158.8,
      80,
      -18095.8
    ],
    "spawn": [
      7171.9,
      -18103.0
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/134846907"
  },
  "nt-wong-shek-trail": {
    "region": "nteast",
    "title": "Wong Shek family walk",
    "zh": "黃石家樂徑",
    "sectionId": "14.7",
    "description": "Explore the wooded shore around Wong Shek in Tai Po's Sai Kung North area.",
    "source": "https://www.openstreetmap.org/way/423067599",
    "lat": 22.4314155,
    "lon": 114.3360895,
    "target": [
      18158.7,
      84.7,
      -15956.8
    ],
    "spawn": [
      18158.7,
      -15956.8
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/423067599"
  },
  "nt-tko-waterfront-park": {
    "region": "nteast",
    "title": "Tseung Kwan O waterfront",
    "zh": "將軍澳海濱",
    "sectionId": "15.1",
    "description": "Explore the waterfront park and the town's coastal pedestrian connections.",
    "source": "https://www.openstreetmap.org/way/311764682",
    "lat": 22.3031139,
    "lon": 114.2640806,
    "target": [
      10753.8,
      80,
      -1743.2
    ],
    "spawn": [
      10748.0,
      -1746.2
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/566013427"
  },
  "nt-po-lam-garden": {
    "region": "nteast",
    "title": "Po Lam and Hang Hau approach",
    "zh": "寶琳與坑口入口",
    "sectionId": "15.2",
    "description": "Start at Po Lam's public sitting-out area amongst the town's residential neighbourhoods.",
    "source": "https://www.openstreetmap.org/way/657755936",
    "lat": 22.3272436,
    "lon": 114.2540214,
    "target": [
      9716.0,
      80,
      -4414.6
    ],
    "spawn": [
      9721.4,
      -4395.4
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/859104263"
  },
  "nt-lohas-road-garden": {
    "region": "nteast",
    "title": "LOHAS Park waterfront approach",
    "zh": "康城海濱入口",
    "sectionId": "15.3",
    "description": "Explore the public garden near LOHAS Park and the eastern Junk Bay shore.",
    "source": "https://www.openstreetmap.org/way/1443435540",
    "lat": 22.2983935,
    "lon": 114.2640985,
    "target": [
      10756.0,
      80,
      -1220.4
    ],
    "spawn": [
      10762.2,
      -1225.7
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/765942656"
  },
  "nt-sai-kung-waterfront": {
    "region": "nteast",
    "title": "Sai Kung town waterfront",
    "zh": "西貢市海濱",
    "sectionId": "15.4",
    "description": "Begin by the waterfront park to explore Sai Kung town and its piers.",
    "source": "https://www.openstreetmap.org/way/266586309",
    "lat": 22.3823173,
    "lon": 114.2743972,
    "target": [
      11811.2,
      80,
      -10514.4
    ],
    "spawn": [
      11810.8,
      -10514.7
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/514855094"
  },
  "nt-clear-water-bay-trail": {
    "region": "nteast",
    "title": "Clear Water Bay tree walk",
    "zh": "清水灣樹木研習徑",
    "sectionId": "15.5",
    "description": "Explore the country-park approach around Tai Au Mun and the Clear Water Bay peninsula.",
    "source": "https://www.openstreetmap.org/way/809421241",
    "lat": 22.2896043,
    "lon": 114.3023856,
    "target": [
      14702.1,
      105.8,
      -250.0
    ],
    "spawn": [
      14702.1,
      -250.0
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/809421241"
  },
  "nt-pak-tam-chung-trail": {
    "region": "nteast",
    "title": "Pak Tam Chung nature trail",
    "zh": "北潭涌自然教育徑",
    "sectionId": "15.6",
    "description": "A public trail approach to the eastern country park and High Island Reservoir area.",
    "source": "https://www.openstreetmap.org/way/103002865",
    "lat": 22.3953657,
    "lon": 114.3217817,
    "target": [
      16689.6,
      80,
      -11963.3
    ],
    "spawn": [
      16689.6,
      -11963.3
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/103002865"
  },
  "nt-ham-tin-beach": {
    "region": "nteast",
    "title": "Ham Tin Wan",
    "zh": "鹹田灣",
    "sectionId": "15.7",
    "description": "Explore the mapped beach and nearby paths of Tai Long Wan.",
    "source": "https://www.openstreetmap.org/way/245413792",
    "lat": 22.4092191,
    "lon": 114.3753996,
    "target": [
      22208.8,
      80,
      -13503.6
    ],
    "spawn": [
      22207.1,
      -13506.3
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/390178989"
  },
  "nt-sharp-island-trail": {
    "region": "nteast",
    "title": "Sharp Island geo trail",
    "zh": "橋咀洲地質步道",
    "sectionId": "15.8",
    "description": "Follow the mapped trail around Sharp Island's western beach and shore.",
    "source": "https://www.openstreetmap.org/way/282307137",
    "lat": 22.3668864,
    "lon": 114.2882037,
    "target": [
      13234.3,
      80,
      -8806.6
    ],
    "spawn": [
      13234.3,
      -8806.6
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/282307137"
  },
  "nt-tung-lung-pier": {
    "region": "nteast",
    "title": "Tung Lung Chau",
    "zh": "東龍洲",
    "sectionId": "15.9",
    "description": "Browse the island around its public pier and nearby walking paths.",
    "source": "https://www.openstreetmap.org/way/102303670",
    "lat": 22.2546165,
    "lon": 114.2889709,
    "target": [
      13322.6,
      80,
      3625.5
    ],
    "spawn": [
      13322.6,
      3625.4
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/386427055"
  },
  "nt-tuen-mun-park": {
    "region": "ntwest",
    "title": "Tuen Mun Park",
    "zh": "屯門公園",
    "sectionId": "16.1",
    "description": "Explore the town-centre park and river corridor.",
    "source": "https://www.openstreetmap.org/way/55444337",
    "lat": 22.3915697,
    "lon": 113.9736577,
    "target": [
      -19158.5,
      80,
      -11549.8
    ],
    "spawn": [
      -19158.0,
      -11549.2
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/516188611"
  },
  "nt-siu-hong": {
    "region": "ntwest",
    "title": "Siu Hong station approach",
    "zh": "兆康站入口",
    "sectionId": "16.2",
    "description": "Explore the northern residential neighbourhoods around the station's public approaches.",
    "source": "https://www.openstreetmap.org/way/41178206",
    "lat": 22.4119334,
    "lon": 113.978716,
    "target": [
      -18634.7,
      80,
      -13804.2
    ],
    "spawn": [
      -18638.2,
      -13848.0
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1531244092"
  },
  "nt-butterfly-beach-park": {
    "region": "ntwest",
    "title": "Butterfly Beach Park",
    "zh": "蝴蝶灣公園",
    "sectionId": "16.3",
    "description": "Explore the park and western residential waterfront near Tuen Mun ferry pier.",
    "source": "https://www.openstreetmap.org/way/148190099",
    "lat": 22.3738597,
    "lon": 113.9578961,
    "target": [
      -20784.5,
      80,
      -9591.0
    ],
    "spawn": [
      -20787.3,
      -9595.4
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/257587901"
  },
  "nt-golden-beach": {
    "region": "ntwest",
    "title": "Golden Beach and Gold Coast",
    "zh": "黃金泳灘與黃金海岸",
    "sectionId": "16.4",
    "description": "Explore the mapped beach beside Castle Peak Bay and the Gold Coast.",
    "source": "https://www.openstreetmap.org/way/439181304",
    "lat": 22.371263,
    "lon": 113.9885037,
    "target": [
      -17632.6,
      80,
      -9299.2
    ],
    "spawn": [
      -17594.2,
      -9299.4
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/100403716"
  },
  "nt-lung-kwu-tan-lookout": {
    "region": "ntwest",
    "title": "Lung Kwu Tan lookout",
    "zh": "龍鼓灘瞭望台",
    "sectionId": "16.5",
    "description": "Browse the coastal village and western slopes from the mapped lookout approach.",
    "source": "https://www.openstreetmap.org/node/1485618943",
    "lat": 22.3929276,
    "lon": 113.9179275,
    "target": [
      -24897.2,
      91.6,
      -11709.0
    ],
    "spawn": [
      -24896.1,
      -11709.3
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/120521501"
  },
  "nt-lung-kwu-chau": {
    "region": "ntwest",
    "title": "Lung Kwu Chau and western waters",
    "zh": "龍鼓洲與西部水域",
    "sectionId": "16.6",
    "description": "An aerial coastal view of the island within the Sha Chau and Lung Kwu Chau Marine Park. Aerial overview only; no verified public arrival or scheduled public transport is provided for this marine-park island.",
    "source": "https://www.openstreetmap.org/way/174627731",
    "lat": 22.3763396,
    "lon": 113.8844977,
    "target": [
      -28343.3,
      80,
      -9878.4
    ],
    "spawn": [
      -28343.2,
      -9878.4
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": true
  },
  "nt-tsang-tsui": {
    "region": "ntwest",
    "title": "Tsang Tsui coastal approach",
    "zh": "曾咀海岸入口",
    "sectionId": "16.7",
    "description": "Browse the mapped road setting near the western coastal facilities and Black Point.",
    "source": "https://www.openstreetmap.org/way/691588854",
    "lat": 22.4190371,
    "lon": 113.9244886,
    "target": [
      -24216.7,
      80,
      -14599.2
    ],
    "spawn": [
      -24211.1,
      -14591.9
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/857456766"
  },
  "nt-yuen-long-park": {
    "region": "ntwest",
    "title": "Yuen Long Park",
    "zh": "元朗公園",
    "sectionId": "17.1",
    "description": "Explore the town's public park and surrounding residential streets.",
    "source": "https://www.openstreetmap.org/way/157811032",
    "lat": 22.4418421,
    "lon": 114.0188523,
    "target": [
      -14498.7,
      80,
      -17111.2
    ],
    "spawn": [
      -14499.6,
      -17112.4
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/302153725"
  },
  "nt-tin-shui-wai-park": {
    "region": "ntwest",
    "title": "Tin Shui Wai Park",
    "zh": "天水圍公園",
    "sectionId": "17.2",
    "description": "Explore the park at the heart of Tin Shui Wai, with Ping Shan to the south.",
    "source": "https://www.openstreetmap.org/way/25637587",
    "lat": 22.4566917,
    "lon": 114.0012121,
    "target": [
      -16312.6,
      80,
      -18757.6
    ],
    "spawn": [
      -16310.8,
      -18751.0
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/501106605"
  },
  "nt-ha-pak-nai": {
    "region": "ntwest",
    "title": "Ha Pak Nai coast",
    "zh": "下白泥海岸",
    "sectionId": "17.3",
    "description": "Browse the rural coastal approach near Ha Pak Nai's historic fortified structure.",
    "source": "https://www.openstreetmap.org/way/318219909",
    "lat": 22.4273827,
    "lon": 113.9428438,
    "target": [
      -22325.5,
      80,
      -15520.3
    ],
    "spawn": [
      -22329.7,
      -15509.7
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/318219910"
  },
  "nt-hung-shui-kiu": {
    "region": "ntwest",
    "title": "Hung Shui Kiu market approach",
    "zh": "洪水橋街市入口",
    "sectionId": "17.4",
    "description": "Explore the public street approaches around Hung Shui Kiu's temporary market.",
    "source": "https://www.openstreetmap.org/way/448228055",
    "lat": 22.4328948,
    "lon": 113.9955515,
    "target": [
      -16898.5,
      80,
      -16123.2
    ],
    "spawn": [
      -16887.6,
      -16108.3
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/495065160"
  },
  "nt-kam-tin-market": {
    "region": "ntwest",
    "title": "Kam Tin market playground",
    "zh": "錦田街市遊樂場",
    "sectionId": "17.5",
    "description": "A village-centre arrival for the Kam Tin and Pat Heung rural area.",
    "source": "https://www.openstreetmap.org/way/449876390",
    "lat": 22.4401216,
    "lon": 114.0652241,
    "target": [
      -9725.3,
      80,
      -16916.4
    ],
    "spawn": [
      -9727.4,
      -16899.8
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1219281774"
  },
  "nt-nam-sang-wai": {
    "region": "ntwest",
    "title": "Nam Sang Wai river approach",
    "zh": "南生圍河畔入口",
    "sectionId": "17.6",
    "description": "Browse the mapped road and nearby paths around the Kam Tin River wetlands.",
    "source": "https://www.openstreetmap.org/way/103645711",
    "lat": 22.4490784,
    "lon": 114.0491966,
    "target": [
      -11374.4,
      80,
      -17909.6
    ],
    "spawn": [
      -11325.8,
      -17869.9
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/552528715"
  },
  "nt-san-tin-park": {
    "region": "ntwest",
    "title": "San Tin Park",
    "zh": "新田公園",
    "sectionId": "17.7",
    "description": "Explore San Tin's public park outside the restricted wetland and border-control sites.",
    "source": "https://www.openstreetmap.org/way/260760038",
    "lat": 22.4986658,
    "lon": 114.0759547,
    "target": [
      -8616.4,
      80,
      -23398.6
    ],
    "spawn": [
      -8620.3,
      -23399.0
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/260760181"
  },
  "nt-tai-tong-trail": {
    "region": "ntwest",
    "title": "Tai Tong nature trail",
    "zh": "大棠自然教育徑",
    "sectionId": "17.8",
    "description": "Explore the wooded uplands and trail links into Tai Lam Country Park.",
    "source": "https://www.openstreetmap.org/way/95749654",
    "lat": 22.4055006,
    "lon": 114.0394794,
    "target": [
      -12379.0,
      199.4,
      -13084.8
    ],
    "spawn": [
      -12379.0,
      -13084.8
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/95749654"
  },
  "nt-luen-wo-playground": {
    "region": "ntnorth",
    "title": "Fanling and Luen Wo Hui",
    "zh": "粉嶺與聯和墟",
    "sectionId": "18.1",
    "description": "Begin by the market-side public playground to explore Luen Wo Hui and Fanling.",
    "source": "https://www.openstreetmap.org/way/208971157",
    "lat": 22.4996144,
    "lon": 114.1449268,
    "target": [
      -1519.3,
      80,
      -23500.5
    ],
    "spawn": [
      -1519.8,
      -23501.5
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/780974447"
  },
  "nt-sheung-shui-garden": {
    "region": "ntnorth",
    "title": "Sheung Shui garden",
    "zh": "上水花園",
    "sectionId": "18.2",
    "description": "Explore the public garden and surrounding streets of Sheung Shui.",
    "source": "https://www.openstreetmap.org/way/255289151",
    "lat": 22.5034619,
    "lon": 114.130482,
    "target": [
      -3005.5,
      80,
      -23927.0
    ],
    "spawn": [
      -3008.2,
      -23930.1
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/800904537"
  },
  "nt-sha-tau-kok": {
    "region": "ntnorth",
    "title": "Sha Tau Kok and Starling Inlet",
    "zh": "沙頭角與沙頭角海",
    "sectionId": "18.3",
    "description": "An aerial browse of the town's mapped promenade and harbour. Aerial overview only in the viewer; real-world entry to Sha Tau Kok requires a Tourism Closed Area Permit. Chung Ying Street is excluded.",
    "source": "https://www.openstreetmap.org/way/658726215",
    "lat": 22.5440294,
    "lon": 114.2212599,
    "target": [
      6333.7,
      80,
      -28419.3
    ],
    "spawn": [
      6333.7,
      -28419.3
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": true
  },
  "nt-ping-che-playground": {
    "region": "ntnorth",
    "title": "Ping Che rural centre",
    "zh": "坪輋鄉郊中心",
    "sectionId": "18.4",
    "description": "Explore the mapped public playground and village approaches at Ping Che.",
    "source": "https://www.openstreetmap.org/way/722685062",
    "lat": 22.5280311,
    "lon": 114.1584077,
    "target": [
      -131.8,
      80,
      -26647.1
    ],
    "spawn": [
      -128.5,
      -26654.3
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/789239269"
  },
  "nt-lin-ma-hang-border": {
    "region": "ntnorth",
    "title": "Lin Ma Hang border landscape",
    "zh": "蓮麻坑邊境地景",
    "sectionId": "18.5",
    "description": "An aerial reference for the eastern border villages and surrounding hills. Aerial overview only; border access and closed-area restrictions are not modelled as walkable routes.",
    "source": "https://www.openstreetmap.org/node/7174065164",
    "lat": 22.550949,
    "lon": 114.1812937,
    "target": [
      2222.6,
      94.0,
      -29184.9
    ],
    "spawn": [
      2222.6,
      -29184.9
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": true
  },
  "nt-luk-keng-village": {
    "region": "ntnorth",
    "title": "Luk Keng village approach",
    "zh": "鹿頸村入口",
    "sectionId": "18.6",
    "description": "Explore the village playground and foothill paths beside Starling Inlet.",
    "source": "https://www.openstreetmap.org/way/696281456",
    "lat": 22.5224546,
    "lon": 114.2160203,
    "target": [
      5795.3,
      80,
      -26030.0
    ],
    "spawn": [
      5801.2,
      -25961.8
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/180798395"
  },
  "nt-lai-chi-wo-trail": {
    "region": "ntnorth",
    "title": "Lai Chi Wo nature trail",
    "zh": "荔枝窩自然步道",
    "sectionId": "18.7",
    "description": "Explore the mapped village-edge trail and Yan Chau Tong coastal setting.",
    "source": "https://www.openstreetmap.org/way/249657682",
    "lat": 22.5269062,
    "lon": 114.2608392,
    "target": [
      10406.0,
      80,
      -26524.8
    ],
    "spawn": [
      10402.7,
      -26526.9
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1050479557"
  },
  "nt-kat-o-main-street": {
    "region": "ntnorth",
    "title": "Kat O village and coast",
    "zh": "吉澳村與海岸",
    "sectionId": "18.8",
    "description": "Explore the mapped village street and coastal setting of Kat O.",
    "source": "https://www.openstreetmap.org/way/705937307",
    "lat": 22.5474517,
    "lon": 114.2912705,
    "target": [
      13534.9,
      80,
      -28802.1
    ],
    "spawn": [
      13534.9,
      -28802.1
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/705937307"
  },
  "nt-chuen-lung": {
    "region": "ntwest",
    "title": "Chuen Lung village trail",
    "zh": "川龍村徑",
    "sectionId": "11.4",
    "description": "A village trail approach below Tai Mo Shan.",
    "source": "https://www.openstreetmap.org/way/306476306",
    "lat": 22.3942294,
    "lon": 114.1055962,
    "target": [
      -5571.8,
      354.6,
      -11832.0
    ],
    "spawn": [
      -5506.5,
      -11861.9
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/306476307"
  },
  "nt-tsing-yi-nature-trail": {
    "region": "ntwest",
    "title": "Tsing Yi Reunification Trail",
    "zh": "青衣回歸徑",
    "sectionId": "12.6",
    "description": "Explore the island's hill paths above the channel and bridge approaches.",
    "source": "https://www.openstreetmap.org/way/139958742",
    "lat": 22.3572594,
    "lon": 114.0897165,
    "target": [
      -7209.4,
      190.2,
      -7738.9
    ],
    "spawn": [
      -7209.4,
      -7738.9
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/139958742"
  },
  "nt-tai-po-kau-walk": {
    "region": "nteast",
    "title": "Tai Po Kau forest walks",
    "zh": "大埔滘林徑",
    "sectionId": "14.4",
    "description": "Explore the mapped forest path in the nature reserve.",
    "source": "https://www.openstreetmap.org/way/58702470",
    "lat": 22.4243467,
    "lon": 114.1869191,
    "target": [
      2802.1,
      350.7,
      -15165.3
    ],
    "spawn": [
      2802.1,
      -15165.3
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/58702470"
  },
  "nt-hoi-ha-trail": {
    "region": "nteast",
    "title": "Hoi Ha Wan nature trail",
    "zh": "海下灣自然教育徑",
    "sectionId": "14.7",
    "description": "Explore the mapped nature trail around Hoi Ha Wan Marine Park.",
    "source": "https://www.openstreetmap.org/way/90793914",
    "lat": 22.4619733,
    "lon": 114.3347371,
    "target": [
      18015.9,
      80,
      -19340.5
    ],
    "spawn": [
      18015.9,
      -19340.5
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/90793914"
  },
  "nt-high-island-geo-trail": {
    "region": "nteast",
    "title": "High Island geo trail",
    "zh": "萬宜地質步道",
    "sectionId": "15.6",
    "description": "Explore the mapped trail near High Island Reservoir's eastern dam and Po Pin Chau.",
    "source": "https://www.openstreetmap.org/way/133800998",
    "lat": 22.3593597,
    "lon": 114.3739199,
    "target": [
      22063.7,
      80,
      -7982.2
    ],
    "spawn": [
      22063.7,
      -7982.2
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/133800998"
  },
  "nt-long-ke-wan": {
    "region": "nteast",
    "title": "Long Ke Wan",
    "zh": "浪茄灣",
    "sectionId": "15.7",
    "description": "Explore the mapped sandy bay and nearby country-park trail.",
    "source": "https://www.openstreetmap.org/way/85964199",
    "lat": 22.374266,
    "lon": 114.3763932,
    "target": [
      22316.3,
      80,
      -9633.2
    ],
    "spawn": [
      22264.1,
      -9652.9
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/302855822"
  },
  "nt-lau-fau-shan": {
    "region": "ntwest",
    "title": "Lau Fau Shan coastal approach",
    "zh": "流浮山海岸入口",
    "sectionId": "17.3",
    "description": "Start on the village-side public approach near the seafood-market coast.",
    "source": "https://www.openstreetmap.org/way/144358836",
    "lat": 22.4673654,
    "lon": 113.9838282,
    "target": [
      -18100.4,
      80,
      -19941.8
    ],
    "spawn": [
      -18092.9,
      -19942.7
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/1531388810"
  },
  "nt-ta-kwu-ling-playground": {
    "region": "ntnorth",
    "title": "Ta Kwu Ling playground",
    "zh": "打鼓嶺遊樂場",
    "sectionId": "18.4",
    "description": "Explore the public village playground and rural roads around Ta Kwu Ling.",
    "source": "https://www.openstreetmap.org/way/447880861",
    "lat": 22.5308814,
    "lon": 114.153853,
    "target": [
      -600.3,
      80,
      -26962.8
    ],
    "spawn": [
      -577.2,
      -26981.0
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/789144718"
  },
  "nt-ap-chau-route": {
    "region": "ntnorth",
    "title": "Ap Chau geo route",
    "zh": "鴨洲地質步道",
    "sectionId": "18.8",
    "description": "Browse the tiny island's mapped geo route and village shore.",
    "source": "https://www.openstreetmap.org/way/337004520",
    "lat": 22.5519262,
    "lon": 114.2697806,
    "target": [
      11324.1,
      80,
      -29296.0
    ],
    "spawn": [
      11304.8,
      -29283.3
    ],
    "offset": [
      1100,
      850,
      1400
    ],
    "aerialOnly": false,
    "arrivalSource": "https://www.openstreetmap.org/way/762306316"
  }
};
