/** Deterministic source-form audit. No acquisition, AI, source edits or visual acceptance. */
import{readFileSync,writeFileSync,existsSync,createReadStream,createWriteStream}from'node:fs';
import{createHash}from'node:crypto';import{createGzip,createGunzip}from'node:zlib';import{createInterface}from'node:readline';import{once}from'node:events';import{resolve,dirname}from'node:path';import{fileURLToPath}from'node:url';
import{makeTerrainSampler,inPolygon}from'../../../3d-viewer/city/geo.js';
export const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'../../..');
export const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v!==null&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
export const hash=v=>createHash('sha256').update(typeof v==='string'||Buffer.isBuffer(v)?v:canonical(v)).digest('hex');
const read=p=>JSON.parse(readFileSync(resolve(ROOT,p))),fileHash=p=>hash(readFileSync(resolve(ROOT,p)));
export function bounds(b){const points=(Array.isArray(b.rings)?b.rings:[]).flat();if(!points.length||!points.every(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite)))return null;return[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1])),Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))];}
const intersects=(a,b)=>!a||Math.max(a[0],b[0])<=Math.min(a[2],b[2])&&Math.max(a[1],b[1])<=Math.min(a[3],b[3]);
function terrainBounds(d){const g=d.meta.georef,x=g.bE-834500,z=816500-g.bN;return[x,z,x+(d.w-1)*g.aE,z-(d.h-1)*g.aN];}
export function terrainDependencies(bb,tree){return tree.flatMap(t=>intersects(bb,t.bounds)?[[t.id,t.sha],...terrainDependencies(bb,t.children)]:[]);}
function descriptor(d,id){const{patches,...base}=d;return{id,bounds:terrainBounds(d),sha:hash(base),children:(patches||[]).map((p,i)=>descriptor(p,id+'/'+(p.id||i)))};}
export function audit(b,model,sampler){
 const flags=[],finite=n=>typeof n==='number'&&Number.isFinite(n);let validRings=true,area=0,vertices=0;
 if(!b.uid)flags.push('missing-source-uid');if(b.uid?.startsWith('landsd/')&&!/^landsd\/[1-9][0-9]*:(0|[1-9][0-9]*)$/.test(b.uid))flags.push('noncanonical-government-uid');
 if(b.uid?.startsWith('landsd/')&&!b.buildingCSUID)flags.push('missing-government-csuid');
 if(!Array.isArray(b.rings)||!b.rings.length){flags.push('missing-rings');validRings=false;}
 for(const[rIndex,ring]of(Array.isArray(b.rings)?b.rings:[]).entries()){
  if(!Array.isArray(ring)||ring.length<4||!ring.every(p=>Array.isArray(p)&&p.length===2&&p.every(finite))){flags.push('invalid-ring-coordinates');validRings=false;continue;}
  vertices+=ring.length;const last=ring.at(-1);if(ring[0][0]!==last[0]||ring[0][1]!==last[1]){flags.push('unclosed-ring');validRings=false;}
  let a=0;for(let i=1;i<ring.length;i++)a+=ring[i-1][0]*ring[i][1]-ring[i][0]*ring[i-1][1];a=Math.abs(a/2);if(a<=1e-8)flags.push('zero-area-ring');area+=(rIndex?-1:1)*a;
 }
 if(area<=0)flags.push('non-positive-net-footprint-area');if(!finite(b.base))flags.push('non-finite-base');if(!finite(b.height)||b.height<=0)flags.push('non-positive-or-non-finite-height');
 if(finite(b.baseHeightHKPD)&&finite(b.topHeightHKPD)&&b.topHeightHKPD<=b.baseHeightHKPD)flags.push('non-positive-surveyed-height-pair');
 const detail=model.length?'native-catalogue':b.modelGeometry?'embedded':'basic';for(const m of model){if(m.record.buildingCSUID&&b.buildingCSUID&&m.record.buildingCSUID!==b.buildingCSUID)flags.push('native-csuid-mismatch');if(m.assetState!=='verified')flags.push('native-asset-'+m.assetState);}if(model.length>1)flags.push('multiple-native-catalogue-records');
 let terrain={state:'not-run-invalid-input'};
 if(validRings&&finite(b.base)&&finite(b.height)&&sampler){const pts=[];for(const ring of b.rings)for(let i=1;i<ring.length;i++)pts.push(ring[i],[(ring[i][0]+ring[i-1][0])/2,(ring[i][1]+ring[i-1][1])/2]);const bb=bounds(b),centre=[(bb[0]+bb[2])/2,(bb[1]+bb[3])/2];if(inPolygon(...centre,b.rings))pts.push(centre);
  try{if(sampler.contains&&!pts.every(p=>sampler.contains(...p))){terrain={state:'not-run-outside-terrain-domain'};flags.push('outside-terrain-domain');return{flags:[...new Set(flags)].sort(),detail,vertices,areaM2:Math.round(area*1e4)/1e4,estimatedHeight:b.heightSource!=='landsd',terrain,nativeGeometryCollision:'not-checked',visualAcceptance:'not-checked',ringSelfIntersection:'not-checked'};}const heights=pts.map(p=>sampler.height(...p));if(!heights.every(finite))throw Error('non-finite');const min=Math.min(...heights),max=Math.max(...heights),roof=b.base+b.height;terrain={state:'sampled-source-footprint-envelope',samples:pts.length,min,max,baseAboveAllSamples:b.base>max+.5,roofBelowAnySample:roof<max-.25,roofBelowAllSamples:roof<min-.25};if(terrain.baseAboveAllSamples)flags.push('sampled-base-above-terrain');if(terrain.roofBelowAnySample)flags.push('sampled-roof-partly-below-terrain');if(terrain.roofBelowAllSamples)flags.push('sampled-roof-wholly-below-terrain');}catch{terrain={state:'not-run-terrain-sampler-error'};flags.push('terrain-sampler-error');}}
 else if(!sampler)terrain={state:'not-run-terrain-unavailable'};
 return{flags:[...new Set(flags)].sort(),detail,vertices,areaM2:Math.round(area*1e4)/1e4,estimatedHeight:b.heightSource!=='landsd',terrain,nativeGeometryCollision:'not-checked',visualAcceptance:'not-checked',ringSelfIntersection:'not-checked'};
}
function state(){const manifest=read('3d-viewer/city/data/manifest.json'),terrain=read('3d-viewer/city/data/terrain.json'),modelMap=new Map(),files={};
 for(const path of manifest.officialModelCatalogues||[]){const c=read('3d-viewer/'+path);files[path]=fileHash('3d-viewer/'+path);for(const record of c.models){const p=resolve(ROOT,'3d-viewer',dirname(path),record.asset);if(!p.startsWith(resolve(ROOT,'3d-viewer')+'/'))throw Error('Asset escapes viewer');const actual=existsSync(p)?hash(readFileSync(p)):null;const m={record,assetState:actual===record.sha256?'verified':actual?'hash-mismatch':'missing',actual};const arr=modelMap.get(record.uid)||[];arr.push(m);modelMap.set(record.uid,arr);}}
 terrain.patches=(manifest.terrainPatches||[]).map(p=>read('3d-viewer/'+p.url));const tree=[descriptor(terrain,'city/data/terrain.json')];const pipeline=hash(['source-scripts/city/citywide-audit/engine.mjs','3d-viewer/city/geo.js','3d-viewer/city/native-terrain.js'].map(p=>[p,fileHash(p)]));return{manifest,terrain,tree,modelMap,files,pipeline};}
function key(b,models,pipeline,tree){const sourceSha=hash(b),modelSha=hash(models),terrainSha=hash(terrainDependencies(bounds(b),tree));return{uid:b.uid,sourceSha,modelSha,pipelineSha:pipeline,terrainSha,cacheKey:hash([b.uid,sourceSha,modelSha,pipeline,terrainSha])};}
export async function lines(path){const rows=[];for await(const line of createInterface({input:createReadStream(path).pipe(createGunzip()),crlfDelay:Infinity}))if(line)rows.push(JSON.parse(line));return rows;}
async function output(path,fn){const gz=createGzip({level:6}),dest=createWriteStream(path);gz.pipe(dest);const emit=async row=>{if(!gz.write(JSON.stringify(row)+'\n'))await once(gz,'drain');};await fn(emit);gz.end();await once(dest,'finish');}
async function main(){const[mode,out,metaOrRequest]=process.argv.slice(2),s=state();let requests=null,sampler=null;if(mode==='compute'){requests=new Map((await lines(metaOrRequest)).map(r=>[r.uid,r]));sampler=makeTerrainSampler(s.terrain);}else if(mode!=='plan')throw Error('Expected plan or compute');const seen=new Set(),counts={buildings:0,tiles:0,audited:0},inputs=[];const started=performance.now();
 await output(out,async emit=>{for(const tile of s.manifest.tiles){const path='3d-viewer/'+tile.url,raw=readFileSync(resolve(ROOT,path)),data=JSON.parse(raw);if(data.id!==tile.id||data.buildings.length!==tile.counts.buildings)throw Error('Tile identity/count mismatch');inputs.push([path,hash(raw)]);counts.tiles++;for(const b of data.buildings){if(!b.uid||seen.has(b.uid))throw Error('Missing/duplicate source UID');seen.add(b.uid);counts.buildings++;if(requests&&!requests.has(b.uid))continue;const models=s.modelMap.get(b.uid)||[],row={...key(b,models,s.pipeline,s.tree),tile:tile.id};if(requests){if(requests.get(b.uid).cacheKey!==row.cacheKey)throw Error('Frozen input changed: '+b.uid);row.result=audit(b,models,sampler);counts.audited++;}await emit(row);}}});
 if(requests&&counts.audited!==requests.size)throw Error('Requested UID missing');const meta={issue:'HKS-221',...counts,pipelineSha:s.pipeline,planSha:fileHash(out),inputFiles:inputs,catalogues:s.files,seconds:(performance.now()-started)/1000,scope:'Deterministic source-form metadata and finite footprint-envelope terrain sampling only; no native triangle, collision or visual approval.'};if(mode==='plan'){meta.runId=hash([counts.buildings,s.pipeline,meta.planSha]);writeFileSync(metaOrRequest,JSON.stringify(meta,null,2)+'\n');}console.log(JSON.stringify({...meta,inputFiles:undefined,catalogues:undefined}));}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch(e=>{console.error(e.message);process.exitCode=1;});
