"""Prepare compact authoritative evidence after the corrected full run and unchanged repeat."""
import argparse,collections,hashlib,json,pathlib,shutil
HERE=pathlib.Path(__file__).resolve().parent;ROOT=HERE.parents[2]
def main():
 p=argparse.ArgumentParser();p.add_argument('--run-id',required=True);a=p.parse_args();folder=HERE/'local'/a.run_id;reports=[json.loads(f.read_text())for f in folder.glob('run-*.json')];full=next(r for r in reports if r['newlyAudited']==r['expected']and r['missing']==0);repeat=next(r for r in reports if r['newlyAudited']==0 and r['reusedAtStart']==r['expected']and r['missing']==0)
 assert full['pipelineSha']==repeat['pipelineSha']and full['flags']==repeat['flags']and full['detail']==repeat['detail'];assert full['expected']==repeat['expected'];assert full['detail'].get('embedded',0)>0
 doc=ROOT/'docs/astra-city/citywide-audit';doc.mkdir(parents=True,exist_ok=True);write=lambda name,x:(doc/name).write_text(json.dumps(x,indent=2)+'\n');write('first-run.json',full);write('unchanged-repeat.json',repeat);meta=json.loads((folder/'plan.json').read_text());write('input-plan.json',meta)
 old=HERE/'local/11d9e3989cb01fcd3dd1e403794ee7ce04fd7cdb33a4195fbaf8205c6830e79c';old_reports=[json.loads(f.read_text())for f in old.glob('run-*.json')];write('superseded-classification.json',{'supersededRun':old.name,'reason':'Earlier classifier checked model instead of existing modelGeometry and labelled1859 embedded forms basic. Corrected code, regression test, fresh pipeline and full rerun replace its detail totals. Terrain checks were unchanged.','oldReports':old_reports})
 verification={'issue':'HKS-221','authoritativeRun':a.run_id,'pipelineSha':full['pipelineSha'],'engineTests':{'passed':7,'command':'node --test source-scripts/city/citywide-audit/test_engine.mjs'},'liveNeonTests':{'passed':5,'seconds':86.991,'command':'MODELLING_INTEGRATION_TEST=1 python -m unittest discover -s source-scripts/city/citywide-audit -p test_store.py -v','includes':'Final expiry after COPY rolls back all grouped cache rows and other chunk completions; restart, cross-label reuse, selective invalidation, concurrent claims, fingerprint rejection.'},'sourceForms':full['expected'],'tiles':full['tiles'],'terrainChecked':full['terrain'],'newChecksOnRepeat':repeat['newlyAudited'],'cachedOnRepeat':repeat['reusedAtStart'],'visualAcceptance':'not-checked','nativeTriangleCollision':'not-checked','sourceDownloads':0,'aiCallsInsideScripts':0,'r2ArchiveRoot':str(folder.relative_to(ROOT)),'artefacts':[{'path':str(f.relative_to(ROOT)),'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'bytes':f.stat().st_size}for f in sorted(folder.iterdir())if f.is_file()]};write('verification.json',verification)
 (doc/'README.md').write_text(f'''# HKS-221 — scripted citywide audit

The corrected pipeline audited **{full['expected']:,} source forms across {full['tiles']} current tiles**. Full execution including initial Neon persistence took **{full['seconds']:.3f} seconds**; the unchanged run under another batch label took **{repeat['seconds']:.3f} seconds**, reused **{repeat['reusedAtStart']:,} cached results**, and performed **zero new terrain checks**.

Current source declarations contain {full['detail'].get('native-catalogue',0):,} native-catalogue entries, {full['detail'].get('embedded',0):,} embedded models and {full['detail'].get('basic',0):,} basic forms. Catalogue/embedded counts are not the separate manually installed-and-verified review ledger, and do not establish visual acceptance.

Terrain diagnostics found {full['flags'].get('sampled-base-above-terrain',0):,} envelopes with their base above every sample, {full['flags'].get('sampled-roof-partly-below-terrain',0):,} with roof below at least one sample, and {full['flags'].get('sampled-roof-wholly-below-terrain',0):,} below every sample. Categories overlap. These are **source footprint-envelope review candidates**, not confirmed buried or floating native models: towers may have podium support and actual native roof shapes differ. No model was moved, downloaded, accepted or published.

All actual terrain checks use the existing exact sampler at source elevations. Self-intersection, native triangle/collision checks and visual inspection remain explicitly unperformed. Seven engine tests and five real pinned-Neon tests passed. The latter prove grouped transaction rollback when even one final lease expires after COPY.

See verification.json for exact hashes and the authoritative R2 archive root. The prior classification error is retained only as compact superseded provenance. Resume commands and implementation details are in source-scripts/city/citywide-audit/README.md. Use the pinned modelling branch; unchanged reruns reuse accepted results across batch names.
''');print(json.dumps({'sourceForms':full['expected'],'firstSeconds':full['seconds'],'repeatSeconds':repeat['seconds'],'detail':full['detail'],'archiveRoot':verification['r2ArchiveRoot']}))
if __name__=='__main__':main()
