import test from'node:test';import assert from'node:assert/strict';import{audit,hash,terrainDependencies}from'./engine.mjs';import{makeTerrainSampler}from'../../../3d-viewer/city/geo.js';
const building=()=>({uid:'landsd/1:0',buildingCSUID:'source',rings:[[[0,0],[1,0],[1,1],[0,1],[0,0]]],base:1.2,height:3,heightSource:'landsd'}),flat={height:()=>1.2};
test('valid source envelope audit leaves visual checks separate',()=>{const r=audit(building(),[],flat);assert.deepEqual(r.flags,[]);assert.equal(r.terrain.samples,9);assert.equal(r.visualAcceptance,'not-checked');});
test('malformed coordinates and absent heights are explicit, never silently accepted',()=>{const b=building();b.rings[0][1]=[null,0];b.height=null;const r=audit(b,[],flat);assert.ok(r.flags.includes('invalid-ring-coordinates'));assert.equal(r.terrain.state,'not-run-invalid-input');});
test('source identity, missing/mismatched assets and holes remain distinct',()=>{const b=building(),r=audit(b,[{record:{buildingCSUID:'different'},assetState:'missing'}],flat);assert.ok(r.flags.includes('native-csuid-mismatch'));assert.ok(r.flags.includes('native-asset-missing'));});
test('actual sampler follows triangle diagonal and yields bounded terrain flags',()=>{const t={w:2,h:2,elev:[2,4,6,20],meta:{georef:{bE:834500,bN:816500,aE:1,aN:-1}}};const s=makeTerrainSampler(t);assert.equal(s.height(.25,.25),3.5);assert.equal(s.height(.75,.75),12.5);const b=building();b.rings=[[[.1,.1],[.9,.1],[.9,.9],[.1,.9],[.1,.1]]];assert.ok(audit(b,[],s).flags.includes('sampled-roof-partly-below-terrain'));assert.equal(audit(building(),[],s).terrain.state,'not-run-outside-terrain-domain');});
test('cache terrain dependencies ignore unrelated sibling changes but invalidate intersecting source or base',()=>{const tree=[{id:'base',bounds:[0,0,100,100],sha:'base-a',children:[{id:'near',bounds:[0,0,10,10],sha:'near-a',children:[]},{id:'far',bounds:[90,90,100,100],sha:'far-a',children:[]}]}];const key=()=>hash(terrainDependencies([1,1,2,2],tree)),a=key();tree[0].children[1].sha='far-b';assert.equal(key(),a);tree[0].children[0].sha='near-b';assert.notEqual(key(),a);const b=key();tree[0].sha='base-b';assert.notEqual(key(),b);});
test('sampling failure is explicit unavailable work',()=>{assert.equal(audit(building(),[],{height(){throw Error('missing')}}).terrain.state,'not-run-terrain-sampler-error');});

test('embedded native forms use the actual modelGeometry field',()=>{const b=building();b.modelGeometry={position:[1,2,3]};assert.equal(audit(b,[],flat).detail,'embedded');});
