/** Isolated before/after native-ground diagnostics; no runtime data edits. */
import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {browserExecutable} from '../landmark-preflight/browser-runtime.mjs';
const require=createRequire(new URL('../../../3d-viewer/city/package.json',import.meta.url)),{chromium}=require('playwright');
const root=new URL('../../../',import.meta.url),read=async p=>JSON.parse(await readFile(new URL(p,root),'utf8'));
const audit=await read('docs/astra-city/roof-occlusion-review/audit.json'),review=await read('docs/astra-city/roof-occlusion-review/patch-review.json'),pin=await read('source-scripts/city/landmark-preflight/snapshot.json'),base=`source-scripts/city/landmark-preflight/snapshots/${pin.id}/`,original=await read(base+'catalogue.json'),uids=audit.rows.map(r=>r.uid),catalogue={...original,counts:{...original.counts,packedModels:uids.length},models:original.models.filter(m=>uids.includes(m.uid))},catalogueURL='city/data/official-models/roof-review/catalogue.json',out=new URL('docs/astra-city/roof-occlusion-review/browser/',root);
await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:browserExecutable(chromium),args:['--enable-webgl','--ignore-gpu-blocklist']}),report={issue:'HKS-214',snapshotId:pin.id,views:[],errors:[],limits:['Diagnostic native models and terrain with unrelated buildings hidden; not ordinary scene visibility or complete-landmark acceptance.','Patch routes are browser-only; source model heights unchanged.']};
try{
 for(const mode of ['before','candidate']){
  const page=await browser.newPage({viewport:{width:1280,height:900}});page.on('pageerror',e=>report.errors.push(e.message));
  await page.route('**/city/app.js',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text())+'\nObject.defineProperty(window,"__roof",{get:()=>({scene,officialModels,stream,camera,controls,renderer,sampler,THREE,terrain,visitBuilding,closeSelection,controlSheet})});\n'});});
  await page.route('**/'+catalogueURL,r=>r.fulfill({json:catalogue}));
  for(const m of catalogue.models)await page.route('**/city/data/official-models/roof-review/'+m.asset,async r=>r.fulfill({body:await readFile(new URL(base+'assets/'+m.asset,root)),contentType:'application/gzip'}));
  for(const row of review.rows)await page.route('**/city/data/'+row.candidate.split('/').at(-1),async r=>r.fulfill({json:await read(row.candidate)}));
  await page.route('**/city/data/manifest.json',async r=>{const response=await r.fetch(),m=await response.json();m.officialModelCatalogues=[...m.officialModelCatalogues,catalogueURL];if(mode==='candidate')m.terrainPatches=[...m.terrainPatches,...review.rows.map(row=>({url:'city/data/'+row.candidate.split('/').at(-1)}))];await r.fulfill({response,json:m});});
  await page.goto('http://127.0.0.1:4176/city.html?district=central');await page.waitForFunction(()=>window.__city?.ready,null,{timeout:180000});await page.locator('#loading').waitFor({state:'hidden',timeout:180000});
  for(const row of audit.rows){console.log(mode,row.uid,'focusing');
   await page.evaluate(b=>{const r=window.__roof;r.stream.buildings.visible=true;window.__roofGroup?.removeFromParent();r.visitBuilding(b);},row.buildingRecord);await page.waitForFunction(()=>!window.__city.state.loadingTravel&&!window.__city.state.travelling,null,{timeout:120000});await page.evaluate(bounds=>{const r=window.__roof,[a,b]=bounds,c=a.map((v,i)=>(v+b[i])/2);r.camera.position.set(c[0]-25,b[1]+25,c[2]+25);r.controls.target.set(c[0],c[1],c[2]);r.controls.update();},row.modelBounds);await page.waitForFunction(uid=>window.__roof.stream.detailedModels.get(uid)?.active,row.uid,{timeout:45000});
   const detail=await page.evaluate(({uid,bounds,label,mode})=>{const r=window.__roof,d=r.stream.detailedModels.get(uid);d.group.updateMatrixWorld(true);const clone=d.group.clone(true);clone.applyMatrix4(d.group.parent.matrixWorld);clone.visible=true;r.scene.add(clone);window.__roofGroup=clone;r.stream.buildings.visible=false;r.closeSelection();r.controlSheet.close({restoreFocus:false});const[a,b]=bounds,c=a.map((v,i)=>(v+b[i])/2),span=Math.max(b[0]-a[0],b[2]-a[2]),dist=Math.max(18,span*1.5);r.camera.position.set(c[0]-dist,Math.max(b[1]+dist*.65,r.sampler.height(c[0]-dist,c[2]+dist)+8),c[2]+dist);r.controls.target.set(c[0],c[1],c[2]);r.controls.update();r.camera.updateMatrixWorld(true);const input=document.getElementById('time');input.value='15:00';input.dispatchEvent(new Event('input',{bubbles:true}));let el=document.getElementById('roof-label');if(!el){el=document.createElement('div');el.id='roof-label';Object.assign(el.style,{position:'fixed',top:'78px',left:'20px',zIndex:9999,background:'#fff',color:'#183a32',padding:'12px',font:'13px monospace',maxWidth:'80vw'});document.body.append(el);}el.textContent=`${label} · ${mode} · native heights · unrelated buildings hidden`;return{active:true,camera:r.camera.position.toArray(),target:r.controls.target.toArray(),groundAtCentre:r.sampler.height(c[0],c[2])};},{uid:row.uid,bounds:row.modelBounds,label:row.name,mode});
   await page.waitForTimeout(600);const file=row.uid.replace(/\W/g,'-')+'-'+mode+'.jpg';await page.screenshot({path:new URL(file,out).pathname,type:'jpeg',quality:88});report.views.push({uid:row.uid,mode,file,sha256:createHash('sha256').update(await readFile(new URL(file,out))).digest('hex'),...detail});console.log(row.uid,mode,'captured');
  }
  await page.close();
 }
}finally{await writeFile(new URL('report.json',out),JSON.stringify(report,null,2)+'\n');await browser.close();}
