"""Record reviewed source-component placement, not whole-landmark completion."""
import json
from pathlib import Path
import native_terrain as n
h=Path(__file__).resolve().parent;b=n.OUT;r=n.read(b/'framing-exact/report.json');assert len(r['rows'])==4 and not r['errors'];assert all(v['final']['clear'] for p in r['rows'] for v in p['views'])
notes={'landsd/103538:0':'Small retained Highcliff source component; native ground contacts, no wholly buried faces.','landsd/176291:0':'Highcliff podium component. One deep rim sample occurs at retaining context. No wholly buried native triangle or upward roof; complete exposed curved facade visible.','landsd/176748:0':'Summit podium component. Nine rim samples meet the rising retaining edge. No wholly buried native triangles or upward roofs; exposed facade and roof visible.','landsd/257313:0':'39 Conduit lower podium component. Seven wholly buried triangles: five downward floor faces and two lower vertical basement/retaining faces (106.73 square metres). No buried upward roofs; front facade and roof exposed in normal and isolated views. Exact native terrain and building elevations preserved.'}
c=n.read(h/'exact-candidates/catalogue.json')
for m in c['models']:m['placementReviewed']=True;m['placementReview']=notes[m['uid']];m['wholeLandmarkAccepted']=False
(h/'exact-candidates/catalogue.json').write_text(json.dumps(c,indent=2)+'\n');(h/'plan-exact.json').write_text(json.dumps({'areas':[{'area':'source-exact-tin-components','catalogue':str((h/'exact-candidates/catalogue.json').relative_to(n.ROOT)),'destination':'city/data/official-models/support-exact-tin-20260909/catalogue.json'}]},indent=2)+'\n')
e={'issue':'HKS-214','parts':4,'approvedSourceUids':list(notes),'views':8,'browserErrors':r['errors'],'notes':notes,'browserReportSha256':n.sha(b/'framing-exact/report.json'),'triangleAssessmentSha256':n.sha(b/'exact-surface-review.json'),'requiredTerrainPatches':n.read(b/'exact-tin.json')['patches'],'sourceGeometryUnchanged':True,'verticalScale':1,'nativeMeshRuntimeRequired':True,'runtimePublished':False,'limits':['Placement acceptance of these exact source components is not whole-landmark architectural completion.','Underground source triangles retained; no shifts or invented foundation geometry.','Parent must validate Float32 projected coverage, parent boundary and combined manifest before publication.']};(b/'visual-acceptance-exact.json').write_text(json.dumps(e,indent=2)+'\n')
print('Four exact native source components accepted with required terrain patches')
