import {readFileSync,writeFileSync} from 'node:fs';
import {prepareModelCatalogue,loadOfficialModel,disposeOfficialModel} from '../../../3d-viewer/city/official-model-assets.js';
import {makeTerrainSampler} from '../../../3d-viewer/city/geo.js';
import {nativeTerrainSurface} from '../../../3d-viewer/city/native-terrain.js';
import * as THREE from '../../../3d-viewer/vendor/three.module.js';
const read=p=>JSON.parse(readFileSync(p)),base='source-scripts/city/assembly-support-review/',cat=read(base+'foundation-candidates/catalogue.json'),mf=read('3d-viewer/city/data/manifest.json'),buildings=new Map();for(const t of mf.tiles)for(const b of read('3d-viewer/'+t.url).buildings)buildings.set(b.uid,b);
const terrain=read('3d-viewer/city/data/terrain.json');terrain.patches=mf.terrainPatches.map(p=>read('3d-viewer/'+p.url));const terrainSampler=makeTerrainSampler(terrain);const surfaces=[{data:{meta:{targetUids:cat.models.map(m=>m.uid)}},surface:terrainSampler}],lighting={night:{value:0},activity:{value:new THREE.Vector4(1,1,1,1)},retail:{value:1},elapsed:{value:0},shimmer:{value:0}},rows=[];
for(const e of prepareModelCatalogue(cat,'http://review.local/catalogue.json')){const raw=readFileSync(base+'foundation-candidates/'+e.asset),model=await loadOfficialModel(e,buildings.get(e.uid),lighting,{fetcher:async()=>new Response(raw)}),g=model.record.modelGeometry,s=surfaces.find(s=>s.data.meta.targetUids.includes(e.uid)),bad=[],roofBad=[];let area=0,buriedArea=0,partialArea=0,roofArea=0;
for(let i=0;i<g.index.length;i+=3){const p=[0,1,2].map(k=>new THREE.Vector3().fromArray(g.position,g.index[i+k]*3)),t=new THREE.Triangle(...p),a=t.getArea(),normal=t.getNormal(new THREE.Vector3()),centre=t.getMidpoint(new THREE.Vector3()),pts=[...p,centre],gaps=pts.map(v=>{const h=s.surface.height(v.x,v.z);return h===null?null:v.y-h;});area+=a;if(gaps.some(v=>v!==null&&v<-.5))partialArea+=a;if(gaps.every(v=>v!==null&&v<-.5)){buriedArea+=a;bad.push({triangle:i/3,area:a,normal:normal.toArray(),centre:centre.toArray(),gapRange:[Math.min(...gaps),Math.max(...gaps)]});}if(normal.y>.25){roofArea+=a;if(gaps.every(v=>v!==null&&v<-.5))roofBad.push(bad.at(-1));}}
const result={uid:e.uid,triangles:g.triangles,area,buriedArea,partialArea,upwardArea:roofArea,buriedTriangles:bad,buriedUpwardTriangles:roofBad,policy:'Actual Float32 native triangle vertices plus centroids against the exact shared runtime terrain sampler; projected overlap may represent valid underground structure. No automatic architectural approval.'};rows.push(result);disposeOfficialModel(model);console.log(e.uid,{area,buriedArea,partialArea,buriedUpward:roofBad.length});}
writeFileSync('docs/astra-city/assembly-support-review/foundation-surface-review.json',JSON.stringify({issue:'HKS-214',rows},null,2)+'\n');
