/** Camera-safe review of the24 already CPU/browser-checked source parts. */
import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {browserExecutable} from '../landmark-preflight/browser-runtime.mjs';
const root=new URL('../../../',import.meta.url),require=createRequire(new URL('3d-viewer/city/package.json',root)),{chromium}=require('playwright'),read=async p=>JSON.parse(await readFile(new URL(p,root),'utf8'));
const selected=await read('source-scripts/city/assembly-support-review/selection-exact.json'),base='source-scripts/city/assembly-support-review/exact-candidates/',cat=await read(base+'catalogue.json'),models=new Map(cat.models.map(m=>[m.uid,m])),dest='city/data/official-models/support-exact-framing/catalogue.json',manifest=await read('3d-viewer/city/data/manifest.json'),buildings=new Map(),out=new URL('docs/astra-city/assembly-support-review/framing-exact/',root);await mkdir(out,{recursive:true});
for(const t of manifest.tiles)for(const b of(await read('3d-viewer/'+t.url)).buildings)if(models.has(b.uid))buildings.set(b.uid,b);
const report={issue:'HKS-214',snapshot:selected.snapshot,selectionSha256:createHash('sha256').update(await readFile(new URL('source-scripts/city/assembly-support-review/selection-exact.json',root))).digest('hex'),rows:[],errors:[],limits:['Full scene and isolated diagnostics are distinguished. Isolated views hide unrelated buildings but preserve native model and terrain.','Camera/ray tests establish inspectable framing, not landmark identity or publication approval.','CPU loader/triangle support evidence remains separate; root runs combined publication checks.']};
const browser=await chromium.launch({headless:true,executablePath:browserExecutable(chromium),args:['--enable-webgl','--ignore-gpu-blocklist']}),page=await browser.newPage({viewport:{width:1280,height:900}});
try{
 page.on('pageerror',e=>report.errors.push(e.message));
 await page.route('**/city/app.js',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text())+'\nObject.defineProperty(window,"__frame",{get:()=>({scene,officialModels,stream,camera,controls,sampler,THREE,terrain,visitBuilding,closeSelection,controlSheet})});\n'});});
 await page.route('**/'+dest,r=>r.fulfill({json:cat}));for(const m of models.values())await page.route('**/city/data/official-models/support-exact-framing/'+m.asset,async r=>r.fulfill({body:await readFile(new URL(base+m.asset,root)),contentType:'application/gzip'}));
 const tb=await read('docs/astra-city/assembly-support-review/exact-tin.json'),rootPatches=[];
 for(const p of tb.patches){const child=await read(p.path);if(p.parentTerrainURL==='city/data/terrain.json'){const url='city/data/'+child.id+'.json';rootPatches.push({url,resolution:1,area:'Native TIN review'});await page.route('**/'+url,r=>r.fulfill({json:child}));}else{const data=await read('3d-viewer/'+p.parentTerrainURL);data.patches=[...(data.patches||[]),child];await page.route('**/'+p.parentTerrainURL,r=>r.fulfill({json:data}));}}
 await page.route('**/city/data/manifest.json',async r=>{const response=await r.fetch(),m=await response.json();m.officialModelCatalogues=[...m.officialModelCatalogues,dest];m.terrainPatches.push(...rootPatches);await r.fulfill({response,json:m});});
 await page.goto('http://127.0.0.1:4176/city.html?district=central');await page.waitForFunction(()=>window.__city?.ready,null,{timeout:180000});await page.locator('#loading').waitFor({state:'hidden',timeout:180000});
 for(const part of selected.parts){
  const model=models.get(part.uid),row={...part,worldBounds:model.worldBounds,views:[],runtimePublicationApproved:false};report.rows.push(row);console.log(part.uid,'framing');
  try{
   await page.evaluate(b=>{const r=window.__frame;r.stream.buildings.visible=true;window.__isolatedFrame?.removeFromParent();r.visitBuilding(b);},buildings.get(part.uid));await page.waitForFunction(()=>!window.__city.state.loadingTravel&&!window.__city.state.travelling,null,{timeout:120000});
   await page.evaluate(bounds=>{const r=window.__frame,[a,b]=bounds,c=a.map((v,i)=>(v+b[i])/2),dist=Math.max(30,b[1]-a[1],b[0]-a[0],b[2]-a[2]);r.camera.position.set(c[0]-dist,b[1]+dist*.5,c[2]+dist);r.controls.target.fromArray(c);r.controls.update();},model.worldBounds);
   await page.waitForFunction(uid=>window.__frame.stream.detailedModels.get(uid)?.active,part.uid,{timeout:60000});
   for(const mode of ['scene','isolated']){
    const result=await page.evaluate(async({uid,bounds,mode,label})=>{
     const r=window.__frame,d=r.stream.detailedModels.get(uid);window.__isolatedFrame?.removeFromParent();r.stream.buildings.visible=true;
     let isolated=null;if(mode==='isolated'){d.group.updateMatrixWorld(true);isolated=d.group.clone(true);isolated.applyMatrix4(d.group.parent.matrixWorld);isolated.visible=true;r.scene.add(isolated);window.__isolatedFrame=isolated;r.stream.buildings.visible=false;}
     r.closeSelection();r.controlSheet.close({restoreFocus:false});const input=document.getElementById('time');input.value='15:00';input.dispatchEvent(new Event('input',{bubbles:true}));
     const[a,b]=bounds,c=a.map((v,i)=>(v+b[i])/2),span=Math.max(b[0]-a[0],b[2]-a[2]),height=b[1]-a[1],radius=Math.hypot(b[0]-a[0],height,b[2]-a[2])/2,dist=Math.max(30,span*1.55,height*.85,radius/Math.tan(r.camera.fov*Math.PI/360)*1.35),attempts=[];
     // Representative actual triangle-centres avoid aiming only into an AABB courtyard.
     const geometry=d.record.modelGeometry,pos=geometry.position,idx=geometry.index,points=[];
     for(let n=0;n<Math.min(21,geometry.triangles);n++){const t=Math.floor(n*geometry.triangles/Math.min(21,geometry.triangles))*3,p=new r.THREE.Vector3();for(let k=0;k<3;k++)p.add(new r.THREE.Vector3().fromArray(pos,idx[t+k]*3));points.push(p.multiplyScalar(1/3));}
     function check(){const contextCollision=r.stream.collision(r.camera.position.x,r.camera.position.z,r.camera.position.y-.3,r.camera.position.y+.3,.3)?.uid||null,occupancy=mode==='scene'||contextCollision===uid?contextCollision:null;let targetRays=0,terrainBlocked=0;for(const target of points){const distance=r.camera.position.distanceTo(target),ray=new r.THREE.Raycaster(r.camera.position.clone(),target.clone().sub(r.camera.position).normalize(),.05,distance+.02),hit=ray.intersectObjects(mode==='isolated'?[isolated]:r.stream.pickMeshes(ray.ray),true)[0],targetHit=!!hit&&(mode==='isolated'||r.stream.featureAt(hit)?.uid===uid);const ground=ray.intersectObjects([r.terrain],true)[0];if(ground&&(!hit||ground.distance<hit.distance-.05))terrainBlocked++;else if(targetHit&&hit.distance>2)targetRays++;}const aboveGround=r.camera.position.y>r.sampler.height(r.camera.position.x,r.camera.position.z)+1,projected=[];for(const x of[a[0],b[0]])for(const y of[a[1],b[1]])for(const z of[a[2],b[2]])projected.push(new r.THREE.Vector3(x,y,z).project(r.camera).toArray());const fullyFramed=projected.every(p=>Math.abs(p[0])<.86&&Math.abs(p[1])<.78&&p[2]>-1&&p[2]<1);return{fullyFramed,projectedBounds:projected,camera:r.camera.position.toArray(),cameraCollisionUid:occupancy,hiddenContextCollisionUid:mode==='isolated'?contextCollision:null,aboveGround,targetRays,totalRays:points.length,terrainBlocked,clear:!occupancy&&aboveGround&&fullyFramed&&targetRays>=Math.min(5,points.length)};}
     for(let attempt=0;attempt<16;attempt++){const angle=attempt%8*Math.PI/4,level=Math.floor(attempt/8),y=b[1]+dist*(level?.85:.3),x=c[0]+Math.cos(angle)*dist,z=c[2]+Math.sin(angle)*dist;r.camera.position.set(x,Math.max(y,r.sampler.height(x,z)+12),z);r.controls.target.fromArray(c);r.controls.update();r.camera.updateMatrixWorld(true);await new Promise(resolve=>setTimeout(resolve,150));const checked=check();attempts.push({attempt,...checked});if(checked.clear&&checked.targetRays>=Math.min(9,points.length))break;}
     const best=[...attempts].sort((a,b)=>(Number(b.clear)-Number(a.clear))||((b.targetRays-b.terrainBlocked)-(a.targetRays-a.terrainBlocked)))[0];r.camera.position.fromArray(best.camera);r.controls.target.fromArray(c);r.controls.update();r.camera.updateMatrixWorld(true);await new Promise(resolve=>setTimeout(resolve,1000));const final=check();let el=document.getElementById('framing-label');if(!el){el=document.createElement('div');el.id='framing-label';Object.assign(el.style,{position:'fixed',top:'78px',left:'20px',zIndex:9999,background:'#fff',color:'#183a32',padding:'10px',font:'13px monospace',maxWidth:'84vw'});document.body.append(el);}el.textContent=`${label} · ${uid} · ${mode==='scene'?'NORMAL SCENE':'ISOLATED NATIVE + TERRAIN'} · ${final.targetRays}/${final.totalRays} target rays · ${final.clear?'clear framing':'occlusion remains'}`;return{mode,attempts,final,active:!!d.active,terrainUnchanged:false,nativeGeometryUnchanged:true};
    },{uid:part.uid,bounds:model.worldBounds,mode,label:part.name});
    await page.waitForTimeout(250);const file=part.uid.replace(/\W/g,'-')+'-'+mode+'.jpg';await page.screenshot({path:new URL(file,out).pathname,type:'jpeg',quality:84});row.views.push({...result,file,sha256:createHash('sha256').update(await readFile(new URL(file,out))).digest('hex')});
   }
   row.framingOutcome=row.views.some(v=>v.final.clear)?'source-part-inspectable':'hold-unresolved-framing';
  }catch(error){row.framingOutcome='hold-capture-failure';row.error=String(error.message);}
  await writeFile(new URL('report.json',out),JSON.stringify(report,null,2)+'\n');console.log(part.uid,row.framingOutcome);
 }
}finally{await writeFile(new URL('report.json',out),JSON.stringify(report,null,2)+'\n');await browser.close();}
