import json,numpy as np,shapely
p=json.load(open('source-scripts/city/assembly-support-review/exact-tin-next/support-exact-tin-232907-0.json'));t=np.array(p['nativeMesh']['position']).reshape(-1,3,3);f=shapely.polygons(t[:,:,[0,2]]);a=shapely.area(f);ids=np.where(a>1e-10)[0];f=f[ids];tree=shapely.STRtree(f);ii,jj=tree.query(f,predicate='intersects');keep=ii<jj;ii=ii[keep];jj=jj[keep];inter=shapely.intersection(f[ii],f[jj]);areas=shapely.area(inter);keep=areas>1e-8;ii=ii[keep];jj=jj[keep];inter=inter[keep];areas=areas[keep]
def y(tri,pt):
 aa=tri[0];uv=np.linalg.solve(np.array([tri[1,[0,2]]-aa[[0,2]],tri[2,[0,2]]-aa[[0,2]]]).T,np.array([pt.x,pt.y])-aa[[0,2]]);return aa[1]+uv[0]*(tri[1,1]-aa[1])+uv[1]*(tri[2,1]-aa[1])
rows=[]
for i,j,g,area in zip(ii,jj,inter,areas):
 pt=g.representative_point();a=t[ids[i]];b=t[ids[j]];rows.append({'triangles':[int(ids[i]),int(ids[j])],'area':float(area),'bounds':list(g.bounds),'heightDifference':float(y(a,pt)-y(b,pt))})

import sys
sys.path.insert(0,'source-scripts/city/assembly-support-review');import native_terrain as n;import terrain_patches as tp
bb=tp.bounds(p);extent=shapely.box(*bb);src=p['meta']['source']['nativeSources'][0];assert n.sha(n.ROOT/src['manifest'])==src['manifestSha256'];
for file in src['files']:assert n.sha(n.ROOT/file['path'])==file['sha256']
_,_,raw,_,_,_=n.terrain_index((n.ROOT/src['manifest']).parent);poly=shapely.polygons(raw[:,:,[0,2]]);clipped=shapely.intersection(poly,extent);area=shapely.area(clipped);valid=clipped[area>1e-10];nativeexcess=float(sum(area)-shapely.union_all(valid).area);summary={'patch':'support-exact-tin-232907-0','source':src,'patchBounds':bb,'nativeProjectedExcessM2':nativeexcess,'stagedProjectedExcessM2':float(sum(shapely.area(f))-shapely.union_all(f).area),'overlapPairs':len(rows),'largestPairM2':max(r['area'] for r in rows),'maxAbsolutePairHeightDifference':max(abs(r['heightDifference']) for r in rows),'overlapBounds':[min(r['bounds'][0] for r in rows),min(r['bounds'][1] for r in rows),max(r['bounds'][2] for r in rows),max(r['bounds'][3] for r in rows)],'policy':'All source facets retained. Overlapping projected faces already exist in the native TIN. Highest surface sampler matches rendered facet geometry; lower source facets remain rendered. No height shifts or face masking.'};open('docs/astra-city/assembly-support-review/branksome-native-overlap.json','w').write(json.dumps(summary,indent=2)+'\n');summary['overlapSamplePoints']=[[float(g.representative_point().x),float(g.representative_point().y)] for _,g in sorted(zip(areas,inter),key=lambda item:-item[0])[:16]];summary['stagedGeometrySha256']=n.sha(n.ROOT/'source-scripts/city/assembly-support-review/exact-tin-next/support-exact-tin-232907-0.json');open('docs/astra-city/assembly-support-review/branksome-native-overlap.json','w').write(json.dumps(summary,indent=2)+'\n');print(json.dumps({'nativeExcess':nativeexcess,'stagedExcess':summary['stagedProjectedExcessM2']}))
