"""Create an unchanged parent-grid extent for exact native TIN replacement."""
import argparse,json,math
from pathlib import Path
import native_terrain as n
import terrain_patches as t
p=argparse.ArgumentParser();p.add_argument('uid');a=p.parse_args();h=Path(__file__).resolve().parent;source=n.read(n.ROOT/'docs/astra-city/landmark-preflight/report.json');row=next(x for x in source['parts'] if x['uid']==a.uid);v=row['candidate']['worldBounds'];bb=[v[0][0]-20,v[0][2]-20,v[1][0]+20,v[1][2]+20];mf=n.read(n.ROOT/'3d-viewer/city/data/manifest.json');parents=[('city/data/terrain.json',n.read(n.ROOT/'3d-viewer/city/data/terrain.json'))]+[(x['url'],n.read(n.ROOT/'3d-viewer'/x['url'])) for x in mf['terrainPatches']];available=[(u,d) for u,d in parents if t.bounds(d)[0]<=bb[0] and t.bounds(d)[1]<=bb[1] and t.bounds(d)[2]>=bb[2] and t.bounds(d)[3]>=bb[3]];url,parent=min(available,key=lambda x:abs(x[1]['meta']['georef']['aE']));g=parent['meta']['georef'];c=abs(g['aE']);cells=[math.floor((bb[0]+834500-g['bE'])/c),math.floor((bb[1]-816500+g['bN'])/c),math.ceil((bb[2]+834500-g['bE'])/c),math.ceil((bb[3]-816500+g['bN'])/c)];assert not any(t.overlap(cells,p['coarseCells']) for p in parent.get('patches',[]));c0,r0,c1,r1=cells;x0=g['bE']+c0*c-834500;z0=816500-g['bN']+r0*c;w=round((c1-c0)*c)+1;hh=round((r1-r0)*c)+1;sampler=t.fine.DemSampler(parent,rendered=True);raw=t.fine.DemSampler(parent);elev=[];rendered=[];veg=[]
for r in range(hh):
 for k in range(w):
  x=x0+k;z=z0+r;elev.append(raw.ground(x,z));rendered.append(sampler.ground(x,z));cc=min(parent['w']-1,round((x+834500-g['bE'])/c));rr=min(parent['h']-1,round((z-816500+g['bN'])/c));veg.append(parent['vegetation'][rr*parent['w']+cc])
sources=[s for s in n.read(n.OUT/'native-terrain.json')['sources'] if t.overlap([x0,z0,x0+w-1,z0+hh-1],[s['worldBounds'][0][0],s['worldBounds'][0][2],s['worldBounds'][1][0],s['worldBounds'][1][2]])];assert sources
patch={'id':'support-native-'+a.uid.replace('landsd/','').replace(':','-'),'w':w,'h':hh,'cell':1,'elev':elev,'renderedElev':rendered,'vegetation':veg,'coarseCells':cells,'meta':{'georef':{'aE':1,'aN':-1,'bE':x0+834500,'bN':816500-z0,'W':w,'H':hh},'parentTerrain':url,'parentSha256':n.sha(n.ROOT/'3d-viewer'/url),'targetUids':[a.uid],'source':{'nativeSources':sources,'policy':'Unchanged parent-sampled extent template only; nativeMesh generated separately.'}}};path=h/'terrain-patches'/(patch['id']+'.json');path.write_text(json.dumps(patch,separators=(',',':'))+'\n');print(path)
