/** Actual app acceptance; run before and after the guarded publisher. */
import {createRequire} from 'node:module';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(new URL('../../../3d-viewer/city/package.json',import.meta.url)),{chromium}=require('playwright');
const root=new URL('../../../',import.meta.url),read=async p=>JSON.parse(await readFile(new URL(p,root),'utf8'));
const phase=process.argv[2]||'before',after=phase==='after';assert.ok(['before','after'].includes(phase));
const config=process.env.REVIEW_CONFIG?await read(process.env.REVIEW_CONFIG):null;
const out=new URL(config?`${config.out}/${phase}/`:`docs/astra-city/building-batch/visual-trial/browser/${phase}${process.env.AREA?'-'+process.env.AREA:''}/`,root);await mkdir(out,{recursive:true});
const samples=config?[]:await read('source-scripts/city/building-batch/local/publication/samples.json');
const plan=await read(config?.plan||'source-scripts/city/building-batch/local/publication/plan.json');
const allModels=(await Promise.all(plan.areas.map(a=>read(a.catalogue)))).flatMap(c=>c.models);
const islandSamples=allModels.filter(m=>m.worldBounds[1][0]<-15000);
const groups=(config?config.groups.map(g=>({...g,selected:g.uids.map(uid=>{const m=allModels.find(m=>m.uid===uid);assert(m,uid);return m;})})):[{area:'central',place:'central',models:samples,selected:samples},{area:'mui-wo',place:'muiwo',models:islandSamples,selected:islandSamples}]).filter(g=>!process.env.AREA||process.env.AREA===g.area);
const needed=new Set(groups.flatMap(g=>g.selected.map(m=>m.uid))),buildings=new Map(),manifest=await read('3d-viewer/city/data/manifest.json');
for(const tile of manifest.tiles){const d=await read('3d-viewer/'+tile.url);for(const b of d.buildings)if(needed.has(b.uid))buildings.set(b.uid,b);}
assert.equal(buildings.size,needed.size);
const report={phase,result:'running',started:new Date().toISOString(),areas:[],errors:[],limits:[config?'Configured landmark samples; CPU validation covers all candidates. No region completeness claim.':'Ten representative Central models tested in browser; all 1,078 additions separately passed CPU screening. No region completeness claim.','Mobile viewport emulation on desktop Chrome; physical-phone performance unverified.']};
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--enable-webgl','--ignore-gpu-blocklist']});let page;
async function open(place,width=1440,failedModel){
 const p=await browser.newPage({viewport:{width,height:width===1440?1000:844},deviceScaleFactor:1,reducedMotion:'reduce',hasTouch:width<760});
 p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400)report.errors.push(r.status()+' '+r.url());});p.on('console',m=>{if(/THREE.WebGLProgram|GL_INVALID|shader error/i.test(m.text()))report.errors.push(m.text());});
 await p.route('**/city/app.js',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text())+'\nObject.defineProperty(window,"__detailReview",{get:()=>({officialModels,stream,camera,controls,renderer,sampler,THREE,nav,terrain,water,environment,visitBuilding,closeSelection,controlSheet,goPlace})});\n'});});
 if(config&&!config.live){
  const replacements=[];
  for(const area of plan.areas){const cat=await read(area.catalogue),base=new URL(area.catalogue,root);replacements.push({area,cat,base});
   await p.route('**/'+area.destination,r=>r.fulfill({json:cat}));
   for(const m of cat.models)await p.route('**/'+area.destination.slice(0,area.destination.lastIndexOf('/')+1)+m.asset,async r=>r.fulfill({body:await readFile(new URL(m.asset,base)),contentType:'application/gzip'}));
  }
  if(after)for(const r of config.terrainReplacements||[])await p.route('**/'+r.url,async route=>route.fulfill({body:await readFile(new URL(r.path,root)),contentType:'application/json'}));
  if(config.terrain)await p.route('**/'+config.terrain.url,async r=>r.fulfill({body:await readFile(new URL(config.terrain.path,root)),contentType:'application/json'}));
  await p.route('**/city/data/manifest.json',async r=>{const response=await r.fetch(),manifest=await response.json();const added=new Set(plan.areas.map(a=>a.destination));manifest.officialModelCatalogues=manifest.officialModelCatalogues.filter(url=>!added.has(url));if(after)manifest.officialModelCatalogues.push(...added);if(config.terrain){manifest.terrainPatches=manifest.terrainPatches.filter(t=>t.url!==config.terrain.url);if(after)manifest.terrainPatches.push({url:config.terrain.url,resolution:5,area:'Ngong Ping landmarks'});}await r.fulfill({response,json:manifest});});
 }else if(!after)await p.route('**/city/data/manifest.json',async r=>{const response=await r.fetch(),manifest=await response.json();manifest.officialModelCatalogues=manifest.officialModelCatalogues.filter(url=>!url.includes('/tourist-trial-'));await r.fulfill({response,json:manifest});});
 let fail=!!failedModel;if(failedModel)await p.route('**/'+failedModel.asset,r=>fail?r.abort('failed'):r.fallback());
 await p.goto('http://127.0.0.1:4176/city.html?district='+place);await p.waitForFunction(()=>window.__city?.ready,null,{timeout:180000});await p.locator('#loading').waitFor({state:'hidden',timeout:180000});await p.waitForFunction(()=>!window.__city.state.loadingTravel&&!window.__city.state.travelling,null,{timeout:120000});return {page:p,recover:()=>{fail=false;}};
}
async function focus(p,m,failed=false){
 const b=buildings.get(m.uid);await p.evaluate(b=>window.__detailReview.visitBuilding(b),b);await p.waitForFunction(()=>!window.__city.state.loadingTravel&&!window.__city.state.travelling,null,{timeout:120000});
 const [a,bounds]=m.worldBounds,centre=a.map((v,i)=>(v+bounds[i])/2),distance=Math.max(config?.views?.[m.uid]?.distance||30,(bounds[0]-a[0])*1.8,(bounds[2]-a[2])*1.8,(bounds[1]-a[1])*.9);
 await p.evaluate(({centre,top,distance,camera})=>{const r=window.__detailReview;r.closeSelection();r.controlSheet.close({restoreFocus:false});if(camera)r.camera.position.fromArray(camera);else r.camera.position.set(centre[0]+distance*.7,top+distance*.75,centre[2]+distance);r.controls.target.fromArray(centre);r.controls.update();r.camera.updateMatrixWorld(true);},{centre,top:bounds[1],distance,camera:config?.views?.[m.uid]?.camera});
 if(after)await p.waitForFunction(({uid,failed})=>failed?window.__detailReview.officialModels.cache.errors.has(uid):window.__detailReview.stream.detailedModels.get(uid)?.active,{uid:m.uid,failed},{timeout:120000});
 await p.waitForTimeout(500);
 await p.waitForFunction(()=>window.__city.state.stream.pending===0&&window.__detailReview.officialModels.stats.pending===0,null,{timeout:120000});
}
async function proof(p,m){return p.evaluate(async uid=>{const r=window.__detailReview,e=r.stream.detailedModels.get(uid),b=r.stream.getLoadedBuilding(uid),ray=new r.THREE.Raycaster(new r.THREE.Vector3(b.centre[0],3000,b.centre[1]),new r.THREE.Vector3(0,-1,0));const terrainHits=ray.intersectObject(r.terrain,true).map(h=>h.point.y);let contact=null,contactColliderUid=null,pick=null;if(e){const {BuildingIndex}=await import('/city/geo.js');const ownIndex=new BuildingIndex([e.record]);const pos=e.record.modelGeometry.position,order=e.record.modelGeometry.index;for(let i=0;i<order.length;i+=3){const ids=[order[i],order[i+1],order[i+2]],q=[0,1,2].map(k=>ids.reduce((s,j)=>s+pos[j*3+k],0)/3);const own=ownIndex.collision(q[0],q[2],q[1]-.05,q[1]+.05,.05),scene=r.stream.collision(q[0],q[2],q[1]-.05,q[1]+.05,.05);if(own?.uid===uid&&scene){contact=q;contactColliderUid=scene.uid;break;}}const meshes=e.meshes;for(const mesh of meshes){const a=mesh.geometry.attributes.position;mesh.updateMatrixWorld(true);for(let i=0;i<a.count;i+=Math.max(1,Math.floor(a.count/70))){const v=new r.THREE.Vector3().fromBufferAttribute(a,i).applyMatrix4(mesh.matrixWorld);for(const origin of [v.clone().add(new r.THREE.Vector3(0,1000,0)),r.camera.position.clone()]){const caster=new r.THREE.Raycaster(origin,v.clone().sub(origin).normalize());const h=caster.intersectObjects(r.stream.pickMeshes(caster.ray))[0];if(h&&r.stream.featureAt(h)?.uid===uid){pick=uid;break;}}if(pick)break;}if(pick)break;}}
 return {uid,fallbackPresent:!e&&ray.intersectObjects(r.stream.pickMeshes(ray.ray)).some(h=>r.stream.featureAt(h)?.uid===uid),active:!!e?.active,modelId:e?.record.modelId,visible:!!e?.group.visible,recordedBase:b.baseHeightHKPD??null,recordedTop:b.topHeightHKPD??null,ground:r.sampler.height(...b.centre),terrainHits,resolution:r.sampler.resolutionAt(...b.centre),contact,contactColliderUid,pick,stats:r.officialModels.stats,render:window.__city.state.render};},m.uid);}
function budget(s){for(const k of ['geometryBytes','residentBytes','triangles'])assert.ok(s[k]<=s.limits[k],k);assert.ok(s.cached<=s.limits.count);assert.deepEqual(s.errors,[]);}
async function time(p,value){await p.evaluate(value=>{const input=document.getElementById('time');input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));window.__detailReview.controlSheet.close({restoreFocus:false});},value);await p.waitForTimeout(150);}
const snap=(p,name)=>p.screenshot({path:new URL(name+'.png',out).pathname});
const measure=p=>p.evaluate(async()=>{const values=[];let last;for(let i=0;i<90;i++){const n=await new Promise(requestAnimationFrame);if(i>10)values.push(n-last);last=n;}values.sort((a,b)=>a-b);return {median:values[Math.floor(values.length*.5)],p95:values[Math.floor(values.length*.95)]};});
try{
 for(const g of groups){const area={area:g.area,models:[],views:[]};report.areas.push(area);({page}=await open(g.place));for(const m of g.selected){await focus(page,m);const q=await proof(page,m);if(after){assert.equal(q.active,true);assert.equal(q.modelId,m.modelId);assert.equal(q.recordedBase,m.recordedBaseHeight);assert.equal(q.recordedTop,m.recordedTopHeight);assert.ok(q.contact);assert.equal(q.pick,m.uid);budget(q.stats);assert.ok(Math.abs(q.terrainHits[0]-q.ground)<.03,'render/sampler agreement: '+JSON.stringify({uid:q.uid,ground:q.ground,terrainHits:q.terrainHits,resolution:q.resolution}));}area.models.push(q);console.log(phase,m.uid,'verified');const name=g.area+'-'+m.uid.replace(/\W/g,'-');await time(page,'15:00');await snap(page,name+'-day');area.views.push(name+'-day');}const last=g.selected.at(-1);await time(page,'22:00');await snap(page,g.area+'-night');area.performance=await measure(page);if(after){await page.evaluate(place=>window.__detailReview.goPlace(place,false),g.place);await page.waitForFunction(()=>!window.__city.state.loadingTravel&&!window.__city.state.travelling,null,{timeout:120000});await page.locator('[data-mode="walk"]').click();await page.waitForFunction(()=>window.__city.state.mode==='walk'&&window.__city.state.movementReady,null,{timeout:120000});area.walkArrival=await page.evaluate(()=>({position:window.__city.state.position,collision:window.__city.state.collision}));assert.equal(area.walkArrival.collision,false);await page.locator('#fly-toggle').click();await page.locator('[data-aircraft="prop"]').click();await page.waitForFunction(()=>window.__city.state.mode==='fly'&&window.__city.state.movementReady,null,{timeout:120000});const start=await page.evaluate(()=>window.__city.state.position);await page.waitForTimeout(1200);area.flight=await page.evaluate(()=>({position:window.__city.state.position,collision:window.__city.state.collision}));area.flight.distance=Math.hypot(area.flight.position[0]-start[0],area.flight.position[2]-start[2]);assert.ok(area.flight.distance>5);assert.equal(area.flight.collision,false);}await page.close();if(after){({page}=await open(g.place,390));await focus(page,g.selected[0]);await time(page,'22:00');area.mobile=await proof(page,g.selected[0]);assert.ok(area.mobile.active);budget(area.mobile.stats);assert.equal(area.mobile.stats.profile,'mobile');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await snap(page,g.area+'-mobile-night');area.mobilePerformance=await measure(page);await page.close();}}
 if(after){const g=groups[0],m=g.selected.find(m=>m.uid==='landsd/75329:0')||g.selected[0],failure=await open(g.place,1440,m);page=failure.page;await focus(page,m,true);assert.equal(await page.evaluate(uid=>!!window.__detailReview.stream.detailedModels.get(uid)?.active,m.uid),false);report.failedLoadFallback=await proof(page,m);assert.equal(report.failedLoadFallback.fallbackPresent,true);failure.recover();await page.locator('#stream-retry').click();await page.waitForFunction(uid=>window.__detailReview.stream.detailedModels.get(uid)?.active,m.uid,{timeout:120000});report.retry=await proof(page,m);assert.ok(report.retry.active);await page.close();}
 assert.deepEqual(report.errors,[]);report.result='passed';
}catch(e){report.result='failed';report.failure=e.stack;report.failureState=page&&!page.isClosed()?await page.evaluate(()=>({models:window.__detailReview?.officialModels?.stats,stream:window.__city?.state?.stream})).catch(()=>null):null;if(page&&!page.isClosed())await snap(page,'failure').catch(()=>{});throw e;}finally{report.finished=new Date().toISOString();await writeFile(new URL('verification.json',out),JSON.stringify(report,null,2)+'\n');await browser.close();}
console.log(JSON.stringify({result:report.result,areas:report.areas.map(a=>({area:a.area,models:a.models.length,performance:a.performance,mobilePerformance:a.mobilePerformance}))}));
