"""Reuse Central's exact attribute-preserving GLB packer for the Pui O matches."""
import gzip,hashlib,json
from run import HERE,ROOT,DOC,module
pack=module('shared_official_glb_packer',HERE.parent/'central-completion/pack_models.py').pack
sha=lambda raw:hashlib.sha256(raw).hexdigest()
def main():
 payload=json.loads(gzip.decompress((HERE/'model-geometries.json.gz').read_bytes()));buildings={b['uid']:b for b in json.loads(gzip.decompress((HERE/'building-selection.json.gz').read_bytes()))['buildings']}
 manifests={p.parent.name:json.loads(p.read_text()) for p in (HERE/'staged').glob('*/manifest.json')};out=HERE/'compact';(out/'models').mkdir(parents=True,exist_ok=True);records=[];evidence=[]
 for uid,baked in sorted(payload['byBuildingUid'].items()):
  b=buildings[uid];m=manifests[baked['sourceTile']];s=next(s for s in m['models'] if s['id']==baked['modelId']);folder=HERE/'staged'/m['tile'];path=folder/s['sourceEntry']
  for rel,digest in s['sourceHashes'].items():assert sha((folder/rel).read_bytes())==digest
  raw,stats=pack(path);compressed=gzip.compress(raw,mtime=0);dest=out/'models'/(s['id']+'.glb.gz');dest.write_bytes(compressed);assert stats['triangles']==baked['triangles']
  records.append({'uid':uid,'buildingCSUID':b['buildingCSUID'],'objectId':b['objectId'],'modelId':s['id'],'sourceTile':m['tile'],'sourceTileRevision':m['tileRevision'],'worldBounds':s['worldBounds'],'triangles':stats['triangles'],'recordedBaseHeight':b['baseHeightHKPD'],'recordedTopHeight':b['topHeightHKPD'],'structureType':b['structureType'],'label':b.get('name') or s['id'],'priority':'unreviewed','placementReviewed':False,'asset':str(dest.relative_to(out)),'encoding':'gzip','bytes':len(compressed),'glbBytes':len(raw),'decodedGeometryBytes':stats['decodedGeometryBytes'],'indexedVertices':stats['vertices'],'sha256':sha(compressed)})
  evidence.append({'uid':uid,'modelId':s['id'],'sourceEntry':str(path.relative_to(ROOT)),'sourceHashes':s['sourceHashes'],'sourceCacheSha256':m['sourceCacheSha256'],'sourceOriginalDownload':m['sourceDownload'],'sourceMatches':s['officialMatches'],'worldBounds':s['worldBounds'],'compressedSha256':sha(compressed),'glbSha256':sha(raw),**stats})
 counts={'catalogueModels':len(records),'packedModels':len(records),'compressedBytes':sum(r['bytes'] for r in records),'glbBytes':sum(r['glbBytes'] for r in records),'decodedGeometryBytes':sum(r['decodedGeometryBytes'] for r in records),'packedTriangles':sum(r['triangles'] for r in records)}
 catalogue={'schemaVersion':1,'kind':'staged-official-model-catalogue','area':'Pui O','datasetId':'landsd_rcd_1742809441342_98380','crs':'EPSG:2326','verticalDatum':'Hong Kong Principal Datum','rootTranslation':[-834500,0,816500],'coordinatePolicy':'Original native glTF nodes and float attributes. Only identical complete vertex tuples are indexed by the existing shared packer; apply city root translation once. No source height edits.','loadingPolicy':'Staged only; retain the current source footprint until its verified individual model has loaded successfully. Shared loader LOD/budget decides which nearby assets to load.','counts':counts,'models':records}
 raw=(json.dumps(catalogue,ensure_ascii=False,separators=(',',':'))+'\n').encode();assert len(raw)<=1024*1024; (out/'catalogue.json').write_bytes(raw)
 report={'counts':counts,'catalogueBytes':len(raw),'catalogueSha256':sha(raw),'sharedPacker':'source-scripts/city/central-completion/pack_models.py:pack','assets':evidence,'limits':['All expanded source attributes are verified bit-for-bit by the shared packer.','This packages already matched models only, does not repeat source acquisition or identity matching.','Four unmatched source models remain excluded; original source archives remain intact.','Per-model requests require the shared loader budget/LOD; 681 tiny assets must not be fetched eagerly merely because one city tile is resident.','Full architecture/browser placement review remains pending; placementReviewed stays false.']}
 (DOC/'compact-assets.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items() if k!='assets'},indent=2))
if __name__=='__main__':main()
