"""Reconcile exact existing Lantau assets and current review evidence; no publication."""
import json,pathlib,hashlib
ROOT=pathlib.Path(__file__).resolve().parents[3];HERE=pathlib.Path(__file__).resolve().parent;D=ROOT/'docs/astra-city/landmark-completion-audit'
read=lambda p:json.loads(p.read_bytes());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,v):p.write_text(json.dumps(v,indent=2)+'\n')
def main():
 batch=read(D/'lantau13-batch.json');uids={p['uid'] for p in batch['parts']};views=[];reports=[]
 for folder in ['lantau12-browser','lantau12-closeups-terrain-aware','lantau13-podium-browser']:
  f=D/folder/'report.json';r=read(f);assert not r['errors'];reports.append({'path':str(f.relative_to(ROOT)),'sha256':sha(f),'runtimeHashes':r['runtimeHashes']})
  for v in r['views']:
   assert sha(f.parent/v['file'])==v['sha256'];assert not v['cameraCollision'] and not v['uiOverflow'] and v['boxInsideView'];assert v['activeUIDs']==v['uids'];assert all(p['uid']==p['hitUid'] for p in v['picking']);assert all(p['hits'] and any(abs(h-p['sampler'])<.003 for h in p['hits']) for p in v['terrainProbes']);views.append({**v,'folder':folder})
 assert len(views)==40
 for uid in uids:assert {(v['mobile'],v['time']) for v in views if uid in v['uids']}=={(False,15),(False,22),(True,15),(True,22)}
 accepted={'issue':'HKS-214','sourceReports':reports,'views':views,'acceptedViewCount':40,'uniqueNativeParts':13,'normalScene':True,'dataInterception':False,'sourceGeometryChanged':False,'qualification':'Browser checks establish actual loading, picking and framing; manual inspection separately holds239278. Earlier close-ups omitted terrain from camera scoring and are superseded by terrain-aware captures.'};save(D/'lantau13-browser-accepted.json',accepted)
 models={m['uid']:m for m in read(HERE/'lantau13-catalogue.json')['models']};proofs={}
 manifests=[* (ROOT/'source-scripts/city/landmark-pass/staged-existing').glob('*/manifest.json'),*(ROOT/'source-scripts/city/landmark-pass/staged').glob('*/manifest.json'),*(ROOT/'source-scripts/city/tai-o-detail-completion/staged').glob('*/manifest.json')]
 for f in manifests:
  m=read(f)
  for spec in m.get('models',[]):
   for uid,entry in models.items():
    if spec['id']!=entry['modelId'] or uid in proofs:continue
    match=next(x for x in spec['officialMatches'] if x['objectId']==int(uid.split('/')[1].split(':')[0]));assert match['buildingCSUID']==entry['buildingCSUID'];verified=[]
    for path,h in spec['sourceHashes'].items():
     assert sha(f.parent/path)==h;verified.append({'path':str((f.parent/path).relative_to(ROOT)),'sha256':h})
    proofs[uid]={'sourceManifest':str(f.relative_to(ROOT)),'manifestSHA256':sha(f),'modelId':spec['id'],'exactMatch':match,'sourceFiles':verified,'sourceGeometryBounds':spec['worldBounds']}
 assert set(proofs)==uids
 save(D/'lantau13-identity-proofs.json',{'issue':'HKS-214','parts':proofs,'policy':'Exact source model ID/GeoRef/CSUID/OBJECTID and cached native source byte hashes; tourist membership and full architectural embellishment are separate claims.'})
 support={r['uid']:r for r in read(D/'lantau13-support.json')['rows']};surface={r['uid']:r['stats']['patched'] for r in read(D/'lantau13-surfaces.json')['rows']};native={r['uid']:r for r in read(D/'lantau13-native-burial.json')['rows']}
 notes={
 'landsd/67478:0':'Main hotel native form, verandahs, roofs and turrets retained;124/124 low-rim points contact current ground within2m; no wholly buried source face. Earlier terrain-edge repair remains active.',
 'landsd/170271:0':'Thin native ancillary terrace/connector form is retained in its source assembly.12/15 rim points within2m of ground, three edge points up to2.736m above ground. No wholly buried faces; do not lower the elevated edge to force flat-ground contact.',
 'landsd/170357:0':'Native intermediate hotel block is visibly joined to the main assembly.15 below-grade faces (10.409m²,2.326%) are reproduced in original native TIN, including two small upward faces at17.331–20.172m HKPD. Keep source lower-step/foundation geometry; this does not certify every heritage stair or ground detail.',
 'landsd/211618:0':'Native hotel wing retains its roofs, turrets and visible facade. Two buried side/foundation faces total19.687m² (1.766%), both reproduced in original TIN; no upward face wholly buried. Preserve source geometry and hillside placement.',
 'landsd/239278:0':'HELD: waterfront outbuilding visibly intersects the hillside across its wall and roof edge in close-up. Four wholly buried faces total27.508m² (8.206%); original native TIN reproduces all four, and prior source audit also found native terrain above the highest roof over a small region. This is a source terrain/building conflict, not download truncation or a vertical multiplier. Requires a source-supported retaining-edge/ground correction or newer terrain; no arbitrary height shift.',
 'landsd/238276:0':'Hall of Great Hero native tiered roof/source form is visible. All14 low-rim vertices contact installed native podium238483 within0.5m, corroborating earlier348 interior native rays within0.167m. Add native podium retention metadata before final installed verification.',
 'landsd/238483:0':'Native Po Lin multi-level podium supports Hall of Great Hero and Grand Hall.22/24 low-rim vertices within2m terrain; remainingtwo below-grade. One buried retaining/foundation face88.714m² (2.087%) is reproduced in original TIN; no upward face buried. Keep platform levels, supporting source geometry and true terrain.',
 'landsd/169498:0':'Ngong Ping native roof/building form remains visible. One tiny buried side/foundation triangle0.0992m² (0.01347%) is also below original TIN. All18 low-rim points within0.621m of current ground.'}
 evidence=[D/'lantau13-support.json',D/'lantau13-surfaces.json',D/'lantau13-native-burial.json',D/'lantau13-browser-accepted.json',D/'lantau13-identity-proofs.json'];hashes={str(p.relative_to(ROOT)):sha(p) for p in evidence};live={}
 for url in read(ROOT/'3d-viewer/city/data/manifest.json')['officialModelCatalogues']:
  f=ROOT/'3d-viewer'/url
  for m in read(f)['models']:
   if m['uid'] in uids:live[m['uid']]=(f,url,m)
 rows=[]
 for p in batch['parts']:
  uid=p['uid'];f,url,m=live[uid];assert m['sha256']==p['asset']['sha256']==sha(ROOT/p['asset']['path'])==support[uid]['sha256'];state='held' if uid=='landsd/239278:0' else 'approved-for-integration' if uid=='landsd/238276:0' else 'installed-verified';rows.append({'uid':uid,'name':p['name'],'status':state,'sourceSHA256':m['sha256'],'modelId':m['modelId'],'observation':notes.get(uid,'Exact government native roof/building form and source identity checked; no wholly buried source face, complete low-rim contact, actual day/night desktop/mobile loading and picking. Retain source geometry.'),'wholeLandmarkComplete':False,'surface':{k:v for k,v in surface[uid].items() if k!='buriedTriangleEvidence'},'evidenceHashes':hashes})
 decision={'issue':'HKS-214','reviewSnapshot':'11a25ce297101f9e','existingNativeParts':13,'newModelsAdded':0,'installedVerified':11,'needsSupportMetadata':1,'heldSourceTerrainConflict':1,'verticalScale':1,'sourceGeometryChanged':False,'rows':rows,'sourceReferences':[{'url':'https://www.taioheritagehotel.com/en/about-us/architecture/','basis':'Owner describes two-storey main block/outhouse, later extension, verandahs, tiled roof and connecting bridge.'},{'url':'https://www.aab.gov.hk/filemanager/aab/common/historicbuilding/en/440_Appraisal_En.pdf','basis':'Government appraisal confirms linked historic blocks, projecting eaves and arched verandahs.'},{'url':'https://www.np360.com.hk/en/things-to-do','basis':'Operator describes Chinese architectural village and landscape design.'}],'limits':['Native government forms retain simplified source architecture; window placement/material colours are procedural, not surveyed textures or heritage ornament reconstruction.','Whole Tai O/Po Lin/Ngong Ping completion is not asserted.','Tai O239278 stays a tracked source conflict even though its existing model remains in the viewer.','Grand Hall238482 also needs its existing podium dependency reconciled in the next review.','Desktop and emulated mobile screenshots do not certify Safari or sustained real-device performance.']};save(D/'lantau13-decisions.json',decision)
 f,url,m=live['landsd/238276:0'];podium=live['landsd/238483:0'][2];contact=D/'lantau13-support.json';assert support[m['uid']]['rimCounts']['otherTriangleContact']==14 and all(any(c['uid']==podium['uid'] and c['distance']<=.5 for c in r['contacts']) for r in support[m['uid']]['rim']);sidecar={'issue':'HKS-214','version':1,'published':False,'scope':'Add exact native podium retention for Hall of Great Hero; all other source fields/assets unchanged.','catalogues':[{'url':url,'source':str(f.relative_to(ROOT)),'oldSHA256':sha(f),'models':[m['uid']]}],'changes':[{'uid':m['uid'],'modelSHA256':m['sha256'],'modelId':m['modelId'],'buildingCSUID':m['buildingCSUID'],'catalogue':str(f.relative_to(ROOT)),'oldSupportDependencies':m.get('supportDependencies',[]),'supportDependencies':[{'uid':podium['uid'],'state':'installed','csuid':podium['buildingCSUID']}],'contactEvidenceSHA256':sha(contact)}],'contactReport':str(contact.relative_to(ROOT)),'contactReportSHA256':sha(contact),'requiresNewNativeUids':[],'requiredExistingNativeUids':[podium['uid']],'requiresVisualApproval':True,'visualApproval':{'status':'approved-for-integration','evidence':str((D/'lantau13-decisions.json').relative_to(ROOT)),'evidenceSHA256':sha(D/'lantau13-decisions.json'),'scope':'All14 native hall rim vertices touch the independently reviewed native podium; actual normal scene day/night desktop/mobile views inspected.'}};save(HERE/'dependency-replacements-polin.json',sidecar);print(json.dumps({'existingReviewed':13,'installedVerified':11,'needsDependency':1,'held':1,'newAssets':0}))
if __name__=='__main__':main()
