"""Validate current evidence and prepare existing-model decisions/IFC metadata only."""
import pathlib,json,hashlib
ROOT=pathlib.Path(__file__).resolve().parents[3];HERE=pathlib.Path(__file__).resolve().parent;D=ROOT/'docs/astra-city/landmark-completion-audit';B=D/'first12-browser'
read=lambda p:json.loads(p.read_bytes());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,v):p.write_text(json.dumps(v,indent=2)+'\n')
def main():
 batch=read(D/'existing-review-batch.json');uids={p['uid'] for p in batch['parts']};views={};reports=[]
 for f in ['report.json','center-and-ck.json','mobile-completion.json','center-final.json']:
  r=read(B/f);assert not r['errors'];reports.append({'path':str((B/f).relative_to(ROOT)),'sha256':sha(B/f),'runtimeHashes':r['runtimeHashes']})
  for v in r['views']:views[v['file']]=v
 assert len(views)==40
 for v in views.values():
  assert sha(B/v['file'])==v['sha256'];assert not v['cameraCollision'] and not v['uiOverflow'] and v['boxInsideView'];assert v['activeUIDs']==v['uids'];assert all(p['uid']==p['hitUid'] for p in v['picking']);assert all(p['hits'] and any(abs(h-p['sampler'])<.003 for h in p['hits']) for p in v['terrainProbes'])
  if v['id'].startswith('the-center-annex'):assert v['visibilitySearch']['visible']/v['visibilitySearch']['samples']>=.9
 for uid in uids:assert {(v['mobile'],v['time']) for v in views.values() if uid in v['uids']}=={(False,15),(False,22),(True,15),(True,22)}
 summary={'issue':'HKS-214','sourceReports':reports,'views':list(views.values()),'acceptedViewCount':40,'uniqueNativeParts':12,'normalScene':True,'dataInterception':False,'sourceGeometryChanged':False,'cameraRetryNotes':['A tower-wide Center frame legitimately culled tiny components at distance; they were reviewed individually close up.','Initial close-ups were obstructed by surrounding buildings; these were superseded by source-triangle visibility searches.','Manual camera placement disables OrbitControls damping and waits for loaded models before final visibility search.'],'limits':['Desktop and emulated mobile, not real-device thermal or Safari validation.','Native model acceptance does not approve surrounding OSM façade overlays or imply whole-landmark closure.']};save(B/'accepted.json',summary)
 support={r['uid']:r for r in read(D/'first12-support.json')['rows']};surface={r['uid']:r['stats']['patched'] for r in read(D/'first12-surfaces.json')['rows']};ifc=read(D/'first12-ifc-support.json');assert ifc['samples']==90 and ifc['directContacts']==73 and ifc['remainingAllConnected']
 notes={
 'landsd/161250:0':'Native tower sits at34.666992m HKPD on podium top34.666999m.73 low-rim vertices directly contact podium triangles;17 remaining vertices are connected in the unchanged source mesh to those contacts, with perimeter overhang distances up to2.676m. Install native podium retention metadata before recording final runtime verification.',
 'landsd/232441:0':'Native IFC1 podium is grounded:109/109 low-rim samples within0.12m of rendered terrain; no wholly buried source face. Required native support for tower161250.',
 'landsd/244915:0':'IFC2 full tower/crown source retained. Eight tiny wholly buried faces total0.3233m² (0.000326% of source area); no upward face is buried. Native TIN does not wholly bury those faces. Preserve native source rather than shift the entire tower for small foundation intersections.',
 'landsd/257115:0':'IFC2 podium/complex is present. Five wholly buried faces total41.784m² (0.059442%); original native TIN still buries four faces totalling23.474m². Preserve below-grade source geometry; no arbitrary flattening. Local ground/plaza refinement remains distinct from native component acceptance.',
 'landsd/89275:0':'HSBC structure, suspension trusses and open ground-level supports are visible.3283 buried tiny triangles total24.021m² (0.021236% of source area). Native TIN reduces covered hidden area to4.942m² but lacks1206 sampled vertices, which remain explicitly unextrapolated. Retain exact source geometry; this is not sign-off of every plaza step or basement edge.',
 'landsd/67579:0':'The Center native tower/crown is visible.590 below-grade faces total31.460m² (0.039722%), all at3.348–3.986m HKPD; original native TIN buries the same faces. Preserve source foundation geometry and true ground. Eight separate OSM glass parts remain outside whole-landmark overlap sign-off.',
 'landsd/96281:0':'Native Center annex fully framed and visible in42/45 sampled surface rays on desktop/mobile; no wholly buried face.20/23 low-rim vertices contact terrain within2m, two contact native main-building surfaces, and the remaining gap is2.099m at the edge. Preserve native peripheral geometry.',
 'landsd/96918:0':'Native small Center annex is visible in25/25 sampled source rays, with9/9 low-rim samples within0.49m of terrain and no wholly buried face.',
 'landsd/98921:0':'Geometry and placement checks pass, but inspected mobile22:00 view shows a speckled facade patch. Hold visual approval until material projection versus overlapping geometry is diagnosed; do not call the visible artefact resolved.'}
 live={}
 manifest=read(ROOT/'3d-viewer/city/data/manifest.json')
 for url in manifest['officialModelCatalogues']:
  p=ROOT/'3d-viewer'/url
  for m in read(p)['models']:
   if m['uid'] in uids:live[m['uid']]=(p,url,m)
 assert set(live)==uids
 evidence=[D/'first12-support.json',D/'first12-surfaces.json',D/'first12-native-burial.json',D/'first12-ifc-support.json',B/'accepted.json'];hashes={str(p.relative_to(ROOT)):sha(p) for p in evidence};rows=[]
 for p in batch['parts']:
  uid=p['uid'];catalogue,url,m=live[uid];assert m['sha256']==p['asset']['sha256']==sha(ROOT/p['asset']['path']);status='held' if uid=='landsd/98921:0' else 'approved-for-integration' if uid=='landsd/161250:0' else 'installed-verified';rows.append({'uid':uid,'name':p['name'],'sourceSHA256':m['sha256'],'modelId':m['modelId'],'catalogue':str(catalogue.relative_to(ROOT)),'status':status,'observation':notes.get(uid,'Native form, full source height, crown/roof, terrain contact, picking and day/night desktop/mobile presence checked. No wholly buried source triangle; keep unchanged government geometry.'),'wholeLandmarkComplete':False,'surface':{k:v for k,v in surface[uid].items() if k!='buriedTriangleEvidence'},'evidenceHashes':hashes})
 decision={'issue':'HKS-214','reviewSnapshot':'11a25ce297101f9e','existingNativeParts':12,'newModelsAdded':0,'verticalScale':1,'sourceGeometryChanged':False,'reviewedExisting':10,'needsSupportMetadata':1,'heldVisualArtefact':1,'rows':rows,'sourceReferences':[{'url':'https://pcparch.com/work/ifc-hong-kong','basis':'Architect describes two towers and podium, with tapered sculptural IFC2 crown.'},{'url':'https://ifc.com.hk/en/office/one-two-ifc/','basis':'Official owner confirms One/Two IFC identities.'},{'url':'https://www.about.hsbc.com.hk/news-and-media/the-fourth-generation-hsbc-main-building-marks-40th-anniversary','basis':'HSBC describes the deliberately elevated base and open ground-level plaza.'}],'limits':['Existing source geometry is accepted as native building form, not photorealistic materials or interior reconstruction.','Below-grade source faces are not automatically faults; reviewed buried areas and source-TIN coverage gaps remain explicit.','Whole-landmark assembly closure and surrounding city refinements remain separate.']};save(D/'first12-decisions.json',decision)
 cat,url,m=live['landsd/161250:0'];podium=live['landsd/232441:0'][2];contact=D/'first12-ifc-support.json';sidecar={'issue':'HKS-214','version':1,'published':False,'scope':'Only add the measured native IFC1 podium dependency; every other model field and all source asset bytes remain unchanged.','catalogues':[{'url':url,'source':str(cat.relative_to(ROOT)),'oldSHA256':sha(cat),'models':[m['uid']]}],'changes':[{'uid':m['uid'],'modelSHA256':m['sha256'],'modelId':m['modelId'],'buildingCSUID':m['buildingCSUID'],'catalogue':str(cat.relative_to(ROOT)),'oldSupportDependencies':m.get('supportDependencies',[]),'supportDependencies':[{'uid':podium['uid'],'state':'installed','csuid':podium['buildingCSUID']}],'contactEvidenceSHA256':sha(contact)}],'contactReport':str(contact.relative_to(ROOT)),'contactReportSHA256':sha(contact),'requiresNewNativeUids':[],'requiredExistingNativeUids':[podium['uid']],'requiresVisualApproval':True,'visualApproval':{'status':'approved-for-integration','evidence':str((D/'first12-decisions.json').relative_to(ROOT)),'evidenceSHA256':sha(D/'first12-decisions.json'),'scope':'Native tower/podium assembled in inspected day/night desktop/mobile views;73 exact rim contacts and17 connected perimeter overhang vertices. Geometry unchanged; no assertion that every rim point is within0.5m.'}};save(HERE/'dependency-replacements-ifc1.json',sidecar);print(json.dumps({'reviewedExisting':10,'metadataPending':1,'held':1,'views':40,'sidecar':str((HERE/'dependency-replacements-ifc1.json').relative_to(ROOT))}))
if __name__=='__main__':main()
