/** Source-accounted vertical triangle support evidence. No publication or geometry edits. */
import assert from 'node:assert/strict';
import {levels,nearest} from '../assembly-support-review/triangles.mjs';
import {readFileSync,writeFileSync} from 'node:fs';
import {resolve,dirname,relative} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../../..');
const hashes={},read=p=>{const raw=readFileSync(resolve(root,p));hashes[p]=createHash('sha256').update(raw).digest('hex');return JSON.parse(raw);};
const report=read('docs/astra-city/landmark-preflight/report.json');
const batch=read(process.env.EXISTING_BATCH||'docs/astra-city/landmark-completion-audit/existing-review-batch.json'),selected=batch.parts.map(p=>({...report.parts.find(r=>r.uid===p.uid),candidate:{...p.asset,worldBounds:null},identityProposalGroups:[],knownHold:null,sourceState:'existing-native-review'}));
const [THREE,{prepareModelCatalogue,loadOfficialModel,disposeOfficialModel},{makeTerrainSampler},{extrudeBuilding}]=await Promise.all(['3d-viewer/vendor/three.module.js','3d-viewer/city/official-model-assets.js','3d-viewer/city/geo.js','3d-viewer/city/world.js'].map(p=>import(pathToFileURL(resolve(root,p)))));
const manifest=read('3d-viewer/city/data/manifest.json'),terrain=read('3d-viewer/city/data/terrain.json');
terrain.patches=manifest.terrainPatches.map(p=>read('3d-viewer/'+p.url));const terrainBundleArg=process.argv.indexOf('--terrain-bundle');
if(terrainBundleArg>=0){const bundle=read(process.argv[terrainBundleArg+1]),safe=new Set(bundle.checks.filter(c=>c.eligibleForBrowserValidation).map(c=>c.patch));for(const parent of bundle.bundles){const parentPath='3d-viewer/'+parent.parentTerrainURL;assert.equal(hashes[parentPath],parent.parentSha256,'Terrain parent changed');for(const child of parent.patches){if(!safe.has(child.path))continue;const patch=read(child.path);if(parent.parentTerrainURL==='city/data/terrain.json')terrain.patches.push(patch);else{const idx=manifest.terrainPatches.findIndex(p=>p.url===parent.parentTerrainURL);assert(idx>=0);(terrain.patches[idx].patches||=[]).push(patch);}}}}
const sampler=makeTerrainSampler(terrain);
const entries=new Map();
for(const url of manifest.officialModelCatalogues){const path='3d-viewer/'+url,cat=read(path);for(const e of prepareModelCatalogue(cat,'http://review.local/'+url))entries.set(e.uid,{...e,path:resolve(root,dirname(path),e.asset),state:'installed'});}
const candidatePath='source-scripts/city/landmark-preflight/snapshots/'+report.snapshotId+'/catalogue.json';
for(const e of prepareModelCatalogue(read(candidatePath),'http://review.local/candidates/catalogue.json'))entries.set(e.uid,{...e,path:resolve(root,dirname(candidatePath),'assets',e.asset),state:'candidate'});
for(const p of selected){const e=entries.get(p.uid);assert(e,'Existing native asset missing');p.candidate={...e};}
const overlap=(a,b,pad=1)=>a[0][0]-pad<=b[1][0]&&b[0][0]-pad<=a[1][0]&&a[0][2]-pad<=b[1][2]&&b[0][2]-pad<=a[1][2];
const contexts=[...entries.values()].filter(e=>selected.some(p=>overlap(p.candidate.worldBounds,e.worldBounds,2)));
const needs=new Set(contexts.map(e=>e.uid)),buildings=new Map(),fallback=[];
for(const tile of manifest.tiles)for(const b of read('3d-viewer/'+tile.url).buildings){
 if(needs.has(b.uid))buildings.set(b.uid,b);
 if(entries.get(b.uid)?.state==='installed'||b.modelGeometry||b.heightSource!=='landsd'||b.baseSource!=='landsd'||!Number.isFinite(b.baseHeightHKPD)||!Number.isFinite(b.topHeightHKPD)||Math.abs(b.base-b.baseHeightHKPD)>.001||Math.abs(b.base+b.height-b.topHeightHKPD)>.001)continue;
 const xs=b.rings[0].map(v=>v[0]),zs=b.rings[0].map(v=>v[1]),bounds=[[Math.min(...xs),b.base,Math.min(...zs)],[Math.max(...xs),b.base+b.height,Math.max(...zs)]];
 if(selected.some(p=>overlap(p.candidate.worldBounds,bounds,1)))fallback.push({b,bounds});
}
const lighting={night:{value:1},activity:{value:new THREE.Vector4(1,1,1,1)},retail:{value:1},elapsed:{value:0},shimmer:{value:0}};
const geometry=new Map(),failures=[];let started=performance.now();
for(const e of contexts){try{const raw=readFileSync(e.path);hashes[relative(root,e.path)]=createHash('sha256').update(raw).digest('hex');const model=await loadOfficialModel(e,buildings.get(e.uid),lighting,{fetcher:async()=>new Response(raw)});const {position,index}=model.record.modelGeometry;const triangles=[],faces=[],rimMap=new Map();for(let j=0;j<position.length;j+=3)if(position[j+1]<=e.worldBounds[0][1]+.35){const v=[position[j],position[j+1],position[j+2]];rimMap.set(v.map(n=>n.toFixed(3)).join(','),v);}for(let i=0;i<index.length;i+=3){const a=index[i]*3,b=index[i+1]*3,c=index[i+2]*3;const ax=position[a],az=position[a+2],bx=position[b],bz=position[b+2],cx=position[c],cz=position[c+2];faces.push(new THREE.Triangle(new THREE.Vector3(ax,position[a+1],az),new THREE.Vector3(bx,position[b+1],bz),new THREE.Vector3(cx,position[c+1],cz)));const det=(bx-ax)*(cz-az)-(bz-az)*(cx-ax);if(Math.abs(det)<1e-9)continue;triangles.push({ax,az,bx,bz,cx,cz,ay:position[a+1],by:position[b+1],cy:position[c+1],det,minX:Math.min(ax,bx,cx),maxX:Math.max(ax,bx,cx),minZ:Math.min(az,bz,cz),maxZ:Math.max(az,bz,cz)});}geometry.set(e.uid,{e,triangles,faces,rim:[...rimMap.values()]});disposeOfficialModel(model);}catch(error){failures.push({uid:e.uid,error:error.message});}}
// Reuse the actual runtime extrusion (including holes) for surveyed fallback podium roof triangles.
for(const {b,bounds} of fallback){const geo=extrudeBuilding(b),position=geo.attributes.position.array,index=geo.index?.array||Array.from({length:position.length/3},(_,i)=>i),faces=[];
 for(let i=0;i<index.length;i+=3){const pts=[index[i],index[i+1],index[i+2]].map(v=>new THREE.Vector3().fromArray(position,v*3));const face=new THREE.Triangle(...pts),normal=face.getNormal(new THREE.Vector3());if(normal.y>.99&&Math.max(...pts.map(v=>v.y))-Math.min(...pts.map(v=>v.y))<.001)faces.push(face);}
 geo.dispose();geometry.set(b.uid+':fallback',{e:{uid:b.uid,state:'surveyed-footprint-fallback',buildingCSUID:b.buildingCSUID,worldBounds:bounds},faces,triangles:[],rim:[]});}
// Only near-coincident actual source surfaces count as contacts. Bounding boxes cull candidates, never prove support.
function chain(uid,x,z,bottom,ground,near,visited=new Set(),depth=0){if(bottom-ground<=2&&bottom-ground>=-2)return {kind:'terrain-contact',chain:[],gap:bottom-ground};if(bottom<ground-2)return {kind:'below-terrain-context',chain:[],gap:bottom-ground};if(depth>=6)return null;visited=new Set([...visited,uid]);for(const g of near){if(visited.has(g.e.uid))continue;const ys=levels(g,x,z);if(!ys.length)continue;const touching=ys.filter(y=>Math.abs(y-bottom)<=.5);if(!touching.length)continue;const base=ys[0];if(base>bottom-.1)continue;const support=chain(g.e.uid,x,z,base,ground,near,visited,depth+1);if(support)return {...support,chain:[{uid:g.e.uid,state:g.e.state,surface:touching[0],base},...support.chain]};}return null;}
const rows=[];
for(const p of selected){const g=geometry.get(p.uid);if(!g){rows.push({uid:p.uid,outcome:'loader-exception',publicationApproved:false});continue;}const [a,b]=g.e.worldBounds;const near=[...geometry.values()].filter(o=>overlap(g.e.worldBounds,o.e.worldBounds));const nx=Math.max(2,Math.min(24,Math.ceil((b[0]-a[0])/2))),nz=Math.max(2,Math.min(24,Math.ceil((b[2]-a[2])/2)));const samples=[];
for(let ix=0;ix<nx;ix++)for(let iz=0;iz<nz;iz++){const x=a[0]+(b[0]-a[0])*(ix+.5)/nx,z=a[2]+(b[2]-a[2])*(iz+.5)/nz,ys=levels(g,x,z);if(!ys.length)continue;const ground=sampler.height(x,z),bottom=ys[0],top=ys.at(-1),support=chain(p.uid,x,z,bottom,ground,near);samples.push({x,z,bottom,top,ground,clearance:bottom-ground,roofAboveTerrain:top-ground,support});}
const count=k=>samples.filter(k).length,n=samples.length,terrainContact=count(s=>s.support?.kind==='terrain-contact'&&!s.support.chain.length),foundation=count(s=>s.support?.kind==='below-terrain-context'&&!s.support.chain.length),supported=count(s=>s.support?.chain.length),unresolved=count(s=>!s.support),hidden=count(s=>s.roofAboveTerrain<-.25);const counts={samples:n,terrainContact,foundation,supported,unresolved,hidden};const dependencies=[...new Set(samples.flatMap(s=>s.support?.chain.map(r=>r.uid)||[]))].sort();
let outcome=!n?'no-projected-triangle-samples':hidden?'terrain-occludes-source-surfaces':unresolved===0&&foundation===0?(supported?'triangle-supported-component':'triangle-terrain-contact'):unresolved===0?'foundation-context-review':supported||terrainContact?'partial-contact-overhang-review':'no-contact-found-review';
const rim=g.rim.map(v=>{const ground=sampler.height(v[0],v[2]),gap=v[1]-ground,contacts=[];if(gap>2)for(const other of near){if(other.e.uid===p.uid||other.e.buildingCSUID===g.e.buildingCSUID)continue;const distance=nearest(other,new THREE.Vector3(...v));if(distance<=.5)contacts.push({uid:other.e.uid,state:other.e.state,csuid:other.e.buildingCSUID,distance});}return{position:v,ground,gap,contacts};});
const rimCounts={samples:rim.length,terrainContact:rim.filter(r=>Math.abs(r.gap)<=2).length,belowTerrain:rim.filter(r=>r.gap< -2).length,otherTriangleContact:rim.filter(r=>r.contacts.length).length,noContact:rim.filter(r=>r.gap>2&&!r.contacts.length).length};
const rimOutcome=!rim.length?'no-low-rim':rimCounts.noContact===0?(rimCounts.otherTriangleContact?'native-low-rim-triangle-contact':rimCounts.belowTerrain?'native-low-rim-foundation-context':'native-low-rim-terrain-contact'):rimCounts.noContact<rim.length?'partial-native-low-rim-contact':'native-low-rim-no-contact-found';
const held=p.knownHold||p.identityProposalGroups.length>0;rows.push({uid:p.uid,name:p.name,landmarkIds:p.landmarkIds,modelId:g.e.modelId,sha256:g.e.sha256,state:p.sourceState,identityProposalGroups:p.identityProposalGroups,knownHold:p.knownHold,counts,outcome,rimOutcome,rimCounts,rim,dependencies,contactOnlyCandidate:!held&&!hidden&&rimCounts.noContact===0&&rimCounts.belowTerrain===0&&rim.length>=3,publicationApproved:false,architectureAccepted:false,samples});}
const counts={},rimCounts={};for(const r of rows){counts[r.outcome]=(counts[r.outcome]||0)+1;rimCounts[r.rimOutcome]=(rimCounts[r.rimOutcome]||0)+1;}const result={issue:'HKS-214',snapshotId:batch.reviewSnapshot||report.snapshotId,method:'Actual indexed runtime-loaded native source triangles. Deterministic up-to-24x24 interior vertical rays; triangle-surface contact tolerance 0.5m, terrain contact band +/-2m. Recursive same-ray source support to terrain up to six components. Additional exact 3D nearest-triangle distance from all unique native vertices within 0.35m of native minimum Y; <=0.5m component seam tolerance. No bounding-box acceptance.',selected:rows.length,contextModels:geometry.size,fallbackPodiumContexts:fallback.length,loadFailures:failures,counts,rimCounts,contactOnlyCandidate:rows.filter(r=>r.contactOnlyCandidate).map(r=>r.uid),rows,hashes,seconds:(performance.now()-started)/1000,limits:['Open-bottom meshes make interior ray minima roof levels, not foundations. Use low-rim results separately.','Low-rim contacts do not establish connectivity of every separate ornament or triangle in a model.','Finite samples establish observed contact, not exhaustive structural stability or whole-mesh support.','Open-sided/vertical components can lack projected surface samples.','Foundation and terrain intersection require source/visual judgement.','Proposed memberships and existing holds are never approved automatically.','Supporting candidate components must be integrated together or remain held.','Surveyed fallback roof contacts reuse exact runtime extrusions with holes, require original LandsD base/top values, exclude estimated heights and self/same-CSUID contacts.','No architectural acceptance, source edits, terrain offsets, runtime writes or publication.']};writeFileSync(resolve(root,process.argv.includes('--output')?process.argv[process.argv.indexOf('--output')+1]:'docs/astra-city/landmark-completion-audit/first12-support.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,rows:undefined,hashes:undefined}));
