import * as THREE from '../../../3d-viewer/vendor/three.module.js';
import {prepareModelCatalogue,loadOfficialModel,disposeOfficialModel} from '../../../3d-viewer/city/official-model-assets.js';
import {nearest} from '../assembly-support-review/triangles.mjs';
import {readFileSync,writeFileSync} from 'node:fs';
const root=new URL('../../../',import.meta.url),read=p=>JSON.parse(readFileSync(new URL(p,root))),cat=read('source-scripts/city/landmark-completion-audit/first12-catalogue.json'),batch=read('docs/astra-city/landmark-completion-audit/existing-review-batch.json'),support=read('docs/astra-city/landmark-completion-audit/first12-support.json'),ids=['landsd/161250:0','landsd/232441:0'],buildings=new Map();
for(const t of read('3d-viewer/city/data/manifest.json').tiles)for(const b of read('3d-viewer/'+t.url).buildings)if(ids.includes(b.uid))buildings.set(b.uid,b);
const lighting={night:{value:0},activity:{value:new THREE.Vector4(1,1,1,1)},retail:{value:1},elapsed:{value:0},shimmer:{value:0}},models=new Map();for(const e of prepareModelCatalogue(cat,'http://review.local/catalogue.json'))if(ids.includes(e.uid)){const p=batch.parts.find(p=>p.uid===e.uid),raw=readFileSync(new URL(p.asset.path,root));models.set(e.uid,await loadOfficialModel(e,buildings.get(e.uid),lighting,{fetcher:async()=>new Response(raw)}));}
const podium=models.get(ids[1]).record.modelGeometry,faces=[];for(let i=0;i<podium.index.length;i+=3)faces.push(new THREE.Triangle(...[0,1,2].map(j=>new THREE.Vector3().fromArray(podium.position,podium.index[i+j]*3))));
const tower=models.get(ids[0]).record.modelGeometry,parent=new Map(),key=v=>Array.from(v,n=>n.toFixed(4)).join(','),keys=[];function find(k){if(!parent.has(k))parent.set(k,k);let a=k;while(parent.get(a)!==a)a=parent.get(a);while(parent.get(k)!==k){const next=parent.get(k);parent.set(k,a);k=next;}return a;}function join(a,b){parent.set(find(a),find(b));}
for(let i=0;i<tower.position.length;i+=3)keys.push(key(tower.position.slice(i,i+3)));for(let i=0;i<tower.index.length;i+=3){const q=Array.from(tower.index.slice(i,i+3),j=>keys[j]);join(q[0],q[1]);join(q[1],q[2]);}
const rim=support.rows.find(r=>r.uid===ids[0]).rim,rows=rim.map(r=>({position:r.position,component:find(key(r.position)),nearestPodiumTriangle:nearest({faces},new THREE.Vector3(...r.position))}));const connected=new Set(rows.filter(r=>r.nearestPodiumTriangle<=.5).map(r=>r.component));for(const r of rows)r.connectedToMeasuredPodiumContact=connected.has(r.component);
const componentBounds=new Map();for(let i=0;i<keys.length;i++){const k=find(keys[i]),p=tower.position.slice(i*3,i*3+3);let b=componentBounds.get(k);if(!b){b={min:[...p],max:[...p],vertices:0};componentBounds.set(k,b);}b.vertices++;for(let a=0;a<3;a++){b.min[a]=Math.min(b.min[a],p[a]);b.max[a]=Math.max(b.max[a],p[a]);}}for(const r of rows)r.componentBounds=componentBounds.get(r.component);
const result={issue:'HKS-214',tower:ids[0],podium:ids[1],method:'Actual nearest native podium triangle distance plus triangle adjacency in the original tower, welding duplicate face vertices at0.0001m solely for connectivity analysis. Geometry unchanged.',samples:rows.length,directContacts:rows.filter(r=>r.nearestPodiumTriangle<=.5).length,remainingAllConnected:rows.every(r=>r.connectedToMeasuredPodiumContact),largestSeamDistance:Math.max(...rows.map(r=>r.nearestPodiumTriangle)),rows};writeFileSync(new URL('docs/astra-city/landmark-completion-audit/first12-ifc-support.json',root),JSON.stringify(result,null,2)+'\n');for(const m of models.values())disposeOfficialModel(m);console.log(JSON.stringify({...result,rows:undefined}));
