/** Whole-source triangle burial comparison with actual runtime samplers; no edits. */
import * as THREE from '../../../3d-viewer/vendor/three.module.js';
import {prepareModelCatalogue,loadOfficialModel,disposeOfficialModel} from '../../../3d-viewer/city/official-model-assets.js';
import {extrudeBuilding} from '../../../3d-viewer/city/world.js';
import {nearest} from '../assembly-support-review/triangles.mjs';
import {makeTerrainSampler,inPolygon} from '../../../3d-viewer/city/geo.js';
import {readFileSync,writeFileSync} from 'node:fs';import {createHash} from 'node:crypto';
const root=new URL('../../../',import.meta.url),hashes={},read=p=>{const b=readFileSync(new URL(p,root));hashes[p]=createHash('sha256').update(b).digest('hex');return JSON.parse(b);};
const manifest=read('3d-viewer/city/data/manifest.json'),terrain=read('3d-viewer/city/data/terrain.json');terrain.patches=manifest.terrainPatches.map(p=>read('3d-viewer/'+p.url));const original=makeTerrainSampler(terrain),variant=structuredClone(terrain);
const patched=makeTerrainSampler(variant),folder='',cat=read('source-scripts/city/landmark-completion-audit/first12-catalogue.json'),buildings=new Map();for(const t of manifest.tiles)for(const b of read('3d-viewer/'+t.url).buildings)if(cat.models.some(m=>m.uid===b.uid)||b.uid==='landsd/256535:0')buildings.set(b.uid,b);
const lighting={night:{value:0},activity:{value:new THREE.Vector4(1,1,1,1)},retail:{value:1},elapsed:{value:0},shimmer:{value:0}},rows=[];
for(const e of prepareModelCatalogue(cat,'http://review.local/catalogue.json')){const part=read('docs/astra-city/landmark-completion-audit/existing-review-batch.json').parts.find(p=>p.uid===e.uid),raw=readFileSync(new URL(part.asset.path,root)),model=await loadOfficialModel(e,buildings.get(e.uid),lighting,{fetcher:async()=>new Response(raw)}),{position:p,index:ix}=model.record.modelGeometry;const ys={original:original,patched:patched},stats={};for(const[k,sampler]of Object.entries(ys)){let vertices=0,buried=0,triangles=0,whollyBuried=0,upward=0,upwardWhollyBuried=0;let surfaceArea=0,hiddenArea=0;const gap=[],buriedTriangleEvidence=[];for(let i=0;i<p.length;i+=3){gap.push(p[i+1]-sampler.height(p[i],p[i+2]));vertices++;if(gap.at(-1)<-.25)buried++;}for(let i=0;i<ix.length;i+=3){triangles++;const ids=[ix[i],ix[i+1],ix[i+2]],hidden=ids.every(v=>gap[v]<-.25);if(hidden){whollyBuried++;buriedTriangleEvidence.push({positions:ids.map(v=>[p[v*3],p[v*3+1],p[v*3+2]]),gaps:ids.map(v=>gap[v])});}const vs=ids.map(v=>new THREE.Vector3().fromArray(p,v*3)),face=new THREE.Triangle(...vs),area=face.getArea(),normal=face.getNormal(new THREE.Vector3());surfaceArea+=area;if(hidden)hiddenArea+=area;if(normal.y>.15){upward++;if(hidden)upwardWhollyBuried++;}}stats[k]={surfaceArea,hiddenArea,hiddenAreaPercent:100*hiddenArea/surfaceArea,vertices,buriedVertices:buried,triangles,whollyBuriedTriangles:whollyBuried,upwardTriangles:upward,upwardWhollyBuriedTriangles:upwardWhollyBuried,buriedTriangleEvidence};}
let k11=null;if(e.uid==='landsd/205478:0'){const b=buildings.get('landsd/256535:0'),seen=new Set(),rim=[];for(let i=0;i<p.length;i+=3){if(p[i+1]>e.worldBounds[0][1]+.35)continue;const v=[p[i],p[i+1],p[i+2]],key=v.map(n=>n.toFixed(3)).join(',');if(seen.has(key))continue;seen.add(key);rim.push({position:v,insideSurveyedPodium:inPolygon(v[0],v[2],b.rings)&&v[1]>=b.baseHeightHKPD&&v[1]<=b.topHeightHKPD});}const body=extrudeBuilding(b),v=body.attributes.position.array,i=body.index?.array||Array.from({length:v.length/3},(_,j)=>j),faces=[];for(let j=0;j<i.length;j+=3)faces.push(new THREE.Triangle(...[i[j],i[j+1],i[j+2]].map(k=>new THREE.Vector3().fromArray(v,k*3))));for(const p of rim)p.actualRuntimeVolumeSurfaceDistance=nearest({faces},new THREE.Vector3(...p.position));body.dispose();k11={uid:b.uid,base:b.baseHeightHKPD,top:b.topHeightHKPD,rim,inside:rim.filter(p=>p.insideSurveyedPodium).length,checked:rim.length,qualification:'Inside the unchanged surveyed podium volume is assembly evidence, not a triangle surface seam or complete structural proof.'};}
const foundationVertexTriangles=[];if(e.uid==='landsd/93890:0')for(let j=0;j<ix.length;j+=3){const ids=[ix[j],ix[j+1],ix[j+2]];if(ids.some(v=>Math.abs(p[v*3]-e.worldBounds[0][0])<.001&&Math.abs(p[v*3+1]-e.worldBounds[0][1])<.001))foundationVertexTriangles.push({positions:ids.map(v=>[p[v*3],p[v*3+1],p[v*3+2]]),terrainClearance:ids.map(v=>p[v*3+1]-patched.height(p[v*3],p[v*3+2]))});}rows.push({uid:e.uid,stats,k11,foundationVertexTriangles});disposeOfficialModel(model);}
writeFileSync(new URL('docs/astra-city/landmark-completion-audit/first12-surfaces.json',root),JSON.stringify({rows,hashes,method:'All runtime-loaded indexed source vertices and triangles against exact current/variant drawn-terrain samplers; geometric normal defines upward faces. Below-grade counts are diagnostic, not automatic rejection.',verticalScale:1},null,2)+'\n');console.log(JSON.stringify(rows.map(r=>({uid:r.uid,buriedAfter:r.stats.patched.whollyBuriedTriangles,upwardBuriedAfter:r.stats.patched.upwardWhollyBuriedTriangles,foundationVertexTriangles:r.foundationVertexTriangles.length}))));
