/** Inspect actual legacy embedded geometry with the runtime validator and current terrain. */
import * as THREE from '../../../3d-viewer/vendor/three.module.js';
import {describeBuilding} from '../../../3d-viewer/city/building-geometry.js';
import {makeTerrainSampler} from '../../../3d-viewer/city/geo.js';
import {readFileSync,writeFileSync} from 'node:fs';import{createHash}from'node:crypto';
const root=new URL('../../../',import.meta.url),hashes={},read=p=>{const b=readFileSync(new URL(p,root));hashes[p]=createHash('sha256').update(b).digest('hex');return JSON.parse(b);};
const manifest=read('3d-viewer/city/data/manifest.json'),terrain=read('3d-viewer/city/data/terrain.json');terrain.patches=manifest.terrainPatches.map(p=>read('3d-viewer/'+p.url));const sampler=makeTerrainSampler(terrain),batch=read('docs/astra-city/landmark-completion-audit/muiwo3-batch.json'),rows=[];
for(const part of batch.parts){const b=read(part.asset.path).buildings.find(b=>b.uid===part.uid),description=describeBuilding(b);if(description.modelStatus!=='usable')throw Error('Embedded native model rejected '+b.uid);const g=description.model,p=g.position,ix=g.index||Array.from({length:p.length/3},(_,i)=>i),gap=[],buriedTriangleEvidence=[],rim=[],seen=new Set();let surfaceArea=0,hiddenArea=0,upward=0,upwardBuried=0;
for(let i=0;i<p.length;i+=3){const ground=sampler.height(p[i],p[i+2]);gap.push(p[i+1]-ground);if(p[i+1]<=g.worldBounds[0][1]+.35){const key=p.slice(i,i+3).join(',');if(!seen.has(key)){seen.add(key);rim.push({position:p.slice(i,i+3),ground,gap:p[i+1]-ground});}}}
for(let i=0;i<ix.length;i+=3){const ids=ix.slice(i,i+3),vs=ids.map(v=>new THREE.Vector3().fromArray(p,v*3)),t=new THREE.Triangle(...vs),area=t.getArea(),up=t.getNormal(new THREE.Vector3()).y>.15,hidden=ids.every(v=>gap[v]<-.25);surfaceArea+=area;if(up)upward++;if(hidden){hiddenArea+=area;if(up)upwardBuried++;buriedTriangleEvidence.push({positions:vs.map(v=>v.toArray()),gaps:ids.map(v=>gap[v])});}}
rows.push({uid:b.uid,modelId:g.modelId,modelStatus:description.modelStatus,sourceSHA256:part.asset.sha256,worldBounds:g.worldBounds,foundationApplied:description.foundationApplied,foundationPolicy:b.foundationPolicy||null,rim,stats:{patched:{surfaceArea,hiddenArea,hiddenAreaPercent:hiddenArea/surfaceArea*100,vertices:p.length/3,buriedVertices:gap.filter(x=>x<-.25).length,triangles:ix.length/3,whollyBuriedTriangles:buriedTriangleEvidence.length,upwardTriangles:upward,upwardWhollyBuriedTriangles:upwardBuried,buriedTriangleEvidence}}});}
writeFileSync(new URL('docs/astra-city/landmark-completion-audit/muiwo3-surfaces.json',root),JSON.stringify({issue:'HKS-214',method:'Actual embedded modelGeometry accepted by runtime describeBuilding; all native triangles against actual terrain at1x. Non-indexed source triangle order preserved. Supplemental foundations reported separately.',rows,hashes},null,2)+'\n');console.log(JSON.stringify(rows.map(r=>({uid:r.uid,status:r.modelStatus,rim:r.rim.length,gaps:[Math.min(...r.rim.map(x=>x.gap)),Math.max(...r.rim.map(x=>x.gap))],buried:r.stats.patched.whollyBuriedTriangles,hiddenPercent:r.stats.patched.hiddenAreaPercent,foundation:r.foundationPolicy}))));
