"""Prepare read-only evidence adapters for legacy tile-embedded native geometry."""
import json,pathlib,hashlib
R=pathlib.Path(__file__).resolve().parents[3];S=pathlib.Path(__file__).parent;D=R/'docs/astra-city/landmark-completion-audit';read=lambda p:json.loads(p.read_bytes());save=lambda p,x:p.write_text(json.dumps(x,indent=2)+'\n');uids=['landsd/197795:0','landsd/201560:0','landsd/291920:0'];parts=[p for p in read(D/'existing-133.json') if p['uid'] in uids];bs={b['uid']:b for b in read(R/'3d-viewer/city/data/tiles/-9_1.json')['buildings'] if b['uid'] in uids};models=[]
for p in parts:
 b=bs[p['uid']];g=b['modelGeometry'];assert hashlib.sha256(json.dumps(g,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()).hexdigest()==p['asset']['sha256'];models.append({'uid':p['uid'],'worldBounds':g['worldBounds'],'modelId':g['modelId'],'sha256':p['asset']['sha256'],'embedded':True})
save(S/'muiwo3-catalogue.json',{'models':models,'kind':'review-only-embedded-native-descriptors'});save(S/'muiwo3-groups.json',[{'id':'muiwo-'+u.split('/')[1].split(':')[0],'uids':[u]}for u in uids]);save(D/'muiwo3-batch.json',{'issue':'HKS-214','reviewSnapshot':read(D.parent/'model-integration-20260909/current-source-review.json')['snapshotId'],'parts':[{k:p[k]for k in ['uid','name','asset','landmarkIds']}for p in parts]})
s=(S/'first12_browser.mjs').read_text();s=s.replace("'../landmark-preflight/browser-runtime.mjs'","'../landmark-preflight/browser-runtime.mjs'")
# A test-only accessor reads the tile's actual batched model, never registers/replaces a runtime asset.
needle="await page.addStyleTag({content:'#location-title,.minimap,#labels{display:none!important}'});"
accessor="""await page.evaluate(()=>{window.__embeddedReviewModel=uid=>{const r=window.__review;for(const entry of r.stream.cache.entries.values()){const record=entry.data.buildings.find(b=>b.uid===uid);if(!record?.modelGeometry||!entry.buildings.group.parent||!entry.buildings.group.visible)continue;const g=record.modelGeometry;return{active:true,record:{...record,modelGeometry:{...g,index:g.index||Array.from({length:g.position.length/3},(_,i)=>i)}},meshes:entry.buildings.group.children.filter(m=>m.isMesh&&m.visible),embedded:true};}return null;};});"""
assert needle in s;s=s.replace(needle,needle+accessor).replace('r.stream.detailedModels.get(uid)','window.__embeddedReviewModel(uid)').replace('window.__review.stream.detailedModels.get(uid)','window.__embeddedReviewModel(uid)').replace('hit?.object.userData.officialBuildingUid??null','hit?r.stream.featureAt(hit)?.uid:null');s=s.replace("report.views.push({id:g.id","report.views.push({embeddedNative:true,id:g.id");(S/'muiwo3_browser.generated.mjs').write_text(s)
print('Prepared three embedded descriptors and test-only access to actual tile geometry; runtime untouched')
