/** Bounded before/staged/live checks using the actual city renderer. */
import{createRequire}from'node:module';import{readFile,mkdir,writeFile}from'node:fs/promises';import assert from'node:assert/strict';import{browserExecutable}from'../landmark-preflight/browser-runtime.mjs';
const root=new URL('../../../',import.meta.url),read=async p=>JSON.parse(await readFile(new URL(p,root))),require=createRequire(new URL('3d-viewer/city/package.json',root)),{chromium}=require('playwright');
const mode=process.argv[2]||'staged',folder='source-scripts/city/kai-tak-port/staged/',catalogue=await read(folder+'catalogue.json'),model=catalogue.models[0],building=(await read('source-scripts/city/kai-tak-port/source-forms.json'))[0],url='city/data/official-models/kai-tak-stadium/catalogue.json',out=new URL('docs/astra-city/kai-tak-port/',root);await mkdir(out,{recursive:true});building.tile="1_-2";
const report={mode,views:[],errors:[],sourceSha:model.sha256},browser=await chromium.launch({headless:true,executablePath:browserExecutable(chromium),args:['--no-sandbox','--enable-webgl','--ignore-gpu-blocklist']});
try{for(const width of mode==='staged'?[1280]:[1280,390]){
 const page=await browser.newPage({viewport:{width,height:900},hasTouch:width<700});page.on('pageerror',e=>report.errors.push(e.message));
 await page.route('**/city/app.js*',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text())+'\nPLACES.kaitak={...PLACES.westkowloon,title:"Kai Tak Stadium",zh:"啟德主場館",region:"kowloon",target:[3879,40,-3857],spawn:[4040,-4050],offset:[350,350,490]};Object.defineProperty(window,"__port",{get:()=>({scene,officialModels,stream,camera,controls,renderer,sampler,THREE,visitBuilding,closeSelection,controlSheet})});'});});
 let inject=mode==='live',fail=mode==='live'&&width===390;
 if(mode==='staged'){
  await page.route('**/'+url,r=>r.fulfill({json:catalogue}));
  await page.route('**/city/data/official-models/kai-tak-stadium/'+model.asset,async r=>r.fulfill({body:await readFile(new URL(folder+model.asset,root))}));
  await page.route('**/city/data/manifest.json',async r=>{const response=await r.fetch(),m=await response.json();if(inject)m.officialModelCatalogues.push(url);await r.fulfill({response,json:m});});
 }else if(fail)await page.route('**/kai-tak-stadium/'+model.asset,r=>fail?r.fulfill({status:503,body:'Test unavailable'}):r.continue());
 for(const phase of mode==='staged'?(process.env.PORT_CANDIDATE_ONLY?['staged']:['before','staged']):['live']){
  inject=phase!=='before';await page.goto((process.env.CITY_BASE_URL||'http://127.0.0.1:4176')+'/city.html?district=kaitak');await page.waitForFunction(()=>window.__city?.ready&&window.__port?.stream,null,{timeout:180000});await page.locator('#loading').waitFor({state:'hidden',timeout:180000});
  // Pause GPU drawing during streaming on the software-rendered test host; simulation and loaders continue.
  await page.evaluate(()=>{const r=window.__port.renderer;window.__portDraw=r.render.bind(r);r.render=()=>{};});console.log(phase,width,'city ready');await page.evaluate(b=>window.__port.visitBuilding(b),building);await page.waitForFunction(()=>!window.__city.state.loadingTravel&&!window.__city.state.travelling,null,{timeout:120000});
  await page.evaluate(bounds=>{const r=window.__port,[a,b]=bounds,c=a.map((v,i)=>(v+b[i])/2),radius=new r.THREE.Vector3(...a).distanceTo(new r.THREE.Vector3(...b))/2,half=Math.min(r.THREE.MathUtils.degToRad(r.camera.fov/2),Math.atan(Math.tan(r.THREE.MathUtils.degToRad(r.camera.fov/2))*r.camera.aspect)),d=radius/Math.sin(half)*1.2;r.closeSelection();r.controlSheet?.close({restoreFocus:false});r.camera.position.set(c[0]+d*.5,c[1]+d*.5,c[2]+d*.707);r.controls.target.fromArray(c);r.controls.update();},model.worldBounds);
  if(fail){await page.waitForFunction(uid=>window.__port.officialModels.cache.errors.has(uid),model.uid,{timeout:90000});assert.equal(await page.evaluate(uid=>!!window.__port.stream.detailedModels.get(uid)?.active,model.uid),false);fail=false;await page.locator('#stream-retry').click();report.failedDownloadFallbackAndRetry=true;}
  if(inject)try{await page.waitForFunction(uid=>window.__port.stream.detailedModels.get(uid)?.active,model.uid,{timeout:45000});}catch(e){console.log('LOAD DIAGNOSTIC',await page.evaluate(uid=>({stats:window.__port.officialModels.stats,errors:[...window.__port.officialModels.cache.errors],loaded:!!window.__port.stream.getLoadedBuilding(uid),detail:!!window.__port.stream.detailedModels.get(uid)}),model.uid));throw e;}
  await page.addStyleTag({content:'#location-title,.minimap,#labels{display:none!important}'});
  for(const time of phase==='before'?['15:00']:['15:00','22:00']){
   await page.evaluate(t=>{const e=document.getElementById('time');e.value=t;e.dispatchEvent(new Event('input',{bubbles:true}));},time);await page.waitForTimeout(700);await page.evaluate(()=>{const r=window.__port;window.__portDraw(r.scene,r.camera);});
   const state=await page.evaluate(uid=>{const r=window.__port,d=r.stream.detailedModels.get(uid);let pick=null,collision=null;if(d){const p=d.record.modelGeometry.position,idx=d.record.modelGeometry.index;let roof=null;for(let i=0;i<idx.length;i+=3){const q=[0,1,2].map(k=>(p[idx[i]*3+k]+p[idx[i+1]*3+k]+p[idx[i+2]*3+k])/3);if(!roof||q[1]>roof[1])roof=q;}const ray=new r.THREE.Raycaster(new r.THREE.Vector3(roof[0],roof[1]+10,roof[2]),new r.THREE.Vector3(0,-1,0));pick=ray.intersectObjects(d.meshes)[0]?.object.userData.officialBuildingUid;collision=r.stream.collision(roof[0],roof[2],roof[1]-.05,roof[1]+.05,.05)?.uid;}return{active:!!d?.active,pick,collision,overflow:document.documentElement.scrollWidth>innerWidth,camera:r.camera.position.toArray(),cache:r.officialModels.stats};},model.uid);
   assert.equal(state.active,inject);assert(!state.overflow);if(inject){assert.equal(state.pick,model.uid);assert.equal(state.collision,model.uid);}const file=`${phase}-${width}-${time.replace(':','')}.jpg`;await page.screenshot({path:new URL(file,out).pathname,type:'jpeg',quality:85});report.views.push({phase,width,time,file,...state});console.log(file);await writeFile(new URL(mode+'.json',out),JSON.stringify(report,null,2)+'\n');
  }
 }
 await page.close();
}assert.deepEqual(report.errors,[]);}finally{await browser.close();await writeFile(new URL(mode+'.json',out),JSON.stringify(report,null,2)+'\n');}
