"""Pack held native sources for isolated review; never approve or modify cache matches."""
import pathlib,sys,json,hashlib,gzip,importlib.util
ROOT=pathlib.Path(__file__).resolve().parents[3];HERE=pathlib.Path(__file__).resolve().parent
spec=importlib.util.spec_from_file_location('existing_pack',ROOT/'source-scripts/city/central-completion/pack_models.py');pack=importlib.util.module_from_spec(spec);spec.loader.exec_module(pack)
pre=json.loads((ROOT/'docs/astra-city/landmark-preflight/report.json').read_bytes());audit=json.loads((ROOT/'docs/astra-city/identity-hold-review/audit.json').read_bytes());UIDS=['landsd/205478:0','landsd/297401:0','landsd/314191:0','landsd/81387:0','landsd/93890:0'];models=[];out=HERE/'candidates';out.mkdir(exist_ok=True)
for row in audit['rows']:
 if row['uid'] not in UIDS:continue
 p=next(p for p in pre['parts'] if p['uid']==row['uid']);a=p['acquisitionEvidence'];mp=ROOT/row['sourceManifest'];m=json.loads(mp.read_bytes());s=next(s for s in m['models'] if s['id']==row['modelId'])
 for rel,digest in s['sourceHashes'].items():assert hashlib.sha256((mp.parent/rel).read_bytes()).hexdigest()==digest
 raw,stats=pack.pack(mp.parent/s['sourceEntry']);compressed=gzip.compress(raw,mtime=0);digest=hashlib.sha256(compressed).hexdigest();(out/(digest+'.glb.gz')).write_bytes(compressed)
 models.append({'uid':p['uid'],'buildingCSUID':p['csuid'],'objectId':p['objectId'],'modelId':s['id'],'sourceTile':m['tile'],'sourceTileRevision':m['tileRevision'],'worldBounds':s['worldBounds'],'triangles':s['triangles'],'recordedBaseHeight':row['footprintBaseTop'][0],'recordedTopHeight':row['footprintBaseTop'][1],'label':p['name'],'priority':'unreviewed','asset':digest+'.glb.gz','encoding':'gzip','bytes':len(compressed),'glbBytes':len(raw),'decodedGeometryBytes':stats['decodedGeometryBytes'],'indexedVertices':stats['vertices'],'sha256':digest,'placementReviewed':False,'identityReviewApproved':False,'publicationApproved':False,'proceduralWindows':False if p['uid'] in ['landsd/297401:0','landsd/314191:0','landsd/81387:0'] else True,'identityHoldReview':'Private review candidate from exact GeoRefNo archive member; original conservative match remains unchanged. Requires explicit per-part identity acceptance.'})
cat={'schemaVersion':1,'kind':'staged-official-model-catalogue','area':'Identity exception review','datasetId':'landsd_rcd_1742809441342_98380','crs':'EPSG:2326','verticalDatum':'Hong Kong Principal Datum','rootTranslation':[-834500,0,816500],'models':models,'counts':{'packedModels':len(models)},'publicationApproved':False}
(out/'catalogue.json').write_text(json.dumps(cat,indent=2)+'\n');(out/'catalogue-index.json').write_text(json.dumps({'models':len(models),'catalogues':['catalogue.json']},indent=2)+'\n');print(json.dumps({'models':len(models),'triangles':sum(m['triangles']for m in models),'bytes':sum(m['bytes']for m in models)}))
