/** Station-only replacement route; source assets and all normal scene layers remain unchanged. */
import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {browserExecutable} from '../landmark-preflight/browser-runtime.mjs';
const root=new URL('../../../',import.meta.url),read=async p=>JSON.parse(await readFile(new URL(p,root))),sha=b=>createHash('sha256').update(b).digest('hex'),require=createRequire(new URL('3d-viewer/city/package.json',root)),{chromium}=require('playwright');
const data=await read('docs/astra-city/identity-hold-review/station-mask/report.json'),patch=await read(data.replacementPatch),building=(await read('3d-viewer/city/data/tiles/0_-1.json')).buildings.find(b=>b.uid===data.uid),out=new URL('docs/astra-city/identity-hold-review/station-mask/browser/',root);await mkdir(out,{recursive:true});assert.equal(sha(await readFile(new URL(data.replacementPatch,root))),data.replacementSHA256);
const report={issue:'HKS-214',uid:data.uid,staged:true,published:false,errors:[],views:[],inputHashes:{},limits:['Only station child terrain and its manifest URL are intercepted. Model catalogues, assets and all scene layers use normal runtime.','Desktop and emulated mobile browser, not physical-device certification.','Footprint plus interpolation-collar correction deliberately leaves other unverified historical coastline-mask problems untouched.']};for(const p of ['3d-viewer/city/app.js','3d-viewer/city/geo.js','3d-viewer/city/world.js','3d-viewer/city/native-terrain.js','3d-viewer/city/data/manifest.json'])report.inputHashes[p]=sha(await readFile(new URL(p,root)));
const browser=await chromium.launch({headless:true,executablePath:browserExecutable(chromium),args:['--enable-webgl','--ignore-gpu-blocklist']});
try{for(const mobile of [false,true]){const page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1280,height:900},isMobile:mobile,hasTouch:mobile});page.on('pageerror',e=>report.errors.push(e.message));
await page.route('**/city/app.js',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text())+'\nObject.defineProperty(window,"__station",{get:()=>({scene,terrain,officialModels,stream,camera,controls,renderer,sampler,THREE,visitBuilding,closeSelection,controlSheet})});'});});
await page.route('**/city/data/manifest.json',async r=>{const response=await r.fetch(),m=await response.json();let n=0;for(const e of m.terrainPatches)if(e.url==='city/data/support-native-297401-0.json'){e.url='city/data/'+patch.id+'.json';e.sha256=data.replacementSHA256;n++;}assert.equal(n,1);await r.fulfill({response,json:m});});await page.route('**/city/data/'+patch.id+'.json',r=>r.fulfill({json:patch}));
await page.goto('http://127.0.0.1:4176/city.html?district=westkowloon');await page.waitForFunction(()=>window.__city?.ready,null,{timeout:180000});await page.locator('#loading').waitFor({state:'hidden',timeout:180000});await page.evaluate(b=>window.__station.visitBuilding(b),building);await page.waitForFunction(()=>!window.__city.state.loadingTravel&&!window.__city.state.travelling,null,{timeout:120000});
await page.evaluate(mobile=>{const r=window.__station;r.closeSelection();r.controlSheet.close({restoreFocus:false});r.camera.position.set(...(mobile?[1010,490,-2450]:[812,330,-2249]));r.controls.target.set(563,24,-1866);r.controls.update();},mobile);await page.waitForFunction(uid=>window.__station.stream.detailedModels.get(uid)?.active,data.uid,{timeout:90000});await page.waitForTimeout(1200);
const probes=await page.evaluate(points=>{const r=window.__station;r.terrain.updateMatrixWorld(true);return points.map(p=>{const ray=new r.THREE.Raycaster(new r.THREE.Vector3(p.xz[0],100,p.xz[1]),new r.THREE.Vector3(0,-1,0)),hits=ray.intersectObject(r.terrain,true).map(h=>h.point.y);return{...p,sampler:r.sampler.height(...p.xz),terrainHits:hits};});},[data.centre&&{xz:data.centre.xz,sourceTIN:data.centre.sourceTIN,stagedGround:data.centre.newChildRendered},...data.probes]);
for(const p of probes){assert(p.terrainHits.length>0,'No terrain at '+p.xz);assert(p.terrainHits.some(y=>Math.abs(y-p.sampler)<.002),'Sampler/render mismatch '+p.xz);assert(p.sampler>0,'Water inside station '+p.xz);}
for(const time of ['15:00','22:00']){await page.evaluate(time=>{const input=document.querySelector('#time');input.value=time;input.dispatchEvent(new Event('input',{bubbles:true}));},time);await page.waitForTimeout(700);const evidence=await page.evaluate(uid=>{const r=window.__station,d=r.stream.detailedModels.get(uid);return{active:d?.active,visible:d?.group.visible,stats:r.officialModels.stats,overflow:document.documentElement.scrollWidth>innerWidth,camera:r.camera.position.toArray(),target:r.controls.target.toArray(),render:window.__city.state.render};},data.uid);assert(evidence.active&&evidence.visible&&!evidence.overflow);const file=(mobile?'mobile':'desktop')+'-'+time.replace(':','')+'.jpg';await page.screenshot({path:new URL(file,out).pathname,type:'jpeg',quality:85});report.views.push({mobile,time,file,sha256:sha(await readFile(new URL(file,out))),...evidence,probes});console.log(file,probes.length,'terrain rays passed');await writeFile(new URL('report.json',out),JSON.stringify(report,null,2)+'\n');}await page.close();}}
finally{report.finished=new Date().toISOString();await writeFile(new URL('report.json',out),JSON.stringify(report,null,2)+'\n');await browser.close();}assert.equal(report.errors.length,0);
