#!/usr/bin/env python3
"""
Generate a rotatable 3D Lantau Island terrain object and browser viewer.

The mesh uses the same cached Terrarium DEM tiles and approximate Lantau mask
as the skyline generator. Outputs:
- lantau-terrain-mesh.json for the Three.js viewer
- lantau-terrain.obj for DCC/CAD import
- lantau-3d-viewer.html for local interactive viewing
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np

import generate_lantau_skyline as skyline


OUT = Path(__file__).resolve().parent
GRID_X = 220
GRID_Z = 140
VERTICAL_EXAGGERATION = 2.0
BASE_DEPTH_M = 80


def bilinear_sample(grid: np.ndarray, extent: dict[str, float], lon: float, lat: float) -> float:
    h, w = grid.shape
    x = (lon - extent["west"]) / (extent["east"] - extent["west"]) * (w - 1)
    y = (extent["north"] - lat) / (extent["north"] - extent["south"]) * (h - 1)
    if x < 0 or y < 0 or x >= w - 1 or y >= h - 1:
        return 0.0
    x0 = int(math.floor(x))
    y0 = int(math.floor(y))
    dx = x - x0
    dy = y - y0
    a = grid[y0, x0]
    b = grid[y0, x0 + 1]
    c = grid[y0 + 1, x0]
    d = grid[y0 + 1, x0 + 1]
    return float((a * (1 - dx) + b * dx) * (1 - dy) + (c * (1 - dx) + d * dx) * dy)


def build_mesh() -> dict[str, object]:
    dem, extent = skyline.build_dem_mosaic()
    lon_values = np.linspace(skyline.BBOX["west"], skyline.BBOX["east"], GRID_X)
    lat_values = np.linspace(skyline.BBOX["south"], skyline.BBOX["north"], GRID_Z)
    mean_lat = (skyline.BBOX["south"] + skyline.BBOX["north"]) / 2.0
    metres_per_degree_lon = 111_320.0 * math.cos(math.radians(mean_lat))
    metres_per_degree_lat = 110_540.0
    centre_lon = (skyline.BBOX["west"] + skyline.BBOX["east"]) / 2.0
    centre_lat = (skyline.BBOX["south"] + skyline.BBOX["north"]) / 2.0

    index_grid: list[list[int | None]] = []
    vertices: list[float] = []
    heights: list[float] = []
    lon_lat: list[tuple[float, float]] = []

    for lat in lat_values:
        row: list[int | None] = []
        for lon in lon_values:
            if skyline.point_in_polygon(float(lon), float(lat), skyline.LANTAU_POLYGON):
                elev = max(0.0, bilinear_sample(dem, extent, float(lon), float(lat)))
                x = (lon - centre_lon) * metres_per_degree_lon
                z = -(lat - centre_lat) * metres_per_degree_lat
                y = elev * VERTICAL_EXAGGERATION
                row.append(len(heights))
                vertices.extend([round(x, 3), round(y, 3), round(z, 3)])
                heights.append(round(elev, 3))
                lon_lat.append((float(lon), float(lat)))
            else:
                row.append(None)
        index_grid.append(row)

    indices: list[int] = []
    for zi in range(GRID_Z - 1):
        for xi in range(GRID_X - 1):
            a = index_grid[zi][xi]
            b = index_grid[zi][xi + 1]
            c = index_grid[zi + 1][xi]
            d = index_grid[zi + 1][xi + 1]
            if a is not None and b is not None and c is not None and d is not None:
                indices.extend([a, c, b, b, c, d])

    x_vals = vertices[0::3]
    y_vals = vertices[1::3]
    z_vals = vertices[2::3]
    metadata = {
        "agent": "Codex",
        "terrain_source": "Cached AWS elevation-tiles-prod Terrarium DEM tiles, zoom 13.",
        "projection": "Local metre coordinates; x west-east, z south-north, y elevation.",
        "vertical_exaggeration": VERTICAL_EXAGGERATION,
        "grid": {"x_samples": GRID_X, "z_samples": GRID_Z},
        "vertex_count": len(heights),
        "triangle_count": len(indices) // 3,
        "bbox_lon_lat": skyline.BBOX,
        "bounds_m": {
            "x_min": min(x_vals),
            "x_max": max(x_vals),
            "y_min": min(y_vals),
            "y_max": max(y_vals),
            "z_min": min(z_vals),
            "z_max": max(z_vals),
        },
        "notes": [
            "Approximate Lantau coastline mask removes surrounding sea and most nearby islands.",
            "Elevation is vertically exaggerated in the 3D object for legibility; raw metre height is preserved in the heights_m array.",
            "No buildings, vegetation, or man-made structures are included.",
        ],
    }
    return {
        "metadata": metadata,
        "vertices": vertices,
        "indices": indices,
        "heights_m": heights,
        "lon_lat": [[round(a, 7), round(b, 7)] for a, b in lon_lat],
    }


def write_obj(mesh: dict[str, object]) -> None:
    vertices = mesh["vertices"]
    indices = mesh["indices"]
    assert isinstance(vertices, list)
    assert isinstance(indices, list)
    lines = [
        "# Lantau Island terrain mesh",
        "# Generated by codex/generate_lantau_3d.py",
        f"# Vertical exaggeration: {VERTICAL_EXAGGERATION}",
    ]
    for i in range(0, len(vertices), 3):
        lines.append(f"v {vertices[i]} {vertices[i + 1]} {vertices[i + 2]}")
    for i in range(0, len(indices), 3):
        # OBJ indices are 1-based.
        lines.append(f"f {indices[i] + 1} {indices[i + 1] + 1} {indices[i + 2] + 1}")
    (OUT / "lantau-terrain.obj").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_viewer() -> None:
    html = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Lantau Island 3D Terrain</title>
  <style>
    :root {
      color-scheme: light;
      --ink: #151515;
      --muted: #68645d;
      --paper: #f7f4ec;
      --panel: rgba(247, 244, 236, 0.86);
    }
    * { box-sizing: border-box; }
    html, body {
      width: 100%;
      height: 100%;
      margin: 0;
      overflow: hidden;
      background: var(--paper);
      color: var(--ink);
      font: 14px/1.4 ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }
    #scene {
      position: fixed;
      inset: 0;
      width: 100vw;
      height: 100vh;
      display: block;
    }
    .toolbar {
      position: fixed;
      top: 16px;
      left: 16px;
      display: flex;
      gap: 8px;
      align-items: center;
      padding: 8px;
      background: var(--panel);
      border: 1px solid rgba(21, 21, 21, 0.14);
      backdrop-filter: blur(10px);
    }
    button {
      width: 38px;
      height: 34px;
      border: 1px solid rgba(21, 21, 21, 0.22);
      background: #fffdf7;
      color: var(--ink);
      cursor: pointer;
      display: grid;
      place-items: center;
      padding: 0;
    }
    button:hover { background: #eee8db; }
    .readout {
      min-width: 128px;
      color: var(--muted);
      font-size: 12px;
      padding: 0 4px;
      white-space: nowrap;
    }
    @media (max-width: 720px) {
      .toolbar {
        top: 10px;
        left: 10px;
        right: 10px;
        justify-content: center;
      }
      .readout { display: none; }
    }
  </style>
</head>
<body>
  <canvas id="scene" aria-label="Rotatable 3D terrain model of Lantau Island"></canvas>
  <div class="toolbar" aria-label="3D view controls">
    <button id="reset" title="Reset view" aria-label="Reset view">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 12a9 9 0 1 0 3-6.7"/><path d="M3 4v6h6"/></svg>
    </button>
    <button id="spin" title="Toggle rotation" aria-label="Toggle rotation">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M17 1l4 4-4 4"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><path d="M7 23l-4-4 4-4"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/></svg>
    </button>
    <div class="readout" id="readout">Loading terrain</div>
  </div>
  <script type="module">
    import * as THREE from './vendor/three.module.js';
    import { OrbitControls } from './vendor/OrbitControls.js';

    const canvas = document.querySelector('#scene');
    const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: false });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.setClearColor(0xf7f4ec, 1);
    renderer.outputColorSpace = THREE.SRGBColorSpace;

    const scene = new THREE.Scene();
    scene.fog = new THREE.Fog(0xf7f4ec, 18500, 43000);

    const camera = new THREE.PerspectiveCamera(34, 1, 50, 65000);
    camera.position.set(0, 10400, 22400);

    const controls = new OrbitControls(camera, renderer.domElement);
    controls.enableDamping = true;
    controls.dampingFactor = 0.06;
    controls.minDistance = 9000;
    controls.maxDistance = 39000;
    controls.maxPolarAngle = Math.PI * 0.48;
    controls.target.set(0, 1200, 0);

    const hemi = new THREE.HemisphereLight(0xffffff, 0xb5aa98, 2.4);
    scene.add(hemi);
    const sun = new THREE.DirectionalLight(0xffffff, 2.8);
    sun.position.set(-9000, 18000, 12000);
    scene.add(sun);

    const material = new THREE.MeshStandardMaterial({
      color: 0x2f5b43,
      roughness: 0.92,
      metalness: 0.0,
      flatShading: false
    });
    const wireMaterial = new THREE.LineBasicMaterial({
      color: 0xf1eadb,
      transparent: true,
      opacity: 0.16
    });

    const readout = document.querySelector('#readout');
    const response = await fetch('./lantau-terrain-mesh.json');
    const meshData = await response.json();
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.Float32BufferAttribute(meshData.vertices, 3));
    geometry.setIndex(meshData.indices);
    geometry.computeVertexNormals();
    geometry.computeBoundingSphere();
    geometry.computeBoundingBox();

    const terrain = new THREE.Mesh(geometry, material);
    terrain.rotation.x = -Math.PI / 2;
    terrain.rotation.z = Math.PI;
    terrain.scale.setScalar(0.82);
    scene.add(terrain);

    const wire = new THREE.LineSegments(new THREE.WireframeGeometry(geometry), wireMaterial);
    wire.rotation.copy(terrain.rotation);
    wire.scale.copy(terrain.scale);
    scene.add(wire);

    const baseGeometry = new THREE.CircleGeometry(12500, 96);
    const baseMaterial = new THREE.MeshBasicMaterial({ color: 0xe8e0d0, transparent: true, opacity: 0.55 });
    const base = new THREE.Mesh(baseGeometry, baseMaterial);
    base.rotation.x = -Math.PI / 2;
    base.position.y = -90;
    scene.add(base);

    const peak = Math.round(meshData.metadata.bounds_m.y_max / meshData.metadata.vertical_exaggeration);
    readout.textContent = `${meshData.metadata.vertex_count.toLocaleString()} vertices · peak ${peak} m`;

    let spinning = true;
    document.querySelector('#spin').addEventListener('click', () => {
      spinning = !spinning;
    });
    document.querySelector('#reset').addEventListener('click', () => {
      camera.position.set(0, 10400, 22400);
      controls.target.set(0, 1200, 0);
      controls.update();
    });

    function resize() {
      const width = window.innerWidth;
      const height = window.innerHeight;
      renderer.setSize(width, height, false);
      camera.aspect = width / height;
      camera.updateProjectionMatrix();
    }
    window.addEventListener('resize', resize);
    resize();

    function animate() {
      requestAnimationFrame(animate);
      if (spinning) {
        terrain.rotation.z += 0.0018;
        wire.rotation.z = terrain.rotation.z;
      }
      controls.update();
      renderer.render(scene, camera);
    }
    animate();
  </script>
</body>
</html>
"""
    (OUT / "lantau-3d-viewer.html").write_text(html, encoding="utf-8")


def main() -> None:
    mesh = build_mesh()
    (OUT / "lantau-terrain-mesh.json").write_text(
        json.dumps(mesh, separators=(",", ":")), encoding="utf-8"
    )
    write_obj(mesh)
    write_viewer()


if __name__ == "__main__":
    main()
