"""Read-only candidate lookup. Never turns a name match into a publishable model."""
import json,pathlib,sqlite3,re,time
ROOT=pathlib.Path(__file__).resolve().parents[3];HERE=pathlib.Path(__file__).resolve().parent;DOC=ROOT/'docs/astra-city/landmark-registry'
def main():
 registry=json.loads((HERE/'landmarks.json').read_text());ids=[r['id'] for r in registry['landmarks']];assert len(ids)==len(set(ids))
 c=sqlite3.connect('file:'+str(ROOT/'source-scripts/city/building-batch/local/buildings.sqlite')+'?mode=ro',uri=True);c.row_factory=sqlite3.Row
 started=time.monotonic()
 detailed={r[0] for r in c.execute('SELECT uid FROM models')}
 inventory={}
 for row in c.execute('SELECT uid,name,csuid,object_id,x,z,embedded FROM buildings WHERE active=1'):
  r=dict(row);r['hasDetailedReference']=bool(r.pop('embedded') or r['uid'] in detailed);inventory[r['uid']]=r
 named=[(r,(r['name'] or '').lower()) for r in inventory.values() if r['name']]
 rows=[]
 for item in registry['landmarks']:
  matches={uid:inventory[uid] for uid in item.get('sourceUidHints',[]) if uid in inventory}
  patterns=[re.compile('^'+re.escape(p).replace('%','.*').replace('_','.')+'$') for p in dict.fromkeys(item.get('inventoryNamePatterns',[]))]
  for r,name in named:
   if patterns and any(p.match(name) for p in patterns) and r['name'] not in item.get('excludedNames',[]):matches[r['uid']]=r
  for uid in item.get('excludedSourceUids',[]):matches.pop(uid,None)
  rows.append({'id':item['id'],'name':item['name'],'origin':item['origin'],'candidateCount':len(matches),'currentDetailedReferences':sum(r['hasDetailedReference'] for r in matches.values()),'candidates':list(matches.values()),'review':'Candidate or prior selection hints only; verify spatial compound membership and missing unnamed parts before processing.'})
 c.close();out={'schemaVersion':1,'seconds':round(time.monotonic()-started,3),'newLandmarkSites':sum(r['origin']=='artchitectours-2026-09-07' for r in rows),'totalRegistryEntries':len(rows),'registrySummary':registry['summary'],'aiCalls':0,'networkRequests':0,'rows':rows}
 DOC.mkdir(parents=True,exist_ok=True);(DOC/'inventory-candidates.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
 lines=['# Landmark discovery registry — HKS-201','',f"{len(rows)} deduplicated discovery entries: original selections plus the requested architecture guides and skyscraper table. Three entries are historical interior venues requiring host review; two separate infrastructure/landscape targets sit outside this table. Sites and tower groups can contain multiple government source parts.",'','[Master registry](../../../source-scripts/city/landmark-registry/landmarks.json) · [Candidate inventory](inventory-candidates.json)','','| Landmark | Origin | Candidate parts | Existing detailed references |','| --- | --- | ---: | ---: |']
 for r in rows:lines.append(f"| {r['name']} | {r['origin']} | {r['candidateCount']} | {r['currentDetailedReferences']} |")
 lines+=['','Name/UID hints are discovery evidence only. A zero name match is not a missing building or missing government model. Tai Kwun has an HKS-208 principal-component audit; unrelated Tai Kwun Mansion is deliberately excluded. Some newly listed sites already have detailed parts from area batches. No model conversion/download occurs in this audit.','','## Sources and processing','','- [User-supplied Hong Kong tour index](https://www.artchitectours.com/tour/tours-in-hong-kong/)','- [Skyline tour](https://www.artchitectours.com/tour/hong-kong-skyline/)','- [West Kowloon tour linked from the index](https://www.artchitectours.com/tour/hong-kong-west-kowloon/)','','Skyline:10 sites, including three existing selections (IFC, HSBC, Bank of China); seven additions. West Kowloon:seven building sites, counting M+ and M+ Pavilion separately. Union Square and West Kowloon Cultural District are area contexts; Sky100 is inside ICC. The overview\'s former Kai Tak Airport reference is excluded from present-day modelling; [Airport Authority history](https://www.hongkongairport.com/en/about-us/?section=our-history) records closure in1998. Source pages are used for discovery, not current dimensions/project status.','','## Next processing gate','','Review compound boundaries, unnamed parts and government IDs; then create explicit batches through HKS-202/203. Keep original trial lists intact for reproducibility. Existing detailed references do not certify appearance or region readiness. The fixed1× vertical-scale requirement applies to every future batch.','','Build locally: `python3 source-scripts/city/landmark-registry/build.py`; audit without AI/network calls: `python3 source-scripts/city/landmark-registry/audit.py`. Refresh the skyscraper snapshot only when needed with `import_tallest.py` (one HTTP request), or supply `--html` to parse an existing local snapshot.', '', 'The additional sources are listed in the master registry with per-entry links. National Geographic is sponsored content from2023; The Foreign Architect is an older guide, so tenant and opening-status statements are not treated as current. Wikipedia contributes180 table rows/179 names. A duplicate Manhattan Place entry has conflicting measurements; these source warnings are retained. Under-construction/proposed, demolished and cancelled/vision tables are retained as excluded-source notes. The main table can also include topped-out projects, so current status must still be verified.', '', 'The skyscraper table advertises a180m threshold and is not an exhaustive list of buildings above35 floors. Discovery heights/floors are never written over government/native elevations.']
 (DOC/'README.md').write_text('\n'.join(lines)+'\n');print(json.dumps({k:v for k,v in out.items() if k!='rows'}))
if __name__=='__main__':main()
