import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const output=new URL('../../../docs/astra-city/atmosphere/browser/',import.meta.url);await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:1000},hasTouch:true});
const report={testedAt:new Date().toISOString(),checks:[],views:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));
await page.route('**/city/app.js',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text())+'\nwindow.__hazeFog=()=>scene.fog.density;\n'});});
const state=()=>page.evaluate(()=>window.__city.state);
const tab=async name=>{if(!(await state()).controls.expanded)await page.locator('#panel-toggle').click();await page.locator('#tab-'+name).click();};
const input=async(id,value)=>{await page.locator('#'+id).evaluate((el,v)=>{el.value=String(v);el.dispatchEvent(new Event('input',{bubbles:true}));},value);await page.waitForTimeout(150);};
const shot=async name=>{await page.screenshot({path:new URL(name+'.png',output).pathname});report.views.push({name,atmosphere:(await state()).environment.atmosphere,sky:(await state()).environment.sky});};
const ready=async()=>{await page.waitForFunction(()=>window.__city?.ready,null,{timeout:120000});await page.locator('#loading').waitFor({state:'hidden'});await page.waitForFunction(()=>{const s=window.__city.state;return !s.loadingTravel&&!s.travelling&&!s.stream.pending&&!s.bridges.pending&&!s.regional.pending;},null,{timeout:120000});};
try{
 await page.goto('http://127.0.0.1:4176/city.html?district=lantau');await ready();await tab('weather');assert.equal(await page.locator('#atmospheric-haze').inputValue(),'35');
 for(const key of ['rain','clouds','fog','snow'])await input('weather-'+key,0);
 await tab('time');await page.locator('#time').fill('14:00');await tab('weather');
 for(const value of [50,0,100]){await input('atmospheric-haze',value);assert.equal(await page.evaluate(()=>window.__hazeFog()),(await state()).environment.atmosphere.fogDensity);await shot('lantau-day-'+value);}
 await input('atmospheric-haze',0);assert.equal(await page.evaluate(()=>window.__hazeFog()),0);await input('weather-fog',70);assert.ok(await page.evaluate(()=>window.__hazeFog())>.0001);await input('weather-fog',0);report.checks.push('Real scene fog reaches zero in clear weather; intentional weather fog is retained; same-camera Lantau screenshots at 0/50/100');
 await tab('time');await page.locator('#sky-date').fill('2026-09-06');await page.locator('#sky-date').press('Tab');await page.locator('#time').fill('22:00');await page.locator('[data-mode="star"]').click();await tab('weather');
 assert.equal(await page.locator('#weather-fog').isDisabled(),true);assert.equal(await page.locator('#atmospheric-haze').isEnabled(),true);
 await input('atmospheric-haze',100);const hazy=await state();await shot('night-sky-100');await input('atmospheric-haze',0);const clear=await state();await shot('night-sky-0');
 assert.ok(clear.environment.sky.visibleStars>hazy.environment.sky.visibleStars);assert.deepEqual(clear.environment.astronomy,hazy.environment.astronomy);assert.deepEqual(clear.camera,hazy.camera);assert.equal(await page.evaluate(()=>window.__hazeFog()),0);report.checks.push('Stargaze slider remains enabled and reveals more catalogue stars without changing time, astronomy or camera');
 await page.locator('[data-mode="orbit"]').click();await tab('weather');
 const observed=new Date().toISOString(),stamp=new Date(Date.now()+8*3600000).toISOString().slice(0,16).replace(/[-T:]/g,'');
 await page.route('**/weather.php?**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({updateTime:observed,icon:[63],temperature:{data:[{place:'Hong Kong Observatory',value:28}]},humidity:{data:[{place:'Hong Kong Observatory',value:84}]},rainfall:{startTime:observed,endTime:observed,data:[{place:'Islands',max:8}]}})}));
 await page.route('**/historical-archive/get-file?**',r=>r.fulfill({contentType:'text/csv',body:`Date,Station,Direction,Speed,Gust\n${stamp},Cheung Chau,East,22,34\n`}));
 await page.route('**/opendata.php?**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({fields:['Date time','Automatic Weather Station','10 minute mean visibility'],data:[[stamp,'Central','12 km'],[stamp,'Chek Lap Kok','12 km'],[stamp,'Sai Wan Ho','18 km'],[stamp,'Waglan Island','N/A']]})}));
 await page.route('**/aqhi-individual?**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify([{station:'Tung Chung',aqhi:8,health_risk:'Very High',publish_date:new Date(Date.now()+8*3600000).toISOString().slice(0,19).replace('T',' ')}])}));
 await page.locator('#weather-mode').selectOption('live');await page.waitForFunction(()=>window.__city.state.environment.weather.status==='live',null,{timeout:20000});const live=(await state()).environment.weather;
 await page.waitForFunction(()=>window.__city.state.environment.atmosphere.air.visibilityMetres===12000&&window.__city.state.environment.atmosphere.air.aqhi.fresh,null,{timeout:20000});
 assert.equal(await page.locator('#atmospheric-haze').isDisabled(),true);assert.match(await page.locator('#atmospheric-haze-value').textContent(),/12 km/);assert.match(await page.locator('#air-quality-status').textContent(),/AQHI 8/);assert.equal(await page.evaluate(()=>window.__hazeFog()),Math.sqrt(-Math.log(.02))/12000);await shot('live-visibility-and-aqhi');
 await page.locator('#haze-override').check();assert.equal(await page.locator('#atmospheric-haze').isEnabled(),true);await input('atmospheric-haze',80);assert.deepEqual((await state()).environment.weather.settings,live.settings);assert.deepEqual((await state()).environment.weather.observation,live.observation);await page.locator('#haze-override').uncheck();await page.waitForTimeout(150);assert.equal((await state()).environment.atmosphere.source,'visibility');assert.equal((await state()).environment.atmosphere.manualHaze,.8);
 await page.locator('[data-mode="star"]').click();await tab('weather');assert.equal(await page.locator('#atmospheric-haze').isDisabled(),true);await page.locator('#haze-override').check();await input('atmospheric-haze',0);assert.equal(await page.evaluate(()=>window.__hazeFog()),0);await page.locator('[data-mode="orbit"]').click();await tab('weather');
 report.checks.push('Live HKO visibility directly drives fog; independent EPD AQHI is shown; manual override and Stargaze preserve readings and saved haze');
 await page.locator('#weather-mode').selectOption('manual');await input('atmospheric-haze',0);await page.reload();await ready();await tab('weather');assert.equal(await page.locator('#atmospheric-haze').inputValue(),'0');
 await input('atmospheric-haze',65);await page.reload();await ready();await tab('weather');assert.equal(await page.locator('#atmospheric-haze').inputValue(),'65');report.checks.push('Zero and non-zero settings persist through real page reloads');
 for(const viewport of [{width:390,height:844},{width:320,height:740}]){await page.setViewportSize(viewport);await tab('weather');await page.locator('#atmospheric-haze').scrollIntoViewIfNeeded();const box=await page.locator('#atmospheric-haze').boundingBox();assert.ok(box.height>=44);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#atmospheric-haze').focus();await page.keyboard.press('Home');assert.equal(await page.locator('#atmospheric-haze').inputValue(),'0');await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#atmospheric-haze').inputValue(),'1');await shot('weather-mobile-'+viewport.width);}
 report.checks.push('320/390 px layouts have no horizontal overflow, 44 px range targets and working keyboard controls');
 assert.deepEqual(report.errors,[]);report.result='passed';console.log(JSON.stringify({result:report.result,checks:report.checks,errors:report.errors}));
}catch(e){report.result='failed';report.error=e.stack;await shot('failure').catch(()=>{});throw e;}finally{await writeFile(new URL('verification.json',output),JSON.stringify(report,null,2)+'\n');await browser.close();}
