import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const evidence=new URL('../../../docs/astra-city/integration/',import.meta.url);await mkdir(evidence,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':undefined),args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:1000},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const state=()=>page.evaluate(()=>window.__city.state);
const settle=()=>page.waitForFunction(()=>{const s=window.__city?.state;return s&&!s.loadingTravel&&!s.travelling&&s.stream.pending===0;},null,{timeout:120000});
const tab=async name=>{if(!await page.locator('#explorer').isVisible())await page.locator('#panel-toggle').click();await page.locator(`[data-panel="${name}"]`).click();};
const input=async(id,value)=>page.locator('#'+id).evaluate((el,value)=>{el.value=String(value);el.dispatchEvent(new Event('input',{bubbles:true}));},value);
try{
 await page.goto((process.env.CITY_URL||'http://127.0.0.1:4176/city.html')+'?district=kowloon');await page.waitForFunction(()=>window.__city?.ready,null,{timeout:120000});await page.locator('#loading').waitFor({state:'hidden'});await settle();
 assert.ok((await state()).counts.buildings>100000);await tab('time');
 await page.locator('#sky-date').fill('2026-06-21');await page.locator('#sky-date').press('Tab');await page.locator('#time').fill('12:00');const summer=(await state()).environment.astronomy;
 await page.locator('#sky-date').fill('2026-12-21');await page.locator('#sky-date').press('Tab');const winter=(await state()).environment.astronomy;
 assert.ok(Date.parse(summer.sunset)-Date.parse(summer.sunrise)>Date.parse(winter.sunset)-Date.parse(winter.sunrise)+2*3600000);
 await page.locator('#sky-mode').selectOption('live');await page.waitForFunction(()=>window.__city.state.environment.mode==='live');assert.ok(Math.abs(Date.parse((await state()).environment.date)-Date.now())<3000);
 await page.locator('#time').fill('20:00');assert.equal((await state()).environment.mode,'manual');assert.equal((await state()).time,20);
 await page.locator('#sky-date').fill('2026-12-31');await page.locator('#sky-date').press('Tab');await page.locator('#time').fill('23:59');await page.locator('#time-play').click();await page.waitForFunction(()=>window.__city.state.environment.hkt.date==='2027-01-01');await page.locator('#time-play').click();
 await page.locator('#sky-date').fill('2026-09-06');await page.locator('#sky-date').press('Tab');await page.locator('#time').fill('20:00');
 await page.locator('[data-mode="star"]').click();await page.waitForFunction(()=>window.__city.state.mode==='star'&&window.__city.state.environment.sky.visibleStars>100);
 const star=await state();await page.mouse.move(920,460);await page.mouse.down();await page.mouse.move(1080,490,{steps:8});await page.mouse.up();assert.notEqual((await state()).stargazing.bearing,star.stargazing.bearing);
 await page.locator('#sky-constellations').uncheck();assert.equal((await state()).environment.sky.constellations,false);await page.locator('#sky-constellations').check();await page.locator('[data-bearing="0"]').click();
 await page.screenshot({path:new URL('stargazing-1440x1000.png',evidence).pathname});await page.keyboard.press('Escape');assert.equal((await state()).mode,'orbit');
 await tab('weather');await input('weather-rain',75);await input('weather-clouds',90);await input('weather-fog',45);await input('weather-wind',65);await input('weather-waves',70);await page.waitForTimeout(500);
 assert.equal((await state()).environment.weather.settings.rain,.75);const fog=(await state()).environment.effects.fogDensity;assert.ok(fog>.0001);
 await page.screenshot({path:new URL('manual-weather-1440x1000.png',evidence).pathname});
 await page.locator('[data-mode="star"]').click();assert.equal((await state()).environment.weather.settings.rain,.75);await page.waitForFunction(()=>window.__city.state.environment.effects.cloudCover===0);await page.keyboard.press('Escape');await page.waitForFunction(()=>window.__city.state.environment.effects.cloudCover===.9);
 const observed=new Date().toISOString();const stamp=new Date(Date.now()+8*3600000).toISOString().slice(0,16).replace(/[-T:]/g,'');
 await page.route('**/weather.php?**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({updateTime:observed,icon:[63],temperature:{data:[{place:'Hong Kong Observatory',value:28}]},humidity:{data:[{place:'Hong Kong Observatory',value:84}]},rainfall:{startTime:observed,endTime:observed,data:[{place:'Yau Tsim Mong',max:8}]}})}));
 await page.route('**/historical-archive/get-file?**',r=>r.fulfill({contentType:'text/csv',body:`Date,Station,Direction,Speed,Gust\n${stamp},Cheung Chau,East,22,34\n`}));
 await tab('weather');await page.locator('#weather-mode').selectOption('live');await page.waitForFunction(()=>window.__city.state.environment.weather.status==='live',null,{timeout:20000});
 assert.equal(await page.locator('#weather-rain').isDisabled(),true);assert.equal((await state()).environment.weather.observation.temperature.value,28);await page.waitForFunction(()=>document.getElementById('weather-observation').textContent.includes('28°C'));assert.match(await page.locator('#weather-observation').textContent(),/28°C/);assert.match(await page.locator('#weather-observation').textContent(),/22 km\/h/);
 await page.locator('#weather-mode').selectOption('manual');await page.waitForFunction(()=>window.__city.state.environment.weather.mode==='manual');assert.equal((await state()).environment.weather.settings.rain,.75);
 for(const key of ['rain','clouds','fog','snow'])await input('weather-'+key,0);
 await page.setViewportSize({width:390,height:844});await tab('time');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.locator('#time-dial').scrollIntoViewIfNeeded();await page.screenshot({path:new URL('sky-mobile-390x844.png',evidence).pathname});await tab('weather');await page.screenshot({path:new URL('weather-mobile-390x844.png',evidence).pathname});
 assert.deepEqual(errors,[]);
 const result={result:'passed',checks:['whole-territory dataset loaded','seasonal daylight length','live HKT clock','manual clock exits live mode','date rollover through New Year','stargazing camera and real catalogue','constellation toggle and compass','manual rain/cloud/fog/wind/waves','stargazing suspends and restores weather','mock HKO integration and source values','manual settings restored after live weather','mobile tabs and no horizontal overflow'],summer,winter,weather:(await state()).environment.weather,errors};
 await writeFile(new URL('verification.json',evidence),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}
