import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';import {nativeTerrainSurface} from '../native-terrain.js';import {nativeTerrainSurface as oldSurface} from '../../../source-scripts/city/government-import/proposed-runtime/historical-native-terrain-runtime-fixture-v1.mjs';import {orientationSign,withinFiniteTriangleProjection as inside} from '../exact-finite-triangle-projection.js';
const root=new URL('../../../',import.meta.url),read=p=>{const b=fs.readFileSync(new URL(p,root));return JSON.parse(p.endsWith('.gz')?gunzipSync(b):b);},hash=b=>createHash('sha256').update(b).digest('hex');
function triangle(y=10){return{position:[0,y,0,1,y,0,0,y,1],index:[0,1,2]};}
test('strict finite interior',()=>assert.equal(nativeTerrainSurface(triangle()).height(.2,.3),10));
test('closed exact boundary and vertices',()=>{const s=nativeTerrainSurface(triangle());for(const [x,z]of[[0,0],[1,0],[0,1],[.5,.5],[0,.5]])assert.equal(s.height(x,z),10);});
test('outside negative grazing floor rejects',()=>{const m=triangle();assert.equal(oldSurface(m).height(.5,.5+1e-9),10);assert.equal(nativeTerrainSurface(m).height(.5,.5+1e-9),null);});
test('far outside rejects',()=>assert.equal(nativeTerrainSurface(triangle()).height(2,2),null));
test('reversed orientation same finite domain',()=>{const m=triangle();m.index=[2,1,0];assert.equal(nativeTerrainSurface(m).height(.2,.3),10);assert.equal(nativeTerrainSurface(m).height(.5,.5+1e-9),null);});
test('outside high surface cannot hide actual lower terrain',()=>{const m={position:[0,10,0,1,10,0,0,10,1,-1,2,-1,2,2,-1,-1,2,2],index:[0,1,2,3,4,5]};assert.equal(nativeTerrainSurface(m).height(-1e-9,.2),2);});
test('vertical projected face provides no height',()=>assert.equal(nativeTerrainSurface({position:[0,0,0,0,1,0,0,2,1],index:[0,1,2]}).height(0,.5),null));
test('exact filtered fallback boundary',()=>assert.equal(orientationSign([100000,100000],[100001,100001],[100000.5,100000.5]),0));
test('one representable double outside remains outside',()=>{const a=[0,0],b=[1,0],c=[0,1];assert.equal(inside(a,b,c,[.5,.5+Number.EPSILON]),false);assert.equal(inside(a,b,c,[.5,.5]),true);});
test('dyadic cancellation resolves true orientation without epsilon',()=>{const a=[0,0],b=[1,1],c=[1,1+Number.EPSILON];assert.equal(orientationSign(a,b,c),1);assert.equal(orientationSign(a,c,b),-1);});
test('nonfinite rejects',()=>assert.throws(()=>orientationSign([0,0],[1,1],[Infinity,1])));
test('actual seven phantom native picks reject exact outside and match independent rays',()=>{const r=read('docs/astra-city/government-import/xl-terrain-recovery-20261010-festival-gap-sampler-finite-membership-v1/diagnostic.json.gz'),c=read('docs/astra-city/government-import/xl-terrain-recovery-20261010-festival-mixed-authentic-parent-gap-proposal-v3/terrain-candidates.json')[0],raw=fs.readFileSync(new URL(c.path,root));assert.equal(hash(raw),c.sha256);const patch=JSON.parse(raw),s=nativeTerrainSurface(patch.nativeMesh);assert.equal(r.rows.length,7);for(const row of r.rows){const p=row.rawRayProbe;assert.equal(inside(...row.completeActualFloat32DrawnFace.map(q=>[q[0],q[2]]),[p.x,p.z]),false);assert.ok(Math.abs(s.height(p.x,p.z)-p.highestIndependentDrawnRayHeight)<.004);}});
test('actual441 gap probes match finite independent ray',()=>{const r=read('source-scripts/city/government-import/local/xl-terrain-recovery-20261010-festival-gap-sampler-ray-v1/diagnostic.json.gz'),c=read('docs/astra-city/government-import/xl-terrain-recovery-20261010-festival-mixed-authentic-parent-gap-proposal-v3/terrain-candidates.json')[0],patch=read(c.path),s=nativeTerrainSurface(patch.nativeMesh);assert.equal(r.rows.length,441);for(const p of r.rows)assert.ok(Math.abs(s.height(p.x,p.z)-p.highestIndependentDrawnRayHeight)<.004);});
