// HKS-180: actual City controls and rendering. Reserve the GPU before running.
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const evidence=new URL('../../../docs/astra-city/tides/browser/',import.meta.url);await mkdir(evidence,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[],checks=[],snapshots={},requests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const state=()=>page.evaluate(()=>window.__city.state);
const input=(id,value)=>page.locator('#'+id).evaluate((el,value)=>{el.value=String(value);el.dispatchEvent(new Event('input',{bubbles:true}));},value);
const tab=async()=>{if(!await page.locator('#explorer').isVisible())await page.locator('#panel-toggle').click();await page.locator('#tab-weather').click();};
const screenshot=name=>page.screenshot({path:new URL(name,evidence).pathname});
const settle=()=>page.waitForFunction(()=>window.__city?.ready&&!window.__city.state.loadingTravel&&!window.__city.state.travelling&&window.__city.state.stream.pending===0,null,{timeout:120000});
const save=(result,extra={})=>writeFile(new URL('verification.json',evidence),JSON.stringify({result,testedAt:new Date().toISOString(),checks,snapshots,requests,errors,...extra},null,2)+'\n');
async function canvasDifference(record=false){return page.evaluate(async record=>{
 const canvas=document.querySelector('#viewport canvas'),image=new Image();image.src=canvas.toDataURL();await image.decode();const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;const ctx=copy.getContext('2d');ctx.drawImage(image,0,0);const data=ctx.getImageData(0,0,copy.width,copy.height).data;
 if(record){window.__tideTestPixels=data;return 0;}let changed=0;for(let i=0;i<data.length;i+=4)if(Math.abs(data[i]-window.__tideTestPixels[i])+Math.abs(data[i+1]-window.__tideTestPixels[i+1])+Math.abs(data[i+2]-window.__tideTestPixels[i+2])>24)changed++;return changed;
 },record);}
try{
 const observed=new Date().toISOString(),stamp=new Date(Date.now()+8*3600000).toISOString().slice(0,16).replace(/[-T:]/g,'');
 await page.route('**/weather.php?**',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({updateTime:observed,icon:[50],temperature:{data:[{place:'Hong Kong Observatory',value:28}]},humidity:{data:[{place:'Hong Kong Observatory',value:75}]},rainfall:{startTime:observed,endTime:observed,data:[]}})}));
 await page.route('**/historical-archive/get-file?**',route=>route.fulfill({contentType:'text/csv',body:`Date,Station,Direction,Speed,Gust\n${stamp},HK Observatory,East,18,25\n`}));
 await page.route('**/opendata.php?**',route=>{
  const u=new URL(route.request().url()),station=u.searchParams.get('station'),date=[u.searchParams.get('year'),u.searchParams.get('month').padStart(2,'0'),u.searchParams.get('day').padStart(2,'0')].join('-');requests.push({station,date,url:u.href});
  const heights=Array.from({length:24},(_,i)=>(1.8+.65*Math.sin((i+1)*Math.PI/6)+(station==='QUB'?.2:0)).toFixed(2));
  return route.fulfill({contentType:'application/json',body:JSON.stringify({fields:['MM','DD',...Array.from({length:24},(_,i)=>String(i+1).padStart(2,'0'))],data:[[u.searchParams.get('month').padStart(2,'0'),u.searchParams.get('day').padStart(2,'0'),...heights]]})});
 });
 await page.goto(process.env.CITY_URL||'http://127.0.0.1:4176/city.html?district=muiwo');await settle();await page.locator('#loading').waitFor({state:'hidden'});await tab();
 let s=await state();assert.equal(s.environment.tides.mode,'manual');assert.equal(s.environment.tides.manualLevelHKPD,.3);assert.equal(s.environment.tides.station.code,'CCH');assert.equal(requests.length,0);snapshots.initial={tides:s.environment.tides,water:s.environment.water};snapshots.performance=await page.evaluate(()=>new Promise(resolve=>{let previous;const samples=[];function tick(now){if(previous!==undefined)samples.push(now-previous);previous=now;if(samples.length<180)requestAnimationFrame(tick);else{samples.sort((a,b)=>a-b);resolve({frames:samples.length,medianFrameMs:samples[90],p95FrameMs:samples[171],render:window.__city.state.render,camera:window.__city.state.camera});}}requestAnimationFrame(tick);}));
 await input('weather-waves',0);await input('tide-level',-1);await page.waitForFunction(()=>Math.abs(window.__city.state.environment.water.renderedLevelHKPD+1)<.001);await page.waitForTimeout(250);await canvasDifference(true);await screenshot('muiwo-low-tide-1440x1000.png');
 await input('tide-level',4);await page.waitForFunction(()=>Math.abs(window.__city.state.environment.water.renderedLevelHKPD-4)<.001);await page.waitForTimeout(250);const changed=await canvasDifference();assert.ok(changed>100,`shoreline pixels should change (${changed})`);s=await state();for(const boat of s.ferries)assert.ok(Math.abs(boat.waterline-4)<.001);snapshots.manualHigh={water:s.environment.water,ferries:s.ferries,changedCanvasPixels:changed};await screenshot('muiwo-high-tide-1440x1000.png');checks.push('manual −1..4 m alters the rendered shoreline; low water stays above the −4 m seabed and ferries follow the surface');
 await page.locator('[data-mode="walk"]').click();await page.waitForFunction(()=>window.__city.state.mode==='walk');s=await state();assert.ok(s.position[1]+.2>=s.environment.water.restingLevelHKPD);assert.equal(s.collision,false);snapshots.walk={position:s.position,camera:s.camera,water:s.environment.water};await page.locator('[data-mode="orbit"]').click();checks.push('high-tide walking arrival stays within the 20 cm shallow-wading limit and outside buildings');
 await tab();await input('tide-level',.65);await page.locator('#weather-mode').selectOption('live');await page.waitForFunction(()=>window.__city.state.environment.tides.status==='live',null,{timeout:15000});s=await state();let tide=s.environment.tides;assert.equal(tide.station.code,'CCH');assert.ok(Math.abs(tide.prediction.heightHKPD-(tide.prediction.heightCD-.146))<1e-9);assert.ok(Math.abs(tide.restingLevelHKPD-tide.prediction.heightHKPD)<1e-9);assert.equal(await page.locator('#tide-level').isDisabled(),true);assert.equal(await page.locator('#tide-graph').isVisible(),true);assert.ok((await page.locator('#tide-source').textContent()).includes('Prediction'));snapshots.liveCheungChau=tide;await screenshot('muiwo-live-prediction-1440x1000.png');
 await page.locator('#tide-station').selectOption('QUB');await page.waitForFunction(()=>{const t=window.__city.state.environment.tides;return t.status==='live'&&t.station.code==='QUB'&&!!t.prediction;});snapshots.liveQuarryBay=(await state()).environment.tides;assert.ok(requests.some(r=>r.station==='QUB'));assert.equal(requests.filter(r=>r.station==='CCH').length,3);checks.push('live hourly prediction uses three HKT dates, correct CD→HKPD conversion, graph, source labels and station switching');
 await page.locator('[data-mode="star"]').click();await page.waitForFunction(()=>window.__city.state.mode==='star');s=await state();const pausedWater=s.environment.water;await page.waitForTimeout(150);s=await state();assert.equal(s.environment.water.renderedLevelHKPD,pausedWater.renderedLevelHKPD);assert.equal(s.environment.tides.manualLevelHKPD,.65);await page.locator('[data-mode="orbit"]').click();await tab();await page.locator('#weather-mode').selectOption('manual');await page.waitForFunction(()=>window.__city.state.environment.tides.mode==='manual'&&Math.abs(window.__city.state.environment.water.restingLevelHKPD-.65)<.001);assert.equal(await page.locator('#tide-level').isDisabled(),false);assert.equal(await page.locator('#tide-graph').isVisible(),false);checks.push('Stargaze suspends water effects and manual tide restores unchanged after live mode');
 await page.emulateMedia({reducedMotion:'no-preference'});await input('weather-wind',85);await input('weather-waves',100);await page.waitForTimeout(400);const first=(await state()).environment.water;await page.waitForTimeout(200);const second=(await state()).environment.water;assert.notEqual(first.renderedLevelHKPD,second.renderedLevelHKPD);snapshots.waves={first,second};await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(100);const reduced=(await state()).environment.water;await page.waitForTimeout(150);assert.equal((await state()).environment.water.renderedLevelHKPD,reduced.renderedLevelHKPD);checks.push('wind-driven waves animate, and Reduced Motion freezes their movement');
 for(const width of [390,320]){await page.setViewportSize({width,height:844});await tab();await page.locator('#tide-level').scrollIntoViewIfNeeded();const layout=await page.evaluate(()=>({width:innerWidth,document:document.documentElement.scrollWidth,panel:document.getElementById('explorer').clientWidth,scroll:document.getElementById('explorer').scrollWidth}));assert.ok(layout.document<=width&&layout.scroll<=layout.panel+1);snapshots['mobile'+width]=layout;if(width===390)await screenshot('tide-controls-mobile-390x844.png');}
 checks.push('tide controls fit 390 px and 320 px layouts');assert.deepEqual(errors,[]);await save('passed',{browser:await browser.version()});console.log(JSON.stringify({result:'passed',checks,errors},null,2));
}catch(error){await save('failed',{error:String(error),latest:await state().catch(()=>null)});await screenshot('failure.png').catch(()=>{});throw error;}finally{await browser.close();}
