"""Build HKS-208 source-accounted delivery notes and an existing-evidence gallery."""
import collections,html,json,pathlib
H=pathlib.Path(__file__).resolve().parent;R=H.parents[2];D=R/'docs/astra-city/architecture-batch'
def read(p):return json.loads(p.read_bytes())
def main():
 a=read(H/'acceptance.json');report=read(H/'report.json');selection=read(H/'selection.json');cat=read(H/'approved/catalogue.json');result={r['uid']:r for r in report['results']};groups=[]
 for g in selection['groups']:
  n=collections.Counter('newDetailed' if u in a['accepted'] else 'placementHeld' if u in a['held'] else 'alreadyDetailed' if result[u]['outcome']=='already-detailed' else 'sourceReview' for u in g['uids']);groups.append({**g,'counts':dict(n)})
 coverage={'issue':'HKS-208','followup':'HKS-209','verticalScale':1,'sourceParts':58,'newDetailed':len(a['accepted']),'alreadyDetailed':17,'placementHeld':a['held'],'sourceReview':10,'compressedBytes':cat['counts']['compressedBytes'],'triangles':cat['counts']['triangles'],'transferredBytes':read(H/'missing-source-report.json')['cumulativeTransferBytes'],'groups':groups,'wholeRegionComplete':False}
 (D/'coverage.json').write_text(json.dumps(coverage,ensure_ascii=False,indent=2)+'\n')
 lines=['# Expanded architecture batch 1 — HKS-208','',f"{coverage['newDetailed']} reviewed new government model components, {coverage['compressedBytes']:,} compressed bytes. The14 selected landmark groups contain58 source parts:17 already detailed, {len(a['held'])} placement holds and10 requiring source/identity follow-up. Model parts are not whole landmarks or regional completion percentages.",'','| Landmark group | New detailed | Prior detailed | Placement hold | Source review |','| --- | ---: | ---: | ---: | ---: |']
 for g in groups:lines.append('| '+g['name']+' | '+' | '.join(str(g['counts'].get(k,0)) for k in ['newDetailed','alreadyDetailed','placementHeld','sourceReview'])+' |')
 lines+=['','[Visual comparisons](comparison.html) · [Per-component decisions](../../../source-scripts/city/architecture-batch/acceptance.json) · [Native terrain/support audit](../../../source-scripts/city/architecture-batch/placement-context.json) · [Acquisition evidence](../../../source-scripts/city/architecture-batch/missing-source-report.json)','','All source geometry uses unchanged EPSG:2326/HKPD coordinates at fixed1× scale. No terrain, surveyed elevations or other building forms changed. Lippo/Hysan towers must retain supporting podiums. Native roofs may exceed footprint TopHeight (e.g. Court of Final Appeal dome/finial); footprint metadata is preserved separately. These are non-textured government meshes with existing procedural city materials, not photographic models.','','## Evidence and limits','','All31 candidates pass the shared model loader, native-roof picking/collision and rendered-terrain/sampler checks. All31 underwent staged browser checks including day/night, mobile viewport budgets, walk/Fly arrivals and failed-download fallback/Retry.229 city regression tests pass. Isolated foundation images are labelled diagnostic; unrelated geometry is hidden only for inspection. Ordinary-scene screenshots and installed verification remain separate. Desktop frame intervals are not physical-phone performance proof.','','HKS-209 tracks held foundations and unresolved source matches. Four exactGeoRef candidates (Asia Society3089/3090/4314, Flagstaff143421) fail the conservative matching screen and need individual investigation. Missing exact models in checked sheet revisions are not proof that no model exists anywhere. The expensive0.25m Tai Kwun terrain experiment remains unpublished.','','## Reproduce','','```sh','/tmp/astra-city-venv/bin/python source-scripts/city/architecture-batch/prepare.py','node source-scripts/city/building-batch/validate_candidates.mjs --candidates source-scripts/city/architecture-batch/compact','python3 source-scripts/city/architecture-batch/review.py prepare','python3 source-scripts/city/architecture-batch/review.py publish','```','','Preparation reuses existing cached decoder/matcher/packer with no AI calls. Four newly acquired models used15,356,700 HTTP-range bytes under a20MB guard; acquisition manifests and complete directory hashes document scope. Raw source/staged payloads and terrain experiment are local, ignored caches. Approved runtime assets are committed for PR298; production R2 offload is HKS-206, not performed here. Publication is deliberately one-shot and refuses duplicate IDs or changed reviewed inputs.']
 (D/'README.md').write_text('\n'.join(lines)+'\n')
 parts=['<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Architecture batch1 — HKS-208</title><style>body{font:16px system-ui;max-width:1080px;margin:24px auto;padding:0 16px;background:#f5f5ee;color:#263e36}article{margin:32px 0}.pair{position:relative}.pair img{width:100%;display:block}.after{position:absolute;inset:0;clip-path:inset(0 0 0 50%)}label{display:flex;gap:12px}input{flex:1}</style><h1>Architecture batch1</h1><p>Reviewed detailed government forms at fixed1×. Five representative staged before/after viewpoints; foundations have separate diagnostic evidence. <a href="README.md">Counts, installed checks and remaining holds</a>.</p>']
 for g in selection['groups']:
  folder='new-sources-browser' if g['id'] in ['opus','peak-tower','hysan-place'] else 'browser'
  for uid in g['uids']:
   if uid not in a['accepted'] or uid not in ['landsd/235860:0','landsd/170207:0','landsd/223794:0','landsd/184076:0','landsd/319803:0']:continue
   stem=g['id']+'-'+uid.replace('/','-').replace(':','-')+'-day.png'
   if not (D/folder/'before'/stem).exists():continue
   label=html.escape(next(m['label'] for m in cat['models'] if m['uid']==uid))
   parts.append(f'<article><h2>{label} · {uid}</h2><div class="pair"><img src="{folder}/before/{stem}" alt="Before {label}"><img class="after" src="{folder}/after/{stem}" alt="After {label}"></div><label>Before / After<input aria-label="Compare {label}" type="range" min="0" max="100" value="50"></label></article>')
 parts.append("<script>document.querySelectorAll('input').forEach(i=>i.addEventListener('input',()=>i.closest('article').querySelector('.after').style.clipPath='inset(0 0 0 '+i.value+'%)'));</script></html>")
 (D/'comparison.html').write_text('\n'.join(parts))
if __name__=='__main__':main()
