/** Exact source triangle contacts; bbox adjacency is never acceptance. */
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as THREE from '../../../3d-viewer/vendor/three.module.js';
import {prepareModelCatalogue,loadOfficialModel,disposeOfficialModel} from '../../../3d-viewer/city/official-model-assets.js';
import {makeTerrainSampler} from '../../../3d-viewer/city/geo.js';
import {nearest} from '../assembly-support-review/triangles.mjs';
const root=new URL('../../../',import.meta.url),read=p=>JSON.parse(readFileSync(new URL(p,root))),sha=p=>createHash('sha256').update(readFileSync(new URL(p,root))).digest('hex'),base='source-scripts/city/whampoa-special/candidates/',catalogue=read(base+'catalogue.json'),manifest=read('3d-viewer/city/data/manifest.json'),terrain=read('3d-viewer/city/data/terrain.json');terrain.patches=manifest.terrainPatches.map(p=>read('3d-viewer/'+p.url));const sampler=makeTerrainSampler(terrain);
const records=new Map(manifest.tiles.flatMap(t=>read('3d-viewer/'+t.url).buildings).filter(b=>catalogue.models.some(m=>m.uid===b.uid)).map(b=>[b.uid,b])),geometry=new Map(),lighting={night:{value:1},activity:{value:new THREE.Vector4(1,1,1,1)},retail:{value:1},elapsed:{value:0},shimmer:{value:0}};
for(const e of prepareModelCatalogue(catalogue,'http://review.local/catalogue.json')){const raw=readFileSync(new URL(base+e.asset,root));const model=await loadOfficialModel(e,records.get(e.uid),lighting,{fetcher:async()=>new Response(raw)}),{position,index}=model.record.modelGeometry,faces=[],rim=new Map();for(let i=0;i<index.length;i+=3)faces.push(new THREE.Triangle(...[index[i],index[i+1],index[i+2]].map(j=>new THREE.Vector3().fromArray(position,j*3))));for(let i=0;i<position.length;i+=3)if(position[i+1]<=e.worldBounds[0][1]+.35){const v=[position[i],position[i+1],position[i+2]];rim.set(v.map(v=>v.toFixed(3)).join(','),v);}geometry.set(e.uid,{e,faces,rim:[...rim.values()]});disposeOfficialModel(model);}
const podium=geometry.get('landsd/225581:0'),rows=[];for(const [uid,g] of geometry){if(uid===podium.e.uid)continue;const samples=g.rim.map(position=>({position,distance:nearest(podium,new THREE.Vector3(...position)),ground:sampler.height(position[0],position[2])}));rows.push({uid,samples,contacts:samples.filter(s=>s.distance<=.5).length,total:samples.length,minDistance:Math.min(...samples.map(s=>s.distance)),maxDistance:Math.max(...samples.map(s=>s.distance)),sourcePodiumUID:podium.e.uid,sourcePodiumCSUID:podium.e.buildingCSUID,placementApproved:false});}
const rim=podium.rim.map(position=>({position,ground:sampler.height(position[0],position[2]),gap:position[1]-sampler.height(position[0],position[2])}));const result={issue:'HKS-219',method:'Existing runtime loader plus closest point on every actual podium triangle; all unique native tower vertices within0.35m of native minimum Y, unchanged0.5m contact tolerance.',catalogueSHA256:sha(base+'catalogue.json'),manifestSHA256:sha('3d-viewer/city/data/manifest.json'),rows,podium:{uid:podium.e.uid,worldBounds:podium.e.worldBounds,rim,minimumTerrainGap:Math.min(...rim.map(s=>s.gap)),maximumTerrainGap:Math.max(...rim.map(s=>s.gap))},published:false};writeFileSync(new URL('docs/astra-city/whampoa-special/support.json',root),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,rows:rows.map(r=>({...r,samples:undefined})),podium:{...result.podium,rim:undefined}}));
