"""Source-aware current-delivery inventory; sheet availability is never called an import."""
import collections,gzip,hashlib,json,pathlib,re
from shapely.geometry import Polygon,box
HERE=pathlib.Path(__file__).resolve().parent;ROOT=HERE.parents[2];DOC=ROOT/'docs/astra-city/central-completion'
read=lambda p:json.loads((ROOT/p).read_text())
hash_file=lambda p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
def main():
 config=json.loads((HERE/'config.json').read_text());manifest=read('3d-viewer/city/data/manifest.json');e0,n0,e1,n1=config['sourceBoundsHK1980'];world=[e0-834500,816500-n1,e1-834500,816500-n0];study=box(*world)
 tiles=[t for t in manifest['tiles'] if box(*t['bounds']).intersects(study)]
 buildings=[b for t in tiles for b in read('3d-viewer/'+t['url'])['buildings'] if study.intersects(Polygon(b['rings'][0],b['rings'][1:]))]
 bridges=[]
 from shapely.geometry import LineString
 for b in read('3d-viewer/city/data/bridges.json')['bridges']:
  if len(b.get('path',[]))>1 and LineString(b['path']).intersects(study):bridges.append(b)
 def counts(bs):return {'forms':len(bs),'government':sum(b['uid'].startswith('landsd/') for b in bs),'osm':sum(not b['uid'].startswith('landsd/') for b in bs),'detailedModels':sum(bool(b.get('modelGeometry')) for b in bs),'structureTypes':dict(collections.Counter(b.get('structureType','OSM') for b in bs)),'estimatedHeightForms':sum(b['heightSource']=='estimated' for b in bs)}
 sections=[]
 for w in config['reviewWindows']:
  area=box(*w['worldBounds']);bs=[b for b in buildings if area.intersects(Polygon(b['rings'][0],b['rings'][1:]))];spans=[b for b in bridges if LineString(b['path']).intersects(area)]
  sections.append({**w,'status':'baseline-audited-implementation-pending','counts':counts(bs),'mappedPathRecords':len(spans),'mappedBridgeRecords':sum(b.get('role')=='bridge' for b in spans),'mappedPathRoles':dict(collections.Counter(b.get('role') for b in spans)),'sourceModelPublicDecks':0,'limits':['Overlapping review windows are planning extents, not statutory boundaries.','Mapped span availability does not establish safe elevated walking or verified deck elevation.']})
 needles={'HSBC':r'^HSBC Main Building$','Bank of China Tower':r'^Bank of China Tower$','IFC':r'International Finance|IFC Mall','Jardine House':r'^Jardine House$','City Hall':r'^City Hall$','Cheung Kong Center':r'^Cheung Kong Center$','Government HQ / LegCo':r'Government.*Headquarters|Legislative Council Complex','Central Market':r'^Central Market$'}
 fields=['uid','name','buildingCSUID','objectId','structureType','centre','baseHeightHKPD','topHeightHKPD','heightSource','base','height']
 landmarks={name:[{k:b.get(k) for k in fields}|{'deliveredGeometry':'original detailed model' if b.get('modelGeometry') else 'footprint extrusion','sourceModelId':b.get('modelGeometry',{}).get('modelId'),'source':f"https://portal.csdi.gov.hk/server/rest/services/common/landsd_rcd_1637211194312_35158/MapServer/0/query?f=json&objectIds={b['objectId']}&outFields=*&returnGeometry=false" if b.get('objectId') else 'https://www.openstreetmap.org/'+b['id']} for b in buildings if re.search(pattern,b.get('name',''),re.I)] for name,pattern in needles.items()}
 baseline=[{k:b.get(k) for k in ['uid','id','objectId','buildingCSUID','baseHeightHKPD','topHeightHKPD','heightSource','base','height','tile']}|{'ringsSha256':hashlib.sha256(json.dumps(b['rings'],separators=(',',':')).encode()).hexdigest(),'modelSha256':hashlib.sha256(json.dumps(b['modelGeometry'],sort_keys=True,separators=(',',':')).encode()).hexdigest() if b.get('modelGeometry') else None} for b in buildings]
 if not (HERE/'baseline-buildings.json.gz').exists():(HERE/'baseline-buildings.json.gz').write_bytes(gzip.compress(json.dumps(baseline,separators=(',',':')).encode(),mtime=0))
 output={'schemaVersion':1,'scope':config['scope'],'worldBounds':world,'counts':counts(buildings),'sections':sections,'landmarks':landmarks,'mappedPathRecords':len(bridges),'mappedBridgeRecords':sum(b.get('role')=='bridge' for b in bridges),'mappedPathRoles':dict(collections.Counter(b.get('role') for b in bridges)),'namedEscalatorRecords':[{'id':b['id'],'source':b['source'],'kind':b['kind'],'tags':b.get('tags',{}),'path':b['path']} for b in bridges if 'escalator' in (b.get('name','')+' '+b.get('tags',{}).get('name:en','')).lower()],'liveTerrainPatches':manifest.get('terrainPatches',[]),'liveBridgeModelPackages':manifest.get('bridgeModels',[]),'sourceHashes':[{'file':'3d-viewer/'+t['url'],'sha256':hash_file('3d-viewer/'+t['url'])} for t in tiles], 'gaps':[{'kind':'missing-import','finding':'No detailed Central building model is delivered in this review window; landmark labels currently sit on official footprint extrusions.'},{'kind':'terrain-resolution','finding':'Central still uses the existing coarse 70 m terrain; current detailed patches cover Mui Wo and Tai O.'},{'kind':'public-walk-surfaces','finding':'Central elevated spans have mapped proxies but no reviewed source-model walking floors in the live infrastructure packages.'}],'references':['https://www.landsd.gov.hk/en/survey-mapping/mapping/3d-mapping.html','https://data.gov.hk/en-data/dataset/hk-landsd-openmap-3d-visualisation-map-non-textured-models'],'limits':['This is a baseline delivery audit, not completed section or pedestrian-access acceptance.','The government building heights are retained approximate outline attributes; source model roofs and spires can differ.']}
 (DOC/'baseline.json').write_text(json.dumps(output,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'counts':output['counts'],'mappedPathRecords':len(bridges),'mappedBridgeRecords':sum(b.get('role')=='bridge' for b in bridges),'sections':[{k:v for k,v in s.items() if k in ['section','counts','mappedBridgeRecords']} for s in sections]},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
