/** Fixed-camera regional before/after evidence in the existing city viewer. */
import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
import {replayRoute} from '../tai-o-completion/route_navigation.mjs';
const require=createRequire(new URL('../../../3d-viewer/city/package.json',import.meta.url)),{chromium}=require('playwright');
const root=new URL('../../../',import.meta.url),phase=process.argv[2]||'before',output=new URL('docs/astra-city/mui-wo-completion/browser/'+phase+'/',root);await mkdir(output,{recursive:true});
const hash=async p=>createHash('sha256').update(await readFile(new URL(p,root))).digest('hex');
const report={phase,commit:execFileSync('git',['rev-parse','HEAD'],{cwd:root}).toString().trim(),started:new Date().toISOString(),manifestSha256:await hash('3d-viewer/city/data/manifest.json'),terrainSha256:await hash('3d-viewer/city/data/terrain-mui-wo.json'),views:[],errors:[],failures:[]};
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});
page.on('pageerror',e=>report.errors.push(e.message));page.on('response',r=>{if(r.url().includes('/city/data/')&&r.status()>=400)report.failures.push({url:r.url(),status:r.status()});});
const settle=()=>page.waitForFunction(()=>{const s=window.__city?.state;return s&&!s.loadingTravel&&!s.travelling&&!s.stream.pending&&!s.regional.pending&&!s.bridges.pending;},null,{timeout:120000});
const tab=async name=>{if(!(await page.evaluate(()=>window.__city.state.controls.expanded)))await page.locator('#panel-toggle').click();await page.locator('#tab-'+name).click();};
const measure=()=>page.evaluate(async()=>{const a=[];let before;for(let i=0;i<140;i++){const now=await new Promise(requestAnimationFrame);if(i>20)a.push(now-before);before=now;}a.sort((a,b)=>a-b);return {samples:a.length,medianFrameMs:a[Math.floor(a.length*.5)],p95FrameMs:a[Math.floor(a.length*.95)],render:window.__city.state.render};});
async function frame(name,eye,target,time='15:00'){
 await tab('time');await page.locator('#time').fill(time);await page.locator('#panel-toggle').click();
 await page.evaluate(({eye,target})=>{const {camera,controls}=window.__muiWoCompletion;camera.position.fromArray(eye);controls.target.fromArray(target);controls.update();camera.updateMatrixWorld();},{eye,target});await settle();await page.waitForTimeout(500);
 const state=await page.evaluate(()=>window.__city.state);await page.screenshot({path:new URL(name+'.png',output).pathname});report.views.push({name,eye,target,time,state});
}
try{
 await page.route('**/city/app.js',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text())+'\nObject.defineProperty(window,"__muiWoCompletion",{get:()=>({stream,camera,controls,sampler,renderer,THREE,nav,bridgeLayer,terrain,water,environment})});\n'});});
 await page.goto('http://127.0.0.1:4176/city.html?district=muiwo');await page.waitForFunction(()=>window.__city?.ready,null,{timeout:120000});await page.locator('#loading').waitFor({state:'hidden'});await settle();
 report.initial=await page.evaluate(()=>window.__city.state);assert.equal(report.initial.counts.buildings,346115);
 await frame('overview-1440x1000',[-16050,780,2880],[-16950,10,2100]);
 await frame('waterfront-day-1440x1000',[-16380,150,2480],[-16515,4,2300]);
 await frame('waterfront-night-1440x1000',[-16380,150,2480],[-16515,4,2300],'22:00');
 await frame('wang-tong-1440x1000',[-16530,130,2140],[-16643,4.7,2040]);
 await frame('pak-ngan-heung-1440x1000',[-17300,180,1910],[-17400,25,1750]);
 await frame('tai-tei-tong-1440x1000',[-17210,160,2370],[-17400,8,2200]);
 await frame('luk-tei-tong-1440x1000',[-17150,160,2890],[-17300,10,2730]);
 report.performance=await measure();
 if(phase==='after'){
  const payload=JSON.parse(await readFile(new URL('source-scripts/city/mui-wo-completion/bridges-mui-wo.json',root))),expected=payload.models.map(m=>m.id);
  report.sourceIntegration=await page.evaluate(ids=>{const {stream,bridgeLayer,sampler}=window.__muiWoCompletion,all=[...stream.cache.entries.values()].flatMap(e=>e.data.buildings),rendered=[...bridgeLayer.cache.values()].flatMap(g=>g.userData.deckMeshes).flatMap(m=>[...new Set(m.geometry.attributes.bridgeFeature.array)].map(i=>bridgeLayer.features[i].id));return {models:[...bridgeLayer.surfaces.models.keys()].filter(id=>ids.includes(id)),visibleSourceIds:rendered.filter(id=>ids.includes(id)),buildingModels:new Set(all.filter(b=>b.modelGeometry).map(b=>b.uid)).size,mappedEstuary:sampler.mappedWater(-16551.2,2282),estuaryHeight:sampler.height(-16551.2,2282),stats:bridgeLayer.stats};},expected);
  assert.equal(report.sourceIntegration.models.length,10);assert.equal(new Set(report.sourceIntegration.visibleSourceIds).size,report.sourceIntegration.visibleSourceIds.length);assert.equal(report.sourceIntegration.buildingModels,1327);assert.equal(report.sourceIntegration.mappedEstuary,true);assert.equal(report.sourceIntegration.estuaryHeight,-4);
  await frame('wang-tong-source-view-1440x1000',[-16590,44,2098],[-16644,4.757,2045]);
  report.sourcePicking=await page.evaluate(()=>{const {camera,THREE,bridgeLayer,stream}=window.__muiWoCompletion,m=bridgeLayer.surfaces.models.get('landsd-infrastructure/I178581445403063C0'),p=m.modelGeometry.position;for(const t of m.walkTriangleIndices){const i=t*9,v=new THREE.Vector3((p[i]+p[i+3]+p[i+6])/3,(p[i+1]+p[i+4]+p[i+7])/3,(p[i+2]+p[i+5]+p[i+8])/3).project(camera),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(v.x,v.y),camera);const hit=ray.intersectObjects([...bridgeLayer.pickMeshes(),...stream.pickMeshes(ray.ray)])[0];if(hit&&bridgeLayer.featureAt(hit)?.id===m.id)return {id:m.id,click:[(v.x+1)*innerWidth/2,(1-v.y)*innerHeight/2]};}throw Error('Source Wang Tong floor cannot be picked');});await page.mouse.click(...report.sourcePicking.click);assert.equal(await page.locator('#building-height-label').textContent(),'DECK · HKPD');report.sourcePicking.card=await page.locator('#building-card').innerText();await page.screenshot({path:new URL('source-bridge-card-1440x1000.png',output).pathname});await page.locator('#selection-close').click();
  const arrivals=JSON.parse(await readFile(new URL('docs/astra-city/mui-wo-completion/arrivals-staged.json',root)));report.arrivals=[];
  for(const visit of arrivals.new){const id=visit.place.id;await tab('places');await page.locator('[data-region="lantau"]').click();await page.locator('[data-place="'+id+'"]').click();await settle();await page.locator('[data-mode="walk"]').click();await page.waitForFunction(()=>window.__city.state.mode==='walk'&&window.__city.state.movementReady,null,{timeout:90000});const before=await page.evaluate(()=>window.__city.state);assert.equal(before.collision,false);await page.evaluate(p=>{const n=window.__muiWoCompletion.nav;n.heading=Math.atan2(p[0]-n.position.x,-(p[1]-n.position.z));},visit.arrival.shortWalk.points.at(-1));await page.keyboard.down('w');try{await page.waitForFunction(d=>window.__city.state.distance>d+2,before.distance,{timeout:5000});}finally{await page.keyboard.up('w');}const after=await page.evaluate(()=>window.__city.state);report.arrivals.push({id,position:before.position,distanceMetres:after.distance-before.distance,collision:after.collision});assert.equal(after.collision,false);await page.locator('[data-mode="orbit"]').click();}
  const route=JSON.parse(await readFile(new URL('docs/astra-city/mui-wo-completion/route-navigation.json',root)));await page.addScriptTag({content:'window.__replayMuiWoRoute='+replayRoute.toString()+';'});
  report.continuousWalk=await page.evaluate(async points=>{const {nav,stream}=window.__muiWoCompletion;await stream.arrive(-17000,2200,3400);const forward=window.__replayMuiWoRoute(nav,points,{maxFrames:90000}),reverse=window.__replayMuiWoRoute(nav,points,{reverse:true,maxFrames:90000});return {forward,reverse};},route.walkCentreline);assert.equal(report.continuousWalk.forward.passed,true);assert.equal(report.continuousWalk.reverse.passed,true);await page.screenshot({path:new URL('continuous-walk-finish-1440x1000.png',output).pathname});await page.locator('[data-mode="orbit"]').click();
  await tab('places');await page.locator('[data-place="muiwo"]').click();await settle();await page.locator('[data-mode="fly"]').click();await page.waitForFunction(()=>window.__city.state.mode==='fly'&&window.__city.state.movementReady,null,{timeout:90000});const flightStart=await page.evaluate(()=>window.__city.state.position);await page.waitForTimeout(2000);const flightEnd=await page.evaluate(()=>window.__city.state);report.flight={start:flightStart,end:flightEnd.position,distanceMetres:Math.hypot(flightEnd.position[0]-flightStart[0],flightEnd.position[2]-flightStart[2]),collision:flightEnd.collision,aircraft:flightEnd.aircraft};assert.ok(report.flight.distanceMetres>30);assert.equal(report.flight.collision,false);await page.screenshot({path:new URL('flight-1440x1000.png',output).pathname});await page.locator('[data-mode="orbit"]').click();
  await page.setViewportSize({width:390,height:844});await frame('waterfront-mobile-390x844',[-16290,300,2630],[-16600,7,2310]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);report.mobilePerformance=await measure();
 }
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.failures,[]);report.result='passed';console.log(JSON.stringify({result:report.result,phase,views:report.views.length,performance:report.performance},null,2));
}catch(e){report.result='failed';report.error=e.stack;await page.screenshot({path:new URL('failure.png',output).pathname}).catch(()=>{});throw e;}finally{report.finished=new Date().toISOString();await writeFile(new URL('verification.json',output),JSON.stringify(report,null,2)+'\n');await browser.close();}
