/** Visible estimated public bridge approaches; original source geometry remains intact. */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import {makeTerrainSampler} from '../../../3d-viewer/city/geo.js';
import {prepareInfrastructure,InfrastructureSurfaces} from '../../../3d-viewer/city/infrastructure-data.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p))),hash=p=>createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');
const manifest=read('3d-viewer/city/data/manifest.json'),terrain=read('3d-viewer/city/data/terrain.json');
terrain.patches=(manifest.terrainPatches||[]).map(p=>read('3d-viewer/'+p.url));const sampler=makeTerrainSampler(terrain);
const source=JSON.parse(gunzipSync(fs.readFileSync(path.join(root,'source-scripts/city/tai-o-completion/infrastructure-models.json.gz')))),models=prepareInfrastructure(source),surfaces=new InfrastructureSurfaces();for(const m of models)if(m.name.startsWith('Tai Chung'))surfaces.add(m);
const bridges=read('3d-viewer/city/data/bridges.json'),way=bridges.bridges.find(b=>b.id==='way/48126232');
if(!way||way.tags.highway!=='pedestrian'||way.tags['name:en']!=='Tai O Wing On Street')throw new Error('Mapped public approach changed; re-review');
const distances=[0];for(let i=1;i<way.path.length;i++)distances.push(distances.at(-1)+Math.hypot(way.path[i][0]-way.path[i-1][0],way.path[i][1]-way.path[i-1][1]));
function along(d){let i=1;while(i<distances.length-1&&distances[i]<d)i++;const t=(d-distances[i-1])/(distances[i]-distances[i-1]);return way.path[i-1].map((v,k)=>v+(way.path[i][k]-v)*t);}
const y0=surfaces.heights(...way.path[0])[0];if(!Number.isFinite(y0))throw new Error('No source deck at mapped bridge entry');
let lo=0,hi=distances[1];for(let i=0;i<60;i++){const mid=(lo+hi)/2;if(surfaces.heights(...along(mid)).length)lo=mid;else hi=mid;}
const end=way.path.at(-1),endY=sampler.height(...end),length=distances.at(-1),exit=(lo+hi)/2;
// The source OSM shortcut intersects a real bridge railing. The documented
// public connector uses the mesh's existing southeast opening; source stays intact.
const connector=read('source-scripts/city/tai-o-completion/route-entry.json');
const [street,landing,stairTop,deckInside]=connector.approach,landingY=3.2,steps=4,rise=(y0-landingY)/steps,stairLength=Math.hypot(stairTop[0]-landing[0],stairTop[1]-landing[1]),run=stairLength/steps;
const pointAt=(t,y)=>[landing[0]+(stairTop[0]-landing[0])*t,y,landing[1]+(stairTop[1]-landing[1])*t];
const landingLead=.8,streetSpan=Math.hypot(street[0]-landing[0],street[1]-landing[1]),landingBefore=landing.map((v,i)=>v+(street[i]-v)*landingLead/streetSpan);
const points=[[end[0],endY,end[1]],[street[0],2.6,street[1]],[landingBefore[0],landingY,landingBefore[1]],[landing[0],landingY,landing[1]]];
for(let k=1;k<=steps;k++)points.push(pointAt((k-1)/steps,landingY+k*rise),pointAt(k/steps,landingY+k*rise));
points.push([deckInside[0],y0,deckInside[1]]);points.reverse();
const landingStart=0,landingEnd=stairLength;
const width=1.5,coords=points.map(p=>[p[0],p[2]]),record={id:'tai-o-access/way/48126232',source:way.source,sourceId:way.id,name:'Tai Chung Bridge / Wing On Street approach',zh:'大涌橋／永安街連接通道',kind:'steps',role:'access',estimatedPublicApproach:true,deckPath:points,width,bounds:[Math.min(...coords.map(p=>p[0]))-width,Math.min(...coords.map(p=>p[1]))-width,Math.max(...coords.map(p=>p[0]))+width,Math.max(...coords.map(p=>p[1]))+width],walkable:true,publicAccessSource:models[0].publicAccessSource,estimatedElevation:true,elevationBasis:'Illustrative public access to the existing southeast mesh opening: four estimated risers link a 3.2 m landing to the source 4.058 m deck; the street end meets current terrain. Original source deck and all railings remain unchanged. Horizontal connector and stair dimensions are estimated, with the OSM/plan/mesh disagreement recorded in route-entry.json.',widthBasis:'1.5 m illustrative pedestrian width; no surveyed width is available for this mapped centreline.',sourceTags:way.tags,sourceNodes:way.nodes,sourcePath:way.path,anchors:{sourceModelId:models[0].id,sourceDeckHeightHKPD:y0,sourceDeckBoundaryDistance:null,sourceDeckBoundary:connector.sourceDeckEntry,publicConnector:connector,terrainEndpoint:[end[0],endY,end[1]],estimatedStairs:{risers:steps,riseMetres:rise,runMetres:run,landingHeightHKPD:landingY,levelLandingBeforeStairsMetres:landingLead,stairBottom:[landing[0],landingY,landing[1]],stairTop:[stairTop[0],y0,stairTop[1]],clearanceReference:'Exact source building and bridge triangles with 1.8 m actor and 0.55 m collision radius; public entry through the existing mesh opening.'},profileHorizontalLengthMetres:points.slice(1).reduce((sum,p,i)=>sum+Math.hypot(p[0]-points[i][0],p[2]-points[i][2]),0)},heightDatum:'Hong Kong Principal Datum',approximation:true};
const route=read('docs/astra-city/tai-o-completion/route.json'),marketIndex=route.nodeIds.indexOf(611687203),marketStart=route.centreline[marketIndex],marketEnd=route.centreline[marketIndex+1],marketWay=bridges.bridges.find(b=>b.id==='way/377823160');
if(!marketWay||route.nodeIds[marketIndex+1]!==4971471802)throw new Error('Market public source edge changed');
const marketY=surfaces.heights(...marketStart)[0],marketGround=sampler.height(...marketEnd),marketLength=Math.hypot(marketEnd[0]-marketStart[0],marketEnd[1]-marketStart[1]);
const marketAt=d=>marketStart.map((v,i)=>v+(marketEnd[i]-v)*d/marketLength);
let marketLo=0,marketHi=marketLength;for(let i=0;i<60;i++){const mid=(marketLo+marketHi)/2;if(surfaces.heights(...marketAt(mid)).length)marketLo=mid;else marketHi=mid;}
const marketExit=(marketLo+marketHi)/2,marketFlat=Math.min(marketLength,marketExit+.8),marketMid=marketAt(marketFlat),marketPath=[[marketStart[0],marketY,marketStart[1]],[marketMid[0],marketY,marketMid[1]],[marketEnd[0],marketGround,marketEnd[1]]];
const marketRecord={...record,id:'tai-o-access/way/377823160',source:marketWay.source,sourceId:marketWay.id,name:'Tai Chung Bridge / Market Street landing',zh:'大涌橋／街市街連接通道',kind:'ramp',deckPath:marketPath,bounds:[Math.min(marketStart[0],marketEnd[0])-width,Math.min(marketStart[1],marketEnd[1])-width,Math.max(marketStart[0],marketEnd[0])+width,Math.max(marketStart[1],marketEnd[1])+width],sourceTags:marketWay.tags,sourceNodes:[611687203,4971471802],sourcePath:[marketStart,marketEnd],elevationBasis:'Illustrative short landing along the unchanged public Market Street source edge: extend the original 2.629 m deck level beyond its cut edge, then meet the current rendered ground. Neither approach elevation nor width is a surveyed accessibility specification.',anchors:{sourceModelId:models[0].id,sourceDeckHeightHKPD:marketY,sourceDeckBoundaryDistance:marketExit,sourceDeckBoundary:marketAt(marketExit),terrainEndpoint:marketPath.at(-1),overallGrade:Math.abs(marketY-marketGround)/(marketLength-marketFlat)}};
const output={schemaVersion:1,kind:'tai-o-estimated-public-access',records:[record,marketRecord],canopyEstimates:[169618,182398].map(id=>({uid:`landsd/${id}:0`,base:y0,height:3,buildingCSUID:id===169618?'0384112815T20080111':'0383712816T20100126',heightSource:'estimated',baseSource:'source-deck-clearance-estimate',heightRule:'tai-o-deck-canopy-clearance',requiredSourceFields:{structureType:'Open-sided Structure',baseHeightHKPD:null,topHeightHKPD:null},source:'source-scripts/city/tai-o-completion/hydro-sources/9-SW-23B.zip',sourceEntry:'9-SW-23B/Layers/Buildings/Building.gml',buildingId:id===169618?1109176709:1109182593,lastUpdateDate:'20260729',note:'Keep the current source-confirmed canopy footprint and raw NULL elevations; its estimated roof is 3 m above the verified bridge deck instead of 3 m above the lower terrain. This clearance/roof elevation is illustrative, not surveyed.'})),sources:{bridges:{path:'3d-viewer/city/data/bridges.json',sha256:hash('3d-viewer/city/data/bridges.json')},sourceMesh:{path:'source-scripts/city/tai-o-completion/infrastructure-models.json.gz',sourceEntryHashes:models[0].modelGeometry.sourceHashes},terrain:[{path:'3d-viewer/city/data/terrain.json',sha256:hash('3d-viewer/city/data/terrain.json')},...(manifest.terrainPatches||[]).map(p=>({path:'3d-viewer/'+p.url,sha256:hash('3d-viewer/'+p.url)}))]},limits:['The existing cartographic street centreline differs from nearby mapped step lines; this is a visible simulation profile, not an exact reconstruction of those steps.','No raw source building heights or source mesh positions are changed.','Route clearance and actual city walking remain subject to root integration/browser acceptance.']};
fs.writeFileSync(path.join(root,'source-scripts/city/tai-o-completion/infrastructure-access.json'),JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify(record.anchors,null,2));

const moduleText='// Generated by source-scripts/city/tai-o-completion/infrastructure-access.mjs.\n// Scoped estimated canopy clearance; original records and NULL source elevations stay intact.\nexport const TAI_O_CANOPY_ESTIMATES = '+JSON.stringify(output.canopyEstimates,null,2)+';\nconst byUid=new Map(TAI_O_CANOPY_ESTIMATES.map(e=>[e.uid,e]));\nexport function taiOCanopyEstimate(building){\n const e=byUid.get(building.uid);\n return e&&building.buildingCSUID===e.buildingCSUID&&building.structureType===e.requiredSourceFields.structureType&&building.baseHeightHKPD===null&&building.topHeightHKPD===null&&building.heightSource==="estimated"&&!building.modelGeometry?e:null;\n}\n';
fs.writeFileSync(path.join(root,'3d-viewer/city/tai-o-estimates.js'),moduleText);
