/** Rebuild public statistics without credentials or network access. */
import {readFileSync,writeFileSync,existsSync} from 'node:fs';import{createHash}from'node:crypto';import{resolve,dirname}from'node:path';import{fileURLToPath}from'node:url';import{countCoverage}from'./counts.mjs';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..'),inputs={},hash=b=>createHash('sha256').update(b).digest('hex'),read=p=>{const b=readFileSync(resolve(root,p));inputs[p]=hash(b);return JSON.parse(b);};
const manifest=read('city/data/manifest.json'),snapshot=read('scripts/building-progress/review-proof.json'),forms=[],models=[],suppressed=[];
for(const t of manifest.tiles){for(const b of read(t.url).buildings){forms.push({uid:b.uid});if(b.modelGeometry){const proof=snapshot.embedded.find(p=>p.uid===b.uid&&p.runtimeDigest===hash(JSON.stringify(b.modelGeometry)));if(proof)models.push({uid:b.uid,sha256:proof.sourceSHA256});}}}
for(const url of manifest.officialModelCatalogues||[]){for(const m of read(url).models){const asset=resolve(root,dirname(url),m.asset);if(!existsSync(asset)||hash(readFileSync(asset))!==m.sha256)throw Error('Deployed native asset unavailable/hash mismatch: '+m.uid);models.push(m);}}
// Bridge source models can replace misclassified building footprints.
function scan(v){if(!v||typeof v!=='object')return;if(Array.isArray(v.suppressesBuildingUids))suppressed.push(...v.suppressesBuildingUids);for(const value of Object.values(v))if(typeof value==='object')scan(value);}
for(const source of manifest.bridgeModels||[]){const url=typeof source==='string'?source:source.url;if(url)scan(read(url));}
const counts=countCoverage({forms,models,reviews:snapshot.rows,suppressed}),manifestDigest=hash(JSON.stringify(manifest)),inputDigest=hash(JSON.stringify(inputs)),output={version:1,status:'available',...counts,updatedAt:snapshot.capturedAt,reviewSnapshot:snapshot.snapshotId,manifestDigest,inputDigest,source:'Hong Kong Lands Department and retained OpenStreetMap forms',countingNote:'Distinct deployed source-form IDs. A physical building may contain several forms. Reviewed detail means installed native geometry with a matching verified source hash; it does not mean surveyed textures or complete regional validation.',reviewPolicy:'Held, pending, candidate and changed-source models are excluded. Camera visibility and level of detail do not affect these citywide figures.'};
const path=resolve(root,'city/data/building-progress.json');writeFileSync(path,JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify(counts));
