/** Actual app acceptance; run before and after the guarded publisher. */
import {createRequire} from 'node:module';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(new URL('../../../3d-viewer/city/package.json',import.meta.url)),{chromium}=require('playwright');
const root=new URL('../../../',import.meta.url),read=async p=>JSON.parse(await readFile(new URL(p,root),'utf8'));
const phase=process.argv[2]||'before',after=phase==='after';assert.ok(['before','after'].includes(phase));
const out=new URL(`docs/astra-city/island-detail-integration/browser/${phase}${process.env.EXTRA?'-extra':''}/`,root);await mkdir(out,{recursive:true});
const groups=[];for(const [area,place] of [['mui-wo','muiwo'],['tai-o','taio'],['pui-o','puio']]){const c=await read(`source-scripts/city/${area}-detail-completion/compact/catalogue.json`);let selected=c.models;if(area==='mui-wo'){const perSheet=new Map();for(const m of c.models)if(!perSheet.has(m.sourceTile))perSheet.set(m.sourceTile,m);const all=[...perSheet.values()];selected=[all[0],all[Math.floor(all.length*.25)],all[Math.floor(all.length*.5)],all[Math.floor(all.length*.75)],all.at(-1)];}if(area==='mui-wo'){const extra=c.models.filter(m=>['landsd/202951:0','landsd/206970:0','landsd/208041:0'].includes(m.uid));selected=process.env.EXTRA?extra:[...selected,...extra];if(after){const approved=await read('source-scripts/city/mui-wo-detail-completion/publication/catalogue.json'),ids=new Set(approved.models.map(m=>m.uid));selected=selected.filter(m=>ids.has(m.uid));}}if(!process.env.AREA||process.env.AREA===area)groups.push({area,place,models:c.models,selected});}
const needed=new Set(groups.flatMap(g=>g.selected.map(m=>m.uid))),buildings=new Map(),manifest=await read('3d-viewer/city/data/manifest.json');
for(const tile of manifest.tiles){const d=await read('3d-viewer/'+tile.url);for(const b of d.buildings)if(needed.has(b.uid))buildings.set(b.uid,b);}
assert.equal(buildings.size,needed.size);
const report={phase,result:'running',started:new Date().toISOString(),areas:[],errors:[],limits:['Representative Mui Wo source sheets plus all eleven Tai O/Pui O additions tested in browser; every added source asset separately has decoder/picking/collision checks.','Mobile viewport emulation on desktop Chrome; physical-phone performance unverified.']};
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--enable-webgl','--ignore-gpu-blocklist']});let page;
async function open(place,width=1440,failedModel){
 const p=await browser.newPage({viewport:{width,height:width===1440?1000:844},deviceScaleFactor:1,reducedMotion:'reduce',hasTouch:width<760});
 p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(/THREE.WebGLProgram|GL_INVALID|shader error/i.test(m.text()))report.errors.push(m.text());});
 await p.route('**/city/app.js',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text())+'\nObject.defineProperty(window,"__detailReview",{get:()=>({officialModels,stream,camera,controls,renderer,sampler,THREE,nav,terrain,water,environment,visitBuilding,closeSelection,controlSheet,goPlace})});\n'});});
 let fail=!!failedModel;if(failedModel)await p.route('**/'+failedModel.modelId+'.glb.gz',r=>fail?r.abort('failed'):r.continue());
 await p.goto('http://127.0.0.1:4176/city.html?district='+place);await p.waitForFunction(()=>window.__city?.ready,null,{timeout:180000});await p.locator('#loading').waitFor({state:'hidden',timeout:180000});await p.waitForFunction(()=>!window.__city.state.loadingTravel&&!window.__city.state.travelling,null,{timeout:120000});return {page:p,recover:()=>{fail=false;}};
}
async function focus(p,m,failed=false){
 const b=buildings.get(m.uid);await p.evaluate(b=>window.__detailReview.visitBuilding(b),b);await p.waitForFunction(()=>!window.__city.state.loadingTravel&&!window.__city.state.travelling,null,{timeout:120000});
 const [a,bounds]=m.worldBounds,centre=a.map((v,i)=>(v+bounds[i])/2),distance=Math.max(30,(bounds[0]-a[0])*1.8,(bounds[2]-a[2])*1.8);
 await p.evaluate(({centre,top,distance})=>{const r=window.__detailReview;r.closeSelection();r.controlSheet.close({restoreFocus:false});r.camera.position.set(centre[0]+distance*.7,top+distance*.75,centre[2]+distance);r.controls.target.fromArray(centre);r.controls.update();r.camera.updateMatrixWorld(true);},{centre,top:bounds[1],distance});
 if(after)await p.waitForFunction(({uid,failed})=>failed?window.__detailReview.officialModels.cache.errors.has(uid):window.__detailReview.stream.detailedModels.get(uid)?.active,{uid:m.uid,failed},{timeout:120000});
 await p.waitForTimeout(500);
}
async function proof(p,m){return p.evaluate(uid=>{const r=window.__detailReview,e=r.stream.detailedModels.get(uid),b=r.stream.getLoadedBuilding(uid),ray=new r.THREE.Raycaster(new r.THREE.Vector3(b.centre[0],3000,b.centre[1]),new r.THREE.Vector3(0,-1,0));const terrainHits=ray.intersectObject(r.terrain,true).map(h=>h.point.y);let contact=null,pick=null;if(e){const pos=e.record.modelGeometry.position,order=e.record.modelGeometry.index;for(let i=0;i<order.length;i+=3){const ids=[order[i],order[i+1],order[i+2]],q=[0,1,2].map(k=>ids.reduce((s,j)=>s+pos[j*3+k],0)/3);if(r.stream.collision(q[0],q[2],q[1]-.05,q[1]+.05,.05)?.uid===uid){contact=q;break;}}const meshes=e.meshes;for(const mesh of meshes){const a=mesh.geometry.attributes.position;mesh.updateMatrixWorld(true);for(let i=0;i<a.count;i+=Math.max(1,Math.floor(a.count/70))){const v=new r.THREE.Vector3().fromBufferAttribute(a,i).applyMatrix4(mesh.matrixWorld);const caster=new r.THREE.Raycaster(v.clone().add(new r.THREE.Vector3(0,1000,0)),new r.THREE.Vector3(0,-1,0));const h=caster.intersectObjects(r.stream.pickMeshes(caster.ray))[0];if(h&&r.stream.featureAt(h)?.uid===uid){pick=uid;break;}}if(pick)break;}}
 return {uid,active:!!e?.active,modelId:e?.record.modelId,visible:!!e?.group.visible,recordedBase:b.baseHeightHKPD??null,recordedTop:b.topHeightHKPD??null,ground:r.sampler.height(...b.centre),terrainHits,resolution:r.sampler.resolutionAt(...b.centre),contact,pick,stats:r.officialModels.stats,render:window.__city.state.render};},m.uid);}
function budget(s){for(const k of ['geometryBytes','residentBytes','triangles'])assert.ok(s[k]<=s.limits[k],k);assert.ok(s.cached<=s.limits.count);assert.deepEqual(s.errors,[]);}
async function time(p,value){await p.evaluate(value=>{const input=document.getElementById('time');input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));window.__detailReview.controlSheet.close({restoreFocus:false});},value);await p.waitForTimeout(150);}
const snap=(p,name)=>p.screenshot({path:new URL(name+'.png',out).pathname});
const measure=p=>p.evaluate(async()=>{const values=[];let last;for(let i=0;i<90;i++){const n=await new Promise(requestAnimationFrame);if(i>10)values.push(n-last);last=n;}values.sort((a,b)=>a-b);return {median:values[Math.floor(values.length*.5)],p95:values[Math.floor(values.length*.95)]};});
try{
 for(const g of groups){const area={area:g.area,models:[],views:[]};report.areas.push(area);({page}=await open(g.place));for(const m of g.selected){await focus(page,m);const q=await proof(page,m);if(after){assert.equal(q.active,true);assert.equal(q.modelId,m.modelId);assert.equal(q.recordedBase,m.recordedBaseHeight);assert.equal(q.recordedTop,m.recordedTopHeight);assert.ok(q.contact);assert.equal(q.pick,m.uid);budget(q.stats);assert.ok(Math.abs(q.terrainHits[0]-q.ground)<.03,'render/sampler agreement');}area.models.push(q);const name=g.area+'-'+m.uid.replace(/\W/g,'-');await time(page,'15:00');await snap(page,name+'-day');area.views.push(name+'-day');}const last=g.selected.at(-1);await time(page,'22:00');await snap(page,g.area+'-night');area.performance=await measure(page);if(after){await page.evaluate(place=>window.__detailReview.goPlace(place,false),g.place);await page.waitForFunction(()=>!window.__city.state.loadingTravel&&!window.__city.state.travelling,null,{timeout:120000});await page.locator('[data-mode="walk"]').click();await page.waitForFunction(()=>window.__city.state.mode==='walk'&&window.__city.state.movementReady,null,{timeout:120000});area.walkArrival=await page.evaluate(()=>({position:window.__city.state.position,collision:window.__city.state.collision}));assert.equal(area.walkArrival.collision,false);await page.locator('#fly-toggle').click();await page.locator('[data-aircraft="prop"]').click();await page.waitForFunction(()=>window.__city.state.mode==='fly'&&window.__city.state.movementReady,null,{timeout:120000});const start=await page.evaluate(()=>window.__city.state.position);await page.waitForTimeout(1200);area.flight=await page.evaluate(()=>({position:window.__city.state.position,collision:window.__city.state.collision}));area.flight.distance=Math.hypot(area.flight.position[0]-start[0],area.flight.position[2]-start[2]);assert.ok(area.flight.distance>5);assert.equal(area.flight.collision,false);}await page.close();if(after){({page}=await open(g.place,390));await focus(page,last);await time(page,'22:00');area.mobile=await proof(page,last);assert.ok(area.mobile.active);budget(area.mobile.stats);assert.equal(area.mobile.stats.profile,'mobile');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await snap(page,g.area+'-mobile-night');area.mobilePerformance=await measure(page);await page.close();}}
 if(after){const g=groups[2],m=g.selected.find(m=>m.uid==='landsd/75329:0')||g.selected[0],failure=await open(g.place,1440,m);page=failure.page;await focus(page,m,true);assert.equal(await page.evaluate(uid=>!!window.__detailReview.stream.detailedModels.get(uid)?.active,m.uid),false);failure.recover();await page.locator('#stream-retry').click();await page.waitForFunction(uid=>window.__detailReview.stream.detailedModels.get(uid)?.active,m.uid,{timeout:120000});report.retry=await proof(page,m);assert.ok(report.retry.active);await page.close();}
 assert.deepEqual(report.errors,[]);report.result='passed';
}catch(e){report.result='failed';report.failure=e.stack;if(page&&!page.isClosed())await snap(page,'failure').catch(()=>{});throw e;}finally{report.finished=new Date().toISOString();await writeFile(new URL('verification.json',out),JSON.stringify(report,null,2)+'\n');await browser.close();}
console.log(JSON.stringify({result:report.result,areas:report.areas.map(a=>({area:a.area,models:a.models.length,performance:a.performance,mobilePerformance:a.mobilePerformance}))}));
