/** Source-triangle collider accounting for a small structure in the native depot assembly. */
import assert from 'node:assert/strict';
import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import * as THREE from '../../../3d-viewer/vendor/three.module.js';import{nearest}from'../assembly-support-review/triangles.mjs';import{BuildingIndex}from'../../../3d-viewer/city/geo.js';import{prepareModelCatalogue,loadOfficialModel,disposeOfficialModel}from'../../../3d-viewer/city/official-model-assets.js';
const root=new URL('../../../',import.meta.url),read=p=>JSON.parse(readFileSync(new URL(p,root))),manifest=read('3d-viewer/city/data/manifest.json'),uids=['landsd/268527:0','landsd/324455:0'],entries=new Map(),records=new Map(),models=new Map();
for(const path of manifest.officialModelCatalogues.map(p=>'3d-viewer/'+p))for(const e of prepareModelCatalogue(read(path),'http://review.local/'+path))if(uids.includes(e.uid))entries.set(e.uid,{e,dir:path.slice(0,path.lastIndexOf('/')+1)});
for(const tile of manifest.tiles)for(const b of read('3d-viewer/'+tile.url).buildings)if(uids.includes(b.uid))records.set(b.uid,b);
const lighting={night:{value:1},activity:{value:new THREE.Vector4(1,1,1,1)},retail:{value:1},elapsed:{value:0},shimmer:{value:0}};
for(const uid of uids){const{e,dir}=entries.get(uid),raw=readFileSync(new URL(dir+e.asset,root));if(createHash('sha256').update(raw).digest('hex')!==e.sha256)throw Error('Source hash mismatch');models.set(uid,await loadOfficialModel(e,records.get(uid),lighting,{fetcher:async()=>new Response(raw)}));}
const target=models.get(uids[0]).record,depot=models.get(uids[1]).record,individual=new BuildingIndex([target]),other=new BuildingIndex([depot]),depotFirst=new BuildingIndex([depot,target]),targetFirst=new BuildingIndex([target,depot]),{position,index}=target.modelGeometry,rows=[];
const depotSurface={faces:[]},dp=depot.modelGeometry.position,di=depot.modelGeometry.index;for(let i=0;i<di.length;i+=3)depotSurface.faces.push(new THREE.Triangle(...[di[i],di[i+1],di[i+2]].map(j=>new THREE.Vector3().fromArray(dp,j*3))));
for(let i=0;i<index.length;i+=3){const point=[0,1,2].map(k=>(position[index[i]*3+k]+position[index[i+1]*3+k]+position[index[i+2]*3+k])/3),query=b=>b.collision(point[0],point[2],point[1]-.05,point[1]+.05,.05)?.uid||null;rows.push({triangle:i/3,point,depotSurfaceDistance:nearest(depotSurface,new THREE.Vector3(...point)),individual:query(individual),depot:query(other),depotFirst:query(depotFirst),targetFirst:query(targetFirst)});}
const count=key=>Object.fromEntries([...new Set(rows.map(r=>r[key]))].map(v=>[String(v),rows.filter(r=>r[key]===v).length])),report={issue:'HKS-214',sourceModels:uids.map(uid=>({uid,sha256:entries.get(uid).e.sha256,modelId:entries.get(uid).e.modelId,worldBounds:entries.get(uid).e.worldBounds})),triangles:rows.length,counts:Object.fromEntries(['individual','depot','depotFirst','targetFirst'].map(k=>[k,count(k)])),surfaceCoincidence:{within5cm:rows.filter(r=>r.depotSurfaceDistance<=.05).length,min:Math.min(...rows.map(r=>r.depotSurfaceDistance)),max:Math.max(...rows.map(r=>r.depotSurfaceDistance))},uniqueTargetContacts:rows.filter(r=>r.individual&&!r.depot).length,rows,published:false};assert.equal(rows.filter(r=>r.individual===uids[0]).length,100,'All actual target triangle contacts remain solid');assert.equal(rows[32].depot,null,'No ghost depot volume ten metres above its local roof');assert.equal(rows[32].depotFirst,uids[0],'Scene collision reaches the actual ancillary roof');report.status='passed';writeFileSync(new URL(process.argv[2]||'docs/astra-city/residential-support-review/collision-surface-268527.json',root),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,rows:undefined},null,2));for(const m of models.values())disposeOfficialModel(m);
