"""Versioned supplemental preflight and explicit reservations for omitted-source support review."""
import pathlib,json,sys,hashlib
ROOT=pathlib.Path(__file__).resolve().parents[3];HERE=pathlib.Path(__file__).resolve().parent;DOC=ROOT/'docs/astra-city/residential-support-review'
read=lambda p:json.loads(p.read_bytes())
def save(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
preflight=read(ROOT/'docs/astra-city/landmark-preflight/report.json');discovery=read(DOC/'support-discovery.json');newcat=read(HERE/'omitted-support/candidates/catalogue.json');lohas=read(HERE/'candidates/catalogue.json');newcat['models']+=[m for m in lohas['models']if m['uid']=='landsd/54170:0'];newcat['counts']['packedModels']=len(newcat['models'])
# Exact declared source references; proposed estate membership is not silently accepted.
byuid={r['uid']:r for r in discovery['targets']};old={r['uid']:r for r in preflight['parts']};new=[]
for m in newcat['models']:
 d=byuid[m['uid']];links=d['targets'];new.append({'uid':m['uid'],'objectId':m['objectId'],'name':m['label'],'csuid':m['buildingCSUID'],'candidate':m,'sourceState':'candidate-staged','sourceProgress':'prepared-for-review','knownHold':None,'identityProposalGroups':[],'landmarkIds':[],'supportForUids':sorted(t['uid']for t in links),'relatedLandmarkIds':sorted({v for t in links for v in old[t['uid']]['landmarkIds']}),'classification':['elevated-component-support-context','foundation-burial-context'],'classificationQualification':'Routing labels only; loader/terrain/triangle review has not yet accepted placement.','publicationApproved':False,'sourceAppendVersion':1})
unprepared=[]
packing={r['uid']:r for r in read(DOC/'omitted-support/packing.json')['results']};acquired={r['uid']:r for r in read(DOC/'omitted-support/report.json')['rows']}
for d in discovery['targets']:
 if d['uid'] in {p['uid']for p in new}:continue
 existing=old.get(d['uid']);a=acquired.get(d['uid']);packed=packing.get(d['uid']);absent=a and a['outcome']=='no-exact-model-in-complete-checked-sheets'
 unprepared.append({'uid':d['uid'],'objectId':d['objectId'],'name':d['name'],'csuid':d['csuid'],'candidate':None,'sourceState':'source-unavailable-checked'if absent else 'source-acquired-match-held','sourceProgress':'source-checked-unavailable'if absent else 'source-match-held','classification':['checked-source-absence'if absent else 'source-matching-hold'],'landmarkIds':existing['landmarkIds']if existing else [],'identityProposalGroups':existing['identityProposalGroups']if existing else [],'supportForUids':sorted(t['uid']for t in d['targets']),'relatedLandmarkIds':sorted({v for t in d['targets']for v in old[t['uid']]['landmarkIds']}),'acquisitionOutcome':a['outcome']if a else 'delegated-existing-source','packingOutcome':packed['outcome']if packed else 'delegated-incomplete-podium-coverage','evidence':'docs/astra-city/residential-support-review/omitted-support/report.json'if a else 'docs/astra-city/identity-hold-review/decisions.json','publicationApproved':False,'existingPreflightUID':d['uid']in old})
exclude={'landsd/'+str(u)+':0'for u in [232804,242294,244779,263404,322191,324716,337475,103538,176291,176748,257313]};affected={t['uid']for d in discovery['targets']for t in d['targets']}-exclude;selected=[old[u]for u in sorted(affected)]+new;uids={p['uid']for p in selected};assert len(uids)==len(selected)
save(HERE/'support-catalogue.json',newcat);save(HERE/'supplemental-preflight.json',{'issue':'HKS-214','version':1,'baseSnapshotId':preflight['snapshotId'],'parts':new+unprepared,'preparedCount':len(new),'unpreparedCount':len(unprepared),'published':False,'qualification':'New exact government source parts appended to the model review inventory; related landmarks are contextual links, not asserted component membership.'});save(DOC/'supplemental-preflight.json',read(HERE/'supplemental-preflight.json'));save(HERE/'review-input.json',{'snapshotId':preflight['snapshotId'],'parts':selected});save(HERE/'review-selection.json',sorted(uids));save(DOC/'support-batch.json',{'oldAffectedParts':len(affected),'supplementalParts':len(new),'selectedParts':len(uids),'excludedConcurrentUids':sorted(exclude),'deferredAcquisitionUid':'landsd/235988:0','deferredReason':'Already acquired and owned by identity review; full replacement held for37.22% footprint coverage.'})
sys.path.insert(0,str(ROOT/'source-scripts/city/shared-modelling'));import reservations
# Three LOHAS towers and one podium already have independent current receipts.
existing=set()
for path in ['/tmp/astra-residential-support-lease.json','/tmp/astra-residential-podium-lease.json']:
 lease=read(pathlib.Path(path));assert reservations.owns(lease);existing.update(lease['resources'])
keys=sorted({'building:'+u for u in uids}-existing);receipt=pathlib.Path('/tmp/astra-omitted-support-review-lease.json');result=reservations.claim('omitted-support-review-session-20260909',keys,batch='HKS-214-omitted-support-review-v1');assert result['ok'],result;receipt.write_text(json.dumps(result['reservation'],default=str,indent=2)+'\n');print(json.dumps({'old':len(affected),'new':len(new),'total':len(uids),'reserved':len(keys)}))
