"""Reuse parent-aligned native-TIN proposal pipeline for the single LOHAS podium."""
import importlib.util,pathlib,sys,json
ROOT=pathlib.Path(__file__).resolve().parents[3];HERE=pathlib.Path(__file__).resolve().parent;DOC=ROOT/'docs/astra-city/residential-support-review'
sys.path.insert(0,str(ROOT/'source-scripts/city/shared-modelling'));import reservations
assert reservations.owns(json.loads(pathlib.Path('/tmp/astra-residential-podium-lease.json').read_text()))
sys.path.insert(0,str(ROOT/'source-scripts/city/roof-occlusion-review'))
s=importlib.util.spec_from_file_location('existing_roof_prepare',ROOT/'source-scripts/city/roof-occlusion-review/prepare.py');p=importlib.util.module_from_spec(s);s.loader.exec_module(p);p.H=HERE;p.D=DOC
# Reuse the reviewed multi-primitive native terrain decoder in this process only.
ns=importlib.util.spec_from_file_location('multi_native',ROOT/'source-scripts/city/assembly-support-review/native_terrain.py');multi=importlib.util.module_from_spec(ns);ns.loader.exec_module(multi);p.shared.shared.terrain_index=multi.terrain_index
uid='landsd/54170:0';b=next(b for b in p.read(ROOT/'3d-viewer/city/data/tiles/5_-1.json')['buildings']if b['uid']==uid);candidate=next(m for m in p.read(HERE/'candidates/catalogue.json')['models']if m['uid']==uid);tm=HERE/'native-terrain/staged/12-SW-1D/manifest.json';m=p.read(tm);sm=HERE/'staged/12-SW-1D/manifest.json';spec=next(s for s in p.read(sm)['models']if s['id']==candidate['modelId']);terrain=p.read(ROOT/'3d-viewer/city/data/terrain.json');manifest=p.read(ROOT/'3d-viewer/city/data/manifest.json');children=[p.read(ROOT/'3d-viewer'/v['url'])for v in manifest['terrainPatches']];poly=p.Polygon(b['rings'][0],b['rings'][1:]);_,_,_,_,usable,tree=p.shared.shared.terrain_index(tm.parent);native,_,_=p.shared.shared.shared_audit.source_piece_audit(poly,candidate['worldBounds'][1][1],(usable,tree))
row={'uid':uid,'name':b['name'],'buildingRecord':b,'modelBounds':candidate['worldBounds'],'terrainManifest':str(tm.relative_to(ROOT)),'terrainManifestSha256':p.sha(tm),'terrainSourceHashes':m['terrain']['sourceHashes'],'currentRenderedTerrain':p.shared.extrema(poly,terrain,children),'nativeTIN':native,'sourceFootprintArea':poly.area,'modelSourceManifest':str(sm.relative_to(ROOT)),'modelSourceManifestSha256':p.sha(sm),'modelSourceHashes':spec['sourceHashes']};p.save(DOC/'audit.json',{'issue':'HKS-214','rootTerrainSha256':p.sha(ROOT/'3d-viewer/city/data/terrain.json'),'rows':[row]});p.main()
